### ISSUE TITLE
look into why open source projects think they are pending approval

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1009]
happened twice already

**Comment by piamancini** [comment]
from user:
> I create collective with GutHub account but can't login with my email - user not exists
> then I signup - result - doubled account (with usernames: restmount and restmount1)

this happened because we fetch the github non-reply email.
@asood123 I thought we changed it so user could add the email?

If we can't avoid fetching the non-reply email an option can be surfacing the email for user to confirm/change?

This is frustrating for users and also we get duplicate collectives because they never receive any notification

cc / @xdamman any thoughts?

**Comment by asood123** [comment]
Our flow doesn't let user enter email, as far as I remember. We pull it from GitHub. We can blacklist emails with `noreply` in them.

**Comment by piamancini** [comment]
ok. If we do that, then what happens when email is hidden?

**Comment by piamancini** [comment]
ok, let's try that.

**Comment by luceos** [comment]
To add to this, OC used the first email on my account. So the one I registered with, even though my email address marked Primary was not:

![image](https://user-images.githubusercontent.com/504687/39444004-907754fc-4cb6-11e8-9e87-c11a350a7b9d.png)

**Comment by piamancini** [comment]
@luceos is this for your new collective? 
happy to change the admins for you.

**Comment by luceos** [comment]
Maybe to clarify a bit further. Because it might not seem obvious. 

You assume that simply blacklisting will solve this, it will not. The problem is that OC will pull the **first** email address provided by the API from GitHub. This is often a very old address and might no longer work. My guess is the users that do not see the confirmation emails experienced the same; their first email address was automatically picked, even though it was not marked as "primary" and as such it no longer worked. It might have still been in the list to match Git commits though.

Just imagine you signed up on GitHub with a company address you no longer work for. As a user you might be worried that git commits no longer match your profile in case you remove it, so you leave it on your account. Instead you add a new email address and mark it as primary. 

Looking at the REST (3) api:

```json
[
  {
    "email": "octocat@github.com",
    "verified": true,
    "primary": true,
    "visibility": "public"
  }
]
```

One should loop over all email addresses from the response and first try to get the one marked as primary. If that fails, one should look at the first address that is verified starting at the end of the array (to get the most recently added).

Hope this helps 👍

**Comment by piamancini** [comment]
this hasn't show up again. closing for now

**Comment by luceos** [comment]
Or people just don't bother to report it a) because it already has been reported b) because they think OC is broken for them or everyone (SPF records, marked spam) c) because they have other stuff to do than following up on someone elses broken app

Not to be a pain, just pointing it out. If you don't plan on fixing this then possibly you should consider not allowing signups from GitHub or making it clear what mail address is being pulled from the GH api.

**Comment by piamancini** [comment]
I agree, but this issue needs to be reformulated.
