### ISSUE TITLE
Refund transactions are showing negative fees

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#1025]
@clarete I noticed that refund transactions and their counterpart (the original transaction) both have negative fees. Thought one would have positive numbers for it to even out when the whole ledger is evaluated?

**Comment by asood123** [comment]
Something else weird: `select sum(amount) from "Transactions" where "RefundTransactionId" is not null;`. That query should return 0 but returns a positive number (256.86)

**Comment by clarete** [comment]
I'll take a look at the fee signs. The `netAmountInCollectiveCurrency` value is most likely off because it's just the amount - fees, so if fees are wrong, net amount will be too. The interesting thing is that I'm getting a different number than you in the query that sums up the net amount. I'm getting `-258.86` (Negative).

**Comment by asood123** [comment]
Oh that might be a typo in my comment. Your number is the right one.

**Comment by clarete** [comment]
Alright, I've flipped the fees of the refunded transactions in the code base. Here's the PR: https://github.com/opencollective/opencollective-api/pull/1246

I'm now working on a quick fix for the 28 transactions in our database that need to have their fees flipped and amount fields updated.
