### ISSUE TITLE
Need to include refunded transactions in queries

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#1026]
Both revenue query and top sponsors query need to be updated. Depends on fixing: https://github.com/opencollective/opencollective/issues/1025

**Comment by clarete** [comment]
Since I don't quite trust my memory, I wanted to document what we've talked offline @aseem,

The problem with the revenue query can be explained with the following example:

 1. Let's say a transaction was created in March 31. 
 2. Then we run the monthly revenue query on April 1st. Since transactions always start with a NULL `RefundTransactionId`, the above transaction will be included in the revenue query result adding up to the total of a user's donation.
 3. The user requests a refund in April 2nd. That creates a new refund transaction and marks the initial transaction with the refund id. The newly created refund transaction should appear in the report in April decreasing the donated amount for that user.

Although that seems to work properly, if we re-run the script on June, the values for March will change (since the original transaction was marked as refunded). And that's what we're trying to avoid.

There's a PR coming with changes to address this issue.

**Comment by clarete** [comment]
I'm closing this ticket since the queries were updated. Please re-open if I missed anything! Thanks!!
