### ISSUE TITLE
new feature: in kind contribution

### ISSUE THREAD

**Issue by gmajan** [opencollective/opencollective#1030]
I am requesting a new feature.

I have submitted an expense (to We-BXL) but I want this expenditure to be considered as a gift to the project. Basically, it is a contribution in kind. So the cost should show up as paid without change to the balance of the project.

I suppose this could be a useful feature for all projects but I will still provide my details below:

URL: https://opencollective.com/webrussels/expenses/1309
Logged in as: (just provide your username or the url of your profile) guyjanssen07june
Error message if any:
Expected result: new feature: contribution in kind that shows up as expenditure
Browser: Chrome

Bonus point if you can add a screenshot :-) I will when you have finished the feature. I promise.

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
@clarete This would require adding another `payoutMethod` that could be `donation`. 

![](https://d.pr/free/i/YRBtZa+)

In that case, unlike `other` which assumes that the host has paid the expense manually outside of the platform, we would need to create a transaction from the `User` to increase their contribution and the budget of the collective by the amount of the expense (and directly add a transaction to reflect that the expense has been paid so that the balance remains the same). Does that make sense?

Can you take on that one?

**Comment by clarete** [comment]
Yes! That such a great feature to implement! \o/ I'll put a PR up soon!

**Comment by clarete** [comment]
Two questions popped up while finishing this off:
* Should I create an order besides the transaction? I guess so right?
* Do platform & host fees apply? If so, do they come from collective's ledger? Is it case by case?

/cc @xdamman

**Comment by xdamman** [comment]
- Mmmmm... I don't think so. Because an Expense is acting as a (negative) Order (`Orders` and `Expenses` should be merged eventually)
- No fees no because no money hit the account in the process.

**Comment by xdamman** [comment]
Just to be sure I understand you correctly, this should be the expense id of the expense that is considered as a donation, no need to create another expense.

**Comment by clarete** [comment]
This is going out on the next rollout!

**Comment by gmajan** [comment]
cool. Thx

**Comment by clarete** [comment]
> Just to be sure I understand you correctly, this should be the expense id of the expense that is considered as a donation, no need to create another expense.

Yes, that's what I did! <o/
