### ISSUE TITLE
show if subscriptions are inactive in user's profile

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1106]
This user wasn't aware his subscriptions were cancelled. Maybe it's worth adding a 'inactive' note on the cards in profiles so users know if they need to re - do them? 

![print-01](https://user-images.githubusercontent.com/3671070/40553873-03523bcc-6012-11e8-8f2b-7b1d346c32b8.png)
![print-02](https://user-images.githubusercontent.com/3671070/40553874-037574ac-6012-11e8-9ecf-c0fa34d7800c.png)

**Comment by HipsterBrown** [comment]
@piamancini I think this requires more nuance in the "backing" card details because the "amount contributed" could be a combination of single and subscription donations. Technically, you are backing a project once you've contributed to the collective, whether or not it's an active subscription in place.

For now, I propose adding a link to subscriptions from the user's collective page.

We can follow up with better language and details around what "backing" means vs displaying active subscriptions on their collective page. 

Another helpful addition is a notification within the app to inform users of recently failed and cancelled subscriptions, in case they missed the email notifications.

**Comment by piamancini** [comment]
>  I think this requires more nuance in the "backing" card details because the "amount contributed" could be a combination of single and subscription donations

Makes sense.

> For now, I propose adding a link to subscriptions from the user's collective page.

Ok. 

> Another helpful addition is a notification within the app to inform users of recently failed and cancelled subscriptions, in case they missed the email notifications.

We don't have any notification in app so not sure how much we should invest in right now. But a better access to subscriptions is a good first step.

**Comment by piamancini** [comment]
I think we should still do this. It's important the they know if they are not being charged (i know we send emails but these might be filtered.)

**Comment by znarf** [comment]
@piamancini can you add labels?
