### ISSUE TITLE
add a field when submitting an expense to link that expense to a URL

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1118]
Use cases: 
- submitting an expense for a PR contributed  (link the actual PR made)
- submitting an expense for a meetup sponsorship (link to the thank you shout out on social media)
- helps collectives to group expenses by project/category/event

**Comment by xdamman** [comment]
I wonder what would be the right way to do that because the use case is different for each collective. Some will want to link it to a PR, others to a tweet, etc. It could also be linked to an expense category.

I'm worried of adding another field when not needed. Because it confuses people ("What am I supposed to enter here? What is a PR? What if I don't have one? If people don't know, they are afraid to press "submit").

Maybe we can have some customs settings for managing expenses at the collective level and host level (like `expensePolicy`).

E.g. in `Collective.settings`:

```json
{
  "expenses": {
    "categories": [
      {
        "name": "Engineering",
        "description": "Invoices for engineering time",
        "metadata": [
          {
            "name": "pull-request",
            "type": "url",
            "multiple": true,
            "description": "Attach the link to a pull request"
          }
        ]
      },
      {
        "name": "Food",
        "description": "Food expenses, e.g. pizzas for meetup",
        "metadata": [
          {
            "name": "Picture",
            "description": "Please share a picture of the event",
            "type": "image",
            "multiple": true
          },
          {
            "name": "Social Media",
            "description": "Please share the URL of the tweet/facebook post",
            "type": "url"
          },
          {
            "name": "Event URL",
            "description": "Please share the URL of the event (on meetup/facebook/eventbrite or other)",
            "type": "url"
          }
        ]
      }
    ]
  }
}
```

We would store the response in`Expense.data`:

```json
{
  "pull-request": ["https://github.com/opencollective/opencollective-api/pull/1316", "https://github.com/opencollective/opencollective-api/pull/1303"]
}
```
```json
{
  "Social Media": "https://www.facebook.com/sysopspolska/photos/a.322474601528311.1073741830.318954778546960/378953452547092/",
  "event url": "https://www.meetup.com/SysOpsPolska/events/250062664/"
}
```

This will take some time to implement. It's not trivial. So it will have to be prioritized (and right now we are all quite busy on things). If we want to make it happen sooner, we could simply add a new URL field and make it clear in the description that it's optional.

I'd also love to take the opportunity to think about custom forms when becoming a member of a collective. It's a feature that has been asked a lot. People want to ask questions to new members to know more about them. Maybe that should be linked to a tier? Let's create another issue for that but it's quite related to this functionality.
