### ISSUE TITLE
Vue.js sponsor links broken

### ISSUE THREAD

**Issue by sodatea** [opencollective/opencollective#1127]
The following links redirect to the project home page:
https://opencollective.com/vuejs/tiers/platinum-sponsors/0/website
https://opencollective.com/vuejs/tiers/gold-sponsors/0/website

The following links respond with 404:
https://opencollective.com/vuejs/tiers/gold-sponsors/1/website
https://opencollective.com/vuejs/tiers/gold-sponsors/2/website
https://opencollective.com/vuejs/tiers/gold-sponsors/3/website
https://opencollective.com/vuejs/tiers/gold-sponsors/4/website

Compared and tried babel's sponsors links and theirs are fine.
Found nothing unusual in the API response https://opencollective.com/vuejs/tiers/gold-sponsors/all.json

**Comment by HipsterBrown** [comment]
@sodatea I've figured out the issue and working with @piamancini on the best way to fix it.

The widgets and the `/:collectiveSlug/tiers/:tierSlug/all.json` endpoint currently returns all contributions at those tiers, if they are active subscriptions or not. 

The shortcut sponsor links, like https://opencollective.com/vuejs/tiers/gold-sponsors/1/website, are looking for sponsors with **active subscriptions** to fill in the redirect url but does not find any because there are no active gold or platinum level sponsors for VueJS on Open Collective at the moment. 

@xdamman I would love your feedback on how we can work to solve the inconsistency between the widget + JSON data and the sponsor/backer website shortcuts.

**Comment by xdamman** [comment]
The `all.json` works as expected, it should return all members and for each there is already an `isActive` flag.

The shortcuts meant for the GitHub banner with `/website` and `/avatar` should only take into account the active members. So the bug here is that for some reason the `/avatar` returns an avatar for https://opencollective.com/vuejs/tiers/gold-sponsors/1/avatar (maybe caching issue?)

**Comment by HipsterBrown** [comment]
@xdamman It could be the cache but it should only last for 10 minutes as the maxAge. The logic works locally, wherein inactive sponsor avatars are not shown. Staging and production both have this issue. 🤔

**Comment by xdamman** [comment]
It doesn't look like a cache issue because adding a random query parameter at the end doesn't change anything https://opencollective.com/vuejs/tiers/gold-sponsors/1/avatar?31212. So maybe it's the internal cache between the frontend server and the backend API?

**Comment by piamancini** [comment]
this is what you currently see on the page: 
![screen shot 2018-09-17 at 2 46 37 pm](https://user-images.githubusercontent.com/3671070/45643236-9866e980-ba88-11e8-99ff-c07f427d367f.png)

**Comment by piamancini** [comment]
In chrome (not incognito)
![screen shot 2018-09-17 at 2 47 54 pm](https://user-images.githubusercontent.com/3671070/45643296-be8c8980-ba88-11e8-92c3-506390588c8e.png)
 you see all these broken images:

**Comment by znarf** [comment]
Will look into it.

**Comment by znarf** [comment]
@HipsterBrown @xdamman @piamancini So, there is no active gold-sponsors and no active platinum-sponsors. This mean it's normal to not display any logo. At least according to your input above.

For the broken images, as displayed in the screenshot above, that's something else.

**Comment by piamancini** [comment]
talked to Evan and he fixed an issue on his end, when platinum sponsor comes in it should show up.  
It seems like the broken images is my browser picking up the 1pxs with the ad blocker. 
Closing this, I'll check when the new sponsor comes in to see it it's ok.
