### ISSUE TITLE
Allow changing paypal email when editing expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1132]
Sometimes people want to change the paypal address after submitting an expense. The submitter, core contributor, and host admin should be able to change the paypal email when needed.

[Here's an example](https://opencollective.com/boulder-react-meetup/expenses/3424).

**Comment by mayel** [comment]
Yes please, we stumbled on this issue.

**Comment by alannallama** [comment]
I've been thinking about this, and I believe the issue is that the Open Collective system is designed to associate one email address per user, and also use that as their paypal address. If everyone has their own OC account and directly submits their expenses, this works. However, in practice, sometimes admins are submitting expenses on behalf of other people. This comes up fairly often (again today which is why I thought about it).

I can see arguments for both approaches (requiring expenses be submitted by that person with their own account, and allowing people to submit expenses on behalf of others). But Open Collective should make a clear decision about it, and either allow inputting alternative payment info or some documentation/help text explaining that we don't do that and asking them to get the payee to create their own account and submit the expense.

Personally I would suggest allowing expense submission on behalf of others, because it's more permissive, and it's pretty common that someone does paperwork on behalf of others in practice. Maybe the expense for could have an option saying "pay to me" or "pay to someone else > input their name and paypal address".

@cuiki  @piamancini or @xdamman do you have an opinion?

**Comment by xdamman** [comment]
I agree. Maybe. I’d love to rethink the flow of submitting an expense to integrate this but also the difference between submitting an expense (to be reimbursed for) and submitting an invoice (to pay the vendor). 

This is a big work and we should include @cuiki in the conversation so that he can help us through the design process.

**Comment by xdamman** [comment]
You could coordinate with @cuiki on this. But right now he is busy on the foundation UI elements to make the entire platform more consistent. And after that his priority will be to redesign the create order flow which is the most important flow and that needs love.
So not sure when he will be available for this :-( 
But I would definitely love to also give some love to the expense flow.

**Comment by alanna** [comment]
We still need this fixed

**Comment by Betree** [comment]
This is now possible in the new expenses page, but not yet in the host dashboard.
