### ISSUE TITLE
Don't use Twitter nick as OC nick

### ISSUE THREAD

**Issue by wolftune** [opencollective/opencollective#1156]
URL: sign-up process

Expected result: a place to choose the short URL for opencollective.com/X and separate place(s) to indicate social media accounts (especially *open* ones like Mastodon)

Actual result: the only option is Twitter, entering that account causes that to be used as the X for opencollective URL *and* lists `@X` on the account page *without* any reference to that being Twitter specifically.

Things to fix:

* indicate on any account page that a link is to Twitter if it is
* (temp fix) indicate in the form that the Twitter nick will be used as the OC nick
* (real fix) add a new field to choose the OC nick/url
* have a new field for Mastodon account and mark that on the profile page

**Comment by xdamman** [comment]
Thanks for your feedback!

Most people are confused by picking up a username. It's a power user feature (that's why Twitter has removed it from their sign up process). That's why we are making a best guest and if the user has a twitter account, we assume that people will want it to be consistent.

People can change that username in the advanced settings when they edit their profile page.
e.g. https://opencollective.com/xdamman/edit#advanced

We show the Twitter logo next to it on the profile page: 
![](https://d.pr/free/i/HGZzfH+)

Would love to add Mastodon, but also GitHub, Facebook, LinkedIn, etc. as ways to sign up/login and show those accounts on your profile. This is up for someone to grab!

**Comment by wolftune** [comment]
Thanks for the clarifications. Some notes:

* incidentally, uBlock Origin (at least with most of the standard lists enabled) blocks the Twitter icon
* glad to know the username is editable, but adding a note "this will be used as OC username too, but that can be edited lated", if even as a footnote or hover text or something, that would be nice
* Of the things you mentioned for connecting accounts:
    * Mastodon is actually free/libre/open (FLO)
    * GitHub, Facebook, LinkedIn, and Twitter are *not* open, and shouldn't be emphasized as much — certainly **do not** encourage sign-up / log-in with those, that's full of problems and is an anti-pattern to be avoided.

**Comment by znarf** [comment]
Missing some precise expectation on what to do here. Can we perhaps track that in multiple issues?
