### ISSUE TITLE
Improvement → Transition from old logo spec to new logo spec

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1185]
Currently, collectives have the opportunity to upload a logo and a cover. 

These images are intended to work with the current profile design, ie: https://opencollective.com/babel

In the future, we would like to use different specs for the logo and we need a transition strategy.

The new specs are already used in newly designed areas, like the Homepage and BackYourStack.

**Comment by xdamman** [comment]
What are the new specs?

I'd suggest to have a new Table `Attachments` that can be either linked with an Expense or a Collective:

id  | CollectiveId | ExpenseId | type | class | url | index | filename  | description 
--- | ------------ | --------- | ---- | ----- | --- | ----- | --------- | ----------- 
1   | 1            | 1         | pdf  |  attachment | https://aws... | 0 | 20180725-invoice.pdf |  | fds 
2   | 1            | 1         | link  |  attachment | https://twitter.com/... | 1 | | tweet proving meetup | fds 
3   | 1            |           | image| logo | https://aws... | 0
4   | 1            |           | image| avatar | https://aws... | 0 
5   | 1            |           | video| embed | https://youtube.com/... | 0 | | Vegan Street Fair video
6   | 1            |           | image| avatar | https://aws... | 1

We may also want to consider adding `CreatedByUserId` or `CreatedByCollectiveId`

**Comment by piamancini** [comment]
This can be closed because we've tackled it in NCP - @Betree do you agree?

**Comment by Betree** [comment]
@piamancini I think so, our transition strategy was quite direct because we just defined that all logos will be squares and displayed on a white background from now on. What we can do to improve this is to have a template email for contacting collectives with some recommendation when logos don't fit.

Some candidates:
- https://opencollective.com/wwcodeinc (and 90% of wwcode collectives)
- https://opencollective.com/gulpjs
- https://opencollective.com/gatsby
- https://opencollective.com/react-boilerplate
- https://opencollective.com/vapor
- https://opencollective.com/redux-devtools-extension
- https://opencollective.com/react-toolbox
- https://opencollective.com/usereact
