### ISSUE TITLE
Update the look & feel for 'How it Works' page.

### ISSUE THREAD

**Issue by cuiki** [opencollective/opencollective#1190]
Reference — https://opencollective.com/learn-more

Update the page's design to match the new style. Review the steps and rewrite the copy-write.

**Comment by cuiki** [comment]
hey @xdamman just to make sure these are accesible by anyone, the new updated images for this page WITHOUT changing anything else can be found here:  #1171

**Comment by cuiki** [comment]
@xdamman, the expectation for this page is to update the general style but still have the layout unchanged or do you think a page re-design is needed now?

**Comment by xdamman** [comment]
We still need to re-implement that feature that we used to have on the old website. But we need to think this through a bit better.

For the layout, see what you can do. I think it has to be adapted for the new design but I wouldn't go too fancy. Done is better than perfect and we need to be mindful of limited frontend engineering resource.

**Comment by cuiki** [comment]
Hi! This is a first version of the page.

— I added two more things before the current things currently on the page that, if they may be obvious, I believe will help users.

— I also re-ordered the sequence of the content to make it feel more sequential based on the steps that users will actually follow.

— https://invis.io/UDMY05M9MH6#/311234794_How_It_Works_-_Desktop

— Image:
![how it works desktop](https://user-images.githubusercontent.com/981188/43321910-db07d086-9172-11e8-99f9-ca467e81a06a.png)

**Comment by xdamman** [comment]
We should review the text. Here is what I'd suggest:

**Create different tiers**
*(screenshot of a backer and sponsor tier)*
Accept one time or recurring donations
Define different tiers for members or sponsors

**Manage your expenses online**
*(screenshot of the detail expense page with comments)*
Allow anyone to file their expenses or invoices online
Let anyone comment on expenses
One click approve/reject expense
Keep picture of the receipt / invoice private 

**Transparent ledger**
*(screenshot of /transactions page and PDF)*
All transactions in and out are public
Automatic PDF invoice

**Open Data, Open Source**
*(csv export image)*
Export the list of all your backers with their email addresses at any time
Export list of all transactions
Open Collective is open source https://github.com/opencollective/opencollective

**Manage multiple collectives**
*(screenshot of monthly host report)*
Open Collective makes it easy to host multiple collective on one single legal entity. We send you a monthly email report with all transactions per collective with all aggregated transactions in a CSV and a one PDF document with all invoices and expenses that have been paid. This makes the work of your accountant a breeze.

**And so much more**
(screenshots of event page, update page, email report)
- Create events
- Publish updates to keep your backers posted on your progress
- Monthly reports to backers
- Slack integration

I put this on a google doc so that it's easier to iterate and get comments: https://docs.google.com/document/d/1I_3VzwPKCO2d6Qv5LkCYQiM9zgIQgnFRQF1dg_xxXzM/edit?usp=sharing

**Comment by cuiki** [comment]
Here's a mock of the page with placeholders for the images we will end up using. This shows a layout adjustment for this updated content.

Let me know your thoughts. The InVision link is the same one.

— Image:
![how it works desktop](https://user-images.githubusercontent.com/981188/43501765-ca2c2778-951c-11e8-805e-76c2bb1901b7.png)

**Comment by xdamman** [comment]
That looks great. 

I've added one more section about goals in the google doc, below for your convenience:

**Set up goals**
Define goals towards your balance to be able to buy something or to organize an event or define goals towards your annual budget to be able to hire someone for your collective.

**Comment by cuiki** [comment]
Latest mockups is in InVision. I left a few comments there.

— InVision: https://invis.io/UDMY05M9MH6#/312730961_how_it_works_-desktop-
— Mockup
![how it works desktop](https://user-images.githubusercontent.com/981188/43752928-e9f34d74-99c8-11e8-951d-77aeec9818c8.png)

**Comment by cuiki** [comment]
Both views have the images within each value prop and feature described. Mobile view is ready.

— Mobile view (InVision): https://invis.io/XBNFG3ZY7A6
— Attached image:
![how it works mobile 2x](https://user-images.githubusercontent.com/981188/43865460-4e602628-9b28-11e8-989c-ef6f4ad79fc6.png)

There are a 2 pending comments made by @piamancini on InVision about including Support Tier in the **"Create different tiers."** block, and about the main headline of the page.

**Comment by cuiki** [comment]
Update:

Saraí (front-end contractor) will begin on this page next Monday, Nov 12 and it should be ready by the following Thursday or Friday, following the instructions that @znarf sent me.
