### ISSUE TITLE
error when adding a yearly contribution to Babel

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1211]
Base support tier is a yearly support. 
<img width="1142" alt="screen shot 2018-08-06 at 1 27 35 pm" src="https://user-images.githubusercontent.com/3671070/43731450-8d2648ae-997c-11e8-9d95-847b0c0fa3b2.png">

**Comment by xdamman** [comment]
That's because the `opencollective` payment method doesn't allow recurring payments. This will be fixed in the upcoming pull request from @marcogbarcellos that will land any day now https://github.com/opencollective/opencollective-api/pull/1404

In the meantime, I'm doing a pull request to improve the error message.

**Comment by xdamman** [comment]
Actually, there was a bug that I'm also fixing in that PR. So this will be fixed independently of the collective to collective donation. I'll confirm when it's deployed.

**Comment by xdamman** [comment]
Deployed.
