### ISSUE TITLE
Proper taxing for non-US entities?

### ISSUE THREAD

**Issue by Domiii** [opencollective/opencollective#1223]
First off: I really like your vision and the idea of this organization. However, I have a few questions regarding financial law, starting with just one:

I don't live in the US, naturally I plan to work on projects outside of the US. However when money starts to flow, taxes must be paid. The explanations on how Open Collective currently deals with legal issues involving money flow is not very comprehensive. The only information on taxes I found is [this wiki article](https://github.com/opencollective/opencollective/wiki/What-happens-to-my-taxes-when-I-submit-an-invoice%3F).

How can I make sure, that the local (and not the US) government gets the taxes from my project, even without tax id (in some countries, it's hard to get one)?

**Comment by piamancini** [comment]
Hi @Domiii 

- Are you a host (will you receive the funds yourself for your collective?) Otherwise where are you hosted?

**Comment by Domiii** [comment]
I'm not exactly planning to use it right now, but rather understand for what I can use it?
Let's say, I want to let people make contributions to projects I work on, how would taxing work there?
What about collaborating with others on a project? Would that be different?

FYI: I'm in Taiwan/Asia, but it would be great to understand the bigger picture here, not just the circumstances in a single country or for some specific project. :)

**Comment by piamancini** [comment]
It depends on who's your [host](https://github.com/opencollective/documentation/wiki/Becoming-an-Open-Collective-Host). If you are receiving the funds for your collective yourself, in a bank account you own, you have to manage the tax implications yourself. It's your responsibility to declare that as income in your own country. 

If you are a collective that is fiscal sponsored by the Open Source Collective (only open source projects are) then you are fiscal sponsored by a non profit, the tax implications for the donations are managed by the non profit but in order to withdraw the funds you must submit an invoice (in which case the amount is again taxable income for you) or submit an expense for an activity related to your collective to be reimbursed (for example server costs, plane ticket to a tech conf. etc) Since you are fiscal sponsored by an entity, then that entity has the right to approve or reject an invoice/expense. 

Collectives fiscal sponsored in Europe, have other restrictions related to VAT.

**Comment by znarf** [comment]
Low activity, closing it. Feel free to re-open.

**Comment by Domiii** [comment]
Thank you! I think this clears it up.

I'm adding a few more things I only recently learned myself and this is largely related:

If I want to make any money, in most countries, I would need a tax id (or even a company) to begin with.

If I use OC for a company, the company would just report it as income. Part of that income could be considered income from an "Export" if the origin of that money is a foreign entity. Here, as is the case in some other countries as well, Exports are not subject to sales tax.
Thus one has to be careful when any money is contributed from entities of the company's own country, which, in many countries, needs to be declared differently from any money contributed by foreign entities (as again, there might be no sales tax on the latter).

Feel free to correct me if you find any oddities in my logic or generally faulty statements.

[Disclaimer: None of this is legal advice and should not be taken as such.]
