### ISSUE TITLE
error when using funds added to an organization

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1229]
when trying to use the funds added to the handshake organization to make the donation to Babel: 
I added 100k to the organization, went to babel, selected handshake org, made the donation with their prepaid method (I tried both going through the tier and babel/donate) Both times I get this error. 
I am an admin (I created) the organization 

![screen shot 2018-08-15 at 5 08 22 pm](https://user-images.githubusercontent.com/3671070/44173500-1f056100-a0ae-11e8-9dec-24fc1ebb2a68.png)

**Comment by marcogbarcellos** [comment]
Technical info:
This part of the code is responsible for this error: https://github.com/opencollective/opencollective-api/blob/master/server/paymentProviders/opencollective/prepaid.js#L52-L56

The following query is supposed to check whether the prepaid card was created by the collective trying to pay. If I query straight to prod database this query:

```sql
select * from "PaymentMethods" as p left join "Collectives" as c 
  on p.customerId = c.slug 
   where p."customerId" is not null and c.slug is not null;
```
I only get 3 results: trivago, airbnb and coinbase.

In my opinion, Instead of comparing `Collective.slug and PaymentMethods.customerId` we could compare `Collective.id and PaymentMethods.CollectiveId`:

```sql
select * from "PaymentMethods" as p left join "Collectives" as c 
  on p.CollectiveId = c.id 
  where p.CollectiveId is not null and c.id is not null;
```

Which as of today results in a 12811 rows instead of only 3 rows of the first query, I am going to spend some more time to make sure this change makes sense.

**Comment by marcogbarcellos** [comment]
@piamancini i'm suspecting of some typo(either on the system through users or on the code as im still looking):

I believe This was the donation you've made today:
```
14354	Donation to Babel hanshake  opencollective  {"HostCollectiveId":11004}  2018-08-15 17:04:17.648-04  10000000  FALSE  USD  prepaid	 10000000				
```
But `PaymentMethod.customerId` is **hanshake** instead of **handshake** which makes it throws an error as there is not match.

In this case, my logic(instead of comparing `Collective.slug` with `Paymentmethod.customerid`, compare `Collective.id` with `Paymentmethod.CollectiveId`) would make it work but i need to know if it can affect some other part of the system(afraid of another collective can create a prepaid card on behalf of another customerId)

**Comment by marcogbarcellos** [comment]
After researching a bit more I figured out that even though using the collectiveId in this case could've make it work, it won't necessarily be true for all cases as collective Ids inside PaymentMethods can be NULL(through the unit tests I found and tried it only makes sense matching customer-id and slug).
I Also found other payments methods(like stripe and giftcard for example) are using the slug to compare which will make it harder if we switch it only for prepaid ones, but if we don't want it to happen again in my opinion the easier way would be making the PM to look for Ids instead of slugs so we wouldn't need to concern about  typos, changing urls and etc.

**Comment by marcogbarcellos** [comment]
Instead of changing the current logic I just did an extra layer of checks before throwing an error: 

It was:
- If the `Collective.slug` is different than the `PM.customerId`, throws error

Now: 

- If the `Collective.slug` is different than the `PM.customerId`
    - If the `PM` has a CollectiveId defined(may be **null**) and its collectiveId is different the `order.FromCollectiveId`(The collective responsible for the present order/transaction), keeps throwing the error.

cc @piamancini we already deployed in staging, could you give it a try?

**Comment by piamancini** [comment]
I can't find handshake in the organizations I'm an admin of on stating? maybe we need to update the db?

**Comment by xdamman** [comment]
@marcogbarcellos I've added some comments to the PR. Not sure I understand its original intent. Anyway, we shouldn't make comparisons with slugs. They can change over time. Also, we shouldn't make comparisons with `paymentMethod.customerId` which is an id/slug coming from an external platform that we don't control.
