### ISSUE TITLE
funky css issue in ticket form - events 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1248]
<img width="526" alt="screen shot 2018-08-28 at 3 53 37 pm" src="https://user-images.githubusercontent.com/3671070/44747241-b1f4c100-aada-11e8-857f-464199bd7569.png">

refreshed and this happened: 
<img width="1187" alt="screen shot 2018-08-28 at 3 55 26 pm" src="https://user-images.githubusercontent.com/3671070/44747305-d81a6100-aada-11e8-9c2c-466c8a252fe5.png">

**Comment by HipsterBrown** [comment]
@piamancini That grid is the new layout that @xdamman just released. https://github.com/opencollective/frontend/pull/712

I'm hoping my recent css fix will resolve the funky css issue after I release it today.

**Comment by xdamman** [comment]
Yes I made the change to show the list of tickets as a grid because on the events page we don't show them in the sidebar. Maybe @cuiki can take a quick pass at it to make those look better.
Also happy to revert this small change. It's literally just two lines of CSS. Lmk.

**Comment by piamancini** [comment]
yes please, let's revert until we have  a better design for it

**Comment by xdamman** [comment]
What about this (without stretching the height of the tickets and making sure they align)
![](https://d.pr/free/i/7ymFmm+)

Versus:
![](https://d.pr/free/i/S9uotm+)

**Comment by piamancini** [comment]
I think that if we want to re-design this, we should involve @cuiki and do a more comprehensive  re-design. 
I don't see how this changes anything and it seems like we have higher priorities atm.

**Comment by cuiki** [comment]
Hi everyone, for this particular case, I think that what @xdamman did is a good improvement vs the stacked elements like we had (which works on mobile but not on desktop).

This will eventually have to adopt the new styles and we can take that opportunity to redesign the layout if needed.

**Comment by xdamman** [comment]
@piamancini this is not a redesign. This is two lines of CSS to make a quick small improvement.

@cuiki thanks for your input. If you have small improvements to suggests, please send them away. It's not a priority but as we fix bugs on those pages, we may as well make small CSS changes that sometime can go a long way.

**Comment by xdamman** [comment]
I hear you. I share that frustration. We still haven't found the right process. On one side we have the homepage that is super well done and well implemented but it took 3 months to get it done (and it's not fully finished yet since it's still lacking the video section at the bottom), and on the other side we have everything else that we have been doing that is made of a lot of patches here and there and not well thought out user flows.

Maybe we can find someone externally who can help us figure out how to manage this process?
I'm obviously not the right person for this type of process thinking.
