### ISSUE TITLE
adobe's donation to sustainOSS seems to be to a non-existing profile

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1249]
go to https://opencollective.com/adobe/transactions# and click on the avatar of the collective to which adobe made a 2k donation - you are sent to https://opencollective.com/sustainuk-2018-442ev instead of https://opencollective.com/sustainoss/events/sustainuk-2018-442ev#

This is what might be producing all sort of issues we are seeing: 
- backer card looks broken 
<img width="652" alt="screen shot 2018-08-28 at 4 24 12 pm" src="https://user-images.githubusercontent.com/3671070/44748860-d8b4f680-aade-11e8-9f3e-ba2084ed4761.png">

- and download receipt in the transactions serves the travolta 404

**Comment by xdamman** [comment]
For the broken link to the invoice, it's because you need to be an admin of Adobe's org to be able to download it. 
We normally don't show the link to download it to avoid linking to a broken place except when you are a root user. This upcoming fix will also allow root users to download any invoice:  https://github.com/opencollective/opencollective-api/pull/1425
