### ISSUE TITLE
in kind donations should not show up in the monthly host report

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1271]
When we do an in-kind donation, we create two transactions: one to remove the money from the collective and one to add the same amount to the collective. That way the result is zero and we can record that the user who submitted the expense did contribute that amount.
However, we still count that transaction in the host report which we shouldn't include it there.
We should remove the `HostCollectiveId` from the transactions created when we do in-kind donations AND we should compute the monthly host report based on the `HostCollectiveId` in the `Transactions` table instead of using all transactions where `CollectiveId` is in the list of collectives hosted by the host.

**Comment by piamancini** [comment]
this needs to happen if we want to maintain the in kind donation feature.

**Comment by znarf** [comment]
@piamancini @xdamman is "in kind" still supported?

**Comment by piamancini** [comment]
We discussed removing it. If we haven't yet, we should until done properly.

**Comment by piamancini** [comment]
@znarf did we end up killing this?

**Comment by znarf** [comment]
The issue to track it was: https://github.com/opencollective/opencollective/issues/1758

It was killed frontend side: https://github.com/opencollective/opencollective-frontend/pull/2158

A small follow up on the API is still pending: https://github.com/opencollective/opencollective-api/pull/2259

This issue is now invalid.
