### ISSUE TITLE
implement badge and support us corner image

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#133]
We need to implement @erickrico's design for badge and corner image. What's the best way forward? or Who can take it on?

The badge with avatar images can be a second iteration if it's too complicated. I'd like to get this out to the collectives soon. 

![screen shot 2016-06-13 at 11 05 56 am](https://cloud.githubusercontent.com/assets/3671070/16015778/34099d60-314c-11e6-8d24-6eb60c8fe148.png)

**Comment by piamancini** [comment]
@xdamman @asood123  this is the issue I created for this.

**Comment by erickrico** [comment]
hey @xdamman @piamancini @asood123 new ideas for the ribbon/widget 

### bubble
i think this one works best, we can decide when it triggers, probably close to the end of the page, or we can let the projects decide
![screen shot 2016-07-11 at 12 25 49 pm](https://cloud.githubusercontent.com/assets/18429104/16740303/12391566-4764-11e6-8115-24c83aa55417.png)



### bar at the top
this one is more intrusive but maybe thats what we need right now, it wouldn't  be fixed
![screen shot 2016-07-11 at 12 28 34 pm](https://cloud.githubusercontent.com/assets/18429104/16740281/f6d23bea-4763-11e6-820b-d11a229287fc.png)

### bar at the bottom 
i also like this one, since is at the bottom we can take more space without being too intrusive
![screen shot 2016-07-11 at 12 29 47 pm](https://cloud.githubusercontent.com/assets/18429104/16740444/c05b9fba-4764-11e6-93e5-c71318f51b79.png)

**Comment by xdamman** [comment]
Those are really cool! I really love them all.
Not sure about the background though.

How would a sponsor show up there?
Can you send me the SVG version (without the background) for the bottom one, that's the one I'll start implementing.

**Comment by Frijol** [comment]
Is there a badge somewhere that I can use for our open collective?

**Comment by xdamman** [comment]
@Frijol see documentation here: https://github.com/OpenCollective/OpenCollective/wiki/Website-banner

Let me know if you have any questions or feedback! (and sorry for late reply!)
