### ISSUE TITLE
Users can't comment on expenses

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1349]
I hear from users fairly often that they cannot reply to my comments on their expenses. They get an email notification when I ask them a question, and they click through to the expense page, but can't figure out how to comment back. I end up hearing from them via email or they contact support which gets forwarded to me.

I think whats happening is they aren't logged in, so they're seeing the expense page with no option to comment and don't know what to do. 

I have some ideas:

1. Since Open Collective logs people in via email link anyway, can clicking through from a comment email notification automatically log the user in?
2. Make it possible for them to reply via email, like many apps have with their email notifications.
3. For the logged-out user view of the expense page, add a big "LOG IN TO COMMENT" button where the comment box is for logged in users, to make it clear what's going on.

**Comment by alannallama** [comment]
OK I just got a more detailed report from a user that makes me think this might be an actual bug, and not just a UX issue.

> The comment box is totally missing, as if I were logged out, but I can see my username in the top right corner and I can edit my profile, so I'm definitely logged in.

<img width="681" alt="screen shot 2018-10-10 at 6 32 39 pm" src="https://user-images.githubusercontent.com/5498878/46715110-1353a680-ccbb-11e8-9044-82e8149cf6fd.png">

**Comment by Betree** [comment]
I've been able to reproduce and find the root cause for this issue. I will submit a patch for it today.

@alannallama regarding the suggestions you made: 

1. A comment reply notification is something a user could forward to someone. I think it would be risky to include a login token in it as user may not know that the email includes sensitive data.

2. Would be nice, certainly time-consuming to develop. Interesting long-term solution.

3. Definitely a good idea and easy to implement. I think we should be explicit here about what user's can or cannot do in any case:
    - `Log in to comment`
    - `You don't have the permissions to comment on this expense`
    - Comment Form

@znarf should I include the `Log in to comment` button in my PR?

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective-frontend/pull/954 is now deployed in production, showing a `Login to comment` button when appropriate. We also show a message if user doesn't have permission to comment.

![Button preview](https://user-images.githubusercontent.com/1556356/48058735-7e5ba480-e1b7-11e8-8ef8-aeafe15adc9d.png)
