### ISSUE TITLE
Profile page show logo of companies in full (not rounded)

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#138]
e.g. https://opencollective.com/digitalocean

There is a new `user.isOrganization` boolean introduced in https://github.com/OpenCollective/opencollective-api/pull/449

If true, the avatar represents the logo of the organization and should therefore not be shown in a rounded style.

**Comment by xdamman** [comment]
It could look better https://opencollective.com/digitalocean
Not sure about the gray background. Also I feel the logo should be larger. @erickrico what do you think?

**Comment by piamancini** [comment]
not a fan of the grey. The page in general, imo is not ready to go live. I feel we can do better. It seems like there are three different font sizes for the same weight of statment and us the "Hello I'm" a different font?

**Comment by carlosascari** [comment]
The gray background is there for the all-white on transparent-background logos.
It is all the same font, however it does vary in color and size.

I will update the cards so the *thumbnails* match the styles in the new homepage cards:
https://github.com/OpenCollective/OpenCollective/issues/119#issuecomment-227282665

I will also see what I can do about the typography

**Comment by erickrico** [comment]
i think to change the grey background to white will work, te open source projects have problems with the white logos because they dont focus on brand awareness, but the supporters or backers shouldn't have problems with either their profile picture or company logo, as for the collective page, this is a little refinement hope it makes more sense with the new collective cards 
![profile](https://cloud.githubusercontent.com/assets/18429104/16389820/722f60d8-3c65-11e6-9a27-b52bffe3c787.png)
