### ISSUE TITLE
Expense creator must be able to edit expense after the expense is approved

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1384]
**Story**
A Contributor creates an expense through a Collective. The contributor is able to edit the expense after it's approved but once it's approved the user can't edit.

**To Reproduce**
1. Create an expense through a collective
2. Collective admin approves the expense
3. Expense cannot be edited by the creator anymore

**Expected behavior**

The expense must remain editable until it's **PAID**.  If the expense is already **APPROVED**, the creator should still be able to edit it, but if he does it, the expense will change the status from **APPROVED** to **PENDING** again.

reference #1378

**Comment by znarf** [comment]
@marcogbarcellos What's the complexity? Is that a priority?

**Comment by Betree** [comment]
Changing categories and description could be really useful but it seems to me user should not be able to change the amount, payment method and email.

**Comment by marcogbarcellos** [comment]
@znarf I'd say we need to discuss the whole expense workflow, not only this part. Otherwise we would work on it and then would need to change other part later on. But having this issue in mind, I believe it could be done in one day(complexity > medium) and it's not a high priority unless someone say so...

**Comment by alannallama** [comment]
We still need this. Edit should always be an option until it's paid (for all data related to an expense), but if any changes are made it should go back to pending status and have to be approved again.

Currently I use an annoying workaround for this all the time, where I edit something small (like adding a trailing space) to force the expense back to pending, so the submitter can then edit it, such as uploading a corrected invoice. I can always edit because I'm the admin, but they should be able to as well.

**Comment by piamancini** [comment]
let's look at this after the collective page flow is done and we start expense flow

**Comment by alanna** [comment]
I really want this... we encounter problems with this all the time in support and when dealing with expenses. I use the annoying workaround to send expenses back to pending status dozens of times a week.

**Comment by gustavlrsn** [comment]
Just leaving a note here that I'm starting to work on this!
