### ISSUE TITLE
Design for automating tax form process

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1386]
I just went through the tax form process for the Medium partner program. They use a third party provider called Tipalti to do it all online. As Open Collective scales, you might want to look into this option.

Here are screenshots of the process...

<img width="536" alt="screen shot 2018-10-31 at 3 10 51 pm" src="https://user-images.githubusercontent.com/5498878/47762119-27ba1a80-dd20-11e8-9321-a1382b1ae12c.png">

<img width="658" alt="screen shot 2018-10-31 at 3 12 03 pm" src="https://user-images.githubusercontent.com/5498878/47762135-343e7300-dd20-11e8-98bd-0e7241184850.png">

If you click "tax form questionnaire"

<img width="654" alt="screen shot 2018-10-31 at 3 12 18 pm" src="https://user-images.githubusercontent.com/5498878/47762144-43252580-dd20-11e8-898e-8dbeffba056f.png">

<img width="655" alt="screen shot 2018-10-31 at 3 12 26 pm" src="https://user-images.githubusercontent.com/5498878/47762152-47e9d980-dd20-11e8-9a84-0ed026f9968e.png">

<img width="647" alt="screen shot 2018-10-31 at 3 12 35 pm" src="https://user-images.githubusercontent.com/5498878/47762158-4e785100-dd20-11e8-9305-cab27ec93cb6.png">

<img width="654" alt="screen shot 2018-10-31 at 3 14 05 pm" src="https://user-images.githubusercontent.com/5498878/47762162-53d59b80-dd20-11e8-961c-b6fe1df6fd63.png">

<img width="653" alt="screen shot 2018-10-31 at 3 15 26 pm" src="https://user-images.githubusercontent.com/5498878/47762164-5a641300-dd20-11e8-9160-212aecbb84ec.png">

<img width="678" alt="screen shot 2018-10-31 at 3 15 59 pm" src="https://user-images.githubusercontent.com/5498878/47762166-6059f400-dd20-11e8-8e64-754a8aab0c60.png">

**Comment by piamancini** [comment]
this is great  and I think we should do the invoices on the fly too.

**Comment by alannallama** [comment]
Some data to back up the need for this: 

We missed getting over 50% of the W9s we needed to Collect this year, and it's a pretty painful manual process to chase them down. It's a risk to Open Collective because there's a good chance some people will just not respond to the request now because they have already been paid.

If we don't want to prioritise a fully automated system, I suggest at least a flag in the database for having a form on file, and the system should throw an error if you try to pay someone who's hit the limit but does not have the form submitted.

Another complication is our system currently does not differentiate receipt reimbursements from invoice payments, and only the latter triggers the requirement for the tax form. I coded them all manually by looking at submitted expenses, but this is very prone to human error. My design for revamping the expenses process includes differentiating these payment types at the time of submission. See #1167 

@xdamman @piamancini

**Comment by piamancini** [comment]
we have a duplicated issue for this. @alanna can you please consolidate in one and close the other one? The latest on seems better.

**Comment by alannallama** [comment]
Merging to #1774

**Comment by alannallama** [comment]
HelloWorks offers a service for these kind of forms, with an API so we could integrate it directly into our expense process. I think we should consider such a solution.

<img width="606" alt="Screen Shot 2019-04-05 at 2 27 49 PM" src="https://user-images.githubusercontent.com/5498878/55598522-9d368500-57af-11e9-9d6c-0259648e86c2.png">
