### ISSUE TITLE
Page to show all pledged collectives 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1387]
It'd be great to have all pledged collectives in one page, to point people there. 
We already have a first one and we've found out via twitter. 

---

*Edit by @Betree: see detailed specs [below](https://github.com/opencollective/opencollective/issues/1387#issuecomment-469169313)*

**Comment by Betree** [comment]
We can probably re-use the logic from the [discover page](https://opencollective.com/discover) to do that.

**Comment by cuiki** [comment]
@Mayekita did a page for this but I was thinking that it might be a better idea to show them (and filter them) at the discover page itself.

I asked Maye to do and post a screen on this in addition to what she already did.

**Comment by Mayekita** [comment]
Yes, I made a page for this but after we discuss that @cuiki and I agreed on add a filter to the Discover page, so it will be something like this:
![screen shot 2019-02-27 at 4 12 25 pm](https://user-images.githubusercontent.com/46466094/53526684-89aa4700-3aaa-11e9-90a5-8b63e28766b4.png)
Also it matches the issue #1560 
Here's the flow you can see how it works:
https://www.figma.com/proto/D9ToLTukHKrcoHq3vNKB9Mea/05.-Discover?node-id=1%3A2&viewport=102%2C310%2C0.788686&scaling=min-zoom

**Comment by piamancini** [comment]
looks good!

**Comment by Betree** [comment]
To sum up what's need to be done to complete this issue and implement [the design](https://www.figma.com/proto/D9ToLTukHKrcoHq3vNKB9Mea/05.-Discover?node-id=1%3A2&viewport=102%2C310%2C0.788686&scaling=min-zoom):

- [ ] This feature should be implemented in the [`/discover`](https://opencollective.com/discover) page.
- [ ] We need a new `PledgedCollectiveCard` component to display pledged collectives
- [ ] Add a search bar on the page
- [ ] Revamp the filters according to design
  - [ ] Move sortBy, use a `StyledSelect` instead of a regular `select`
  - [ ] Remove the "Show" filter select and instead use links (`All collectives`, `Open source collectives`...)

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by fakela** [comment]
Am interested in working on this issue

**Comment by Betree** [comment]
Hi @fakela, welcome! First come first served, this issue is yours :slightly_smiling_face: 

If you have any question please ask directly on this issue or on [Slack](https://opencollective.slack.com).

**Comment by Betree** [comment]
@fakela I've invited you to the [contributors/developers](https://github.com/orgs/opencollective/teams/developers) team. You should receive an email to validate this shortly. Once accepted, you'll be able to push code directly on this repository.

Please note that the `master` branch is protected so you will have to create a new branch to work on.

**Comment by Betree** [comment]
@fakela As agreed on Slack, we need to move forward with this one and for that we must has a timeframe. If not completed in two weeks from now (2019/04/29) the issue will re-assigned to another contributor or to someone from the team.

**Comment by cuiki** [comment]
@Betree we've created another separate issue to track the last pending sub-task of this. You can find it here: #1929

**Comment by Betree** [comment]
@cuiki Great! https://github.com/opencollective/opencollective/issues/1929 is out of the bounty scope but ideally we should ship it at the same time.

**Comment by cuiki** [comment]
Cool, that issue is being delivered today.

**Comment by eloyekunle** [comment]
@Betree Is this still open?

**Comment by Betree** [comment]
@eloyekunle It is, let's just merge https://github.com/opencollective/opencollective-frontend/pull/1822 before, it will make the changes for it much easier.

**Comment by Betree** [comment]
opencollective/opencollective-frontend#1822 is now merged, so this issue is up for grabs!

**Comment by leonardohof** [comment]
> is now merged, so this issue is up for grabs!

@Betree I'd like to work on this issue.

**Comment by Betree** [comment]
@leonardohof all yours! Ping me if you need anything :)

**Comment by Betree** [comment]
:trophy: This issue is now completed. 

@leonardohof To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:
