### ISSUE TITLE
OCR for Receipts

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#14]
We require all expenses to have a receipt attached. Currently, users need to manually fill that info. No one likes filing expenses, so any reduction in friction in this process would go a long way. 

We want to OCR receipts and prefill some of the fields like here: https://opencollective.com/yeoman/expense/new. Submit a receipt and whatever fields we can deduce, we will fill the form for user to review.

Fancier versions of this could hook it up to a phone number. Txt a receipt to us and we'll send you back a link showing what we prefilled and you can edit or approve.

**Comment by carlosascari** [comment]
This sounds ambitious, I've played with OCR in the past so what you're asking for, makes me wonder. 

Is there a particular receipt structure, or anything goes?
From the extracted characters, how will you make sense of each chunk, do you want to make assumptions, like the total must be towards the bottom and is numeric?
Will the OCR support international languages?

A not so ambitious take IMO would be to draw rectangles around numbers, dates and strings that is determined to be relevant, where the user can click or drag and drop the chunk of characters.  This is because teaching a computer what we understand as relevant data, is pretty darn hard.

link https://opencollective.com/yeoman/expense/new is 404

**Comment by asood123** [comment]
I was imagining this as an API call - takes an image and returns back it's best guess for date and amount. For finding amount, I would take all the numbers with decimals and pick the highest as the best guess. Date is a little trickier - look for a few formats (MM/YY/DDDD, MM/YY/DD, etc) and find one that's closest to the current date.

This task is more in the fun category if somebody wanted to build this as a separate microservice, we would play with it. Our volume of receipts is far too low for this to matter immediately.

**Comment by piamancini** [comment]
closing this, reopen if this becomes a priority in the future.
