### ISSUE TITLE
Update credit card is failing

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1419]
**Describe the bug**
From user: opencollective.com/genuinebeehive: 
I'm trying to update the payment method for my organization account (https://opencollective.com/genuinebeehive/edit#paymentMethods), however it's not working for me... it shows me the old card removed (it expired) and allows me to add a new one,  I get a "saved" message, but when I leave the payment methods and come back, the old card continues to appear, and the new one does not show...

**Comment by znarf** [comment]
I think the issue is mentioned in: https://github.com/opencollective/opencollective/issues/1336

This one might be also related: https://github.com/opencollective/opencollective/issues/1335

Current outcome: the operation might be technically working, but we make everything possible in the interface to hint that it's not.

**Comment by znarf** [comment]
This is gonna be released in the "Gift Cards 2nd release"
