### ISSUE TITLE
Charge a fee for bank transfers

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1424]
@xdamman says: 
We should have a clear policy for that because it’s not fair that people get to get paid using a wire (which takes a lot of administrative work on our side) and pay no fees versus those who use PayPal and pay fees but it’s only one click for us. I think we should have an administrative fee
and based on that people will be smart enough to figure if they are better off using paypal or asking for a wire, a bit like on Amazon where you can select shipment type with different price and delay.
Eg.:
* PayPal: processed every Friday - 2.9% + $0.30
* Wire: takes up to 2 weeks - $50

The current feature is only to record the payment processor fee. e.g. for transferwise. It doesn’t let us input the host administrative fee. Shouldn’t be too hard to add though.

**Comment by alannallama** [comment]
@piamancini can you share your thoughts on this? We have a range of special circumstances for bank transfers, like people who live in non-paypal countries. I think the idea of a $50 fee makes sense for large amounts, but what about smaller amounts when they are still asking for bank transfer?

**Comment by piamancini** [comment]
$50 is crazy. 
For reference, these are Patreon's fees 
https://support.patreon.com/hc/en-us/articles/203913489-What-are-my-options-to-receive-payout-

**Comment by alannallama** [comment]
Yes $50 is crazy, but the context is that every time someone wants a bank transfer one of you has to go to the bank or otherwise do a manual process, so I think @xdamman was more thinking about fees to cover that time. 

Patreon says:
> If you are a US creator, you have the option to receive payout to your checking account via direct deposit. If you're an international creator, you can receive payout via Payoneer or through PayPal.

I am assuming they have automated their process for US direct deposits. Can Open Collective do the same thing? If so, then of course we can offer them for low or no fees. I think the issue is how much we can afford to do bank transfers manually.

What is blocking Open Collective from automating direct deposits through Stripe?

**Comment by piamancini** [comment]
Nothing I'm aware of. We should look into what it entails. It'd be good to do it before we get into reviewing the expense flow so we can potentially incorporate it.

**Comment by alannallama** [comment]
I raised a separate issue for looking into automating direct deposits. I agree that if we're going down that route, we shouldn't start charging a special fee now. That's only prolonging the real problem.

**Comment by piamancini** [comment]
Thanks. I'll put it on my list

**Comment by xdamman** [comment]
We will always have to offer a manual payout option since we can have hosts in countries with payment methods that we won't be able to directly support. So I think it's a good idea to let the host offer such manual processing for a fee (up to them to define what that fee should be).

The primary goal here was to remove the incentives for people to ask for a IBAN transfer to avoid fees instead of PayPal. Because it's 10x more work on our side to manually process such transfer.
It's also not fair that sometimes we do it, sometimes we don't. It should be the same policy for everyone.

That's why if Paypal is taking 2.9% + $0.30, we should also charge the same for wire transfers, or we could say that wire transfers are only for payments of more than $1,000 and the fee is 2% (so it's cheaper than paypal).

**Comment by lsmith77** [comment]
I like the idea of making wire transfers cheaper for large enough transactions than having to go through paypal as a “quick fix”
