### ISSUE TITLE
collective to collective donation is not showing up as a payment method 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1460]
**Describe the bug**
@jdorfman - core contributor of opencollective.com/getbootstrapcdn is trying to make a donation to opencollective.com/network-time-foundation 

Both collectives are on the same host. 

He selects the collective's profile from the dropdown menu, but in the payment method option he doesn't see the collective's budget. He only sees Credit Card / PayPal 

**Screenshots**
![image 4](https://user-images.githubusercontent.com/3671070/48799586-4f305180-ece6-11e8-8916-259d0ad04849.png)

**Additional context**

**Comment by piamancini** [comment]
Collective to Collective donations is used to move budget from one collective to another under the same host. When selecting a collective you admin in the contribute as section, you should see the collective's budget (or at least a payment method option) to use that budget to make a contribution. 
Related closed issues: 
https://github.com/opencollective/opencollective/issues/1282
https://github.com/opencollective/opencollective/issues/1244
https://github.com/opencollective/opencollective/issues/1238
https://github.com/opencollective/opencollective/issues/1196

**Comment by marcogbarcellos** [comment]
I believe this was manually fixed by @Betree 's db change. can any @piamancini or @Betree give a status on it? the collective payment looks good in staging. I tried donating U$10 from Sustain(collective) to Webpack(collective):
https://staging.opencollective.com/webpack/transactions

![screen shot 2018-11-20 at 7 30 01 pm](https://user-images.githubusercontent.com/8717041/48811190-b1934d00-ecfa-11e8-8696-d9407c6a274a.png)

**Comment by marcogbarcellos** [comment]
I believe this was manually fixed by @Betree 's db change. can any @piamancini or @Betree give a status on it? the collective payment looks good in staging. I tried donating U$10 from Sustain(collective) to Webpack(collective):
https://staging.opencollective.com/webpack/transactions

![screen shot 2018-11-20 at 7 30 01 pm](https://user-images.githubusercontent.com/8717041/48811190-b1934d00-ecfa-11e8-8696-d9407c6a274a.png)

**Comment by Betree** [comment]
@marcogbarcellos It is fixed indeed, was due to a missing `PaymentMethod` for collective, manual insertion in DB did the trick. 

However the following query:

```sql
SELECT		* FROM "Collectives" c
LEFT JOIN 	"PaymentMethods" pm on c.id = pm."CollectiveId"
WHERE 		pm.id IS NULL
AND 		c.type = 'COLLECTIVE';
```

Still returns:
![Table preview](https://user-images.githubusercontent.com/1556356/48843358-1a300780-ed97-11e8-8f85-e56ca253806d.png)

@piamancini @marcogbarcellos The collectives in this table will have the same problem if they try to donate from collective to collective. Should I fix all them as well?

**Comment by piamancini** [comment]
Also, we should find patterns of why this happens
- Purescript, pre-committ and simpleinjector are pledged collectives  (only pre-committ has been claimed)
- Network Time Foundation, Gentlewoman's Club and Scuttlebutt created an organization thinking they  were creating a collective. 
- Open Miami Host User and Helium Grant have hosts that are users instead of organizations (this is something that has consistently happened in this particular case) 
-  PyMX, Purescript, simpleinjector, webxrsf don't have a host connected yet
- glammrus I have no data and it has a host. 

I guess, it makes sense that collectives without a host don't have a payment method, but we need to make sure they have one once they are activated or claimed.

**Comment by piamancini** [comment]
@Betree see my comment above before adding them.

**Comment by Betree** [comment]
- So for manual organization -> collective conversion we should keep that in mind when making the conversion.
- I'll open an issue to ensure pledged collectives get a proper PaymenMethod added when claimed.
- For hosts that are users, is it a common scenario (that we should handle in the code) or just a particular case were we should only be careful?

**Comment by piamancini** [comment]
> For hosts that are users, is it a common scenario (that we should handle in the code) or just a particular case were we should only be careful?

If @xdamman assumptions on how non open source projects should behave are correct (that projects that have less that $500 p/m budget will be hosted by a person) we can expect this case to grow. It's not super common yet, but I think it will become more common as we develop a flat fee model. We should handle this well for all cases.

**Comment by Betree** [comment]
I've fixed the 8 collectives that had a host:
![Fixed collectives](https://user-images.githubusercontent.com/1556356/48922652-8fd7c880-eea8-11e8-8a21-f734d0426525.png)

And created an issue to pursue the investigation: https://github.com/opencollective/opencollective/issues/1467
