### ISSUE TITLE
Create an org collective for NServiceBusExtensions based on nuget downloads

### ISSUE THREAD

**Issue by SimonCropp** [opencollective/opencollective#1469]
I would like to create an org collective for https://github.com/NServiceBusExtensions/ but none of the  individual repos have 100 stars. in fact stars are a poor way to justify "allowed to create an open collective" in this case. All the tools in that repo target enterprise developers, which (from what i have observed) do not interact much on github except to raise issues. They generally do not star repos. They are what @shanselman refers to as [Dark Matter Developers](https://www.hanselman.com/blog/DarkMatterDevelopersTheUnseen99.aspx). A better measure would be nuget downloads. for example this https://www.nuget.org/packages/NServiceBus.Serilog/ gets several 1000 downloads per major version, and 55 downloads per day.

So is there any way i can get an open collective for NServiceBusExtensions?

**Comment by piamancini** [comment]
Hi @SimonCropp Yes, stars is an imperfect measure, but it's a measure standard enough that lets us quickly evaluate repos in an automated way. 
I'd love to help you set up, create a collective opencollective.com/create choosing anything other than open source and we'll manually approve you. If you'd like us to fiscal sponsor your collective (read opencollective.com/faq/hosts) please apply to the Open Source Collective as your fiscal sponsor. Otherwise, feel free to connect your own host and stripe account.

**Comment by piamancini** [comment]
You are all set @SimonCropp. Closing this for now. Let me know how it goes.

**Comment by SimonCropp** [comment]
@piamancini thanks so much for all your help
