### ISSUE TITLE
Expense page not showing host admin actions

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1496]
As a host admin, I need to be able to view invoices and receipts and pay out expenses from expense pages. As of recently, the expense page no longer shows these functions (view attachment, pay button). I can only see them in the ../collectives/expenses view. This makes host admin tasks a lot harder.

**Comment by znarf** [comment]
@xdamman Do you know what happened?

**Comment by xdamman** [comment]
@alannallama are you talking about the dashboard page (e.g. https://opencollective.com/opensourcecollective/dashboard) or the collective/expenses page (e.g. https://opencollective.com/webpack/expenses).
Probably a bug I introduced but I think I already fixed it. Both of those pages work now (at least for me). Please let me know if it's still an issue, otherwise please close it.

**Comment by alannallama** [comment]
@xdamman - I was talking about individual expense pages [like this](https://opencollective.com/webpack/expenses/5899). But it's fixed now :)

**Comment by znarf** [comment]
Great to hear!
