### ISSUE TITLE
Duplicate "Financial contributor" on Collective profile

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1532]
https://opencollective.com/slack

There is two times the headline "Financial contributor"

![Capture d’écran 2019-07-05 à 16 56 09](https://user-images.githubusercontent.com/806/60730616-d9f85080-9f45-11e9-9585-ae3d62abba63.png)

**Comment by marcogbarcellos** [comment]
It's duplicating the backing because It "repeats" the section according to the different types of the collectives: EVENT, COLLECTIVE and ORGANIZATION. so it may actually repeat it 3 times. I see 2 possible solutions:
1) consider only one section for all collectives regardless their types(my favorite)
2) Leave the way it is today but specify which type of collective that section is about so instad of `Backing` 3 times we would have: `Organizations we are backing`, `Collectives we are backing` and `Events we are backing`.

Let me know what's the best solution in your opinion

**Comment by xdamman** [comment]
I agree that 1. is better

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by alabobriggs** [comment]
am from osca ph and I'll like to work on this

**Comment by alabobriggs** [comment]
I amm having difficulty understanding how to fix this issue. Please I need some guidance @znarf

**Comment by alabobriggs** [comment]
Am almost done with this sorry for delay

**Comment by alabobriggs** [comment]
Just made a [Pull request](https://github.com/opencollective/opencollective-frontend/pull/2120)  @znarf

**Comment by znarf** [comment]
@alabobriggs cool, we will look at it!

**Comment by znarf** [comment]
Closing the issue because it's gonna be invalid with the release of Collective Page v2.
