### ISSUE TITLE
Verify paypal pre-approval is connecting to correct account

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1540]
To refill the paypal pre-approval balance you click a button on the dashboard. Normally, you'd then log into paypal and approve the balance.

However, if you are already logged into another paypal account, it will skip asking you for your credentials and apply the key from the logged in account, even if it's not the correct one. Then the Open Collective system proceeds to pay expenses from the wrong paypal account.

The system should only apply a paypal key associated with the correct paypal account for the host dashboard you click the button from. There should be some verification so the Open Collective system is never allowed to automatically pay expenses from the wrong account.

**Comment by xdamman** [comment]
If you are already logged in, it will not proceed to pay the expense. It will proceed to create a new prepaid paypal card so that you can pay expenses. It will also show you the email address of the paypal account connected to your account.

We cannot control the fact that paypal ask or doesn't ask you for your credentials. If you are already logged in, they won't ask them (but they show you which account you are currently logged in with).
It's outside of our control.

It's the same when connecting your twitter account to your open collective, if you are logged in twitter won't ask you for your credentials but it will show you what is the account that you are currently logged in with.

**Comment by alannallama** [comment]
What I'm saying is Open Collective hosts should have an associated paypal email address and should not be allowed to auto-pay expenses from any account but that one. Like looking at your host dashboard and seeing the wrong paypal email address connected should never be a thing that could happen.

**Comment by alannallama** [comment]
We've just had a support thread with a user who made this exact same mistake. She was already logged into her personal Paypal on her computer, so when she refilled the pre-approval balance through open collective it ended up connected to her personal account not the host org's paypal account. She then paid out expenses and it caused a mess because it drew from her personal bank account. 

The way our system is designed now, this mistake is way too easy to make, and I think given that it causes money to get paid from the wrong account, I think it is pretty serious.

@xdamman @znarf - is there ever a case when users actually want to be hooking up different paypal accounts to their open collective and changing back and forth? I cannot think of any such case, so I don't think it should be possible in the system. There should be a setting for the host's paypal address, and no other address should work with that host.

**Comment by Betree** [comment]
We have to check but I think that Lea from Open Collective Paris recently used her personal account to reimburse some transactions. I'm not sure why.

@alannallama Just jumping on this one so I'm not sure if that was already addressed, but we actually show the email under the "Refill balance" button:

![image](https://user-images.githubusercontent.com/1556356/55386793-29cf1200-5528-11e9-984e-7ff27b5c5856.png)

Does that solve the problem?

Otherwise if I understand correctly the proposal here is to not allow the hosts to change their PayPal account?

**Comment by alannallama** [comment]
@Betree Yes the paypal address shows on the dashboard. But there are several issues: 

* The connected paypal doesn't show on expense pages, which you can also pay from
* If you are already logged into another paypal, when you click refill balance it actually doesn't give you the option to log into the correct paypal, it just sets an approval key from the account it has the cookie for or whatever it's doing
* It's way to easy to make the mistake of not noticing the connected paypal to logging into the wrong account

My suggestion is not that paypal accounts should be hard-wired and unchangeable, but that it's a setting the user can define for each host, and that host can only connect to the paypal address you've set, not accidentally connect to another one.

Obviously people should just be careful and not make mistakes, but unfortunately humans don't work that way.

**Comment by alannallama** [comment]
I made a screencast showing why it's so easy to make this mistake. At no time does it confirm your paypal email address or the name of the account, or even show it to you clearly - it just gives you the approve button. I clicked "refill" from Open Collective EU dashboard, and it nearly connected Open Collective c-corp host Paypal because I had a cookie set for that account from before in my browser.

https://drive.google.com/open?id=1487OiR-LxZ28awfXafg7g1mtJF-1cV3q

**Comment by Betree** [comment]
Ok I can see why that's bad now. 

So I'd be in favor of blocking the change: if your PayPal account for the host is a@opencollective.com and you choose b@opencollective.com in the flow, you'll get an error message like:

> Hosts cannot change their PayPal email address, {host} is currently linked to a@opencollective.com. Please contact support if you do want to change your PayPal address.

An alternative would be to just show a warning when changing it:

> Warning: the PayPal email for this account just changed from a@opencollective.com to b@opencollective.com. If it's not the change you inteded to do, you can click on "Refill balance" and choose a different one.

Not sure that the second one is easily feasible though, will have to check.

**Comment by alanna** [comment]
I really want @Betree 's solution above to be implemented. This is a rare situation but the consequences for making this (very easy to make) mistake are really bad. The system shouldn't allow it to happen.

**Comment by alanna** [comment]
We just had this issue come up again. I know it's rare because we are practically the only org that's running multiple hosts at once, but the consequences when it happens are really messy. I wish this could be fixed.

**Comment by alanna** [comment]
We have determined that every single host admin who manages multiple
PayPal's makes this mistake at some point, and it's extremely damaging. I
really think it needs to be addressed.

**Comment by Betree** [comment]
Changes should be API only, but there's maybe a tiny bit of Frontend to touch to display the error correctly.

**Comment by Betree** [comment]
Some specs based on the latest conversations, that require https://github.com/opencollective/opencollective-api/pull/4422 to be merged first:

In https://github.com/opencollective/opencollective-api/blob/a4c9bbffa2f0d18ecceca7c1d031df2fafba17f1/server/paymentProviders/paypal/index.js#L140, if there was another PayPal account link before with a different email than the new one, add a `paypalApprovalError` parameter to the response like `PRE_APPROVAL_EMAIL_CHANGED`. Display this message properly in the frontend, where `paypalApprovalError` is currently displayed.

**Comment by snitin315** [comment]
@Betree Can this be a bounty? I would like to work on this one.

**Comment by Betree** [comment]
PayPal is a bit tricky to test sometimes, but if you feel good about it feel free to pick up the bounty. Check the docs if you need info on how to setup this: https://docs.opencollective.com/help/contributing/development/paypal#developing-testing-sandbox.

To test it, you can go to https://localhost:3000/{HOST}/dashboard and click on Refill Balance for PayPal.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
