### ISSUE TITLE
GitHub README shows not all backers (and sponsors)

### ISSUE THREAD

**Issue by punker76** [opencollective/opencollective#1578]
I want to list all backers (there are 12) on README of our site, but it shows only 7 and the `Become a Backer` picture.

These are the lines inside the README:

```
[![MahApps Backer](https://opencollective.com/mahappsmetro/backer/0/avatar)](https://opencollective.com/mahappsmetro/backer/0/website)
[![MahApps Backer](https://opencollective.com/mahappsmetro/backer/1/avatar)](https://opencollective.com/mahappsmetro/backer/1/website)
[![MahApps Backer](https://opencollective.com/mahappsmetro/backer/2/avatar)](https://opencollective.com/mahappsmetro/backer/2/website)
[![MahApps Backer](https://opencollective.com/mahappsmetro/backer/3/avatar)](https://opencollective.com/mahappsmetro/backer/3/website)

...

[![MahApps Backer](https://opencollective.com/mahappsmetro/backer/28/avatar)](https://opencollective.com/mahappsmetro/backer/28/website)
[![MahApps Backer](https://opencollective.com/mahappsmetro/backer/29/avatar)](https://opencollective.com/mahappsmetro/backer/29/website)
```

GitHub URL: https://github.com/MahApps/MahApps.Metro
README: https://github.com/MahApps/MahApps.Metro#readme
OpenCollective URL: https://opencollective.com/mahappsmetro

![image](https://user-images.githubusercontent.com/658431/50344851-1aa1f680-052d-11e9-8c1f-8b4183d911a2.png)

**Comment by znarf** [comment]
First, we're iterating on the Readme integrations and this is why the results might already looks different since your last report.

Here are a few problems I see today:

1) If you look at https://opencollective.com/mahappsmetro The results for the "$5 per month" are currently inconsistent. It's because the definition of the Tier might have changed in the history and you ended up having "One time donation" in this Tier. I would suggest you to create a new "Donation" Tier for "One time donations". After that, we would be able to move these donations to the new Tier.

2) In the Readme, the "Backers" widgets is currently reporting all individuals that have donated money. It's not related to the "Backer" Tiers themselves. We'll need to change the URL in the Readme, from `https://opencollective.com/mahappsmetro/backer` to `https://opencollective.com/mahappsmetro/tiers/backer`. That's easy.

3) Next problem is that you have 3 different "Backer" Tiers. Either you keep it like that, and they will have to be displayed  in separated sections in the Readme. Either, you decide to group them together in a unique Tier starting at 5$ (with 10$ and 15$ as additional presets). Like that, we would able to display all the backers together in the Readme.

Let us know what you think and we will help you make everything consistent.

**Comment by znarf** [comment]
@punker76 I'm slowly progressing on your case. I should have a PR ready for you later today or tomorrow. Thank you for your patience!

**Comment by znarf** [comment]
@punker76 What do you think of the Readme here?
https://github.com/opencollective/MahApps.Metro/tree/opencollective

**Comment by punker76** [comment]
@znarf 👍

**Comment by znarf** [comment]
It depends your definition of "Backers" and "Sponsors". On Open Collective, for historical reasons, we have conflicting definitions and this is why we are in this situation. See: https://github.com/opencollective/opencollective/issues/1368

To sum up:
- current: Organization -> Sponsor, Individual -> Backer
- my PR: "Sponsor" Tier -> Sponsor,  "Backer" Tier -> Backer

It's up to you.

**Comment by punker76** [comment]
@znarf Thank you for your help! I will use a mix with your suggestions. 👍
