### ISSUE TITLE
Display total recurring donations

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#1585]
## User story 
_As <persona>, I can <what?> so that <why?>_

As a collective owner, I can see the total amount of recurring donations so that my contributors and I can allocate our monthly budget.

## Best solution for this problem
_What does the ideal solution look like?_

The current amount of recurring donations (after fees/deductions) is easy to find for collective owners.

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_

I think a logical place would be the "Estimated Annual Budget" display.

![image](https://user-images.githubusercontent.com/2379650/50521664-c77ff480-0a94-11e9-9378-17be7265ab33.png)

## Metrics 
_What metrics will be used to measure impact?_

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

No new documentation necessary. If there is documentation with images containing the "Estimated Annual Budget" meter, those will eventually need to be updated.

**Comment by piamancini** [comment]
cc/ @Betree

**Comment by Betree** [comment]
It sounds like a useful piece of information :slightly_smiling_face:

Thanks for the suggestion @sloria!

**Comment by piamancini** [comment]
I thought we were getting rid of the stale bot @znarf?

**Comment by znarf** [comment]
@piamancini No, we decided to have it tag only the issues, not close them anymore. The message was also updated https://github.com/opencollective/opencollective/pull/1883/files This issue got the previous message, we changed it after.

**Comment by alanna** [comment]
@hzoo said he might be interested in building this

**Comment by hzoo** [comment]
I think it's a little complicated at the moment so we'll need to figure out some things (otherwise it seems like the original idea is simply to divide the current number by 12 and display that)? Some thoughts:

> I see this was brought up already via Pia/Alanna in https://github.com/opencollective/opencollective/issues/2216#issuecomment-509421385

I think the current calculations for an annual estimate amount sort of inflate what the the annual estimation is because it assumes any one-time donations will continue to happen in the future (just total up all contributions in the last year).

For our project maybe we would rather be conservative in the estimation and only include monthly donations (or if someone is actually donating year then you could divide it by 12). So it's not that they aren't meaningful but it seems less reliable to use those to make a decision on spending? This is more the case if you get a large one-time donation.

Maybe you could have the option? (depending on the project) to choose to only show the estimated monthly donations and basically ignore the one-time ones in that calculation? Even better you could show the change from the last month to the current month.

Maybe it's fine to show the total but it is more useful to know specifically the monthly amounts. So maybe something like (assuming the monthly was $1k) - will have to figure out wording

> "Estimated Annual Budget (Recurring)": ~12,000 USD (tooltip: Projected annual budget based on the recurring contributions from the current month. Does not include one-time donations in this estimation).

**Comment by sloria** [comment]
My proposal is to only show the sum of recurring monthly donations, minus fees and deductions. The total divided by 12 would not be useful for me.

For context, I split monthly donations between me and a co-maintainer. One-time donations are used for misc. expenses like merch and donating to upstream projects. So to determine the funds that go to me and my co-maintainer, I need to determine the recurring monthly revenue.

**Comment by Betree** [comment]
@sloria @hzoo Thanks for sharing your uses cases!

With the new collective page we're changing the way this information is displayed:

![image](https://user-images.githubusercontent.com/1556356/65324655-23535600-dbad-11e9-823d-e21f71252d16.png)

We've also added a tooltip where we could display more advanced information. 

![image](https://user-images.githubusercontent.com/1556356/65324717-51d13100-dbad-11e9-8702-7f4ce3cd15c2.png)

Based on what you both describe, I propose to keep the estimated annual budget view as it is today and to add the following breakdown in the tooltip:
- One time contributions in the last month: **$xxxx.yy**
- Monthly recurring contributions: **$xxxx.yy** / month
- Yearly recurring contributions: **$xxxx.yy** / year

@hzoo's suggestion to show the progress is also very good:

> Even better you could show the change from the last month to the current month.

**Comment by hzoo** [comment]
> My proposal is to only show the sum of recurring monthly donations, minus fees and deductions. The total divided by 12 would not be useful for me.

Ok great then we are probably on the same page then. Knowing the recurring (whether monthly or yearly which could be viewed as monthly) seems like the key as you can make decisions around that like in your case splitting it.

> One time contributions in the last month: $xxxx.yy
> Monthly recurring contributions: $xxxx.yy / month
> Yearly recurring contributions: $xxxx.yy / year

Yeah that could be good!

Would monthly also be calculated via the last month and same for year? Because those calculations wouldn't be the same as literally totaling all the funds in the last 12 months and I wonder how people will understand that.

**Comment by alanna** [comment]
In the interest of simplicity, maybe we could go with:

* Current balance
* Monthly recurring (I think we should include *recurring* annual donations divided by 12 in this total, excluding one-time contributions)
* Total all time *or* total this year *or* average annual budget (normalised across all years Collective has been active)

One thing I'm worried about is we need to design for different Collective types. Those participating in this thread so far represent Collectives where monthly recurring contributions are the main focus, but we also have Collectives funded mainly or only through large one-off contributions (e.g. grants), and we have to make sure they don't end up with misleading $0 figures showing prominently either.

**Comment by hzoo** [comment]
Yeah agreed that the options are important, some folks do rely on one-time and others monthly (or even the one you want* to rely on). Either way can skew what's really going on for both sides

**Comment by Betree** [comment]
Adding some specs so we can eventually move forward with this issue. I've included @alanna's [feedback](https://github.com/opencollective/opencollective/issues/1585#issuecomment-534317547) above, taking into account the fact that today's balance and average annual budget are already displayed.

# Specs

## API

- [ ] In [CollectiveStatsType](https://github.com/opencollective/opencollective-api/blob/a0e9414694f9629d64a04b43c7c19d321d184b67/server/graphql/v1/CollectiveInterface.js#L362), add a new `activeRecurringContributions` field that returns an object like `{ monthly: 4200, yearly: 6000 }` that sums up all the **active** subscriptions. Must be implemented with a Graphql loader.

- [ ] In [CollectiveStatsType > totalAmountReceived](https://github.com/opencollective/opencollective-api/blob/a0e9414694f9629d64a04b43c7c19d321d184b67/server/graphql/v1/CollectiveInterface.js#L449), accept a `startDate` and `endDate` parameters and pass them to `getTotalAmountReceived`

## Frontend

Thanks to these API changes you can now add the following lines in budget's section `Estimated annual budget` tooltip:

- Monthly recurring: **$xxxx** _(use `monthly + (yearly / 12)`_
- Total in the last 12 months: **$xxxx**

![image](https://user-images.githubusercontent.com/1556356/65324717-51d13100-dbad-11e9-8702-7f4ce3cd15c2.png)

**Comment by jamesgeorge007** [comment]
Taking this up :raised_hands:

**Comment by snitin315** [comment]
working on it.

**Comment by snitin315** [comment]
Looking into it.
