### ISSUE TITLE
Delete currencies fxrate

### ISSUE THREAD

**Issue by emilerousseau** [opencollective/opencollective#1662]
Not stored as constants. At the moment you have:

[currencies.js](https://github.com/opencollective/opencollective-api/blob/master/server/constants/currencies.js)

It seems potentially a relatively trivial task to have this update from an external source. If the update were to take place, say, once per day, this is unlikely to cause significant disruption to other app services. 

It might be interesting to consider, though, whether this information would be best stored centrally, and pushed to clients simultaneously, or whether it would be best to allow client computers to update themselves,  which I could forsee causing some synchronicity issues and potentially leading to users seeing alternative exchange rates.

Just some ideas anyway.

**Comment by znarf** [comment]
🏆 This issue was completed by @NotJohs as part as our first Hackathon (it started at at the event but was finished after). 

I retroactively added a $200 bounty on it. To claim the bounty, you can either:

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new

**Comment by znarf** [comment]
@NotJohs can you have a look at `generateFXConversionSQL`, it doesn't make any sense?

```
Homepage Error TypeError: Cannot read property 't.currency' of undefined
Nov 29 07:35:12 opencollective-prod-api app/web.1:     at /app/dist/lib/currency.js:70:45
Nov 29 07:35:12 opencollective-prod-api app/web.1:     at runMicrotasks (<anonymous>)
Nov 29 07:35:12 opencollective-prod-api app/web.1:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
