### ISSUE TITLE
Contribution flow > confirmed step: remove tags

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1696]
- [ ] Tags are a bit ugly there. I'd remove them or move them below "view your profile" with a text: "Search for other related collectives to support: #tag1 #tag2 ..."

- [x] Also the copy should read "You've contributed a total of"
otherwise it's not clear who contributed.

- [x] Also the "Share it" should be "Share on Facebook"

![](https://d.pr/free/i/4pfzJP+)

**Comment by Mayekita** [comment]
![all fixed tier 2 9](https://user-images.githubusercontent.com/46466094/53517469-46dd7480-3a94-11e9-94b2-d17381696987.jpg)
I made this mockup, basically I changed the card so instead of showing the tags, it shows either the public message or a quick description of the profile/organization. Also changed the buttons for the tweet it and share it, it would be too long to put "Share it on facebook" and It would look uneven, so i just add the icon for each social network.
I let the tags at the end next to the "view profile" button. @cuiki let me know if there are any feedback on this one.

**Comment by cuiki** [comment]
Looks ok. I'd limit the characters of the personal or organization profile so the card doesn't distort much with a lot of text.

Also, double check the copywrite. It should not say "Will contribute..." The user has already contributed at this stage.

**Comment by Mayekita** [comment]
Ok, there are just 140 characters which is the basic amount of characters, also we can make it 120 if that make sense. 

Also you are right on that, my bad made the changes:
![screen shot 2019-02-27 at 4 07 03 pm](https://user-images.githubusercontent.com/46466094/53526422-c6297300-3aa9-11e9-934e-d25c76a1e538.png)
