### ISSUE TITLE
tickets with a donation (gift) of 0 not “buyable”

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#1720]
**Describe the bug**
I setup an event with a ticket and a flexible “donation (gift)” with 0, 5, 10, 20 Euro price:
https://opencollective.com/symfony-diversity-speaker-mentoring/events/workshop-1-st-day-27586ev

When I then try to purchase the ticket with 0 Euros there are two issues:
* it ends up showing both the previously selected price and the 0 Euro with the “grey” background.
* when clicking “Donate” the “0 Euro” selection is lost, so it has to be selected again leading to the same issue again
* it also removes the payment options (which is correct) but when I then “Place order” it complaints that a payment option is missing

**To Reproduce**
1. Go to 
https://opencollective.com/symfony-diversity-speaker-mentoring/events/workshop-1-st-day-27586ev
2. Click on “0 Euro”
3. See both “0 Euro” and “10 Euro” having a grey background 
4. Click on “Donate”
5. See its back to  “10 Euro”
6. Click on “0 Euro”
7. See both “0 Euro” and “10 Euro” having a grey background 
8. Click on “Place order”
9. See error “This order requires a payment method”

**Expected behavior**
* Selecting “0 Euro” should remove the grey background from “10 Euro”
* “0 Euro” should remain selected after clicking “Donate”
* Clicking “Place order” with “0 Euro” selected should buy the ticket

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lsmith77** [comment]
was looking at the code (being a node.js n00b)

this line seems to ensure that payment is only required if the amount is larger than zero
https://github.com/opencollective/opencollective-api/blob/0ae50866998a555c6c3768f7e3ae2d95acbfb062/server/graphql/v1/mutations/orders.js#L222

however I suspect that the issue with the two amounts being “selected” is causing the root issue?

**Comment by znarf** [comment]
Ping @xdamman

**Comment by znarf** [comment]
Was that solved @lsmith77 @xdamman?

**Comment by xdamman** [comment]
A good workaround has been found over the weekend. For reference:

Usually people create a separate free tier for free tickets instead of offering zero has an amount preset. See what they’ve done for fearlesscities in Brussels. It worked quite well: https://opencollective.com/fearlesscitiesbrussels/events/september-2018

By doing it that way it also makes sure that people understand that if they pay nothing, it’s because someone else paid for a pay it forward ticket. It moves the burden of making the event inclusive away from organizers and to the community. Which is the way it should be if you ask me.

Final event:
https://opencollective.com/symfony-diversity-speaker-mentoring/events/workshop-1-st-day-27586ev
