### ISSUE TITLE
Break down in Platform Report platform fees from added funds

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1731]
we need to find a way for the accountants to know how much $$ in platform fees are currently held by hosts from manually added funds.  The platform fees amount in the monthly platform report doesn't break these down.

**Comment by xdamman** [comment]
See https://github.com/opencollective/opencollective/wiki/Queries#platform-fees

**Comment by xdamman** [comment]
![](https://d.pr/free/i/ipyvgg+)

**Comment by xdamman** [comment]
Actually, I realized that this was also counting the paypal payments to the 501c6 even though we don't get automatically the platform fee on them. Let me update the query to reflect that better.

**Comment by xdamman** [comment]
I think this is more clear:
![](https://d.pr/free/i/lW5KE7+)

I've also updated the query in the wiki (link above)

**Comment by xdamman** [comment]
Turned out to be even more complex because of gift cards. Some are linked to a Stripe account in which case we automatically get the platform fee, but some are linked to a prepaid card that is on the host.

I've updated the query to reflect that. Here is a quick preview of the updated results:
![](https://d.pr/free/i/px0lZQ+)
