### ISSUE TITLE
Report non-platform revenue

### ISSUE THREAD

**Issue by mcrosson** [opencollective/opencollective#1741]
## User story 
Report outside revenues. Particularly from direct donations via PayPal / other donation services users may prefer over OpenCollective.

## Best solution for this problem
Similar to expenses allow collective admins to report outside revenue/funding as an incoming balance and apply it to existing expenses / goals.

**Comment by piamancini** [comment]
@mcrosson we thought about this, and implemented a hacky version of it, allowing folks to submit in kind donations through the expense system. The issue we have is that at the core, open collective is a ledger that computes transactions and in order to compute a sponsor we would need to fake the entry of that amount and as a consequence we would have inaccurate accounting reports. We need to come up with a better solution. We have worked on a better ledger system that would enable us to have multi wallets per collective, which seems like the right way of doing it. We are still figuring out if we should prioritize continuing that, given that we don't have a strong use case for it.

**Comment by mcrosson** [comment]
With multi-wallet support collectives could in theory have ledgers for different platforms coming together in one place as a form of transparency that other platforms don't currently allow.

That said, I understand and appreciate the situation. If there isn't a strong need at present de-prioritizing the multi-wallet approach makes a lot of sense.

**Comment by piamancini** [comment]
you are absolutely right and more, it would enable us to better manage currency between host and collectives in different currency as well as having crypto wallets associated to a collective.
The only weakness in my argument about timing, is that by the time we have a pressing case (say we are out of the crypto bear market), we would still be a good couple of months out of having it ready... 
It's a balance, thanks for adding another chip in the scale! :)

**Comment by alanna** [comment]
This is achieved through `add funds`
