### ISSUE TITLE
Support SEPA payments

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1742]
User feedback:
> Any chance Open Collective could integrate [Single Euro Payments Area (SEPA)](https://en.wikipedia.org/wiki/Single_Euro_Payments_Area) payments See https://www.alternativepayments.com
This is more and more important in Europe.

**Comment by znarf** [comment]
This can be implemented through Stripe.

**Comment by kewitz** [comment]
I took a look into on how to implement SEPA payments using Stripe and this is my quick overview.

1. Creating payment Sources:
    1. We need to create new component for collecting SEPA information. (Account holder name, IBAN and Email)
        - This form should also display the [Mandate Acceptance](https://stripe.com/docs/sources/sepa-debit#prerequisite) message.
    2. We must also create a client on Stripe before we charge it. (Not sure if we're currently enforcing client creation)
    3. After creating the source we can immediately charge them.
2. Asynchronously Charging:
    1. Create an Order to track the status of this charge.
    2. We charge the SEPA source and wait for the callback.
        - Charged ALWAYS in Euros.
        - Can take up to 14 days to clear.
        - Include the order id in the meta information of the charge, we'll need that later on.
    3. Add a listener in our Webhook controller that process `charge.succeeded` events.
    4. Create a Transaction and update the Order status.
3. Subscriptions:
    1.  In the case of recurring payments, we need to make sure we're following [some rules].(https://stripe.com/docs/sources/sepa-debit#notifying-customers-of-recurring-payments)
    2. The notification should include our SEPA creditor identifier.
    3. New Cron job that create Notifications and send email to donors prior to charging them.
        - Stripe can do this automatically if we want to.
4. Refunds:
    1. Takes up to 5 days.
    2. If the client opens a dispute and win: these disputes can't be appealed and they incur in a fee. (EUR7.50).
    3. If a Refund is opened while a Dispute is claimed, the client might end up getting twice the value.

**Comment by rugk** [comment]
keep open

**Comment by rugk** [comment]
I also want to keep it in TODO, because that's quite important IMHO.

**Comment by rugk** [comment]
shh #badbot :no_bell::robot::no_bell:

**Comment by mkurz** [comment]
An alternative to Stripe would be https://gocardless.com/

Howver, you don't have to use 3rd party service for that. Sure, maybe it's easier to set up. However if you do have a bank account within the SEPA area you could implement everything yourself using the EBICS protocol: https://github.com/node-ebics/node-ebics-client
I did implement SEPA direct debit payments in Java once using EBICS and have quite some experience with it. If you need help let me know.
So basically how this works is you set up a EBICS contract with your bank (nothing special, it's usually just a service they provide, like normal e-banking), and then you are able to send signed xml payloads to a banking server which tells the bank what to do. That way you can initate recurring SEPA direct debits by e.g. running a monthly cron job. Nothing special.
You might need a bit of error handling in case the bank server is down e.g. for maintance, but that shouldn't be hard.

The only annoying issue that can occur is that the partner you try to charge does not have a sufficient balance on its account and the order comes back with an error, in which case you might get charged fees. However not sure how Stripe or gocardless handle that, because I don't thing they can work around that as well.

The advantage of that is that no one has to pay any fees to a 3rd party (however not sure if that would be much anyway) and you have full control over what's happening.

If you want to go down that road let me know, I may can help (EBICS looks a bit complicated, but its not if you understand how it works :wink:)

**Comment by alanna** [comment]
Someone requested this again today. Has anything changed since we last looked into it @kewitz @znarf ?

**Comment by bohwaz** [comment]
Hi, in Europe it's much easier to do a SEPA payment than go through Paypal when you are a non-profit, so it would be easier to contribute for us :)

**Comment by znarf** [comment]
Done. Feedback issue: https://github.com/opencollective/opencollective/issues/6290
