### ISSUE TITLE
Less css transparency behind logos in the collective cover

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1748]
It kind of bothers me the high level of transparency of the white background behind the logo of the top backers in the cover. I'd love to go from 50% to 90%:

Before:
![](https://d.pr/free/i/KXHnBD+)

After:
![](https://d.pr/free/i/VD4cnr+)

@cuiki what do you think?

**Comment by cuiki** [comment]
I'd actually go to full opacity. 100%

**Comment by xdamman** [comment]
Actually that doesn't work for a logo like [Triplebyte](https://opencollective.com/triplebyte) which is white:
![](https://d.pr/free/i/MRoGjw+)

Alternatively, we could use a 50% opacity black:
![](https://d.pr/free/i/Joizhy+)

**Comment by cuiki** [comment]
Ah, right. Well, in that same way, it won't work good with dark grey/black logos. This issue with PNG logos on different colored bg won't be solved like this. The new collective page addresses this from the root.

Will bringing the cover of each collective as the bg of these containers be too much? That is the only way we know it'll work for most if not all cases. Otherwise then yeah, white 80-88% might be good. Depending on how many white vs dark logos we have.

**Comment by xdamman** [comment]
You prefer white 80-88% than black 50% ?

**Comment by cuiki** [comment]
Its not that I prefer one over the other (white 80% vs black 50%). There is always going to be cases where the solution won't work because we accept solid AND transparent images as logos and place them on top of different colored backgrounds.

If I have to make a hard choice, I would say that we should go for the one that will make less amount of logos look bad (I'd need to find out how many we have and categorize them), but there's always going to be cases where it'll look bad until we fix it the origin.

With that said, given the examples a short answer is I'd go for black 50%.
