### ISSUE TITLE
Don't round monetary amounts in emails

### ISSUE THREAD

**Issue by adamchainz** [opencollective/opencollective#1773]
**Describe the bug**

When I get emailed about expenses, the subject features a rounded amount whilst the body features the exact amount.

**To Reproduce**

Submit an expense and get an email about it, e.g. when it is repaid:

<img width="963" alt="screenshot 2019-02-28 at 19 34 57" src="https://user-images.githubusercontent.com/857609/53589631-2b579400-3b90-11e9-8b3f-34ac1a11c4ee.png">

**Expected behavior**

Always use the exact amount to make it less confusing. It makes it easier to find "that £122.75 expense" and leads to precision in accounts.

**Screenshots**
See above
 
**Desktop (please complete the following information):**
N/A - email

**Smartphone (please complete the following information):**
N/A - email

**Additional context**
N/A

**Comment by znarf** [comment]
@adamchainz good point

**Comment by adamchainz** [comment]
But how to make it not stale?

**Comment by znarf** [comment]
@adamchainz commenting on it like you did :-)

Stale is just for us about surfacing issues. We'll try to tackle this one.

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by alabobriggs** [comment]
am from osca ph and I'll like to work on this

**Comment by Gbahdeyboh** [comment]
I'm from osca and i'm working on this already

**Comment by Gbahdeyboh** [comment]
https://github.com/opencollective/opencollective-api/pull/2364

**Comment by znarf** [comment]
@Gbahdeyboh Thank you for the PR in https://github.com/opencollective/opencollective-api/pull/2392 Can you share some screenshots of the emails?

**Comment by someofthethings** [comment]
Current guidelines state: https://blog.opencollective.com/scaling-up-our-bounty-program/ $100 minimum

**Comment by someofthethings** [comment]
@znarf thanks for the clarification snarf 🚀

**Comment by Betree** [comment]
:trophy: This issue has been resolved in https://github.com/opencollective/opencollective-api/pull/2392

Because @jeffin143 made the effort of testing and providing screenshots on the PR, we've decided to give him a bounty of the same amount.

 @Gbahdeyboh and @jeffin143, to claim the **$50** bounties, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:
