### ISSUE TITLE
Split out Open Source Collective and main newsletter

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1779]
Recently @xdamman pointed out that we include a lot of Open Source specific content in our monthly Open Collective newsletter, but in fact this is most relevant to the Open Source Collective users (most of the Open Source projects and their supporters), but not so much to people associated with other fiscal hosts, who might only want to know about new features and stuff affecting the platform overall.

Should we split the newsletters into 'everyone' and 'open source collective' as two seperate mailing lists?

If so, here's how I imagine we'd do it:

* Everyone who signs up for our newsletter or opts in when creating a user account gets the main newsletter, which only has content relevant to all users on all hosts.
* We make another list called 'Open Source' from all the core contributors, backers, sponsors, etc associated with the Open Source Collective and all the Collectives it hosts, where we share content about open source sustainability, new open source Collectives, etc.

Thoughts? Feedback?

**Comment by digitalextremist** [comment]
I've visited the issue a number of times, about to respond. I've not seen the newsletter long enough to "really" know, but I do think splitting into content channels is a good idea, possibly including other "top level" channels like:

* OC Program itself.
* F/OSS on its own.
* Regional / Focuses.

But this also had me wondering, since effort goes into it, couldn't it be the secondary source, and there could be means of flowing into readers outside email? Like some kind of RSS equivalent.

Going to a full-block magazine might be aggressive, but at least aggregating the content like an archived periodical, distributing it outside email primarily and sending excerpts by email, would be cool?

Or maybe this happens already and I'm just missing it.

**Comment by xdamman** [comment]
I like the idea. I’d argue that we should have one platform level newsletter then each host should have their own newsletter. The open source newsletter should effectively be the open source collective host newsletter.

**Comment by alannallama** [comment]
I talked to @piamancini and we decided to keep just one newsletter for now. This seems like it will be more relevant when other hosts make up more of the userbase.
