### ISSUE TITLE
Automatically donate to the npm modules that you depend on

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#178]
@btholt started this thread on Twitter with this idea:

> automated gittip based on npm installs / git clones. I say I want to give $100/month and it divides it automatically. [9:16 AM - 20 Jul 2016](https://twitter.com/holtbt/status/755798493764005888)

@BrianLeroux:

> I'd love to autopilot support our dependency tree
> [9:18 AM - 20 Jul 2016](https://twitter.com/brianleroux/status/755798974586458113)

@izs: 

> this is still on my dream list for @npmjs. It's hard! Probably someone else could build it first and we'll support it?
> [9:33 AM - 20 Jul 2016](https://twitter.com/izs/status/755802779432562688)

I wanted to create this issue to track this. I think this is something that the entire community will benefit from.

We also run into this issue here at OpenCollective. [iDoneThis](http://idonethis.com) just committed earlier this week $500/month to support the open source community. They've listed all their dependencies on their [OpenCollective profile](https://opencollective.com/idonethis). It's a very manual process and there is no automated way to spread that money across those projects ([and most don't have a way to receive money](https://medium.com/open-collective/a-new-way-to-fund-open-source-projects-91a51b1b7aac#.ky05pse2h)).

Also, we have [Auth0](http://opencollective.com/auth0), who wants to sponsor open source projects related to authentication (oauth, etc.). Here also, there is no easy way to do that.

We first need a standard way to link to a place where we can donate. What about adding a `"donations"` attribute in `package.json` at the same level than `name`, `description`, ... ?
E.g.

```
{
  "name": "mocha",
  "version": "2.5.3",
  "description": "simple, flexible, fun test framework",
  "donations": "https://opencollective.com/mochajs", // could also be a gittip/paypal.me url
  "keywords": [
    "mocha",
    "test",
    "bdd",
    "tdd",
    "tap"
  ],
...
```

People could put there the url to their paypal.me, GitTip/Gratipay/Liberapay (ping @whit537 @Changaco) or OpenCollective page.

Then, we could develop a command line tool (`npm-donate`?), that would automatically parse the dependencies tree and look for that `"donations"` attribute.

E.g.

```
$> npm-donate
What is your paypal email? xdamman@gmail.com
How much do you want to donate? $100
Donate that amount every month? [Y/N]
> Searching through your dependencies for modules that accept donations...
We found 23 modules:
  - MochaJS
  - lodash
  - ... 
Confirm [Y/N]: Y
> Redirecting you to PayPal.com for confirming the transaction
```

This opens a lot of questions such as what should the split be?
I'd suggest to start with the number of stars on Github/Gitlab as a first heuristic. We can always improve it over time based on experience. We could also let the user decide or choose between different algorithms.

What do you think?
Please ping people that could contribute to this conversation.

**Comment by brianleroux** [comment]
Couple of things. Heuristics could lead to creating weird incentives (as Issac mentioned in the thread) so I think a equal and flat split is the right edge of Occam's razor to target for starting. Secondly, my company isn't setup to use Paypal for discretionary expenses and so Stripe or similar would be better (friction-less) to get this rolling. I could see making things _opt-out_ with a dotfile but otherwise just assigning a dollar value to a repo which evenly pays out to the deps would be 👍.

**Comment by btholt** [comment]
I like the npm package idea, especially if npm buys in (which it seems they do.) I like the tool that searches through and finds donate-able projects.

I would suggest that based on npm/git usage you run this tool and brings up a prompt that says something like 
```
We suggest this split for you:

react: 30%
babel: 25%
mocha: 25%
[…]
```

At this point the user can play with the dials and get the split they feel is best. The downsize if you see libraries like `request` where they're often depended upon but rarely required by you, they may not be apt to donate to those, but at the end of the day that's the user's choice. Perhaps you ask them `Can we schedule a cron job to notify you for once a week/month/quarter for you to come back and readjust?`

At this point it asks `How much do you want to pay?` and then the user says $100/month and it automatically adjusts it according to their split.

**Comment by xdamman** [comment]
@brianleroux something like 50% for the repo and the other 50% evenly split to its dependencies?

I hear you on PayPal Vs. Credit Cards. We could help there using our API. We could donate the aggregated amount by credit card to the [Open Source Collective](https://opencollective.com/opensource) and disburse transparently the money to the dependencies. That's what we are doing manually now with [iDoneThis](https://opencollective.com/idonethis). 

Btw, this `"donations"` attribute could also be a bitcoin address. We should have different plugins to accept different donation methods.

**Comment by substack** [comment]
I don't think this will work well. Depending on charity doesn't scale very well and creates unequal outcomes where known personalities and projects which are already well supported capture the majority of the value along a power-law distribution, where value provided by open source is largely unseen, thankless work that nobody cares about or will notice.

Also, I think the fallout from the [gratipay money-transmitter issue][1] has shown the difficulty in operating a kind of many-to-many payment system legally while complying with relevant labor and financial regulations. I'm not sure how OpenCollective is addressing that issue, if at all.

[1]: https://github.com/gratipay/inside.gratipay.com/issues/192

**Comment by Changaco** [comment]
Hey @xdamman :-)

Adding the donation link in the package metadata seems like a great idea. The attribute should support multiple links though.

Regarding the split, I think the trick is in getting the money to where it's actually needed, and only the potential donees can tell you how much they need. Of course some kind of reputation or flagging system is also required to prevent donees from abusing the system.

https://github.com/liberapay/liberapay.com/issues/78 is a related issue on our side.

**Comment by xdamman** [comment]
@substack we are taking care of that with the concept of fiscal sponsorship. See https://medium.com/open-collective/a-new-way-to-fund-open-source-projects-91a51b1b7aac#.ky05pse2h

**Comment by nayafia** [comment]
I don't quite understand how this will work in practice. A lot of (most?) projects don't want or need money, and forcing them to opt out seems tedious. Obviously, I believe some projects could really benefit :) but I don't think this type of work can be automated, particularly not in an egalitarian way.

**Comment by xdamman** [comment]
@nayafia It would be opt in, not opt out since people will have to create an OpenCollective or a Gratipay/Liberapay/Paypal in the first place.

The automation part is more about making sure that if a project accepts donations, there should be a programmable way (machine readable way) to know about it. This would make http://fundingoss.com much more easy to maintain.

Then it's up to the donors / companies who use OSS, to decide how they want to donate and to whom. Such tool (`npm-donate`) would be helpers to reduce the friction to give to more than one project.

**Comment by nayafia** [comment]
@xdamman ah, got it. makes sense! seems useful for discoverability; getting ppl to tweak their donation allocations (or be ok with equal dividing) will be harder.

**Comment by btholt** [comment]
I hear and understand @substack's problem: big, shiny libraries (like React, Angular, Webpack, Babel) would command the lion's share of the prize if we gave users dials to adjust which libraries to send money to; it's a marketing game. However:

1. It is the user's money; they should ultimately decide where it goes.
1. I hope (perhaps in vain) that libraries like React and Angular wouldn't take donations since they're largely backed by big companies.
1. I think if you gave some indication to a user that they have an unknown library that they largely depend on that's underfunded, I think they'd be inclined to donate to it. Or perhaps I'm generalizing my own feelings. But I feel it's a UX issue that can be solved.

So I stick by my suggestion: automate and personalize the suggestion of which libraries to donate to; allow users to decide the split and which libraries get their money.

**Comment by xdamman** [comment]
@btholt Or, those shiny libraries should take advantage of their visibility to collect money and redistribute it down stream to their dependencies (or other related projects that they like who have less visibility).

Btw, I see that your employer Netflix is using GulpJS, any chance you can get them to [support their collective](https://opencollective.com/gulpjs@support)? They need funding :-) (see https://github.com/gulpjs/gulp/issues/540#issuecomment-233472532 by @phated)

**Comment by btholt** [comment]
Yeah, that would be great too.

As far as the GulpJS funding, I was informed that it's under consideration since someone else was contacted before me about it. Don't know any more than that.

**Comment by BenJam** [comment]
*leans into shot* we could do this for you through out API. *leans back out of shot*

**Comment by nemild** [comment]
I've been interested in this problem and did some research. Notes below.

All that said, my bias is to pick an ecosystem (say Node) and then make a judgment call of 15-30 packages that can receive donations from a crowdfunding page. Donors can change these allocations and other projects can sign up if they're not included over time. I also personally believe that there should be goals of how much a project receives at max, but that the aim isn't to make people rich off donations, just give them the basic support to keep doing what they love to do.

Let's scope the automated dependency payment into a few parts:

###Dependency Identification 
##### Determine one's *key* dependencies and their associated online repositories.

First, some quick research:

- Using `npm ls` to get a full dependency graph for a recent web project, I get ~2300 total dependencies, and ~1200 unique dependencies
- If I look through the `package.json` to find the first-level dependencies, I still have 88 of them (15 are babel-related plugins and 20 gulp-related plugins)
- In Ruby, I'd have say 30 first level gems for a web project

At minimal, there needs to be some judgment that specifies the core dependencies that should be paid - which users can then adjust. Otherwise, there are a lot of small, often inconsequential libraries. For example, all Gulp plugins might resolve to one Gulp entry. Same with Babel. Left pad is "important", but also something that may be ignored for donations.

I think someone needs to go through the top 1000 NPM downloads, and resolve them into a smaller group that actually can be considered meaty dependencies (I already know the main ones I care about, which is mostly foundational: node core, express, babel, bluebird, webpack, passport, lodash, socket, pug, requests, your ORM, etc.). It's pretty simple than to take one's dependencies and get a reduced list.

### Allocation
##### Determine how much a dependency should get

The easiest method is proportional allocation (based on number of dependencies, number of downloads, number of stars, etc). I like @xdamman 's approach of stars (with some human judgment).

Still, I think that Express (pre-IBM ownership) should get far more than its single dependency or even stars indicates. And if we used downloads, there are many small libraries (say left pad) with tremendous usage that would be rewarded.

Another question is how much to surface choice to the user. There are challenges with both extremes. As before, the right approach might be to come up with some judgment, and then allow users to override if they want.

### Payment Resolution
##### Identify how to pay an open source project

Ideally, this is agnostic of language/ecosystem. My bias is to a `donations.json` file (or `.md`) in the root of the repository. This allows non-JS related projects to participate. If JSON, this field can be integrated at first into the `package.json` field for NPM packages.

This file would list out the various ways to pay (e.g., Open Collective, Bitcoin, PayPal)

For example:

```
{
	"methods": [
		"paypal": "email@example.com",
		"bitcoin": "some_address",
		"open_collective": "url"
	]
}
```

### Payment
##### Pay a number of projects in an automated manner

I envision a curl-like tool that you can run to make payments. This means it needs access to your various payment accounts - and can make a transfer on your behalf. In the early days, we might just pick one payment method (say PayPal or an Open Collective account) - and then figure out an API endpoint to make a payment.

Part of the problem is that with many dependencies, the amounts may be very small. There are ways around this (pooling), but they inject complexity.

### User Acquisition

To get started, it's critical to get 10-15 leading projects in the community bought in and actively publicizing this. We have to address all the major concerns (injecting money into open source, how allocations are made, legal questions). It may also be helpful to run this jointly with a matching grant from a foundation to motivate people to donate.

**Comment by xdamman** [comment]
I love the idea of launching this with a matching grant from a foundation 👍 
Anyone has any connection to make this happen?

A few thoughts:
- Not all projects want to receive donations for various reasons and that's ok.
- Instead, I'd consider showing after `npm install` a list of the dependencies that do request donations and offer to donate to all of them in one go (pick a total donation amount and we'll take care of the rest). But we should also always offer the ability to manually pick a few you'd want to give money to.
- in both cases, and to reduce the number of transactions (and transaction fees), we could make one donation to an open collective (reusing the [Open Source Collective](https://opencollective.com/opensource) or creating a new one the "npm collective"?) and pass as a description the split to the different dependencies. Then, the money could be assigned to the different collectives or PayPal addresses of the different projects.
- I wonder how we could be integrated in the current user flow. To that goal, we released a npm module to automatically show a "please consider donating to our collective" at the end of `npm install` (https://github.com/opencollective/opencollective-postinstall) but people haven't been jumping on it yet (many are afraid of asking people for donations. I think we need a few first courageous projects who will lead the way and show that it works and that it doesn't bother users). Apparently it should go out in the next release of Preact https://github.com/developit/preact/pull/588

**Comment by BenJam** [comment]
>make a judgment call of 15-30 packages that can receive donations from a crowdfunding page

Danger Will Robinson! How are you going to make this judgement call?

> And if we used downloads, there are many small libraries (say left pad) with tremendous usage that would be rewarded.

Note: some package managers inflate download counts by pulling the complete tree for every package, rather than resolving down to a minimal I/O footprint.

We're (@librariesio) looking at a similar problem and open to helping establish a more comprehensive set of measures to identify infrastructure-type projects.

Personally  I'm interested in identifying projects that are open to the idea of receiving financial support (and getting it to them) *and* ways to safeguard those with an imploding community unable to accept support of any kind. 

>Not all projects want to receive donations for various reasons and that's ok.

So much this. 

> with a matching grant from a foundation

A grant application could work, it's not very sustainable. An endowment with government support would be much better... which I will be getting to at *some point* :)

**Comment by feross** [comment]
Hey everyone! I know it's been a while since this issue was opened, but I just discovered it while building [`thanks`](https://github.com/feross/thanks). I think it might be interesting to many of the folks in this thread.

`thanks` is a CLI tool that tells you which of your npm dependencies have authors who are seeking donations. Here's what it looks like in action:

![npm-install-thanks](https://user-images.githubusercontent.com/121766/36006055-a04f69de-0cef-11e8-8dfb-1e2df3555aaa.gif)

I punted on solving a lot of the hard problems discussed earlier in this issue thread, like payment methods, deciding how much to allocate to each maintainer, etc. The tool is deliberately simple -- it just tells you that a maintainer is asking for donations and directs you to their donation pages where you can read more and decide how much to donate.

I think it's a simple first step. It raises awareness that you may have dependencies looking for donations, but doesn't prescribe how much to donate or whether to donate at all.

We're also considering [supporting a new package.json field](https://github.com/feross/thanks/issues/2). Please share your thoughts!

The repo is here if you're interested in collaborating or discussing further: https://github.com/feross/thanks

**Comment by iandanforth** [comment]
I also just discovered this because of `thanks` and wanted to raise two points:

1. Are heuristics for the split needed?

By default an even split would result in the most used projects receiving the most money.
A customizable split would then be a good optional feature for people who want to allocate funds based on *their* heuristic.

2. If there is an automatic split + donate does this incent project hacking?

If all that's required to get funds sent to me is that I change a line in a package.json of a popular library then I very well might target a maintainers account.

**Comment by xdamman** [comment]
@feross this is awesome! Let us know if there are any specific API endpoints that you need from us. For example, would be awesome to be able to link your OC account and donate using your credit card on file directly from the command line.

**Comment by feross** [comment]
@xdamman Thanks, will do!
