### ISSUE TITLE
Consolidated yearly invoice

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1783]
Some sponsors prefer to deal with one yearly invoice instead of 12 separated invoices. 
We should offer a yearly consolidated invoice.

**Comment by Betree** [comment]
To make this happen: 

## API 

We should rely on the `Invoice` query. As of today, all the information is parsed from the invoice slug. It's not a good practice because there's no graphql validations on these params, so something we can do is to add new params that are used instead of the slug if provided:
- `dateFrom`
- `dateTo`
- `collective`
- `fromCollective`

The good thing about doing so is that the API would work in the exact same way for monthly, yearly or biannual invoices.

## Frontend

We need to specify where the links to the yearly invoices should appear. I propose that we add tabs on the invoices popup to choose between monthly and yearly:

![yearly_invoices](https://user-images.githubusercontent.com/1556356/54089772-dd4f4700-436c-11e9-9c35-b56e1e2b2f07.png)

## Invoices

The only thing needed in the invoices project is to add the new API requests and routes.

**Comment by pietgeursen** [comment]
I'm working on this.

**Comment by Betree** [comment]
Hi @pietgeursen, thanks for taking care of this issue! Just add a comment here or ping me on Slack if I can be of any help :slightly_smiling_face:

**Comment by pietgeursen** [comment]
@Betree 

# Invoice slugs and date ranges

At the moment there as an invoice "slug."
It's a string that looks something like: `201710.brusselstogether-host.xdamman`. 
Unfortunately the slug encoding can't represent date ranges.

## Implications for Invoices

The invoice slug is used to generate the invoice filename and reference field.
The invoice also has a `Date` field that used the `invoice.date`.

## Implications for the API + Invoices server

The api exposes a slug field on an invoice. That field is used by the frontend to generate links to the Invoice server.

Then the Invoice server uses those slugs to hit the graphql api to generate a specific invoice.

## Options

### Make a new slug format and upgrade all the code to use that new encoding. Don't be back compatible with the old format.

We could use something like: `201710-201810.brusselstogether-host.xdamman`

:-1: Breaking change to the api.

:-1: We still have invoice slugs.

### Make a new slug format (like the one above) but only use it when getting invoices with a date range.

We could keep the current Invoice route the same for old slug types and add a new one for invoices with a date range.

:-1: Then we have two encodings. All parts of the code need to be able to parse both sorts of encoding because graphql consumers expect an invoice to have a slug field.

:-1:  The graphql Invoice endpoint needs to be able to handle two different slug encodings + {dateFrom, dateTo, collective, fromCollective}

:-1: Code is harder to maintain.

:+1: Could be made back compatible

### Completely remove the invoice slug from the code...

:-1:  Breaking change to the api.

:+1: Will be most maintainable solution.

### Questions

**What should the Date field be on the invoice when a date range is used?**

**What should the reference field + filename be when using date ranges?**

**Which of the three options (if any) should we go with?**

PS: I'm happy to jump on a quick call if that's faster + easier.

cc @mixmix who's been working with me on this today.

**Comment by Betree** [comment]
That's a good thing to raise this up. I've been maintaining this legacy slug for backward compatibility but now that we've migrated invoices to their own service and that I have a better understanding of it, I'm confident that we should re-think that part instead of hacking it.

I don't like the fact that we use a slug because it breaks really easily and it's not extensible. For example I quickly patched it to use `.` instead of `-` because collectives like `my-collective` had broken invoices links (`201710-201810-brusselstogether-host-xdamman`).

So I'd be in favor of `Completely remove the invoice slug from the code...`, maybe we can progressively deprecate the endpoints using slugs so that the breaking change doesn't result in any error for users.

---

> What should the Date field be on the invoice when a date range is used?

I'd deprecate the `year`/`month`/`date` fields to instead use `startDate` and `endDate`.

> What should the reference field + filename be when using date ranges?

For transactions (no change): `transaction-{uuid}.pdf`
For all other invoices: `${host}_${fromCollective}_${startDate}-${endDate}.pdf`

(feel free to propose better alternatives)

**Comment by pietgeursen** [comment]
> maybe we can progressively deprecate the endpoints using slugs so that the breaking change doesn't result in any error for users.

What would this look like? I don't have enough context about the system. Is this something that can be done in the course of a day by deploying the right repos in the right order? Or are there other systems relying on this api that need time to adapt to a deprecated api?

**Comment by pietgeursen** [comment]
> > What should the Date ~field~ be on the invoice when a date range is used?

> I'd deprecate the year/month/date fields to instead use startDate and endDate.

Just to be clear, I'm talking about the pdf / html of the invoice. It has a date. But should it display the date range now? Any guidance on how you want that to look?

**Comment by Betree** [comment]
No other systems rely on this. Invoices are not a critical service so it's not a big deal if we aren't reverse compatible, however it's good if we can avoid broken links if frontend / invoices services are not updated at the same time.

The way to do that would be:

**API**

1. Add a `deprecationReason` on the old API fields ([example](https://github.com/opencollective/opencollective-api/blob/bd97592430fbcd4e34a20c2ec3f64e0ab629d034/server/graphql/v1/CollectiveInterface.js#L503))
2. Add the new fields

**Invoices**

1. Create the new endpoints (eg. `server.get('/:collectiveSlug/:host/monthly')`)
2. Add a comment on old endpoints to mark them as deprecated

**Frontend**

Change to the new endpoints, old endpoints should still work.

---

Once everything is deployed and tested, make another PR to remove all the deprecated fields and endpoints.

Migrating like that can sometimes be painless but again, if you hit too much walls while doing so then a breaking migration is acceptable for this service.

**Comment by Betree** [comment]
> Just to be clear, I'm talking about the pdf / html of the invoice. It has a date. But should it display the date range now? Any guidance on how you want that to look?

Yes it should.

- Invoice type transaction: year/month/day (no change)
- Invoice type monthly: year/month (no change)
- Invoice type yearly: year
- Custom range: year/month/day - year/month/day

Dates should be formatted with the `FormattedDate` component so we can easily localize them later.

So I guess the new endpoint should be something like:

```
/:collectiveSlug/:host/:type(monthly|yearly|custom-date-range)
```

**Comment by Betree** [comment]
Hi @pietgeursen, have you started to work on that one? I need to make some modifications to invoices but I'd prefer to do it once you're done to avoid conflicts.

**Comment by mixmix** [comment]
yes @pietgeursen has done 16+ hours of work on this - it's touching several repos. We (hi I'm from the same coop as Piet and paired for a couple of hours on this) need to catch up about where this issue is at, what standard you want this work to, and probably the size of it (time / money)

**Comment by Betree** [comment]
Ok I'll wait until we merge it then. In the same time I'm available on [Slack](https://slack.opencollective.com/) if you need anything.

**Comment by pietgeursen** [comment]
Hey @Betree,
I had a productive day on this today. I'm out of energy for now but I'm _really_ close to being done.

I'll have something for you to review in 24 hours I think.

I've got 3 WIP PR's that you can check if you like.

https://github.com/opencollective/opencollective-frontend/pull/1618
https://github.com/opencollective/opencollective-api/pull/1849
https://github.com/opencollective/opencollective-invoices/pull/30

**Comment by Betree** [comment]
@pietgeursen I gave them a quick look and it seems really good, the code is clear. Thanks for adding tests too. Please tell me when it's ready for review :slightly_smiling_face:

**Comment by pietgeursen** [comment]
@Betree Ok, I think they're ready. :smile:

**Comment by Betree** [comment]
Hi @pietgeursen! I'll review it today. In the same time I've updated the bounty amount for this task, my first evaluation for the complexity was really bad in regard of all the refactors needed.

**Comment by Betree** [comment]
You really did a great job on this one @pietgeursen. The code is clean, tested and you took the extra-step of refactoring the GraphQL queries properly so that it will be easier to maintain in the future. It was a pleasure to review it!

I'll merge everything on Monday.

:trophy: You can claim the bounty by submitting an expense to https://opencollective.com/engineering !

**Comment by mixmix** [comment]
<3 <3 <3

I'm planning to have a go at an issue soon.
Would be great to do a reflection on how the bounty process went for everyone. We can do this public/ private, and in text/ a call

**Comment by Betree** [comment]
@mixmix We should! We're learning on the process and are eager to improve the experience. I'm sure @alannallama and @znarf will be happy to join too.

**Comment by alannallama** [comment]
@Betree this can be closed, right?

**Comment by Betree** [comment]
Yep, it's live and working fine. Thanks again to Piet!
