### ISSUE TITLE
approving a collective from email is failing 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1797]
**Describe the bug**
Collective applies to the open source collective (not via the github flow), I hit approve in the email and I get an error that the token is invalid and I need to log in again. 

When I look in the database the collective was isActive = FALSE so hitting approve in the email didn't get the action expected. 

I signed in again and repeat with the same result. I manually set the collective as isActive = TRUE as I needed to unblock sponsor+collective. 

**Screenshots**

<img width="1268" alt="screen shot 2019-03-07 at 11 35 55 am" src="https://user-images.githubusercontent.com/3671070/53973038-ff776980-40cd-11e9-87aa-35ed25dc7f0f.png">

**Comment by znarf** [comment]
@piamancini The invalid token is normal, if you're clicking on an email older then 24 hours, and you are not already authenticated. This is current expected behavior.

Have you seen a confirmation screen somewhere? If you haven't and just saw a sign in screen, then it was certainly not approved.

Can you forward me the 2 emails.
- First approval one
- Sign In email after first approval attempt

Also, which collective was that?

**Comment by znarf** [comment]
@Betree can you take over tomorrow?

1) The invalid token in the approval email is not ignored as it should be (when the user is already authenticated)
2) The Sign In email sent afterwards (when following the instructions) doesn't redirect to where it should (encoding issue?)
