### ISSUE TITLE
markdown issues

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1799]
**Describe the bug**
Reported by Sindre

> I'm having some problems with the Markdown editor setting in https://opencollective.com/sindresorhus/edit/advanced Every time I turn it on (blue), and then edit my info in the "Info" tab, and then go back to "Advanced", the Markdown editor setting is turned off again. This results in my list looking weird

and then 

> I solved it. It was just Open Collective having weird restrictions on the Markdown. It only recognizes list items when they have an empty line between them. I was also confused because sometimes changes took 5-20 min to be visible.

Is is normal that we have this restrictions and the markdown changes take 5-20' (!!) to be visible?

**Comment by Betree** [comment]
I'd be in favor of getting rid of one of the two editors. We should pick the one that works the best and stick with it everywhere on the site. It would reduce the potential bugs exposure and the complexity of the code. Ideally we should reflect this change on the API by removing the `markdown` columns to keep only the `html`.

I don't see any value in making this setting configurable to the user, Github is a good example that you can have a markdown editor with buttons so that it's simple enough for anyone to use.

The delay to see the update should really be tackled too, it has probably something to do with the cache not being updated when the collective's description changes.

**Comment by znarf** [comment]
@piamancini I don't think the cache problem mentioned in this issue is related to markdown. Can we create a new issue for that?

**Comment by znarf** [comment]
If we put the cache issue aside, what do we have left as a bug here?

**Comment by Betree** [comment]
@znarf Nothing else than the cache issue. The discussion to remove the editor settings is moved to #1805 so we can either change the title here or create a new one for the cache problem.

**Comment by piamancini** [comment]
ok - closing this then @znarf feel free to do a new one for the cache if you guys want to tackle it
