### ISSUE TITLE
"sponsors.svg" and "backers.svg" are outdated

### ISSUE THREAD

**Issue by danielsun1106** [opencollective/opencollective#1802]
**Describe the bug**
"sponsors.svg" is outdated

**To Reproduce**
1. Go to 'https://opencollective.com/friends-of-groovy/sponsors.svg?width=890'
2. Compare the above sponsors with 'https://opencollective.com/friends-of-groovy'
3. Find the difference

**Expected behavior**
The sponsors in picture should be updated in time.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 72.0.3626.121

**Comment by znarf** [comment]
It's similar to:
https://github.com/opencollective/opencollective/issues/1368
https://github.com/opencollective/opencollective/issues/1578

This is happening because there is for historical reasons conflicting definitions of "Backers" and "Sponsors".

1. Tiers based: in your case $5+ -> "backer" $100+ -> "sponsor"
2. Type based: Supporting individual -> "backer", Supporting organization -> "sponsor"

In your Readme, this is the second definition that is currently used.

To match the "sponsor" tier, use:
https://opencollective.com/friends-of-groovy/tiers/sponsor.svg?width=890

**Comment by danielsun1106** [comment]
Thanks for your quick response.
I have another similar issue: 'https://opencollective.com/friends-of-groovy/backers.svg?width=890' is outdated too... Some sponsors appear in the backers too...

**Comment by znarf** [comment]
For backers, same problem, similar answer, use:
https://opencollective.com/friends-of-groovy/tiers/backer.svg?width=890

**Comment by danielsun1106** [comment]
Gotcha. Thanks :-)

**Comment by danielsun1106** [comment]
@znarf 
I found  'https://opencollective.com/friends-of-groovy/tiers/backer.svg?width=890' does not contains backer donating once(not monthly)...

How can I show all the backers?

**Comment by danielsun1106** [comment]
Or how can I show backers donating once?

**Comment by znarf** [comment]
@danielsun1106 in these SVGs, it's unfortunately not possible to target only backers donating once at the moment.

**Comment by danielsun1106** [comment]
OK. I see. Thanks.
