### ISSUE TITLE
title spacing needs fixing in expense page (payment method other) view 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1828]
words of input titles need correct spacing 

<img width="737" alt="Screen Shot 2019-03-18 at 1 08 21 PM" src="https://user-images.githubusercontent.com/3671070/54548909-4e9b8500-497f-11e9-8a97-36d3afb5d7e4.png">

**Comment by znarf** [comment]
🏆 This issue was completed by @anshumanv as part as our first Hackathon.

I retroactively added a $100 bounty on it (based on our previous complexity classification, it would have been a "minimal" in today's one). To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
