### ISSUE TITLE
Open Collective Pro - First features

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1830]
Open Collective Pro is a tier designed for individual users of the platform who want a better experience (Octobox model). During our last retreat we discussed how we can start fleshing this out. The tier would be $7 per month and it would give individuals access to enhanced features. These are the first two. 

# Invoices on the fly 

## User story 
_As contributor, I can input my information on an expense dashboard  that automatically generates and files the invoice_

## Best solution for this problem
_What does the ideal solution look like?_ Check out @alannallama's detailed issue about this here https://github.com/opencollective/opencollective/issues/1167

Adding a way to fill out / upload a w9 would be great (This might need to be available to everyone, since it's our responsibility) 

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_

## Metrics 
_What metrics will be used to measure impact?_
Number of users purchasing the pro tier. 

# Automatically file an invoice while forwarding an email 

## User story 
_As contributor, I can forward my monthly heroku invoice and automatically file an expense on the collective_

Contributors need to file the same expense each month and forwarding an email instead of submitting each expense individually will a great enhancement. Even more, it will increase how many expenses are filed in the platform which will increase a collective's activity.

## Best solution for this problem
_What does the ideal solution look like?_ 
I way to forward an email with an attachment that uploads de attachment as an expense? 

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_
Maybe an MVP would require user to create a first expense with the details (title, amount, vendor) and then each email updates the date and file only. 

## Metrics 
_What metrics will be used to measure impact?_
Number of users purchasing the pro tier. 

@Betree You've been working on invoices lately and you are also suffering from editing and uploading an invoice each month. Do you have thoughts on this? Is this something that interests you as a project?

**Comment by Betree** [comment]
### Invoices on the flight

Would be a nice to have but not a killer feature: there are a lot of apps or easy ways to do it manually. I personally like to generate those with my bank's app because it integrates smoothly with my accounting.

### Automatically filling expenses for recurring payments

=> Killer feature. One of the reasons why I actually stopped adding expenses for CaptainFact's hosting is because it is time consuming.

I like the email forwarding option, it saves the cost of having to download, navigate then re-upload the file and file the expense's details.

**Comment by Betree** [comment]
Possible specs for the automatic expense for invoices:

### Admin

- Navigate to `/{collective}/expenses/new-automation`
- Click on "Create a new automation"
- Fill the form
  - **Filters**
  - Trigger automation when the title contains the following words: __________
  - **Prefill info**
  - Description: `New recurring expense for _______`
  - Amount: *Keep empty to set the amount manually*
  - Category: _______
  - Payout Method: _____
  - Private Instructions: _________
  - **Save**

> Your automation is ready! Just forward your invoices emails to `invoice-4253@{collective}.opencollective.com` to add the expense on Open Collective.

### Usage

If all info have been provided, we add the expense directly. Otherwise we need to add a "pending expense" concept where we have prefilled some info but the form must still be submitted.

We can send a reply by email to users when they submit invoices:

> Hey! We received your invoice and created and expense for it on https://opencollective.com/{collective}/expense/4242. Please come and fill the missing info so the host can reimburse you.

### Things that this specs don't cover

- How to deal with emails with multiple attached documents
- How to deal with companies that don't attach invoices in email (eg. CloudFlare)

**Comment by piamancini** [comment]
I like the full automation idea - we will need to send a confirmation email with the details (user can always go and click on edit and expense). 

The host - as always - still needs to make sure invoice amount and expense are accurate.

**Comment by xdamman** [comment]
I can work on the create expense by email feature. The hard part is to figure out how to enter the data because OCR is not great for this yet.

Also, don't forget the badge: "Pro user".
It may sound silly but it goes a long way. 
We could also send them special emails to keep them posted on various developments, patreon style.
It's not only about features, but also about creating a sense of belonging to a community that shares the same values of sustaining open source (one could wonder whether this should be done at the platform level or OSC host level)

**Comment by Betree** [comment]
@xdamman In my opinion we should not try to extract any data from the invoice. OCR would probably not be necessary because most services send invoices with real text (not images) but extracting structured data from PDFs is a nightmare and often has a huge failure rate.

+1 for the badge!

**Comment by alannallama** [comment]
I'm not convinced a Pro offering should be directed at people filing Expenses. Aren't the ones with money really the sponsors? I feel like directing premium features at them makes more sense. 

There are only a tiny number of people filing expenses for a lot of money regularly, who would consider a pro version, and Collectives already perceive the percentage Open Collective takes in fees to be high. What have we done to validate users care about these features enough to pay for them, over and above what they already pay in fees? 

To me it seems like having multiple invoicing systems is going to create a lot more admin for us, and actually we have a responsibility to just fix the main invoicing and expense flow for everyone. Many of the changes I suggested in #1167 actually create the most value for Open Collective by reducing support requests and manual admin.

**Comment by piamancini** [comment]
You make good points @alannallama! 
I've had chats with @znarf and @xdamman about it as well. @znarf proposed a tipping model and @xdamman proposed to offer the users who purchase a subscription,   a badge and first access to features as we develop them. To this, we can also add that when we release a feature we include the names of those who helped us by purchasing a subscription.

**Comment by alannallama** [comment]
Sounds good @piamancini - what about directing the efforts of subscriptions toward encouraging people to give to the Open Collective Collective (or the Open Source Collective, etc). That way, we'd be in the same position as all the other projects on the platform who are backed by companies. We can be transparent about where the funds go, and direct them to pay for bounties and other expenses clearly for the open source community not just the company.

**Comment by znarf** [comment]
We decided to not tackle that project. Maybe we will revisit in the future.
