### ISSUE TITLE
Allow  admins to interact with event's expenses

### ISSUE THREAD

**Issue by samswag** [opencollective/opencollective#1868]
## User story 
Our collective created an event on the OC platform, but only one admin(the creator) had access to comment and interact with the expenses.

## Best solution for this problem
It will be great if all admin have access to event page.

<img width="1195" alt="Screenshot 2019-03-26 at 2 31 07 PM" src="https://user-images.githubusercontent.com/6048601/55001393-cb101280-4fd4-11e9-8e76-8286bebdbf30.png">

**Comment by Betree** [comment]
@samswag could you provide the name of the collective and a URL to the event? Thanks!

**Comment by samswag** [comment]
URL of the [event ](https://opencollective.com/osca/events/the-opensource-way-31395ev)

Collective name:
Open Source Community Africa

**Comment by znarf** [comment]
@piamancini seems you understood what that was well. can you provide input?

**Comment by piamancini** [comment]
Yep. Essentially what happenes is that the admins of a collective do not automatically become admins of the event. The person that creates the event becomes an admin but needs to add everyone else. This I think was done since we expected a larger collective group to manage events separately, but in truth it's confusing. 

@samswag the workaround is to manually add everyone else as admins of the event collective. 

@znarf the solution is to make all collective admins event admins by default?

**Comment by Betree** [comment]
This lead to another bug recently where an admin of a collective wasn't able to empty the event's balance because the person wasn't recognized as an admin of it.
