### ISSUE TITLE
Deleted Tiers appearing in collective monthly report

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1887]
**Describe the bug**

The monthly report is reporting Tiers that are deleted.

Reported by https://opencollective.com/typeorm

**From user**

> In the Collective March 2019 Report I’ve got `Sponsor ($100+ per month)`

https://www.dropbox.com/s/8h903tchaebrj0r/Screenshot%202019-04-01%2017.10.29.png?dl=0

> But they actually donate $50+

**Details**

It's currently difficult to understand the bug described by the user in the first place, because of the confusion between active tiers and deleted tiers.

Reading the code, looks like deleted tiers are loaded on purpose.

```
  Collective.prototype.getTiersWithUsers = function(
    options = {
      active: false,
      attributes: ['id', 'username', 'image', 'firstDonation', 'lastDonation', 'totalDonations', 'website'],
    },
  ) {
    const tiersById = {};
    // Get the list of tiers for the collective (including deleted ones)
    return (
      models.Tier.findAll({ where: { CollectiveId: this.id }, paranoid: false })
```

**Screenshots**

![Screen Shot 2019-04-01 at 18 14 55](https://user-images.githubusercontent.com/806/55342881-2006c980-54aa-11e9-9fad-bc9801add02b.png)

![Screen Shot 2019-04-01 at 18 15 35](https://user-images.githubusercontent.com/806/55342900-2bf28b80-54aa-11e9-8c47-ef80dccb7d4b.png)

![Screen Shot 2019-04-01 at 18 18 47](https://user-images.githubusercontent.com/806/55343103-afac7800-54aa-11e9-908a-796290e16b4b.png)

**Comment by xdamman** [comment]
It's normal that we report tiers that are deleted because some backers might still be in that Tier.
E.g. I create a "Gold sponsor tier", an organization ACME registers for it, then I delete the tier. In the monthly report we should still report that ACME is part of that deleted tier.

So this is an issue that is beyond the scope of the monthly report, it's about how do we manage deleting a tier.

The reason why it shows $100+ is because the presets for the tier start at $100 even though the default value of the tier has been set to $50.

We shouldn't be able to set the default amount to a value smaller than the minimum preset. I'm creating another issue for it.

Also I notice that some avatars are missing, we should show the default image using ui-avatars.com. Creating another issue for it.

Beside that, I don't see any other issue with this monthly report. So I wouldn't disable it.

**Comment by znarf** [comment]
From the user perspective, 2 things:

- if the Tier is displayed "Sponsor $50+ per month" in the collective page, it should be labeled as "Sponsor $50+ per month" in the email. Whatever the internal details.
- we should label deleted Tiers as deleted, otherwise it's confusing

**Comment by xdamman** [comment]
> if the Tier is displayed "Sponsor $50+ per month" in the collective page, it should be labeled as "Sponsor $50+ per month" in the email. Whatever the internal details.

Agreed. But the bug here is on the frontend, not the email.

> we should label deleted Tiers as deleted, otherwise it's confusing

Agreed. And we should also allow admins to move a backer to a different tier somehow. But that's beyond the scope of this issue.

**Comment by znarf** [comment]
My call. The definition of minimum amount that currently matters is the one that we use in the frontend, it's historical, what our users are exposed to and likely comfortable with. We'll fix the API to match this definition. https://github.com/opencollective/opencollective-api/pull/1892

In the meantime, we need to clearly give controls to admins on a minimum amount, we'll follow up on  that in: https://github.com/opencollective/opencollective/issues/1938
