### ISSUE TITLE
Shutdown collective with balance

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1907]
We need to deactivate the collective https://opencollective.com/climatewborders
but it has a balance of €1.79

The balance should go to the host but the host doesn't have a default collective.

So maybe we could record a transaction with amount = 0 and `hostFeeInHostCurrency` = 179 ?

**Comment by alannallama** [comment]
This is a dup of #1871

**Comment by znarf** [comment]
@xdamman I don't like it much. The cleanest options:

- create a collective for the host
- donate to another collective on the host

**Comment by piamancini** [comment]
Ideally all entities on open collective are collective with different functionalities. It's not efficient that a host needs to have an org and a collective. It should be one, with different tags/colors and the ability to add / remove functionalities. The new collective page is getting us closer to this.

**Comment by alannallama** [comment]
I believe in the case where a host is not storing their host fees on Open Collective (this one it seems), we should be able to just delete the balance off the Collective's ledger and logically, it will be 'given' to the host, because in this case the 'host fees' are just the difference between what's represented in their Collective balances and what is in their bank account. So if you click the 'zero collective' option on a Collective whose host has no default Collective, the balance can just disappear.

However, the larger issue is what @piamancini mentioned, that hosts should not have host entities and default Collectives as seperate things. There is an issue for there here: #1723
