### ISSUE TITLE
Feature Request: Add ability to create private updates

### ISSUE THREAD

**Issue by josegonzalez** [opencollective/opencollective#1923]
## User story 
As a collective maintainer, I can create a private update for backers/sponsors so that only backers/sponsors can see specific updates.

## Best solution for this problem
Ideally, a collective maintainer will see a checkbox that makes an update "private". We might further be able to target only backers, only sponsors, or only those contributing above a certain amount. The only public information would be the update title, and potentially an bit of text that can be specified by the collective maintainer. Finally, it might be nice to automatically publicize the update after a certain datetime.

## MVP
The MVP would be a checkbox that allows a maintainer to mark an update as private for backers/sponsors. Users can see that there is an update, but will not be able to view anything other than the datetime and title of the update. The Dokku Collective volunteers to test out this functionality.

## Metrics 

Private updates are a functionality of other similar platforms and allow maintainers to send out information that might be important regarding funds contributed and their usage.

## Documentation 

N/A

**Comment by Betree** [comment]
I had a similar use case a few months ago and I ended up downloading the members list (from `/:collective/edit/export`) to send an email manually.

We should support that.

**Comment by piamancini** [comment]
I think so too. @znarf has been talking about a paywall for collectives(I think).  The MVP sounds manageable. 

We would need to keep it simple at the beginning (without separating access per tier) because we still don't support backers/sponsors jumping tiers by increasing their contribution and therefore we can end up with sponsors giving the amount that gives them access but still not receiving the update. 

Happy to discuss further.

**Comment by josegonzalez** [comment]
That seems fine by me.

**Comment by josegonzalez** [comment]
I asked online, but is this something the Dokku collective could place a bounty on? I noticed that some other issues have bounties, and if possible, we can maybe help fund this functionality for our own benefit?

**Comment by Betree** [comment]
Sorry for the late reply @josegonzalez, we wanted to discuss this with the team first. We'd love to experiment something like this by co-financing this bounty with Dokku! I'll first write the specs below to give a rough estimate of how much work this is and what needs to be done.

**Comment by Betree** [comment]
# Specs

## API

- [ ] Add a field `isPrivate` (default=`false`) to the `Update` model
- [ ] GraphQL `allUpdates` endpoint: filter private updates if user is not a member
- [ ] GraphQL `Update` endpoint: return null for private updates if user is not allowed
- [ ] Allow `isPrivate` field for `createUpdate` and `editUpdate` mutations

## Frontend

- [ ] On create update form, add a `StyledCheckbox` that allows a maintainer to mark an update as private. The label must clearly explain what it's for: `Private update` - `Only contributors will be able to see this update`. This checkbox should also be displayed when users edit the updates.

![image](https://user-images.githubusercontent.com/1556356/56210214-9c2a1100-6055-11e9-8d5b-2f2cbae687e3.png)

- [ ] Show a lock icon on the update metadata with title="This issue is private"

![image](https://user-images.githubusercontent.com/1556356/56210146-77359e00-6055-11e9-886f-1bdbe628634e.png)

- [ ] Complete the tests in `cypress/integration/28-update.create.test.js` to cover this new feature
  - [ ] Create/edit update with `private` field
  - [ ] Icon presence
  - [ ] Random users cannot see private updates

---

*Notes*
- The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
- Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
- Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
- Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
@josegonzalez Does the [spec above](https://github.com/opencollective/opencollective/issues/1923#issuecomment-483647957) works for you?

**Comment by josegonzalez** [comment]
How would that impact any potential future enhancements, as per the "best solution" story?

**Comment by Betree** [comment]
The specs are based on the MVP. We should create separate issues for the others enhancements, unless it's critical for you to have them for v1.

---

> target only backers, only sponsors, or only those contributing above a certain amount.

This is compatible with the current specs, we'll be able to add a `limitedToTiersIds` field if we want to make that happen. 

---

> The only public information would be the update title, and potentially an bit of text that can be specified by the collective maintainer

What would be the use case for that? As I see it, an update is either fully public or private.

---

> Finally, it might be nice to automatically publicize the update after a certain datetime.

That should be possible too but I don't see a huge need as the proposed specs allow admins to edit the visibility of the update after is posted (so it can be done manually).

Again, I would love to hear the use case to better understand.

**Comment by josegonzalez** [comment]
1. Makes sense.
2. Cool, yeah that can be an enhancement later.
3. It would be a way to "entice" folks to back a collective. If you back the collective, you get more info than just the title :)
4. That workaround makes sense, though it would be cool for... automating that manual work in the future.

---

I'm more or less stealing this idea from Patreon, which is where I utilize these features.

**Comment by Betree** [comment]
I just went to see how [Patreon](https://user-images.githubusercontent.com/1556356/56247771-3d40b800-60a6-11e9-8754-8f3e76cbad8d.png) users use this feature and I better understand now. 

I also better understand the need for the automatic private/public switch, with things like "our backers get access to exclusive content 24h before". That will be worth adding the feature as a separate issue.

I've also updated the specs to reflect this change (public title, private content). We'll talk about it with the team today to confirm that this is how we want to do it.

Thank you!

**Comment by Betree** [comment]
@josegonzalez Green light from the Open Collective team :tada: 

You can send the amount that you want to add to the bounty for this issue to https://opencollective.com/engineering/donate, using your collective as a payment method (see below). For the reference, please mention the issue number in the public message left on the "Donation succeed" page.

We evaluate this to be a medium complexity (see our [bounty policy](https://docs.opencollective.com/help/developers/bounties))

---

![image](https://user-images.githubusercontent.com/1556356/56432645-722f5380-62ce-11e9-835c-1cb4c6a238a0.png)

![image](https://user-images.githubusercontent.com/1556356/56432792-11ece180-62cf-11e9-863d-79963a68a741.png)

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$300** bounty has been attached to this issue. 
:diamond_shape_with_a_dot_inside: $200 from @josegonzalez @ https://opencollective.com/dokku :tada: :heart:  
:diamond_shape_with_a_dot_inside: $100 from Open Collective

---

Anyone submitting a Pull Request will be rewarded with $300 when the Pull Request is reviewed, accepted and merged.

Specs: https://github.com/opencollective/opencollective/issues/1923#issuecomment-483647957

---

:arrow_right: [More info on bounties](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by Git-R-Goin** [comment]
I am very interested in this ticket and it would be great if I can work on this issue.

**Comment by Betree** [comment]
@Git-R-Goin thanks for joining in! You've been invited to @opencollective/developers, you can now push directly on Open Collective's repos (only master branches are protected).

You've got two weeks from now to complete this issue. Please tell us if you need any additional time, we can adapt when needed :slightly_smiling_face:

**Comment by Betree** [comment]
@Git-R-Goin didn't find the time to work on this. As the time frame is now passed, the bounty is open again for contributions.

**Comment by eloyekunle** [comment]
I will like to work on this.

**Comment by Betree** [comment]
Hi @eloyekunle, we'd love to have you on this one :slightly_smiling_face: 

Is the two weeks timeframe ok for you?

**Comment by eloyekunle** [comment]
@Betree Yes, the two weeks timeframe is fine.

**Comment by josegonzalez** [comment]
@Betree feel free to reach out to me on slack with any details on how to proceed with the bounty :)
