### ISSUE TITLE
Free tier contributors aren't displayed in the UI

### ISSUE THREAD

**Issue by johanricher** [opencollective/opencollective#1963]
**Describe the bug**
Contributors who choose the free tier contribution do not appear anywhere in the organization's page.

**To Reproduce**
1. A user creates a new OC account (e.g. [this user](https://opencollective.com/eloise-gabadou) has done so for the purpose to reproduce the problem)
2. They go on the organization's page (e.g. [Code for France's](https://opencollective.com/codeforfrance/))
3. They choose to become a contributor by selection the 1st tier option (free) (e.g. [Code for France's TierId 8544](https://opencollective.com/codeforfrance/contribute/tier/8544-membre-niveau-1)) 
4. Everything seem to work on their side (i.e. they get the Hourra! page)
5. Nothing happens on the organization's side. The contribution doesn't seem to have been registered.

**Expected behavior**
The usual signs that the contribution has been registered: email notification to the organization, the user appears on the organization's page, in the list of contributions, the contribution appears on the user's page, etc.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Free tier users seem to be partially registered:
[The correct badge](https://opencollective.com/codeforfrance/tiers/membre-niveau-1/badge.svg?label=Membre%20Niveau%201&color=brightgreen) (![Image](https://opencollective.com/codeforfrance/tiers/membre-niveau-1/badge.svg?label=Membre%20Niveau%201&color=brightgreen)) can be rendered from the API, although [the API doesn't return the users when requested](https://opencollective.com/codeforfrance/members/all.json?limit=10&offset=0&TierId=8544).

**Comment by znarf** [comment]
@johanricher thank you for reporting this.

@xdamman what do you think?

**Comment by johanricher** [comment]
Have you diagnosed the problems with your API? it seems to me it might be much deeper than the symptoms I have reported here...

**Comment by xdamman** [comment]
We never really foresaw the use case of a free tier. But it makes sense to support that use case.

This is how we get the data for that page:
https://github.com/opencollective/opencollective-frontend/blob/master/src/graphql/queries.js#L428

The problem is that all those orders have a `PENDING` status. This is the bug.
We should also make it better front end wise. We should just have to select the profile and then the button should be directly “contribute”. There shouldn’t be a step 2 (there is no amount to review) and 3.

**Comment by xdamman** [comment]
It looks like we are missing the case where the order does not require a payment and the collective is not of type of `EVENT`
https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/mutations/orders.js#L486

**Comment by znarf** [comment]
Ok, then it's more precise than that. It seems the problem in that case is that it's a free **yearly subscription** (`amount=0 type=MEMBERSHIP interval=year amountType=fixed`).

@xdamman Do we want to actively support that?

**Comment by johanricher** [comment]
The use case is to manage the membership of a non-profit organisation with Open Collective. I thought you were open to that.

**Comment by xdamman** [comment]
It’s a bit weird to have a free yearly/monthly tier (if it’s free, why should it be automatically renewed?), but in any case, it shouldn’t matter. 

When processing an order for which the `totalAmount === 0`, it should automatically be marked as `PAID` and not stay in the `PENDING` state.

@johanricher yes I think it’s a good idea to allow collectives to also have free tiers, in fact in the upcoming new collective page we want to make it easy for collectives to offer more ways for people to contribute. One way could be “give 1h of your time” which of course should be a “free tier”.

**Comment by johanricher** [comment]
>  we want to make it easy for collectives to offer more ways for people to contribute

I support this, Open Collective would match with a lot more use cases.

**Comment by johanricher** [comment]
A fix seems to have been deployed, following https://github.com/opencollective/opencollective-api/pull/2138

On [Code for France's collective](https://opencollective.com/codeforfrance/), I can now see the number of free tier contributors (9). I think this wasn't displayed before.

However this number is not consistent with the one given by the badge API: [![image](https://user-images.githubusercontent.com/10212787/60036348-502bc600-96af-11e9-8e0b-325b3b81b3b6.png)](https://opencollective.com/codeforfrance/tiers/membre-niveau-1/badge.svg?label=Membre%20Niveau%201&color=brightgreen)

An the list of users is still not returned by the API: https://opencollective.com/codeforfrance/members/all.json?&TierId=8544

**Comment by znarf** [comment]
@johanricher I will look into it.

**Comment by znarf** [comment]
https://opencollective.com/codeforfrance/members/all.json?TierId=8544 is now returning data. There was a missing data migration from the previous fix.

1) 5 PAID + 8 ACTIVE = **13** orders

This is the number of entries returned by the endpoint https://opencollective.com/codeforfrance/members/all.json?TierId=8544

2) Out of the 13 orders:

- 4 orders are from the same person
- and 2 orders from another person

13 - 3 - 1 = **9** orders once de-duplicated

This is the number exposed on the collective page https://opencollective.com/codeforfrance

3) 5 PAID + 8 ACTIVE + 5 CANCELLED = 18 orders

- 4 orders from the same person
- and 2 orders from another person
- and the 5 cancelled orders are from a third person

18 - 3 - 1 - 4 = **10** once de-duplicated

This is the current number of the badge

### Outcome

1) We're not gonna change this endpoint but we're currently building "v2" endpoints which should be clearer about what's exposed.

2)  There is a mix of one time and recurring donations in this tier, this is problematic. Should we also count CANCELLED orders here? I would say no, because it's a recurring tier. But we should not count one-time donations here then.

3) Should we continue to count CANCELLED orders here? I would say no, for the same reason exposed above.

###  Extra

- The tier is currently set at 0.01 euro instead of 0 euros, this is gonna cause problems. It should be fine with 0 now.
- It seems the Tier was edited from onetime to recurring in the past, this is causing problems. Maybe Open Collective should not allow that. Once the issue is settled, maybe you should contact people who donated once so that they subscribe to it, now that it's recurring.

**Comment by johanricher** [comment]
Thanks @znarf. 

I think the API is meant to list "members" i.e. all people who successfuly completed their membership. So I agree that cancelled orders should be dismissed completely or accessible only with an additional parameter in the API url.

Looking at the data, I see a lot of `"isActive": false`, are they the same as cancelled orders? If so, IMHO they shouldn't appear by default either.

> It seems the Tier was edited from onetime to recurring in the past, this is causing problems.

Yes this is very possible. I have to point that the tier types differences could be clearer ("Default tier" vs "Member (recurring)").

> There is a mix of one time and recurring donations in this tier

How do you see that in the data? I don't see that [in the first "free" tier](https://opencollective.com/codeforfrance/members/all.json?TierId=8544) (TierId=8544). I only see members with values in `lastTransactionAmount` and `totalAmountDonated` that are equal.

> The tier is currently set at 0.01 euro instead of 0 euros, this is gonna cause problems. It should be fine with 0 now.

Still not possible: the value fields in https://opencollective.com/codeforfrance/edit/tiers require an amount > 0: ![image](https://user-images.githubusercontent.com/10212787/60091648-68e6bb00-9745-11e9-80ca-1d56ae82be8c.png)

**Comment by johanricher** [comment]
It seems the issue has been resolved, thank you and keep up the good work!
