### ISSUE TITLE
Contribution Flow: blocked at first step

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1973]
**Describe the bug**

On a particular collective tier, I'm not able to go to the second step of the contribution flow.

**To Reproduce**

As a Signed In user.

1. Go to 'https://opencollective.com/mvvmcross/contribute/tier/2574-support-request'
2. Click on 'Next Step'

**Current behavior**

Nothing happens. There is an error in the console.

`Unhandled promise rejection TypeError: "Expected "verb" to match "events", but got "contribute""`

**Expected behavior**

No error.

**Comment by flickz** [comment]
@znarf The problem is, the affected collective tier "'Support request'' is a `type` of `TICKET` (meant for events) without associated `eventSlug`. 

TICKET tiers expect `eventSlug` in url when trying to createOrder like this (`http://localhost:3000/tipbox/events/flickz-conf-7ev/order/2805?amount=1000000`).

I think the solution will be for the collective to change the type from "TICKET" to a "generic tier".

**Comment by znarf** [comment]
Thank you for investigating that @flickz, closing.
