### ISSUE TITLE
Host dashboard: "Record as paid" button for PayPal

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1976]
In host dashboard, we sometimes have to pay PayPal expenses manually - for example when the amount is more than $2000. We need to have a `Record as paid` button  to account for these cases.

![image](https://user-images.githubusercontent.com/1556356/56945665-35622880-6b28-11e9-9d4c-49c5513f659b.png)

**Comment by alannallama** [comment]
This would be great! It also would need the 'payment processor fee' input box as well.

**Comment by flickz** [comment]
Is it fixed that any expense with paypal payment method and amount >= $2000 are paid manually?

**Comment by alanna** [comment]
Yes all expenses over $2000 are paid manually. However there are times when Paypal expenses less than $2000 are paid manually too.

**Comment by flickz** [comment]
I'm trying to ascertain the exact logic to use to display "Record as paid".

> However there are times when Paypal expenses less than $2000 are paid manually too.

How often does that occur? What could be reason?

**Comment by alanna** [comment]
If a user wants to take out 100% of the balance, we have to do the payment manually and then retroactively edit the amount of the expense because we can't know the fees in advance, so that requires manual payment.

We often pay manually for expenses less than but near to $2000, because re-authorizing the API key is really annoying to do for one expense as it takes a long time.

I can't think of other examples right now but it happens pretty often that we manually pay through Paypal for less than $2000.

So while it would be ugly and crowded, I think the best option would just be to have "mark as paid" and the "processor fee" box appear for every Paypal expense. 

Otherwise we have to do a hacky workaround where we make an edit, save, reapprove, then pay, triggering confusing notifications to the user. If you want data on how often we do this, you could look at instances of expenses edited from Paypal to Other payment type.

We are planning to do a project about improving the host dashboard after the expense flow project. At that time, we'll get the designers to come up with a better solution. But for now, I think the ugly solution would still be a big improvement.

**Comment by flickz** [comment]
It will look too messy, I think amount less than $2000 should wait for the new design solution while I implement this for amount greater than $2000.

**Comment by znarf** [comment]
@flickz please follow @alanna's direction, she's the one using the interface every day and needs this button even for expenses of less than 2000$.

**Comment by alanna** [comment]
Yes it's messy but only host admins see this and the entire host dashboard is messy! We need to do a big project to clean it up, but until then functionality is most important.

**Comment by flickz** [comment]
@alanna, In all use cases, will the value of processor fees always greater than 0?

**Comment by alanna** [comment]
Sometimes the payment processor fee is $0 and sometimes it is more than $0. So we need a "payment processor fee" box there, with the default amount set to 0 but editable, similar to what we have for manual payments now.

**Comment by alanna** [comment]
@alinamanko reports:

> one problem I discovered now is that for instances where there is a low balance and I process the payment manually (resulting in 0 fees) the option of Record as Paid still shows an error message like with this expense which has been successfully processed for payment but I can't mark it as Paid. In this case I still need to edit the expense and change the option to "other" for the payment be recorded as paid.

![image](https://user-images.githubusercontent.com/5498878/70279612-b64e7480-181b-11ea-8c70-ff5a5aa6d731.png)

**Comment by znarf** [comment]
@flickz have a look?

**Comment by flickz** [comment]
On it
