### ISSUE TITLE
Refunds by Collective admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1993]
## User story 
As a Collective admin (core contributor) I want to have the ability to issue refunds so I can respond to requests from my backers and sponsors directly.

## Best solution for this problem
Turn on the refund button for Collective admins for transactions in their Collective (currently only available to host admins)

## Todo list (added Sept 2020)

- [ ] security review
- [ ] make sure this is only available for Stripe/Paypal transactions, not manual

**Comment by alanna** [comment]
I think this will become even more relevant now that we're making it easier for users to contact Collective admins. It's likely they will get refund requests. I don't see any downside to giving them this permission, as long as they have enough balance in their account to cover the refund amount.

**Comment by Betree** [comment]
Re-opening after reverting the feature in https://github.com/opencollective/opencollective-api/pull/2679 and https://github.com/opencollective/opencollective-frontend/pull/2747 because there are some concerns that we need to address before making this feature public:

- We need to have a security pass to ensure that it's safe to open the refund function to collective admins. Because (1) it was previously limited to hosts and root users (that we can trust more than collective admins) and (2) this function is quite powerful (it can move real money out of a Stripe account) we may want to be more defensive on the code and what we allow.
- There was an issue in the way it has been implemented in https://github.com/opencollective/opencollective-api/pull/2679 - users could have refunded their own transactions by passing the `DEBIT` transaction instead of the `CREDIT` (because in debit `transaction.collective` is the user making the transaction, not the collective).
- Allowing collectives to refund manual transactions is strange, because they're not the ones in charge of the bank account. We may not want to allow that.
- Is it safe to let users refund all transactions, regardless of the date? (@piamancini suggested we should only allow 30 days)

**Comment by sbinlondon** [comment]
Can I get an update on this? When I run local dev environment with the test account, I can see a 'Refund' button on transactions for the Brussels Together collective. But don't think the feature has been released elsewhere?

What is the latest status on this and were any of the issues in @Betree's last comment fixed/addressed/discussed?

**Comment by Betree** [comment]
@sbinlondon are you an admin of the Brussels Together host? The current status is that only host admins can refund transactions.

Regarding my previous comment:

> We need to have a security pass to ensure that it's safe to open the refund function to collective admins. Because (1) it was previously limited to hosts and root users (that we can trust more than collective admins) and (2) this function is quite powerful (it can move real money out of a Stripe account) we may want to be more defensive on the code and what we allow.

We did some security improvements, but not a full review. Enabling the feature is a one line change, but I still think that we should review the security properly before doing so.

> There was an issue in the way it has been implemented in opencollective/opencollective-api#2656 - users could have refunded their own transactions by passing the DEBIT transaction instead of the CREDIT (because in debit transaction.collective is the user making the transaction, not the collective).

This is fixed.

> Allowing collectives to refund manual transactions is strange, because they're not the ones in charge of the bank account. We may not want to allow that.

Not sure about what to do with that, but we should keep this case in mind. If the collective mark a manual contribution has refunded but the host haven't done so, there will be a problem.

---

Also we should probably solve this before allow collective admins to refund: https://github.com/opencollective/opencollective/issues/1656

**Comment by sbinlondon** [comment]
> @sbinlondon are you an admin of the Brussels Together host? 

Only using the `testuser` account on local dev.

> We did some security improvements, but not a full review. Enabling the feature is a one line change, but I still think that we should review the security properly before doing so.

Would it possibly be a candidate for adding 2FA to as an extra layer of security? And what specifically will we need to review to figure out if it's ready?

> Allowing collectives to refund manual transactions is strange

Agreed and I think it should be limited to Stripe/Paypal (if possible?)/gift card contributions (if that makes sense to do)

**Comment by Betree** [comment]
> Would it possibly be a candidate for adding 2FA to as an extra layer of security? And what specifically will we need to review to figure out if it's ready?

Could be, but the goal here is really to know if the feature is safe enough to open to any collective admins because we can't have the same level of trust in collective admins than in host admins when it comes to payment-related stuff.

> Agreed and I think it should be limited to Stripe/Paypal (if possible?)/gift card contributions (if that makes sense to do)

Maybe, but then we may need to iterate later with a "Request refund" button. It's hard to explain to collectives why they can't reject contributions made via bank transfer.

**Comment by sbinlondon** [comment]
This is now out but with the limitation that Collective admins can only refund (and reject, if the feature flag is enabled) transactions up to 30 days in the past.
