### ISSUE TITLE
Graphql API stopped returning transactions

### ISSUE THREAD

**Issue by sheerun** [opencollective/opencollective#2005]
**Describe the bug**

We used following GraphQL query to fetch list of transactions to compute list of current sponsors:

```
{
  account(slug: "bower") {
    transactions(limit: 2000, type: CREDIT) {
      nodes {
        type
        amount {
          value
          currency
        }
        createdAt
        fromAccount {
          name
          slug
        }
      }
    }
  }
}

```

Right now this query returns `null` for `account.transactions.nodes`.. Could you fix it?

**Comment by znarf** [comment]
@sheerun Sorry! Didn’t know you were already using the GraphQL API v2. I’ll fix it promptly.

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/opencollective-api/pull/1958

We will add tests for common GraphQL v2 queries so that it doesn't happen in the future.

Also, for the future, be careful with `limit: 2000`, we don't enforce today a maximum for it, but it's possible we will add one, such as `1000`. To get more entries, you will need to paginate with `offset`.

**Comment by sheerun** [comment]
Thank you <3

**Comment by sheerun** [comment]
btw. I'd set much lower limit but there's no way to sort nodes. I'd like to show e.g. 200 latest transactions

**Comment by znarf** [comment]
@sheerun in your query, transactions are sorted anti-chronologically by default.

You can play with it, trying `DESC` or `ASC` as sort direction.

```
{
  account(slug: "bower") {
    transactions(limit: 200, type: CREDIT, orderBy: { direction: DESC }) {
      totalCount
      nodes {
        type
        amount {
          value
          currency
        }
        createdAt
        fromAccount {
          name
          slug
        }
      }
    }
  }
}
```
