### ISSUE TITLE
Keep filters when refilling paypal balance

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2018]
## User story 

As a host admin, I want to keep my filters and my place in my list of expenses to pay, so I don't have to reset everything each time I refill the paypal balance.

## Best solution for this problem

Alternatively, the system could at least remember your filter preferences when it send your back to the host dashboard screen, if doing the process in another window isn't possible.

## Metrics 

Pay expenses faster.

_Edited on September 16th to integrate feedback from @Betree and @alanna_

**Comment by Betree** [comment]
The problem with that is that we need to refresh the page once the flow is completed to account the money that has been added from PayPal. I just tried locally and it makes the displayed balance go out of sync because it is configured to show the balance of the payout method `A` and when you refill the balance it actually creates a new payout method `B`.

I agree that it's not a great experience but I'm afraid there may be side effects if we don't refresh the page. Keeping the filters after the redirect would be easier.

**Comment by alanna** [comment]
I think keeping the filters after redirect is a good solution. That would help a lot, because right now I need to continually reload the right filter and the page is so slow.

**Comment by flickz** [comment]
@Betree I'm trying to test this out but I'm unable to sign into the paypal sandbox account, do I need to create my own account separately?

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/opencollective-frontend/pull/2786
