### ISSUE TITLE
Users with empty email

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2039]
There are 534 rows in the user table where email=NULL and collectiveID is not. From these 438 are not deletedAt... 

The latest user created like this was created  2019-02-15 10:57:35.668+00  So they are pretty recent. 

@xdamman any ideas?

**Comment by Betree** [comment]
Last entry is still `2019-02-15 10:57:35.668+00` so whatever bug caused it this seems to be resolved now. However I'd like to take active steps to ensure we protect the system against this in the future because we always expect users to have an `email` in the code:

1. Users without email and without a collective (91) should be marked as deleted
2. Mark all users with null email and no transaction/expense as deleted
3. Set emails for all users with `null` email to something we own like `user-missing-email-${id}@opencollective.com`
4. Add a `NOT NULL` constraint on all emails

**Queries**

```sql
SELECT COUNT(*)
FROM "Users" u 
LEFT JOIN "Collectives" c ON u."CollectiveId" = c.id
WHERE email IS NULL
AND c.id IS NULL
AND u."deletedAt" IS NULL
```

**Comment by znarf** [comment]
I recently had to add defensive code to protect about Users without Collectives recently, they're likely due to failures in the middle of the sign up process. Good idea to delete these.
