### ISSUE TITLE
Ability to embed videos in long descriptions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2043]
To allow embedding videos we need to add a list of `trustedThirdPartiesForIframes` (including `YouTube` as a valid provider) and to add a custom validator to allow iframes **only** if the URL is from a trusted third party. 

Once this is done we can enable the video button in the editor.

Before enabling this feature for Updates, we'll also need to work on something to adapt the content before sending the email (replacing the iframe with a link + video picture).

**Comment by mlncn** [comment]
This is such a key feature for the Updates section!

`trustedThirdPartiesForIframes` should include:

vimeo.com
youtube.com
kolektiva.media
breadtube.tv
peertube.ch
tube.cloud-libre.eu

and i'm sure i'm missing plenty of reputable instances.

**Comment by alanna** [comment]
+1 to this! It's fine to only allow videos from select sources, like Youtube and Vimeo. Lots of sites do that. Also fine to just do this for About descriptions as a first step and then look at Updates later, because we definitely need them for About sections.

**Comment by Betree** [comment]
API now supports this in `server/lib/sanitize-html.ts`, so this issue is mostly about adding a button in the `RichTextEditor`

**Comment by SudharakaP** [comment]
@Betree : I can help on this one if this is something we are still interested in. Few things to clarify are; 

1) As an initial MVP this is only for the long description in the collective page? Or should we do any other pages too? 😺 

2) I have to look into adding a new button to Trix editor but is there a specific design or something that is agreed upon for the button design? 😺

**Comment by Betree** [comment]
1. Yes, for the MVP we should limit this to the collective page.

2. There is no design defined, the button should look like the others in the toolbar. Any video icon from styled-icons would do the job

**Comment by SudharakaP** [comment]
@Betree : I've added support to add attachments. Now this one was a bit tricky as the Trix editor doesn't support [embeds in the usual way](https://github.com/basecamp/trix/issues/120#issuecomment-161064186); I had to add some special functions to solve the editability issues. Anyways let me know how it looks or anything else needs to be done. 

One thing to notice is that currently [we allow only YouTube and Vimeo](https://github.com/opencollective/opencollective-api/blob/540bd335f4b7bc2587c48ea863b5dc7f973a5fc4/server/lib/sanitize-html.ts#L90). And we need to give the embed url (see screencast) from those sites for the embeds to work. Otherwise it seems that YouTube and Vimeo blocks the embeds from happening. Here's my suggestion for this;

What we could do potentially for YouTube and Vimeo is to take the given URL and construct the embed URL; so user enters say, https://www.youtube.com/watch?v=LOMbySJTKpg and we take the last character set (`LOMbySJTKpg`) and the embed url would be, https://www.youtube.com/embed/LOMbySJTKpg. Similar thing could be done for Vimeo. But this would be specific to the service. If we plan to embed videos from other sites we'll have to add these constructions for each one separately). So I was wondering if we should just leave things be and let the users put the embed URL themselves or construct a function to do this for the user so the user can just paste the URL of the video he is viewing? I am inclined to adding these constructions as otherwise it won't bet he best experience for the users. WDYT🤔 

Let me know your thoughts. 🤔

**Comment by Betree** [comment]
> What we could do potentially for YouTube and Vimeo is to take the given URL and construct the embed URL; so user enters say, youtube.com/watch?v=LOMbySJTKpg and we take the last character set (LOMbySJTKpg) and the embed url would be, youtube.com/embed/LOMbySJTKpg. Similar thing could be done for Vimeo. But this would be specific to the service. If we plan to embed videos from other sites we'll have to add these constructions for each one separately). So I was wondering if we should just leave things be and let the users put the embed URL themselves or construct a function to do this for the user so the user can just paste the URL of the video he is viewing? I am inclined to adding these constructions as otherwise it won't bet he best experience for the users.

Let's start with these two, we'll add other ones if users request them. For YouTube, the following regex server me well in the past to extract the ID from any YouTube link (works with embed, no-cookie or regular links):
```
(?:https?:\/\/)?(?:www\.)?youtu(?:\.be\/|be.com\/\S*(?:watch|embed)(?:(?:(?=\/[^&\s\?]+(?!\S))\/)|(?:\S*v=|v\/)))([^&\s\?]+)
```

**Comment by SudharakaP** [comment]
@Betree : Thanks, I did some further investigation and found the following library; 

https://github.com/radiovisual/get-video-id

This can handle both YouTube, Vimeo and some other popular service urls (vine, videopress and microsoftstream) if we ever decide to support them. I've integrated this one instead. That way I feel this is more future proof. 😄 If you have any objections to this let me know. 😸 

Also as a side note I've added a small label at the bottom of the video dialog to indicate the users that only YouTube and Vimeo are supported.

**Comment by Betree** [comment]
Since it's only two providers at the moment, I think having two dedicated regexps will do the job fine - I don't see the need for a third party library yet.

> Also as a side note I've added a small label at the bottom of the video dialog to indicate the users that only YouTube and Vimeo are supported.

Great idea!

**Comment by SudharakaP** [comment]
> Since it's only two providers at the moment, I think having two dedicated regexps will do the job fine - I don't see the need for a third party library yet.

@Betree : I've adjusted the PR to include the two regex expressions. Think it looks all good for review now. 😄
