### ISSUE TITLE
Generate automatic pages of Collectives based on tags

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2053]
## User story 

As a user, I want to be able to see groupings of Collectives across various fiscal hosts that share other characteristics in common.

As a Collective admin, I want to be able to label my Collective with different tags so that it's more discoverable.

As a member of a network of Collectives, I want to be able to see a page with all Collectives tagged with that label.

As a contributor, I want to be able to easily discover Collectives according to my criteria.

Currently we have tags on Collectives, but it's not implemented to the level we need to achieve these outcomes. Right now, admins can add tags but they are not displayed on the Collective page, and we don't have an easy way to display all Collectives with a given tag.

This intersects with the concept of "supercollective" which is an idea that was never fully implemented and isn't defined or documented. I think we should drop that term and just focus on useful ways to group Collectives with tags.

## Best solution for this problem

Create a format like www.opencollective.com/tag/drupal which will show all Collectives tagged #drupal (current use case motivating desire for this feature). This should work for any tag.

We have https://opencollective.com/meetups as an example, but this had to be created manually. Instead, we should automatically display all Collectives tagged #meetup, and a similar page should be generated automatically for any tag.

The meetups page has a description section, which I think is useful, but that leaves the question open as to who will have permission to change that content. I suggest for now we let go of the description element and implement it later if we hear from users that it's necessary.

The system should automatically put a country tag on for Collectives that have told us their country in their settings (already an option).

Search should still work on keywords, so all Collectives that mention Drupal in any way would come up if you search "Drupal", but only Collectives *tagged* #drupal would come up if you search "#drupal" (similar to how it works on Twitter).

## MVP
URLs like opencollective.com/tag/drupal display all Collectives tagged #drupal.

## Metrics 
Page loads of tag pages, more Collectives joining from networks that get a generated page of all the related Collectives.

**Comment by Betree** [comment]
Sounds redundant with two existing pages:

- Search: https://opencollective.com/search?q=drupal will show all the collectives that are tagged with `#druppal`

- Discover: Has a tag filter, though we're going to revamp it a little bit with https://github.com/opencollective/opencollective/issues/1387

Could we cover these use cases by completing one of this existing pages?

**Comment by gusaus** [comment]
I'm actually not sure Drupal is the best example since Open Collective integrated into projects on https://www.drupal.org/ and https://git.drupalcode.org/ would leverage the robust system for categorizing, search and filtering already built into Drupal. Integration should also provide a conduit for funds flowing into Open Collective from potentially thousands of projects and community initiatives. 

Improvements to search and discovery will certainly help (I left some related suggestions in https://github.com/opencollective/opencollective/issues/1745#issuecomment-474872514) but a page that groups together collectives based on tags won't have that much value.... unless of course they are grouped together in a form of a supercollective where funds can flow downstream and upstream.

**Comment by alanna** [comment]
@Betree I think you're right, and some small improvements to the existing pages would be enough for now. Given @gusaus doesn't think this is really what Drupal needs, I'll close this.
