### ISSUE TITLE
Allow editing of "core contributor since" dates

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2076]
## User story 
As a core contributor, I want the date appearing under my name to reflect when I joined the project itself, not when I joined on Open Collective, so that we can recognize long-term contributors and not have misleading info on our page.

## Best solution for this problem
Allow the "core contributor since" dates to be editable by Collective admins. Probably as a setting on the "members" screen in "edit Collective".

## MVP
Enable platform admins to change these dates on request from users.

## Context

A new Collective was getting set up and they have been working on the project for years, so they feel the dates that are displayed are really off.

![Screen Shot 2019-05-30 at 4 24 05 PM](https://user-images.githubusercontent.com/5498878/58608450-b7946700-82f7-11e9-8f85-9cf38b4f277e.png)

**Comment by samus-aran** [comment]
Agreed! Would love to see this implemented. :+1:

**Comment by Betree** [comment]
Today we rely on `createdAt` to display this information. Changing this value can be considered as a bad practice because you loose the real historicity of the records. For example we can use this information for statistics, to know how many members are added each month.

So a proper way to do this would be:

**API**
- [ ] Add a `since` column to members (null=false, default=NOW())
- [ ] Makes sure the migration uses `createdAt` as the initial `since` value for all existing members
- [ ] Make it available in GraphQL query/mutation for members

**Frontend**
- [ ] Use this new field for the `MemberCard`
- [ ] Allow field to be edited in `EditMembers`

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. Please add a comment below if you want to be assigned to this issue.

:hourglass: Time to complete: 10 days
:notebook: Specs: https://github.com/opencollective/opencollective/issues/2076#issuecomment-498209068
:arrow_right: [Bounty policy](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by leonardohof** [comment]
Hi,

I want to work on this issue. Can you assign to me?

**Comment by Betree** [comment]
@leonardohof Done :heavy_check_mark: 

Please ask if I there's something I can do to help.

**Comment by leonardohof** [comment]
> @leonardohof Done 
> 
> Please ask if I there's something I can do to help.

Ok, thanks.

**Comment by leonardohof** [comment]
https://github.com/opencollective/opencollective-frontend/pull/1890
https://github.com/opencollective/opencollective-api/pull/2063

**Comment by Betree** [comment]
Both PRs seem very good @leonardohof! Special kudos for using a transaction in the migration (one could argue that running migrations inside of transactions should be sequelize's default behaviour). And also for providing all the translations :wink: 

Let me rebase both PRs in-house so we can have the CI properly running. BTW you've been added to https://github.com/orgs/opencollective/teams/developers so you're allowed to push directly on API/Frontend (except master branch).

**Comment by Betree** [comment]
Let's wait for frontend to be merged to close this

**Comment by Betree** [comment]
Thanks for handling this @leonardohof, you did a great job!

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:  
 
---

:trophy: This issue is now completed. You can **claim the bounty** by submitting an expense to https://opencollective.com/engineering :tada: Please mention the issue number in the title expense's title.

**Comment by samus-aran** [comment]
Fantastic! Great job @leonardohof :tada:
