### ISSUE TITLE
Upgrade dataloader-sequelize to version 2.0

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2094]
We have a policy to try to use the latest version of our dependencies in all repositories.

In the API, we're currently using the version 1 of `dataloader-sequelize` and the upgrade to version 2 has breaking changes.

We want to:

  - upgrade the package
  - adapt the code where it's used
  - make sure the test are passing

The breaking change is that the we need to use the `context` API from `dataloader-sequelize` and this will need an important refactoring.

**Comment by brymut** [comment]
Hi @znarf, I'd be more than happy to have a look at this while I wait for review on a pull request, and get unblocked on the same issue.

**Comment by znarf** [comment]
@brymut Feel free to have a look. Let's check again in 1 week, as we now set up a timeframe for bounties to be completed.

I just have a small refactoring pending in that area, so maybe you want to try to start from that branch. https://github.com/opencollective/opencollective-api/pull/2075

**Comment by znarf** [comment]
@brymut any progress since last review? if not, we'll unfortunately have to release the bounty for someone else to take over

**Comment by brymut** [comment]
Hi, I'm sorry for the delay. I have made some more progress, planning on pushing later on tonight just working out some issues I came up on with the tests.

**Comment by Betree** [comment]
@brymut any news on that one?

**Comment by EvanBurchard** [comment]
@znarf I made a [wip PR](https://github.com/opencollective/opencollective-api/pull/2621/files) thinking I'd get some CI feedback, but I guess it's not set up?

Locally I was getting 8 test failures before the changes, and I had the same failures after upgrading.

I think I have the set up alright, but I'm not sure of the scope of queries that need to be reworked. Is it just ones in the loaders.js file?

**Comment by znarf** [comment]
This bounty is now free again. Can someone take over the good work from @brymut ? https://github.com/opencollective/opencollective-api/pull/2128

**Comment by CanerSezgin** [comment]
Happy to work on this.

**Comment by CanerSezgin** [comment]
@znarf  , Unfortunately, I won't be able to make this. I have spent a lot of time on this. By following brymut's step I tried to make this changes from scratch in order to understand what's going on. Actually after changing **loaders** file, and every lines which contains **req.loaders** works fine. I got rid of every errors except **CollectiveHistory** ones. 
Than I started to change every models that contains **findById** however at this point, I got lost. Because there are lots of connections especially when you add loaders as a params to function, this affects whole project. On the downside, I don't even know even if I change all these lines successfully (without missing any points) I don't know whether it will work or not. 
This is why I don't want to take your time more. You should assign this to someone else. Sorry for that. 
PS: Also I can send the code that I have made some loaders changes. This is basically similar to brymut's PR but it covers more part of the project (because you have added more functions after that PR I guess) However, changing models to req.loaders part totally messed up.

**Comment by znarf** [comment]
@CanerSezgin than you for the time you spent on that and sorry to hear it was too complex.

Let's maybe share your branch so that the next developer can see how far you went?

**Comment by gmarcos87** [comment]
Can I try to continue this work?

**Comment by znarf** [comment]
@gmarcos87 Have a look. It might be massive in the amount of changes required.

**Comment by gmarcos87** [comment]
@znarf Here is updated to master and passes all tests successfully! 
https://github.com/opencollective/opencollective-api/tree/fix-2094-v2

All I did was update the code and then resolve the errors detected by the tests.
Almost all the work was done by @CanerSezgin and @brymut.

**Comment by znarf** [comment]
🏆 This issue was completed by @gmarcos87 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by znarf** [comment]
Huge thank you @CanerSezgin and @brymut for you work on that too!

**Comment by gmarcos87** [comment]
@CanerSezgin and @brymut  I'd like to split this with you. What do you think?

**Comment by CanerSezgin** [comment]
Hi @gmarcos87, thank you for your kind and generous offer. It's all up to you in the end.

**Comment by brymut** [comment]
No thank you, I think you should just have it however you'd like. But I appreciate it tho.
