### ISSUE TITLE
Add a "Contributor" GraphQL type as a simplification of member

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2102]
# Motivations

With the new contributors grid that's being displayed on the tier page and the new collective page, we're now able to display dynamically thousands of contributors without impacting the frontend performances.

However we have two issues that are related to this:

1. **Performance (API):** Loading a large number of collectives without using a select has a cost. We're loading the rich description, the settings, the data...etc while all we want is a name, a collective slug, a picture and an (optional) public message. When loading few collectives, this is not a big deal. But if we're loading thousands of them, we'd better not overload the memory with unwanted data.

2. **Flexibility**: One thing that we also want with this new page is to surface Github contributors (https://github.com/opencollective/opencollective/issues/2103). We can already foresee that Github contributors may not be stored as `Members` and will probably not even have a collective. Relying on the `Member` graphql type doesn't allows us to include them.

# Proposal

- [x] Add a `ContributorType` graphql type with:
  - A name (required)
  - Roles (required, default=[contributor]) - List all roles for this contributor
  - A picture (optional)
  - A public message (optional)

- [ ] Add a `contributors` field on `Collective` and `Tier` to fetch them by loading the appropriate `Members`.

- [ ] Use these new fields in Frontend for new collective page and tier page

**Comment by Betree** [comment]
This could be a first step toward separating the idea of `Member` (as a way to handle permissions and administration level) from `Contributor` (as a way to surface the contribution level of a person without granting additional rights).

Which would resolve https://github.com/opencollective/opencollective/issues/1801

**Comment by xdamman** [comment]
I like the sound of it. But some comments/questions.

From the discussion with @alanna, we identified that everyone is a contributor. An admin, a backer, a github contributor, the creator, ... they are all effectively contributors. We just need to specify the type of contributor (github contributor, financial contributor, or just a plain contributor).

If I recall correctly, the only question was for organizations. Can we refer to members of an organization as contributors? Why not actually. Maybe Alanna or @piamancini want to chime in here. Maybe I forgot something. But I like the overall idea of doubling down and owning the concept of « contribute » and therefore « contributors ». You create an Open Collective because you want to attract contributors to pursue your shared mission.

If we can agree that *everyone is a contributor* (I love that as a tagline btw, it’s a bit like « everyone can be a cook* » from Ratatouille, such a great movie), then the question becomes why don’t we just rename the table `Members` to `Contributors`?

On the performance question, ideally you’d want to paginate. You don’t want to retrieve at once the 1,000+ contributors of large open source projects. Using a consistent `ResultSetType` to always return the total number of rows, the current page, and a `nodes` array with the actual results would be useful. See what @znarf has been doing with the GraphQL v2 API.

On the picture, I think the picture should be attached to the actual `UserCollective`. Ideally (and eventually), people will be able to create one or multiple profiles (e.g. an anonymous/pseudonymous one) and use that across multiple collectives they contribute to. But when they contribute to a given collective, it can be in a different capacity, that’s why it’s important to store a custom description per user - collective relationship.

For the role, I think we should create a Tier for each.

The more I think about this, the more I think that Tiers are basically simply different « ways to contribute ». You can contribute as a financial contributor, as a designer, as a volunteer, as an ambassador. For each role, people should be able to define a name for the role and a « role description ». Such tier could be free to join or you may have to give a set or minimum amount, one time or monthly. That will give full freedom to the admins to define the different roles, ways to contribute. It’s important to note that a given user can have multiple roles / contributions to a collective. I can be a designer and a financial backer.

* Whoever said that never saw me cooking, but I digress

**Comment by piamancini** [comment]
@Betree is this user facing or backend facing? 
@xdamman I think we agreed we were not migrating the database categories regardless of how we called things user facing. I think Ben is referring to this, but I might be mistaken.

**Comment by xdamman** [comment]
It belongs to @znarf and @Betree to decide if they want to change the name of the table in the DB for consistency. They are the primary users of it.

But the question here is different: do we agree that everyone is a contributor instead of member?
I think @cuiki did a nice graph to picture all the different roles, where can we find it? I thought he was going to link to it from the [design collective](https://opencollective.com/design).

**Comment by znarf** [comment]
Let's not rename anything in the database. We may at some point but not now. We can live with that if it's well understood: ie: `Collective` -> `Account`.

**Comment by Betree** [comment]
@xdamman 

> it’s a bit like « everyone can be a cook* » from Ratatouille, such a great movie

Excellent comparison :smile: 

> On the performance question, ideally you’d want to paginate. You don’t want to retrieve at once the 1,000+ contributors of large open source projects. Using a consistent ResultSetType to always return the total number of rows, the current page, and a nodes array with the actual results would be useful. 

For sure we'll have to do it at some point. Still, lightening the model will make data retrieving faster and the component even more reactive, both approaches will be more powerful when combined.

> On the picture, I think the picture should be attached to the actual UserCollective

Definitely. That isn't clear in the issue, but as per @znarf https://github.com/opencollective/opencollective/issues/2102#issuecomment-499462740 I don't want to make any change in the database for now, I just want to create a GraphQL interface that would map our existing data model to this new `Contributor` concept.
