### ISSUE TITLE
Poor alignment of "team" section on the Collective page

### ISSUE THREAD

**Issue by yellowwoods12** [opencollective/opencollective#2120]
**Describe the bug**
Poor alignment of the "team" section on the collective page. It looks very odd.

**To Reproduce**
1. Go to 'https://opencollective.com/scicommxyz-mastodon-instance'.
2. Scroll down to 'team' section.

**Expected behavior**
The alignment of the 'team' section should be center like the other sections on the same page.

**Screenshots**
![image](https://user-images.githubusercontent.com/31931348/59426954-22b16380-8df7-11e9-8505-3b19895a0a51.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : Mozilla FIrefox

**Comment by Betree** [comment]
Hello @yellowwoods12, this is because the right column is normally reserved for the tiers:

![image](https://user-images.githubusercontent.com/1556356/59429819-e3781800-8de0-11e9-8637-a8e52c18f519.png)

The reason why it looks bad is because https://opencollective.com/scicommxyz-mastodon-instance have no tiers setup, which is a very rare case. I agree that if there's no tier we should ideally center the block, but as the impact of this is very limited and we're currently re-designing the entire page I don't think that we'll be fixing it.

**Comment by yellowwoods12** [comment]
Hi @Betree, where can I find the details about redesigning and what is its current status? I would like to contribute in that.

**Comment by Betree** [comment]
@yellowwoods12 The progress is tracked here: https://github.com/opencollective/opencollective/projects/18. You can try it by adding `/v2` at the end of the URL (ex: https://opencollective.com/babel/v2).

Also if you're curious about the final design this is what it will look like when ready: https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-07-%2F-Collectives?node-id=0%3A7428

It's not easy to open that project to contributions right now because it involves feedback loops with the design team and also because there's no "quick task" in the list, all of them are complex ones that require quite some time to specify and/or implement.

If you're looking for open issues, I can suggest you look at the open bounties: https://github.com/opencollective/opencollective/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abounty

[Complexity > Simple](https://github.com/opencollective/opencollective/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22complexity+%E2%86%92+simple%22) and [Complexity > Medium](https://github.com/opencollective/opencollective/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22complexity+%E2%86%92+medium%22) issues should also be a good place to look for :slightly_smiling_face:

**Comment by yellowwoods12** [comment]
@Betree Yes sure. Will look into them :)

**Comment by alanna** [comment]
Fixed in NCP
