### ISSUE TITLE
Displaying collectives from "super collectives"

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2141]
I was demoing using opencollective.com/wwcode as I often do but I realized that for some reason the collectives of the network don't show up anymore there.
Instead, we see a list of contributors which is made of many of their chapters but also some sponsors.
It really looks weird.

What happened?

![](https://d.pr/free/i/VCfpg7+)

**Comment by xdamman** [comment]
Is that related to the conversation about the concept of `ParentCollectiveId` that you wanted to remove @znarf ?

**Comment by znarf** [comment]
What is "broken" on this page? 

Yes, I moved forward with `parentCollectiveId` because the bug preventing hosts to be removed was too important to wait https://github.com/opencollective/opencollective/issues/2101 https://github.com/opencollective/opencollective-api/pull/2119

It's still confusing to me why we should display collectives on such page when there is a host page for that https://opencollective.com/wwcodeinc But I had that in mind, and to make the transition smoother, I worked on a frontend PR to do something similar, which is unfortunately blocked because of a SSR rendering issue: https://github.com/opencollective/opencollective-frontend/pull/1948

There was no change to the "Contributors" section on this page, it had been "weird" like that for a long time. See for example: https://web.archive.org/web/20190501172148/https://opencollective.com/wwcode

**Comment by xdamman** [comment]
What's broken is that /wwcode should show the list of chapters.

The user need here is the following:
When going to /wwcode I should be able to donate to the movement in general or to directly go to a particular chapter (and donate there).

That's why /wwcode cannot point to the host, because a host doesn't collect money. 

So yeah, this is very annoying.

I don't understand why we had to kill the `ParentCollectiveId` to fix that bug, it seems unrelated. We should be able to remove a host without interfering with the `ParentCollectiveId`.

I guess a proper fix would be to enable a host (org) to act as a collective. But that's much more involved in terms of changes.

Let's see if we have more requests for this.

**Comment by znarf** [comment]
I'm sorry to be the one carrying that, but the notion of "parentCollective" (out of events) and "superCollective" are creating a lot of confusion. I'm sure they can be avoided. If not, they should be clarified. The fact that there is no admin interface, no documentation, is a hint that this a MVP that was never scaled. 

The notion of "host collective" is also creating a lot of confusion itself, but there is no way out today, so we're currently consolidating it.

I still think my approach (https://github.com/opencollective/opencollective-frontend/pull/1948) of displaying the collectives from the "host" (here wwcodeinc) on the "host collective" (here wwcode) is a sensible one.

In the meantime, feel free to add back "ParentCollectiveId" to wwcode collectives. But when they create new chapters, by which mechanism will  "ParentCollectiveId" be set?

**Comment by alanna** [comment]
> I guess a proper fix would be to enable a host (org) to act as a collective.

We need this for a lot of other reasons, too.

**Comment by gusaus** [comment]
WWCode and Open Source Collective supercollectives have been showcased many times to the Drupal community. Although none have needed this functionality to this point, that hopefully should change soon.

Because the host is usually Open Source Collective (host acting as a collective probably wouldn't work in this case), we'd need the functionality similar to what @xdamman is describing https://github.com/opencollective/opencollective/issues/2141#issuecomment-504370521

Is this use case related to this issue?

**Comment by piamancini** [comment]
@xdamman can we close this?
