### ISSUE TITLE
Make a request for funds / apply for grants

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2158]
## User story 

As a collective, I should be able to make a request for fund to a host or to an organization.
E.g. Can we have $5,000 to do this? Then one of the admins of the host/org can approve then pay. 

## Best solution for this problem
I go to the profile page of the host / org and there is a tier that says “grants” with a call to action “apply”. The amount can be fixed or variable with a ceiling. There might be some custom questions asked, including a long description (this goes well with #2128). Behind the scene, it’s basically a tier –i.e. another way to contribute– but with a “negative amount” in the sense that it’s not about giving money but receiving money. When you apply, this would create a pending order that needs to be approved by one of the admin of the host / org. Once approved, it could be paid and the collective that applied receives the grant (a donation).

## MVP
A first MVP could be using a slightly modified version of the Expense Flow where it wouldn’t be required to upload a picture (since there is no receipt/invoice). In the drop down to select the payout method, we should be able to select “put the money in my collective”.

## Metrics 
How many people are using that feature. 
This will be a great feature for hosts and foundations. 
This will also help the open source community. At Sustain in London we discussed how we could facilitate and standardize the application process for open source projects to ask for grants to companies https://twitter.com/xdamman/status/1055865769815429120?s=21
@duaneobrien @michaelmcandrew were especially interested in following up on that.

**Comment by alanna** [comment]
Do we have any grant-makers that want this feature? We should build it in partnership with them. Right now, all the grants are being managed in a semi-manual way, where we receive and credit funds to the Organization or Collective of the grant-maker, who then distributes the funds to projects that were selected through a seperate application process. 

Most grantmaking orgs either use a simple form or a more involved product like Submittable. I don't really see how Open Collective providing overlapping functionality is a value add. The value for grantmakers that we offer is in the funds distribution, not the processing of applications.

To me, this seems like a whole seperate feature that we should properly design and implement if we think there is demand for it, not shoe-horn in as a 'negative contribution'. If anything it's more like an adaptation of an expense (apply to be paid, including evidence/documentation, and they approve or reject it).

**Comment by lgagarcia** [comment]
We are currently exploring adopting OC for an organisation that has many collectives that we would ideally like to offer the opportunity to apply for 'grants' that we can then allocate to each group. 

The adaptation of expense (apply to be paid, including evidence/documentation, approve/reject) would be a perfect solution. 

How would you suggest building this in partnership? 

Thanks!

**Comment by xdamman** [comment]
In the redesign of the Expense Flow, we will include the ability to add custom fields to include evidence/documentation (such as adding a picture of the t-shirts you printed, or a link to the blog post that has been written, or to the pull request on github, etc.) /cc @raulgrafico

**Comment by alanna** [comment]
Good to know @lgagarcia ! I would be happy to help facilitate that. Is the organization already a fiscal host on OC? 

We are just about to start a project to revamp the expense flow. It's possible we could add an "apply for funding" adaptation of the expense process. I think we should make it a toggle option in settings though, because we don't want a bunch of people applying for funding from groups who don't offer it.

We are already going to add an "expense type" question so submitters can choose between "invoice" and "reimbursement". We could possibly add "funding application" there. If applicants were instructed to attach their documentation as a PDF or other document, would that work? 

I don't think we'll be able to build in a full fledged application form... if you need more specific info from people it might make more sense to run the applications outside Open Collective and then instruct successful applicants to create a Collective and then you can fund it. This is how grant-makers are currently using Open Collective to disburse funds.

@xdamman I think the above would entail allowing a Collective to submit an expense as opposed to an individual, and the payout to be a Collective to Collective transfer. I think this is a good idea anyway, as we have more and more Collectives hiring other Collectives (e.g. OSC hiring OC Design).

**Comment by xdamman** [comment]
Exactly. In the same way that we allow a collective to donate to another collective, we should allow the opposite operation, ie. "request donation". The only difference being who initiated the transaction (a donation on one side is an expense on the other side).

**Comment by michaelmcandrew** [comment]
hey all, a bit late to the party. thanks for including me on this ticket.

@xdamman - at this point in time, I'm probably more interested in understanding the motivations of corporations that give to open source and the ways in which they do it rather than standardising the process per se.

hope you have fun with this in any case :)

**Comment by xdamman** [comment]
@michaelmcandrew ok. Please share what you find! :-)

**Comment by michaelmcandrew** [comment]
will do

**Comment by kewitz** [comment]
Implemented. It is now possible to submit a grant request to fund collectives.
