### ISSUE TITLE
Place to highlight the people that contribute to Open Collective

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2175]
During last team retreat in Brussels flourished the idea that we should have a place on the website to surface Open Collective's team and contributors. 

The main argument for it was that we're a diverse team, with amazing contributors from all over the world and that by just showing it we may reflect an image that will incentive all communities to feel welcome to join and contribute.

@xdamman argued that maybe that's something we can build not just for ourselves, but for all collectives on the platform. For example, we could have a special page/widget to show all contributors on a world map.

Another way of doing it would be to create a `/team` page that's only for us, or to make it part of the new homepage redesign.

@opencollective/core did I forget something? Do we have an actionable for this one? 

---

Related to https://github.com/opencollective/opencollective/issues/1781

**Comment by xdamman** [comment]
To respect the terminology of collectives, we should refer to ourselves as “core contributors”, not “team”.

We could have on the homepage the same section than on any collective page: “Open Collective is all of us”, with a grid of all the people who contribute to Open Collective. It would be great to have an embeddable version of that section so that we could just embed the one of our our main collective (https://opencollective.com/opencollective)

If we want to get more fancy, we could have an icon somewhere to switch between a map and grid view. Maybe it’s an option when embedding?

**Comment by alanna** [comment]
I think we should dogfood this. If we are not happy with how the core contributors are showing up for our Collective (Open Collective Inc), then we should improve how that works, and also improve it for all Collectives. If we have to route around our own product by creating another page on the website, it's a sign we're not offering a good enough solution for all on the platform. Pretty much every Collective has this need to explain well who the core contributors are. Before jumping to the embeddable version, let's fix it on the Collective page and then link to that from our website. If people want embeds we will respond to that.

**Comment by Betree** [comment]
Closing as there's no immediate actionable. Feel free to open new issues to extract the ideas discussed here.
