### ISSUE TITLE
Switch /opensource and /opensourcecollective

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2182]
Since we removed the `ParentCollectiveId`, the list of collectives hosted by the open source collective are not listed anymore on https://opencollective.com/opensource

To be keep things consistent with the other hosts, I’d recommend to switch the slug of the host opensourcecollective with the main collective of the host /opensource.
E.g. 
- https://opencollective.com/Europe
- https://opencollective.com/Brussels
- https://opencollective.com/Paris
- https://opencollective.com/UK

It also means that the main call to action will be “apply to create a collective” rather than “contribute”

@alanna @piamancini are you fine with this?

Ideally, we shouldn’t make a distinction between a host and a collective but that’s beyond the scope of this issue. This is just meant to be a quick fix.

**Comment by piamancini** [comment]
yes, this was mentioned in the original thread https://github.com/opencollective/opencollective/issues/2101

**Comment by znarf** [comment]
@piamancini Xavier's question is about switching "opensourcecollective" (currently the Open Source Collective Organization, a Host) and "opensource" (currently the Collective linked to the Open Source Collective Organization, a Collective). Are you fine with this?

**Comment by piamancini** [comment]
Yes I am (sorry I wasn't clear)

**Comment by xdamman** [comment]
Let's wait for @alanna's go then I'll make the change. 
The dashboard URL will also change from opencollective.com/opensourcecollective/dashboard to opencollective.com/opensource/dashboard

**Comment by znarf** [comment]
I'm afraid the proposal is not resolving the confusing terminology used here.

- opensource: the "Open Source Collective" organization, a Host
- opensourcecollective : he "Open Source Collective" collective, a "Host Collective" linked to the "Open Source Collective" organization

Why is it confusing in the first place?

- The Open Source **Collective** is not a "collective", it's an "host", an "organization"
- We need to link a collective to something that is already named ""Open Source Collective"

What would be the non confusing way that respects existing names and conventions?

- opensourcecollective: the "Open Source Collective" organization
- opensourcecollective-collective: the "Open Source Collective" collective

Ok it's repetitive, we can try removing "collective":

- opensource: the "Open Source Collective" organization
- opensource-collective: the "Open Source Collective" collective

Ok, I've just written all and the only difference with the proposal is "opensource-collective" instead of "opensourcecollective". But it's just that it's impossible to have a better proposal without renaming the "Open Source Collective" and removing the notion of "Host Collective".

**Comment by xdamman** [comment]
I’m fine with your proposal @znarf. 
We will fix this at some point in the future. A host should be a role, not an entity. It’s a type of contribution that can be offered by a user, an organization or a collective. But that’s for later.

**Comment by alanna** [comment]
I agree with this change in theory. I'm just nervous because there are a lot of links to opencollective.com/opensourcecollective out there and I don't know how to find them all and change them.

I guess.... go ahead and do it and we'll fix any broken links as they come up. I definitely prefer opencollective.com/opensource pointing to the host organization page, because it's much more commonly used and public facing, and that URL is cleaner.

**Comment by alanna** [comment]
I just searched for the string "opencollective.com/opensourcecollective" in the codebase and there are a bunch of instances. Will these automatically change to "opecollective.com/opensource" @znarf ?

I also searched for that string on Google and there are a few links out there but nothing critical. I think once this change is made, I will just put a note on the "opensource-collective" Collective description that if they are looking for the OSC host page go here.

**Comment by znarf** [comment]
If we move forward, we need to fix all these links in sync with the change. We can also put a redirect in place linking `opensourcecollective` to either `opensource` or `opensource-collective`.

**Comment by alanna** [comment]
OK let's do it.

**Comment by alanna** [comment]
FYI I have changed OSC's Collective slug to /osc instead of /opensource-collective because we are emphasising the initials more in the new branding and it's a lot simpler.

**Comment by xdamman** [comment]
Mmmm... it's confusing now. 
Because technically /osc should be an organization, not a collective.
The point of having `-collective` was to be the default collective for a given organization (in this case /opensource).

A better way to think about this could be:
/opensource: a vertical across multiple hosts like /meetups (the old concept of "super collective")
/osc: open source collective organization/host
/osc-collective: default collective of the open source collective organization

**Comment by alanna** [comment]
I don't think it's confusing. The organization and the host are one in the same, located at /opensource. The Collective is the group and budget running the thing, located at /OSC. I don't want to use "OSC-collective" because in many places in the app, it will then display "OSC Collective Collective" and I don't like that. Plus the URL will be unnecessarily long, as we're not using /osc for anything else now.

/opensource is *not* a "vertical across multiple hosts". That's not something that really exists in our system. *That* is confusing. If we are going to have supercollectives, let's specify what they actually are, document them, and properly design them. Open Source Collective is **one single host**. We had a discussion and decided that host's URL should be /opensource. I do not want to overcomplicate it.

I see what you mean about having a pattern for the names of hosts and their default Collectives. However, if you want to actually solve that, we should fully implement #1723, removing the need for a default Collective, and make hosts have all the functions of a Collective, which they should. But that is not our priority right now.

Anyway, I don't really think debating this whole debate is a priority right now. I'm running OSC these days and I'm happy with how it is now so I'm going to leave it.

**Comment by znarf** [comment]
@alanna a decision was made in this issue and you agreed to the plan: "opensource" -> host, "opensource-collective"-> host collective.

This was our best shot as consistency. It's not great to revisit that decision that without discussing and let us know after the fact.

Please reconsider and open on a new issue if you want to introduce the "OSC" brand.

**Comment by xdamman** [comment]
> /opensource is not a "vertical across multiple hosts". That's not something that really exists in our system. That is confusing.

That's a good example of looking at it from our own perspective, not from the perspective of outsiders.

As a visitor going to opencollective.com/opensource, I'd expect to see all the open source projects on open collective. I don't have the concept of "host" in my head. So just show me all the open source projects. Same for /meetups. I agree that we should have this discussions as part of the discussion about "super collectives". And like you, I don't think that this is a priority for now.

I just wanted to point this out because I'm worried that we are more and more taking decisions from our vantage point instead of the visitor/user's vantage point. This worries me a lot. Let's be mindful about that.

@znarf this is a good example where consistency cannot get in the way of doing the right thing. @alanna is running the OSC. She knows better what she needs. She shouldn't have to abide by that consistency rule because we said so in a different context. This is the best recipe to create a top down environment where people feel very demotivated. So as far as I'm concerned, if she feels like having a collective for the OSC that is on `/osc`, I'm fine with it.

**Comment by znarf** [comment]
@xdamman I engaged in this discussion, we reached a consensus and at the end we do something else. What about my motivation?

**Comment by xdamman** [comment]
That's a good point.
(djeez, we still have work to do to improve our processes to make sure that everyone can feel good about their contribution! Sorry for the mess and frustrations it creates before we get there)

I guess we didn't frame the conversation the right way at the beginning?
As a general rule the person closer to the action / users should have the last word.
And we should reach consensus when the decision is impacting others (ie. using /opensource is prime real estate, so we reached a consensus to use it for the OSC host for now even though I feel strongly that it should be multi-hosts. But it's not a priority, so good enough for now).

The question here is: how does changing `/opensource-collective` to `/osc` impacts you?
Why does it matter for you and how does that compare to the need of @alanna?

**Comment by znarf** [comment]
@xdamman I tried to help. I proposed a rationale for the change https://github.com/opencollective/opencollective/issues/2182#issuecomment-507356767 What is the rationale for the new change? I would like to see what was the problem and the alternatives that were considered.

In the end, I guess that doesn't impact me, so I l'm disengaging from this discussion.

**Comment by alanna** [comment]
I am disengaging from this as well. I have made the decision. To me this is clearly inside my sphere of leadership and I'm not arguing about it.
