### ISSUE TITLE
Terminology: "Get updates" vs "Subscribe" vs "Follow"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2202]
During the team retreat, we had a chat with @xdamman and @raulgrafico about the terminology for #1445 and especially the label for this button:

![image](https://user-images.githubusercontent.com/1556356/60669707-405e6f80-9e6f-11e9-9bfe-4238cb575938.png)

We were not able to find the past discussion about this.

There were arguments that we should use `Subscribe` or `Follow` instead of `Get updates` because:
- That's what users know from other platforms
- We may want to be able to subscribe to other types of notifications in the future with something like:

![image](https://user-images.githubusercontent.com/1556356/60670848-f034dc80-9e71-11e9-9c52-af63c142439f.png)

On the other hand there are arguments that we should use `Get updates` because:
- When you click on `Subscribe` or `Follow` you expect to receive notifications, not emails

---

**Expected decision for this issue**
> Decide if we should call this `Get Updates`, `Subscribe` or `Follow`.

Ping @raulgrafico @xdamman @alanna @piamancini 

---

Below are the notes from that meeting about Updates:

# Updates 

## Why

- Reduce churn
- Inform community / annoncements
- Show it's alive / progress
- Reporting
- Opportunity to engage
- Call your community into action
- Show gratitude (say thanks)

## How

- Write/send updates to all contributors
- Gather/summarize updates for the community

## What

- Mailing list of contributors
- Quick reaction
- Polls
- Images/videos
- Pin important announcements
- Comments
- Follow converations on this update
- Mentions
- Tags
- Pivate updates / target specific groups|contributors|tiers
- Share

**Comment by piamancini** [comment]
Since 'Subscribe' is an action related to a financial contribution (we have subscriptions) I would keep Get Updates.

**Comment by alanna** [comment]
That's the opposite of what we decided @piamancini 

We have removed the word 'subscribe' in reference to financial contributions throughout the app and site. 

The action we decided for getting updates was explicitly "Subscribe" because that is the common meaning of that word on the internet. We moved away from subscribe for financial contributions specifically to free up that word.

@Betree if unsure please refer to the [conclusion notes from the terminology workshop](https://github.com/opencollective/opencollective/issues/1969#issuecomment-490342216). This issue is specifically mentioned there.

> Subscriptions will become "recurring contributions", so things don't get confused with 'subscribing' to Collective updates.

**Comment by alanna** [comment]
I really need us to stick to the decisions we made about terminology, otherwise we will be having the same conversations over and over. This is a classic example of making a clear decision, communicating it, and not rehashing.

**Comment by Betree** [comment]
Alright, that solves the issue. @alanna can we export the conclusions of the terminology issue somewhere (maybe in https://docs.opencollective.com/help/about/glossary)? Issues are a place of debate and discussion, it's not easy to find the conclusions in there.

**Comment by Betree** [comment]
Actually after reading the conclusions I see a decision about not using `Subscribe` for the recurring financial contributions, but I don't see any decision for naming this feature.

We still have to decide whether we want `Follow` or `Subscribe`.

**Comment by xdamman** [comment]
I’d go for “Follow”. 
It feels less involved than “Subscribe”. When you subscribe, it could mean that you may have to pay something.
Follow feels very light touch, very easy.

That said, I could live with Subscribe if you really feel strongly about it.

But I’m really not a fan of “Get Updates”. What popular website is using such terminology? The more we can tap into a shared reference that people are already familiar with, the better.

**Comment by piamancini** [comment]
We moved away from subscribe for financial contributions specifically to free up that word.
Cool - if we moved away from it then I'm ok with Subscribe (as long as there is no piamancini/subscriptions page showing our financial contributions)

**Comment by Betree** [comment]
> It feels less involved than “Subscribe”. When you subscribe, it could mean that you may have to pay something.

I'll add that from the **existing** users perspective, "Subscription" === "Recurring financial contribution". We may want to avoid re-using this word for a different feature too quickly to avoid any confusion.

**Comment by alanna** [comment]
I am fine with "follow". 

I agree we should give 'subscribe' a break while we fully transition to the new terminology. 

Good idea to update the glossary @Betree I will put it on my to-do list.

**Comment by piamancini** [comment]
I'll add that from the existing users perspective, "Subscription" === "Recurring financial contribution". --> yes, this is what I meant above. +1

**Comment by Betree** [comment]
Alright, seems that we have a consensus for `Follow`. Thank you everyone!

**Comment by raulgrafico** [comment]
Just want to bring to the conversation, @xdamman even users got confused with the expectancy of the "Follow" Label. Part of the feedback we had is that "Follow" was associated with social networks follow option (We got that feedback from an Open Collective Brussels user on Belgium). We need to use a real expectancy label because they are not following anything, they are receiving updates on their emails, what makes total sense for me, at least until we have a real follow feature.

**Comment by xdamman** [comment]
You are referring to JF's feedback. His first suggestion was actually "Follow".

If the expectation is different from what we offer (today), we should reconsider what we offer.
We are the ones that should adapt to the expectations of the user, not the other way around.

When a user lands on the page of a collective, they either want to "Follow" it or "Subscribe to newsletter".

From the perspective of a collective, the number one thing they do when they set up a website is add a button "Subscribe to newsletter".

From the perspective of a platform that makes it easier for people to "follow" multiple collectives, "follow" is a better term because it implies that you can follow more than one.

Anyhow, this button won't show up for now because we don't have a real "follow feature" yet. We should create a separate issue to describe the feature.
