### ISSUE TITLE
Monthly report to backers includes orders with status ERROR

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2204]
See Order Id 47376

**Comment by znarf** [comment]
Doing my best to understand what this issue is about. In the future, can you write a more detailed report?

If I look at the `user.monthlyreport`, Order with `status=ERROR` should not be included.

https://github.com/opencollective/opencollective-api/blob/master/cron/monthly/user-report.js#L200

Can you confirm the template and share a screenshot?

**Comment by znarf** [comment]
@xdamman Can you **at least** confirm the template and share a screenshot?

**Comment by znarf** [comment]
Not enough info.
