### ISSUE TITLE
Conversations - community discussions on Collective pages

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2223]
## User story 

As contributor, I can open an issue on a collective's page so that I can start a conversation about a topic, make a proposal, get and provide feedback, provide or ask for community support, organize.

## Best solution for this problem
Github Issues on the collective page. 
Comments on expenses posted on the thread in the CP
Comments on transactions posted on the thread in the CP
Pinned issues/updates from core contributors 
Link comments to transactions.

## MVP
An MVP is a comment thread that lets anyone start or answer to a thread and lets core contributors post their updates as comments on the thread and pin them. 

## Metrics 
Engagement on the CP measured by number of threads started and commented on. 

## Documentation 
N/A

**Comment by xdamman** [comment]
I wonder if we could start with renaming the table `Updates` to `Conversations` and allow anyone to create one. And following the existing design pattern of filtering a list by tag, we could filter conversation from "Core Contributors" or "All conversations" (Updates are today effectively conversations started by the core contributors). Later we could introduce the concept of tags for conversations to let people define a "Updates" tag.

Another thought I had was about how we could include comments on expenses because they are also "conversations". Maybe a good way to fetch the list of latest "Conversations" would be to not only fetch the latest updates but also the latest comments.

E.g.

## XR Belgium Conversations
- Sunday: What about doing an action at the Atomium? by Tom
(No comment yet)
- Saturday: Expense: €300 for paint for the pink boat submitted by Majo
Latest comment by Xavier
- Friday: Good luck for the Royal Rebellion by Bernadette
- Friday: Expense for posters submitted by Shadowfaxxx
Latest comment by Misternature

**Comment by xdamman** [comment]
After talking to Ben and thinking more about it, I’d propose to have two separate sections on the collective page that can be each turned on/off for each collective (like the global goals, events sections): one section for updates and one section for conversations.
From Ben’s perspective it’s not that complicated to merge the two sections. 
From my perspective I’d like to keep things separated so that the collective can turn each section on/off independently. Waiting for design feedback on that.

In the MVP we won’t implement the emoji reactions (though I think it’s a great great feature that would be very nice to have, so that’s a stretch goal, cherry on the cake) :-)

The form to create a conversation should be a minimal rich text editing that allows for image upload.

Everyone that participates in the conversation should automatically « follow » the conversation and can unfollow with one click by email. 
**Question**: where can we show who follows the conversation?

## Collective page
![](https://d.pr/free/i/mPODry+)

## Conversation page
![](https://d.pr/free/i/FMZamd+)

## Mobile view
![](https://d.pr/free/i/Nky9tq+)

**Comment by piamancini** [comment]
Great progress! 
What's the rationale for having two separate sections? it seems to me that updates is just a pinned conversation and only admins can pin/unpin it. Pretty much like a twitter pinned tweet. You can only have one item pinned at a time so it'd be the latest update. I think simplicity should be something we try to do more of.

**Comment by xdamman** [comment]
I think it’s confusing to mix the two.
Especially if at a later stage we gonna introduce the concept of pinned conversations.

I’d like to keep both separated like on a facebook page. 
You can publish posts on your page and you can participate in conversations in the facebook group associated to your page. But there is a clear distinction. 
Same on telegram where you have the concept of a broadcast channel to get updates from the community and then an associated “chat” where anyone can initiate a conversation. Here again, it’s very well separated. And here again you have the concept of “pinned message”.

It’s also two very different level of engagement. Only the people quite involved in the community will be interested in the conversations. People just supporting financially will only be interested in the “Official Updates”.

**Comment by Memo-Es** [comment]
Here are the results after the first round of feedback on Friday, Oct 18th
👉 [Prototype](https://www.figma.com/proto/KinuveYf4WUlRIXzMTnmIsmO/OC.COM-XX1-Lab?node-id=1059%3A16638&viewport=1912%2C-150%2C0.5&scaling=scale-down)
👉 [Figma file](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/OC.COM-XX1-Lab?node-id=1059%3A14763)

Updates          |  Conversations    |  
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/49539954/67236828-a1ef1d80-f40f-11e9-9399-e2efbf8bf456.png)  |  ![](https://user-images.githubusercontent.com/49539954/67236879-bd5a2880-f40f-11e9-9c06-5de4c2b021e8.png) | 
![](https://user-images.githubusercontent.com/49539954/67236941-db278d80-f40f-11e9-84d5-5ca4a6ca5eba.png)  |  ![](https://user-images.githubusercontent.com/49539954/67236968-e7134f80-f40f-11e9-9604-ecec5314fa52.png) | 
![](https://user-images.githubusercontent.com/49539954/67237006-ff836a00-f40f-11e9-879c-6f9ce0748956.png)  |  ![](https://user-images.githubusercontent.com/49539954/67237020-0ad69580-f410-11e9-9294-992c3fa2e6bc.png) |

**Comment by piamancini** [comment]
Looks great @Memo-Es - We need a view that includes the Create a new update for logged in admins.

**Comment by xdamman** [comment]
See my comments in the images below:
![](https://d.pr/free/i/PQsnlu+)

![](https://d.pr/free/i/7B3Pub+)

Let me know if you have any questions.

**Comment by Betree** [comment]
@Memo-Es Looks great! We need to have some pagination for these pages. That may not be implemented for MVP, but that's something we're 100% sure will be needed if Collectives start using the feature.

**Comment by xdamman** [comment]
Feedback on latest export from @Memo-Es 
![](https://d.pr/free/i/GQQucU+)
![](https://d.pr/free/i/VgYw5C+)

I'd also put the Conversations section right below the Updates section.

Can you share the latest version of the the Conversation page?

**Comment by raulgrafico** [comment]
@xdamman this is the latest version for the conversation page. 

<img width="1504" alt="03 → Conversation Thread" src="https://user-images.githubusercontent.com/1252676/68133673-76c3fe00-fee6-11e9-81c0-0cf73377edf3.png">

**Comment by Betree** [comment]
Notes from today's meeting:

## MVP

- Use `Notification` + `Member` tables to manage subscriptions
- Follow/unfollow button for conversations
- Create/Delete
- Rich text (bold, italic)

## Important

- Reactions
- Hide
- Edit
- Reply

## Not MVP

- Manually subscribe to updates
- Pin conversation
- Mentions
- Posting as (posting comments as a collective)
- Private comments

## Won't do 

- Showing organization on avatar

**Comment by raulgrafico** [comment]
Hi guys, this is the latest update for this. The overlay to view all the people on a reaction is still pending, and I want to confirm with Dario if there is a pattern for that.

![01-Collective - COMPRESSED  - A](https://user-images.githubusercontent.com/1252676/68733279-b7cda980-059b-11ea-8c80-9bc96f80946a.png)
![01-Collective - COMPRESSED  - B](https://user-images.githubusercontent.com/1252676/68733280-b8664000-059b-11ea-96dd-408cff70f093.png)
![02 → Create new conversation STEO 02](https://user-images.githubusercontent.com/1252676/68733281-b8664000-059b-11ea-8476-5433f8576eb7.png)
![02 → Create new conversation STEP 01](https://user-images.githubusercontent.com/1252676/68733283-b8664000-059b-11ea-9e68-6e6680cd2795.png)
![03-Conversations - List](https://user-images.githubusercontent.com/1252676/68733284-b8664000-059b-11ea-96fc-309ca99cabb5.png)
![03-Updates - List](https://user-images.githubusercontent.com/1252676/68733285-b8664000-059b-11ea-8c28-a2e886b20bcc.png)
![05 → Conversation Thread](https://user-images.githubusercontent.com/1252676/68733286-b8664000-059b-11ea-8a25-d504d4d81fec.png)

**Comment by Betree** [comment]
Looking great @raulgrafico!

The `Create conversation` CTA's position on the form still feels strange to me.

I'm ready to start implementing if @xdamman is ok with it.

**Comment by raulgrafico** [comment]
![01-Collective - Desktop](https://user-images.githubusercontent.com/1252676/69582781-f487a080-0f9e-11ea-9dcb-20fc763f8c08.png)
![02 1 → Create new conversation](https://user-images.githubusercontent.com/1252676/69582782-f487a080-0f9e-11ea-925f-487e466fd815.png)
![02 1 → Create new conversations - Mobile](https://user-images.githubusercontent.com/1252676/69582783-f487a080-0f9e-11ea-843e-978aad6031ee.png)
![02 1 → Create new update - Mobile](https://user-images.githubusercontent.com/1252676/69582784-f487a080-0f9e-11ea-831a-bd0466379e51.png)
![02 2 → Create new update](https://user-images.githubusercontent.com/1252676/69582786-f487a080-0f9e-11ea-8a49-62893f85c33c.png)
![03 1-Conversations - List - Mobile](https://user-images.githubusercontent.com/1252676/69582787-f5203700-0f9e-11ea-9954-1a402b7a32c4.png)
![03 1-Conversations - List](https://user-images.githubusercontent.com/1252676/69582788-f5203700-0f9e-11ea-939b-e0e474ef3e6a.png)
![03 1-Updates - List - Mobile](https://user-images.githubusercontent.com/1252676/69582789-f5203700-0f9e-11ea-86c4-acd8dd3b001e.png)
![03 2-Updates - List](https://user-images.githubusercontent.com/1252676/69582790-f5203700-0f9e-11ea-923a-d5acd1a48522.png)
![05 1 → Conversation thread - Mobile](https://user-images.githubusercontent.com/1252676/69582791-f5b8cd80-0f9e-11ea-876c-c16346aa6cf7.png)
![05 1 → Conversation thread](https://user-images.githubusercontent.com/1252676/69582792-f5b8cd80-0f9e-11ea-902b-0abceb0b8546.png)
![05 2 → Update - Mobile](https://user-images.githubusercontent.com/1252676/69582793-f5b8cd80-0f9e-11ea-8069-2bc3fc2df8d8.png)
![05 2 → Update detail](https://user-images.githubusercontent.com/1252676/69582795-f5b8cd80-0f9e-11ea-9120-6beae9ec4c8d.png)
