### ISSUE TITLE
Proposal: kill bitcoin payment method type

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2238]
# Acknowledging

- That maintaining code for a feature always takes time (eg. tests need to be updated, bugs...)
- That unmaintained features can contain security issues, or be a vector for privilege escalation
- That the bigger/more complex the code base, the harder it is for newcomers to get on board

# And regarding the fact that...

- The feature is not used since more than one year (last created was 2018-04-15)
- There's very few of them (17 total)
- We currently have no plan to re-support it in a near future
- If we want to re-implement this, we'll need a lot of work on it in any case

# I propose that

We kill the bitcoin payment method entirely:
- Mark PMs as deleted in the DB
- Remove all references from API code
- Remove all references and translations from Frontend code

**Comment by xdamman** [comment]
I agree. Stripe doesn’t support it anymore. 

I’d love to abstract the concept of “manual donation” so that a host could define multiple manual ways. This would give them a way to accept crypto donations.
E.g. give money by making a bank transfer, give money by donating to this BTC address, etc. 
It’s basically always the same mechanism: we send you special instructions by email and the host has to confirm once they have received the money.

**Comment by piamancini** [comment]
+1

**Comment by Betree** [comment]
Thanks for the quick feedback!
