### ISSUE TITLE
New collective page: customize primary calls to action

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2239]
Following up on https://github.com/opencollective/opencollective/issues/2228#issuecomment-511093177

---

One thing that appears in @nemchik's feedback is that different collectives will have different expectations about the primary calls to action.

Currently we've defined that the primary call to actions should be `Donate` and `Contact`. For my example, I'd prefer for my collective CaptainFact to have `Donate` (because one time contributions are something we're looking for and we want to make it simple) and `Website` (because some people arrive on our OC page without knowing about the project and there's no chance that they will donate if they haven't seen our main product yet). Having a contact button is actually a problem for us because we have clear paths to handle communications and having emails on collective admin's inboxes is messing up with our processes.

Another example: we don't care about the "Donate" button for OC engineering collective, but the "Submit expense" is very important: people come there to claim bounties.

That being said, we should of course have smart defaults and I think that the ones we already defined are good because they're based on very relevant feedback from support requests, users and examples from other websites.

**Feature summary**
Collective admins can pick up to 2 calls to actions to put on their collectives Hero amongs the following:
- Contact
- Donate
- Website
- Github
- Submit Expense
- [Custom?]

@raulgrafico @cuiki not to implement in the edit mode before we have a consensus, but opinion welcome.

Also @alanna @piamancini @xdamman as you have strong opinions about what we should put there.  

PS: to be clear I'm talking about this:
![Screenshot_20190713_082354](https://user-images.githubusercontent.com/1556356/61168196-b8e9be00-a54a-11e9-8dde-9aa189db8649.jpg)

**Comment by alanna** [comment]
Hmmm. It's an interesting idea but I'm not sure it's the way to go.

When it comes to "contact", the problem is that the core contributors might not think it's important because they are not the ones ever looking for the contact button. It's everyone else who is trying to reach them and getting confused and failing because it's hidden.

To me, it seems far more important that the design is consistent, so people only have to figure out these things one time (where is the contact button, where is the submit expense button, where is the contribute button). If these are in different places for each Collective it could be a nightmare. Different users have different top actions. Some only contribute financially. Others only submit expenses. Others just want to get to their dashboard to approve expenses, etc.

That said, I do think actions which are very important to some Collectives are too hidden in the new design, such as the website link, repo link if they have one, subscribe to updates, etc. Can we just try to reveal all of these a bit more, so whatever someone is looking for is easy to find near the top of the screen?

I would focus on making creating custom tiers part of the Collective onboarding process, so the Collectives have a lot of control over the words and CTAs that appear in the top section of their page (Contribute). We really hammer home the contribution thing in that section, so I don't think we need yet another contribute button in another place.

**Comment by Betree** [comment]
> To me, it seems far more important that the design is consistent, so people only have to figure out these things one time (where is the contact button, where is the submit expense button, where is the contribute button). If these are in different places for each Collective it could be a nightmare. Different users have different top actions. Some only contribute financially. Others only submit expenses. Others just want to get to their dashboard to approve expenses, etc.

I agree, the main risk of customization is often inconsistent design and hardly predictable paths. It's a tough thing to find the right balance between allowing enough customization for users to feel that they own this page without breaking the experience for all the other visitors.

So I understand that there is a danger if one collective has a big `Contribute` button there while a sibling collective has a `Submit Expenses` button instead. But I still think that we must somehow bring more flexibility here, if not by picking the precise buttons at least the page should better adapt to the collective usage.

Another example for this is the ~`Get Updates`~ `Follow` button: most collectives never create updates on the platform. I'm pretty sure that a good part of them don't really care about adding a `Follow` button. On the other end we got feedback that collectives **do** care for a more prominent `Contribute` button (https://github.com/opencollective/opencollective/issues/2228).

**Comment by Betree** [comment]
@cuiki @raulgrafico Your experience about UX would be valuable in this conversation, especially about how customizing these CTAs could lead to confusion for users.

**Comment by cuiki** [comment]
Hi. The challenge, IMO, is to make sense of all the incoming feedback and put it together and apply strategically. Most of what you said in the initial comment is already addressed but this could be a matter of hierarchy and sequence. Some users think that their CTA could be submitting an expense but it could only mean that the action of submitting is hard to find or buried too deep into the page.

I think we should aim for consistency (reinforcing the action of contributing which seems the most recurring feedback) but rethinking what are the important contexts that matter to users, rather than thinking about a single action.

**Comment by Betree** [comment]
Closing this for now as we prefer to target consistency

**Comment by xdamman** [comment]
Sorry I missed this issue. Only seeing now with the notification that you closed it ;-)

Thanks for sharing your experience with CaptainFacts. We need more stories like those to better understand the different use cases.

I agree with @alanna that consistency across all the collective pages for the main actions is important.

But I also agree with @Betree that the “Submit expense” is an important CTA that for now, should be put much more forward.

I say for now because to this day, the main use case for open collective is “collect and disburse money”, so it only makes sense that those should be the two top CTA (especially on mobile with limited screen real estate). Then “Contact”.

@cuiki @raulgrafico could you share it a desktop and mobile screenshot of having those 3 CTA in that order? (Donate, Submit Expense, Contact)

@Betree maybe one way to reconciliate the need for consistency with the need of customization, why don’t we let the collective customize where the “contact” button goes? By default it could be `info@:collectiveSlug.opencollective.com` but people could for example put another email or a URL such as https://github.com/CaptainFact/captain-fact/issues/new

**Comment by Betree** [comment]
> maybe one way to reconciliate the need for consistency with the need of customization, why don’t we let the collective customize where the “contact” button goes? By default it could be info@:collectiveSlug.opencollective.com but people could for example put another email or a URL such as https://github.com/CaptainFact/captain-fact/issues/new

Yep that'd be a good way to solve the contact issue that I'm pretty sure other collectives will complain about at some point. Opening an issue for that now.

**Comment by cuiki** [comment]
Yup I think thats a good level of customization for now. :)
