### ISSUE TITLE
Improve Performance, SEO and PWA

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2241]
## User story 
The Lighthouse audits for OpenCollective - https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=http://opencollective.com
We are not a fully offline supportive + PWA + best performance

## Best solution for this problem
- Improve TTI
- Compress Images for better contentful paint
- Offline Support

## MVP
**PWA**

## Metrics 
Improve Lighthouse metrics

## Documentation 
- https://developers.google.com/web/progressive-web-apps/
- https://developer.mozilla.org/en-US/docs/Web/API/Performance

**Comment by znarf** [comment]
Anything that improves performance is always warmly welcome.

To be solvable, this feature request needs to be broken in specific points that can be tackled individually by contributors.

Feel free to create PRs or Issues to address the individual problems.

**Comment by maddhruv** [comment]
If we can keep all individual items under this issues
like - **Performance**
and ask individuals to make PRs

**Comment by maddhruv** [comment]
@znarf 
can I work on these issues?

**Comment by Betree** [comment]
> If we can keep all individual items under this issues
> like - Performance
> and ask individuals to make PRs

We try to keep issues as contained and focused as we can, otherwise they stay open forever. Take this one as an example: you can always improve performance and SEO so when do we close it?

I've created the [`performance`](https://github.com/opencollective/opencollective/labels/performance) and [`SEO`](https://github.com/opencollective/opencollective/labels/SEO) labels so we have a way to group issues about these topics. 

As said by @znarf contributions for these will be warmly welcomed :slightly_smiling_face: To contribute you can either:
- Create an issue detailing a specific problem (ex: `Images on the homepage should be compressed`)
- Or create a PR to tackle the issue directly.

Please open an issue before making a PR to discuss the problem **if it's a big change**, we don't want contributors to loose their time if the solution they're targeting is not the one chosen by the core team.
