### ISSUE TITLE
Lazy Load contributors avatar

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2243]
## User story 
We load all the avatar (companies as well as backers/people) on the page load even if they are not on the viewport, this increases the total data to be loaded as well as the number of requests being transmitted.

## Best solution for this problem
Lazy Load avatars and logos

## MVP
Improved Performance

## Metrics 
Total number of requests done to load the initial viewport

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by maddhruv** [comment]
@znarf

**Comment by Betree** [comment]
Avatars are usually pretty small, weighting somewhere between 2kb and 5kb. On the [new collective page](https://opencollective.com/babel/v2)  where the `Contributors` section can display thousands of contributors we already lazy load them.

Lazy loading should not be the default because:
- It can improve the network performances, but triggering the fetch from JS is not free neither 
- It has no utility if all images are in the initial view
- Being SEO friendly requires additional markup

A good candidate for lazy loading should:
- Have an important number of images (> 50?)
- Have enough scroll distance between the images so that we don't end up loading all the images at once when we load the page

@maddhruv Can you specify the pages where we should lazy load the avatars?

**Comment by maddhruv** [comment]
As these improvements are landing in the V2
we can close this issue?
