### ISSUE TITLE
Homepage design enhancement for collectives cards

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2244]
**Describe the bug**
The 4-4 cards shown in the _Recently Created_ and _Most Active_ Collectives
are broken into uneven 3:1 of grids

**To Reproduce**
1. Go to https://opencollective.com/
3. Scroll down to Active Collectives Section
4. Change screen dimensions to iPad
5. See design error

**Expected behavior**
Should either show all 4 in a row like iPad Pro
or show 2:2 like other mobile devices

**Screenshots**
<img width="602" alt="Screenshot 2019-07-14 at 12 48 33" src="https://user-images.githubusercontent.com/18121502/61180578-160e6e00-a636-11e9-9066-750eac0c5ab4.png">

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]
 - OS: [e.g. any]
 - Browser [e.g. any]
 - Version [e.g. any]

**Additional context**

**Comment by maddhruv** [comment]
@znarf

**Comment by Betree** [comment]
Thanks for this issue @maddhruv 

> Should either show all 4 in a row like iPad Pro
> or show 2:2 like other mobile devices

There's not enough space to display 4 in a row and we'll loose space on the right if we display only 2:2. The proper fix could also be to do 3:3.

As we're re-designing this page I'm not sure that we want to invest time fixing this. I'll add a `won't fix` for now and will let @znarf close or update accordingly.

**Comment by maddhruv** [comment]
@Betree I have seen the issues regarding the redesign of several pages
I want to help and work on these
any steps or particular issues I can contribute on?

**Comment by Betree** [comment]
@maddhruv These are usually tackled by the core team because it requires close collaboration with the design team and the rest of the team. We don't have open issues for the re-designs right now but you can check the [open bounties](https://github.com/opencollective/opencollective/issues?q=is%3Aopen+is%3Aissue+label%3Abounty) and [good first issues](https://github.com/opencollective/opencollective/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+) if you're looking for places to contribute

**Comment by Betree** [comment]
Closing because we're redesigning this page entirely, it's not worth investing in small UI enhancements for it at the moment.
