### ISSUE TITLE
Proposal for new business model

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2251]
## Why?

Our goal is to enable communities to become sustainable.
So far we helped raise more than $7M across more than 2,800 collectives hosted by more than [100 different fiscal hosts](https://opencollective.com/hosts) (the [Open Source Collective](https://opencollective.com/opensource) being the largest one having raised more than $3.6M for more than 1,000 collectives, followed by [Women Who Code](https://opencollective.com/wwcodeinc) who raised almost $1M for their 83 chapters).

Our philosophy has always been to [create more value than we capture](https://twitter.com/ValaAfshar/status/683698120664850432) but if we want to continue being a force for good, we need to make sure that we are ourselves sustainable.

Our business model so far has been to capture 5% of the money raised directly on the platform (like most other crowdfunding platforms). That means $15k/month on average in the past 6 months. That doesn't pay the bills (about $70k/month for a team of 6 FTE + infrastructure + legal costs).

![](https://d.pr/free/i/xGPRMj+)

(you can find all our financial data on our public drive: https://drive.opencollective.com)

We were able to finance so far the development of Open Collective through investments ([we raised $2.85M](https://docs.opencollective.com/help/about/investors)).

While we still have money in the bank (~$1M), we don't want to keep going mindlessly and reach a point where we need to ask for more money from investors. We believe that our best investors moving forward are our users.

We had a couple of conversations in the past few months / weeks about different paths forward ([fixed monthly fee based on budget](https://github.com/opencollective/opencollective/issues/1458), [call for contributors to define open collective v3](https://github.com/opencollective/opencollective/issues/1745), [Strategy: Where should Open Collective focus as a platform?](https://github.com/opencollective/opencollective/issues/2168)).

We [finally settled](https://github.com/opencollective/opencollective/issues/2168#issuecomment-509630941) on becoming a software platform for enabling individuals and entities to host open collectives in their community.

We see the business model as a tool to align the company and the community around that goal (think of it as a heuristic that an AI would optimize for).
If our source of revenue is solely based on 5% of the money raised by credit card, we will naturally gravitate towards helping collectives get the most financial contributions that can be processed by [Stripe](https://stripe.com).

The reality is that a large number of collectives want to receive large sponsorships and grants that often can't be made by credit card. That's why hosts offer a way to make a direct donations directly to their bank account. Then using Open Collective, they manually allocate those funds to the right collective. When that happens, we don't take any commission.

To refocus the company and to make sure that we can support all those collectives no matter their source of funding, we would love to move to a monthly fee per collective of $20-$10/month. This will also allow us to help collectives get more than just financial contributions. The primary source of energy of a collective are people contributing their time. We want to embrace that. We also want to [improve the expense flow](https://github.com/opencollective/opencollective/issues?q=is%3Aissue+is%3Aopen+expenses+label%3Aexpenses).

## New proposed pricing model

|                     | free  | $10 | $50 | $100 | $250 | $500 | $1,000 | $2,500 | $5,000 | $10,000 |
| ----------- | ----- | ---- | ---- | ---- | ---- | ---- | ------ | ------ | ------ | ------- |
| collectives | 1     | 1   | 5   | 10   | 25   | 50   | 100    | 250    | 500    | 1000+   |
| Commission  | 5%    | 5%  | 5%  | 5%   | 5%   | 5%   | 5%     | 5%     | 5%     | 5%      |
| Add funds   | -     | ✓   | ✓   | ✓    | ✓    | ✓    | ✓      | ✓      | ✓      | ✓       |
| Expenses    | 25    | 100 | 500 | 1,000| 2,500| 5,000| 10,000 | 25,000 | 50,000 | ♾       |

What this would mean in terms of revenue based on our existing user base:

|               | free  | $10 | $50 | $100 | $250   | $500   | $1,000 | $2,500 | $5,000 | $10,000 |
| ------------- | ----- | --- | --- | ---- | ------ | ------ | ------ | ------ | ------ | ------- |
| collectives   | 1     | 1   | 5   | 10   | 25     | 50     | 100    | 250    | 500    | 1000+   |
| hosts         | 37    | 71  | 40  | 8    | 5      | 3      | 3      | 2      | 1      | 1       |
| total revenue | $0    | $710| $2k | $800 | $1,250 | $1,500 | $3,000 | $5,000 | $5,000 | $10,000 |

As a comparison, [Expensify](https://www.expensify.com) [charges $10-$5/month/user](https://www.expensify.com/pricing.php) to manage expenses and [Meetup.com](https://meetup.com) charges [$24-$10/month for up to 3 groups](https://help.meetup.com/hc/en-us/articles/360001620472-Organizer-Subscription-Pricing) and $30/month/group for [Meetup Pro](https://www.meetup.com/pro/).

Applying this new pricing to existing hosts would triple our monthly revenue from ~$15k to ~$45k (~$30k of monthly fees + ~$15k from the 5% commission). This is purely for illustration purpose as in reality we will grandfather most of them (see below).

#### Should we price based on the number of active collectives or collectives created?

While it may make more sense to base this on active collectives (collectives that have at least submitted one expense or got at least one donation during the month), this can quickly become difficult to manage and to budget ahead. An alternative could be to charge on collective created but make it easy for hosts to detect inactive collectives and archive them.

#### Should we allow the host to add funds for the first free collective?

It's good to let users try all features so that they know they exist. Maybe we could just put a limit on the total amount of funds they can add to their collective?

#### Grandfathering existing hosts?

It's good practice to grandfather existing users.
But we should probably exclude from that the hosts that we are directly managing given how much resources we are dedicated to them (namely the [Open Source Collective 501c6](https://opencollective.com/opensource) and the [Open Collective Foundation 501c3](https://opencollective.com/foundation)). 

#### Should we keep the 5% fee on the money raised?

We could potentially adopt [a model like Shopify](https://www.shopify.com/pricing) where you can opt-in to pay a higher monthly fee in exchange of a lower commission per sale.

If we remove entirely the 5% commission that would mean $15k/month less (based on current numbers)

One could argue that this would add more complexity in our pricing model.
We could also argue that it would be better to start simple. We can always change this later.

### Should we also discriminate based on number of expenses?

Our server costs are directly proportional to the number of expenses stored since they each have an attachment
- 767 collectives have submitted at least one expense
  - 174 have submitted more than 10 expenses
  - 93 more than 20 expenses
  - 11 more than 100 expenses
- 2 hosts have more than 2,000 expenses (Open Source Collective and Women Who Code)

As above, one could argue that this would add more complexity in our pricing model.
We could also argue that it would be better to start simple. We can always change this later.

## Next steps

We already had a few conversations with existing hosts but we would love to reach out to more of them to make sure they are included in this process. While this new pricing model won't affect them in the short term, they will probably have good feedback on the budget they can dedicate to make an open source platform like Open Collective sustainable. We also want to make sure that hosts are sustainable themselves!

Then we will have to design new flows to create and onboard hosts and collectives.

Our goal would be to implement such new model by September 2019.

**Comment by alanna** [comment]
Thanks for writing this up and moving the discussion forward @xdamman! There are exciting possibilities here. 

Just to reinforce a positive spin, it's not just about the platform being financially sustainable, it's also about how that will enable us to become a more amazing tool for more fiscal hosts, who will bring their networks of Collectives with them, and provide essential infrastructure for lots of groups. Financial sustainability is a means to that end.

Some thoughts....

### Free and freemium

I like the idea of a free plan for single-Collective hosts. We could be 'soft' about it and let them have most all functionality truly free, with a 5% commission, or we could be 'hard' about it and not charge a commission so it's totally free, but limit the features available. Or some combination.

There are more potential features we could use to tempt people to upgrade to the $10/mo plan:

* Add funds manually
* Updates
* Events
* Custom tiers
* Appear in 'discover'
* Turn on host fee charging functionality
* Enable multiple admins

I'm not saying all of these should be behind the paywall, but we should consider the full range of possibilities. If we go this way, we'd need to radically improve all these premium features and make them really show their value. I'm excited about that.

I was previously quite against the "Open Collective Pro" idea previously. Now I realise that's because it was focused on charging end-users (expense submitters) and it seemed like the wrong approach. I am in favor of this new idea because it's charging the entities that have money flowing and are really getting the value (hosts).

### Charging for active Collectives
I don't think we should charge for inactive Collectives. Customers should pay when they are getting real value.

I really like your idea of host admins defining this explicitly instead of defining this through activity metrics. Make it easy for them to activate and deactivate Collectives as a setting.

Inactive Collectives could stay online and their page and history would be visible. But these features could deactivate:

* Receiving funds (via Stripe or manually)
* Paying expenses
* Creating events
* Sending Updates
* Contact button

The reason I like this approach is that I don't want to disincentivise hosts from creating new Collectives. I don't want them to hold back because they will have to pay $10 more a month. If they know they can deactivate it and not be charged for it at any time, that would ease their mind. If it turns out to give them value, they'll be happy to pay.

### Host pricing models
Part of this pricing model evolution will be about radically simplifying the pricing story we can tell. Right now it's a confusing mess with platform fees and host fees and payment processor fees, as we know.

Open Collective Inc can tell one pricing story, and it will be told to fiscal hosts as the customers. Once we answer the questions in this thread, it will be super clear and predictable.

Collective core contributors will become the customers of their fiscal host. They will also be told one simple pricing story, by the host. They won't need to think about Open Collective Inc's pricing model if they aren't the host admin.

Therefore, the platform should support hosts to choose and communicate their pricing model well. This is part of us focussing on building a better tool for hosts. If we help hosts nail their own business model, they will be more than happy to pay fees to Open Collective Inc.

During onboarding, we can offer them options for their host fees:

* Set a % commission on funds contributed to Collectives (credit card, manual, or both)
* Set a flat monthly fee
* Donations (Collectives pay what they want to support their host)
* Free
* Potentially other options too

As part of this, we could finally automate the collection of host fees. Hosts should be Collectives in terms of functionality, meaning their pages would show their budgets, expenses, core contributors, etc, instead of making hosts manually create a seperate default Collective.

I'm very excited about enabling a range of creative fee models for hosts, because I anticipate a diverse range of communities coming on board, who each have a different context and therefore need to match their pricing model to it. If it's a big foundation that gives grants, they may want to offer the service free to grantees. If it's a membership network, they want to charge $10 per chapter. If it's an entity looking to pay its costs through fees for providing value to a community (eg OSC), then we can enable that too. We already have all these examples as hosts now.

### Don't charge based on number of expenses
I am not in favor of charging or limiting based on number of expenses. Some Collectives have 100 small expenses while some have two massive ones, and they both are getting roughly equal value. 

Plus, processing expenses is actually done by the host admin. If anything, we should enable *hosts* to charge Collectives who generate lots of expenses. But I don't think we should because it's unnecessary complexity.

It doesn't make a difference to Open Collective Inc how many expenses a host has to process. From Inc's perspective, we want to incentivise more activity, more budget transparency, etc, not disincentivise it.

**Comment by aptalca** [comment]
Some thoughts on Expensify comparison:

I don't think it's fair to use Expensify as a comparable service. In my opinion Expensify and Open Collective are vastly different in terms of the target user base although there are some similarities/overlap in the services offered (expense tracking and reimbursements).

As a preface, I'm making an assumption that most of Open Collective's clients are using a separate fiscal host rather than host themselves. That's how my FOSS collective is intending on using Open Collective. The main reasons being (in ranking order):
1) We did not form and do not intend to form a company any time soon (too much overhead, not enough team members to absorb the workload)
2) We do not have a company bank account
3) We need to track expenses and initiate reimbursements

On the other hand, we use expensify for my company (for profit) simply to manage employee reimbursements. The company is incorporated and has bank accounts, so we only needed reimbursement management.

Expensify is a great fit for my company, but we would not consider Open Collective as an alternative. Here's why:
1) Expensify does ACH transfers in and out of our company bank account. No paypal, no transaction fees. They deposit directly into employee bank accounts.
2) They integrate really well with Quickbooks
3) They don't care about incoming funds. They only handle reimbursements, and they do a great job at it

Similarly, my FOSS group is interested in Open Collective but would never consider Expensify as an alternative, because
1) No bank account to ACH from

Also, at my company, expensify is not even used to track all company expenses. That is done through Quickbooks. Expensify only manages reimbursable employee expenses. A very specific service for a very specific problem.

Now, I might be wrong with my assumption that most collectives on your platform use a separate fiscal host. If that is not accurate, you can disregard my message above.

**Comment by xdamman** [comment]
@aptalca thanks for chiming in and bringing another perspective.

You are right that Expensify and OC are very different products. We are not competing in any way (nor do we intend to). The goal of the comparison was more about having an anchor point to know how much we could charge hosts to use OC.

Before we created Open Collective, Women Who Code was actually using a combination of Expensify and Spreadsheets (AirTable). But it was a mess and very expensive for them.

**Comment by alanna** [comment]
Thanks for the comments @aptalca. 

Just in case it wasn't clear, in your case as a Collective not hosting themselves, in the new model you wouldn't be charged anything by Open Collective Inc. You would become a customer of your host, and each host would define its fees. In the case of the Open Source Collective, it would likely still be 10%, but that would be a simple charge instead of being a complex charge split into 5% for OSC and 5% for OC inc.

I definitely recognise that Open Collective doesn't provide the full functionality of accounting and payment system software. Most hosts will probably still need to use other tools to manage their finances. However the point is that you as a Collective admin won't have to worry about any of that stuff because you're outsourcing it to your host and paying a fee for that service. That's the pitch to Collectives from who they are a customer of, their host.

**Comment by Upperholme** [comment]
Initial thoughts:

The gap between $15K per month and $70K per month is big. Even applying your proposed model to existing hosts (which won't be the case) you are still $15K per month away from breakeven. i.e. the proposal doesn't solve the issue.

OC has had a significant impact in the open source tech space, but it feels like there is a lot more value that could be added there, and partnerships/collaborations yet to be built that could make OC as  much a part of the open source world as Github. I'm not sufficiently closely involved in that community to make further comment, but my sense is that there is plenty of money in the open source world, but that it is unequitably distributed, so maybe there's a strategic role there for OC to resolve that issue, and be sustainable itself through that work. Other orgs are doing stuff in this space, inc. Github and Tidelift. How does OC differentiate and thrive in that segment? The back your stack thing shows promise - what's the scope to grow that?

Setting aside the specifics of the open source space, overall my perception is that OC has reached an early point in its development whereby it has validated the core proposition (that there is a useful role to play in enabling collectives to manage income and expenses without need for incorporation and/or a bank account), and that it now needs to develop that proposition into a sustainable business model. 

Is that sustainability simply a case of growing the scale of OC. Today the website states 1154 collectives - would scaling that to 11,000 deliver a sustainable business? - 110,000? Or is the core business model fundamentally flawed in that supporting more collectives simply generates a bigger gap between net revenue and costs?

What I don't know is what the lifecycle of a collective looks like. Are they fairly short term, using OC while they get their act together, and then once they do they incorporate and/or get a bank account and no longer needs OC's services, or are they content to continue and use OC over the longer run? If we are really in a post-Coasian paradigm where transaction costs are so low that we don't need companies any more then the number of collectives is set to grow enormously, and capturing a percentage of those, and delivering useful value added services seems like a real opportunity. Providing a financial service is just one element of that product/service mix, and there are others that OC could be assisting with. Has that option of developing horizontally to offer a wider range of services to collectives been explored? Or is the goal to do one thing, and do it really well? If the latter, there's no shortage of improvements to the OC platform that are needed in order to make it much clearer and easier to all parties what OC actually does and how to make it work.

As someone involved in a small host organisation, our rationale for becoming a host was perhaps atypical. We want to see many more collectives created in our space (the cooperative economy) and so the idea of offering a service to early stage pre-start groups to enable them to receive funds from supporters and help them to grow their crowd using OC makes sense to us. Would the proposed charges have had an impact on our decision to become a host? Very probably. As it is our use of OC is a time cost that is likely to grow and outstrip any revenue that we receive by being a host. That's OK, because we see our role as a host as partly a marketing activity and partly as an element of our emerging service offering (we're new ourselves). But if each new collective that we supported were to cost us $10 a month it is a much steeper hill to climb, and right now we wouldn't be in a position to fund that cost. It would change our whole approach, but as I say we may be atypical as a host.

OC is a platform business, enabling an ecosystem. As such I'd encourage you to take a look at http://platformdesigntoolkit.com if you 've not already done so. I'd say that so far OC has done solid work on the Transaction Engine aspect, but still with lots to do on that, and has a longer way to go to get the Learning Engine aspect in place. Generating more revenue is clearly an increasingly urgent priority, but I do fear that disincentivising newcomers to the platform through price will slow the growth of the ecosystem without a clear improvement in the quality of the offer.

Hope this is helpful.

**Comment by xdamman** [comment]
@Upperholme thanks for taking the time to share your thoughts and your perspective.

While it’s true that we won’t get to profitability immediately by announcing this new business model, the real intent here is to change the dynamics. We have not invested enough in the expense flow, in the dashboard for hosts to manage their collectives and other features like that because the reality is that they don’t have a large impact on the total amount of money flowing through the platform, and therefore our bottom line.

By charging a monthly fee to all collectives, it will change how we will prioritize things.

You are right to say that there is still a lot of value / money in the open source space and we could play a larger role there. BackYourStack subscriptions could really help there. I see this more as an AND than a OR story. It has the potential to show that there is so much value that could be created on top of Open Collective once you have so many “organizations” on top of one platform and you could programmatically disburse money among them.

> But if each new collective that we supported were to cost us $10 a month it is a much steeper hill to climb, and right now we wouldn't be in a position to fund that cost.

Wouldn’t each collective be ok to pay that amount? After all, that’s the amount that they would have paid to a bank to open a bank account for their group.

It reminds me a bit of [that post](https://signalvnoise.com/posts/2751-scott-heiferman-looks-back-at-meetups-bet-the-company-moment-) about the day Meetup.com changed from free to $19/month. Painful process, people hate it, but eventually it plays out. The key for them was that charging was a great filter to make sure that people were committed to create great meetups.
I think likewise for hosts, you want to have people who are committed to create great collectives. 

Also agreed on the learning side of things. I wonder how we could help hosts provide that layer. I’d love to see hosts that would be incubators of collectives. Ideas / propositions welcome! :-)

**Comment by Upperholme** [comment]
> Wouldn’t each collective be ok to pay that amount? After all, that’s the amount that they would have paid to a bank to open a bank account for their group.

So why not just open a bank account? And, if I do have a bank account, I'm then not paying a 10%+ fee to receive money into that account. The higher the cost for each collective, the greater the disincentive to  set up on OC, which goes directly against what I assume to be a key aim for the ecosystem, i.e. to substantially grow the number of collectives using the platform, and thereby build network effects. Yes, I get the point about a fee helping to focus the mind and drive action, and that's certainly a factor, but the fee also steepens the on-ramp.

For me the way ahead is to add value. Add value for hosts by making their life easier, and giving them options and tools to add value for, and maybe generate some revenue from, the collectives they host. Add value for collectives by expanding the service offering. Add value for everyone by enabling the learning engine. As a consequence the whole platform makes more sense for everyone, and they'll be enabled to move money through it, and pay more of that to OC. In short: make the platform better and everyone, including many of the 'grandfathered' hosts/collectives may well be happy to make a bigger contribution.

**Comment by xdamman** [comment]
> Add value for hosts by making their life easier, and giving them options and tools to add value for, and maybe generate some revenue from, the collectives they host. 

Can’t agree more. That’s exactly our goal with this move. Hosts want tools such as “Add funds” and better expense management. We need to align our business model with the value that we want to create. The ecosystem needs much more than just yet another platform to help them raise money. That’s why we want to break free from the model of just making money on the money raised online by credit cards.

You are right that this will steepens the on-ramp. It’s a risk. That’s why we want to make sure there is a good enough free plan. You can create a collective and host it yourself. That’s free. But if you want to start hosting other collectives, that’s where you’d need to upgrade.

**Comment by piamancini** [comment]
two cents from talking to small self-hosted collectives. I think maybe @xdamman is right that the first $500/$1000 raised on open collective should be free of the 5% fee. This can get more than one collective started.

**Comment by luceos** [comment]
To me it's unclear how this proposal affects:

- collectives that use a fiscal sponsor
- collectives that do not use a fiscal sponsor
- collectives that are a host to other collectives

From what I read this only applies to the last case?

I have a strong feeling you are doing this at the wrong time. Sustainable open source development is a very active topic right now. Any platform backing this goal will see a lot of attention. Changing your pricing scheme will have a serious impact on your growth and thus on the economy of scale. I wrote this while being under the impression that the cost scheme applies to every collective.

Another thing I considered is that you have collectives trying to raise funds, some being more active about this than others. These collectives need to attract attention to their collective in order to become sustainable. Aside from the current fees applied to transactions, demanding fees while you could be also attracting funds of your own doesn't really make sense to me. There should be sufficient potential partners out there willing to push funds into this project as its fundamental to sustainable open source.

I actually liked the idea of freemium or a simple opt-in (voluntary) monthly donation to OC.

**Comment by alanna** [comment]
Thanks for your thoughts @luceos ! It's helpful to get other views.

Let me answer a couple things that might be unclear. We use the term 'fiscal host' but it means the same thing as fiscal sponsor below. Sorry in advance for how complex all this is. It's our fault for not making it simpler. That's a big motivation for this business model discussion - simplification.

> collectives that use a fiscal sponsor

For Collectives in the Open Source Collective (fiscal host) - the vast majority of open source projects on the platform - the fee will not change. It will still be 10%. In the background, instead of 5% going to Open Source Collective and 5% going to Open Collective Inc, the full 10% will go to Open Source Collective (who will then pay a fee to Open Collective Inc but this will be invisible to users).

> collectives that do not use a fiscal sponsor

All Collectives must have a fiscal host to accept or pay out money, because it's the fiscal host who brings the bank account and stripe account and takes on the legal responsibility. I think you might mean Collectives who fiscally host themselves because they already have a bank account and entity set up for the project or use their personal accounts for their Collective. 

In that case, things might change. Currently self-hosted Collectives pay 5% of income to Open Collective Inc, and don't pay a host fee. This model proposes that changing to $10 per month per Collective. So if they self-host and just have one Collective, that's $10/month total.

@xdamman do we have some stats about self-hosted Collectives? What's the average they pay now on the 5% model, compared to $10/mo? I think it makes sense to look only at active Collectives for these stats, as there are a lot of inactive ones that could skew the numbers lower. My guess is for active Collectives, $10/mo might be much cheaper for them.

> collectives that are a host to other collectives

I think you mean fiscal hosts, because Collectives can't host other Collectives. In the current model, fiscal hosts can charge whatever % they want as a fee to the Collectives they host (5% is default) and pay nothing to Open Collective Inc. 

We're proposing that we change this to hosts paying $10/mo per active Collective to Open Collective Inc, and empower them to charge what they want to their Collectives for the service they provide. Some will charge $0. Others will charge a monthly fee. Others will charge a % on income. Each host's community of Collectives is different and we want to enable diverse models to suit them all.

This means that Open Collective's financial relationship would shift from being with Collectives to being with fiscal hosts. Hosts become our paying customers. They can turn around and charge Collectives if they want, but that's independent from Open Collective Inc's charges.

> Sustainable open source development is a very active topic right now. Any platform backing this goal will see a lot of attention. Changing your pricing scheme will have a serious impact on your growth and thus on the economy of scale.

I 100% agree! It's a very hot time for open source sustainability and we need to be fully in the game. The reasons I think this business model shift isn't as risky as you fear at this time are:

* The actual price to open source Collectives on the platform will not change
* We will be able to *greatly* simplify how we explain our pricing, by shifting that to come from fiscal hosts. Instead of this complicated 5% platform fee and 5% host fee thing, for Collectives with the Open Source Collective it will just be 10%, end of story. Other hosts will be able to tell a similarly simple story about pricing to their Collectives.
* We are still planning to be a leader in open source funding and sustainability, and are gunning to grow and focus even more in that space. It's just that it will be led by the Open Source Collective. Up to now, the two entities and brands have been very intertwined and it confuses everyone. But Open Source Collective has been evolving and getting a lot more active and distinct ([see this update for examples](https://medium.com/open-collective/news-and-opportunities-from-the-open-source-collective-e9dddfcafd23)). Because Open Source Collective is hyperfocused on open source only, it can speak to that community and pursue initiatives specifically for it.

> There should be sufficient potential partners out there willing to push funds into this project as its fundamental to sustainable open source.

Absolutely. For the most part, open source maintainers don't want to be trying to do sales and marketing and landing sponsor relationships. They want to be building their codebases and communities. We are very aware of that. Open Source Collective absolutely needs to be a matchmaker who brings funding to Collectives. We have been doing that already, but it should be 10x. 

One big thing we're doing right now is the Back Your Stack expansion where companies will be able to identify all their dependencies and commit to supporting them all financially, and then we do the legwork of collecting and distributing the funds. For maintainers, this will look like money just showing up in their Collective magically. @piamancini is also working on understanding and shifting industry norms around financially supporting open source. We need to change the whole culture toward more giving back and less one-way extraction. 

These are all technically initiatives of the Open Source Collective. There's still overlap with the Open Collective team and resources going into them, but we're on track to seperate that out more in the future.

I hope that helps shed some light!

**Comment by xdamman** [comment]
A new issue has been created for the creation of a new pricing page to reflect the updated pricing model: #2592

**Comment by znarf** [comment]
Closing.
