### ISSUE TITLE
Unexisting collective leading to "unexpected error" instead of 404

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2272]
When you search for a url that doesn't exist it takes you to an "oops page" instead of to the search page. 

To repro: search for a wrong URL for the first time. 

<img width="1270" alt="Screen Shot 2019-07-24 at 6 41 06 PM" src="https://user-images.githubusercontent.com/3671070/61811970-e5eb7a00-ae42-11e9-85dc-3fef2c65e55b.png">
<img width="549" alt="Screen Shot 2019-07-24 at 6 08 36 PM" src="https://user-images.githubusercontent.com/3671070/61811981-eb48c480-ae42-11e9-911f-727ed0d57d35.png">

**Comment by EslamHiko** [comment]
I can't reproduce the problem, it redirects me to `not found` page however, the error still exists in the console.

![problem](https://user-images.githubusercontent.com/18349358/65968868-23ccd600-e464-11e9-946c-472176e97a36.PNG)

So I think the solution to this issue is to prevent error message, Am I right?
