### ISSUE TITLE
Everything should be a Collective and Collectives should be able to do everything

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2276]
I have realised that a bunch of issues coming up recently are all actually part of the same problem (and some I haven't raised yet). I have been hesitating to post this because it's kind of like *OMG WE SHOULD CHANGE EVERYTHING!!* — but I honestly think if we made this shift the system would be so much simpler.

* Collectives should be able to submit expenses (#2266) - this is going to get more and more important as more Collectives charge out for services. I just had a very complicated discussion about invoicing for Open Collective Design to Open Source Collective - this should be a very smooth process in our system.
* Fiscal hosts should be Collectives, with an integrated budget where their host fees go (#1723). Fiscal hosts are a type of Collective that can "have" other Collectives under its umbrella.
* Organizations should have a transparent budget so it's clear when they've added a bulk payment and how much credit they have left in the system. The page should also display the team members, contact button, and many other elements of a Collective page.
* User profiles should show both their contributions and their expenses they've been paid for (#2210 ), essentially a transparent budget. They should be able to frictionlessly use the balance they have been paid from submitting an expense to contribute to other Collectives if they want. Users already 'have' Collectives in our data model, which is confusing. They should just *be* Collectives.
* Collectives can already become financial contributors, but we need to enable it across hosts (#2017).
* Fiscal hosts and Organizations should be able to send updates. Core Contributors with Collectives in their host should be automatic subscribers, but others could subscribe too.
* When manually adding funds, you should be able to ascribe the source to an existing Collective or user, or create a new one (not having this results in issues like #2273 where we now have duplicate accounts and there's no one page that properly shows the transactions in one place).
* Collectives should be able to generate gift cards (#1546) not only Organizations.

Every type of entity on the platform should have access to all these actions and functionality. If they don't use it, it can be hidden (ex. user has no expenses only contributions, an Organization hasn't sent any Updates, etc). We can still have Collective "types" such as "user" "Collective" "Organization" and "Host", and those types can have different designs and notifications that best suit their needs (see #2062), but underneath it would be the same basic data model and functionality for all.

**Comment by Betree** [comment]
This is already working like that today. Users, organizations are also collectives and the only difference between them is the `type` field that can be `ORGANIZATION`, `USER` or `COLLECTIVE`.

> Collectives should be able to submit expenses (#2266) - this is going to get more and more important as more Collectives charge out for services. I just had a very complicated discussion about invoicing for Open Collective Design to Open Source Collective - this should be a very smooth process in our system.

The reason why it's not possible today is because your paypal email is attached to your user, not to your collective. It's legacy and we'll surely move away from that in the revamp of the expense flow when we'll support multiple payouts.

> Fiscal hosts are a type of Collective that can "have" other Collectives under its umbrella.
Organizations should have a transparent budget so it's clear when they've added a bulk payment and how much credit they have left in the system. The page should also display the team members, contact button, and many other elements of a Collective page.

Adding a bulk payment doesn't show up in the transactions because it's not a transaction, we're creating a payment method.

> Users already 'have' Collectives in our data model, which is confusing. They should just be Collectives.

It can be confusing at first but it actually makes sense because users can contribute from multipleprofiles (themselves, incognito, as an organization they're an admin on...etc) yet you want to have a single entry point for them to login that contains their email and that we can log to know who did this specific action (for example we need to be able to know which users sent money out of a collective).

> Collectives can already become financial contributors, but we need to enable it across hosts (#2017).

I don't see how this is related.

> Fiscal hosts and Organizations should be able to send updates. Core Contributors with Collectives in their host should be automatic subscribers, but others could subscribe too.

It's technically feasible, it's just disabled in the interface. We can enable that if needed.

> Collectives should be able to generate gift cards (#1546) not only Organizations.

I don't see any blocker in the code, it's just disabled currently.

> Every type of entity on the platform should have access to all these actions and functionality. If they don't use it, it can be hidden (ex. user has no expenses only contributions, an Organization hasn't sent any Updates, etc). We can still have Collective "types" such as "user" "Collective" "Organization" and "Host", and those types can have different designs and notifications that best suit their needs (see #2062), but underneath it would be the same basic data model and functionality for all.

Again I may have missed something, but from what I understand that's exactly the way it works today.

**Comment by alanna** [comment]
OK great, so we have some of the building blocks in place @Betree - so how do we enable all these actions for all these types of Collectives? Because right now it feels artificially limited and we're having to do a lot of complicated workarounds.

**Comment by Betree** [comment]
@alanna There are too many topics in there to provide a general answer, I tried to reply to specific points above. Which ones are still unclear?

**Comment by alanna** [comment]
I think you are saying that under the surface many things actually work this way already but are hidden. I am talking about bringing that functionality out and making in accessible to users. So what's not clear to me is how to get there. 

Many of the ideas mentioned already have issues open for them (see my original list) but not all. I can raise issues for the rest if that's helpful. I started this issue because I only recently realised how all these things are related, and I thought maybe talking about the big picture would be useful. But maybe it's not.

**Comment by alanna** [comment]
I will raise the seperate issues now for the things that don't have one already.

**Comment by Betree** [comment]
Most of the things reported are either technical debt (collectives to submit expenses), features to add (show bulk payment methods creation in transactions) and features that we've intentionally hidden for some collective types that we can enable if we now think they would be useful for them (updates for organizations, gift cards for collectives).

I don't see a general pattern to solve (or facilitate) everything at once. So I think that we should indeed focus on specific issues. Said differently, there's not one single answer about how to get there, it's specific to each issue.

I may not have fully understood your proposal, for example I still don't see how this below is related to having profile types (org, users, collectives) using the same model underneath.:
> Collectives can already become financial contributors, but we need to enable it across hosts (#2017).

Maybe we should add this to our plate for tomorrow's meeting to ensure that I didn't misunderstood what you're proposing.

**Comment by alanna** [comment]
I'm closing this because @Betree explained it's not useful to think about the big picture here. Instead I've raised a couple more individual issues for the different features. I still think long term our platform would be a lot easier to maintain and use if everything on it were a Collective with all the associated features, and then we could make small tweaks for users, orgs, hosts, and other types of entities.

**Comment by Betree** [comment]
> if everything on it were a Collective with all the associated features, and then we could make small tweaks for users, orgs, hosts, and other types of entities.

Sorry if I sound like a parrot but that's what we already do, everything is already a collective :slightly_smiling_face: The real issue is that we carry technical debt from some features that were implemented with conditions specific to orgs/users...etc. But this is related to these specific features, not to the data model.
