### ISSUE TITLE
Revamp Apply to host button

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2282]
The current `Apply` button has an important issue: it can only accept one option. https://github.com/opencollective/opencollective/issues/2281 showcase that there can be multiple options for this button:
- Apply from GitHub
- Apply manually
- Apply with MyCollective
- Apply with MyCollective2

Most of the time, the only option will be `Apply to create a collective`.

**Comment by piamancini** [comment]
> Apply with MyCollective
> Apply with MyCollective2

Is this the use case of - I created my collective with no host and now want to apply?

**Comment by Betree** [comment]
@piamancini yes

**Comment by alanna** [comment]
It would be great to improve this!

My suggestion would be to just have the button simply say `apply`. Then what happens after you click depends on the circumstances.

* If the user has no Collectives → Create new as a pending Collective under this host.
* If the user has one or more Collectives → Show a list of their Collectives and let them select one or choose 'create new'.
 * In an ideal world, you would even be able to choose a Collective that already has a host and remove it to change to the new host in this flow. But that gets complicated because they need to have a 0 balance. For MVP we could show all their Collectives but only unhosted ones are selectable, with help text saying 'If your Collective already has a fiscal host, you need to remove it before adding a new one. Go to edit Collective > fiscal host > remove." 
* If they are applying to the Open Source Collective, after clicking apply and selecting or creating the Collective, they should be given the option to verify with Github or apply for manual verification.
* If we want to make a good generalisable feature to serve diverse hosts, it would be great if the apply button took you to an application form editable by host admins. Currently the pending Collective notification emails have very little info in them and I have to reach out to prospective Collectives with questions like "Are you in the US?" etc, to verify they meet the host's criteria. Having a form they fill out would be amazing. Even if it was super basic (text fields only).

**Comment by piamancini** [comment]
> If they are applying to the Open Source Collective, after clicking apply and selecting or creating the Collective, they should be given the option to verify with Github or apply for manual verification.

We should clarify that manual verification will require a similar traction proof like 100 stars in github. 

> If we want to make a good generalisable feature to serve diverse hosts, it would be great if the apply button took you to an application form editable by host admins. 

+1 For the sake of pushing through this I would plan for this item after the 1st release.

**Comment by raulgrafico** [comment]
@alanna Hi Alanna!

We need your help with this issue; please take a look at this: https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hot-Fixes?node-id=1122%3A16. 

I made three ddifferent versions of this modal:
A - Includes link to the settings page so you'll be able to remove your Fiscal host, but then you need to manually go back to the Fiscal host page and then apply again.

B - Displays your collectives, including a message under those collectives that already have a Fiscal host.

C - Not displaying collectives that already have a fiscal host.

Not sure which one makes more sense for Fiscal hosts, or if you have a better idea on how to fix resolve this.

Thank you, Alanna :) I hope everything is fine with your baby!

**Comment by alanna** [comment]
Sorry for the late reply.

We should go with option C, because changing fiscal hosts is actually a more complex process that we can't handle inside this modal (e.g. if the Collective balance is not at zero we can't allow it, etc). For MVP we should simply allow them to select from their unhosted Collectives or create a new Collective. I think create new is by far the most common scenario, so it should be on top (the basic crew option, then github, then select from existing unhosted if there are any).

@cuiki can you take this on and get it ready for a dev to implement?

**Comment by alanna** [comment]
@Memo-Es is this in scope for the host dashboard project?

**Comment by Memo-Es** [comment]
It was in development before beginning the host dashboard project and it got staled for a few months, I'm adding this issue to our tasks for these upcoming weeks @alanna

**Comment by Memo-Es** [comment]
Closing in favor of #3728
