### ISSUE TITLE
unable to add/remove contributors

### ISSUE THREAD

**Issue by mojoaxel** [opencollective/opencollective#2284]
**Describe the bug**
I'm unable to add new contributors.

**To Reproduce**
1. Go to https://opencollective.com/visjs/edit/members
2. Click on 'add more contributors'
3. Fill in the empty form.
4. Click 'save'
5. See error: `Validation error: In Support's tier, "Amount" is required`

**Expected behavior**
It should be possible to add/remove contributors!

**Screenshots**
![image](https://user-images.githubusercontent.com/600565/62109830-67149800-b2ad-11e9-94ef-298b79b72afd.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Chrome Version 75.0.3770.142 (Offizieller Build) (64-Bit)

**Comment by Betree** [comment]
@mojoaxel This is because your `Support` tier on https://opencollective.com/visjs/edit/tiers is configured to use a fixed amount, but no amount has been provided. You can either set its type to `Flexible` or set an amount.

We acknowledge that this validation is crazy and totally counter-intuitive. We have a plan to revamp that (#2253). In the mean time, sorry for the inconvenience.
