### ISSUE TITLE
Collective Page→ Feedback Navigation Collective Page

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#2290]
## User story 
Here under we have option A and B for Navigation in te collective page.
This is to collect feedback for both options pros and cons.

## Referenced Issues 
#1928 

## Links

Option A
https://tafka.d.pr/S5GyYn

Option B
https://tafka.d.pr/6IwscL

**Comment by alanna** [comment]
I would vote for A because otherwise you lose the context of being on a Collective page.

**Comment by Betree** [comment]
- In A my only concern is how it will look mobile/tablet, we already have users saying that the current menu for V2 is too big (#2225). I'm not sure that we need to fix it in there because it doesn't help you to navigate on the page.

- In B the sudden change of the NavBar feels unexpected. Having the collective info fixed only during 200px of the scroll doesn't make much sense to me. I'd rather have only the info about the current page fixed, we don't need to fix the collective navbar for such a short distance.

  I do like having this header that is specific to the page, this is especially helpful to know where you are when you open multiple tabs. I don't agree that you loose the context of the collective page because you still have it at the top, it's just not fixed. It's actually what GitHub does right here and I find it pretty clear.

**Comment by piamancini** [comment]
I agree with Ben that B feels strange, the double step. 

> 
I don't agree that you lose the context of the collective page because you still have it at the top, it's just not fixed. It's actually what GitHub does right here and I find it pretty clear.

+1 

I would vote for B without the double step

**Comment by xdamman** [comment]
Thank you for those videos, it’s so great to be able to see those behaviors in action 👌 

I agree with all comments. We want to keep it as small as possible to maximize the screen real estate for the conversation. So A is way too tall.

I’d suggest a mix of the two.

Also, to simplify the top bar, I’d remove “Pricing”. Just having it on the homepage and within the Help & Docs is more than enough.

![IMG_0300](https://user-images.githubusercontent.com/74358/62364893-9da31a80-b51a-11e9-9b59-2305a3451c63.jpeg)

**Comment by lindatalu** [comment]
The discussion now is going to be about to CTA buttons for secondary navigation on the collective page here the link to the figma file
https://www.figma.com/proto/KinuveYf4WUlRIXzMTnmIsmO/OC.COM-XX1-Lab?node-id=223%3A51&viewport=453%2C935%2C0.7145232558250427&scaling=min-zoom @xdamman @piamancini @raulgrafico

**Comment by Betree** [comment]
There's no indication on the `Edit goals` page about what will change if you pick an option. Collective admins may end up changing their call to actions unintentionally.

If we're going to let users customize their call to actions, wouldn't that be clearer to let them pick precisely the two calls to action that they want to display (as suggested in https://github.com/opencollective/opencollective/issues/2239) rather than picking a `Collective Stage`?
