### ISSUE TITLE
Onboarding flow for new collectives / hosts: personas 

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2295]
The first step is to clearly identify the personas of the users that will actually come to open collective to create a collective.

I see 3 of them that I’ll describe below. Feel free to add to this. The more stories we have, the better we will be able to meet their expectations.

1- Founder/Core contributor 

“I want to collect money for my (open source) community.”

This persona is attracted by the ability to collect money from and for the community. This is the one that we’ve been focusing on so far.

The biggest appeal was: you can collect money without having to create a legal entity in a transparent way for the community.

**Pros**: painkiller for transnational online communities. We already have a good name and a network effect in the open source community.

**Cons**: quite expensive (10% fee + payment processor fees). Needs approval from the community (may take a while).

2- Contributor in charge of finance

“I need a place to manage openly the finance of our collective.”

This persona will be more attracted by the expense management features.
For example: Evin from XR Hackney.

“I joined XR Hackney. I wanted to contribute. I saw a need to manage finance for the group so I volunteered and took the lead with someone else. We use chuffed.org and crowdjustice to raise money because it’s cheap. But we needed a place to manage expenses. Open Collective is great for that. Would be great if we could connect it to those other crowdfunding platform to automatically add the revenue from them.”

**Pros**: no politics. Just need to get the job done. 

**Cons**: they need a free version. They don’t like paying a tax on money coming in but could be sold on a low flat monthly fee.

3- Finance person for a non profit

“It’s a nightmare to manage the balance of the different projects that we fiscally sponsor. There’s got to be a software platform for that.”

Alaina / Joey from Women Who Code: “we were using spreadsheet, then Airtable with Expensify to manage the different chapters that were asking for money. It was a nightmare to keep things up to date and to give them visibility on how much funds are left for each”

**Pros**: they are less price sensitive. They are already experienced with the concept of fiscal sponsorship (which could be a negative since they already have processes in place that they would rather not change)

**Cons**: might be a long sales process, especially if the non profit is not new.

**Comment by alanna** [comment]
I conceive of this quite differently in light of the new strategy. I feel we need to think in those terms. My ideas are not necessarily in conflict with what @xdamman said but just structured very differently in my head.

@Memo-Es asked me to think about personas and flows for the new homepage design, so that was my starting point, but ultimately I end up at a similar place to this issue so I'm going to add my thoughts here.

I imagine 3 main personas arriving at the homepage potentially interested in engaging on Open Collective. Each needs to be guided to a different flow. The overarching principle for me is *don't try to tell multiple stories at once - instead guide people to where they can be told one story specifically for them*.

There are a few universal things we want to communicate to all personas, but very quickly we want to shunt them into flows specifically designed for them, so we don't distract and confuse them with info only useful to different personas.

The universal things are more about values than features:

* Transparency
* Contribution
* Credibility
* Funding communities

I think we should convey the above points in a very simple and lightweight way, and let them manifest fully in the experience the different personas have once they get into the flow designed for them, because they will be expressed differently in each context.

|  Persona  |  What they need when arriving at homepage  | Call to Action  |   
|---|---|---|
|  Potential Host creator  | Understand how the system works, simple pricing model ($10/active Collective/month), value prop, check out existing hosts  | Create host - needs to be sent into a much improved host onboarding flow, which works well for both large hosts and new self-hosting Collectives  |  
|  Potential Collective creator  | Discover a great host for them, then the *host* conveys their pricing (simple! one answer!), what they offer, and invitation to create Collective with that host (or figure out they want to self host and be transferred to 'potential host' flow) - do not distract them with info about value prop or pricing between OC Inc and hosts, they have one relationship and it's with the *host*.  |  Find host and create Collective |  
|  Potential financial contributor  | Discover Collectives they want to support, do not get distracted by info about hosts, creating Collectives, etc etc  | Make financial contribution |  

*Note: these are potential users, not existing ones. Existing users of each type need a different set of tools presented to them, but that's a different issue.*

The key to all of the above is supporting hosts to play their critical role in onboarding Collectives very well. This means the host onboarding must do a great job of helping them clarify and communicate their offering to Collectives, which Collectives they want to host (subject area, geographical location, etc), and what their pricing model is (charge a % on income, simply pass on OC $10/mo per Collective fee to the Collective, offer hosting for free, etc). So we need to make sure the new host onboarding flow is there to catch people coming through the homepage into that pipeline.

**Comment by Memo-Es** [comment]
Thank you @xdamman for starting this discussion,

I very much agree with @alanna 's idea of "Don't try to tell multiple stories at once - instead guide people to where they can be told one story specifically for them" for the homepage...

I think both are correct, but the way I see it they consider different phases of the user cycle inside OpenCollective. Let I get myself clear:

This is an onboarding model that describes how a path for each of our users might look like:
_(Considering the central message of the homepage has been successfully transmitted "Make your community sustainable" and "How do I make my community sustainable?")_

| Initial contact → with OC  | User story (need)  → | Platform user → | User story
| :---        | :---        | :---        | :---        |
| Potential host creator      | "There's got to be a better way to support an initiative to get funds and be sustainable doing it"        | Fiscal host admin | "I need an easy, streamlined way to manage the balance of the collective we host"  
| Potential Collective creator      | "I need an easy, transparent way to get contributions from and for my community, to make it sustainable"     |Core Contributor      |“I need a place to manage openly the finance of our collective (Donations, expenses, balance, etc.)”      | 
| Potential contributor  (Financial, code, or service-based)   | "I want to find and support initiatives I connect with"    |Collective contributor (This includes financial and non-financial contributions)    | "How can I stay in the loop with how the money is spent and the goals that are met with the collectives I currently support".      |

This model should work directing each of those 3 users to a page or flow where the value proposition specially designed for them, is transmitted with no other noise around. The main objective of these pages/flows would be to convert users.

I think Alanna's suggestions on "What they need when arriving" and call to actions are quite useful when we break down chunks of the design work at a more granular level.

Feel free to add comments and/or feedback.
 
 I will reference this issue in the Homepage issue #2264.

**Comment by piamancini** [comment]
### Feedback for @xdamman 

> quite expensive (10% fee + payment processor fees)

The ability to raise funds when you can't do it otherwise for 10% is only expensive if they community has another option. If not, it's actually quite cheap. It's from 0 to 1. 

> Contributor in charge of finance

This seems like super specific for a homepage persona. I think it's safe to assume that the core contributor creating the collective is also the person in charge of finances for narrative purposes. 

### Feedback for @alanna 

> don't try to tell multiple stories at once - instead guide people to where they can be told one story specifically for them.

Love this. 

> The universal things are more about values than features:
> 
> Transparency
> Contribution
> Credibility
> Funding communities

More than 'Funding Communities' I would think about making them grow/thrive or making them sustainable. It's broader than just funding but it includes it very clearly. 

> Potential Collective Creator Persona ---> Discover a great host for them

This is the end of the journey for them, not the beginning. To illustrate: 

First: Great, I can create a collective, add people, it's up and running, has my images, I can submit expenses, I can manually add funds I already have. Free up to $1000, great I can try it! 
Second: I want to raise funds through Open Collective, how can I do this? Oh cool I can connect a Stripe or a PayPal (one day, if the universe allows) account that I own. Done! 
Third: hmmm I don't have a paypal account / stripe for my community, I'd like someone else to to do this for me --> Discover a great host for you!

**Comment by alanna** [comment]
Based on what @piamancini said, I think we'll need to clarify the details of the new business model to actually nail clear personas and workflows here. I agree that works if it's free for that whole phase before finding a host. But since the "pricing" answer comes from the host, we need to get them in a host before we tell that part of the story, and pricing is one of the first questions people ask.

**Comment by xdamman** [comment]
I can totally see the two different approaches here. @alanna’s one is a great one for a very decentralized approach where we are super focused on developing the federation of hosts.

But I don’t think that we are ready for that yet. Fiscal hosting is a very complex topic to explain and that slows down our growth a big deal. Doing so would position ourselves into the B2B type of business with much longer sales cycles.

That’s why I’d rather see that as a dedicated page for hosts (e.g. a mix of https://opencollective.com/hosts and https://opencollective.com/become-a-fiscal-host) that we can link to from the homepage (maybe even a whole section on the homepage like we do have today for Back Your Stack).

For now, I think we should focus on the bottom up approach, meaning we need to start with the people who want to create a collective. Because the best way to get the Drupal Foundation or Wordpress or WWCode, or Extinction Rebellion, or what not, is become some of their chapters are already using it with success.

I think @piamancini’s paragraph nails it very well. To build on that (and I agree we can probably merge the contributor in charge of finance and the core contributor):

1. I have a project with other people, we are a collective. I can create an open collective to keep track of the budget transparently. I can manually record money in (add funds up to $1k) and out and enable anyone in the collective to submit expenses with a simple approval process.
That’s already in and on itself a very cool value proposition for free. Low barrier of entry (no need for a stripe account) -> We can see a lot of growth in that segment.

2. I can upgrade to a pro plan for $10/month once budget reaches $1k or to add cool features such as
  - raising money on the platform using a Stripe account and automatically account for those donations in the budget (with an extra 5% fee at least for now)
  - pay expenses using paypal (and automatically account for it in the budget)
  - other automation tools: automatically account for income from eventbrite / kickstarter / threadless / teespring / Shopify / etc.

In 1 and 2, there is no concept of host really. You are the host.

To keep things clean, I’d separate entirely the 3rd point (the concept of fiscal sponsorship) and market it differently as: “Open Collective for Organizations” (or “for Fiscal Sponsors”, or “for Auspices” for our Australian friends ;-) ).
Which is a bit the equivalent of Meetup Pro for organizations/networks, or Google Apps for companies. It’s basically a way for existing organizations to take control over a bunch of accounts. This pattern is not new and well understood.

Another analogy would be Wordpress.com. You can create an account or you can download the community version and start your own host. Or you can also reach out for the enterprise plan which is basically the same thing except it’s people from Wordpress that manage your server for you for a fee.

**Comment by piamancini** [comment]
+1 @xdamman

**Comment by alanna** [comment]
> That’s why I’d rather see that as a dedicated page for hosts

I agree. That's why I think the homepage should more be a place people go to get quickly filtered to a different page that speaks directly to their persona, not a page trying to explain everything in one place.

> 1. have a project with other people, we are a collective. I can create an open collective to keep track of the budget transparently. I can manually record money in (add funds up to $1k) and out and enable anyone in the collective to submit expenses with a simple approval process.
That’s already in and on itself a very cool value proposition for free. Low barrier of entry (no need for a stripe account) -> We can see a lot of growth in that segment.

I am very skeptical of this because it's possible right now and as far as I know we don't have any Collective using the platform to manually record transactions for the sake of transparency. If I am understanding this correctly this is the "host-less Collective" case, right? We have discussed this before and I thought we concluded that manual ledger tracking was a no-go because people won't actually do it and the value add is low compared to a spreadsheet. What evidence do you have that where is a market for this? We already offer this service for free - why aren't people using it?

2. is the "self-hosted Collective" case. I agree we need to make it much easier for this kind of Collective to get on board and up and running. That should be a big focus of the host onboarding flow improvement process.

3. is fiscal hosts. Yes this has a completely different sales cycle and very different approach. Personally I think the payoff could be huge here because onboarding one big host is a big win for us once we fix the business model so we actually get revenue from that. But going after whales is a high risk endeavor and we would need someone really focusing on it.

OK, 1, 2, and 3 are clear. But what about the biggest current use case on the platform?

4. I am a potential Collective creator whose project fits great with an existing fiscal host, like Open Source Collective. But I don't know that, and I don't know how the whole thing works. I don't really care about 'fiscal hosting' I just want to get my Collective started quickly and easily. I need to arrive at opencollective.com and somehow be smoothly sent to the host that my project fits in, where I can find out what their offering is and take the next step.

We have the bare bones of the flow we need already:

> Create Collective > choose between no host, self-host, or join host

However, it's very confusing and awkward as a user experience right now and we could radically improve it. We need to figure out a way to quickly peel off the no-host and self-host Collectives, and then help the Collectives destined for an existing host get there without needing them to understand everything about fiscal hosting, etc etc.

**Comment by xdamman** [comment]
> We have discussed this before and I thought we concluded that manual ledger tracking was a no-go because people won't actually do it and the value add is low compared to a spreadsheet. What evidence do you have that where is a market for this? We already offer this service for free - why aren't people using it?

We don’t really offer it. It’s such a hidden feature that no one knows they can actually do it. There is no easy way to record money in. You first need to create a host (which requires you to connect a stripe account!), then you can “add funds”. So no, I’d argue we don’t offer this option right now.

The biggest challenges with a spreadsheet (and I’ve been there with Tipbox), is the management of attachments, approval process, access rights, and transparency (+ exports). So yes, Open Collective could really really help. Fundamentally a lot of things can be done with a spreadsheet. It’s the most versatile and user friendly programming language. But people crave for dedicated tools to unbundle the spreadsheet.

Agree on the rest. The flow for open source collectives is definitely an interesting one. Thanks for bringing it back up.

However, this worries me because it would force us to expose the user to the concept of host in the onboarding flow, which is a complicated concept.

I’d rather first let people create a (self hosted) collective and then –based on their tags– suggest them to be hosted by a host that matches their description.

The idea is that the collective should be the top level unit. As such it should be able to have multiple hosts that can easily be switched (a collective is a fluid organization where contributors –including fiscal hosts– can easily come and go). We are not there yet but this should be our North Star.

Let me make a few flows based on this conversation.
