### ISSUE TITLE
Monthly report email: Empty "You have contributed"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2298]
In the user monthly report (`templates/emails/user.monthlyreport.hbs`), the amount next to `You have contributed` is not displayed. From the email I received I can say that this has been broken since (at least) December 2018.

---

![image](https://user-images.githubusercontent.com/1556356/62368053-b962ec80-b52b-11e9-836d-a5af94b39388.png)

---

**Expected behavior**

Should display the amount actually contributed.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by isnonsodanniel** [comment]
Hi, I'd like to solve this issue

**Comment by nonsodaniel** [comment]
Hi, I'd like to work on this issue

**Comment by Betree** [comment]
@nonsodaniel Sorry, this issue is already assigned

**Comment by znarf** [comment]
🏆 This issue was completed by @leonardohof 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
