### ISSUE TITLE
Emails not sent/received

### ISSUE THREAD

**Issue by staltz** [opencollective/opencollective#2302]
**Describe the bug**

I know that in the beginning of the month there are typically report emails sent by OC to collectives that I manage, but this month I haven't seen any. I also wrote an update to a collective, and published it. A friend who backs that collective said they received the email, but I haven't (I typically receive them, even if I publish it).

I have checked my spam inbox, and they're not there either. It seems to be a problem on your server side, but on the other hand, some people are receiving emails correctly.

**To Reproduce**
1. Go to some collective's Updates page
2. Create and publish an Update
3. Go to your email inbox
4. In some seconds or minutes, an email should arrive

**Expected behavior**

I see an email with the contents of the Update that I wrote and published.

**Actual behavior**

I don't see any email, in hours since I published.

**Comment by znarf** [comment]
We use Mailgun for delivering email. I looked in the dashboard and noticed your personal email address was in the "Complaints" list there since "07/08/19 08:45 AM".

Since this date, you're not receiving any email from opencollective.com, we can see such error in the logs "Failed: hello@manyverse.opencollective.com → xxxx@staltz.com 'August 2019 update' Not delivering to a user who marked your messages as spam".

I'm removing you from this list and we now need to understand how that happened.

**Comment by staltz** [comment]
Thanks for investigating it! By the way, I'm also very interested in the stats that are in the monthly report email, is there anyway I could get that?

**Comment by znarf** [comment]
Looks like Mailgun is tracking openings, so the data is there, but we unfortunately don't have any report we can share.
