### ISSUE TITLE
Collective Page→ Feedback Profiles Collective Page

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#2304]
## User story 

This issue is to collect feedback for profiles on collective Page.
As requested here under the images instead of the Figma complete file.

## Referenced Issues
#1928 

## File
**Large Profile-User - Empty**
![01-Large Profile-User - Empty](https://user-images.githubusercontent.com/34247919/62503876-c85fce00-b7bb-11e9-905f-09afd4b170e5.png)
**Large Profile-User - Half]**
![02-Large Profile-User - Half](https://user-images.githubusercontent.com/34247919/62503877-c8f86480-b7bb-11e9-9951-94fa42164f53.png)
**Large Profile-User - Filters**
![03-Large Profile-User - Filters](https://user-images.githubusercontent.com/34247919/62503878-c8f86480-b7bb-11e9-8a94-b3944b9075f5.png)
**Large Profile-User - Filled**
![04-Large Profile-User - Filled](https://user-images.githubusercontent.com/34247919/62503879-c8f86480-b7bb-11e9-9b0d-10d2de9c06a6.png)
**Large Profile-Host - Multiple-Hosts**
![05-Large Profile-Host - Multiple-Hosts](https://user-images.githubusercontent.com/34247919/62503880-c8f86480-b7bb-11e9-969e-4ec7de21ae49.png)
**Large Profile-Organization - Multiple-Hosts**
![06-Large Profile-Organization - Multiple-Hosts](https://user-images.githubusercontent.com/34247919/62503881-c8f86480-b7bb-11e9-918f-8404af788b75.png)

**Comment by piamancini** [comment]
Thank you! 

> This issue is to collect feedback for profiles on collective Page.

Profile pages (not on collective Page)

> Large Profile-User - Half

@raulgrafico there seems to be an awful lot of white space between the end of the collectives card and the transactions. This is not the case in the rest of the images. 

> Large Profile-User - Filters & Large Profile-User - Half

One says 'expenses and donations' the other 'credits and debits'. I prefer we use 'expenses and donations' 

> Large Profile-User - Filters
Transaction filter tabs are not aligned 

> Large Profile-Host - Multiple-Hosts

- This should be Multiple Collectives. We don't have a Multiple Host option. 

- Where does the Event tab link to? Events attended / sponsored by this profile? 

- Where is the dashboard link? 

> Large Profile-Organization - Multiple-Hosts

- This should be Multiple Collectives. We don't have a Multiple Host option. 

We are missing the view of the profile menu when the admin of the profile is signed in. How do I see where I can create a new collective, manage my subscriptions, create a new organization, etc.

**Comment by raulgrafico** [comment]
Hi Pia, I've made the changes on the profile pages, re the tab for events on organizations, can you please review this and give approval so we can move this from WIP to Done for Ben.

Re the tab for events on hosts and organization, I used the spec you created and the references on the current profile pages and I wasn't sure if organizations or host can have that tab, I just removed it. :)

![01-Large Profile - User - Empty](https://user-images.githubusercontent.com/1252676/62563678-1f5fb480-b849-11e9-8a1b-f6766891408e.png)
![02-Large Profile - User - Half](https://user-images.githubusercontent.com/1252676/62563679-1f5fb480-b849-11e9-8177-a848a591425c.png)
![03-Large Profile - User - Filters](https://user-images.githubusercontent.com/1252676/62563680-1f5fb480-b849-11e9-8a34-a8f6c7a76d88.png)
![04-Large Profile - User - Filled](https://user-images.githubusercontent.com/1252676/62563681-1f5fb480-b849-11e9-8ed4-735f2c1f2118.png)
![05-Large Profile - Fiscal-Host](https://user-images.githubusercontent.com/1252676/62563683-1ff84b00-b849-11e9-9b28-bcae3851e47b.png)
![06-Large Profile - Organization](https://user-images.githubusercontent.com/1252676/62563684-1ff84b00-b849-11e9-9f13-39caa60606f4.png)

**Comment by Betree** [comment]
I'm good with most of the proposed design. It's important that we address these questions from @piamancini above https://github.com/opencollective/opencollective/issues/2304#issuecomment-518598958 before we can move on:

- Where is the dashboard link?
- Where is the link to manage subscriptions?

@piamancini I'm not sure to follow the following one. We indeed loose the link to manage the subscriptions (that's a problem that we really need to address, people already have trouble finding their subscriptions). But I don't see where create collective/org is related.

> - We are missing the view of the profile menu when the admin of the profile is signed in. How do I see where I can create a new collective, manage my subscriptions, create a new organization, etc.

**Comment by Betree** [comment]
Can we add a screenshot collective card's hover state? I don't know how to trigger it on Figma.

Also when we look at these cards from a user or an organization page I think that we don't care that much about the number of contributors but we **do** care about how much and since how long this user/org has contributed. The previous version of the card were better contextualized on this regard.

![image](https://user-images.githubusercontent.com/1556356/62621539-65d21380-b91c-11e9-93a6-4de60da622a4.png) ![image](https://user-images.githubusercontent.com/1556356/62621642-b0ec2680-b91c-11e9-80cf-cc5818c88f4f.png)

**Comment by cuiki** [comment]
I agree on the context change within these cards. I'll make a task out of defining all versions of these –and other– cards so we know what supporting info to show and when.

**Comment by raulgrafico** [comment]
Hi guys, maybe we can do something like this?

![Screen Shot 2019-08-08 at 5 33 37 PM](https://user-images.githubusercontent.com/1252676/62742050-b2901a00-ba02-11e9-855f-0b973943fbe4.png)

**Comment by alanna** [comment]
I'm confused with the screenshots -  do they only show only a host Org page or also show a regular Org page? The designs for these two should be different. The example used here is FB Open Source, but in real life that Org does not have Collectives and it doesn't make sense.

I think non-host Org profile pages should show:

* Collectives they financially support
* Total financial contributions all time
* Team members (technically we said in the terminology workshop that this is the one case they shouldn't be called 'core contributors' because they are usually company employees, but if it's too complex to implement that let's just live with 'core contributors' here.)
* If they have an existing bulk transfer balance, that balance - also don't forget the "add funds" button for platform admins
* About info

This is related to #2062 - fiscal host orgs and sponsor orgs are fundamentally different things in many ways.

**Comment by Betree** [comment]
@raulgrafico That works for me. Please look at the rest of the feedback above (https://github.com/opencollective/opencollective/issues/2304#issuecomment-518598958), we still need:
- Host dashboard button
- Link to edit subscriptions (or alternative)

This is blocking because we can't break these features

**Comment by raulgrafico** [comment]
@alanna can you please help me writing a spec for each user profile page? Otherwise, we are going to keep having this back and forward, because I'm still not entirely familiar with those small differences. Right now what I've been doing is using the current cards and pages as reference, but those probably include scenarios that I have no idea, and perhaps I'm skipping parts that are not visible showing on the ones I'm using as a reference.

**Comment by alanna** [comment]
I think using the current pages as a reference is fine. You can look at any host page or sponsor org page to see the various functions it has. You can also look at the docs to see all the features associated with each type of entity on the platform.

I can help writing a spec if needed. Can you start a draft with what you have so far and send me the link @raulgrafico ?

**Comment by raulgrafico** [comment]
Sure @alanna it can be something like this:

Regular user (Just contributor, no  Core Contributor):
- Hero Image
- Profile Page
- Link to edit profile
- @tag username
- Short Description
- Social network links
- Total amount contributed
- Total amount raised
- **Collectives**
1. User will see a list of the collectives he has interacted with (Financial contributor and Events)
2. User can filter collectives using tabs
3. User can sort the collectives based on the following criteria
- **Transactions**
1. User will see a list of the transactions he has been part of
2. User can filter using tabs to show (All, Contributions, Expenses)
3. User is able to download a CSV with all the transactions
- About (The same WYSYWYG we are using inside the collective page)

That will be for all the kind of users with all the variations, so I don't skip anything important.

Thanks a lot Alanna :)

**Comment by raulgrafico** [comment]
@pia and @xdamman maybe you guys can help with this.

**Comment by alanna** [comment]
OK great  @raulgrafico  - please write that up for all the different types of users and pages that you have now, then I can check it and make sure it's complete. It's probably easier to do it in a document than here on Github.

**Comment by piamancini** [comment]
> But I don't see where create collective/org is related.

@Betree this is the view of the dropdown menu currently in the user profile. Where is this now in the new profile? 

<img width="1180" alt="Screen Shot 2019-08-19 at 2 05 16 PM" src="https://user-images.githubusercontent.com/3671070/63264083-80947880-c28a-11e9-92f4-e2041293e3fd.png">

> The example used here is FB Open Source, but in real life that Org does not have Collectives and it doesn't make sense.

@raulgrafico, @alanna is right here, you should use FB Open Source as is today. It is only a financial contributor. Why do you have the tab: collectives there? 
<img width="664" alt="Screen Shot 2019-08-19 at 2 08 24 PM" src="https://user-images.githubusercontent.com/3671070/63264228-dcf79800-c28a-11e9-8a7a-c3a99695f5c9.png">

> I think non-host Org profile pages should show:

Please just show what they do today. @raulgrafico go to opencollective.com/fbopensource for reference and replicate in the new design. No need to add anything at the moment.

**Comment by piamancini** [comment]
> please write that up for all the different types of users and pages that you have now, then I can check it and make sure it's complete. It's probably easier to do it in a document than here on Github.

Is this happening?

**Comment by Betree** [comment]
> > But I don't see where create collective/org is related.
> 
> @Betree this is the view of the dropdown menu currently in the user profile. Where is this now in the new profile?
> 
> <img alt="Screen Shot 2019-08-19 at 2 05 16 PM" width="1180" src="https://user-images.githubusercontent.com/3671070/63264083-80947880-c28a-11e9-92f4-e2041293e3fd.png">

From my understanding I don't think that we've planned to change this yet, the dropdown menu for the user profile is not in my Todo.

**Comment by piamancini** [comment]
>  From my understanding I don't think that we've planned to change this yet, the dropdown menu for the user profile is not in my Todo.

yes, that is correct. We corroborated that with design. Thanks Ben

**Comment by piamancini** [comment]
> The example used here is FB Open Source, but in real life that Org does not have Collectives and it doesn't make sense.

Actually, @alanna in this particular case they do (I had forgotten as well) But Facebook asked us to add the collectives in open collective that belong to their organization and we did. If you go to opencollective.com/fbopensource you'll see them: 

<img width="881" alt="Screen Shot 2019-08-19 at 6 01 59 PM" src="https://user-images.githubusercontent.com/3671070/63280656-7cc51e00-c2ab-11e9-8367-0860eaba5cde.png">

This is the same thing we do in opencollective.com/drupal-collectives or opencollective.com/meetups This is where the confusion is coming from, and @raulgrafico was right in adding them because that's what he was seeing. 

With regards to the host dashboard request, that button is only visible when you log in as an admin of the host, so design couldn't see it and that's why it was missing. I already shared my screen with them and walked them through it. They are working on adding that now to unblock @Betree.

**Comment by alanna** [comment]
What does it mean for an Organization to "have" Collectives, like with FB Open Source? Is this documented anywhere? I didn't know about that feature.

**Comment by piamancini** [comment]
It's the same thing we did for [Drupal Collectives](opencollective.com/drupal-collectives) or [Meetups](opencollective.com/meetups). It's a way to use tags to show all the collectives that are part of a certain ecosystem (language, or type of collective) even if they don't share a host.

In this case, Docusaurus and the react collective are OSS created inside the fbopensource github organization. They've been done as repos in that org. So when the collectives where created, we were asked if there was a way of expressing this inside open collective platform.

**Comment by piamancini** [comment]
For the record: the agreement on the drupal/meetup pages is to do this as temporary solution 
- Drupal: https://opencollective.com/discover?show=drupal
- Meetup: https://opencollective.com/discover?show=meetup
(with lazy loading)

And for facebook open source we are replicating what we have now 
"These collectives are part of our organization"

<img width="389" alt="Screen Shot 2019-08-21 at 9 38 30 AM" src="https://user-images.githubusercontent.com/3671070/63412220-8eb3d780-c3f7-11e9-9bc8-379f565c5178.png">

Which can also be used for the collective of the host 

<img width="385" alt="Screen Shot 2019-08-21 at 9 38 54 AM" src="https://user-images.githubusercontent.com/3671070/63412244-9a070300-c3f7-11e9-89ab-778df5a21c23.png">
