### ISSUE TITLE
Strangely delayed expense?

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#2307]
I got this email about a new expense. 
It came into my email August 4th : 

> ![image](https://user-images.githubusercontent.com/2665886/62532248-13e7aa00-b898-11e9-93bd-9880dfa82290.png)

**expense**: https://opencollective.com/secure-scuttlebutt-consortium/expenses/9382

when I approved the expense it looks like it was made ... a month ago (July 2):

> ![image](https://user-images.githubusercontent.com/2665886/62531921-80ae7480-b897-11e9-9300-7ff6714af80d.png)

---

**Questions**:
- is this a bug?
- did Luandro start making an expense but not push submit or something?

I'm pretty sure I've been watching these expenses .. yeah I have, because I approved the other large ones above this $150, $200 , and I would have seen this because I refresh the page (lack of trust!)

**Feeling** : I feel like someone did something wrong, or something is broken. A funny smell

---

cc @alanna this is the thing I was yelling at you about tonight

**Comment by flickz** [comment]
@mixmix This is not actually a bug when creating expense, you can select the date expense was due. Could be 2 months ago but you didn't submit immediately.
 
<img width="859" alt="Screenshot 2019-08-07 at 12 58 03 PM" src="https://user-images.githubusercontent.com/15707013/62621253-569a9800-b913-11e9-8bae-212282577359.png">

I think what we can do is to sort the expenses based on the time it was created instead of the date selected by the user.

**Comment by mixmix** [comment]
oh interesting, thank you!

**Comment by piamancini** [comment]
should we close this? Let's open a separate issue with your suggestion @flickz so we can look at it in the expense flow revamp.

**Comment by flickz** [comment]
Closing this in favour of https://github.com/opencollective/opencollective/issues/2351
