### ISSUE TITLE
Invalid platform fees when adding funds to Organization

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2311]
This is what I see when adding funds to an Organization:

<img width="617" alt="Screen Shot 2019-08-08 at 10 09 10 AM" src="https://user-images.githubusercontent.com/5498878/62661333-d7fe3300-b9c4-11e9-98fd-c937034117ce.png">

It says a 5% platform fee should be applied, but it's showing $0.00 deduction. 

I'm also unclear about what this means for when the Org admin sets up a contribution. In this example, they sent us these funds to do $500/mo for 6 months. Does the system automatically know some of the fees have been taken out and therefore they can still do it for $500, or do they need to actually reduce the amount so the balance can cover the total?

**Comment by Betree** [comment]
The 5% is hard-coded in the string, the real number here is `$0.00` and this is related to a recent change I've made. I need some clarification about this to fix properly, so is the following correct:
- There should not be any platform fees when host add funds to a collective
- There should be a 5% platform fee when adding funds to an organization

Also are the funds in the screenshot already added? We may need to update the transaction to add the platform fees.

**Comment by alanna** [comment]
Yes they are already added. This is the organization: https://opencollective.com/gusto

Can you clarify further how it's supposed to work? I still don't quite get it. So we charge the platform fee when we add the funds to the Org. Does that mean no further fee is added when the Org contributes to a Collective?

**Comment by Betree** [comment]
> Can you clarify further how it's supposed to work?

I don't know how it's supposed to work, my message above was unclear but basically what I was asking was: when should we charge platforms fees for adding funds?

**Comment by piamancini** [comment]
This is how it's suppose to work (as we have it today): 
Sponsor A sends us bulk payment 1000 we add that amount to their profile.
We add the total amount so it shows up complete. 
When Sponsor A makes a donation, we then take 5% platform fee (which we later invoice OSC for it) and 5% host fee. 
That's why it says "put aside". 

The idea was to show that the sponsors have $1000 and not 1000 - fees to spend. 

The alternative would be to treat bulk payment as any other transaction and add 900 to the prepaid card instead of 1000 and then the subsequent transactions using that prepaid budget don't have fees attached, since we already took them. This is a cleaner way of doing it - fees are taken the moment the money is deposited - but it's uglier for the sponsor. For example, they send 1000 in order to make two $500 donations but once we take the fees they only have $900 available which means in their profile and the collective's card it'll show as giving $450 to each collective instead of $500.

**Comment by piamancini** [comment]
PS: the $0.00 is the bug introduced by Ben, it should be the same amount 5% and 5% for both fees

**Comment by alanna** [comment]
Thanks for the clarification @piamancini. 

I think it's important when someone gives a $1000 bulk payment they get $1000 to spend in the system, because otherwise it's going to get very confusing. Sponsors think about this like "I want to give $a for b months, so I am sending a x b as the payment" and do not want to consider fees. I think it's fine to take the fees when they contribute to the Collective instead. 

@Betree I guess the only issue here is the bug with the 5% coming up as $0.

**Comment by Betree** [comment]
@piamancini Thanks for the explanation, it helps to understand but I'm still not 100% sure about the assumption I made above, is the following correct?

- There should not be any platform fees when host add funds to a collective
- There should be a 5% platform fee when adding funds to an organization

**Comment by piamancini** [comment]
> There should not be any platform fees when adding funds to a collective

When we add funds to a collective, Alanna and myself have the option of adding platform fees to that transaction. This happens because the hosts we manage (OSC, Foundation and EU) pay platform fees when adding funds. 

Other hosts don't need to pay platform fees and therefore there's no reason for them to see this option. 

I imagine this will change when @xdamman finalizes and deploys the new business model. But for the moment this is how it works. 

> There should be a 5% platform fee when adding funds to an organization

Yes, because when the sponsor uses those pre-paid funds to make a donation to a collective host and platform fees are deducted.

**Comment by alanna** [comment]
This issue appears to be still happening. It's saying fees will be removed when adding funds to an Organization. No fees should be taken at this point. Fees should be applied when they use their funds to contribute to a Collective. The net amount should be 100% of the amount added.

![Screen Shot 2019-11-04 at 12 18 22 PM](https://user-images.githubusercontent.com/5498878/68093754-da0d5a80-fefd-11e9-82e0-1abed459f71d.png)

**Comment by piamancini** [comment]
@alanna it doesn't say they'll be removed, it says to put aside from that amount. So the c6 receives amount in full, we are telling it to separate 5% because it'll have to pay it as platform fees in the future.

**Comment by alanna** [comment]
But we won't set aside 5% of that $8000 for platform fees. What will happen is that org will contribute to a Collective and we will set aside *that* 5% for platform fees. All fees are applied at the time the funds are used to contribute to a Collective. 

Telling us we need to set aside the funds here is misleading, because we'll also get a report that month saying to set aside the platform fees, meaning a double count of the same fees. If the org only spends $5000 that month on contributions, we only owe 5% of $5000 for platform fees, not 5% of $8000.

**Comment by Betree** [comment]
What is the decision for this issue? Should we rephrase this presentation?

**Comment by alanna** [comment]
My opinion is there should be *no fees* mentioned at all on this screen. But we should confirm with @piamancini.

**Comment by piamancini** [comment]
we agreed on this over the phone - It's not a huge issue, it root admins only. It's not a user facing feature at this stage.

**Comment by znarf** [comment]
The feature is gone. It's replaced by an automated Prepaid Payment Method creation or converting organizations to FUNDs. 

<img width="315" alt="Screenshot 2021-08-15 at 09 40 21" src="https://user-images.githubusercontent.com/806/129470945-4b950e2c-24e5-4c2f-a952-c6ffe236770a.png">
