### ISSUE TITLE
No new newsletter subscription since June 26th

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2327]
```sql
SELECT "createdAt" FROM "Users"
WHERE "newsletterOptIn" IS TRUE
ORDER BY "createdAt" DESC NULLS LAST LIMIT 5
```

![](https://d.pr/free/i/FhhAYn+)

Something that we deployed on June 26th broke the recording of people opting in to the newsletter.

**Comment by znarf** [comment]
newsletterOptIn had never been part of the new registration flow

<img width="860" alt="Capture d’écran 2019-08-13 à 21 33 59" src="https://user-images.githubusercontent.com/806/62971443-2e7acf80-be12-11e9-904c-33123d6ef7ad.png">

We were still getting registrations because the old registration flow was still displayed in some areas. This came to an end in https://github.com/opencollective/opencollective/issues/2119

**Comment by alanna** [comment]
Can we send everyone who signed up since that date one email asking them to subscribe to the newsletter if they want? I'm sad to think about all those lost subscribers.

**Comment by xdamman** [comment]
First, let's figure out how we can add back the opt in option to register to the newsletter.

I don't feel comfortable sending people an email to register to a newsletter. But maybe we can use the notification emails to ask them to register for it. Ideally, this should be at the host level and collective level. For example, XR also wanted to have people to register to their newsletter, not to the open source collective one. I'll create an issue for that.

**Comment by znarf** [comment]
Are we good with the follow up issues, can we close this one?

**Comment by alanna** [comment]
@znarf I would rather not close this issue because the other issue is for a whole complicated new feature and approach involving considering opt-ins for all different levels (hosts, collectives, etc). I doubt that can get prioritised soon. But I really want to get the basic problem here with platform-lelve opt-ins fixed ASAP.

My proposal: add a newsletter opt-in on the "account creation" screen (for individuals and organizations):

<img width="456" alt="Screen Shot 2019-09-18 at 10 24 27 AM" src="https://user-images.githubusercontent.com/5498878/65130856-89e64180-d9fe-11e9-944c-006ecbc49203.png">

How can we get this prioritised?

**Comment by znarf** [comment]
It's prioritized. Ideally, it should be a new "feature request" issue, explaining what the work should be. A newcomer should not have to look at the comments to understand what to do, the issue content should speak for itself.

**Comment by flickz** [comment]
@alanna I created a PR for this already and below is the screenshot, what do you think of the checkbox label text?

<img width="505" alt="Screenshot 2019-09-19 at 4 43 51 PM" src="https://user-images.githubusercontent.com/15707013/65262228-c9498680-db01-11e9-83f1-ce34cbf048fb.png">

**Comment by alanna** [comment]
Thanks Olu. Let's just say "Receive our monthly newsletter".

>
