### ISSUE TITLE
Offer to register to newsletter when becoming a financial contributor

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2329]
Since we moved to the new sign up flow (#2119), we don't offer anymore the option to sign up for the open source collective newsletter.

Other hosts / collectives would also love to be able to ask people to sign up for their newsletter (https://github.com/opencollective/opencollective/issues/2327#issuecomment-521139414)

We could think about it in two ways:

## Updates

We could use the "updates" feature and in the sign up flow, ask them if they would like to receive updates from the collective they are joining.

## External newsletter systems

Play friendly with the ecosystem and allow collectives to use other newsletter systems such as mailchimp.

@alanna would it be conceivable for you to use the Updates of the OSC collective to send the monthly newsletter? Would be great to eat our own dogfood. If not, we should figure out a way for any host to be able to use Mailchimp or other newsletter service. 
But ideally, all newsletters should be published on the collective page anyway.

In both cases, I think we should use the last screen of the contribution flow:
![](https://d.pr/free/i/aZQyyc+)

Maybe something like this (needs some design love) 
![](https://d.pr/free/i/fnvBLA+)

**Comment by alanna** [comment]
Well we have two use cases. First is at the level of a host, and I already raised this issue for it: #2314 - in this way we are similar to our users.

But we also have another use case, which is the platform newsletter. This is a different situation.

I'm a bit concerned about the layering of opt-ins here. If a new person signs up they could potentially be asked to opt in to the platform newsletter, Host newsletter, *and* Collective newsletter. 99% of users will not even understand the difference between all these.

To my mind, the recipients of the Host newsletter should be the core contributors of its Collectives. The recipients of Collective updates should be the contributors and followers of that Collective. If someone actually is both, they should get both Updates.

So I would propose this:

* We turn on Updates for Fiscal Hosts. We start dogfooding that for OSC updates and updates from our other Hosts.
* Core Contributors (admins and non admins) of Collectives in a host receive its updates.
* Updates for Collectives stays the same - financial contributors get them, plus soon anyone who signs up to receive them on a Collective's page.
* We request platform newsletter opt-in when anyone registers on Open Collective for the first time, regardless of what Host or Collective they are related to.

It's clear how that opt-in will work for the platform newsletter (checkbox on registration), but less clear for Collective and Host updates. Right now I think all contributors are automatically subscribed to Collective updates right? Maybe we need to ask them for explicit consent? When it comes to Core Contributors getting Host Updates, I don't think it can be optional because it's often things like updates to the terms, etc. Hosts have a legal relationship there and need to be able to communicate with their member Collectives.

I do not think it's worthwhile to invest in integrating with Mailchimp at this time, and instead we should focus on improving the Updates feature and helping Collectives get signups through their page. In and ideal world of course we'd offer the mailchimp or other service connection as an option but I don't see it as a big priority right now.

I also don't think we need to use Updates for the platform newsletter, because the platform has no entity on itself which can be the home of Updates as we have designed them. Unless we want to invest some sort of 'platform' type entity which is like a meta-host and only applies to Open Collective as a whole, it doesn't make sense. Again, not a priority right now IMO.

**Comment by piamancini** [comment]
Please let's create issues for this with people assigned to them if we want this to happen. thanks!

**Comment by heyakyra** [comment]
Might be nice to plug into SMS gateways for bulk text messages also

**Comment by alanna** [comment]
We now have Updates for Collectives and Hosts and we have the platform newsletter opt-in in the flow.
