### ISSUE TITLE
Troubleshooting guide for Github authentication flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2333]
We get a lot of support requests related to the Github authentication flow, and I struggle because I don't know how to help people troubleshoot. 

Would it be possible for @znarf or @xdamman or someone who understands how it works to give me the info here so we can write up a guide for the docs?

Here are the common issues people report:

* Repository missing from the list
* Showing personal repo's but they need an organisation's repo
* Repo not showing because it has less than 100 stars but they are confused about why it's missing
* Don't want to or can't grant unnecessary permissions
> The organisation I want to connect it to is fully open, however other orgs I'm a member of do not want to allow the required permissions, and indeed shouldn't have to because they are unrelated to the organization in question. I can't seem to only allow the permissions for the relevant org. Read and write has to be granted to all repos in all orgs that allow third party applications.

Currently whenever someone can't use the Github flow I just ask them to create the Collective and manually apply to OSC. But this is not great because it's sometimes difficult for me to verify they are a legit core contributor this way. It's possible someone could start a Collective for a repo they don't have rights to. So it's better if we can get the Github flow working for them.

**Comment by piamancini** [comment]
> Repository missing from the list

If you can't find your repo on the list check this: 

- does the repo you are looking for has +100 stars? 

- are you the owner of the repo with the profile you authenticated with? If the repo is under a different profile or an organization profile you won't see it here. You'll need to revoke access from your Github settings and re-authenticate with the right profile. If it's under and organization, make sure you give us access to your organizations (scroll down to see the check mark for it).

If you can't give us access to the organization who owns the repo, you won't see it in the list. Please contact support if this is the case. 

also useful for: 
> Showing personal repo's but they need an organisation's repo

> Don't want to or can't grant unnecessary permissions

We agree, the permissions are overly generous, we just need to read info. Unfortunately, there's not much we can do now since this is the only scope we can use to read the info we need. We've discusses this at length here: https://github.com/opencollective/opencollective/issues/355

If you have any suggestions on how to handle this better, feel free to send post on that issue, start a new one or send us an email support@opencollective.com

**Comment by Betree** [comment]
If you need to test the flow, the best way is to go to https://staging.opencollective.com/opensource/apply where you'll be able to add any repositories safely.

The only blocker that you may encounter is that you need to have access to a repository with 100+ stars (the usual limitation) to be able to add it. If that's a problem, we can easily disable this requirement for staging.

**Comment by contraexemplo** [comment]
@Betree Asking before I break anything: the only repositories with 100+ stars I have access to are from Open Collective's organization. Would that be a problem to test the flow? Or would you rather disable that requirement?

**Comment by Betree** [comment]
@contraexemplo Feel free to test with Open Collective repos, as long as it's on staging that's fine. One problem you may face is that other team members may already have done the same on staging, thus you may get an error like "this collective already exist". 

If you face this issue, just tell me and I'll prioritize the ability to disable the 100 stars requirement on staging.

**Comment by contraexemplo** [comment]
@Betree I can't go much further after picking a repository because I'm not an admin on eligible repositories or organizations. Will disabling that 100 stars requirement allow me to continue with any other repository I may have on my account?

**Comment by Betree** [comment]
@contraexemplo Yes. I'm going to put that on my TODO to unblock you

**Comment by contraexemplo** [comment]
@Betree Just to check: did you already disable the filter? Because I still can't find repositories with less than 100 stars on the list to apply. I tried to reconnect my GitHub account to see if anything would change but... that doesn't seem to do anything. It looks like it sends an API request but on my settings, it still shows "GitHub account contraexemplo connected on 8/29/19" (yesterday).

**Comment by Betree** [comment]
@contraexemplo Not yet but the PRs are ready (https://github.com/opencollective/opencollective-api/pull/2481 + https://github.com/opencollective/opencollective-frontend/pull/2441). I'll try to get this merged before the weekend

**Comment by contraexemplo** [comment]
Okay! Thank you @Betree

**Comment by Betree** [comment]
@contraexemplo Sorry I haven't been able to merge in time, will be done today

**Comment by contraexemplo** [comment]
@Betree No worries!

**Comment by Betree** [comment]
@contraexemplo It's merged, https://staging.opencollective.com/opensource/apply should now display all your repos

**Comment by contraexemplo** [comment]
@Betree Aaaand it's working! Thank you!

**Comment by contraexemplo** [comment]
@Betree What's the recommended procedure to change which GitHub account is connected to your profile on Open Collective? Revoking access from GitHub?

**Comment by Betree** [comment]
@contraexemplo Sorry for the late reply! I would indeed revoke access from GitHub yes.

**Comment by contraexemplo** [comment]
@Betree I'm revisiting this issue this week and I have a question: when I go through the authorization process on GitHub, our organization (`opencollective`) is followed by a green tick ("This organization allows the application to access organization data as described in the permissions above."). Is this related to the way an organization on GitHub manages their third-party application access policy or is this something else?

Additionally, with the organization I created just to test those functionalities, my policy is access restricted; I have to click on `Grant` to authorize the access. On another organization, I have to click `Request` (because of my [role in the organization](https://help.github.com/en/github/getting-started-with-github/access-permissions-on-github#organization-accounts), I imagine?).

**Comment by Betree** [comment]
> when I go through the authorization process on GitHub, our organization (opencollective) is followed by a green tick ("This organization allows the application to access organization data as described in the permissions above."). Is this related to the way an organization on GitHub manages their third-party application access policy or is this something else?

Yes it is. We already granted the permissions to the Open Collective Github app for our organization, that's why there's a green tick.

> Additionally, with the organization I created just to test those functionalities, my policy is access restricted; I have to click on Grant to authorize the access. On another organization, I have to click Request (because of my role in the organization, I imagine?).

Seems correct.

**Comment by contraexemplo** [comment]
Great, thanks!

**Comment by contraexemplo** [comment]
Finished with @alanna's help, published here: https://docs.opencollective.com/help/collectives/osc-verification

**Comment by Betree** [comment]
@contraexemplo looking great!
