### ISSUE TITLE
Explicit the fact that gift cards cannot be used with incognito

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2365]
As reported by a user in https://opencollective.freshdesk.com/a/tickets/1211

We should make it clear that gift cards cannot be used with incognito profiles.

**Proposed solution**

- Add a message on the `redeemed` page to explain users that they can't use their gift card with an incognito profile.
- Add a FAQ at the payment step if using incognito while there's a gift card stored for user

    **Title** 
    > Why can't I see my gift card?

    **Description**
    > Unfortunately, gifts cards cannot be used with incognito profiles. Allowing this could allow malicious users to find out what your main profile is. The protection of your personal information is too important for us to take this risk!

**Comment by Betree** [comment]
This happened again https://opencollective.freshdesk.com/a/tickets/1671

**Comment by JohnTitor** [comment]
@Betree I'd like to work on this, the FAQ to edit is this? https://github.com/opencollective/documentation/blob/master/backers-and-sponsors/README.md

**Comment by Betree** [comment]
@JohnTitor The FAQ is to be added for the payment step in the contribution flow, in a similar fashion to what we do for the details step: https://github.com/opencollective/opencollective-frontend/blob/6a807bb7e2be3c215694ccdd74f8e7cca9b7f3db/components/contribution-flow/index.js#L746

**Comment by Betree** [comment]
Issue resolved by @JohnTitor :taco: :tada:

**Comment by znarf** [comment]
🏆 This issue was completed by @JohnTitor as part as our first Hackathon (it started at at the event but was finished after). 

I retroactively added a $200 bounty on it. To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
