### ISSUE TITLE
Project: Create collective flow (design)

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2366]
New flow to create a collective to embrace the new business model discussed in #2251.

This closes #2331 #2295 #2251

## Links

- [Google Drive](https://drive.google.com/drive/folders/1tEnq1BqrzbnPymYRPFRzU00l9mPUWqIj?usp=sharing)
- [Specs](https://docs.google.com/document/d/1UUdmxjWmPLYahPg1jjKllwNS2wlXclZzq9T4ihAp2YQ/edit?usp=sharing)

## Design

- Latest design file: https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-04-Collectives-%E2%86%92-Create-Edit?node-id=7762%3A42619
Production ready: No

## Next steps:

- Work on the [specifications](https://docs.google.com/document/d/1UUdmxjWmPLYahPg1jjKllwNS2wlXclZzq9T4ihAp2YQ/edit?usp=sharing) to make sure we don't forget anything big
- @opencollective/design  to work on wireframes (with me)
- Call with the team to discuss the first wireframes once ready to share
- Second iteration on wireframes
- Call to approve the wireframes
- Design the different screens
- Implementation
- Design fix ups based on implementation feedback
- Staging
- Last checks and fixes
- Production

**Comment by alanna** [comment]
Sorry unpinned by mistake

**Comment by znarf** [comment]
What is our policy for "pinned" issues? Why pinning this one over the 374 others? ping @Memo-Es

**Comment by alanna** [comment]
@xdamman finally got a chance to watch the Friday video where you cover this.

* Create new fiscal host is redundant to selecting 'our organization' as bank account owner in the previous screen. It should assume that if you click 'fiscal sponsor' instead of 'our organization' that means you're not creating a new host.
* I'm still confused about what's going to happen to open source Collectives who don't want to join OSC (want to self-host or join OC EU etc) - what will their path be, because they will likely click "open source" on that first screen. Maybe add an option on the 'apply to OSC' screen next to "github" and "manual verification" that says "use another host or start your own", which sends you back to the other flow?

**Comment by xdamman** [comment]
1. It's redundant but it's ok because it's a very different user story. It's one thing to use your organization as a fiscal host for your collective, it's an entirely different ballgame to become a fiscal host for others (need to define formal policies, terms of service, application process, pricing strategy, ...)
2. There is a already a "request manual verification" button below the "Verify using Github stars" one 
![](https://d.pr/free/i/mPxt9H+)
If they pick manual process, they can apply to OSC or to any other host (or use their own) like any other new collective.

**Comment by Memo-Es** [comment]
### Wireframes update

In a call with @alanna we talked about making ridiculously easy to create a collective so we discussed a 1-step-version and a contact extra step. (after choosing open source vs any other initiative)
Next, are the results and the comments.

Create Collective | Contact
------------ | -------------
![Create collective](https://user-images.githubusercontent.com/49539954/70197032-35369680-16d0-11ea-9c2c-7e0d51e16c07.jpg) | ![Contact](https://user-images.githubusercontent.com/49539954/70197036-3798f080-16d0-11ea-805a-5e8d5c982d06.jpg)

> @alanna 
First screen is much better! For “what does your Collective do” that’s the short description, right? We should just make sure it’s character limited to match the short description field.
The second screen looks ok, but do we really need it as part of the setup process? Can’t they add that info later if they want? The basic contact from is already built in and 99% of Collectives will just stick with that anyway.
I think we should be making this setup flow as simple as possible and focus on guiding creators to add to their Collective once they reach their actual page.

Any thoughts? @xdamman @piamancini

**Comment by alanna** [comment]
Here's my opinion: 

One major goal of the Collective onboarding redesign is to reduce barriers to new Collectives getting on board.

A big way we're achieving that is to make the initial setup super simple, then focusing on encouraging core contributors to build out their Collective based on their priorities, once their basic page is set up. If that's about financial contributions, they'll set that up. If it's about adding team members and creating updates, they'll do that. Different Collectives will have different focuses and that's OK.

So I think we should make the initial setup super simple and take out everything that's not absolutely necessary, really strip it down. I think what's on this single screen is enough:

![Screen Shot 2019-12-05 at 3 52 30 PM](https://user-images.githubusercontent.com/5498878/70199724-4b4b6200-1777-11ea-939d-3bec35cbaa5f.png)

Then, we can really invest in the experience of new users once they reach their new Collective page, having really good action buttons for all the ways they can build up and enhance their Collective from there. I think this will be a much improved onboarding process and help guide people to the areas that are most important for their communities.

**Comment by alanna** [comment]
Just to clarify, I still think we need the "open source" or "other initiative" screen before this, so we can have a good experience for the large number of Collectives who are coming to us looking to join Open Source Collective. The designs already shared above for that flow are great. I hope this is a temporary state, and in the future we have many other communities just as large as Open Source, but for now we should make sure it's an easy flow for them.

**Comment by Betree** [comment]
100% agree with @alanna on this one. I think asking for contact details here is a distraction.

The smart default of having a contact form will probably fit most collectives, at least at the begining. We should make it easy to change.

**Comment by piamancini** [comment]
I agree - having to think about what's their preferred contact details at the beginning can make them have to go back to their communities to figure this out, therefore distracting them from starting a collective. This doesn't seem essential at this point in the flow.

**Comment by Memo-Es** [comment]
### Update

This is the version presented in today's demo, it features a 1-step collective creation with special attention on the collective values (See values modal). And the start of the onboarding inside the collective page.

Link to the [prototype](https://www.figma.com/proto/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-04-Collectives-%E2%86%92-Create-Edit?node-id=7646%3A864&viewport=3904%2C6687%2C0.3822273910045624&scaling=scale-down)
@xdamman @alanna @piamancini 

Sign in → | Type of collective → | Create collective → | Values modal → | Onboarding 1 → | Onboarding 2 → | Onboarding 3 →
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
![1 Sign in](https://user-images.githubusercontent.com/49539954/70348170-c409f700-1827-11ea-99c2-ce0e07b373d9.png) | ![2 Type of collective](https://user-images.githubusercontent.com/49539954/70348171-c409f700-1827-11ea-8c3e-f2169191e989.png) | ![5  Create collective](https://user-images.githubusercontent.com/49539954/70348174-c409f700-1827-11ea-8619-6c67db0de9ba.png) | ![6 Values modal](https://user-images.githubusercontent.com/49539954/70348175-c409f700-1827-11ea-9ad9-b08d03073a87.png) | ![Onboarding 1](https://user-images.githubusercontent.com/49539954/70348830-23b4d200-1829-11ea-8ab2-3056e286d4f8.png) | ![Onboarding 2](https://user-images.githubusercontent.com/49539954/70348829-23b4d200-1829-11ea-94c2-8f5a76a406e0.png) | ![Onboarding 3](https://user-images.githubusercontent.com/49539954/70348828-23b4d200-1829-11ea-8fa7-5de09b862b62.png) |

**Comment by piamancini** [comment]
I think this is very well resolved @Memo-Es . It allows for @xdamman's request to have the contact form details in the flow, without blocking it with them.

**Comment by alanna** [comment]
Looks good!

**Comment by xdamman** [comment]
Looks good. 

However, there is a confusion in the last step “choose the way people can contact Agora”. Social media accounts are not ways to contact the collective, they are primarily ways to receive updates.

What was wrong with the wireframe of Karim for that particular step? I understand there was a confusion between the concept of recipient and core contributor (since we don’t distinguish yet between the two), but adding a step “add core contributors” before seems to solve that, no?

I also really think that we don’t understand each other in those conversations. The experience of the team is mostly with open source communities. When was the last time that you started or joined a non open source collective? What was your experience? From my experience, one of the very first steps they do is create a gmail address (or protonmail) so that they can be contacted. They absolutely need an email address.

I understand that today most collectives on opencollective.com are open source and those don’t need (and probably don’t even want) yet another way to be contacted. So maybe we can skip that step for open source collectives?

Another way to solve this issue is to put this feature out of the open collective core and ask hosts of non open source collective to finance the development of such feature. This would mean that we need to think more in terms of enabling hosts to customize the experience.

**Comment by alanna** [comment]
> From my experience, one of the very first steps they do is create a gmail address (or protonmail) so that they can be contacted. They absolutely need an email address.

We already have contact functionality built in. There's a nice button and form. Users will not have a problem contacting a Collective even if they don't add extra contact info. The screen in the flow here gives them many options for adding more ways to communicate if they want.

**Comment by xdamman** [comment]
That's definitely not the best for non open source collectives. It would go a very long way for them to be able to share in other places (posters, flyers, emails, ...) an actual email address. But let's move on. We will make this part of another project lead by non open source hosts.

> I hope this is a temporary state, and in the future we have many other communities just as large as Open Source, but for now we should make sure it's an easy flow for them.

Same. But there is a chicken and egg here. In order to make other types big we need to make a statement and drive attention to them. So I'd love to see a third option on the selection of type of collective:
- For Open Source Projects
- For Local Groups of #ClimateJustice Movements
- For all other initiatives (maybe this one can just be a link below in the same style as "skip")

In the same way that there is a special flow for open source projects, there could eventually be a special flow for #ClimateJustice movements (not now though).

> A big way we're achieving that is to make the initial setup super simple, then focusing on encouraging core contributors to build out their Collective based on their priorities, once their basic page is set up. If that's about financial contributions, they'll set that up. If it's about adding team members and creating updates, they'll do that. Different Collectives will have different focuses and that's OK.

I agree with that. So instead of having an onboarding like this

step 1 | step 2 | step 3
------ | ------ | -------
![](https://user-images.githubusercontent.com/49539954/70348830-23b4d200-1829-11ea-8ab2-3056e286d4f8.png) | ![](https://user-images.githubusercontent.com/49539954/70348829-23b4d200-1829-11ea-94c2-8f5a76a406e0.png) | ![](https://user-images.githubusercontent.com/49539954/70348828-23b4d200-1829-11ea-8fa7-5de09b862b62.png)

Why not simply have good calls to action within the page where sections are empty at first?
Maybe also add a place with check marks showing a list of TODOs (not as a modal that can be quickly dismissed then people don't know how to ever get back to it)
- [x] Add a logo
- [ ] Add a fiscal host
- [ ] Edit tiers

This is also a good opportunity to improve how people can get to `/edit` (the gear on the avatar is not obvious).

**Comment by piamancini** [comment]
> Why not simply have good calls to action within the page where sections are empty at first?
> Maybe also add a place with check marks showing a list of TODOs (not as a modal that can be quickly dismissed then people don't know how to ever get back to it)

I think this design achieves that without getting in the way of users. We want them to add contributors but we want them to be able to skip it as well. It's like when you set up a phone, you can go through all the steps of click skip and finish later. 

At this stage, we would like to start implementing instead of going back to the drawing board. I don't think the current design is going to be substantially better by adding CTAs - which by the way, you see already when you are logged in as an admin. Sure they, can be improved, but the goal of making it very easy for collectives to start is achieved here. 

If you don't think the contact is important now, we can remove that step. I don't quite follow what you want to say above in relation to that. 

I am ok with the idea of adding open source, climate change and others. Where would you take the climate change ones to? How different is is from the others path?

**Comment by alanna** [comment]
Personally I don't think we need more complexity at this point, and I don't see the necessity of adding more options to the initial "open source or other" selection screen. The only reason we have that branching option is because we have a completely seperate technical implementation of the onboarding process for open source projects, i.e. the Github verification flow. There's no need for a separation for other categories unless they have a similar specialised flow.

I look forward to a time when there are many verticals who create their own unique onboard flows and it's no longer up to Open Collective to build and design them, but we're not there yet. The goal now is to make onboarding as easy and simple as possible, while not damaging the existing open source onboarding process. I think the design where it is now achieves this, and we should move forward. Otherwise we are delaying what will be a big improvement for our user experience and letting the perfect be the enemy of the good.

**Comment by xdamman** [comment]
Here are my comments based on latest renderings from @Memo-Es 

![](https://d.pr/free/i/JQadmO+)

![](https://d.pr/free/i/abHRPa+)

![](https://d.pr/free/i/UtHKth+)

![](https://d.pr/free/i/Iw0Y4M+)

![](https://d.pr/free/i/LaYNK4+)

![](https://d.pr/free/i/1plOz9+)

![](https://d.pr/free/i/xcKZVa+)

**Comment by Memo-Es** [comment]
@xdamman Could you elaborate a little bit more on this one?

![68747470733a2f2f642e70722f667265652f692f49773059344d2b](https://user-images.githubusercontent.com/49539954/72037223-fc578780-3262-11ea-80f2-980ce93373f8.jpeg)

I made the prototype private because we are working on it right now, also tomorrow will share a google doc for copy editing

**Comment by xdamman** [comment]
That screen is about “Contact” as the top of the modal suggests.

Twitter is before all a tool to communicate and follow updates. So that’s not the right place to ask for their twitter account. It should be asked along with their website url, facebook page, etc. (Btw, most collectives don’t have a twitter account, most however do have a facebook one)

So, when it comes to contact the collective, open source collectives will most likely opt to redirect people to write an issue on their repo, e.g. https://github.com/opencollective/opencollective/issues 
All other collectives, either already have created a generic email address, have a website with a contact form or, most likely scenario, they don’t have anything yet and they would love to have an easy way to contact them privately. Others, would rather avoid having people to contact privately and force people to use the conversations feature to reach out to them.

So that’s the purpose of that step in that modal.

**Comment by Betree** [comment]
Let's also add the contact form in the design, `hello@` email is not ready to be shared publicly yet but we have a contact form already developed.

**Comment by xdamman** [comment]
This screen is only showed to the creator of the collective so I’d definitely share the info@ email there. We don’t have (yet) to communicate it publicly on the collective page, we can keep that for another issue. But at least they would know that they can communicate on their own channels that email address.

Yes, maybe this modal can be larger and show more explicitly a small version of the contact form and asking, with examples, what they prefer (send those messages to an existing email address of your choice, to one we create for you info@, or, and this need probably an updated design, to an external url such as github issues or a facebook page)

**Comment by Betree** [comment]
> But at least they would know that they can communicate on their own channels that email address.

The issue still stands if they share it by other means (social networks, their website...). We shouldn't encourage the public use of this address while the spam issue hasn't been properly investigated.

**Comment by xdamman** [comment]
Huh. We need to fix that. Is there an issue for it yet? (Couldn’t find any with a quick search on “email”) Should we consider putting a bounty on it and reach out to people with experience with such topics?

In the meantime, can you live with it? I’m part of a gazillion of collectives and spam issues has never been an issue for me so far. If not, we can omit it and just say “message will be sent to all core contributors”. But that doesn’t make me happy ;-) 

(Also given that through this interface one clearly won’t be able to assume anymore that there is an info@ for every collective, mass spamming potential is reduced)

**Comment by Betree** [comment]
The problem is not about admins getting spammed, it's about email providers (Google) flagging our server as sending spam. We rely too much on emails (signup/SignIn) to take the risk of letting that happen. Without saying, sending spam is against Heroku's TOS and we don't want them to take action against our servers neither. So it's not just a preference, it's a real blocker.

I should have created an issue for it at the time, I'll do that tomorrow to ensure that we take action. Because of its nature it will be hard to outsource this issue, but some expertise with Mailgun and the email protocol would be really helpful. A first step would be to contact Mailgun, they probably have some answers to this.

**Comment by Memo-Es** [comment]
A couple of issues that were left pending in Friday's demo:

1.  The Open Collective way
Right now, we are displaying three central values that conform to the Open Collective way: Your data is yours, safe space, and transparency.
<img width="1440" alt="Create collective" src="https://user-images.githubusercontent.com/49539954/72232517-37b9c500-3587-11ea-8493-59bd929f5b93.png">
@alanna and I discussed this issue, and she thinks that if such representation of values ends up in the final design, it should be something more aligned to what we have here: https://docs.opencollective.com/help/about/values


2.  Where can people find (Collective)?
After the last round of feedback with both @xdamman and @alanna, I worked on this option:
![Onboarding - Where can people find Collective](https://user-images.githubusercontent.com/49539954/72232870-84060480-3589-11ea-9df3-c6bdc9fb43e3.png)


- Do you have a website? 
This is one of the most critical touchpoints for fiscal hosts to choose whether if they host a collective or not. Besides is the most common referring point of the general community.

- Turn on conversations in your collective
We introduce the conversations feature to the new collective creator, after the onboarding they can go and start creating conversations/updates.

- Connect your social platforms
The fields here directly feed the following contact buttons in today's collective page:
<img width="2616" alt="Annotation on 2020-01-12 at 22-17-29" src="https://user-images.githubusercontent.com/49539954/72232857-6173eb80-3589-11ea-897b-2e7d07e152e6.png">


We removed the @opencollective address option due to the spam issue.

Any thoughts? @piamancini @Betree

**Comment by piamancini** [comment]
LGTM thank you @Memo-Es

**Comment by Betree** [comment]
LGTM too. Let's acknowledge that the contact address is meant to be re-added as soon as we resolve the SPAM issue.

**Comment by xdamman** [comment]
As discussed in the weekly design call, let's remove the switch to activate conversations as they will be activated by default.
Let's also replace the github field with a facebook one for non open source projects (we can tell by their tag if they picked something else than open source on the first screen)
![](https://d.pr/free/i/abHRPa+)

(can we have an illustration for that?)

**Comment by Betree** [comment]
@xdamman Actually there was already an issue for the SPAM problem, it was just not public: https://github.com/opencollectiveinc/opencollective-security/issues/28

**Comment by piamancini** [comment]
@Memo-Es please don't block this on the climate illustration - put a placeholder please when this is ready for us to start production so we can move faster. Illustrations are taking quite a while. Thanks!

**Comment by Memo-Es** [comment]
The document for copy editing is online @alanna can you help me check it?
https://docs.google.com/document/d/1_ScKV5EKtlO-hkEuXln6fgAStWxAbV6pD1PqLaSrTPE/edit?usp=sharing

I will upload the updated prototype once Cuiki finish giving maintenance to some buttons in the design system we are using inside the flow

**Comment by alanna** [comment]
I made a bunch of changes and comments on the Google doc.

**Comment by Memo-Es** [comment]
### Illustrations for the Create Collective Page sections
Any feedback? @piamancini

Contribute | Updates | Conversations | Budget | Events | About 
------ | ------ | ------- | ------- | ------- | -------
<img width="314" alt="Screen Shot on 2020-02-24 at 08-47-48" src="https://user-images.githubusercontent.com/49539954/75164391-6084bc80-56e6-11ea-85be-95901c8ce0e3.png"> | <img width="303" alt="Screen Shot on 2020-02-24 at 08-50-12" src="https://user-images.githubusercontent.com/49539954/75164675-c2452680-56e6-11ea-9cf3-eb24b78152a0.png"> | <img width="300" alt="Screen Shot on 2020-02-24 at 08-51-07" src="https://user-images.githubusercontent.com/49539954/75164706-cc672500-56e6-11ea-8640-9925cf672f2e.png"> | <img width="312" alt="Screen Shot on 2020-02-24 at 08-51-21" src="https://user-images.githubusercontent.com/49539954/75164760-e0ab2200-56e6-11ea-9f69-4ed07d0093ce.png"> | <img width="306" alt="Screen Shot on 2020-02-24 at 08-51-32" src="https://user-images.githubusercontent.com/49539954/75164841-01737780-56e7-11ea-8d21-682c16dcb2fc.png"> | <img width="293" alt="Screen Shot on 2020-02-24 at 08-51-43" src="https://user-images.githubusercontent.com/49539954/75164902-1ea84600-56e7-11ea-83e3-8e8a16c8110f.png"> | <img width="590" alt="Screen Shot on 2020-02-24 at 08-55-38" src="https://user-images.githubusercontent.com/49539954/75164918-25cf5400-56e7-11ea-83fc-5644d06935d3.png">

**Comment by piamancini** [comment]
all good to go @Memo-Es -
