### ISSUE TITLE
send email to contributors?

### ISSUE THREAD

**Issue by sebsheep** [opencollective/opencollective#2371]
Hello,

Will the button "send email" above the list of participants of an event send an email to all the participants? 

Some of my participants are "incognito", will the be reached by the email?
![image](https://user-images.githubusercontent.com/6839698/63749692-43447200-c8ac-11e9-9c38-b082ec71f0c9.png)

I'm confused because the "send email" button is just a "mailto:[event-name]@[collective-name].opencollective.com" which is easily guessable....

**Comment by xdamman** [comment]
Sending an email to that address sends a confirmation email to the admins of the event (to avoid spam). Once confirmed, the email will be sent to all participants. 

I’ve heard that there is an issue when exporting the list of participants for incognito users. @Betree can you look into that?
Also, I don’t think we should allow people to register as incognito to events (tiers of type “ticket”).

**Comment by znarf** [comment]
@xdamman if there is an issue please document it properly first so we can have a look at it. cc @Betree

**Comment by piamancini** [comment]
> Also, I don’t think we should allow people to register as incognito to events (tiers of type “ticket”).

This should be a separate ticket @xdamman

**Comment by Betree** [comment]
@znarf I'm aware of the issue mentioned by @xdamman (it was reported in a ticket I'm assigned to). When users click on `Export CSV`, the file is missing the emails for all incognito users.

**Comment by Betree** [comment]
Hi @sebsheep,

The incognito feature was introduced recently and we missed the fact that event's organizers would need access to users details. I can confirm that **if you try to reach the participants via the "Send Email" feature, incognito users won't receive it**.

With https://github.com/opencollective/opencollective-frontend/pull/2435 we're going to prevent users for contributing "incognito" when they order tickets in the future. In the mean time, can you contact `support@opencollective.com` (please mention my name to assign me directly) so that we can export the list of emails for these incognito profiles for you?

**Comment by alanna** [comment]
@contraexemplo to add to docs ^

**Comment by Betree** [comment]
Issue solved in support ticket https://opencollective.freshdesk.com/a/tickets/1412
