### ISSUE TITLE
Update react-dropzone to latest version

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2408]
We have a policy to try to use the latest version of our dependencies in all repositories.

In the Frontend, we're currently using the version 5 of `react-dropzone` and the upgrade to version 6 has breaking changes. The latest version is now 10.

We want to:

  - upgrade the package: `react-dropzone`
  - ~~upgrade related dependencies: `react-dnd`  and `react-dnd-html5-backend`~~
  - adapt the code where it's used
  - make sure the tests are passing

**Edit**: `react-dnd`  and `react-dnd-html5-backend` are not related with `react-dropzone` but `react-tag-input` so should not be touched https://github.com/opencollective/opencollective-frontend/commit/afd137a75d7f9bd1f394046ca49d90b951582c30

**Comment by NotJohs** [comment]
@znarf Will look into this

**Comment by nonsodaniel** [comment]
Hi, I'd like to jump on this

**Comment by NotJohs** [comment]
@nonsodaniel already on this.

**Comment by Betree** [comment]
:trophy: This issue is now completed by @NotJohs in https://github.com/opencollective/opencollective-frontend/pull/2506

To claim the **$300** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
