### ISSUE TITLE
Remove Why Join & move video & image to description

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#242]
- [ ] Remove Why Join?
- [ ] Move video/image into `description` section

**Comment by asood123** [comment]
@carlosascari Can you help here? We want to remove whyJoin section and move image or video below Description?

**Comment by carlosascari** [comment]
@asood123 
Sure, let me just confirm. This issue is to

1. Remove the `whyJoin` section on the `PublicGroup` container, entirely.
2. Move the `video` or `image`, that is currently in the `whyJoin` section, up and below the `description` section, which is right above the `website` & `longDescription` sections

![Placement](https://my.mixtape.moe/drkepu.png)

**Comment by asood123** [comment]
Not needed for now.
