### ISSUE TITLE
New Collective Page V2: Contributors with Financial Contributor Tag have no Amount

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2438]
On https://opencollective.com/sustainoss/v2 two contributors to the event don't have the total amount donated. 
I think it's because they had a free ticket so there's no transaction - or maybe the way we added them as members was creating a $0 transaction. 
We should remove the tag if there's no actual donation and maybe add event attendee? 
<img width="361" alt="Screen Shot 2019-09-20 at 9 32 45 AM" src="https://user-images.githubusercontent.com/3671070/65308238-e9bd2380-db89-11e9-8602-37a6a4f45dd4.png">

**Comment by Betree** [comment]
There's indeed a condition to not show the amount if it's 0. This not new, but the new collective page does makes it really obvious. On the old collective page:

![image](https://user-images.githubusercontent.com/1556356/65308558-9a2b2780-db8a-11e9-8399-27044f1158cc.png)

Showing `Event attendee` may not be the most adapted solution, because in this specific case we don't know if the collective is an event or not. The same can happen with collectives that have a free tier so their member can register.

My proposal would be to replace `FINANCIAL CONTRIBUTOR` by `CONTRIBUTOR` on the tag if the amount contributed is `0`.

**Comment by Betree** [comment]
Resolved by @jeffin143 in https://github.com/opencollective/opencollective-frontend/pull/2832
