### ISSUE TITLE
NCP: wrong currency in contributors section

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2444]
It’s the right currency in the leaderboard and in the latest transactions but not in the list of contributors of the collective:

![](https://d.pr/free/i/xiVhbp+)

(Much less important but there is also a CSS issue with the background being clipped)

**Comment by Betree** [comment]
@xdamman is this Brave browser?

**Comment by xdamman** [comment]
Safari on iPad iOS 13

**Comment by jzabala** [comment]
Hi, I would like to give this one a try. 

I already have the app running locally connected to staging. Is there a test user with data that I can use to check the bug?

**Comment by Betree** [comment]
Hi @jzabala, you can open http://localhost:3000/xr-belgium/v2

This should be 477€:

![image](https://user-images.githubusercontent.com/1556356/65506882-ecdb4b00-decc-11e9-9f36-8b6f3db8e9c4.png)

The currency is available in `collective.currency`, somehow it is not passed or considered to/in `StyledMembershipCard`.

**Comment by Betree** [comment]
(and thanks for jumping in :slightly_smiling_face:!)

**Comment by jzabala** [comment]
Hi @Betree, thank you very much for you help. I found this issue was not in the `StyledMembershipCard` but in the `Contributors` section.

But I think in the parts of the app where `StyledMembershipCard` is used there must be an issue too since _USD_ is hardcoded in it: https://github.com/opencollective/opencollective-frontend/blob/68b6b55bfd6f7d60a3d4cc49900fb0ae9e4861c3/components/StyledMembershipCard.js#L80
It looks like this was a limitation of an older version of `formatCurrency`.

**Comment by Betree** [comment]
Good catch! The comment I added there is actually wrong:

> Ideally we should breakdown amounts donated per currency, but for now API only returns the total amount in USD.

Should be:

> Ideally we should breakdown amounts donated per currency, but for now API only returns the total amount **in collective's currency**.

It should be safe to implement the following code in there:

```es6
formatCurrency(stats.totalDonations, collective.currency || 'USD', { precision: 0 })}
```

**However**, my first comment was also misleading because the component in screenshot above is `ContributorCard` - not `StyledMembershipCard`. Sorry about that!

**Comment by jzabala** [comment]
> Should be:
> 
> > Ideally we should breakdown amounts donated per currency, but for now API only returns the total amount **in collective's currency**.
> 
> It should be safe to implement the following code in there:
> 
> ```js
> formatCurrency(stats.totalDonations, collective.currency || 'USD', { precision: 0 })}
> ```
**Done**

> **However**, my first comment was also misleading because the component in screenshot above is `ContributorCard` - not `StyledMembershipCard`. Sorry about that!

Don't worry. I really appreciate your help :D

**Comment by znarf** [comment]
🏆 This issue was completed by @jzabala

I retroactively added a $100 bounty on it. To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by jzabala** [comment]
Thank you very much @znarf. I'll use the bounty to support an Open Source project. Let me read the instruction on how to create an invoice and come back to you with any question.

Thanks again. It is greatly appreciated 😁

**Comment by znarf** [comment]
@jzabala if you want to support one or multiple Open Collectives, no invoice needed. We will just give you a gift card.

**Comment by jzabala** [comment]
Awesome. Let me know what I need to do @znarf.

**Comment by znarf** [comment]
Sent by email.
