### ISSUE TITLE
Homepage: refunds should not be displayed

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2458]
On the homepage, we display refunds as regular transactions. The result is pretty strange (see screenshot below).

**Expected**
Latest transactions list on the homepage should not list refunds.

![image](https://user-images.githubusercontent.com/1556356/65781171-71d39800-e14b-11e9-809f-01b8f13f186b.png)

**Comment by jeffin143** [comment]
@Betree , I am not sure, whether we need to handle this at `api` side or not, I came up with a solution, Don't know how correct it is, so what my approach is

Replace 

 https://github.com/opencollective/opencollective-frontend/blob/1094ced9ad45b2b992d562022989fab9ea2cbe6b/pages/index.js#L237-L242 

the above lines of  code with 

```
    const filteredTransactions = transactions.filter(({ type, order, category, fromCollective, collective, isRefund }) => {
      // Ignore corrupt entries (should not happen)
      if (!fromCollective || !collective) {
        return false;
      }
      // Should not show refund
      if (isRefund)
        return false;
```
The output will be 

Everything will be shown since nothing is a refund 

![Screenshot from 2019-10-23 00-42-50](https://user-images.githubusercontent.com/21286134/67322490-b544da80-f52e-11e9-8047-8658a17434f3.png)

So to test my code, instead of not showing the refund types , I only showed the refund types , what i mean is

```
    // Only show refund transactions 
      if (!isRefund)
        return false;
```

output will be blank, since nothing is refund
![Screenshot from 2019-10-23 00-42-37](https://user-images.githubusercontent.com/21286134/67322622-ef15e100-f52e-11e9-80b2-1a9a591bd11a.png)

**Comment by Betree** [comment]
@jeffin143 Thanks for investigating that! Your approach is correct. I'd say the ideal solution would be to add a `includeRefunds` flag on the `transactions` endpoint (https://github.com/opencollective/opencollective-api/blob/1bac9485fd2b61e2cc6292d57517cf21fe5d2d34/server/graphql/v1/queries.js#L426) to not fetch them at all. Let's say that we refund 15 translations in one go, the section will be empty on the homepage and we prefer to avoid that.

Feel free to jump on it if you find this issue interesting, but keep in mind that this page is going to be revamped in the next few months. Because of that we tend to give less priority to issues about homepage :wink:

**Comment by jeffin143** [comment]
Sure, I will take a look , But again since we are going to revamp the home page I don't want the following to happen :-p


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21286134/67587464-8ff3de80-f771-11e9-9c90-27f248e329ed.gif)

**Comment by znarf** [comment]
Homepage is gone.
