### ISSUE TITLE
Apply sentence case on all strings

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2461]
**Describe the bug**
Most of the action buttons on pages - Save, Add, Remove Edit, etc. are not capitalized. This styling seems to be a little awkward when there are some other contents in the action buttons.

You can observer this style behavior at a lot of places

**To Reproduce**
1. Go to 'https://opencollective.com/{username}/edit' - profile edit page
2. Check the `save` button at the bottom

**Expected behavior**
The button content should be `Save` capitalized text

**Screenshots**
<img width="757" alt="Screenshot 2019-09-28 at 17 44 38" src="https://user-images.githubusercontent.com/18121502/65816391-6dc17c00-e218-11e9-96a2-fd72f060c7f9.png">

🆙 check the `remove Core Contributor`, `add Core Contributor` or `save` button

**Comment by Betree** [comment]
+1 on this one. We've enforced capitalization in a lot of places but it's currently inconsistent and we should do a pass to migrate everything.

@alanna is that ok for you? Are there places where you think we should not capitalize the first letter?

**Comment by alanna** [comment]
This is a stylistic choice as there is no hard and fast rule for capitalization of buttons like this in English. But whatever we choose, it should be consistent. Because buttons are capitalized in the new Collective page design, I think we should make it that way everywhere. The same goes for bits of text like "view collective page". 

It's called "sentence case" when you capitalize the first letter of phrases and sentences, and "title case" when you capitalize every letter. Proper nouns are capitalized regardless (e.g. the names of specific things on our platform like Collective). Google Material Design follows sentence case, while Apple goes for title case. I tend to agree with Google and [so does this article](https://medium.design/a-thorough-detailed-comprehensive-methodical-guide-to-capitalizing-strings-in-our-user-interface-11b39da146f3). 

All lower case isn't really an option I can see recommended in articles about this at all.

**Comment by JoyLubega** [comment]
Hey @maddhruv when I got to the page you have mentioned, I don't see those buttons.

**Comment by Betree** [comment]
@JoyLubega This particular button is now capitalized indeed.

**Comment by Betree** [comment]
Text cases described here have been fixed, and new designs now apply case policies. Closing!
