### ISSUE TITLE
Add type dropdown to edit expense options

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2486]
## User story 
As an expense submitter, Collective admin, or host admin, I want to be able to change an expense's type between invoice and receipt, so that I can correct errors made at the time of submission.

## Best solution for this problem
Add the dropdown to the edit expense options.

## Metrics 
Reduce the need for developers to have to change these manually.

![Screen Shot 2019-10-03 at 3 36 55 PM](https://user-images.githubusercontent.com/5498878/66095471-20685480-e5f4-11e9-844b-ab6149dc08f1.png)

**Comment by someofthethings** [comment]
This looks pretty basic. Any chance of an assignment?

**Comment by jeffin143** [comment]
![Screenshot from 2019-10-10 17-07-09](https://user-images.githubusercontent.com/21286134/66565680-acdcbf00-eb80-11e9-8311-5091648cdcfc.png)

@alanna , The option is already there, or did i miss something !!

**Comment by znarf** [comment]
@jeffin143 it’s in edit, not in create

**Comment by jeffin143** [comment]
thanks @znarf , could you point me to the editeEpense form, since I went through the codebase components/expenses/* and couldn't find edit, may be you could guide me.

Thank you

Or is this the right location to add
https://github.com/opencollective/opencollective-frontend/blob/1bc17264d2cdaec4174fde0e83da07f983fec8c0/components/expenses/ExpenseDetails.js#L234-L251

**Comment by znarf** [comment]
@jeffin143 I can confirm it's in `ExpenseDetails`

**Comment by jeffin143** [comment]
@znarf , I tried making apt changes, but I am not sure How to test it, Since I am not a collective admin. So possibly should I make a PR , and you will go ahead and test , or if you could let me know a way of testing it. I can handle that .

**Comment by jeffin143** [comment]
> @jeffin143 I can confirm it's in `ExpenseDetails`

I am working on this , I have almost done it , but for some odd reasons I am not able to get the expense from createexpense form , can I open a WIP pr, and then you may help ma a liltle bit 
Thanks :)

**Comment by znarf** [comment]
Adding a bounty. @jeffin143 is already on it. Please try to fix the PR within 7 days or we will open to someone else.

**Comment by znarf** [comment]
🏆 This issue was completed by @jeffin143 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
