### ISSUE TITLE
Allow anyone to comment on expenses

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2490]
Right now only the admins of the collective and of the host can comment on expenses.

I think that we should relax that rule and allow any logged in user to comment on any expense.

This has multiple benefits:
- it will make it more clear that those expenses are public and anyone is invited to ask for questions or provide feedback (i.e. more details about the reason for that expense, a link to a social media post for Cloudflare, ...)
- More people can comment to "approve it"
- It follows the policy of Github on pull requests and issues where also every logged in user can comment.

This is a very easy change so happy to take that on but just wanted to check first if you were fine with such change.

**Comment by xdamman** [comment]
Feedback from Pia: ok but then we also need to offer a way to remove comments (in case of spam)

**Comment by alanna** [comment]
I agree that we should let any logged in user make a comment. I've encountered this when I want to make a comment on expenses myself in relation to support requests, but I can't because the Collective is in a host where I'm not an admin.

I agree about the spam problem. It's been growing recently. Requiring a login is a good partial filter but won't stop it entirely. There's already an issue for this #2323 for host admins deleting comments, but maybe we should extend this to Collective admins too. The downside to that is potential impact on transparency, but I feel OK leaving that up to core contributor discretion.

**Comment by znarf** [comment]
It's not exactly "host dashboard" but because it's related we'll be tackling that as part of the "host dashboard" project.
