### ISSUE TITLE
Show contributors grouped by Tier

### ISSUE THREAD

**Issue by deepu105** [opencollective/opencollective#2511]
## User story 
As collective admin, I can visualize contributors better

## Best solution for this problem
Instead of showing all contributors together, show them grouped by tier

**Comment by piamancini** [comment]
hi @deepu105! Thanks for raising this. 

The challenge is that we don't limit the number of tiers so it can get potentially bloated with filters. But we can consider it for an enhancement of NCP. 

I know it's not ideal, but if you click on the Red More on the tier, you go to your standalone tier page: https://opencollective.com/generator-jhipster/contribute/backer-2595 And you'll have the financial contributors to that tier. If a tier is not linking to a standalone (because the description is too short, you can go into edit/tiers and click on Force Standalone Page)

<img width="974" alt="Screen Shot 2019-10-08 at 5 54 14 PM" src="https://user-images.githubusercontent.com/3671070/66411930-d963d000-e9f4-11e9-8813-d7d4d1ec0a2a.png">


Is this workaround good enough? If not, please explain the use case more in detail so we can consider it.

**Comment by deepu105** [comment]
Hi Pia, Thanks, I have seen this view it's good for me personally, I just thought it might look nicer on the front page as well. But I understand your concern, maybe a filter alongside the below could be an option as well.

![image](https://user-images.githubusercontent.com/1107223/66412382-b38afb00-e9f5-11e9-9aca-4e35a5b8f47b.png)

Anyway, I didn't think of the too many tier issue, so feel free to close this if you feel appropriate.
