### ISSUE TITLE
expenses page makes duplicate queries for every single expense

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2519]
**Describe the bug**
The expenses page for any collective makes _n_ number of queries (network calls) for _n_ number of expenses i.e. it makes a separate query for each expense. Even when the query - `allExpenses` returns with the information required for all the expenses the page makes recursive queries `Expense` for each expenses it encounters.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://opencollective.com/babel/expenses'
2. Check the network panel in dev tools
3. You shall see a huge number of queries being made.
4. But if you inspect the data/response for the first query, all the data required to render these expenses are already available with it.

**Expected behavior**
It should simply not make all these duplicate (which fetches the same data) queries

**Screenshots**
<img width="1287" alt="Screenshot 2019-10-11 at 01 20 31" src="https://user-images.githubusercontent.com/18121502/66601751-4084ae80-ebc6-11e9-80bc-841f76b7f15a.png">
<img width="555" alt="Screenshot 2019-10-11 at 01 26 22" src="https://user-images.githubusercontent.com/18121502/66601759-437f9f00-ebc6-11e9-8123-56bbe75cc6d0.png">

**Comment by someofthethings** [comment]
Tryin' to get paid twice, amiright!

**Comment by piamancini** [comment]
@flickz this might be useful since you are looking into this issue.

**Comment by Betree** [comment]
@piamancini  this is not related to https://github.com/opencollective/opencollective/issues/2520

From my understanding, we need to refetch the data because some fields (`privateMessage` for example) are only accessible when you're logged in, if you have access to them.

However you're right that having one fetch per item is an issue. We need to migrate that code to refetch only the main query (`getExpensesQuery`) and only if the user is logged in. An example for a similar behavior can be found in https://github.com/opencollective/opencollective-frontend/blob/fef6cb3e6a03747d324580da4f6ca479981c1e6a/components/collective-page/sections/Transactions.js#L118

@piamancini are we going to revamp this page in the expenses flow project? If so, I wouldn't prioritize this issue (it's an optimization).

**Comment by franciscotv** [comment]
hello, I was not aware of the *complexity* category level `-> unknown`, what is the meaning of this category? who could give a hint on the complexity of this task/issue?
**Thank you**

**Comment by Betree** [comment]
Hi @franciscotv, we didn't try to estimate to complexity (thus it's `unknown`) because it's also a `wontfix`, the page mentioned here has since been revamped and the new version is not affected: https://opencollective.com/webpack/expenses/

There's still one path suffering from this issue, bet we also plan to revamp it in the next months and don't want to invest in optimizations for it.

**Comment by franciscotv** [comment]
thanks @Betree for the clear explanation, I see the revamped took place. So, I wonder if this should continue to be consider as a valid effort/task for **[open collective bounty hunters](https://docs.opencollective.com/help/contributing/development/bounties#open-collective-bounty-program)** like i am myself, this said, i have to say i do not see the whole picture of this effort as you do. This issue/task is still listed in the bounties [page](https://github.com/opencollective/opencollective/contribute) and i wonder if i should tackle it or not. Please let me know your thinking.

**Comment by Betree** [comment]
This one is not a bounty.

As specified in the doc you linked, only issues with the `bounty` label are eligible for bounties. You should go to this page to find bounties: https://github.com/opencollective/opencollective/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abounty

**Comment by Betree** [comment]
This is resolved in the new expense(s) pages. Only the host dashboard `Expenses` tab is still affected, but it's about to be replaced by the new `Expenses (beta)` tab, which is not.
