### ISSUE TITLE
Accepting financial contributions in Bitcoin

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2522]
I've been exploring options to enable the Open Source Collective to accept financial contributions to Collectives via Bitcoin. I signed up with [Bitpay](https://bitpay.com) and we've been approved for a merchant account. 

The Open Collective team isn't able to prioritise a bunch of dev in this area right now, so what I'm trying to figure out is if there is a lightweight way to do some initial experimentation before getting into more complex options or technical integrations. Right now I am assuming this will be handled by manually reconciling payments and crediting Collective balances in our system.

Bitpay will enable us to accept bitcoin donations and immediately transfer them to USD and send to our regular bank account, allowing us to integrate the payments with our current fiat-based systems. This is the option I'm considering at the moment, as we're not able to get into expense payouts in bitcoin or anything involving accounting in crypto at the current time.

My questions:

* Are Collectives interested in receiving Bitcoin contributions? Do core contributors think this channel will be used by supporters to give to your Collective?
* Does anyone in our community have experience with the Bitpay system specifically? I'm trying to work out how we can track which funds belong to which Collective as they come in.
* To the OC team, I'm wondering if this could work via pending orders, similar to how we do bank transfers now. They'd select "bitcoin" and be told how to transfer the funds, then we'd manually mark as paid when received. Am I on the right track thinking that would be pretty simple to implement?

If you would be interested in being an initial guinea pig Collective for this project and experiment with receiving bitcoin contributions as we figure out how this can work, please let me know.

**Comment by alanna** [comment]
Sigh. Bitpay has now closed our account after looking more closely at what we do. Seems like we can't get a crypto merchant account anywhere (we also tried with other providers previously), so we can't offer this service to Collectives. Hopefully we can find a way in the future.

**Comment by jhabdas** [comment]
> Bitpay has now closed our account after looking more closely at what we do.

Who is "we" and what exactly is it that we do? Accepting a Bitcoin payment is in my mind the most ideal thing any open source contributor could possibly want. It's near instant, borderless and irreversible.

Ref: #2238 #1005 #1076 #764

**Comment by jhabdas** [comment]
https://github.com/zloirock/core-js/issues/635#issuecomment-547461547

**Comment by alanna** [comment]
"We" in this instance is the Open Source Collective, the legal entity that holds funds on behalf of open source Collectives. If someone can find us an exchange willing to work with us, we'd love to support bitcoin payments.

**Comment by GriffGreen** [comment]
@alanna I assume you have reached out to Gemini and Coinbase... maybe try Abra? Hopefully others will come out of the woodwork... 
https://twitter.com/thegrifft/status/1197175614400167937?s=20

**Comment by alexk111** [comment]
@alanna Bitpay is the worst processor both for merchants and customers: https://debitpay.directory/anti-bitcoin/
Check these: https://github.com/alexk111/awesome-bitcoin-payment-processors

**Comment by alanna** [comment]
We spent ages filling out paperwork for Gemini, only for them to reject us. 

I will try looking into some of the other options suggested here, but I have limited capacity at the moment. If anyone wants to help out please let me know!

**Comment by alanna** [comment]
I'll reopen this issue for the time being, although we shouldn't expect progress quickly on this.

**Comment by xoviat** [comment]
Two more processors that you can try are CoinGate and OpenNode. Looking at your business model though, may be difficult to find a processor that would convert the payments to fiat for you. The problem is that processors are looking to avoid AML/compliance problems, and that becomes much more difficult when there are many users on one platform. As I see it, you have two options:

1) You can try the two processors that I mentioned. There is reason to think that CoinGate would support you because they previously supported SubscribeStar, which has a business model similar to yours and has been deplatformed by other payment processors (leading me to believe that CoinGate may be more resistant to deplatforming). 
2) You can use btcpay and pass the payments through to the projects themselves. This option would guarantee a stable API since it could not be shut down, because you would not have to convert to fiat. However, you would have to run a server which incurs a fixed cost. Also, you may have to comply with 5AMLD EU regulation if you hold payments.

**Comment by xoviat** [comment]
@alanna I may be willing to do some work to help you out. Basically anything but writing JavaScript.

**Comment by alanna** [comment]
Thanks @xoviat ! Can you look into whether CoinGate might accept us? We present a pretty complicated use case that doesn't tick the easy boxes for most services, so that's why we keep getting rejected. It seems you understand the issue, as our model is being a single entity representing thousands of different projects.

We aren't able to work with cryptocurrency if we can't convert to fiat (for the time being) because we have lots of accounting processes set up and it all only works with fiat. Paying out BTC to projects directly would present too many complications for us right now. How would we report that income on our taxes, etc? In the future we might be able to take that on as a project, but it would be a big one and we don't have capacity at the moment. For now, crypto payments would need to fit into our existing processes, and to do that we have to convert it.

**Comment by xoviat** [comment]
Coingate is not willing to accept open collective because open collective is registered as a nonprofit in the United States (at least I was under the impression that it was). OpenNode will accept open collective with an opt-in model: each project can opt-in to receiving bitcoin after designating someone to undergo KYC. Would you like to move forward with OpenNode?

**Comment by alanna** [comment]
Thanks for looking into this!

Can you put me in touch with whoever you've been taking to at opennode so I
can discuss the details of how the process would work?
alanna@opencollective.com

I'm not surprised the other service won't accept us because we're a
nonprofit. That's depressingly common in the crypto space.

**Comment by xoviat** [comment]
You can contact Kevin with the contact form at https://www.opennode.com/contact, I am not specifically familiar with their KYC approval process, but my conception is that you would have a new database boolean field called "kyc_approved" and then you would have a new button that says "accept bitcoin" in the project configuration page that redirects to their KYC page, and then they would respond with a message that KYC has been approved, and then you can change the "kyc_approved" field to true. And of course, if "kyc_approved" is true, then display the bitcoin payment option. It's a bit of extra work, but once the process is fleshed out, I don't foresee that much effort devoted to maintaining the bitcoin payments because this process seems easily automatable, and I also think that there's a good chance that you won't be shut down.

If you have any further questions or need any more assistance, let me know.

**Comment by alanna** [comment]
Thank you @xoviat I will reach out to them.

**Comment by alanna** [comment]
**Update:** We have been approved by OpenNode and are in the process of testing out how bitcoin contributions can work. If any Collectives are interested in early access, [sign up here](https://docs.google.com/forms/d/e/1FAIpQLSfyiaEMZN_DfzxiAHADQGlzKrFrVNHfAiNrFZ8c24-bjKmC0g/viewform).

**Comment by alexk111** [comment]
@alanna Congrats! Have you considered an idea of Bitcoin-only Fiscal Hosts not requiring a bank, a stripe and a paypal account?

**Comment by alanna** [comment]
@alexk111 - I'm not opposed to that idea at all. It's just not something we're able to prioritise at the moment due to other important projects. So we're beginning with Bitcoin contributions that are immediately converted to USD so we can accept them through our existing systems. 

There are quite a few services out there already for open source projects to get funded in cryptocurrency, so we don't feel a pressing need to fill that particular niche. Our niche is about solving the pain points involved in accepting fiat (taxes, accounting, banking etc).

If someone independently wants to take on the project of starting a crypto-host and figuring out how to integrate it with the Open Collective platform, we're certainly supportive.

**Comment by mytwocentimes** [comment]
@alanna - can you list a few of the services of which you are aware that fund open source work in crypto ??  thank you in advance

Otherwise, as regulators (both USofA, but also international) ramp up on regulating wire-transfers (including crypto) solving tax, accounting and banking for bitcoin funded support will be a thing ... my two cents :)

**Comment by alanna** [comment]
@mytwocentimes Gitcoin is one funder. I've also worked on OSS projects funded by crypto grants from Handshake, Ledger, ConsenSys, DAOstack, Ethereum Foundation and a few others. Those always seem to come from random connections as opposed to formal processes though.

I agree about the market niche for Open Collective type services for the crypto space. It's not our focus right now because there's still so much to do in the fiat space, but it's certainly on the radar.

**Comment by knocte** [comment]
This being closed means OpenCollective will never support crypto-integration?

**Comment by alanna** [comment]
@knocte - Open Source Collective can accept contributions in Bitcoin. I'm happy to assist other hosts who are interested in setting up a similar system.

**Comment by knocte** [comment]
> Open Source Collective can accept contributions in Bitcoin

Oh, how? I don't find it in the UI.

> I'm happy to assist other hosts who are interested in setting up a similar system.

What do you exactly mean with the word "hosts" here?

Thanks

**Comment by alanna** [comment]
@knocte the host is the entity who holds funds for a Collective and is responsible for receiving its funds. 

This option is not in the UI as it's a beta feature we have to activate manually for OSC Collectives who want it.

Which Collectives(s) would you like to give bitcoin to?

**Comment by knocte** [comment]
> Which Collectives(s) would you like to give bitcoin to?

Well, actually, my interest in OpenCollective is not so much because of the current collectives that you host, but because of potential ones: I was about to recommend OpenCollective to a developer that is starting an opensource project (which I might be interested to donate to); plus I also work as a maintainer of an opensource project, and I might be interested to setup a collective for it. But I'm only interested in going forward with these two possibilities if cryptocurrency integration is a real option, not just beta :)

**Comment by alanna** [comment]
@knocte - OK, well as long as they sign up with Open Source Collective as their fiscal host, we can enable Bitcoin contributions for them. I don't know what you would want in a more integrated cryptocurrency option, but you're welcome to raise a new issue for it with specs. For now, our beta Bitcoin integration is working fine for us.
