### ISSUE TITLE
Edit button overlapping text in About section on Collective page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2523]
![Screen Shot 2019-10-14 at 12 22 33 PM](https://user-images.githubusercontent.com/5498878/66724067-7ef7c300-ee7d-11e9-8957-f993b80704f0.png)

**Comment by dinolinjob** [comment]
Take it..

**Comment by dinolinjob** [comment]
Can I work on this? @alanna

**Comment by Betree** [comment]
Hi @dinolinjob, feel free to do so :slightly_smiling_face: 

Please not that we don't want to change the styles for the other inline editable fields (in most cases we do want this icon to overlap the content, because when the icon is smaller than the text it doesn't hide anything). The problem here is that the icon can eventually hide characters for collective admins.

So the proper fix would be to keep the default `top={-5} right={-5}` for `InlineEditableField`, but make it configurable and change it for the about section of the collective page.

**Comment by dinolinjob** [comment]
@Betree Changing the value of top={-5} to top={-18} prevents overlapping. How can I change the value of top to top={-18} for about section? Is there a way to do styling such that top value alone changes?

**Comment by Betree** [comment]
@dinolinjob Yes. You need to add new props in `InlineEditField` so that it can be customized from the parent (the parent here is the about section).

**Comment by Betree** [comment]
Resolved by @dinolinjob in https://github.com/opencollective/opencollective-frontend/pull/2837 :tada:
