### ISSUE TITLE
Should we use staging for all Cypress tests?

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2531]
Cypress tests are great candidates for bounties, but it's currently hard for us to outsource them:
- Though well documented, configuration is not easy: contributors need to setup a local Postgres, a local API and configure their Frontend to point on it.
- Contributors often miss this first step and are then confused because the data they use (from staging) doesn't match the one in CI (from local dump).

The CI is also slowed down by the fact that it needs to pull the API, build the API and the Frontend then start everything.

## Proposal

By assuming cypress tests always point to staging, we could drastically improve the flow for new contributors to work on Cypress tests: just run `npm run cypress:open` and it's ready - no need to setup the API.

Thanks to Zeit, we could run the tests directly against the pre-deploy - no need to rebuild nor pull the API (see https://zeit.co/docs/v2/advanced/now-for-github/#extending-your-github-workflow).

**Expected gains**
- Faster CI (skip the build of Frontend, skip the build of the API)
- Easier to contribute
- Easier to debug (tests always point to the same data)

**Expected downsides**
- Actual cypress tests would be slowed down because server will not be local anymore
- Tests that depends on existing data would not run anymore against a local API
- We'd loose the feature of having the Frontend PR match the API when they have the same name
- Because staging is shared by everyone, a collective that have been modified could make the test fail for everyone. We may want to use `cy.createCollective` more and make our tests more flexible (example: don't expect Host to have x collectives or y budget).

---

Ping @opencollective/full-time-developers @opencollective/confirmed-contributors @opencollective/recurring-contributors - what do you think?

**Comment by piamancini** [comment]
pining @sbinlondon too - one of her bounties was Cypress related.

**Comment by NotJohs** [comment]
I don't understand the overall picture. 
What I find valuable is the ability to dynamically create a collective and also seed this collective with dummy data. e.g `Transactions || Events`
This would significantly speed up the testing process.

**Comment by sbinlondon** [comment]
This is really well thought through.

My Cypress bounty was very small so I don't know if I can really advise much on this.

I thought the documentation for setup was straightforward. I ran into issues but that was due to how Postgres was installed on my computer. I had to repair some stuff with Homebrew but the Open Collective Postgres docs helped with that.

Maybe we can think how we can do the most to make sure local setup is super easy to allow the current way to work? Maybe a giant script that sets ups local Postgres, local API, and points frontend at it all in one go?

Can't really speak to the pros vs cons, but my thought in the end is how can we best optimise the current process and make it work for everyone, before going through the effort to completely change how it works. (Or maybe it's not a lot to do - still learning a lot about Circle CI and Cypress 😅)

**Comment by flickz** [comment]
The downsides to me are huge compare to the gains, I think we should have cypress for both environments. Like you said this will be difficult for staging because our current tests rely on data from the local dump. 

> We may want to use cy.createCollective more and make our tests more flexible (example: don't expect Host to have x collectives or y budget).

I believe this is the solution. But is it possible we can get all our tests to 100% rely on data created during the test process and cleaned up after the tests have ended? (No reliance on any data stored and no data stored permanently on db). If this is achievable getting cypress to work on any of the environments shouldn't be a problem.

Although with this way the tests might become slower but if we can find a way to optimize the process for data creation.

**Comment by richport** [comment]
awesome very good idea if will work perfect

**Comment by Betree** [comment]
> But is it possible we can get all our tests to 100% rely on data created during the test process and cleaned up after the tests have ended?

@flickz  Not easy, but that could be achieved indeed. The tricky part is for the tests like the one for the organizations profiles. One of the them is for example making sure that there is a `Load more` button in contributions, which requires the organization to have made contributions for at least 30 collectives. If we want to create this data we'll need to make calls in GraphQL directly (it would be too slow to make this from the UI). 

I agree with the general idea of your comment, having environment-agnostic tests that can run the same in local or staging would be the best solution in terms of simplicity.

**Comment by sbinlondon** [comment]
> I agree with the general idea of your comment, having environment-agnostic tests that can run the same in local or staging would be the best solution in terms of simplicity.

+1! Not sure if this is something that will be worked on immediately or not, but I'd be interested in helping out with it, it sounds like a really interesting problem to work on.

**Comment by Betree** [comment]
> Maybe we can think how we can do the most to make sure local setup is super easy to allow the current way to work? Maybe a giant script that sets ups local Postgres, local API, and points frontend at it all in one go?

@sbinlondon Maybe a `docker-compose` script could be a good way to achieve that? I did one in the past for another project, was helpful to pull the API and start it in one go: https://github.com/CaptainFact/captain-fact-frontend/blob/staging/docker-compose.yml. I'm curious if something that would also start the frontend would be fast enough to provide a good experience.

**Comment by Betree** [comment]
Thank you everyone for providing feedback! That was really helpful. We'll follow up in https://github.com/opencollective/opencollective/issues/2556 to define new patterns to make these tests more generic.

We'll eventually create a separate ticket if we also want to start a new project to have a "magic script" to start everything as proposed by @sbinlondon above.
