### ISSUE TITLE
Contact form for collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2532]
## User story 
Users need to be able to contact hosts and collectives.

## Best solution for this problem
We're not happy with the current button that is a simple link with a `mailto:`. We want to replace that with a proper contact form that will not leak the email address.

### Frontend

- Create a new page in `/{collective}/contact`
- Make the contact button link to that new page
- Users need to be authenticated to see the page
- On the page, show a form with:
   - Subject (optional): string
   - Message (required): text
   - Submit button

### API

- Add a `canContact` function on collectives that returns true for hosts, collectives or events.
- Create a `sendMessage` mutation
  - Must be authenticated
  - Add a cache to limit emails sent to 5 per hours 
  - Only accepts collectives if `canContact` is true
  - Can't contact collectives with `isActive` === false
  - Must strip all HTML content from the message (`html-sanitize` with strict options)
  - Params:
    - `collectiveId`: the collective to send the email to
    - `subject`: string, optional
    - `message`: text, required

- Add a function called by the endpoint when params are valid that will send a new email template like the following one. The `Reply-To` header must be set to user email.

> Subject: New message from {fromCollective} on Open Collective
>
> Hi {collective},
> {fromCollective} just sent you a message on Open Collective:
>
> ------------------------------------------------------------------------------
>
> / Message in \<quote> / 
>
> ------------------------------------------------------------------------------
>
> You can send a message to {userName} ({userEmail}) by replying to this email.
>
> If this is a spam, please forward the message to support@opencollective.com
>

## Going further

We may want to add a CAPTCHA on this page if it's used by spammers.

**Comment by xdamman** [comment]
Hiding information (the email address of the collective) is not a sustainable way to solve the problem.

I’d much rather use our energy to solve the real underlying problem instead of getting in the way of user experience.

Can we reframe the question into: how do we avoid collective email addresses to get spammed and explore the different options?

**Comment by xdamman** [comment]
From a user perspective endpoint, it’s much much better to have an email address for your collective. That’s a big draw for the new business model. People need to pay $5/month/user today with google apps for that. Creating an email address for a group of people is a big need.

So even if we offer a form to contact the collective on the collective page, we will have to offer an email address. And we cannot control its publication. People will share it on many different platforms. And those emails will be spammed at some point.

So if we have to address that issue anyway at some point, we may as well solve that issue rather than creating a different way to contact the collective that will force people to be logged in no?

Since it’s just a forwarding email, I’m surprised that this is an issue. It feels to me that gmail would actually catch that spam. Am I missing something?

If that assumption is right (big if), then the end user is actually not that much impacted but our spam score with mailgun is (which is a problem).

**Comment by Betree** [comment]
@xdamman It's a much nicer feature to have a redirect email indeed but also a much complex one, that won't be solved in a day. Google is still not blocking all the spams I receive on Gmail, I doubt that we'll be able to do better than they do in a reasonable time frame.

> It feels to me that gmail would actually catch that spam. Am I missing something?

Gmail do catch the SPAM, and because our servers are the origin we take the risk of having them flagging all our emails if we don't filter correctly.

> So even if we offer a form to contact the collective on the collective page, we will have to offer an email address. And we cannot control its publication. People will share it on many different platforms. And those emails will be spammed at some point.

If that's important let's follow up with that in a separate project. The solution proposed here is a better user experience than a `mailto:` that opens your OS email client and it's pretty easy to implement, so we don't take much risk in implementing it.

Figuring out a good security with basic spam filtering and a separate server than API to forward the email is a more complex task.

**Comment by piamancini** [comment]
Another option is to enable collectives to add their preferred contact method, sort of a yaml for contact. See https://opencollective.slack.com/archives/C0HSLRNVC/p1571314191099100 Bower has a contact point, maybe they prefer to direct sponsors there. 

> we will have to offer an email address.

I agree that the solution here helps a need right now and adding a new email system is out of scope of this issue. For the next months of roadmap, offering an email service is not a priority. I'd like to see first, the new business model collectives coming on board and then beef up features for them. We have time to scope a proper feature for this. That doesn't mean we can't fix this now.

**Comment by Betree** [comment]
> Another option is to enable collectives to add their preferred contact method, sort of a yaml for contact.

@piamancini I've updated the specs on #2263 to reflect the new contact form.

**Comment by alanna** [comment]
I agree with @Betree - the proposed solution of a contact form is a better experience than the current `mailto`, and providing Collectives an email address that deals with the spam question should be considered a seperate project.

A *lot* of open source projects put a lot of effort into *not* sharing an email address, because they get spammed not just by typical spammers but by 10,000 asking for users support, feature requests, etc, and they work hard to direct people to their issues or forums instead. Many well known open source devs also get badly harassed by recruiters. It's the opposite problem to a community group or movement that wants their email as accessible as possible. 

If we don't provide some filtering like Ben suggested, they will simply block emails from their Collective if it's overwhelming them, and then we've lost the communication channel. So I think we should go with the solution Ben has proposed now, and maybe in the future even offer a toggle setting to only accept emails from contributors to the Collective.
