### ISSUE TITLE
Cannot add event as a core contributor

### ISSUE THREAD

**Issue by paul121** [opencollective/opencollective#2544]
**Describe the bug**
As a core contributor of the [farmOS](https://opencollective.com/farmos) collective I cannot add a new event.

**To Reproduce**
1. Sign into opencollective.
2. Go to `opencollective.com/farmOS/events/new`
3. The error reads "You need to be logged in as a core contributor of this collective to be able to create an event. [Sign In Button]" (At this stage it shows my account `paul-weidner` signed in)

**Expected behavior**
Be able to create a new event for the collective.

**Screenshots**
<img width="1546" alt="Screen Shot 2019-10-20 at 12 48 53 PM" src="https://user-images.githubusercontent.com/3116995/67165265-00e16380-f338-11e9-9c19-74a4979d285d.png">

**Desktop (please complete the following information):**
 - Firefox v69.0.2

**Additional context**
After I was added as a core contributor to the project, I received an email that said go to `farmos/events/new` to create events.

**Comment by Betree** [comment]
Hi @paul121, you may be facing a cache issue. Just to be sure, do you still see the error after refreshing the page?

**Comment by piamancini** [comment]
Hi Paul, this is happening because you are a contributor to farmOS and not an admin - you need to ask Michael to make you an admin. He is the only admin of the collective. 
He can edit roles in https://opencollective.com/farmos/edit/members
<img width="951" alt="Screen Shot 2019-10-21 at 6 40 46 PM" src="https://user-images.githubusercontent.com/3671070/67185842-7598c880-f432-11e9-8213-fab7512fbc17.png">

**Comment by paul121** [comment]
Thanks for verifying that @piamancini !

You may want to update the emails that get sent out - this is what I received (note this was 13 days ago) after I was added as a core contributor. It seems to say that "MEMBER" permissions give you access to creating new events:

<img width="1309" alt="Screen Shot 2019-10-21 at 9 57 17 PM" src="https://user-images.githubusercontent.com/3116995/67260041-f5805c00-f44d-11e9-9686-fdb473f4e53d.png">

**Comment by Betree** [comment]
Thanks @paul121, that's wrong indeed!

@piamancini @znarf what should we do, update the email or allow `Member`s to create events?

**Comment by paul121** [comment]
@Betree  happy to help!

In our case it would be great if a `Member` could create events without being admin :smile: 

I came across this because I wanted to add an event for a conference I'll be speaking at. I don't necessarily need admin privileges to approve expenses, but would like to be able to add events!

**Comment by piamancini** [comment]
> In our case it would be great if a Member could create events without being admin

@Betree I think this was the original intent and thus the email. We would have to double check how the approving of expenses work, since the person who creates the event is the only one who can approve expenses for it, they became the default admin of the event. Beyond this particular case, I think event admins have an expectation to manage the event expenses. 

@paul121 have you been unblocked already by the collective admin?

**Comment by paul121** [comment]
@piamancini I haven't been unblocked, no. The admin went ahead and just made the event for me. We just wanted to add the event as a way to "advertise" what is happening - not sell tickets or anything. I wasn't aware that expenses can be tied to events - so it makes sense that some additional permissions are required!

**Comment by piamancini** [comment]
sorry @paul121 I'm not following. If you need to be made admin of the collective or the event, that's something the collective admin can do for you. You can then make all the events yourself. You'll need to add others to the event as admin when you do.

**Comment by paul121** [comment]
@piamancini oh no - that's all fine. I have my event created 😄 

Just wanted to submit an issue because from the email I got I thought I could create an event as core contributor myself, but that wasn't the case. That's all!
