### ISSUE TITLE
Make a $5k/month donation from /ccc to /rebelsmanager

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2549]
We can't do between hosts donations.

![](https://d.pr/free/i/fsD5sM+)

Can you take care of this manually?
This should run for the next 3 months.

**Comment by piamancini** [comment]
> Can you take care of this manually?

Who are you talking to?

**Comment by alanna** [comment]
It's a pain to do recurring contributions manually. Can I just do one for $15k?

**Comment by xdamman** [comment]
I realize that but I thought that for 3x$5k it was worth it. If it continues beyond 3 months I will push to make quarterly payments.

**Comment by alanna** [comment]
I'll see if Alina can take this on. In general our policy is no recurring manual contributions because the admin is too high.

**Comment by alanna** [comment]
OK I discussed with Alina. We have initiated monthly $5k transfers in the bank account from Foundation to OSC, which will run for three months.

@xdamman how can we credit the funds to XR Rebels Manager? If we do the standard manual add funds process, it will create an Organization profile for CCC seperate from their Collective (and we'll need to submit an expense to CCC to debit $5k from their Collective balance separately). It's not possible to select "contribute as" a Collective and then select the "bank transfer" payment option to create a pending order - the only option is to select paying with the Collective balance but that won't work in this case due to different hosts.

How should we proceed?

**Comment by alanna** [comment]
@alinamanko - I talked to @xdamman about this in the meeting. @Betree is going to action #2573 so platform admins can use the bank transfer option in cases like these. Xavier will create a pending order in the system and all you'll need to do is mark it as paid when the money shows up in the Xero feed. Xavier, when the pending order is created please let us know.

**Comment by Betree** [comment]
> @Betree is going to action #2573 so platform admins can use the bank transfer option in cases like these.

https://github.com/opencollective/opencollective-frontend/pull/2912 should be deployed soon and will unlock this feature. Please note that the `Bank transfer` option will not be displayed if you set an interval (`monthly`). For this one you'll need to make 3 x one time contributions. The reason is that subscriptions don't work with manual payments.

**Comment by alanna** [comment]
Thanks @Betree - @xdamman let us know when the pending order is created, then @alinamanko can mark it as paid.

**Comment by alinamanko** [comment]
@xdamman I will await confirmation from you on this one - got the funds ready to be allocated

**Comment by alanna** [comment]
@xdamman update on this?

**Comment by Betree** [comment]
I think this is now done, can we close?
