### ISSUE TITLE
HTML showing on info card

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2554]
This is how the card looks in the Collective search result. Note the `<p>` tag.
![Screen Shot 2019-10-23 at 7 57 58 PM](https://user-images.githubusercontent.com/5498878/67434636-11028700-f647-11e9-9e02-e17e49e955e0.png)

This content is drawn from the About section, which is correctly showing the formatted text.
![Screen Shot 2019-10-23 at 7 58 16 PM](https://user-images.githubusercontent.com/5498878/67434643-152ea480-f647-11e9-89e4-749773b7586c.png)

**Comment by sbinlondon** [comment]
I'd be happy to look into this if you'd like?

**Comment by Betree** [comment]
In https://github.com/opencollective/opencollective-frontend/blob/a3c83bfa6ae5f5ba18d8d6f7a1b13c7cf5d19653/components/CollectiveCard.js#L63 the card is using `longDescription`. We can't rely on that anymore because this text is formatted and we don't want to allow that in the cards.

So immediate fix would be to remove this behavior, and a possible way to fallback on `longDescription` would be to add a `longDescriptionSummary` field (feel free to find a better name) on `CollectiveInterface` that would return the long description with HTML removed (`sanitize(longDescription, { allowedTags: [], allowedAttributes: {} }`) and truncated to 255 (I think that's the max length for `description`).

@sbinlondon thanks for proposing, feel free to take it! The solution above is just a proposal, if you see a better solution ideas are welcome.

**Comment by sbinlondon** [comment]
Thanks for the info - I'll be sure to jump on this this weekend! 🙌

**Comment by sbinlondon** [comment]
Quick update: I am still going to work on this, just moved house last weekend and haven't had internet/been busy unpacking and getting things set up, so will be able to do more starting this week 😊

**Comment by jeffin143** [comment]
@Betree let's close this to keep issue count less :)

**Comment by Betree** [comment]
@jeffin143 You're right, https://github.com/opencollective/opencollective-frontend/pull/2969 is fixing this issue.
