### ISSUE TITLE
Profile picker doesn't allow you to create a new entry unless you type in 'other'

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2561]
As a host admin, when I need to create a new funding source for adding funds manually, the profile picker does not behave as expected. When I type in the name of the organization, if it doesn't exist already it comes up with "nothing found" and does not give me the option to create new. To create a new organization, I have to type in "other" and select "please specify". If the search string does not come up with an existing result, it should always give you the option to create a new one.

![Screen Shot 2019-10-28 at 9 26 02 AM](https://user-images.githubusercontent.com/5498878/67641200-51267a00-f965-11e9-9c1f-77faf0592063.png)

**Comment by Betree** [comment]
@alanna This is because the new Collective picker which allow to create inline hasn't been added on this form. There's already an issue for it on https://github.com/opencollective/opencollective/issues/2558

Feel free to comment directly on it, I'd like to ensure that we properly cover the specs before implementing.

**Comment by flickz** [comment]
Closing this in favour of https://github.com/opencollective/opencollective/issues/2558
