### ISSUE TITLE
Allow gift card issuer to recommend collectives to support

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2565]
Triplebyte would love to recommend specific collectives to support.
Given that they are the ones paying, I think it’s a fair request.

As a first step to enable that, can we record on the TripleByte’s `Collective.settings` a small list of collectives that they recommend and add them above the “Find [other] collectives to support” on the gift card redeemed page? Something along the line of “Collectives recommended by $CARD_ISSUER”.

![](https://d.pr/free/i/bhExPe+)

---

*Edited by @Betree: message about incognito removed from the page in another PR*

**Comment by Betree** [comment]
Related to #2535 

> Also, I’d remove the notice about incognito. It’s out of place and it prevents people on small screen to see what’s below the fold. This should be shown in the context of the contribution flow (in the contextual FAQ).

Seems out of scope for this issue, but for context this message is also displayed in the contribution flow. Was specified in #2365 after we got some related support tickets.

**Comment by xdamman** [comment]
I mentioned it because if someone gonna edit that page, they may as well remove that message no?

I just looked at that issue that you referenced. But I still don’t think that this is the right place to put such message. The contextual faq is the place. If you really want to keep it, at the very least I’d push it to the bottom of the page. But I honestly don’t think think it should be on that page at all (unless we had a proper FAQ on that page)

**Comment by znarf** [comment]
- The work should happen in the redeemed page: https://github.com/opencollective/opencollective-frontend/blob/master/pages/redeemed.js
- As specified by @xdamman, it should display a list of <CollectiveCard> trough <CollectivesWithData> but based on a list provided by the Gift Card emitter through its `settings` property. We usually use `settings` for experimental properties to not impact the schema. We can name the property `recommendedCollectives`.
- <CollectivesWithData> (Frontend side) and the `allCollectives` query (API side) needs to be modified to allow an arbitrary list of `id`s or `slug`s to be passed.
- As extra, we should temporarily hide the "notice about incognito" for this specific issuer.

Adjusting the complexity and attaching a $500 bounty. Anyone submitting a Pull Request will be rewarded with $500 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md). Note that according to our guidelines, because of it's "medium" complexity this bounty is not available to first time contributors.

**Comment by NotJohs** [comment]
@znarf can I look into this issue.
Would a UI design be provided?

**Comment by znarf** [comment]
No UI design provided, just follow the directions and use the same style as elsewhere in the page.

You're assigned!

**Comment by NotJohs** [comment]
@znarf  
please can you explain the modification to `allCollectives`

**Comment by znarf** [comment]
@NotJohs in `settings.recommendedCollectives`, you will have a list of `id`s or `slug`s. You will then ask the GraphQL API to get the full information about this collectives. For that matter, `allCollectives` needs to be modified.

**Comment by NotJohs** [comment]
@znarf  Alright.
So the `settings.recommendedCollectives` are emitted when you visit `/redeemed/<gift-card-number>`  and based on this array of `slug`s or `id`s we would make a query for the respective collectives data.

**Comment by NotJohs** [comment]
>  schema. We can name the property `recommendedCollectives`.


 Questions: 
* Is this already created and emitted by a collective?
* I won't be implementing any functionality for collective admins to select these recommended collectives?

**Comment by znarf** [comment]
No, this will be directly edited in the database.

**Comment by NotJohs** [comment]
@znarf Understood.

**Comment by jasonsblake** [comment]
@xdamman and @znarf how will a user be able to adjust / modify the "promoted" projects list?

**Comment by znarf** [comment]
@jasonsblake this should be handled manually through support to begin.

**Comment by NotJohs** [comment]
This issue involves API modification.
I couldn't test the API change because I received an error: `GraphQL v1 error: column Collective.balance does not exist`.

I am guessing this is particular with some local testing organizations not properly setup.

**Comment by Betree** [comment]
@NotJohs Can you try `npm run db:migrate`? If it doesn't work, can  you give more details about the error (stacktrace)?

**Comment by NotJohs** [comment]
@Betree 
`npm run db:migrate` didn't work.

> The image below shows the only output printed when it errors out.
<img width="486" alt="Screenshot 2019-11-19 at 10 06 43 AM" src="https://user-images.githubusercontent.com/29008971/69132468-6ef28500-0ab4-11ea-82b6-ab2ed7e4549e.png">

I am still investigating this issue.

**Comment by znarf** [comment]
🏆 This issue was completed by @NotJohs

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.

**Comment by znarf** [comment]
@xdamman get in touch if you want to set up that in production for Triplebyte.
