### ISSUE TITLE
HostDashboard: Improve error display

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2567]
Errors displayed in host dashboard are currently not nice, the error message displace expense action buttons. Also some method hide error message from the user, this is not a good practise. 

<img width="542" alt="Screenshot 2019-10-28 at 2 05 39 PM" src="https://user-images.githubusercontent.com/15707013/67680692-09671900-f98c-11e9-9555-6129e54ee270.png">

**Comment by jeffin143** [comment]
+1 for this, Lot of places we have had this issue not only host-dashboard, #2008 is one of such place.

May be a solution for this could be instead of printing  them as `tool-tip` , So that when you `hover` over the `disabled button`, you get error message

Which would not displace the button ,  just a suggestion, may be you have a better plan :)

**Comment by Betree** [comment]
> May be a solution for this could be instead of printing them , display them as tool-tip , So that when you hover over the disabled button, you get error message

I did something similar to what @jeffin143 is suggesting a few days ago in https://github.com/opencollective/opencollective-frontend/pull/2869 using `StyledTooltip`. It's not meant to display errors, but I think it does the job of explaining why an action is disabled.

![image](https://user-images.githubusercontent.com/1556356/67698606-f31c8580-f9aa-11e9-9faa-92f6ccd2ac02.png)

**Comment by JoyLubega** [comment]
I would love to try this issue if no one is working on it.

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective-frontend/pull/3186 partially address this issue by implementing @jeffin143's [suggestion](https://github.com/opencollective/opencollective/issues/2567#issuecomment-546942626). We still need to lift the mutation errors up to display them properly below the buttons (rather than next to them).

**Comment by Betree** [comment]
What's left to do for this issue is:

- Errors should be centralized in the parent, and displayed above them, ideally in a `MessageBox` to be consistent.

**Comment by Betree** [comment]
Closing in favor of https://github.com/opencollective/opencollective/issues/2746
