### ISSUE TITLE
User says wrong fee amount was charged on expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2578]
See [details on this expense](https://opencollective.com/texas-camp-2019-19178ev/expenses/11004).

Open Collective shows:
> -$206.88 -$6.3 (-3.05% payment processor fee) = -$213.18 (net amount for Texas Camp 2019)

But the user says they received less than they should have and it seems like the fees were deducted twice.

> It looks like you only submitted $206.88 and then PayPal deducted $6.30 because we only received $200.58. Looks like someone on your end submitted the wrong total amount. Open Collective should've submitted $213.18.

**Comment by znarf** [comment]
I thought about it and I expect this to be a Paypal gotcha. It seems in this case fees were removed on the receiver side instead of being added on the issuer side. The `$6.30` value was properly reported by the Paypal API, not calculated by us. I think it could be interesting to log the full object returned by Paypal if we want to properly understand this case.

**Comment by alanna** [comment]
OK so will you continue to investigate here @znarf or do you want to move this to Freshdesk? There is an open ticket here: https://opencollective.freshdesk.com/a/tickets/2618

**Comment by znarf** [comment]
Closing as it's handled on FreshDesk for now. We'll open a new issue if necessary.
