### ISSUE TITLE
Blank support tickets

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#2586]
We are currently working to improve our analytics of the support functions. One area I am looking for your input is related to blank tickets received ([here is an example]() to better understand what I mean).  I don't really understand how those are triggered and looking for advice on how to treat them going forward (what category we tag them? how those are closed? etc.). At the moment there is no consistency around how different agents address those and it would be good to have a better process in place.

**Comment by znarf** [comment]
@alinamanko the idea was to help people submit issues when they get an error. However, this hasn't proven much useful, few people are using it properly. And it's likely most of the reports we get are generated from robots not humans. It's why they are blank.

We're now having the same kind of functionality but automated (via a tool named Sentry), so I think moving forward:
- we can ignore these reports if it seems to come from a robot, or if the user didn't made the effort to provide additional context by filling the blanks
- we should think about disabling this functionality because we can rely on automated reporting (via Sentry) for the future

**Comment by alanna** [comment]
If we are not using this function for anything important, I think we should disable it. It takes up our time to process all these blank support tickets (each ticket must be dealt with as none can be ignored in Freshdesk).

**Comment by znarf** [comment]
@alanna I'm not aware of these reports sent to Freshdesk, they're only appearing in GitHub, ie: https://github.com/opencollective/opencollective/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+Unexpected+error+when

Are talking about the same thing?

**Comment by alanna** [comment]
Hmm no I don't think that's the same. We're talking about the large number of blank emails sent to info@opencollective.com - we get them all the time.

Here's how they look in Freshdesk:

![Screen Shot 2019-11-05 at 1 17 15 PM](https://user-images.githubusercontent.com/5498878/68168746-b108ca80-ffce-11e9-8637-1e6a873a0837.png)
![Screen Shot 2019-11-05 at 1 16 51 PM](https://user-images.githubusercontent.com/5498878/68168747-b108ca80-ffce-11e9-9cb8-f9bf16cd9786.png)

**Comment by znarf** [comment]
It seems to me I don't have all the settings available in Freshdesk, I would like to check if we can add some automation to tackle that. @alanna can you check if I can get more rights?

**Comment by alanna** [comment]
I made you admin @znarf

**Comment by znarf** [comment]
@alanna Thanks. In FreshDesk, there is no way to filter based on an empty subject :-/

**Comment by alinamanko** [comment]
@znarf if you go to the reporting section and look into the ticket metrics report, by clicking on the column of "tickets received" you get an option to export the file as csv with the option of looking into the subject field. 

Have a go at this - hopefully it helps

**Comment by znarf** [comment]
@alinamanko that doesn't help for automation within FreshDesk unfortunately
