### ISSUE TITLE
'Load more' button on expense comment thread doesn't load more content

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2590]
At the end of the comments on [this expense](https://opencollective.com/gosublime/expenses/10024) there is a 'load more' button, but if you click it there is no new content loaded.

[See screen recording.](https://i.gyazo.com/e27f6e674a737e74f6ec23d2030e43e6.mp4)

**Comment by znarf** [comment]
@alanna Not sure what it is. I'm not able to reproduce the behavior at the moment, not seeing the "load more" button on this page.

**Comment by jeffin143** [comment]
@znarf , you are right there is no `load more` button on this page, but I can reproduce the behaviour locally, Try adding some more comments and then load button will appear.It will appear if `comments.length%10==0` and it should be more than 20 since `const Expense_SIZE = 10` and `limit = Expense_SIZE*2` so more than 20, but this page has only 13 comments :)
but if you click on the button it will append the full data again. 
example
```
a
b
c
 ```

After pressing load more it will give
```
a
b
c
a
b
c
```

just like the video

**Comment by znarf** [comment]
Thank you for investigating that @jeffin143. How do you explain that you were able to reproduce locally and not in production? Because one comment was deleted or added?

**Comment by znarf** [comment]
```
{comments.length >= 10 && comments.length % 10 === 0 && (
<div className="loadMoreBtn">
  <Button bsStyle="default" onClick={this.fetchMore}>
    {this.state.loading && <FormattedMessage id="loading" defaultMessage="loading" />}
    {!this.state.loading && <FormattedMessage id="loadMore" defaultMessage="load more" />}
  </Button>
</div>
)}
```

Ok, this is plain buggy. I understand that if there is a total of 10 or 20 comments, the load more button will be displayed for no reason. This should be revamped.

**Comment by jeffin143** [comment]
> Thank you for investigating that @jeffin143. How do you explain that you were able to reproduce locally and not in production? Because one comment was deleted or added?

@znarf , now I am guessing this part , while adding the comments there would be an instance where the `comment.lenth%10==0` would be true ( at 10th comment most probably) but after commenting further that load more button would be vanished since the condition would become false, and it again become true after 20th comment

**Comment by jeffin143** [comment]
> ```
> {comments.length >= 10 && comments.length % 10 === 0 && (
> <div className="loadMoreBtn">
>   <Button bsStyle="default" onClick={this.fetchMore}>
>     {this.state.loading && <FormattedMessage id="loading" defaultMessage="loading" />}
>     {!this.state.loading && <FormattedMessage id="loadMore" defaultMessage="load more" />}
>   </Button>
> </div>
> )}
> ```
> 
> Ok, this is plain buggy. I understand that if there is a total of 10 or 20 comments, the load more button will be displayed for no reason. This should be revamped.

I agree with you may be it should be `comments.length > 20` , but not only that there is some other issue underhood , which I guess is fishy, because even if we do that , our Mai issue of displaying everything is not resolved*

Some issue with comment.js file , fetchmore I guess , I am not sure since I don't the code base :)

**Comment by jzabala** [comment]
@znarf for this I think we need a change in the api and the frontend. I see that the type returned by `allComment` is an array of `UpdateType`. But an array doesn't convey information about how many comments are in total. We could deprecated `allComments` and create a `comments` fields that returns a type like: 
```
{
  # Total amount of comment
  total: ...
  # [UpdateType]
  comments: ...
}
```

And make the adjustments to the frontend to show the _load more button_ if the length of the comments array is lest that the total amount of comments.

`allComments`
![Screen Shot 2019-11-06 at 9 35 14 AM](https://user-images.githubusercontent.com/1315054/68302661-d3efb900-0078-11ea-991a-89d834cd9ab7.png)

**Comment by znarf** [comment]
@jzabala if you look at our GraphQL API v2, you'll see that we implemented that for every collection: `limit`, `offset`, `totalCount`, `nodes`.

We have been reluctant about mixing GraphQL API v1 and v2 in the frontend codebase so far. So here:
- either we implement in in GraphQL API v2 and figure how to make it works in parallel with v1
- or we just implement that in v1 using the same style as v2

I think it's about time we start migrating the frontend to v2, but only if this doesn't introduce trouble for developers and users.

**Comment by jzabala** [comment]
Yeah, I like the idea of using v2.

Just for reference I want to say that having multiple versions is not the recommended way, by GraphQL 
folks, of evolving a GraphQL api: https://graphql.org/learn/best-practices/#versioning.

About using two version of the Apollo client I found this resource that is perfect for us: https://www.loudnoises.us/next-js-two-apollo-clients-two-graphql-data-sources-the-easy-way/

There is also another technique called **schema stitching** and you can read more about it here: https://medium.com/open-graphql/apollo-multiple-clients-with-react-b34b571210a5. I prefer the first one.

So this issue would have three tasks:

1. Implement the `allComments` (I prefer just to call it `comments`) field in the api v2.
2. Make our two GraphQL versions work in parallel in the frontend.
3. Fetch the comments data in `CommentsWithData.js` from the api v2.

What do you think @znarf?

**Comment by jzabala** [comment]
Taking this one @znarf

**Comment by znarf** [comment]
🏆 This issue was completed by @jzabala 

I retroactively added a $500 bounty on it. To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
