### ISSUE TITLE
Show Paypal payment is processing

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#2601]
## User story 
_As collective admin,  I can Approve an expense, and also click "Pay with Paypal" when the expense submitter has chosen to be paid that way. **When I click Pay with Paypal, I see a spinner and see the word "Processing..." so that I know that I have done all I need to and can wait**. Once processing is finished I see the spinner change to "Paid" (this part already shows up nicely!)_ 

## Current feeling

the feeling I had at the moment (I'm using Firefox) is that I clicked Pay, but then the payment button just went grey.... I was like "is that invalid, or did I do something wrong"? I frantically read around on the page looking for signs of what to do.... and then "Paid" showed up, and I felt stupid. Help me not feel panicked and stupid :heart:

**Comment by gmarcos87** [comment]
Hi, I can take this issue :)

Looking quickly at the code I can think of several possible solutions.
In order of complexity:

* Change the text when loading to "Processing".
* Modify SmallButton to incorporate a spinner
* Modify Button to use StyledButton (which already has spinner) instead of the button element

I can do any of the three, but I'd like to know which one you prefer.
