### ISSUE TITLE
Some users having trouble finding the settings cog

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2606]
This is a design question. 

Some users are having trouble finding the little gear/cog on the Collective logo to access their Collective settings. 

Could we add another way to get there, such as another cog next to the Collective name in the user menu dropdown, or a more obvious button or something?

**Comment by znarf** [comment]
I personally don't understand why we have a so big button to change the collective cover/color and the settings link is so hidden. It should be as big as the others.

**Comment by contraexemplo** [comment]
I decided to chime in in this issue because this was a common theme while I was documenting setting screens. I think it would be better to have a shortcut to the main settings on the dropdown menu (where I expected it to be when I used Open Collective for the first time):

![Screenshot of Open Collective's dropdown menu, accessible by clicking on your username](https://user-images.githubusercontent.com/29989176/69483649-9aed6d80-0e08-11ea-8b98-f115036708e7.png)

Those settings are three clicks away, and I think that's a bit too much.

**Comment by alanna** [comment]
@cuiki @raulgrafico any thoughts on this?

**Comment by alanna** [comment]
This keeps coming up constantly and needs to be fixed. Adding the priority label as I'm not sure how else to get it attention. We're getting support requests about it all the time and it's blocking new admins I'm trying to onboard from using our system effectively.

**Comment by Betree** [comment]
I'm all up to fix this but we need an input from design. The best way to get their attention is to ping them on Slack.

**Comment by Betree** [comment]
@contraexemplo's proposal [above](https://github.com/opencollective/opencollective/issues/2606#issuecomment-557823252) would actually solve this in my opinion.

**Add cog icons to the user menu dropdown**

![2020-01-23_09-20-52](https://user-images.githubusercontent.com/1556356/72967757-53f90580-3dc2-11ea-8537-41aaa52ed880.png)

**Comment by znarf** [comment]
@Betree That could help. But I personally would like to see a big bold edit button on top of the collective page.

**Comment by piamancini** [comment]
ok - I'll try and get design on a fix for this soon

**Comment by Betree** [comment]
> @Betree That could help. But I personally would like to see a big bold edit button on top of the collective page.

For this an input from design is required because we already have a lot of call to actions on this page:

![image](https://user-images.githubusercontent.com/1556356/72969402-ae479580-3dc5-11ea-980f-3f202262da7e.png)

Would be great if we can find a way to reduce the overload here at the same time.

---

So should we go with @contraexemplo's proposal? As they said:
> where I expected it to be when I used Open Collective for the first time

More than the collective page, this is probably where I would have expected it too.

**Comment by piamancini** [comment]
I personally don't like the idea of having it in the dropdown menu. I'd expect that to be my profile editing, but not the collective editing. I expect the collective editing to be contextualized in the collective itself. 

For example on a github Repo you can edit your profile and settings from the top right dropdown menu but the repo settings button is contextualized in the repo itself. 

<img width="1418" alt="Screen Shot 2020-01-23 at 12 57 53 PM" src="https://user-images.githubusercontent.com/3671070/72982924-7a2d9e00-3de0-11ea-9c80-3f77ee7e47a0.png">

We waited this long, let's wait a couple of more days until design finishes with their current workload and they can look at this again.

**Comment by Betree** [comment]
@piamancini It's not exclusive, even tho I think having it in the dropdown would help it is true that we should keep it on the profile page.

The analogy with Github doesn't really fit, because this dropdown is dedicated to your personal profile and doesn't show your repositories nor your organizations. Crowdin however uses this pattern, in your projects list you can either click on the project or on settings:

![image](https://user-images.githubusercontent.com/1556356/72984174-5c156d00-3de3-11ea-8d55-57f1bdd78f82.png)

I think it's a pretty common pattern. But as there's no consensus on this one let's indeed wait for design.

**Comment by piamancini** [comment]
I'm not against it **as part of a solution** but we need to keep it contextualized as well. We can do that while we get some time in the design schedule.

**Comment by Betree** [comment]
Implemented the proposal of adding a cog to the user menu in https://github.com/opencollective/opencollective-frontend/pull/3428. I'll remove the `priority` label but let's keep the issue open until we figure a solution with design.

**Comment by alanna** [comment]
Has their been any progress on this?

**Comment by Betree** [comment]
@alanna  https://github.com/opencollective/opencollective-frontend/pull/3428 should be merged and deployed soon, it adds the following enhancements:


1. Adds a cog icon pointing to collective/org settings if user has access to them

![image](https://user-images.githubusercontent.com/1556356/73198591-85abfc80-4133-11ea-81fb-e4a4dfd20537.png)

2. Truncate text if collective name is too long

**Before**
![image](https://user-images.githubusercontent.com/1556356/73198677-b5f39b00-4133-11ea-9008-dd576c4e8dc3.png)


**After**
![image](https://user-images.githubusercontent.com/1556356/73198693-c0159980-4133-11ea-97f0-fde1570941ee.png)

**Comment by alanna** [comment]
Looks good!

@contraexemplo can you add this to the docs please?

**Comment by contraexemplo** [comment]
@alanna Sure! Looks consolidated enough to mention it.

**Comment by raulgrafico** [comment]
Link to the Figma file: 
https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hotfix-Fixes?node-id=1030%3A93

**Comment by raulgrafico** [comment]
Sorry closed this by mistake

**Comment by Betree** [comment]
![image](https://user-images.githubusercontent.com/1556356/78337777-d277dd80-7591-11ea-8052-d0105e5272d9.png)
