### ISSUE TITLE
Reorganize how files are saved

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2619]
Looking at the data, we need to improve our strategy to store files.

![Screenshot 2019-11-11 at 09 36 12](https://user-images.githubusercontent.com/806/68572868-c8303800-0466-11ea-8734-e1a8238b4c5e.png)

- We need another naming scheme for the dependency files. And a the same time, potentially fix the issue which is storing `undefined.json` currently.
- I don't see why the dependencies files are stored as a stringified JSON object. It should just be the original file.
- Would be great if the `dependencies.json` would be pretty formatted.
- The permissions on S3 needs to be double checked.

**Comment by flickz** [comment]
> We need another naming scheme for the dependency files. And a the same time, potentially fix the issue which is storing undefined.json currently.

Our current naming scheme is using the project name within package files but I think it is not consistent now with other languages package files, this is `undefined` because the `composer.json` does not have project name in it's content unlike npm package.json.  Another option is to use actual repository name but there might be cases where a repository has more than 1 package files and we don't want them overwriting each other. To fix the `undefined.json` will be to use a uuid when package name is unavailable.

> I don't see why the dependencies files are stored as a stringified JSON object. It should just be the original file.

In my attempt to save it directly I got error below from s3
```(node:30192) UnhandledPromiseRejectionWarning: Error: Unsupported body payload object```
but `dependencies.json` can be saved directly.

> Would be great if the dependencies.json would be pretty formatted.

Definitely can better, currently we have
```json
{ 
   "profile":true,
   "files":{ 
      "AbiHome-test":{ 
             "private":false
           },
         },
   "objectKeys":[ "flickz/abihometest.json" ],
   "excludedRepos": [ ],
    "selectedDependencies": [ ],
}
```

Maybe we can this instead:

```json
{
"profile":true,
   "object": [ 
           {   
             "name":  "AbiHome-test",
              "private": false,
               "key": ["flickz/abihometest.json" ]
           },
     ],
   "excludedRepos": [ ],
    "selectedDependencies": [ ],
}
```

**Comment by znarf** [comment]
For me, the clearer naming scheme should be `{githubProfile}/{githubRepository}/{pathToFile}/{filename.extension}. You need to figure the error while saving, the file should be saved "as it is".

When I mentioned pretty printing, I saw no indention whatsoever in the saved file currently. You should just pass an indentation of 2 spaces to `Stringify` and we should be good to go.

**Comment by flickz** [comment]
> {githubProfile}/{githubRepository}/{pathToFile}/{filename.extension}

What is the `pathToFile` to file here?

**Comment by znarf** [comment]
@flickz The same path than in the GitHub repository. If I'm not mistaken, in most cases, _empty_ or `/` depending on how you see it.
