### ISSUE TITLE
Review eslint pre-commit hooks

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2630]
Opening this quickly to talk about the eslint pre-commit hook implemented in https://github.com/opencollective/opencollective-frontend/pull/2804, to share my early feedback and talk together to decide if this is a good practice that we should enforce or a counter-productive one that we should avoid.

**Pros**
- It can save time for contributors who doesn't have automatic linting in their editor

**Cons**
- **Velocity**: Sometimes you just want to send a WIP commit that you'll amend later to save your work (I personally do that often when jumping from a branch to another to test PRs). This pre-commit hook makes it painful because it won't let you commit a work in progress that is not in an acceptable state for eslint. It happened to me 3 times in 2 days.
- **Accessibility**: We just deactivated the same config for another project I'm contributing to (captainfact) because a junior contributor was failing to send simple changes because of a silly error that core contributors could have fixed easily. While it's very clear to developers what they should fix when they see this message, non/young developers making their first contribution may be blocked by this without us knowing about it (so we can't assist them).

---

Ping @znarf @flickz @gustavlrsn @maddhruv - I'm probably biased, happy to hear other arguments!

**Comment by jeffin143** [comment]
@Betree I would recommend linting only through circleci and remove hook , we could then just say/mention linting should be passing in circleci , before asking for review. We could also get lining feedback from circleci and then would solve it. 

What goes through my end , is I push easy fixes without even linting, and then probably their would be a failure and then lint again - ` an extra import / something `

Also let me look through that if there is an argument to disable hook locally for confirmed contributors and let hook be there for some contributors.

If anyone wants to use they could , since it is followed across many projects so some people don't mind.

Another example here - https://github.com/opencollective/opencollective/issues/2475#issuecomment-554222548

**Comment by znarf** [comment]
I'm cool to disable it if this a problem for developers, especially core team developers. We agreed to merge it to give it a try, if the try is not conclusive, fine.

I agree we should be able to push broken code on branches.

**Comment by flickz** [comment]
I agree with @Betree especially for velocity. I think we should remove it.
