### ISSUE TITLE
"Prepaid BackYourStack payment methods" should not be visible

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2647]
It's an internal process that should be hidden to the user.

![Screenshot 2019-11-19 at 17 21 58](https://user-images.githubusercontent.com/806/69165054-3fae3900-0af1-11ea-9425-56e02f57a6e7.png)

![Screenshot 2019-11-19 at 17 21 24](https://user-images.githubusercontent.com/806/69165055-4046cf80-0af1-11ea-8af1-b45cefa73390.png)

**Comment by flickz** [comment]
@znarf  is the goal to hide `prepaid` payment method ? Or prepaid that are just for backyourstack because we don't really have a unique way of identifying backyourstack prepaid method apart from the `name` property with value "BackYourStack dispatch Payment Method" which doesn't look right to make a condition based on that.

**Comment by znarf** [comment]
> is the goal to hide prepaid payment method ?

no

> Or prepaid that are just for backyourstack?

yes

>  we don't really have a unique way of identifying backyourstack prepaid method 

we're creating them, so we should be in control of that.
