### ISSUE TITLE
Customizable "thank you" email to contributors

### ISSUE THREAD

**Issue by heyakyra** [opencollective/opencollective#2682]
## User story 
_As collective, the platform automatically sends out a thank you email to contributors, but I have no way to customize this. I want to be able to set custom text, ideally using smart templating capable of inserting data like the contributors name, the amount, and other relevant information. I should also be able to opt in or out of the addition of the "New Related Collectives" section of the email #2681 

## Best solution for this problem
Customizable thank you email contents. 

## MVP
A new section in the collective's edit settings page.

**Comment by Betree** [comment]
Sounds like a great feature to have. That would also help non-English collectives to thank their community in their native language.

**Comment by kaylarep** [comment]
We have received more requests from our hosted groups for this feature.

**Comment by kaylarep** [comment]
+1 for this

**Comment by znarf** [comment]
@BenJam volunteered to spec this as a Project.

**Comment by Betree** [comment]
Another request for this in https://opencollective.slack.com/archives/C6JTTA4SK/p1644007590497949:
> Our contributors need to 'claim' their reward manually, but this is difficult to communicate efficiently and we now have to send manual reminders if nobody shows up.

**Comment by reshamas** [comment]
This would be a wonderful feature to have, and it would also help with fundraising and help the collectives build relationships with our donors and supporters.

**Comment by natehn** [comment]
Further feedback from @reshamas: "I think it would be nice to have a custom message to keep our donors engaged.
And it would be nice if we could get a copy of the message so we know they have received it."

**Comment by piamancini** [comment]
- [ ] Meet: Clarifying status & specs

**Comment by kaylarep** [comment]
would it be possible to draft & save templates/canned replies? or maybe its irrelevant with the tier/ticket having customization abilities.

Also, Accountable just [gave us feedback](https://opencollective.slack.com/archives/G46PNRCGP/p1655356121683939) that they'd like this feature, so could do testing with them if you'd like.

**Comment by znarf** [comment]
Q2 Week 3

- Finish design @aminakazi 
- Move to implementation @SudharakaP

**Comment by Memo-Es** [comment]
## Design update

Thank you email (New section) | Preview modal | Tier settings
-- | -- | --
![Image](https://user-images.githubusercontent.com/49539954/175198984-9f1213e7-70f0-49c7-bf0d-119555cfd871.png)  | ![Image](https://user-images.githubusercontent.com/49539954/175198983-76023818-c5d0-4bc5-9681-66c8b07507b6.png)  |  ![Image](https://user-images.githubusercontent.com/49539954/175198982-61b2706f-f8f4-4a4a-8215-c0e4b7a569f3.png)
  |   |  Here I used the existing interface for tiers @SudharakaP, add the text field towards the end (Indicated by the arrow)

**Note:**We should prioritize the redesign to edit tiers soon!

[🎨 Figma file ready for production](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=17819%3A191629)

CC @znarf @aminakazi

**Comment by alanna** [comment]
OK this makes sense for Collectives and Tiers. But a main use case is per-Event and per-Project, so how can they set the thank you messages for those? Events are probably the most common use case after a global Collective custom message.

**Comment by Memo-Es** [comment]
@SudharakaP let's make sure to include a "Custom thank you email message" text field in the event creation form
<img width="858" alt="Screen Shot on 2022-06-23 at 20-23-26" src="https://user-images.githubusercontent.com/49539954/175443525-17208b76-aab3-43a5-93cd-00640d1cd5ee.png">

**Comment by znarf** [comment]
@Memo-Es can we have the section in the settings named something else than "Thank you email"? We discussed "Notifications". 

Also, seems we're trying to do way too much that what we initially scheduled. This is gonna create friction and delay shipping the MVP:
- I don't remember scoping the setting for Tiers for the MVP, actually the opposite
- I don't agree tweaking the Event creation form for the initial release
- The preview functionality will add complication
- We should start without the "inherit" functionality and just pick a default, inherit or not.

It seems we're somehow trying to accommodate many cases instead of shipping the MVP.

**Comment by Memo-Es** [comment]
@znarf I don't like 'Notifications' because it can be confused with the 'Notifications settings' page from #3357. If I'm trying to find the setting to customize emails for my contributors, it seemed a better way to be literal instead of generic. Also, we are not including anything else apart from the 'Thank you' email here, so it feels confusing IMO to call it just 'Notifications.'

As for the features not included in the MVP:
 - We can start by having it as a global feature at first. I think the opportunity to customize it across tiers, projects, and events is necessary still
 - It's ok to leave the event-form update for later
 - Same for the preview

What makes sense on the design side may sometimes include details that we consider part of the whole experience, even if it doesn't fit into the ongoing development plan. If we decide on a scope for implementation first those details can be ignored easily.

**Comment by kaylarep** [comment]
I almost think it could live under 'Advanced' in the Settings

**Comment by kaylarep** [comment]
Some copy edits @Memo-Es :
![image](https://user-images.githubusercontent.com/64920686/175663915-5795895a-bb23-42ab-8089-c21cafe86dc3.png)
"Add a custom message to be included in the email sent to financial contributors of your Collective, Project, or Event"

---
![image](https://user-images.githubusercontent.com/64920686/175664239-d57e10a5-e0ee-4cc6-9a20-f7853fdbf4a0.png)

"The above text will be considered as the default customized email response for all contributions to your Collective, and all of your Events and Projects. You also have the ability to customize the messages for Events & Projects from within their individual Setting's Menus."
___
![image](https://user-images.githubusercontent.com/64920686/175665133-cc6ed487-5e53-4265-acc5-be83e5895f83.png)
"The above text will override the customized message set by the parent Collective of this Event or Project"

(just adding some capitalizations)

**Comment by aminakazi** [comment]
Week 3 progress:
• Production-ready file handed over to @SudharakaP can be [found here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=17819%3A191629)
• We decided to rename the section in the Settings as 'Custom Email' instead of 'Thank You Email'

Week 4 updates:
- [ ]

**Comment by SudharakaP** [comment]
Just to clarify, what will be included in the MVP; 

- Copy changes mentioned above by Kayla; https://github.com/opencollective/opencollective/issues/2682#issuecomment-1165928372

What is NOT included in the MVP and we should iterate later,

- Updating the event creation form (propose my Memo); https://github.com/opencollective/opencollective/issues/2682#issuecomment-1165081295
- Email customization preview form
- Customizing across tiers; we are not touching tiers in this sprint, but in the current implementation I am working on we have support to customize the text across projects and events.

**Comment by znarf** [comment]
Let's make sure we have the simplest version of the preview before shipping. Screenshot explaining where the message will appear is fine.

**Comment by SudharakaP** [comment]
@BenJam : Now that this is deployed, shall we publish the 🔥 notification? Let me know if you would like me to write it down.

**Comment by alanna** [comment]
Yes please do a 🔥 for this!

**Comment by shannondwray** [comment]
Can we change the text so that when you're on the event settings custom page it only says event? etc.

**Comment by SudharakaP** [comment]
> Can we change the text so that when you're on the event settings custom page it only says event? etc.

@shannondwray : Are you talking about this text? 

![image](https://user-images.githubusercontent.com/12435965/179698051-72a5182e-7378-4cb6-8dd6-cf95bf035506.png)

**Comment by shannondwray** [comment]
Yup and the little blurb in blue down the bottom as well

**Comment by kaylarep** [comment]
some [feedback](https://opencollective.com/opencollective/updates/customizable-thank-you-email):
>  It is also possible to set a custom text just for a certain tier? It would be nice for example to remind banner sponsors how they should provide the necessary information for their banner.

**Comment by Memo-Es** [comment]
@kaylarep set custom text for tiers was included in the design proposal:

<img width="1059" alt="Screen Shot on 2022-08-02 at 15-01-58" src="https://user-images.githubusercontent.com/49539954/182463046-9864eb09-78a5-4669-a73c-48054f94b745.png">

With #3438 the interface will be nicer as well
