### ISSUE TITLE
Money transaction from host to OpenCollective account (not the same host).

### ISSUE THREAD

**Issue by Leadang** [opencollective/opencollective#2698]
Is it possible to pay back someone from our host (OpenCollective Paris) to his OpenCollective Account from another host?

Here the screenshot: 

![1BA4C420-279F-4BD6-A0A9-D579C51ED5A8](https://user-images.githubusercontent.com/38157592/70322752-38926500-182b-11ea-8e22-7de70c9d2220.jpeg)

Thanks a lot! 

Lea

**Comment by Betree** [comment]
Hi Léa, unfortunately we don't support cross-host donations at the moment (we plan to, see #2441).  

There's a workaround which is to make a wire transfer between hosts and record the transaction manually, but that's a lot of efforts for only $100 (especially because the collectives mentioned are using two different hosts).

Despite the fees, I'd recommend to pay the user via PayPal then he can make a donation with his credit card directly to the collectives.

**Comment by Leadang** [comment]
Merci ! 

Léa Dang 
+33647207234
