### ISSUE TITLE
Collective cover image is not updated

### ISSUE THREAD

**Issue by mhulet** [opencollective/opencollective#2708]
**Describe the bug**
I can't update the cover anymore on [my collective page](https://opencollective.com/rebelsmanager). No error shown. It is not displaying the uploaded picture.

**To Reproduce**
1. As a collective admin, go to your collective page
2. Click on 'Edit cover'
3. Click on 'Upload' and select a JPG
5. Click 'Save' (image is not showing up)
6. The cover is now missing

**Expected behavior**
Uploaded picture is shown as cover.

**Screenshots**
<img width="1085" alt="Screenshot 2019-12-11 at 07 40 21" src="https://user-images.githubusercontent.com/293355/70597776-828f9800-1be9-11ea-90cd-72c50fc98ae1.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 78.0.3904.108 (Official Build) (64-bit)

**Comment by znarf** [comment]
@Betree Crop data is: ```{"crop":{"x":-1814.2912211913506,"y":-4574.7602892083005},"zoom":0.46031677901744844}},```

**Comment by Betree** [comment]
I think indeed that the problem comes from https://github.com/opencollective/opencollective/issues/2471. Your image was uploaded, but it was out of the cropping zone (thus invisible).

> Do we have an issue to start serving background images from the images service?

We don't, a work was started in https://github.com/opencollective/opencollective-frontend/pull/2571/files but the full implementation required some more work.

I'm going to revisit that with a much simpler PR and I'll open an issue to document what's left to fix.

**Comment by mhulet** [comment]
Thanks @Betree @znarf 🙌
