### ISSUE TITLE
email and name field missing from organization creation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2713]
![Screen Shot 2019-12-12 at 2 51 28 PM](https://user-images.githubusercontent.com/5498878/70676102-ee5c2880-1cef-11ea-8753-c739458649c7.png)

There's nowhere to put the email or contact name in when creating a new org as a source of funds.

* How does the user get their receipt and notification of the contribution?
* How can they later log in and make changes or more contributions from that profile?
* How does the system know who to put in for the core contributors of that organization?

Regarding the last point, I just added funds on behalf of an organization and it's put me as the core contributor on their profile page. This is falsely giving the impression that I represent this organization. It's also made me an org admin, which is incorrect.

**Comment by Betree** [comment]
The current behavior has been designed like that. Because it adds you as the org admin, the current flow is indeed to create the organization then go to the members section and add another admin. This flow is definitely not suited for this use case and we should review it.

The problem if we just add an email input is that we'll probably end up with duplicate users, which is not great either (but arguably still better than what we have).

The "logical" thing would be to re-use a collective picker to pick or create the organization's admin inside the collective picker, but that may create a very confusing UX (CollectivePickerCeption).

I'd argue that this `Create new ...` thing should appear in a modal (rather than a small tooltip below the select) to give us space and to create a new context for the user, separated from the rest of the flow.

I think an input and/or updates to the existing design from @opencollective/design would be very valuable on this one.

**Comment by alanna** [comment]
Legally we have to provide a receipt when we receive funds so we need to associate the contact info here. I'm also uncomfortable showing up as the admin of all these organizations I don't actually represent.

**Comment by alanna** [comment]
This issue of needing a pattern for creating profiles is going to come up more and more because of the "submit on behalf of" feature in expenses and also when adding core contributors during Collective creation. We need some system for creating a profile, associating the name and email, and sending an invitation to that person to confirm they accept.

**Comment by Betree** [comment]
@xdamman your feedback is welcome here as you led the collective picker project

**Comment by Betree** [comment]
As discussed in Tuesday's call, we're going to iterate with simple email / name fields to unlock the feature. We'll iterate with a better solution later.

**Comment by Memo-Es** [comment]
We already have a pattern to create an organization on the fly, we could combine it with a pair of collective pickers in 2 different screens so it doesn't get confusing...
@Betree 

I attach a very rough representation of this:

Add funds | Create organization
------------ | -------------
![Add funds](https://user-images.githubusercontent.com/49539954/71224759-f8f06200-229b-11ea-9417-d47f39b47e90.png) | ![Create organization](https://user-images.githubusercontent.com/49539954/71224866-453ba200-229c-11ea-9f72-b19ceaebc6c5.png)

**Comment by Betree** [comment]
We could indeed re-use the create organization form designed for the contribution flow. The question is where to display it. If it were just me I'd open a modal when users click on `Create new organization` in the collective picker so that it creates a new screen (= new context). 

I can build that easily without the need for a proper design, but because having forms in modals is not a pattern that we use today I need your green light first.

I'm up for other proposals as well as long as we address this in a systemic way.
