### ISSUE TITLE
Not compliant with GNU LibreJS (i.e. FSF FreeJS)

### ISSUE THREAD

**Issue by sampablokuper** [opencollective/opencollective#272]
Please can the Open Collective website either:
- (ideally) not require the user to execute JavaScript; or
- (failing that) comply with GNU LibreJS as per the FSF's [FreeJS](https://fsf.org/campaigns/freejs) initiative?

Thanks!

**Comment by piamancini** [comment]
@clarete is this something you want to keep in your radar? otherwise will close for lack of activity

**Comment by clarete** [comment]
Unfortunately, I don't think we'd be able to attend this request because LibreJS isn't really compatible with our use of Webpack. The whole frontend is compiled into a huge file that will always be categorized as "NONTRIVIAL" by LibreJS.

Nevertheless, I still think it could be great to track the licenses of the packages that we use. A veeeery quick analysis of our API dependencies shows that from our 1386 dependencies (including different versions of the same package if they exist). From that 1072 are `MIT`, there's a bunch of `BSD`s and some very few GPL so most of it is libre software but almost none is copyleft.

I'll create an issue to verify what is the `*` in some licenses and why we depend on any proprietary licenses (Even Stripe is MIT) so I think we might actually be close to 100% free software as well!

Here's the breakdown of what we currently have in the API:

```
{'(BSD-2-Clause OR MIT OR Apache-2.0)': 2,
 '(GPL-2.0 OR MIT)': 1,
 '(MIT AND CC-BY-3.0)': 1,
 '(MIT AND Zlib)': 1,
 '(WTFPL OR MIT)': 1,
 'Apache-2.0': 23,
 'BSD': 9,
 'BSD*': 25,
 'BSD-2-Clause': 26,
 'BSD-3-Clause': 62,
 'BSD-3-Clause OR MIT': 1,
 'Custom': 1,
 'Custom: http://graphql.org/': 2,
 'Custom: http://graphql.org/swapi-graphql': 1,
 'Custom: http://linuxcommand.org/man': 1,
 'Custom: https://flowtype.org/': 2,
 'Custom: https://github.com/dominictarr/event-stream': 1,
 'Custom: https://github.com/douglascrockford/JSON-js': 1,
 'Custom: https://github.com/graphql/graphql-language-service': 2,
 'GPL-3.0': 2,
 'ISC': 109,
 'LGPL': 1,
 'LicenseRef-LICENSE': 1,
 'MIT': 1072,
 'MIT*': 24,
 'Public Domain': 1,
 'UNKNOWN': 2,
 'UNLICENSED': 1,
 'Unlicense': 2,
 'WTFPL': 1,
 'license': 1,
 'proprietary': 1}
```

I'll close this issue and then I'll create another one to trace what proprietary software we're using and why!

**Comment by sampablokuper** [comment]
@piamancini, thanks for following up on this.

@clarete, good to see that Open Collective is using almost entirely free software.

Thanks for explaining what you perceive to be the obstacle to compatibility with LibreJS. Perhaps users could be given an option to not be fed web-packed scripts, as a way around this?

Alternatively, how about the other approach I mentioned in the original post: not requiring JavaScript? It's certainly possible to *browse* https://opencollective.com without JavaScript, so you are already at least part of the way there. Maybe you are (almost?) all the way there? Is there any part of the Open Collective website whose reliance on JavaScript is so crucial that it is worth requiring your users to expose themselves to the security risks and ergonomic issues posed by JavaScript?

Thanks again.

@phated and @developit, why the thumbs down?

**Comment by clarete** [comment]
Hi @sampablokuper! Thanks for your interest in how we can make open collective more compliant with free standards.

> @clarete, good to see that Open Collective is using almost entirely free software.

And the software that isn't free is there by mistake! We'll get rid of it as soon as we figure out what's not free and where it's being used (probably dependencies of dependencies). 

> Thanks for explaining what you perceive to be the obstacle to compatibility with LibreJS. Perhaps users could be given an option to not be fed web-packed scripts, as a way around this?

Unfortunately, this isn't an option as well because the size of the scripts would get so big that it would slow down the experience of our users considerably. The amount of work `webpack` does to deliver small bundles built from lots and lots of lines of code is extremely important to how our website works.

> Alternatively, how about the other approach I mentioned in the original post: not requiring JavaScript? It's certainly possible to browse https://opencollective.com without JavaScript, so you are already at least part of the way there. Maybe you are (almost?) all the way there? Is there any part of the Open Collective website whose reliance on JavaScript is so crucial that it is worth requiring your users to expose themselves to the security risks and ergonomic issues posed by JavaScript?

I think that's not possible either.  The whole software (frontend and backend) is written in JavaScript. Offering a website without JavaScript means starting a brand new software (which isn't realistic since we invested 2+ years of effort on the current codebase).

Although I really want to improve our compatibility with FSF standards as much as possible, I think this one is a really tough one. LibreJS doesn't account for JavaScript websites that are already libre. Although we do execute complex scripts in our users browsers, our users have total freedom to read, audit and patch every single line of code that is executed in their browser and in our servers.

If you still think this isn't enough, there might be another approach for users that don't want to execute JavaScript. We're in the process of opening our API for the public. With that in hand, users will be able to access our information without relying on our frontend.

**Comment by sampablokuper** [comment]
@clarete,

> The whole software (frontend and backend) is written in JavaScript. Offering a website without JavaScript means starting a brand new software (which isn't realistic since we invested 2+ years of effort on the current codebase).

Well, the backend wouldn't necessarily need to be changed at all; and the front-end would just need graceful degradation of any remaining functionality that doesn't work with JavaScript disabled. So, hopefully it's not as much work as you fear it is :-)

Put differently: I didn't say, "without JavaScript", I said, "[that does] not require the user to execute JavaScript" (i.e. in their browser). Quite a big difference ;-)

Anyway, thanks again for the consideration you have given to this. Perhaps one day you will find yourself regularly using uMatrix or NoScript or TBB, and will feel independently motivated to minimise dependence upon user-run JavaScript :-)

**Comment by ncorder** [comment]
> I'll close this issue and then I'll create another one to trace what proprietary software we're using and why!

I'm glad to hear you all are focusing on free/libre software! : D

Would you be able to link to that issue here as well?

**Comment by yantar92** [comment]
> I'll create an issue to verify what is the `*` in some licenses and why we depend on any proprietary licenses (Even Stripe is MIT) so I think we might actually be close to 100% free software as well!

Is the JS blob loaded by stripe also MIT-licensed? I was unable to find the JS sources on their github page.
