### ISSUE TITLE
New Expense Flow Feedback

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2725]
We're working on a big upgrade to the expense submission process, and we'd like feedback from the community.

The new expense flow will enable useful new features like:

* Receipt batches: Upload a bunch together to reduce data entry.
* Automatic invoices: No attachment needed - it saves your details.
* Submit on behalf: File an expense for someone else.
* Expense tags: Track projects or categories any way you want.
* Status changes: Names and dates for edits, approvals, payments, rejections, etc.
* Improved comments: fully featured discussions on expense pages.

Here are some designs we've done so far:

## Select expense type

Make it much clearer whether you're submitting a receipt or an invoice, as these are different in many ways. Receipts are for getting paid back for a purchase already made, while invoices are for charging for your time, getting paid in advance, or if you don't have a receipt.

<img width="757" alt="Screen Shot 2019-12-15 at 2 39 33 PM" src="https://user-images.githubusercontent.com/5498878/70856950-658cf900-1f4a-11ea-91a6-888f07250fff.png">

## Submit single receipt

<img width="754" alt="Screen Shot 2019-12-15 at 2 40 04 PM" src="https://user-images.githubusercontent.com/5498878/70856956-91a87a00-1f4a-11ea-9aa4-d09cf5ed6f19.png">

## Submit multiple receipts
We want to cut down on repetitive data entry as much as possible, so it's more worthwhile to submit even small expenses. We're calling this a `receipt batch`. Batches can also be paid out in one transaction instead of a seperate payment per receipt, which should reduce transaction fees and admin overhead.

<img width="832" alt="Screen Shot 2019-12-15 at 2 41 00 PM" src="https://user-images.githubusercontent.com/5498878/70856966-c61c3600-1f4a-11ea-9767-71fde32b4c57.png">

## Submit invoice
Instead of requiring you to create a seperate invoice document and attach it, users will put the invoice details directly into the expense form. 

This will allow us to save your details for next time, so if you submit an invoice every month for example, you'll just have to type in the description of what you're charing for and the amount and everything else will be there already. 

(If you want to include an attachment for any reason, you still can as a comment).

<img width="764" alt="Screen Shot 2019-12-15 at 2 42 08 PM" src="https://user-images.githubusercontent.com/5498878/70856972-fb288880-1f4a-11ea-98d3-17a23c0c201c.png">

![Screen Shot 2019-12-15 at 2](https://user-images.githubusercontent.com/5498878/70856984-4d69a980-1f4b-11ea-9a3f-d6b79d7f31f4.jpg)

## Payout methods
Fiscal hosts can define the payout methods they use, and expense submitters can select from them. The system will save your payout details for that method, such as your paypal address or bank transfer instructions.

<img width="827" alt="Screen Shot 2019-12-15 at 2 41 38 PM" src="https://user-images.githubusercontent.com/5498878/70856988-75590d00-1f4b-11ea-93d3-66bbe50f038b.png">

## Clear privacy
A lot of users are concerned about their private info, such as address, email, and bank details, becoming public, since Open Collective emphasises transparency. It's always been the case that these details are kept private and only admins can see them, but we're making that way more obvious in the new design to put minds at ease.

There are also very clear "public notes" and "private notes" boxes, so you can decide what details to share publicly and what to keep private

<img width="963" alt="Screen Shot 2019-12-15 at 3 01 05 PM" src="https://user-images.githubusercontent.com/5498878/70857001-c10bb680-1f4b-11ea-9ec2-5ee38948db6b.png">

## View Expenses
Improved view of a Collectives expenses, where you can filter by status and tag. The admin view of this screen will also have action buttons like `approve` and `reject`.

<img width="834" alt="Screen Shot 2019-12-15 at 3 05 10 PM" src="https://user-images.githubusercontent.com/5498878/70857033-6e7eca00-1f4c-11ea-8690-d9d925bdbbe9.png">

## Expense narrative
Fully featured discussion threads, with clear indications of the status changes an expense has had, including when and who. For example, when an expense was approved, edited, rejected, etc. There will also be the option to post private comments to answer questions about payment details and confidential matters.

<img width="585" alt="Screen Shot 2019-12-15 at 3 06 56 PM" src="https://user-images.githubusercontent.com/5498878/70857050-c87f8f80-1f4c-11ea-8783-6969ae788b18.png">

## Rejection reasons
Say why you're rejecting an expense so the submitter as an explanation and others can see the Collective's policies in action.
<img width="560" alt="Screen Shot 2019-12-15 at 3 08 59 PM" src="https://user-images.githubusercontent.com/5498878/70857055-e77e2180-1f4c-11ea-9668-120dec47eb06.png">

## Delete expense
For expenses submitted in error, spam, etc.

<img width="557" alt="Screen Shot 2019-12-15 at 3 09 59 PM" src="https://user-images.githubusercontent.com/5498878/70857066-041a5980-1f4d-11ea-8004-a886b5e84adb.png">

## Submit on behalf of
We don't have a mockup for this one yet, but it's an important improvement that will let you submit an expense to be paid out to someone else. This means you can help out collaborators who don't like paperwork, or submit on behalf of a vendor who isn't signed up to Open Collective yet and make it easier for them. The person will get an invitation to accept/confirm the expense and enter their payment details (if they don't already have them saved to their profile), and the expense will be correctly attributed to their profile instead of the submitter's (for accurate records, tax reporting, etc).

## Clickable prototype
You can check out some [clickable mockups here](https://www.figma.com/proto/KinuveYf4WUlRIXzMTnmIsmO/OC.COM-XX1-%2F-Lab?node-id=4404%3A383&viewport=662%2C-149%2C0.15480825304985046&scaling=scale-down).

**Comment by xdamman** [comment]
Here is my feedback. Hope it's useful.

## Select expense type
- Expense policy (singular) should be above the expense form. You first need to see that before you know if you can submit that given expense
- Expense title: might be easily missed. All the visual attention is on the expense type. I’d only ask for the expense title after selecting the type. 
- As a general UX principle, it’s weird to have such choice and then tabs to switch between the two. Either you can skip that first choice and go straight to the most likely option (because it’s easy to switch), or if you want to keep it, there should be a smaller back button instead of the big tabs
- I’d move the title of the expense below the type of expense. 
- I’d move who is going to be reimbursed below the actual expenses. It’s the equivalent of the payment method used to pay a receipt, you first have the details of all the items with their price, and then you choose how you are going to pay for them, i.e. here are all the expenses, and this is who should be reimbursed.

## Submit invoice
- Same for submit invoice, start with the list of things. To be consistent with the interface for receipts, I’d also allow the user to have multiple line items with the possibility to attach a picture, i.e. here are all the things that I’ve done. 
- I’d also move the payee to the bottom for the same reason. Please pay all those things to that vendor (most likely: "my individual company", "me as a freelancer"). Another reason for this being that this information will be recorded once and then people will only have to edit every time the list items. So better to put at the beginning the info that needs to change. Alternatively, you can make a more wysiwyg version. 
- The supporting documentation should be public. 
- Not a fan of the design of public/private note. It’s not much needed anymore as there is already a public title and private instructions depending on the payout method. I’d rather see the default comment box after submitting the expense to add more details with the option to make a private or public comment. 

## Payout methods
- It’s weird to have public and private notes there. The host should only have to define a payout method name and (public) description. Then the submitter of the expense/invoice provides custom private instructions (that will be saved for later use)

## View expenses
- Would be great to have a view with a tag selected.
- It’s weird to see "Invoice id". Should be "Expense id" to be generic and consistent.
- There is an interesting analogy between a batch expense and an order that is part of a recurring schedule (aka subscription). It might be worth showing what a "orders" page may look like to identify those similarities and ensure a consistent experience.

## Expense narrative
- Should be more "Expense page" no?
- "Expense history" should be more "Expense thread" or "Discussion" no?
- It feels like actions (reject/delete) are basically comments with an action. 

## Submit on behalf of
- isn’t that covered already by defining who is going to be reimbursed at the beginning of the submit expense flow?

**Comment by alanna** [comment]
Thanks @xdamman that's helpful! @Memo-Es see above.

> The supporting documentation should be public.
Normally supporting documentation includes private information such as payment details and people's addresses, so I don't agree with this. I think users should be able to post attachments as comments and decide whether it's private or public.

> Expense narrative
This is just a name I gave to this section for the purposes of this post. It's not going to appear anywhere. The feature will be expense pages.

> Submit on behalf of
Yes this is about selecting someone else besides yourself to be paid. It's mentioned separately because it's a very different function than getting yourself paid. We're missing designs for how that flow will look.

Everything else I agree with!

**Comment by Betree** [comment]
@alanna with the new expense flow implemented, we should maybe close this one?
