### ISSUE TITLE
Tax form submitted by user but not recognised as received

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2726]
Tax form completed by user and showing as completed in HelloWorks, but not being marked as received in our system. Multiple users reporting.

Two examples:
* https://opencollective.com/smelukov 
* https://opencollective.com/alyssa-wright

Both these users have definitely completed the form through HelloWorks, but the legal document status in Forest is showing as "requested" not "received".

**Comment by znarf** [comment]
Just investigated and it's related to https://github.com/hellosign/helloworks-nodejs-sdk/issues/9

```
Dec 09 19:19:23 opencollective-prod-api app/web.1: info: Completed Tax form. Metadata: {"email,example@gmail.com":"1","userId,46107":"0","year,2019":"2"}
Dec 09 19:19:23 opencollective-prod-api app/web.1: error: Tax Form: could not find user matching metadata {"email,example@gmail.com":"1","userId,46107":"0","year,2019":"2"}
```

While this is being troubleshooted, we'll need to re-conciliate by hand.

**Comment by znarf** [comment]
Actually, Piet might have been right that this is coming from the SDK (at input time, not output).

We accidentally reverted to HelloWorks version instead of Piet in https://github.com/opencollective/opencollective-api/commit/8f032163ca0de8f04233ef18dc3cbe77a169618c (It's signed by me, but it's the result of an automated script, not sure what went wrong). This is when we started to have the issue again.

I'm writing a patch to handle malformed metadata and we'll keep the official SDK.

I'll follow up on Helloworks side to make sure this is addressed in the SDK or in the API.

**Comment by alanna** [comment]
Thanks @znarf - are there any tests or checks we could put in place so that in the future if changes are made to the tax form system we can ensure it's not broken? This incident caused problems because we were not even aware the forms weren't being received correctly for several weeks.
