### ISSUE TITLE
Open Collective code hosting currently fails GNU Ethical Repository Criteria Evaluations

### ISSUE THREAD

**Issue by sampablokuper** [opencollective/opencollective#273]
Please could Open Collective migrate its entire code-base and bug tracker to a code hosting and bug-tracking service that does not _fail_ the [GNU Ethical Repository Criteria Evaluations](https://www.fsf.org/news/gnu-releases-ethical-evaluations-of-code-hosting-services)?

GitLab might be a reasonable compromise:
- it _[passes](https://www.gnu.org/software/repo-criteria-evaluation.html)_ (albeit imperfectly) the GNU Ethical Repository Criteria;
- it supports Git as a first-class DVCS;
- its interface is quite similar to GitHub's;
- it has a large and active user base.

Other possible hosts, albeit lacking some of those features, so maybe not currently such a good fit for Open Collective: 
- [NotABug](https://notabug.org)
- [GNU Savannah](https://savannah.nongnu.org/)

Thanks!

**Comment by hbetts** [comment]
Many of the `A` level criteria feel inappropriate for a non GNU project, however, it would be encouraging to see the Open Collective group consider the transparency of the platform on which they maintain their repositories.

**Comment by piamancini** [comment]
cc / @clarete If this is something you want to look into, otherwise please close until it becomes a priority.

**Comment by sampablokuper** [comment]
@piamancini, if the ethics of openness are a priority for Open Collective then this is already a priority, surely.

**Comment by clarete** [comment]
That's unfortunately a hard one as well. We currently rely on Github for more than just hosting code. We have our wiki and our issue tracker data there. Although it's possible to migrate that data to other places, the only alternative we realistically have is Gitlab (neither Savanahh nor NotABug provide all the features that we use from Github). That would take a lot of work and would only bring us from F to a C in the ethical evaluation. I'm not sure if it's worth the effort.

Another huge downside of leaving Github is to lose engagement from users that currently use it. and since we do accept support requests via other types of communication like Email, users aren't necessarily forced to use Github's interface.

I don't think this compromises the openness of Open Collective as a project because all the information and code we create is publicly available in multiple channels.

I do agree that it'd be nice to allow users to access the content we have hosted on Github more conveniently using tools that are completely free thought.
