### ISSUE TITLE
Enable recurring bank transfer contributions (SEPA)

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2734]
We are starting to build more features for bank transfer as a payment type and welcome hosts who don't use Stripe and credit cards. 

We have the functionality to support one-off transactions via bank transfer. It works by sending the contributor an email with wire transfer instructions, and creating a pending order for the host admin. When the funds arrive, they mark the pending order as paid.

Should we also enable recurring contributions via bank transfer? 

This depends on users to properly set up the recurring funds transfers, which they don't always do reliably. Are there other possible problems?

**Comment by xdamman** [comment]
That would be really cool. I also have a demand for it from European collectives.
It's quite easy with mobile banking apps over here to set up such recurring donations.

The best way to handle it would be through Stripe's support for SEPA payments (but it's only for Europe, but it's a big market).

The more versatile way that doesn't depend on Stripe would be to turn the current implementation into a recurring one. It could create every first of the month a new pending order that the host has to reconcile.

There are two cases to handle: 
1- The donor has set up an automatic transfer with their bank. In that case there is no need to remind them to make the payment. Just to confirm when it has been received (reconciled).
2- The donor is manually making the payment (e.g. for a rent in a community house). In that case, we should automatically send an email reminder on the first of the month with the wire instruction. 

If it's recurring, the communication on the bank transfer has to remain the same. So we can't really create a new pending order every time. Or we do, but they all reference the same `SubscriptionId`. Might be easier. But then we need to use that instead of the `OrderId` as a way to reconcile payments.

We also need to think about how to cancel them. 

It's a cool project that is well contained. Maybe a good candidate for a bounty projet?

**Comment by alanna** [comment]
This feature is requested by users, and as we already have most of the functionality built, I think we should do it. In my mind, this is how it would work:

* Payer sets up contribution and selects recurring and bank transfer
* Pending order is created as normal
* System emails payer the bank instructions as normal
* System emails host admin the "has $x arrived for $y?" notification as normal
* One month or one year later, the system re-sends the instructions to remind them to pay
* Another pending order is created
* System emails host admin the "has $x arrived for $y?" notification again
* Repeat

**Comment by alanna** [comment]
We have someone in NZ who wants to launch a large-scale campaign on OC but really needs this recurring bank transfer function. 

@Betree @BenJam or whoever might be able to, can you look at my description in the comment above ^ and let me know if this would be as easy to implement as I think? And if so, would it be at all feasible to do in the short term? They want to launch in a week and I said that's not feasible, but I want to get some kind of indication.

One thing that came out of the discussion I had with them today is *no crowdfunding platform offers recurring bank transfers* as a payment option. Because OC already has all the tooling for bank transfers (ie the process of setting up a pending order, notifying the payer of the instructions, and enabling the admin to confirm receipt of funds), we have a unique opportunity to serve markets like NZ where bank transfers are much more common than credit card payments and people really value not paying payment processor fees on transactions. I think other places in Europe are similar.

**Comment by alanna** [comment]
Noting that we continue to get requests for this feature from NZ Collectives, as recurring bank transfer is a very common way to pay here.

**Comment by bnjmnjns** [comment]
Would like to add another vote for this feature. NZ has been mentioned frequently but I'd add that in some european countries it is relatively common to not own a credit card so bank transfers are preferable. Equally it causes a lot of confusion that recurring payments are allowed for card payments. 
The proposition made is this comment looks good to me too. As both a frontend developer and OC user, don't hesitate to reach out if there's something I can do to help move this along https://github.com/opencollective/opencollective/issues/2734#issuecomment-916493163

**Comment by mkurz** [comment]
Please prioritize, thanks! See https://github.com/opencollective/opencollective/issues/5330#issuecomment-1097852518

**Comment by Betree** [comment]
@mkurz As a workaround for the use case you shared, could they use PayPal? It is normally possible to use bank accounts as the source for payments when using PayPal.

**Comment by Betree** [comment]
> Alright, I will reach out to the donor and ask if that will work for them. I keep you posted.

Please do! Also to make it clear, the workaround with PayPal doesn't invalidate this issue, we still want to have bank transfers directly integrated into the website.

**Comment by BenJam** [comment]
Following the conversation here I think the main idea is to implement https://stripe.com/docs/payments/sepa-debit as the coverage (countries supported) has a good overlap with our biggest areas and areas of growth (US, EU, NZ).

**Comment by BenJam** [comment]
just FYI we're exploring support through Stripe Checkout/Elements right now in https://github.com/opencollective/opencollective/issues/4927

**Comment by mkurz** [comment]
@kewitz Why not? It is: https://opencollective.com/playframework
However the case where we would have needed sepa direct debit was solved different, so not sure if someone will make use of it.

**Comment by kewitz** [comment]
@mkurz just noticed your collective is hosted in the US. In this case, it would only enable ACH for now.

**Comment by mkurz** [comment]
Got it. You can still enable ACH for our collective, if it does not crash it :wink:

**Comment by BenJam** [comment]
closing as we have recurring contributions through stripe payments (ACH/SEPA) enabled. 

contributions in the local country we'll deal with as a separate issue.
