### ISSUE TITLE
Gulp collective custom styling no longer applied

### ISSUE THREAD

**Issue by phated** [OpenCollective/OpenCollective#274]
It seems the page has been reorganized.  Was this an accident or conscious change?

**Comment by asood123** [comment]
We simplified pages a bit - there were too many places for repetitive information and the financial transparency aspects were hidden too far below. The new collective page has one single field (description in About Us section) where collectives can add whatever information (and formatting via markdown). What do you think?

Custom styling shouldn't have broken in this change. I see that the link on the hero image is now showing up in blue, instead of white. Is there any other custom styling that broke?

**Comment by phated** [comment]
All of the green buttons had custom styling to match our color scheme.

**Comment by asood123** [comment]
ah yes, I'll fix that.

**Comment by asood123** [comment]
fix here: https://github.com/OpenCollective/opencollective-website/pull/594. Should be deployed later today.
