### ISSUE TITLE
Docs are missing information about incognito contributions

### ISSUE THREAD

**Issue by gallexi** [opencollective/opencollective#2742]
Hello 👋 

I notice that the docs for OpenCollective don't have any reference to incognito contributions. As a user I'd love to know what happens when I contribute while incognito, specifically whether this hides my name from everyone (so the contribution is made completely anonymously) or just hides my name from the public view (and the collective admins can still see my name).

I poked around in the OpenCollective frontend, and noticed that there is a message detailing the behavior: https://github.com/opencollective/opencollective-frontend/blob/21f152ef6496dee351a617db3ef7730ca40b7a9c/components/faqs/ContributeAsFAQ.js#L35

Perhaps this message should be mirrored in the docs? If so, happy to open a PR to add it!

**Comment by Betree** [comment]
Good catch, there's indeed 0 result  when searching for `incognito` on https://docs.opencollective.com.

> Perhaps this message should be mirrored in the docs? If so, happy to open a PR to add it!

We'd be happy to merge such PR, I suggest adding a new page in `Financial contributors`, maybe @contraexemplo has a better suggestion.

**Comment by contraexemplo** [comment]
Hi @gallexi! 👋 Thank you for opening this issue. Please correct me if I've missed anything—does this list includes all info you would like to see in a page about this feature? 

- What are incognito contributions.
- What are the effects of using such feature—what does it hide, what does it mean for collectives, etc.
- How to enable it.

You are welcome to open a PR on opencollective/documentation about this. And if you wish, we can work on this together!

Your suggestion is spot on, @Betree — that's the right section.

**Comment by gallexi** [comment]
Hi @contraexemplo! Yes that list of info sounds perfect, thank you!

I'll take a try at a PR in opencollective/documentation tonight, and cc you on it. Thank you!

**Comment by gallexi** [comment]
Whoops, I have more questions 😅 

@contraexemplo I started thinking about where exactly to put the info about incognito contributions: as a new page called "incognito contributions" (doesn't feel quite right, because it doesn't seem to be on the same level of importance as "payments" or "website badge"), or under the FAQ (where I originally searched for it, because the UI copy told me to), or somewhere else (like perhaps the ["contribute as"](https://docs.opencollective.com/help/financial-contributors/payments#contribute-as) section of the payments page). I'm thinking perhaps the third one is the best place for it, as this is most related to "payments" and who you're "contribut[ing] as". But, perhaps we might have too much information to add for it to fit nicely in that sub-sub-sub-section? What do you think? 

Thanks!

**Comment by contraexemplo** [comment]
@gallexi Having questions is great! You are encouraged to ask as many as you need. :relaxed: 

I think it's a good idea to add a question related to that information under the FAQ since it was where you originally searched for that info—that's a good indication that other users may do the same. And your final suggestion is spot on, that's definitely a part of the financial contribution flow and would be a better fit for `Payments > Contribute as`.

Also, since the `Suggesting changes` page needs to be updated a bit, I need to tell that if you prefer to work on changes by forking our repository, you should fork the `v2` branch (which is our main one) and use it as a base for pull requests. If you decide to use the **Edit on GitHub** button to submit a patch, GitBook will point you to the right branch.
