### ISSUE TITLE
Receipt sent to incognito contributors should list the user's name

### ISSUE THREAD

**Issue by gallexi** [opencollective/opencollective#2743]
**Describe the bug**
Users who contribute as incognito will get a receipt that says "Bill to: Incognito". For the receipt to be useful for proving a user contributed, it should probably list the user's actual name.

**To Reproduce**
1. Make an incognito contribution to a collective
2. Receive email with receipt
3. View receipt

**Expected behavior**
Receipt should contain user's name

**Screenshots**
![Screenshot showing "Bill to: Incognito"](https://user-images.githubusercontent.com/17116584/71064398-00e5c000-213d-11ea-90b5-111862478572.png)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS 13.2.3
 - Browser: Safari
 - Version 13

**Additional context**
The use case for this is showing to other specific folks that I did pay, without revealing my name publicly. 

Thanks!

**Comment by Betree** [comment]
Thanks for reporting this issue, receipts should always include the user name so that's definitely a bug!

**Comment by bolariin** [comment]
From what I can see, I'm not sure you can get the user's actual name through GraphQL because of https://github.com/opencollective/opencollective-api/blob/116cdae0f79240757a54d96c56ee3624896f5607/server/graphql/v1/types.js#L1551

**Comment by Betree** [comment]
@bolariin that's indeed probably the problem here. However this GraphQL endpoint normally returns the user info if the user is an admin, so we need to check the following:
- That `req.remoteUser.isAdmin(incognitoProfile.id)` returns true when `incognitoProfile` is the incognito profile of `req.remoteUser`.
- That the invoice service properly send the authorization header to the endpoint when it makes the GraphQL query. This endpoint used to be unauthenticated (because we consider the UUID as private, so that was a way to protect it by default) and it's possible that we didn't update the request in the invoice service properly.

**Comment by Betree** [comment]
Fixed by @bolariin in https://github.com/opencollective/opencollective-invoices/pull/285. Will be deployed soon
