### ISSUE TITLE
Host dashboard: display errors above buttons

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2746]
<img width="1037" alt="Screen Shot 2019-12-18 at 12 12 14 PM" src="https://user-images.githubusercontent.com/3671070/71088858-cb25f300-219f-11ea-9cfe-9d4fc8faf43a.png">

**Comment by Betree** [comment]
This will be improved when we deploy https://github.com/opencollective/opencollective-frontend/pull/3186. It's very similar to what's reported in #2567.

**Comment by znarf** [comment]
@Betree Now that https://github.com/opencollective/opencollective-frontend/pull/3186 is merged seems what's left is moving the error message. Is that correct?

**Comment by Betree** [comment]
Yes, the error message doesn't break the layout as it used to but it still appears between the buttons. It should be centralized in the parent, and displayed **above** them, ideally in a `MessageBox` to be consistent.

**Comment by znarf** [comment]
A $200 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by brymut** [comment]
Hi, I'd like to take a look at this while I wait for a review on a pull request.

**Comment by brymut** [comment]
So far, I have been able to come up with the following solution, passing error messages from state gathered from failed props.refetch() or the Record as paid and Pay with paypal. Hopefully as expected.


<img width="542" alt="Desktop solution" src="https://github.com/brymut/github-gifs/blob/master/opencollective_opencollective_2746(1).jpg?raw=true">

<img width="542" alt="Mobile solution" src="https://github.com/brymut/github-gifs/blob/master/opencollective_opencollective_2746(2).jpg?raw=true">

**Comment by Betree** [comment]
@brymut looks good to me! A `withIcon` on `MessageBox` and a small margin-bottom (`mb={2}`?) would be perfect

**Comment by Betree** [comment]
:trophy: This issue is now completed by @brymut 

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:
