### ISSUE TITLE
Collective page: review sections for inactive collectives

### ISSUE THREAD

**Issue by Emekaborisama** [opencollective/opencollective#2758]
**Describe the bug**
I can't find my event on my org front page. i added slash event and i saw all my events

**To Reproduce**
1. Go to 'https://opencollective.com/ai-festival-nigeria/events'
2. Go to https://opencollective.com/ai-festival-nigeria/
3. The events don't appear there

**Expected behavior**
At least I should be able to see my added events

**Screenshots**
![Capture](https://user-images.githubusercontent.com/24501919/71264422-eeb08100-22f8-11ea-8526-84340381bf9e.PNG)

**Desktop (please complete the following information):**
 - Browser [Chrome]

**Comment by Betree** [comment]
Hello @Emekaborisama, events are normally displayed on the collective page, in the contribute section. The reason why they're not showing up for you right now is because your host (https://opencollective.com/sarapisorg) hasn't approved your collective yet. As soon as the host approves you, your events will show up.

The events page you're referring to (https://opencollective.com/ai-festival-nigeria/events) is a widget and is not meant to be visited directly.

**Comment by Betree** [comment]
We should display the events of inactive collectives on the collective page. The contribute tiers on the other hand should not be displayed, so to solve this issue:
- [ ] If collective is inactive, don't show tiers
- [ ] If collective is inactive, still show events

Careful, events for collectives with pending applications may be innactive as well. We may need to use the `includeInactive` graphql param.

**Comment by Emekaborisama** [comment]
I applied for Open Collective 501 to be my host but they request to see our
community previous events

**Comment by znarf** [comment]
I think Events are skipped on purpose, for the same reason as tiers. We don't want people to try to get tickets if the transaction can't be processed. We can reconsider.

**Comment by Betree** [comment]
@znarf As long as the tickets section is hidden from the event page, I'd say it's fine to list it in the collective page. I've added `Hide Tickets section if the event is not active` to the specs for this issue.
