### ISSUE TITLE
Contribution flow: small improvement with wording to increase conversion

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2780]
Picture this: like 99.99% of people on this planet, you've never heard of Open Collective. You don't have an account. But you did hear about #FridaysForFuture (who hasn't?).

You want to support them financially, and then you click to donate and this is the screen you see:

![](https://d.pr/free/i/6SgneK+)

I don't have numbers but I'm sure that this screen is probably pushing a lot of people away.
People would think: I don't have an account and I don't want to create one.

So we know that the best solution is to move this step at the very end of the process. 

In the meantime, I'd suggest a quick fix: 
Let's default to the create account view with some wording tweaks:

![](https://d.pr/free/i/sI4us5+)

I'd also consider moving the email input after the first name and last name and removing the "receive our monthly newsletter". At this stage, people (potential donors) have still no idea what Open Collective is, what this newsletter is about, etc.

Thoughts?

**Comment by piamancini** [comment]
I like it. Makes sense and it's a good improvement without a lot of effort.

**Comment by xdamman** [comment]
Cool. Here is a more accurate version. 

![](https://d.pr/free/i/JWg5UO+)

@Betree @znarf can one of you take this on or dispatch?

**Comment by Betree** [comment]
Related: #2286 

Sounds like a very good idea to me.

**Comment by Betree** [comment]
We can (should) also merge first name and last name as discussed recently. 

I don't especially agree with the removal of the checkbox for the newsletter because I don't think anyone will be slowed down or blocked by this, it's very common to have that on signup forms and there's no action required on user side (I personally never check them). On the other hand, it can be damaging if people who would normally check it because they're interested by Open Collective don't find it anymore.

About the wording: do we really want to use `Donate`? ping @alanna

**Comment by alanna** [comment]
I think this is a good idea.

We should say "contribute" as that's the term we've agreed to use.

Also please keep the newsletter opt in. I think there's a project that needs to be done about flows for people to opt in to Collective updates vs Platform updates, but until we take the time to properly sort that out, we should just stick with the current functionality. Otherwise we'll get into the situation we had before where we accidentally removed the ability to sign up for the newsletter completely.

**Comment by Betree** [comment]
Question: regarding the fact that it's now possible to contribute as incognito, shouldn't we make the `Full name` field required to comply with KYC?

![image](https://user-images.githubusercontent.com/1556356/71966420-d221ad80-3201-11ea-84ed-634a1f74a29f.png)

**Comment by znarf** [comment]
We're all aware that people will land on the "Account Created - Please check your inbox" screen and will need to go to their inbox before moving forward?

> @Betree @znarf can one of you take this on or dispatch?

It's difficult to do it now based on our current priorities. We can add a bounty once the specs are settled and clear.

**Comment by Betree** [comment]
@znarf I actually started implementation in https://github.com/opencollective/opencollective-frontend/pull/3280, I wanted to internationalize the component and fix some design mismatch and took the opportunity. I haven't tackled the part that are still unclear tho.
