### ISSUE TITLE
Contributors can't download PDF receipt

### ISSUE THREAD

**Issue by mallowigi** [opencollective/opencollective#2783]
**Describe the bug**
My contributors are not able to download the PDF receipt from the mail sent to them

**To Reproduce**
I haven't tried myself but one of my contributors forwarded me the mail sent to them thanking them for their donation. And indeed if I click on the link to download a PDF receipt of the donation, I am greeted with 
"Internal Server Error: Not authorized to access /material-theme-jetbrains/transactions/xxxxxxxxxx/invoice.pdf. Please provide an authorization header or an app_key."

**Expected behavior**
Be able to download the receipt

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 49

**Comment by Betree** [comment]
Hi @mallowigi, thank you for reporting this issue.

This endpoint previously wasn't requesting authentication. It was protected by the fact that transaction's `uuid` are private and non-predictable.

We've however enforced the security of this endpoint by requesting authentication, which was a requirement - among others - for the service to generate incognito invoices properly (because we need to check that users can access these private info, #2743).

My suggestion would be to link to the user's transactions page instead, where users can download receipts directly.

@mallowigi if your contributors need their invoice asap, a workaround is for them to go to https://opencollective.com/USERNAME/transactions (`USERNAME` must be replaced). They'll be able to download the receipts from there.

**Comment by mallowigi** [comment]
I got word from my customers and it appears e problem has been resolved

**Comment by Betree** [comment]
Well actually the underlying issue is real, I was able to reproduce :slightly_smiling_face:
