### ISSUE TITLE
Confusing error message when approving Collective that has since applied to another host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2785]
[This Collective](https://opencollective.com/ai-festival-nigeria) applied to OSC. But when I clicked "approve" from the email notification, I got this error:

![Screen Shot 2020-01-09 at 3 09 23 PM](https://user-images.githubusercontent.com/5498878/72031690-0a081e00-32f2-11ea-87e8-c760c678b816.png)

When I looked at the Collective page I realised they have since decided to apply to another host and are in pending status with them (Sarapis). I think I got that error because I'm not admin of the other host.

However this is confusing because it references "opensource" in the error, which I am an admin of (by the way it should should the host name not the slug here anyway).

In this scenario, the error should be "This Collective has decided to apply to another host and therefore could not be approved." or something like that.

**Comment by znarf** [comment]
Some context, the URL you landed on was `https://opencollective.com/opensource/collectives/74101/approve` and was generated on December 18th.

However, since ttps://github.com/opencollective/opencollective-api/pull/3059, for security reasons, we don't do this kind of actions anymore, we're just directing the user to the Host Dashboard.

While we'll still have Collectives changing hosts before approval, this precise situation and the error message should not happen in the future.
