### ISSUE TITLE
Can't edit an organization after creation

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2789]
**Steps to reproduce**

- Create an Organization
- Wait to be redirected on the Organization page

**Current Behavior**

- No ability to edit the settings
- Takes two browser refresh to be visible

**Expected Behavior**

- Immediate ability to edit the settings

**Possible Fix**

- It's likely that the cache for the `LoggedInUser` needs to be refreshed so the Frontend knows the authenticated user is an admin
- It seems to work when creating a Collective and not an Organization, we can get inspiration from there.

**Comment by znarf** [comment]
A $200 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by JoyLubega** [comment]
hey @znarf  I want to fix this.

**Comment by znarf** [comment]
@JoyLubega All right, initial time limit is 1 week. This can later be extended if there is demonstrable progress. Good luck!

**Comment by Betree** [comment]
:trophy: This issue is now completed by @JoyLubega 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
