### ISSUE TITLE
Design a cover button and flow to let anyone pay for an approved expense

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#279]
Currently:
1. Alice files an expense on webpack for $37.50 for stickers
2. Sean (who's a member of the Webpack) approves the expense
3. Pia (who's the host for webpack) pays $37.50 from webpack collective to Alice.

We want to support an alternate flow (in addition to the above flow):
1. Same as above
2. Same as above
3. Denise can go to webpack collective and "Cover" the outstanding expense that Alice filed. 

That means, instead of host paying it out of collective, we'd create a one-time donation for $37.50 (+ fees), charge it and then payout Alice's expense.

**Comment by asood123** [comment]
@erickrico let's use this issue to design flow

**Comment by erickrico** [comment]
Ok, i merged this task with the "request money" one since they both share screens,  

## Cover expense + Raise funds

![screenshot 2017-01-11 13 21 15](https://cloud.githubusercontent.com/assets/18429104/21862976/2c97dce8-d801-11e6-8cc2-b073d9035049.png)

Note 1: the "cover expense" btn only appears for visitors when the owner have previously approve of it.

Note 2: the owner will have a new CTA to create this "campaign links" since "request money" seems to aggressive/demanding.

## This is how it looks like on the other end

![screenshot 2017-01-11 13 20 46](https://cloud.githubusercontent.com/assets/18429104/21863120/c162adf8-d801-11e6-88cd-94a5e5e3c8f7.png)

i added a couple social links to make it a little easier to get the campaign going


i still have to solve some scenarios but this is the main idea

**Comment by xdamman** [comment]
I like the idea of the banner for logged in user to create a link.

Design wise:
Why is the "raise funds" (not rise) with shadow and not the other one?
I feel like it breaks the flatness of the page, don't you think?

Also, I feel like there are a lot of different styles on this last screen. Some titles are uppercase, in black, or gray, some titles are not in uppercase, etc. Shouldn't we simplify?

**Comment by erickrico** [comment]
i have 2 options, talking with aseem we figure that being consistent with the buttons on the email collective owners get when a expense is submitted would be a good approach, i made the exercise and believe the colors used there are way to strong for our current color palette and everything looks like a CTA

## Op. 1 Email Buttons example

![screen shot 2017-01-24 at 4 37 12 pm](https://cloud.githubusercontent.com/assets/18429104/22269992/5ea7ef64-e253-11e6-9b75-18a4cb3b1445.png)

![screen shot 2017-01-24 at 4 36 27 pm](https://cloud.githubusercontent.com/assets/18429104/22270004/6830c8bc-e253-11e6-8893-acfde634ab64.png)


based on this i propose a slightly different solution, stick to our current color scheme, add red to our palette (for labels like reject, error, etc) 

## Op.2 
 
![screen shot 2017-01-24 at 4 29 09 pm](https://cloud.githubusercontent.com/assets/18429104/22270027/79ee7162-e253-11e6-96d9-8789ed14e69a.png)

![screen shot 2017-01-24 at 4 29 14 pm](https://cloud.githubusercontent.com/assets/18429104/22270296/7e513f54-e254-11e6-9a23-fdf5907c43e8.png)

i also suggest to change the color of the email buttons to begin normalizing oc web, email & app

**Comment by xdamman** [comment]
I like this second approach. And I agree, we should use that new style in the email.

**Comment by piamancini** [comment]
moving this to #478 and hosts issue
