### ISSUE TITLE
Use the design system for the changelog

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2813]
The [changelog](https://changelog.opencollective.com) setup by @flickz on https://github.com/opencollective/opencollective-changelog is great. A simple way to make it look better without an input from design would be to use the design system.

Because we don't use a monorepo, sharing the code is not very straightforward. 
We have three options to do it:
- Copy/paste the theme and components (:cry:)
- Export to an npm package
- Give a try to https://bit.dev

The third approach has my preference because this is exactly the problem Bit.dev is trying to solve - and I'm curious about it. Doing this for the changelog is a scoped experiment.

Regarding the components to update, I'd say:

- Use the typography (`H1`, `P`...) for all texts to add consistency on the font(-size)s
- Use `StyledTag` for all tags, try to use the base theme (`success`, `error`, `info`...) as much as possible

![image](https://user-images.githubusercontent.com/1556356/72338181-393cd780-36c4-11ea-8a50-4e8219cc1993.png)

**Comment by Betree** [comment]
This issue should be fairly simple now that we have our design system on https://bit.dev/opencollective/design-system

**Comment by SudharakaP** [comment]
@Betree : I'll be working on this; hope no one is already on it. :smile:

**Comment by Betree** [comment]
@SudharakaP check https://bit.dev/opencollective/design-system for installing the components that you need. You'll probably need to create an `.npmrc` file at the root of the repo with the following content:

```
@bit:registry=https://node.bit.dev
```

**Comment by SudharakaP** [comment]
@Betree : Thanks much for the info. Will do. :+1:

**Comment by SudharakaP** [comment]
@Betree : I've created a draft pull request for this but there's a small issue blocking this. I cannot import `StyleTag` at the moment since in [StyleTag we use `react` as a dependency](https://github.com/opencollective/opencollective-frontend/blob/d7f6fb92f0430be907edbe7c697d9e59868637c3/components/StyledTag.js#L1). This creates a problem unless we define `react` as a peer dependency as mentioned at; https://docs.bit.dev/docs/react-guidelines#add-react-libraries-as-peer-dependencies-with-relaxed-versions. I've opened a pull request for this; can you merge this first, then I think this would work. :smile:
