### ISSUE TITLE
Incorrect info after upgrading host plan

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2842]
I just upgraded Protozoa host to the Small plan. 

At the bottom of the screen it's showing incorrect or incomplete info under "limits and usage".

- [ ] Current plan should show plan name not variable ID or whatever it's displaying there. This should just say "Small".
- [x] ~~Manual payments should say "unlimited".~~ Fixed.
- [ ] There's should be another point saying "Bank transfers: not enabled (turn on here)" linking to that setting so newly upgraded hosts can start using their new feature.

![Screen Shot 2020-01-23 at 9 24 03 AM](https://user-images.githubusercontent.com/5498878/72931466-c7027c00-3dc2-11ea-8d4e-05380863511d.png)

- [x] ~~I am on a paid plan but bank transfer payment type is still disabled for this host:~~ Fixed

![Screen Shot 2020-01-23 at 9 31 43 AM](https://user-images.githubusercontent.com/5498878/72931813-69226400-3dc3-11ea-95ec-0bb71b632a6e.png)

**Comment by alanna** [comment]
Added `priority` label because we are going live with these changes this week and the basics needs to function for users who want to upgrade.

**Comment by znarf** [comment]
The "Manual Payments" issue should be fixed now.

**Comment by znarf** [comment]
Removing the priority because the main issue was fixed.

**Comment by snitin315** [comment]
I will take this up.

**Comment by Betree** [comment]
@snitin315 are you still working on this?

**Comment by snitin315** [comment]
@Betree I think `small-host-plan` is actual plan name. 

https://github.com/opencollective/opencollective-frontend/blob/cc6e11870ff8d1e220042e13e7080b78bfe17873/components/edit-collective/sections/HostPlan.js#L240

and in the cards above we are using hard coded values.
https://github.com/opencollective/opencollective-frontend/blob/cc6e11870ff8d1e220042e13e7080b78bfe17873/components/edit-collective/sections/HostPlan.js#L203

**Comment by Betree** [comment]
@snitin315 Yes, we need to update that as described in the issue. Ideally we should also internationalize the strings.

Feel free to un-assign yourself from the issue if you don't have the bandwidth to work on it at the moment, you can always come back to it later. We usually recommend contributors to not take more than 2/3 issues at the same time as there's a risk to loose track after that and because it's blocking other contributors that may want to work on this too. You currently [have 6 issues assigned](https://github.com/opencollective/opencollective/issues/assigned/snitin315), it would be great to remove your assignments from the ones you're not ready to tackle in the next week(s).

**Comment by snitin315** [comment]
Sure, I will un-assign myself from some issues.
