### ISSUE TITLE
Support regular log in for better UX

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#285]
Will it soon be possible to just do a regular log in? I appreciate that you do the password-forgot-flow by default, but these days most browsers just remember & auto-login the details anyway so this email flow is actually quite cumbersome.

And I find myself being logged out all the time too. This is especially annoying on mobile, where you need to switch to the mail app and then back.

**Comment by piamancini** [comment]
I'll let @asood123 take this one.

**Comment by asood123** [comment]
We usually get the opposite feedback :). Many users prefer the simplicity of not remembering passwords (or having to worry about someone stealing them).

I agree that on mobile it's a little icky with app switching. I'm also surprised that you find yourself logged out often. It should remember you for 30 days.

**Comment by jancborchardt** [comment]
I just needed to log in again. I would recommend upping the 30 days a bit since I’m not actively on Open Collective that much, and since it’s a more passive (donate once and forget) kind of thing, maybe just putting it to 60 already works better. :)

Also cc @simonv3 who had the same problem.

**Comment by simonv3** [comment]
Yeah, part of my problem also stems from the fact that I can't remember which of my two accounts I'm using for which thing (which I think I've actually talked to Aseem about) so I always end up having to log in and log out again, which with this particular flow is a bit more of a hassle. 

Like Jan said, I also only ever check in not very often, so that's probably why I keep hitting the 30 day log in period.

**Comment by asood123** [comment]
Problem noted @jancborchardt @simonv3. It's on our list to improve login tokens. Stay tuned, hope to have something to show in next few weeks.
