### ISSUE TITLE
Load more button does not load more transactions

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2855]
I'm trying to view transactions here: https://opencollective.com/open-source-festival-2020-4abe0517/transactions

I clicked load more a few times and it worked, but then it stopped loading more content. How can I tell if it's actually reached the end?

![ezgif-3-a0fa678eef46](https://user-images.githubusercontent.com/5498878/73229435-aa10e300-41de-11ea-8cf4-f77e5be3339a.gif)

**Comment by marcos-mendez** [comment]
Please provide the Inspect Element page with console and errors.

**Comment by alanna** [comment]
I tried to do that but I couldn't get it to happen again. Now it appears to be working. Strange!

**Comment by marcos-mendez** [comment]
Please, we need to close the issue


Em ter., 28 de jan. de 2020 às 05:36, Alanna <notifications@github.com>
escreveu:

**Comment by Betree** [comment]
I see three possible explanations for this one:

1. Either the bug is related to the number of transactions
2. Or we don't refresh the list properly
3. Or there was a network error that we don't display

After testing, a network error seems to result in having the `Load more` button stuck to `loading...`, so 1. and 2. seems like better candidates.

**Comment by znarf** [comment]
Might be the same that the one we fixed for comments. https://github.com/opencollective/opencollective/issues/2590 https://github.com/opencollective/opencollective-api/pull/2869

**Comment by znarf** [comment]
Should be fixed in the updated Transactions. cc @kewitz
