### ISSUE TITLE
Include receipt PDF in "thank you" email

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2867]
## User story 
As a financial contributor, I can easily download receipts from the email sent when I make a contribution (the `Thank you for your $_ contribution to ____` email). We used to have a link in there that pointed directly to the invoices server, but this has been deprecated because it didn't meet our security standard.

## Best solution for this problem

Two possible solutions:
1. When sending the email from API, fetch the invoice from the invoices server and attach it to the email. If the invoice generation fails, we should still send the email without it.
2. Create a page to show a single transaction on `/{collective}/transactions/${transactionId}` that has a download invoice button on it. Link this page form the email.

My personal preference goes to (1) because it's a simpler UX and it doesn't seems more difficult to implement. But implementing both solutions could actually be nice.

## Metrics 
- Number of support requests for people not finding their receipts

**Comment by Betree** [comment]
We also have to think how this would play with https://github.com/opencollective/opencollective/issues/2864

**Comment by repi** [comment]
This would greatly simplify our workflow with OpenCollective and reduce admin overhead so we can sponsor more projects and individuals.

Currently [we](opencollective.com/embarkstudios) have to login to OpenCollective every month and manually download the billing receipt PDFs for each individual project and for the right months and then email and important that into our accounting system. Instead of just getting a single overall receipt PDF every month that can be auto imported into our systems.

**Comment by repi** [comment]
@sbinlondon thanks for implementing this, will make our lives easier! cc @arirawr

**Comment by Piedone** [comment]
Very nice! Is there anything we as sponsors need to configure to receive the PDFs?

**Comment by Betree** [comment]
@Piedone Nothing to do on your side, the PDFs should just land with your next "Thank you" emails :slightly_smiling_face: Please note that we can't guarantee that this will happen with the next batch on 1st November as we still need to do some load testing to make sure it will run smoothly for everyone. We're also going to tackle https://github.com/opencollective/opencollective/issues/3626 to make sure your accountant receive them too!
