### ISSUE TITLE
Filenames attached to reports should include profile name

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2882]
Currently, the monthly and annual report emails to Collective and host admins come with attached documents with the filename format `date-transactions.csv` and `date-expenses.pdf`. When you operate many profiles, it's confusing to try to keep them all straight when doing accounting, etc. We should add the name of the Collective, Host, etc to the filename, so it becomes `name-date-transactions.csv` instead.

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by znarf** [comment]
🏆 This issue was completed by @bolariin 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
