### ISSUE TITLE
adding funds as a sponsor to an event triggers a ticket

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2891]
When you add funds to an event it triggers a ticket to the sponsor. It should trigger a donation confirmation. 

<img width="1034" alt="Screen Shot 2020-02-07 at 8 49 12 AM" src="https://user-images.githubusercontent.com/3671070/74010944-e97dc300-4986-11ea-8bbd-bfa5415fe2ae.png">

**Comment by bolariin** [comment]
I found that the reason the ticket is sent is because a ticket is always sent if the collective type receiving the payment is an event.
https://github.com/opencollective/opencollective-api/blob/2da1699a51a7888a274e20bf91865993df08e9c9/server/lib/payments.js#L351

I was wondering how donation payments are differentiated from order payments?

**Comment by znarf** [comment]
We should actually check if the `Tier` is `type=TICKET`, everything else can be considered as a donation.
