### ISSUE TITLE
Add some diversity to the homepage

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2893]
Would be great to have different skin tone on this illustration to show that collectives are open and inclusive 👩🏽‍🦰👨🏿👩🏽‍🦱👨🏼‍🦳

![](https://opencollective.com/static/images/makecommunity-section-illustration.png)

**Comment by Memo-Es** [comment]
@xdamman We wanted to move away from the generic visual way to showcase diversity (Different skin tones). The concept of diversity was addressed in the illustration project by featuring these cubist characteristics https://d.pr/i/EyDS2x because we think that diversity exists even within oneself and then it's communicated to others using social norms, clothes, skin tone, attitude, etc.

**Comment by xdamman** [comment]
That’s very true but it doesn’t have to be “or”, it can be “and”.
