### ISSUE TITLE
Contributors grid: implement horizontal scroll snapping

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2905]
Scroll snapping improves the experience of scrolling through horizontal lists, especially on mobile. We want to add this to the contributors grid to always display the full contributors cards when scrolled horizontally.

See https://github.com/opencollective/opencollective-frontend/pull/3511 for an example of how to achieve that.

![image](https://user-images.githubusercontent.com/1556356/74322946-051d0b00-4d85-11ea-9057-65e5096054e4.png)

**Comment by rdinicut** [comment]
Hi @Betree . I would like to give this a shot. Can you assign me please

**Comment by Betree** [comment]
Hi @rdinicut, thanks for jumping in :muscle: It's all yours!

**Comment by rdinicut** [comment]
@Betree I managed to look a little at the code. IMO the proposed solution, using scroll-snap-type will not work with the current implementation because the component(ContributorsGrid.js) renders and positions it's children programmatically. Looks like it is trying to implement virtual scrolling. Also it has an inner container with a calculated width based on number of items and rows it wants to render which is scrolled. 
![image](https://user-images.githubusercontent.com/1313388/74971652-bb858d80-5420-11ea-8331-793db4e4c5e2.png)

So the component need a serious refactor to make it work with css and it might not be a best idea considering that contributors list can be large and virtual scrolling can help. 

IMO the best way to implement this will be to scroll it programmatically.  WDYT?

**Comment by Betree** [comment]
@rdinicut thanks for digging that! You did a great job understanding the issue and explaining the implications :pray: 

> Looks like it is trying to implement virtual scrolling. 

It is virtual scrolling indeed, if you look at the DOM while scrolling you'll notice that the items come and go. You're right that we won't be able to use CSS scroll snapping with this code and it's a huge task to re-implement virtual scrolling without this technique.

> IMO the best way to implement this will be to scroll it programmatically. WDYT?

That would indeed be the best fix, however the goal of this issue was to benefit of the small UX improvement granted by this CSS technique "for free", because it's really simple to implement.

If it's going to be more complex than that I'd rather close the issue.

**Comment by rdinicut** [comment]
@Betree ok, I will look for another issue that think I can pick up then. Any suggestions?

**Comment by Betree** [comment]
@rdinicut this one may be a good one :slightly_smiling_face:  : https://github.com/opencollective/opencollective/issues/2830
