### ISSUE TITLE
Tax forms for organizations & collectives

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2962]
The new expense flow allows for organizations and collectives to submit expenses to a collective. When these expenses are invoices we need to gather tax forms for them as well. 

Some issues we can anticipate when we set up tax forms for them. 

- Collectives are not legal entities so the tax form needs to be filled (or check against) their host organization. 

- Organizations are managed by several users and even if we can those users individual forms - linked to their emails - we still need an organization one. 

- Te way HelloWorks is set up, it uses the email as a single identifier that uses to check if user has a form linked to their profile or not. Organizations have multiple admins, so we need to store this check at the organization level. Collective ID? We also need at least one email address linked to that ID for us to send the relevant tax filing in January 2021. 

We shouldn't block on this, but we need to be aware that the hosts will need an export of the organizations who submitted an expense in order to request the tax form to be completed.

**Comment by Betree** [comment]
While we figure this out, I can disable the payee select to make sure that it stays locked on user's profile:

![image](https://user-images.githubusercontent.com/1556356/75984278-63538e80-5eea-11ea-8a85-3c010411c0d9.png)

**Comment by piamancini** [comment]
@betree I don't think it's worth it to be honest. It's an important feature and one requested by several collectives. I think an export of companies / collective submitting expenses is good enough

**Comment by Betree** [comment]
We must not forget this one

**Comment by piamancini** [comment]
indeed!

**Comment by Betree** [comment]
Some progress on this: I've worked on the tax form SQL query (that we should now use as the default one to detect tax forms) and the ability to detect which organizations need tax form is just one step away - it's a matter of removing this line: https://github.com/opencollective/opencollective-api/blob/95305ce13ed814aa6edc63ec108bfa8f1ecee02f/server/graphql/loaders/expenses.ts#L42.

With this detection in place, what we still need to do is:
- Notify the collective admins (+ send the HelloWorks notification)
- Make sure the process works

There should not be any required change on the frontend.

**Comment by alanna** [comment]
> The new expense flow allows for organizations and collectives to submit expenses to a collective. When these expenses are invoices we need to gather tax forms for them as well.

We don't need a tax form for expenses to be paid to a Collective if the money is staying within the same host. Tax agencies can only 'see' money when it comes in or goes out of a legal entity. Moving money between Collectives in the same host doesn't mean anything to them, so it has no tax implications. If a Collective is paid by a host or another Collective budget in that host, the tax form only needs to be triggered when someone invoices to that Collective to take the money out externally.

> Collectives are not legal entities so the tax form needs to be filled (or check against) their host organization.

This will only become relevant when we implement Collective to Collective payments between different hosts. I suggest we defer this part until that project is prioritised.

> Organizations are managed by several users and even if we can those users individual forms - linked to their emails - we still need an organization one.

Yes, importantly we need the tax form *for the organization* not the individual. Any individual can submit it if they have the authority and information needed, but the entity on the tax form is the company in question, and its tax ID number, etc. E.g. an organization overseas will fill out a W8-BEN-E and an individual overseas will fill out a W8-BEN (the tax form is set up to recognise this distinction through their answers, but we need to ensure it's clear to the user we're asking for the organisation's info).

But here's the part I think will be really painful:

Because we haven't solved #3340, **a lot** of expenses have been submitted under individual profiles that are actually paid out to an organization they represent. We *must* have a tax form matching the actual payee entity where we sent the money, i.e. the organization. *Most* individuals who submit an expense under their individual profile and get a tax form request know to fill it out on behalf of their organization, but our system currently associates that to their individual profile.

**Comment by Betree** [comment]
I'm now prioritizing this issue to make sure we have the time to handle everything before the end of the year.

**Comment by znarf** [comment]
@piamancini the Tax Form system should works properly with Grants since the beginning. Please report issues if that's not the case.

**Comment by Betree** [comment]
It should indeed, the query is looking at all expenses that are not type=`RECEIPT` (so invoices, grants and unclassified)

**Comment by Betree** [comment]
This is done
