### ISSUE TITLE
Graphql help

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#301]
For our upcoming Events support, we are using Graphql (https://github.com/OpenCollective/opencollective-api/tree/master/server/graphql). Currently it's setup to query for Events. We are working on mutations next and have some questions about how to get most of it.

Models:
- `Event`: `name`, `description`, `location`, etc.
- `Tier`: Type of tickets available for the event. Like a free ticket or an early bird
- `Response`: RSVPs associated with a particular `Tier`.

Our stack: Postgres, Sequelize and now GraphQL on top.

1. Should there be a query for each view on the frontend?
- We have a view that shows details of a single Event (name, location, description, etc) and we have a view that shows a list of all events for a particular group. Should that be two different queries: `getEvent` and `getEvents` or should it be one query `getEvents` and you filter by `Event.id` when you only want one particular event?

2. Similarly for mutations:
- We have an action on frontend that records an RSVP for an Event. Should there be a mutation `addResponse` and another one `updateResponse` or is it better to have just one `addOrUpdateResponse`?

3. Where should business logic be? 
- We handle auth through our own middleware and that works fine for now
- Where should data be validated? If I want to record an RSVP for a paid ticket, should the backend ensure that a `Response` can't be recorded without a `PaymentMethod` or should the frontend be responsible for ensuring that a mutation isn't used until `PaymentMethod` is present.

4. Where should outbound requests be?
- When someone RSVPs and gives us a credit card, we need to contact Stripe. With a REST API, we send the Stripe token and user's info to the backend. It records it and spins up an asynchronous call to Stripe that charges the card.
- How should that be handled with GraphQL? 

Some of it boils down to where does GraphQL fit in. Traditionally, we think of our API as three layers: Data/models, business logic and controllers to receive and serve REST requests. How does GraphQL overlay on those three layers? Definitely don't need controllers anymore but is a controller now equivalent to a query or a mutation?

**Comment by petrbela** [comment]
These are all great questions. As in most cases, "it depends". There could certainly be a long discussion about each approach.

> 1. Should there be a query for each view on the frontend?

I'd suggest keeping `getEvent` and `getEvents` separate. `getEvent` returns a single item, while `getEvents` return a list. GraphQL's main idea is about enabling clients to request data in a format that best fits each the product's needs. Typically, you'd write GraphQL server once and then reuse it across many clients and their UX/product iterations. And from the client's point of view, when they know they want to fetch one item, it'd be weird to fetch a list. (Although, technically, it's the same as `Event.where(slug: slug).first` which is not too uncommon.)

> 2. Similarly for mutations:

You could go either way. If RSVP is identified by a combination of event+user, then you could have a `saveResponse` mutation that would receive the event and status as arguments (plus user in the context). If for some reason you need to treat RSVP as a standalone entity (i.e. you care about its ID), then separating the intent to `add` and `update` might make more sense. To me, it seems like the former could be a better fit for this situation.

> 3. Where should business logic be?

Authentication is handled outside of GraphQL itself. You'd then typically pass the current user in the context to the GraphQL executor so you can access it from the `resolve` methods to perform authorizations on individual pieces of data.

Rule #1 of validation: Always validate on the backend. Front-end validation is optional. That said, GraphQL is strongly typed, and if you declare `PaymentMethod` argument as `GraphQLNonNull`, the GraphQL executor itself will validate it and return an error without even calling the mutation's resolve method.

> 4. Where should outbound requests be?

You'd deal with it in exactly the same way. Since you're changing data, you'd create a mutation, taking the user and stripe token as inputs. Now, if you want to maintain the asynchronicity, the mutation could just return `true`. Although it might be wiser to confirm the payment was successful before sending the response back to the client.

--

In my view, a mutation corresponds to one controller's action that is not a get/list. Get/list actions in GraphQL don't exist per se; instead, the GraphQL executor traverses the *types* along the query. So to build a GraphQL server, I'd first create types for all models and their relationships so they could be queried as the clients need. Then I'd identify all individual actions that a user might make that modify data, and create a mutation for each of them.

Relating to the three layers, when you use GraphQL, models are still the same, business logic is still largely the same (if you previously had it separate from the controller actions), and the only layer you need to convert is the controllers.

**Comment by asood123** [comment]
@petrbela Very helpful, thanks for detailed comments.

**Comment by AlexGaspar** [comment]
I mainly agree with what @petrbela said 👍 

Few comments:
> Should there be a query for each view on the frontend?

Keep it separate. Also GraphQL people tends to use `all + Model + s` and `Model`
e.g. `allFims` / `Film`

> Authentication

If it works, keep it that way. You should already be able to use `req.jwtPayload` inside GraphQL through context (3rd variable in your resolve function).

You could also handle it "inside" GraphQL. (https://medium.com/the-graphqlhub/graphql-and-authentication-b73aed34bbeb). I just choose to go with the last approach. Not sure yet how it will turn out. 

> you'd create a mutation, taking the user and stripe token as inputs.

If the payment is only for the user himself, I'd say that you only need the stripe token and you should use the user from context. 

> Where should outbound requests be?

Not really related, but the resolve function can return a Promise, and GraphQL will make sure the promise is fulfilled before doing anything, just in case. 

--

Since you are already using Sequelize, you could give https://github.com/mickhansen/graphql-sequelize a try. It removes the need of declaring your models two times (one for Postgres and one for GraphQL) + some other cool stuff.

**Comment by sedubois** [comment]
Yep you got nice answers already. I haven't made any GraphQL backend so can't talk about that part. I've just been prototyping with Graphcool so far, so as they probably had to do a lot of thinking themselves already, you could take inspiration from how its API is designed (use the built-in Playground). E.g when you create an `Event` table, it automatically creates `Event` and `allEvents` queries, etc.

Also note that tools like Graphcool might not necessarily be incompatible with having your own backend: it has hooks to run AWS lambda or stuff like that (but I haven't played with that yet).

**Comment by piamancini** [comment]
@asood123 do you need this still open?
