### ISSUE TITLE
Open Source apply flow does not work for personal repos

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3015]
**Describe the bug**
When you try to apply on `/create/opensource` using the Github flow, the `Continue` buttons stays disabled for personal repos.

**To Reproduce**
1. Go to /create/opensource
2. Login with Github
3. Pick a personal repo
4. See disabled button

**Expected behavior**
Continue button should be enabled and should take you to the next step.

**Screenshots**
![Peek 27-03-2020 13-21](https://user-images.githubusercontent.com/1556356/77755582-deade900-702d-11ea-8b98-b577eaa321a8.gif)

**Additional context**
It seems that `changeRepoInfo` is only triggered from the "For the repository" / "For the organization" select, which is never displayed for personal repos. 

Also I don't understand why we have two `GithubRepositoryEntry.js` and `GithubRepositories.js` is there a reason why they're duplicated?

**Comment by sbinlondon** [comment]
Re: context and why they were duplicated. At the time I believe there were some differences in the existing one and the one for the new CCF that led me to duplicate the files instead of changing how the existing ones worked (and possibly breaking the old flow). I don't have the exact logic to hand but I don't think I would have just duplicated them without reason. But if we have the old Create flow turned off I guess we can get rid of the old components?

**Comment by znarf** [comment]
Yes, we should delete the whole old create collective, but we should also port the E2E tests to the new flow.

**Comment by sbinlondon** [comment]
I'll create an issue for that
