### ISSUE TITLE
Migrate Events E2E tests to new Event page

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3024]
A few E2E tests covering events are currently skipped because the legacy page was removed.

We want to migrate these tests to the new page (remove `/legacy`).

See: https://github.com/opencollective/opencollective-frontend/blob/master/test/cypress/integration/24-event.createOrder.test.js

If some tests are not applicable anymore, they should be replaced by similar tests to keep good coverage.

Bonus: any extra test is welcome.

**Comment by jeffin143** [comment]
Will look it during the weekend , super obsessed with E2e test in repo 😉

**Comment by SudharakaP** [comment]
The things I've added here are, 

- Test for checking the submission of a Free Ticket.
- Test for checking the submission of a Ticket with Fixed Payment Amount. 
- Test for checking the submission of a Ticket with a Flexible Payment Amount. 

I hope this covers everything in this issue. Let me know otherwise. 😃
