### ISSUE TITLE
Handling of props to variables conversion in graphql HOC

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3056]
Following up on a comment I made in https://github.com/opencollective/opencollective-frontend/pull/3895#pullrequestreview-390926264, I would like us to settle on a common pattern through the codebase. We have two choices: relying on default behavior or being explicit.

> By default, graphql will attempt to pick up any missing variables from the query from ownProps. [...] However, if you need to change the name of a variable, compute the value, or just want to be more explicit about things, the options function is the place to do it.

1) Either we always rely on `ownProps` when available and delete all code where we are repeating ourselves.
2) Either we made it explicit everywhere and make sure there is always an `options` method to convert `props` to `variables`.

Based on the output of this discussion a PR will be made to make the codebase consistent.

I personally favor the first option!

**Comment by Betree** [comment]
I tend to think that it's easier for developers who are unfamiliar with Apollo to understand what's happening if we're using the explicit form.

But I also prefer the first one, because it's simple.

I don't have a strong opinion for one side or the other.

**Comment by sbinlondon** [comment]
I'm still confused.

Looking at this file, both ways are used in short succession. What's the difference? Is it that you only use `ownProps` with mutations and the other way with queries?

As @Betree said, it's pretty difficult for newbies to graphql and Apollo to grasp these things. Personally for me as well, I can read all the documentation and theory I want, but without seeing code examples comparing the two approaches to the same problem, for example, I find it _incredibly_ hard to understand. More of a practice than theory person (which is why I still didn't really understand despite you linking to the documentation, @znarf).

So in the end I don't have an opinion either way - I'll leave it up to y'all. In the end consistency in the codebase will only help newbies (to the codebase and graphql/apollo) because we have a template for how things are supposed to look, and can work backwards from that figuring out how we need to apply that to our particular situation.

**Comment by znarf** [comment]
@sbinlondon The file you're linking is not the best example to the problem.

Let's look at the file I was originally commenting on. We're passing `props.slug` as `slug` in variables. With this approach (2), it's explicit. https://github.com/opencollective/opencollective-frontend/blob/master/pages/accept-financial-contributions.js#L51

I'm asking if we should generally remove that, because it's not necessary. By default, apollo will look at the props of the component and pass it automatically as variables. The value is originally coming from here: https://github.com/opencollective/opencollective-frontend/blob/master/pages/accept-financial-contributions.js#L17 With this approach (1), it would look like that: https://github.com/opencollective/opencollective-frontend/pull/3936

If you look at the codebase, we currently use the first approach (1) a lot, especially in pages. Example: https://github.com/opencollective/opencollective-frontend/blob/master/pages/editCollective.js no variables.

1) shorter, avoid repetitions and potentially easier to maintain
2) more explicit, easier to understand

**Comment by kewitz** [comment]
To be honest, I didn't know about how the `ownProps` behavior until now.
After reading this issue, I'm fairly confident we all know how that works being implicit about variables wouldn't be a problem.
The problem is: should we be implicit and expect everyone to know it or be explicit to people that are not very familiar with the library?
I tend to think we should be explicit, but I don't have a very strong opinion about it.
Also, keep in mind that being implicit means that our routes are responsible for generating the right props to our pages and one typo in that string might break things.

**Comment by sbinlondon** [comment]
Right, I understand now - thanks for the in depth explanation! When you were telling me to rewrite this bit https://github.com/opencollective/opencollective-frontend/blob/master/pages/accept-financial-contributions.js#L51 I thought you meant still using `options` and `props` but in a different way, rather than omitting them entirely, hence my confusion 😅 

Ok, so now knowing what's going on... personally, yes, I would favour explicit over implicit, even if it's less beautiful, for the same reasons I mentioned above. Like writing out full `if` statements instead of a succint ternary (yes I say this as an offender who loves writing ternaries). It helps people who either aren't familiar with the codebase, or familiar with the particular concept, see more of the info that would allow them to grasp what's going on and contribute better + faster.

**Comment by znarf** [comment]
Thank you for your feedback!

Given that this Apollo feature is not well documented and that we should aim to have code that is easy to understand for newcomers, we should favor the explicit version that is constructing the necessary `variables` in `options`.
