### ISSUE TITLE
Feedback for new expense flow (pre-release)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3057]
This issue is here to gather feedback and impressions around the new expense flow.
  
Known issues:
- The admin buttons (approve, reject, etc.) have not been implemented yet on the page. We're working on it.

# Changelog

A small highlight of the new features:

### Automatic invoice generation

<details>
<br/>

> No need to generate a PDF to get reimbursed anymore! Just pick the `Invoice` type, and we'll generate one for you :receipt: 

![image](https://user-images.githubusercontent.com/1556356/79250670-4dd56b00-7e7f-11ea-96b6-b2d8da763cd7.png)

</details>

### Submit multiple receipts

<details>
<br/>

> No need to create multiple expenses or to merge receipts in PDFs anymore: you can now submit a single expense for multiple related items :shopping: 

![image](https://user-images.githubusercontent.com/1556356/79251416-65612380-7e80-11ea-82d3-ac24112cd2b8.png)

</details>

### Submit an expense as an organization

<details>
<br/>

> You can now submit an expense in the name of your organization. We currently working on making this feature work for collectives too!

![image](https://user-images.githubusercontent.com/1556356/79251700-c983e780-7e80-11ea-9996-4a95bcff06bd.png)

</details>

### Associate multiple payout methods

<details>
<br/>

> You can now associate multiple payout methods to your profile.

![image](https://user-images.githubusercontent.com/1556356/79252371-c9d0b280-7e81-11ea-82e2-e307a31ec5df.png)

</details>

### Expense activity feed

<details>
<br/>

> Along with the comments, see when expenses get approved, rejected, edited and paid.

![image](https://user-images.githubusercontent.com/1556356/79252690-51b6bc80-7e82-11ea-9d35-72fcf887e331.png)

</details>

# Try it :arrow_down: 

Add `/v2` at the end of expense's URLs. Feel free to use our collective if needed:
- https://opencollective.com/engineering/expenses/new/v2
- https://opencollective.com/engineering/expenses/9183/v2

*Note: expenses list re-design has not been released yet*

# Give feedback

Below are some questions to guide your feedback - you don't need to answer them all, feel free to answer with whatever format is easier for you:
- What is your general impression?
- Did you understand all the terms and actions that were presented to you?
- Did you encounter any glitches/bugs?
- Are there things that you especially like?
- Do you see things that could be improved?

_If you had experience with the previous flow:_
- Was it faster or slower to complete?
- Is there anything that you did with the previous flow that you're not able to do anymore?

<br/>

**Comment by xdamman** [comment]
When I click on https://opencollective.com/engineering/expenses/new/v2
this is what I see: 

![](https://d.pr/free/i/TBJzvM+)

Console:
![](https://d.pr/free/i/y0WulR+)

I'm logged in as xdamman

**Comment by xdamman** [comment]
I tried to log off and log in again and I see a different error message but same error in console:
![](https://d.pr/free/i/KZojTW+)

**Comment by znarf** [comment]
@xdamman Fixed. It should work better now!

**Comment by xdamman** [comment]
When I go to an expense page (e.g. https://opencollective.com/allforclimate-uk/expenses/15296/v2), my primary goal as a collective admin is to review it to approve or comment on it, or as a visitor I want to see the title/description/date, amount and tags (and maybe comment on it)

Yet, I'm welcomed with a first screen that doesn't show me much of the information that I actually need. From a pure usability perspective, this is a regression on mobile phone for the most common use case.

Fear not, this is all fixable:

![IMG_5927](https://user-images.githubusercontent.com/74358/79270449-7f116380-7e9e-11ea-8d39-0eeb1cb0da31.jpg)


1- It's weird to have the balance of the collective always floating when looking at an expense. What's the goal? It takes a lot of real estate on a mobile screen. It's important information but I'd put it just below the header with the name of the collective and I wouldn't make it float.

2- There is a lot of real estate being taken for duplicate information. Both the payee and the host are already on that screen. 

3- Where are the tags? I'd expect to see them nearby Receipt (which could be considered as a tag), not below the prompt to write a response (are those tags related to my response?)

![IMG_5924](https://user-images.githubusercontent.com/74358/79270769-019a2300-7e9f-11ea-83ae-536101ebb4f4.jpg)

The expense receipt is incredibly small. Make it full width on my mobile phone so that I can quickly look at it and approve it or comment on it (which should be the primary goal of getting to that page no?)

2- Private note should linkify the text (and also allow markdown)

4- Payout option**s** or (better): Payout details and then Payment method then Private instructions (private instructions should come after as they are related to the payment method)

![IMG_5926](https://user-images.githubusercontent.com/74358/79271557-4d010100-7ea0-11ea-8641-629181856800.PNG)

CSS issue for the arrow after each question
It's also weird to have the dotted border around the question. Not sure what is it supposed to convey.

**Comment by xdamman** [comment]
Submit expense page:

Here again I'd move up the bar with the balance of the collective to the top, just below the bar with the name of the collective (and don't float it).

I'd also only show "receipt" or "invoice". It's distracting to see "Tags" below before I've answered the first question (typeform style).

The text for Invoice is weird. No one should ever get paid in advance in a collective. What about: "Pay directly the vendor" (the biggest difference between receipt and invoice is being reimbursed versus paying directly the vendor).

I wonder if we need a back button on mobile. Aren't people used to the swipe to go back and/or the back function of the browser?

![IMG_5931](https://user-images.githubusercontent.com/74358/79323527-9ab45280-7f0e-11ea-98dc-20b9a146ffbe.jpg)

![IMG_5928](https://user-images.githubusercontent.com/74358/79324041-478ecf80-7f0f-11ea-9db1-bfd5ac06cc9e.PNG)

I love the progress bar for uploading, really cool.

Tags are here again very weirdly placed. I'd expect to set them right after the title and optional description.

Expense Policy (singular, not plural) should be at the very top of that page.

![IMG_5929](https://user-images.githubusercontent.com/74358/79324445-ef0c0200-7f0f-11ea-9694-12592cf94785.PNG)

Please make the preview of the receipt full width on mobile. Why making it so small? I can't tell if I picked the right picture from my photo library, this also forces me to go back to the photo app to double check the actual amount.

Description should be multiline. 
Amount input should be of type Number and allow me to enter decimals. 

![IMG_5930](https://user-images.githubusercontent.com/74358/79324702-4c07b800-7f10-11ea-9d35-9af627a287cf.PNG)

Margins feel off for "who is being paid for this expense" and "choose payout option" (should be "payout method").

When creating a new payout method, I expect to be able to give it a label (e.g.: personal bank account, joint bank account, venmo, bitcoin, ...)


I'm very confused by this sending invoice.
The main use case is a vendor submitting an expense that needs to be paid. Instead of paying it myself and asking for a reimbursement, I want to ask the collective to directly pay it.
So I select "Invoice" instead of receipt. Then I see this:

![IMG_5933](https://user-images.githubusercontent.com/74358/79325062-d0f2d180-7f10-11ea-801b-d1cc500ff005.PNG)

Where can I upload the PDF?
Am I supposed to create an organization for this vendor? It doesn't let me do that.

This is the way it should work if you select Invoice to pay directly the vendor (vendor could be you as a freelancer):

1- a) Upload the invoice OR b) Create an invoice 
If a), pretty much same form than for a receipt. Then ask: 

Payee: 
Select the organization that needs to be paid: (search or create an organization)
Legal address of the vendor: _____________________
Payout method: list payout methods already attached to that org or create a new one

If b), current form is ok, just need to add legal address of the vendor.

When I select paypal as payout method, my paypal email shows up instead of paypal and then it asks for my email (?). I'd replace the dropdown with: "Paypal (email address)" (so that we don't lose the context of paypal), and I won't ask for the email. Probably a bug.

![IMG_5934](https://user-images.githubusercontent.com/74358/79326193-c0dbf180-7f12-11ea-9174-928e71f672b2.jpg)

Lot of vertical space wasted here. Also I'd say "vendor", not "payee".
Payout should show after the amount.

![IMG_5935](https://user-images.githubusercontent.com/74358/79326438-2203c500-7f13-11ea-9974-0784007f33f8.PNG)

The "add more details" should read more like "Private notes to the administrators of the collective or the host" (that's more self explanatory than the padlock (optional) at the end).

Very surprised to see that I can upload a PDF right after entering all the info. Either I have such attachment and I want to start with that, or I don't, but then I'd love to add maybe public attachments for the community to see. Maybe remove that and just have the button "Submit expense" with a note that says: "you can add more supporting documents that will be visible to the community on the next screen" (this will make more clear that this step is meant primarily for the collective / host admins and next is to explain to the community what it was about, see for example https://opencollective.com/mealsofgratitude-belgium/expenses/15320)

One last thing: I would adapt the wording based on wether it's a receipt or invoice.
E.g. if receipt, instead of "Payee & payout information", I'd say "Reimbursement details"

Also "Expense Summary" button is not clear (one may think: "I don't need an expense summary, where is the submit button?". I'd simply say "Next". Also very weird to have tags after the submit button. Most people will miss it.

Bug: When I try to submit an expense on https://opencollective.com/testcollective/expenses/new/v2 I used another payout method and entered an iban number, clicked on expense summary then when clicking on "submit expense" it said "This account cannot be used for payouts". Then I'm stuck and I don't know what to do. At least the error message should tell me how can I resolve this.
I went back, selected paypal, but same error message. So unable in my test to go pass the submit expense button.

**Comment by flaki** [comment]
I was going through an expense flow and was about to write up a loooong thing here, but then realized @xdamman very much said all I wanted so I'll just double down on some of his points from my perspective.

FWIW I was doing this on desktop and I didn't have too much qualms with the UI, but I agree with many of his notes on making the mobile version more usable, even if just with small tweaks.

### Receipt vs Invoice
![Screenshot of v2 expense screen](https://user-images.githubusercontent.com/2089432/79362195-f6063500-7f4e-11ea-854d-1c39884e68b2.png)

As I understand "Invoice", as currently implemented, allows for directly billing "hours" (or any other service) at the collective, this avoids the submitter needing to be able to put together an invoice of their own, submit it to the right entity, etc etc... I think this is nice and it makes sense but "Invoice" doesn't really describe what is this option useful for, and is confusing the submitter because "Receipt(s)" are _also_ a way to submit invoices.

There are two ways I can see "Receipt(s)" being used. One is the "photo of a receipt I already paid" use case, where I want a *reimbursement*. This is easy, straightforward and well supported. I also ran into the "here's an invoice from a vendor, please fulfill according to the instructions on the PDF, I don't want to be paid" which is ill supported currently. See below for details.

I think it would be useful to rename the options with something describing the task to be accomplished or the pre-requisites of each. Without going too deep into bikeshedding "I have receipts i want reimbursed / I have an invoice I want to be paid / I don't have a receipt, I want to bill for time worked", or along these lines. I think the receipts/invoice use case might be worth to be distinguished and separated, explained next.

---

### Submitting a payable invoice

So I have an invoice from someone that needs to be paid by the host, according to the details on the invoice PDF itself. **Me personally**, I am just the messenger, I don't want to be paid/reimbursed etc, just submitting this invoice so the host pays it and it shows up nicely for the collective in the budget. (In fact, this particular invoice has *already* been paid by the host, and I'm just recording it in the budget here but that doesn't make any difference to my point).

![Screenshot with expense details asking for wire payment](https://user-images.githubusercontent.com/2089432/79363515-aaed2180-7f50-11ea-9e71-4211ca125838.png)

So because I don't want to be paid, I select the next best thing here, the host itself, as the beneficiary, noting that a manual payment is required.

![Screenshot with the Payer same as Payee](https://user-images.githubusercontent.com/2089432/79363522-ade81200-7f50-11ea-84c2-dc9d32d3bb13.png)

Oh well, I knew it's not gonna work when I saw this screen - the payee and the payer are the same!

![Screenshot showing the error due to invalid payee](https://user-images.githubusercontent.com/2089432/79363539-b3ddf300-7f50-11ea-8792-ba6a5f857991.png)

Trying to submit the expense, I'm informed that *"This account cannot be used for payouts"*. Oh well, it was a hack anyway.

I think this could be fixed by adding another recipient in the box that is stated as *"Invoice vendor"*, or, if needed, even a "Custom" with a text field where the recipient could be shown.

---

### Workaround (current solution)

So the way I ended up submitting the invoice is submitting it as myself as a "payee", but noting that I'm not the person who needs to be paid but the invoice should be paid according to the wire transfer details recorded on it:

![Screenshot_2020-04-15 Unannounced Project - New expense - Open Collective(4)](https://user-images.githubusercontent.com/2089432/79363569-bb9d9780-7f50-11ea-81d5-396ba70b6740.png)

I guess part of the reason the system is like this is to have "someone" towards whom these funds flow, even if I'm not the recipient of these expenses, I'm the one who is responsible(?) for them, at least as far as Open Collective is concerned. It is just a bit weird that arbitrary transactions show up on my account that I never received any funds for (not even funds that "passed through" me, as in me paying them and getting reimbursed).

---

**Comment by Betree** [comment]
@xdamman @flaki Thank you for the feedback! We just deployed [an important update](https://github.com/opencollective/opencollective-frontend/pull/3947/) that should address some items mentioned here, including:

- Updated the layouts
- Using hosts as payees is not supported yet, so they don't appear in the "payee" select anymore
- Expense policy is now rendered as markdown
- Updated some of the working
- Improve distinction between Payee and Submitter

![image](https://user-images.githubusercontent.com/1556356/79452755-f226f100-7fe8-11ea-896a-e0bcb5ba9ebe.png)

---

Note that there are still important updates to come, including:
- Implement admin buttons (pay, approve, etc.)
- Tags are not yet implemented where/as they should be
- Small layout issues (especially on Firefox)
- Responsiveness

**Comment by Memo-Es** [comment]
Expense type descriptions:

**Reimbursements:** Get reimbursed for a purchase already made.

**Invoices:** Create an invoice to get paid or to pay a vendor directly.


<img width="1460" alt="Screen Shot on 2020-04-17 at 09-24-18" src="https://user-images.githubusercontent.com/49539954/79753553-be471680-82db-11ea-9a9c-33f91ff7945b.png">

**Comment by Memo-Es** [comment]
This comes also with another copy change for the last part regarding payout options:

**For Reimbursements:** Reimbursements details

**Invoices:** Create an invoice to get paid or to pay a vendor directly.

**Comment by flaki** [comment]
> Expense type descriptions:
> 
> [...]
> **Invoices:** Create an invoice to get paid or **to pay a vendor directly.**
> 
> <img alt="Screen Shot on 2020-04-17 at 09-24-18" width="1460" src="https://user-images.githubusercontent.com/49539954/79753553-be471680-82db-11ea-9a9c-33f91ff7945b.png">

Does this mean "Invoice" will also allow us attach the PDF version of an invoice (issued by the vendor who needs to get paid directly?).

The currently deployed `/v2` does not allow for attachments in the *Invoice* case.

**Comment by Betree** [comment]
> The currently deployed /v2 does not allow for attachments in the Invoice case.

@flaki It does, but on the summary step - which we acknowledged is not clear at all. Design is currently working on moving this field onto the main form, so this will ultimately be supported.

![image](https://user-images.githubusercontent.com/1556356/79850982-fc6c3500-83c4-11ea-943d-effcffd1793d.png)

**Comment by xdamman** [comment]
The fact that you had to explain where it is shows that this is a UX issue, a lot of people will have the same question.

Indeed, when someone wants to submit an expense to a collective, they expect to be able to submit a receipt or an invoice. With this new flow, being able to upload the pdf of an invoice is effectively hidden behind an extra step.

The case of creating your own invoice is an edge case compared to those two main ones (even though I can understand why this case is quite common for the [Open Source Collective](https://opencollective.com/opensource)).

I'd recommend to make upload a PDF the default after clicking on "invoice". But with a link "if you don't have an invoice, you __can create one__".

**Comment by alanna** [comment]
Wow, overall it looks great! I'm so impressed. This will be a huge upgrade.

@Betree @piamancini I don't think it's quite ready for full rollout yet, though.

Some of the below issues are only "nice to have", but there are a few critical ones. I would prioritise 4, 5, 7, 9, 13, 16, 17, 19, 21 below, before release. 

I also think we should prep an email to send to all host admins at the same time as full rollout, as they will need to understand the differences for their process and should be the first point of contact for any confused users. We have to explain to them how system generated invoices work and recommend they update their expense policy wording (which shows in the sidebar now) because directing people to template invoices etc no longer makes sense. It's also an opportunity to inform them about how the payout options work and everything else.

1. Illustration is cutting off the radio button on the edge:
<img width="766" alt="Screen Shot 2020-05-05 at 9 49 27 AM" src="https://user-images.githubusercontent.com/5498878/81017068-b8ddf480-8eb5-11ea-964a-d2b9a894fc12.png">

2. When adding tags, you get no visual feedback after pressing `+`. At first I thought it didn't work, but then I click off and the new tags were there. They should appear as you click them.

3. It's very unclear that you can type into this box to search. It seems like you can only select what's showing in the drop down. I suggest the submitter is the first (pre-selected) option but the actual box remain blank with a search icon indication.

<img width="386" alt="Screen Shot 2020-05-05 at 9 54 55 AM" src="https://user-images.githubusercontent.com/5498878/81017392-7a950500-8eb6-11ea-9674-eed33a21e48c.png">

4. How do you create a new profile in the "who is being paid" part of the process? You should be able to trigger the flow to create a new profile and invite them from here. I mentioned this on Slack but fiscal hosts CANNOT pay to third parties for expense under another user's profile. The whole point of the "submit on behalf of" design was to allow users to do the paperwork for people who need to be paid, but not violate anti-money laundering practices or mess up tax accounting. The current implementation does not accomplish this.

5. How do you select an existing individual user (not org) profile in "who is being paid"? Like if I am going to submit and expense for Pia, right now I can't select her.

6. Tags are not showing on the expense summary screen.

7. Remove this attachment box for invoices! I don't know how many times I brought this up during the design phase, but this attachment box is **WAY TOO BIG**. It needs to be a tiny link somewhere way down on the page, NOT appear as if it's the main focus of this form. This design is to enable *system generated invoices* and if we make users think they *also* need to upload an invoice document they will be confused and frustrated. Uploading an invoice is an *optional extra* that I expect *and hope* only a minority of users will even access. We WANT them to focus on the system form because it makes the data way easier for us to ingest and manage, and reduces overhead for users because they don't have to fill out the info over and over. This was a key goal of the whole redesign. Please remove this box and turn it into a tiny "add attachment" link somewhere down the page, for people who want to include the invoice generated by their accounting software etc (tiny tiny minority of people). I think this is a case where the devs and designers working on this want to add attachments when they submit their own invoices so they think it's important but don't realise the vast majority of users are NOT like us (contractors) and that MOST users now use the default google doc template invoice and will switch to using NO uploaded document from now on.

<img width="797" alt="Screen Shot 2020-05-05 at 10 05 44 AM" src="https://user-images.githubusercontent.com/5498878/81018282-54706480-8eb8-11ea-8eab-f713f2a5fa09.png">

8. The payee info should be titled "payee info" not "vendor info". Most payees will not consider themselves "vendors".

9. Do we have the tax form system hooked up for when someone selects an org as a payee? We absolutely need that before allowing people to select an org payee for invoices. Right now I do not think the tax system can handle org profiles.

10. In my case my pay for invoices is going to an org which exists, but I'm not seeing it on the dropdown to select it (Protozoa). Is that because it's a host org? Confused.

11. On the expense summary page the payer information should be titled "Payer" not "Fiscal host". We're trying to make this screen act as a valid invoice, so we should use the standard terms.
 
<img width="241" alt="Screen Shot 2020-05-05 at 10 21 44 AM" src="https://user-images.githubusercontent.com/5498878/81019150-268c1f80-8eba-11ea-9ee9-a9294a1c985f.png">

12. As a fiscal host admin, I want to know how to get more required info (such as VAT number) to appear below my address on the invoice under the payer info section where the fiscal host name and address appears.

13. If you submit an expense then edit it, the Expense Submitted success banner appears before you have clicked "save". I think this is going to mislead users to not save their changes.

<img width="1191" alt="Screen Shot 2020-05-05 at 10 26 17 AM" src="https://user-images.githubusercontent.com/5498878/81019502-e5e0d600-8eba-11ea-9414-6eb95075a8d5.png">

14. I created a test expense to try testing expense deletion, but I did it in Engineering where I'm not an admin. Oops! Please delete for me. 

15. When you click the 'link' button, it copies the text after ? in the URL, e.g. https://opencollective.com/engineering/expenses/17521/v2?createSuccess=true - it should just copy the base URL.

16. Several issues with the below screen. The individual expense page should display the expense summary with all details, not a basic view as below. This is important because this screen function AS the invoice now. Many people will need to download or screenshot it for their records, and they need to be able to get back there easily. Also for invoice expenses, if there's not attachment, the attachment section should not appear. And showing "type" and "legal type" is weird. It should be "Location" and "type" to be friendly to the user, but actually I don't think we need to display these labels at all.

<img width="805" alt="Screen Shot 2020-05-05 at 10 31 23 AM" src="https://user-images.githubusercontent.com/5498878/81019868-b5e60280-8ebb-11ea-9a80-748c51caff6f.png">

17. The print option need to export the expense summary page as it appears in the design. Right now it's outputting a document with the wrong info on it. The details of the expense summary were designed to function *as a valid invoice* for people's records, but the download version shows the Collective instead of the fiscal host, missing a lot of info, etc.

<img width="861" alt="Screen Shot 2020-05-05 at 10 35 04 AM" src="https://user-images.githubusercontent.com/5498878/81020025-02314280-8ebc-11ea-9262-d1e586ed1114.png">

18. I think this was already mentioned but when I went to a completely different Collective to do another expense, the system had saved the data from the previous expense I entered. This is great when you accidentally close the window and need your text restored, but it should only activate if you go back to the *exact* same URL, not another expense or another Collective.

19. I entered my bank account details when I submitted an expense to Engineering. But when I tried to submit another expense to a different Collective, that payment method had not been saved for my profile, even though I ticked "save for future payouts".

20. If you try to submit a receipt expense with no attachment, the error says "This field is required". It should say "Receipt required" or "Attachment required".

21. How do I make a private comment on an expense comment thread? This is a very common situation when admins need to discuss confidential info like emails, bank account numbers, addresses, etc.

22. When viewing a rejected expense I can only see the "delete" option. I should also be able to re-approve it.

<img width="808" alt="Screen Shot 2020-05-05 at 10 52 05 AM" src="https://user-images.githubusercontent.com/5498878/81021071-6523d900-8ebe-11ea-86ec-50db3dde1171.png">

23. Under https://opencollective.com/opensource/edit/sending-money we should allow fiscal host admins to toggle allowed payout options, and these are what should so in the payout method dropdown to the user submitting an expense. So they can allow or not allow paypal, bank transfer, etc.

**Comment by alanna** [comment]
I am wondering if we should just remove the whole "who is being paid" option for MVP, and wait until we properly implement "submit on behalf". Because right now with this half-baked implementation it's going to cause more problems then it solves. We can regress to only allowing people to submit expenses under their own profiles so we can move forward with releasing the other upgrades to the flow, and then work on "submit on be half". 

We cannot have people submitting as orgs if the tax system isn't connected, and the feature really doesn't have much value if you can't create new profiles for your vendors which they activate and control themselves, or select existing individual profiles, with a flow for that person to approve the expense and confirm their account and payout details.

**Comment by piamancini** [comment]
@alanna Feedback is appreciated! Replies below: 

**Blockers**

- Tags not showing on summary
We'll fix

- Update invoice attachment design
We are not going to change the location of the dropzone, we've tested several options and also did user testing. Feedback was the opposite, they expect somewhere to drop an invoice they already have, even if then we ask them to fill up the details. 

- Payee info
We had vendor, since on a previous version we allowed people to create an organization on the fly for the vendor. Due to the money laundering feedback, we are leaving that feature for later. We need to solve a bunch of things like (what happens to an expense until the person approves the email, etc) Same for selecting another user on the platform, we need to solve the approval process, we can't have someone submitting an expense on behalf of another user without their approval.  For now you can only submit expenses on behalf of orgs you own. We will continue to solve this on other iterations. It's not a blocker for this release. 
 
We will revert back to Payee. 

- Add tax form warning
Yes, it's in the design, not implemented yet. 

- Submit expense as a host
The reason you can't find protozoa is because it's a host, we can on the to do list solving how this affects the computing of the host balance. We agree it's a blocker, it's on the list. 

- Check invoice styles (missing address) and add host as bill to
There's a bug there, we are missing fetching some info. We will fix this, but the design is not a blocker, we will continue to iterate.  

- Add complementary info on summary screen
Yep, this was in the design we missed it in the implementation.

- I think this was already mentioned but when I went to a completely different Collective to do another expense, the system had saved the data from the previous expense I entered. This is great when you accidentally close the window and need your text restored, but it should only activate if you go back to the exact same URL, not another expense or another Collective.

This is a bug, we'l look into it

- I entered my bank account details when I submitted an expense to Engineering. But when I tried to submit another expense to a different Collective, that payment method had not been saved for my profile, even though I ticked "save for future payouts".

Also a bug 

- If you try to submit a receipt expense with no attachment, the error says "This field is required". It should say "Receipt required" or "Attachment required".

Good idea. 

**Other feedback**: 
Tags: is a design issue - we'll send it to them. 

Sending money toggle: this is out of scope, please create a feature request issue. 

16 & 22: you are seeing the old flow - the expense list hasn't been released yet. You won't see this page anymore afterwards. 

21: we decided that having private and public comments in the list it's too confusing and a risk. You will be able to send a private email as an expense comment from the host dashboard. we expect host admins to do most of their interactions from the dashboard. 

11. Payer is not a denomination in our system at all, I think we should be consistent and keep Fiscal Host.

**Comment by alanna** [comment]
Cool, I had a feeling you were already aware of most of those things. Glad they are already underway.

> Payer is not a denomination in our system at all, I think we should be consistent and keep Fiscal Host.

In terms of our own system I completely agree we should be consistent. However these documents are going to be used outside our system (by definition that's why people are exporting them). I think in order for it to function as a valid invoice for tax purposes in most countries, it will need to indicate in some way that "fiscal host" is the payer, because the IRS sure doesn't know. How about `Fiscal Host (payer)` to serve both purposes?

> Add tax form warning

This doesn't answer my question specifically about how the tax form system and submitting expenses *as an org* interact. Will all the org admins be sent the email to submit the form to HelloWorks or just the submitter? Will we store the tax form against the org or the user? Will progress to the $600 threshold be cumulative between the user and the org or seperate? It will be very hard to tell the difference between a user submitting under their own name but paying out to their company (how I do it now) and users submitting as orgs, right?

> Invoice attachments

OK, I disagree, but if user testing shows it need to be so big, so be it. But can we at least move it under the system generated invoice form part so it comes after filling that out?

**Comment by piamancini** [comment]
> Will all the org admins be sent the email to submit the form to HelloWorks or just the submitter? 

Just the org admin that is logged in for now. 

> But can we at least move it under the system generated invoice form part so it comes after filling that out?

We tried that already and we feel that it's a worst experience because 
a) it's the first thing they look for
b) we make them fill up the form and at the end they discover the dropzone so they don't know if they fill up the form for no reason when they could've just dropped and invoice. It's a more frustrating experience. 

in the current design, they can drop an invoice but they'll need to fill form anyway afterwards, flow feels more natural.

**Comment by Betree** [comment]
All the feedback in this issues have been acknowledged - either by design or engineering. Thanks to everyone who participated here, all this feedback was super helpful for us!  

If you feel strongly about specific items that have not been addressed here, feel free to open dedicated issues to discuss them more in depth.

The new flow is now deployed as the default in production. We still have some iterations coming to improve it, but it's already ready for a new round of feedback. This one will be broader, as we are probably going to mention it on public channels: https://github.com/opencollective/opencollective/issues/3128
