### ISSUE TITLE
Changelog entries are not sorted properly

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3080]
**Describe the bug**
On https://changelog.opencollective.com, the first event is not where it should be. The order is:
- September 10th - 10th **2019**
- April 20th - 21st 2020

**Expected behavior**
All entries should be always be sorted by date descending. Maybe the year is currently ignored in the comparison?

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/79953597-685da480-847c-11ea-9adb-05aff788b789.png)

**Comment by SudharakaP** [comment]
@Betree : Just saw this a few moments ago. I think I know the root cause of this; have to think of a solution. :thinking: 

The problem here is that in our change log creation logic we take all the issues [updated since the specified date](https://github.com/opencollective/opencollective-changelog/blob/b67056f392634fd0d6e7ea28bf56174c57706013/scripts/index.js#L21). The problem with that is the issue in question (https://github.com/opencollective/opencollective/issues/2180), was updated on March 18th (Francois added a label) whereas the [updatedSince date before the change log was created was March 17th](https://github.com/opencollective/opencollective-changelog/commit/b67056f392634fd0d6e7ea28bf56174c57706013). Therefore that issue was also considered for the changelog.

**Comment by SudharakaP** [comment]
@Betree : Done. Let me know if you see any further issues. :smile:
