### ISSUE TITLE
[PROJECT] Fees on Top

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#3105]
## Purpose
(Why have we prioritised this?)
Since the onset of COVID-19 we've waived our fees for all crisis response collectives. This is a great opportunity to try giving the donors the option to pay for a fee - If it works well we can extend the 0 fee for collectives beyond June. 

We have [identified a couple of ways ](https://docs.google.com/document/d/1YfudytCCD5xGmtlUBzrS6zfzl8ldRIp_HdQLHheRM2A/edit)we can do this: 
- Offer donors to add a % of the contribution to their donation for the platform (gofundme / USA style)
- Offer donors to adda fix amount we calculate in advance (helloasso / EU style)

We could try this in these different ways for collectives hosted in Europe or in the US. If its too complex, then I think % model makes more sense, since it's what users are used to in the US where we are seeing the majority of the growth in this collectives. 

## Owner
(Name of core team member responsible for the project)
Project Owner 
@piamancini 
@Memo-Es we need a design owner than can quickly make a wireframe for it 
@znarf We need a technical owner who can already start working on the backend part. 

## Prioritization

- Does this serve our mission? 
Yes, it's helping us help more collectives raise funds and spend them transparently, removing the hassle of dealing with legal entities, taxes, etc. 

- Will this help to make us financially sustainable within a year?
Yes. We are currently waiving all our fees so this will help. 

- Is it feasible to build and maintain with our team and runway?
Yes

- Can this make us move faster?
Not relevant

- Does this increase quality and not technical debt?
Not relevant

- Will this bring us more Collective and financial contributors?
Yes - if we can have 0 fees for collectives and give sponsors the option, we'll have more collectives. 

- Is this already solved elsewhere or is it our unique contribution?
It's part of our value prop. 

## Roadmap & Timeframe
(Key milestones or phases and estimated delivery dates, including specs, design, feature development, feedback, marketing/comms, and documentation)

## Success metrics
(What we will judge outcomes of the project by)
Increasing our fees from each contribution
Increasing the number of collectives

**Comment by sbinlondon** [comment]
> * Offer donors to add a % of the contribution to their donation for the platform (gofundme / USA style)
> 
> * Offer donors to adda fix amount we calculate in advance (helloasso / EU style)

I think offering a range of fixed amounts would be a cool idea. They did a test of this in NYC with the taxi, which rely on tipping heavily. When faced with a choice people often only rounded up to the nearest $5 or $10 and would drastically under tip, or else not do it at all because it was extra mental work to calculate a 10-20% tip when they were probably in a rush to go somewhere.

So the taxis started offering fixed tips at the end of a ride. It would take your calculated fare and when you paid with your credit card, it would then pop up a screen that had a range of options. So if your fare was $40 they would say: "Would you like to tip?"

* 10% - $4
* 15%  - $6
* 20% - $8

And not only would people actually leave a tip more often, because the work was done for them, but they would often leave a bigger tip (most choose the middle option).

So I guess I would suggest a blend of the US/EU style - I think we offer 3 set $/£ amounts but also say how much it is as a % and give people a very easy way to just choose one. Take away the friction/mental work and more people will do it.

**Comment by Betree** [comment]
@sbinlondon that's a great example, I strongly agree with your conclusion.

To give some more details on how the french platform HelloAsso is dealing with that:
- They don't take any platform fee **nor** payment processor fee
- A default amount is always pre-filled, so the tip is opt-out
- If you want to remove the custom contribution, you actually have to get through a modal and check `I don't want to support HelloAsso` then confirm `No thanks, maybe another time` (see screencast below)


**Default HelloAsso donation**
- On 1€ donation, the default HelloAsso donation is 0.25€ (25%)
- On 10€ donation, the default HelloAsso donation is 2.35€ (23,5%)
- On 100€ donation, the default HelloAsso donation is 8€ (8%)

![Peek 04-05-2020 15-25](https://user-images.githubusercontent.com/1556356/80970564-a57e4b00-8e1b-11ea-9c24-a92b2296e75f.gif)

**Comment by Memo-Es** [comment]
### Design proposal

![Screen Capture on 2020-05-04 at 23-51-37](https://user-images.githubusercontent.com/49539954/81036039-2d3b7800-8e63-11ea-99b2-02b3a804a56d.gif)

**Comment by piamancini** [comment]
@Memo-Es thanks! The text is too long and - I think it needs to be more to the point. 
 
Can you paste all the copy here so I can edit?

**Comment by sbinlondon** [comment]
Update: the MVP is now shipped to production. Still to work on:

* setting minimum fee on top amount for $1 if the base amount is <= $10
* free event - in MVP we won’t address this but we will when we set the minimum to $1 for <$10?
* preserving the existing tip when we change the amount (i.e. if we pick 20% it would stay at 20%)
