### ISSUE TITLE
Add a new "ACCOUNTANT" member type

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3112]
## User story 
As an organization supporting collectives **or** a fiscal host, I need my accountant to be able to access the financial information such as receipts and reports. Adding them as `ADMIN` is not a nice option because it gives them too much privileges and because I don't want them to be displayed as `Collective admin` on my collective page.

For concrete examples, see:
- https://opencollective.freshdesk.com/a/tickets/6272
- https://opencollective.com/opencollectiveinc

## Best solution for this problem
Add a new `ACCOUNTANT` member type, that can be picked in the `Edit members` section. Members of this type:
- Should be able to download receipts on the transactions page
- Should receive monthly/yearly reports
- Should receive receipts by emails (once we implement #2867)
- Should not be displayed on the collective page (or displayed as "Accountant")

## MVP
- Add the new type on the API
- Adapt the "Edit members" section
- Update the code that sends reports to include accountants
- Update permissions to download receipts
- Update https://opencollective.com/opencollectiveinc 

## Documentation 
- We should update https://docs.opencollective.com/help/collectives/core-contributors#adding-or-changing-core-contributors
- We should update the texts on the "Edit members" page to explain what this role is
- Add the description on https://github.com/opencollective/opencollective-frontend/blob/e052f7c6fe97498584f883d0e63cfd96a0ea07d4/components/ReplyToMemberInvitationCard.js#L31

**Comment by Piedone** [comment]
What would cover our needs completely is just send out the bills in e-mail. E.g. Cloudflare has a setting to send out all e-mails to a billing e-mail address. Not further users needed, just the PDF invoices go out as e-mail attachment. What accountants mostly need is this, no further reports or details

**Comment by Betree** [comment]
@Piedone Sending the receipts by email is also planned, you can follow https://github.com/opencollective/opencollective/issues/2867 for this one.

**Comment by Piedone** [comment]
I don't think it's about sending bills out to a billing address, no?

**Comment by Betree** [comment]
@Piedone It's about sending the receipts (that are generated for each financial contributions) to the admins of the collectives and (as per the specs in this issue) to the members listed as "Accountants". In the end the feature will provide the same capabilities than having a billing address, except it will support having multiple ones - which is something also required by other organizations like https://opencollective.com/opencollectiveinc and fiscal hosts.

**Comment by Piedone** [comment]
I see. What I'm suggesting as an interim or supplemental solution is really just an e-mail address, no users at all. Creating users is another step that in the case of us for example (understanding that our use-case is not the only one, just talking about our experience specifically) would serve no use apart from gaining access to the invoice. Note that we're donors only.

Since all companies everywhere need to keep these invoices in their records I think the most important thing is to provide easy access to it. Since the administrative job of filing invoices is frequently not done by the person responsible for deciding over money, i.e. donating (or doing the technical or project management of an open-source project in case of entities receiving donations I'd guess but that side I don't know) that person might not need to know about Open Collective at all. They might not even be part of the company donating (i.e. an external accountant).

This is why a lot of online services send out invoices in e-mail, without requiring any kind of further login to access it (I'd say maybe 3/4 of all services we use at my company, and we use dozens). Out of these, the minority sends them out to users, which in the case of OC would translate to having a user account just for receiving bills. The majority lets and administrator configure a single, company-wide e-mail address when specifying billing details.

Note that a single e-mail address can have any number of recipients, which is actually the case for us as well, and kind of the point: billing@lombiq.com is received by everyone who should deal with it, so there is no single point of failure.

**Comment by alanna** [comment]
Good idea. Why don't you check directly with OC's accountant Dominick to get feedback before finalising the design? He is most familiar with what is needed.

**Comment by Betree** [comment]
Sorry @Piedone, we haven't had time to deal with it yet

**Comment by Betree** [comment]
Got a reply from Dominick regarding these changes:

> Hi Benjamin,
> 
> Thanks for reaching out.  I support the change to create a new “accountant” role- it works for us.
> 
> Once you have it set, we can define the emails with you that need to receive the monthly / annual reports.

This issue is now ready for implementation, but we still need to define a priority.

**Comment by Piedone** [comment]
Should this be already usable? Because as the Role I can still only select Admin and Core Contributor under https://opencollective.com/lombiq/edit/members.

**Comment by Betree** [comment]
Sorry @Piedone this hasn't be deployed yet, it should be ready between today and tomorrow. Please note that this release will not yet include sending the PDFs by email (which is tracked by https://github.com/opencollective/opencollective/issues/2867).

**Comment by Piedone** [comment]
Thank @Betree, I see. I could actually use this already.
