### ISSUE TITLE
Expense form: Validate addresses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3145]
https://opencollective.com/osc/expenses/15393

This expense came though without required info. This should not be allowed.

* No line item description
* No Payee address
* No payout method

<img width="852" alt="Screen Shot 2020-05-16 at 11 31 59 AM" src="https://user-images.githubusercontent.com/5498878/82103976-32ed6380-9769-11ea-803b-df7cbfbd62de.png">

**Comment by alanna** [comment]
Hmmm I'm wondering if this was created before the new expense flow? If so, then it's missing the attachment that would have been included.

**Comment by alanna** [comment]
Here's another one I just created. It's showing most of the info, but it's missing the full payee address details (my own address in this case) - it's not showing the city or post code. Without the proper address it can't function as a valid invoice for the host's accounting.

<img width="779" alt="Screen Shot 2020-05-16 at 8 08 26 PM" src="https://user-images.githubusercontent.com/5498878/82115534-740c6480-97b7-11ea-87a7-cd9022b64324.png">

**Comment by Betree** [comment]
From what I see this was submitted before the release of the new expense flow.
Other expenses like that still exist, they were created with the old flow and there's not much we can do except asking to update the info when they're missing

**Comment by Betree** [comment]
What would be the expected behavior for the one you created? Validating addresses when they can be from any country is not straightforward, to do it properly you need to have clearly separated fields for the different parts of the address.

**Comment by alanna** [comment]
Thanks @Betree - maybe we have some migration challenges with expenses submitted under the old flow? The expense I linked initially has no info and no attachment, but I assume those were there when they submitted it in the old form?

With address validation, we may have to have seperate fields, as we can't pay expenses (mainly invoices) without an address we could actually use to contact the person. I agree it's annoying because every country is different, but how about just `address` `city` `country` `postal code` as the most generic option? Like in NZ we don't have states/provinces and it's very annoying when they are required! I'm guessing millions of other web companies face this same challenge so maybe we could just pick up a standard design?

**Comment by Betree** [comment]
> maybe we have some migration challenges with expenses submitted under the old flow?

Not really because people were supposed to attach invoices in the old flow, if they didn't then the expense was already invalid and the new expense flow didn't change much about it. 

I however just spotted a bug that created some confusion here: because the expense type is `INVOICE`, we don't show the attachments for expense items on this page (host dashboard is not affected) - tho this expense does have an attachment. I'll push a fix for that today.

> With address validation, we may have to have seperate fields

We can do that indeed, needs to be checked with design to find something that does not overload the form. In my opinion this is a `v2`, not a `priority` because there's no regression - people could already submit expenses with invalid addresses on their invoices before the new expense flow.

**Comment by juliana0101** [comment]
Plano de projeto e comprometimento
Endereço
Conta bancária
Me ajudando

**Comment by sbinlondon** [comment]
Closing - please see https://github.com/opencollective/opencollective/issues/3630 for further discussion and solving.
