### ISSUE TITLE
Formatting broken in email notifications

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3186]
**Describe the bug**
This is how all expense notifications are looking in my email.
<img width="935" alt="Screen Shot 2020-06-03 at 10 05 55 AM" src="https://user-images.githubusercontent.com/5498878/83574577-dddf8900-a581-11ea-9c2d-4269772b069d.png">

**Expected behavior**
It should have space between the elements and they should be aligned horizontally.

**Comment by Betree** [comment]
I suspect we're seeing this because the email uses CSS `flex`, which probably have very bad support among email providers. We should replace that with a `table`.

This is how it's supposed to look like:

![image](https://user-images.githubusercontent.com/1556356/83604731-f26a5400-a576-11ea-8766-2083732af8c7.png)
