### ISSUE TITLE
Expenses list: add buttons to process expenses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3203]
:art: Design: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=1120%3A19272

We want to add the buttons to process expenses (`Pay`, `Approve`...etc) on the expenses list.

![image](https://user-images.githubusercontent.com/1556356/83854935-ad315800-a717-11ea-89d6-73e8f881d54c.png)

**Comment by alanna** [comment]
Did design resolve the issue where this is starting to become redundant with the host dashboard?

In order to pay expenses from this screen, you need a way to review expense details (attachments, comments, payment method), otherwise it's not functional for the host admin. But if you add those things, it's super crowded and also basically the host dashboard.

@Memo-Es you and I discussed focusing the design for this view on the other users *besides* the host admin. So info and actions for the public, the expense submitter, and the Collective admin. I think that design focus could help optimise this view, while we focus everything for host admins on the host dashboard.

**Comment by Betree** [comment]
@alanna there are two different designs for this component (one for the expenses list and one for the host dashboard). The one presented here is indeed more suited to collective admins.

@Memo-Es let me know if you want to integrate some of the feedback from @alanna before we start the implementation

**Comment by Memo-Es** [comment]
### We designed 2 different versions of this component depending on the context:

| **Public Collective's budget page**  | **Fiscal host dashboard**  |
|---|---|
| - Accesible by normal users and admins  | - Accessible only by admins  |
| <img width="3420" alt="Annotation on 2020-06-08 at 23-50-58" src="https://user-images.githubusercontent.com/49539954/84108483-e7d01480-a9e5-11ea-888c-f21902f8494a.png">  |  <img width="4854" alt="Annotation on 2020-06-09 at 00-05-39" src="https://user-images.githubusercontent.com/49539954/84108246-611b3780-a9e5-11ea-83c3-b26d13c38954.png"> |
| Try me 👉[Behaviour test](https://decisionmate.app/c/03b2a807c4)  |    |

This component update is included in the latest design system update #3209  

@alanna @Betree

**Comment by piamancini** [comment]
Thank you @Memo-Es This looks great.
