### ISSUE TITLE
Expenses list: add search bar

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3214]
Related to https://github.com/opencollective/opencollective/issues/3204
Design: [Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=3038%3A1126)

### API 

- [x] On `ExpensesQuery`, add a `searchTerm` string field. If provided, filter expenses to include those that contain this text in `description`, `id`, `tags`, `fromCollective.name`, `items.description`

### Frontend

- [x] Will be really close to the screenshot below, but we can expect a few changes on the placeholder text and the dropdown (that should be replaced with a search button).

![image](https://user-images.githubusercontent.com/1556356/84005443-6d63ae00-a96d-11ea-82c1-13da18a95503.png)

**Comment by SudharakaP** [comment]
@Betree : Hey, I've added basic support for this; here's a screenshot. Take a look and let me know if you have any specific things to alter. Currently the search is case sensitive and also you may notice that once we search something and then clear the search we don't automatically reset the filter; rather the search button needs to be clicked again. I kept it minimal so that we can add things later as needed. :smile: 

![Peek 2020-06-16 00-09](https://user-images.githubusercontent.com/12435965/84743456-d6978280-af66-11ea-8078-928507d3f91d.gif)
