### ISSUE TITLE
Fixes to manual payout confirmation screen

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3221]
There are some grammar and user experience issues here:

<img width="315" alt="Screen Shot 2020-06-09 at 9 15 09 AM" src="https://user-images.githubusercontent.com/5498878/84089716-d61d5a00-aa43-11ea-96dc-65aeec3042ac.png">

It should say:
> Processing fee (if any) 

*note: some hosts are charging a handling fee here, to cover the admin's extra time, not a payment processor fee such as a bank wire transfer fee, so let's make it generic*.

> Important: By clicking below, you acknowledge that you have paid this expense by other means.

Delete the sentence at the top saying "Please add the corresponding fees..." completely, because that's already communicated by the above wording.

The "Payout method" part should not be a dropdown menu, because that leads you to think you can change it here. Just list the payout method, including the details of it specified by the payee, in a grey box indicating it can't be edited on this screen.

**Comment by Betree** [comment]
> note: some hosts are charging a handling fee here, to cover the admin's extra time, not a payment processor fee such as a bank wire transfer fee, so let's make it generic.

For us it's really important to know what these fees are. The current input is stored in the ledger as `paymentProcessorFees`. If the host wants to set a custom fee, we need to store that info in `hostFees`. That's why it was decided at the time to have a very specific label (`Payment processor fees`) that you can't confuse with something else.

So from what I understand, if we want hosts to be able to add custom fees in there, we need to add another input.

> The "Payout method" part should not be a dropdown menu, because that leads you to think you can change it here

I don't really agree because the input is disabled. But that's one for Design/@Memo-Es

**Comment by alanna** [comment]
I understand what you're saying about payment processor fees being a specific thing, but in real life this is a free text box, and hosts are going to put whatever fee they are wanting to charge in there, not just the Paypal or bank fee. Like, if that payment method requires them to go in person to a bank, they might add $20 for their time. I think you could still call that "processing fee" though?

**Comment by Memo-Es** [comment]
Great, we were working on a shorter version of the modal for small screens, will take it into consideration.

**Comment by Betree** [comment]
@alanna if we just rename the label we'll end up with misleading information in our ledger. What about the solution proposed above of going back to 2 inputs, one for the host fees and one for the payment processor fees?

**Comment by Betree** [comment]
> if that payment method requires them to go in person to a bank, they might add $20 for their time. I think you could still call that "processing fee" though?

To add some clarity, it's not a problem with the label - I don't have a strong opinion on that. It's a problem of storing the information in the right place.

- If we store these $20 in the `paymentProcessorFee` (as we do today), we'll be storing misleading information because the bank did not charge those fees. If we ever need to query this data for whatever reason (taxes, accountability, metrics...) we won't be able to rely on it.

- If we store it in `hostFee`, it's slightly better because you can say that hosts are responsible for paying the processor fees and that it's included in the fees that they charge. But it's not great for transparency, and it will produce some strange results if we want to compute or display the "total amount charged by the host to the collective".

The only way to differentiate between the two is to have 2 inputs.

To visualize, we can think about the "transaction details" that is displayed for the expenses:

**Using `paymentProcessorFee`**
> $100 + $10 (10% payment processor fee) = **$110** (net amount for collective)

**Using `hostFee`**
> $100 + $10 (10.00% host fee) = **$110** (net amount for collective)

**Using two inputs**
> $100 + $5 (5.00% host fee) + $5 (5% payment processor fee) = **$110** (net amount for collective)

**Comment by alanna** [comment]
This is how we ended up with so many boxes on the current host dashboard:
![Screen Shot 2020-06-11 at 12 01 30 PM](https://user-images.githubusercontent.com/5498878/84330381-5a561580-abdb-11ea-99b6-6d89d1e02f3c.png)

It seems we need at least two boxes on this screen... I'm concerned it will be hard to communicate the purpose of them to users clearly, but we'll have to try.

Maybe call them `payment processor fee` and `extra host fee` to differentiate?

**Comment by Betree** [comment]
Yes, note that `Platform fee` is only displayed for root users.

I'll wait for an input form @Memo-Es before tackling this one.

**Comment by Memo-Es** [comment]
### Updated design for this is  👉🏼 [Here](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-05-UI-Kit?node-id=2116%3A0)

@Betree @alanna

**Comment by alanna** [comment]
I can't load Figma @Memo-Es - can you post a screenshot please?

**Comment by znarf** [comment]
Re-tagged and removed "bounty candidate" as it's not suitable for a bounty yet (clear spec and desired outcome).

**Comment by Memo-Es** [comment]
@alanna Posting the details of the modals as png

![Item](https://user-images.githubusercontent.com/49539954/85975591-1e260180-b99e-11ea-880b-8acfc7268124.png)

**Comment by Betree** [comment]
@alanna are we good with the design above, should we start the implementation?

**Comment by alanna** [comment]
Sorry I've been slow. It looks good to me. I haven't had time to dig into every detail but it looks good enough to start implementing. 

@alinamanko @piamancini please give any comments you have.

**Comment by alanna** [comment]
Ahh I thought of something! I just went to pay some expenses and I'm sitting there with my bank app open looking at the payment modal, and I realised I need to see the note the submitter left. Especially for "other" payment method, that's where the details I need to make the payment will be.
