### ISSUE TITLE
"Enable custom contribution" should be linked to the save button

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3263]
**Describe the bug**
I try to disable custom contributions for an event, but after unticking the box, it won't let me click save. The button is disabled and I get a little 🚫  symbol.

**To Reproduce**
1. Create or edit an event
2. Disable custom contributions by unticking box
3. Try to save

**Comment by Betree** [comment]
I tried to reproduce, it's an UX issue rather than a bug. The state of this checkbox is saved instantaneously, it's not linked to the `Save` button which is just saving the content of the form for the `Create custom tiers` section. The only thing that indicates that in the interface is the little spinner in the checkbox:

![Peek 22-06-2020 09-04](https://user-images.githubusercontent.com/1556356/85258260-75404980-b467-11ea-82c1-98beb56237c9.gif)

The contributor who implemented that didn't make a crazy call, for technical reasons it was simpler and more future-proof to do it this way. But the current behavior is confusing.

We should ideally solve this issue with #1451 by moving the whole form submission directly into the component.

**Comment by Betree** [comment]
The new edit tiers page (https://github.com/opencollective/opencollective/issues/3438) shouldn't be impacted by this since there's no save button. Putting a `wontfix` on this issue.

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective/issues/3438
