### ISSUE TITLE
Donating with PayPal

### ISSUE THREAD

**Issue by leena4c** [opencollective/opencollective#3267]
We held a first people assembly with collectives hosted by the AllForClimate fiscal host.

The question for the option 'donate to the paypall account' comes back very often as a feedback. Is there any possibility to make that possible?

Credit cards are not used very often in Belgium, it is just not part of the culture. We need to provide other, very easy ways of collecting money. Wire transfer is good, but  we also notice a lot of payments don't come through because of the extra email with paying details, and people somehow missing that email etc. 

The option for PayPall donations would help a lot. And maybe even a qr-code to pay with your bank app on your phone.

Thanks!!

**Comment by znarf** [comment]
@piamancini It is technically possible. We're currently blocked to extend that to more Fiscal Hosts because we need a decision on how to collect (or not collect) the Open Collective platform fees.

**Comment by leena4c** [comment]
Right now we are losing collectives because of these missing features. OpenCollective can not be fully used as a crowdfunding platform, because the options to donate are not adjusted to the European context where people don't use credit cards but pay pall, wire transfer and apps like pay coniq or ideal. Collectives like the accounting features, but don't see the value of the donation options and choose alternative platforms because of that. If we want to move forward as a fiscal host, those features seem to be crucial. (listening to the feedback of the collectives)

**Comment by alanna** [comment]
@leena4c While we are working on the underlying issues, for now you can instruct people to select "bank transfer" payment method. Then they can actually pay by any means, such as Paypal or any other app, and the host admin can mark it as paid when it's received anywhere outside Open Collective. It's not as nice an experience as if it was all integrated, but at least it will work and allow people to use their chosen payment method. The host admin can update the text of the message that is sent to users who select bank transfer, so it can include the Paypal address or other app info.

**Comment by znarf** [comment]
@leena4c I've been in touch by email. Long story short, we're willing to enable that for All For Climate.

If you want to move forward, could you answer to me and cc @piamancini ?

**Comment by Terrafire123** [comment]
Looking forward to this feature. In the meantime, I'll avoid OpenCollective and use other alternatives.

**Comment by znarf** [comment]
@Terrafire123 what's your use case? it's already available for a selection of Fiscal Hosts and we're slowly expanding. It might be that it's already available to you.

**Comment by Terrafire123** [comment]
I was trying to donate to https://opencollective.com/browserslist , and discovered the only way I could donate was via credit card.

**Comment by znarf** [comment]
> I don't feel comfortable letting OpenCollective save my card information.

How can we make you comfortable? For example, we're not storing any credit card data, we're relying on our partner Stripe for that. If our systems are compromised, we can't loose your credit card number because we simply don't have it.

> Is this something the owner of the project has control over?

They're using https://opencollective.com/evilmartians as Fiscal Host and PayPal is not supported for them at this stage. No need to harass them. We're slowly expanding PayPal support and it's something that should be available to them in the next months.

**Comment by Terrafire123** [comment]
>How can we make you comfortable?
Inside the registration flow, perhaps include the words, "Powered by Stripe, the secure way to pay! (URL to Stripe's website, to a page that has extremely reassuring language like, 'Trusted by millions of users!')".

>For example, we're not storing any credit card data, we're relying on our partner Stripe for that. If our systems are compromised, we can't loose your credit card number because we simply don't have it.

I didn't know that, and now that I do, I feel much more comfortable.

**Comment by Betree** [comment]
In the upcoming contribution flow revamp, we have this little info box which links to a page that describe how we handle data and the security policy around it (which includes the fact that we use Stripe, our security bounty policy, etc).

@Terrafire123 Do you think this link could have helped in your case?

![image](https://user-images.githubusercontent.com/1556356/90527497-e5223600-e171-11ea-9e9e-3a63b0bdd686.png)

**Comment by Terrafire123** [comment]
@Betree Absolutely. This is perfect.

**Comment by LyllouC** [comment]
Hi! Thanks a lot for adding payment options for one-off donations. Would it be possible to add these same payment options (bank transfer and PayPal) for monthly donations?

**Comment by Betree** [comment]
Hi @LyllouC, we are tracking this issue on https://github.com/opencollective/opencollective/issues/1141. We haven't prioritized it yet, so we can't provide an ETA.

**Comment by LyllouC** [comment]
Hi @Betree, thanks for your reply! Just checking in to find out if any progress has been made on this?
I know that the team at OC are working on many things so I do understand that this particular issue might not be a priority for you. However I am bringing it up because for most of our backers in Belgium, credit cards are not considered common, whereas bank transfer and Bancontact cards are, so I think adding theses options (and ideally PayPal too) for monthly donations would result in a real boost in our fundraising.
Thanks again for all your work, I hope everything's well!

**Comment by Betree** [comment]
@LyllouC Not yet, @alanna commented on https://github.com/opencollective/opencollective/issues/1141#issuecomment-713853570 yesterday to suggest we at least write some specs to see how complex it would be to implement recurring contributions with PayPal.

We won't have the capacity to work on this for 2020, but we may re-study the scope in early 2021 (based on the proposed specs).

Let's move the discussion about recurring contributions with PayPal to https://github.com/opencollective/opencollective/issues/1141, it will be easier to notice the users interest if comments are made there :slightly_smiling_face:

**Comment by smileBeda** [comment]
> None of the payment providers currently active on your account supports recurring contributions. You can enable them by connecting Stripe or PayPal. Alternatively, you can remove the ability to contribute recurringly from the [tiers settings](https://opencollective.com/dynamicpress/admin/tiers).

However, PayPal is not offered to collectives - only stripe (which is an extremely selective service, not available to more than 2/3ds of the world as payment processor) and Bank Transfer, which does not support recurring payments, and also probably is the least of all preferred methods (ask yourself this question: Would you sponsor a project with 5USD monthly, via Bank Transfers, which might cost you 30 USD if you are abroad?)

The least that can be done here is to update that message any collective Admin gets when they try to establish donation links.
The right thing however (believe me I know how hard it is to actually have good payment processors as partners, actually there are _none_ globally perfect solutions) to integrate Paypal, because it is, like it or not, the _only_ globally acceptable solution also for private entities (not everyone on OC is a company, and stripe, apart of being selective and pricey, doesn't allow private persons to have an account).

Thank you!

**Use case**
Currently small, but aspiring to get big public, free knowledge platform that is desperately looking for a way to finance their server and domain expenses in a transparent way.
