### ISSUE TITLE
[ENHANCEMENT] Recurring contributions with fees on top

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3290]
The recurring contributions revamp did not deal with fees on top (displaying info about them on the frontend, or dealing with them in contribution updates on the backend). 

We've removed the ability to 'reactivate' a recurring contribution until we figure this out. Since @kewitz has finished up the last bits of the fees on top project we can now look at it as a whole and figure out how it'll fit in with recurring contributions and editing/cancelling/activating them.

**Comment by znarf** [comment]
We actually haven't decided to disable "Reactivate" just for this reason, but because there were too many unknowns in the behavior of the feature.

Right now, there is a priority on surfacing "Fees on Top" in the Recurring Contribution cards so it's clear they are attached to the contribution. We should not try to deal with editing, we should keep that for later.

**Comment by znarf** [comment]
@sbinlondon Marking that as priority for next week.

**Comment by sbinlondon** [comment]
Work for Monday:

- [ ] Add 'fees on top' to styled card so user knows they are on the contribution
- [ ] open PR, get feedback from Leo

**Comment by sbinlondon** [comment]
Closing this issue and opening a new one for renaming 'platform fees'
