### ISSUE TITLE
System not saving full bank payout info and unable to add it

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3291]
When submitting an invoice, I select my organisation as payee, then select the saved bank account I input previously. But the system has not saved all the details (missing address), so it won't let me proceed. But it also won't let me add the details. So I have to create a new bank payment method every time, and now I have four identical payout methods saved, none of which I can actually use.

<img width="667" alt="Screen Shot 2020-07-01 at 10 47 52 AM" src="https://user-images.githubusercontent.com/5498878/86184919-3efe7a80-bb89-11ea-9785-391ab855e8b7.png">

<img width="371" alt="Screen Shot 2020-07-01 at 10 50 51 AM" src="https://user-images.githubusercontent.com/5498878/86184883-2a21e700-bb89-11ea-842b-b35b6522f224.png">

**Comment by Betree** [comment]
Same here, I can't use my existing Transferwise linked account and no error is displayed so it's unclear why the Submit button is disabled (related to what was reported in https://github.com/opencollective/opencollective-frontend/pull/4441#discussion_r441549859 I think).

Marking this as a priority as it may be blocking payments for anyone with an already linked bank account.

**Comment by sbinlondon** [comment]
Another small bug: I was also not able to proceed with my invoice with my old IBAN details selected, so I went to select "new bank account" and no form appeared. I was really confused and thought it was a bug with the form not rendering. But then I selected another option and clicked "new bank account" again and noticed that this time the 'currency' field asked me to select a currency, and once I clicked it the form appeared. Whereas before, when I selected "new bank account" from my IBAN details, it carried over the 'EUR' currency and I'm assuming because I didn't make a change to the 'currency' field, then the form wasn't rendered.

![Jul-03-2020 15-28-55](https://user-images.githubusercontent.com/37520401/86478631-706e7600-bd42-11ea-86c3-ccf91ef28861.gif)

**Comment by Betree** [comment]
@sbinlondon this is another issue documented in https://github.com/opencollective/opencollective/issues/3292

**Comment by kewitz** [comment]
Hey guys, I'm investigating this and it seems that address is now required for every currency.
This means that older payout methods are now outdated and will need to be updated.
Although the dropdown displays identic payout methods, they're actually referring to the multiple created payout methods and the ones that have the address should be valid for reuse.
There was another problem here, the bug related to fields not being updated would prevent you from seeing which one of the created methods actually had the address.
So, fixing this should provide all you need to clean and fix your payout methods.

**Comment by kewitz** [comment]
We're now able to delete and recreate the new payment method with the required address. The bug in the dropdown is also fixed. Closing this.
