### ISSUE TITLE
Fiscal host address missing from invoice

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3302]
On the expense summary there is no address under fiscal host.
<img width="793" alt="Screen Shot 2020-07-02 at 10 28 54 AM" src="https://user-images.githubusercontent.com/5498878/86297557-c44c6280-bc4f-11ea-82a3-2ed41d91be31.png">

But the address is saved in settings.
<img width="742" alt="Screen Shot 2020-07-02 at 10 34 54 AM" src="https://user-images.githubusercontent.com/5498878/86297564-c8788000-bc4f-11ea-84c8-d589fb569d28.png">

**Comment by Betree** [comment]
It seems that because this is a host, we're not fetching all the fields that we should: https://github.com/opencollective/opencollective-frontend/blob/9302f86dfc029616a1ef252dd7a3096e9601d703/components/expenses/graphql/fragments.js#L147

@znarf as an alternative, in `hostResolver`, could her return the collective itself when it's a host? Like:

```es6
{
  account: Account({
    slug: 'opensource',
    isHost: true,
    host: Host({
      slug: 'opensource',
      hostFeePercent: 5,
      ...
    })
  })
}
```
