### ISSUE TITLE
RFC: Moving out of utils.resetTestDB

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3305]
I wanted to open this issue to discuss the `utils.resetTestDB` that I think we should stop (ab)using, for the following reasons:
- It's **heavy**: the tool drops all the data then recreate the entire schema. On my local machine, that's almost 1 second.
- In many places we use it in a `beforeEach`, so **we're adding almost 1 second to each test**
- It's using `sequelize.sync`, recreating the DB from the models and **ignoring the migrations** (a big diff compared to other envs)
- It's usually **not necessary**, the cases where you need an empty DB for your test are very marginal

---

I'd like more feedback from @opencollective/core-developers, I'm not sure why we're using that helper everywhere and may have missed some cases.

**Comment by kewitz** [comment]
This is complicated because we have a mix of unit and integration tests.
See GQL mutation tests, for example, there are tests where we generate a query and verify mutations in the DB.

> It's usually not necessary, the cases where you need an empty DB for your test are very marginal

I think the main idea behind clearing the DB is to guarantee tests are mutually exclusive and also, simplify tests.
I'm OK with removing the DB state of the equation and not resetting it, but I think this could generate a whole new set of problems like inter-test dependency.
If we're strictly looking for faster tests, perhaps we could try truncating tables?

**Comment by Betree** [comment]
> a whole new set of problems like inter-test dependency

Do you have examples of how this could happen? Except when we count entries in the DB, I don't see many cases where a test would fail because of another one, nor how GQL mutations affect this: our tests run synchronously.

> If we're strictly looking for faster tests, perhaps we could try truncating tables?

I'm also looking for simplification, and reproducibility: the fact that we create the database with `.sync()` in tests means that we may not be testing with the same structure as dev/prod, where the database is prepared through migrations.

**Comment by kewitz** [comment]
Every test that requires a specific unique property of a model could be compromised.
For example, testing fees on top requires OpenCollective and its host to be created with a specific id.
If tests are strong, we'll just need to replace the suite/test DB seed function with a single initial seed for the whole testing script.
Another example is the use of a fixed mocked date by older tests.
That will probably require some refactor since we won't be able to create multiple collectives with the same slug.

Although our tests run synchronously, we can't guarantee the order they will run since we can add new files and tests that will mess with the same record in the DB.

I think this is doable, we just need to define clear rules on how to write tests so we don't end up writing tests that break other tests.

**Comment by Betree** [comment]
The most problematic thing is probably the fact that we rely on specific IDs for some hosts/collectives.

A good first step to me would be:
- To only use `utils.resetDB` if necessary
- If possible, use it in `before` (not in `beforeEach`)
- To add a comment whenever we add a `utils.resetDB` to explain why it's necessary

Closing as the complexity/gain ratio doesn't seem great at the moment.
