### ISSUE TITLE
Redesign tiers

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#331]
We should have multiple types of tiers:

- tickets: name, description, amount, quantity (the current design we have in events is fine for it, e.g. https://opencollective.com/sustainoss/events/2017)
- product: name, description, fixed amount (e.g. become a sponsor for that event for $500)
- donation: name, description, custom amount (choose amount and frequency). We really like what Women Who Code has on their website for that, see https://womenwhocode.com/donate

I think that would be a good start to have a constant component to handle those 3 different use cases.

**Comment by cuiki** [comment]
Hi @xdamman, here's a first attempt at redesigning the tiers. I modified them in order to make them a same component with variants, but generally the same structure.

1. Tier type: **Ticket**
2. Tier type: **Product**
3. Tier type: **Donation**

![widgets-tiers](https://cloud.githubusercontent.com/assets/981188/24384022/215d8514-131e-11e7-98b2-281d8e4ac2ac.png)

Zeplin link: https://zpl.io/Z1EyAaz

Let me know your thoughts/feedback.

**Comment by cuiki** [comment]
Hey @xdamman, for this you asked me to do the edit versions and that they should be inline. Can you provide the fields needed? Some are obvious but I'm not sure how many options will the user have. Thx

**Comment by cuiki** [comment]
Hey again, I did this example for the tickets tier, based on the API that @asood123 shared with me. Let me know if this is the right path for this and if the fields are correct.

![screen shot 2017-04-05 at 11 29 26 am](https://cloud.githubusercontent.com/assets/981188/24716137/8422cd68-19f3-11e7-8626-01028bd43623.png)
