### ISSUE TITLE
Host fees added to host budget showing as debit instead of credit

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3317]
I'm pretty sure this is related to the switch to having the host budget integrated on the host page. To add these fees, I think I went to dashboard and selected Open Collective Foundation from the Add Funds dropdown. They should be showing as a credit to the budget.

![Screen Shot 2020-07-07 at 10 29 19 AM](https://user-images.githubusercontent.com/5498878/86658206-fa695800-c03c-11ea-8d18-37d923bb098a.png)

**Comment by alanna** [comment]
Ah, related, the old Foundation Collective is still active: https://opencollective.com/foundation-collective

This needs to be closed down and the transactions merged into the host budget.

**Comment by znarf** [comment]
They were counted as a debit because they were indeed moved from the Organization (foundation) to the Collective (foundation-collective).

We were not supposed to have anymore transactions registered to foundation-collective. I've now cleaned the transactions and this is looking good. https://opencollective.com/foundation/transactions

<img width="1101" alt="Screenshot 2020-07-28 at 16 32 50" src="https://user-images.githubusercontent.com/806/88680194-84fb1f80-d0f0-11ea-8b4b-3693f6c5eba1.png">
