### ISSUE TITLE
Homepage design enhancements (July 2020)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3321]
# Design

:art: See [Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=4541%3A120024)

# Changes summary

## General typography update

All typography on this page should be reviewed and updated if necessary (`lineHeight`, `fontSize`, `fontWeight`).

## Are you ready to make your community sustainable?

Move this section at the bottom (see design)

## Hero layout change 

![image](https://user-images.githubusercontent.com/1556356/86926869-e4d65a00-c132-11ea-8328-c917a7f7d6d1.png)

## Do you need a fiscal host... ?

This new section should replace "Open Collective for Fiscal Hosts".

![image](https://user-images.githubusercontent.com/1556356/86927143-3c74c580-c133-11ea-9924-e2aec02d51ca.png)

## We are open in every way + learn more

Update to the latest design, use new illustrations

![image](https://user-images.githubusercontent.com/1556356/86927718-f79d5e80-c133-11ea-824d-2c8c3e7f4c45.png)

## Contribute to the platform

This is a new section. As per `Are you ready to make your community sustainable?`, it must be animated on hover but let's take that as an opportunity to improve it: both images must be initially loaded and animation must be triggered through CSS (to prevent image flickering). Checkout [this link](https://github.com/opencollective/opencollective-frontend/blob/5d230fb72fcb11610420e4195bcad9999770aae9/components/expenses/ExpenseTypeRadioSelect.js#L75) if you need an example on how to do that.

![image](https://user-images.githubusercontent.com/1556356/86927853-20255880-c134-11ea-838c-6d4a00d96376.png)

## Join the movement 

Layout + illustration change

![image](https://user-images.githubusercontent.com/1556356/86928533-f6b8fc80-c134-11ea-94c6-92e3943105a0.png)

**Comment by alanna** [comment]
Let me know if help is needed with copy text

**Comment by Memo-Es** [comment]
@alanna Can you take a look at the copy?

![1280 px - Desktop](https://user-images.githubusercontent.com/49539954/87372892-3f662080-c54e-11ea-86c2-bac8562e6e7a.png)

**Comment by alanna** [comment]
Changes (top to bottom):

Period on the end of "Collective and spend money transparently."

Below **What's great about Open Collective** change description text to:
> Money management made simple, plus great tools for community engagement, budget reporting, and fiscal sponsorship.

Under **Spend money**
> pay in one click with Paypal or bank transfer

Discover the possibilities of our features > Discover our features.

### Fiscal host section

**Do you need a fiscal host?**
Need help holding money on behalf of your project? Fiscal hosts handle taxes, accounting, and payments for you.

These are our fiscal hosts > Find the right fiscal host for you

Can we add a few words of description under each host title? I think it would help a lot.
* Open Collective Foundation: for US charity initiatives
* Open Source Collective: for open source software projects
* Open Collective Europe: for EU-based groups
More hosts ->

Become a fiscal host
> Support your community with fundholding and fiscal sponsorship services. [Learn more]

### **We are open in every way**
* Documentation: About us, how to create a Collective, become a fiscal host, contribute code, and much more.
* Slack: Come meet the team, chat with the community, and share your questions and stories. *(note: it's not a slack "channel" because each topic inside the slack is a channel, so just say 'slack")*
* Blog: Case studies, news, and how groups around the world use Open Collective.
* Open Company: See our public *data* ->

**Contribute to the platform**
> Open Collective is free for charitable initiatives. We rely on generosity of contributors like you to make this possible. [Donate]

**Join the movement section**
I think some of this content is redundant. I suggest we remove the "join the movement" text and subtext, and just have "Create a Collective" button and "subscribe to our newsletter" here. If 'read our stories' points to the blog, we already link right above and below there to the blog.

**Footer**
Change tagline under logo to "Make your community sustainable"
Under 'platform' change Discover to "Explainer video" (because we link discover in the next column)
Change "join the movement" to just "Join" and change links under there to:
* Create a Collective
* Discover Collectives
* Find a fiscal host
* Become a fiscal host
Community - remove forum and change to "help & docs"
Company - where does FAQs link? Replace that with "contact"?

@Memo-Es

**Comment by Betree** [comment]
Done by @flickz
