### ISSUE TITLE
Collectives should not have the option to hide their budget and contributors

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#3324]
We just realized that this option has been added to the settings of the collective. 
But this goes against the very principles of open collective.

With allforclimate.earth we cannot take the risk to host collectives that wouldn’t share publicly their budget and list of contributors.

**Comment by Betree** [comment]
There are some legit uses cases for hiding these sections, for example you may want to start a collective just to get conversations and updates, without managing any budget. As we're trying to serve different types of projects (especially with the latest developments for Funds) this flexibility has been very helpful to accommodate for the various differences and let each initiative take the most value from their collective page.

It's also important to note that it hides the section from your profile, but it doesn't remove the feature itself: you can still track the budget from the transactions and expenses pages. 

That being said, it's an important conversation to have. If this feature goes against Open Collective's mission then we should reconsider it.

**Comment by alanna** [comment]
Maybe it could be a host-level setting whether hiding budgets is allowed?

Just to confirm, even if a Collective hides their budget, logged in admins of that Collective and its host can still see it, right? It's just hidden publicly.

**Comment by znarf** [comment]
For context, the issue to track this feature was https://github.com/opencollective/opencollective/issues/2424

> Just to confirm, even if a Collective hides their budget, logged in admins of that Collective and its host can still see it, right? It's just hidden publicly.

As of today, "hidden" is hidden for everyone, making it different for admins would be confusing. In "Funds", we're exploring the possibility of turning it on "Only for admins".

<img width="951" alt="Screenshot 2020-07-13 at 01 10 23" src="https://user-images.githubusercontent.com/806/87258674-b72c4080-c4a5-11ea-945e-9726db502789.png">

**Comment by xdamman** [comment]
The problem here is that collectives that do have transactions can now hide them and that goes very much against the principles of OC. 

If there are other types of profiles such as Funds (I'm not sure what it is), then it could be different for them but I'd argue that then those profiles should be clearly labelled as "Funds" and not "Collectives" (for which the expectation is full transparency of their transactions).

Also, it feels like this is right now needed for a very small number of collectives. So until a more long term solution is found, I'd remove the interface to change this (or hide behind a feature flag).

**Comment by piamancini** [comment]
There are very legitimate use cases for people protecting their transactions, just to name a few (we are supporting): medical bills for member of the black trans community, anti-surveillance and human rights activists, people working in privacy sensitive projects, women at risk of doxxing and online harassment. As we always knew, full transparency comes at the cost of high exposure and this is not a privilege everyone holds. The difficulty lies in upholding a principle, while understanding nuances and specifics of the different communities we serve. 

That said, the ability to share the budget with smaller group of contributors (donors, admins and hosts for example) is a feature still experimental and one we rolled out specifically for Funds. 

I didn't expect it to be rolled out to all collectives until we see how it behaves and make provisions for organizations who might not want their collectives not to be fully transparent. 

@znarf can we remove the option for collectives so hiding the budget doesn't appear in the list and it does only for funds? 

thanks!

**Comment by znarf** [comment]
@piamancini For the record, it was not part of the "Funds" work, it was part of the "Edit Collective Sections". https://github.com/opencollective/opencollective/issues/2424

Seems, we just want to make sure that "Disabled" is not an option for "Budget". @kewitz or @sbinlondon may tackle that this week.

**Comment by piamancini** [comment]
@znarf yep - @kewitz will do it. 
Leo, please note, this option should still be the case for Funds - is should only be disabled for collectives.

**Comment by kewitz** [comment]
If I'm not mistaken, Projects are also a subcategory of Funds, with that in mind, are projects also allowed to disable the budget section?

**Comment by alanna** [comment]
I believe there are good "happy medium" solutions for the transparency/privacy tension with expenses. The trick is designing well enough that people can use them effectively. What we see happening now is users are not clear about what exactly is public and what their options are to deal with it. For example we made expense comments private because people were constantly putting private payment info and addresses and stuff in them. Communicating which parts are private and public on the expense form is a hard problem.

Solutions with current feature set:
* User signs up with a pseudonym and only puts their real name on the payout info which is private
* Use very generic expense title and description (like 'rent support' but not who for) and use the private notes box for more details (like the recipient name)

Right now we're not communicating the above options or giving effective enough warnings about public/private info. We really don't want situations where someone accidentally shares private info and suffers bad consequences from that.

Ideas for new features:
* Incognito expenses, where the profile association is only visible to the admins, like incognito contributions, but the public can still see the Collective paid out x number of expenses for y amount.
* Collective-level settings to hide all expense titles and descriptions but still show the transaction amounts, or even hide amounts and just show a total per month or something.
* Collective-level settings so budget is viewable to logged in users only, or people associated with the group only (contributors, admins, etc) - this is still a big step up from only one or a few people in the community having visibility on the finances, to the whole community having it.

I agree that we should push our tool to guide people toward more transparency, and sometimes that means making the defaults open, because it's part of our core values. But we should work on creative solutions to meet the various needs we encounter.

**Comment by kewitz** [comment]
There's a lot of space for privacy tools in our platform but I'm not so sure we should enforce transparency on every collective.
I agree with @alanna, I think it's enough to provide transparency as a feature because there are collectives that want to use it, but if privacy is crucial to a set of people looking for financial hosting, I don't see why to enforce it.
Nonetheless, disabling the budget section is not the way to go because it might give an illusion of privacy when everyone can access the transaction list through the URL.

For now, we're blocking anyone except Funds and Projects from hiding the budget section.
There are a few collectives that already disabled the section, we'll email them explaining why we rolled back this "feature" and refer this issue for further discussion.

**Comment by znarf** [comment]
The ability to remove some sections of the collective page should only be seen as "visual customization". There is so many ways to access the data elsewhere, especially through our API, that we should never sell it as a privacy tool or anything similar. At least at this stage.

**Comment by Betree** [comment]
As a follow up on this issue, it may be good to add a small section to the FAQ for collectives, like `Why can't I hide my budget section?`. Proposed content:

> Open Collective is all about transparency, and hiding collective's budgets could go against this value.

![image](https://user-images.githubusercontent.com/1556356/88149184-ff630580-cbff-11ea-97b0-085201608996.png)
