### ISSUE TITLE
Two to sign for payouts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3328]
## User story 
As a fiscal host admin, I want to implement financial risk management best practice, so I can meet governance requirements and avoid misuse of funds.

Many organizations require 'two to sign' for payments, meaning at least two people have to sign off. This is often implemented in banking, where the same person can't both set up a payment and push the button to send it. This is best practice because it means no one person can get away with doing anything dodgy with the money. It's one of those things that seems just annoying, until someone defrauds you (or simply makes an error that wouldn't happen if two pairs of eyeballs checked) and you realize why it's important.

## Best solution for this problem
In the Open Collective context, there are three roles involved in paying out an expense: submit, approve, pay. I suggest an optional fiscal host setting that will not allow a single person to play all three roles for a single expense. 

For some small fiscal hosts (like self hosted Collectives), they would not turn this on because there might only be one person involved who needs to do everything, but for larger or stricter organizations, it would be necessary.

This could be implemented in a few ways:
* Not allowing people to approve their own expenses
* Not allowing people to pay their own expense out
* Only allowing a single person to play two out of the three roles, so they could submit and approve, but not pay, their own expense, or they can approve and pay someone else's expense that they did not submit.

## MVP
What we're doing for OSC and OCF is just verbally telling all the admins and staff not to approve their own expenses and instead approving each other's. It works OK informally, but it's not as foolproof as a technical solution.

**Comment by alanna** [comment]
I don't think this is a big priority at the moment but I wanted to have an issue raised in case it comes up in the future from third party hosts or requirements of compliance audits (for example I wouldn't be surprised if some large funders to OCF ask if we have such a policy in place @piamancini).

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/3081

**Comment by alanna** [comment]
I think this might be addressed by the work @sbinlondon is doing on 2fa?

**Comment by sbinlondon** [comment]
Read my mind @alanna I was coming here via the 2FA issues to see if that ticked the box. Should we leave this issue open since 2FA doesn't *exactly* do what you were describing, or can we close it since 2FA is in essence providing more security, just in a different way? We can always reopen or open another issue if people request another specific security practice.

**Comment by alanna** [comment]
We should leave this open. 2FA is great for added security, but it won't satisfy the requirements of "two to sign" which literally means two separate people have to sign off on a payment.

**Comment by BenJam** [comment]
closing in favour of https://github.com/opencollective/opencollective/issues/3081

**Comment by Betree** [comment]
@BenJam though strongly related, #3081 is different: it's about requiring multiple **collective** admins for approving an expense. This one is about requiring multiple **host** admins to **pay** an expense.

**Comment by BenJam** [comment]
Starting to think about this as parallel to [GitHub pull request reviews](https://github.blog/2018-03-23-require-multiple-reviewers/)

- [ ] add a 'require multiple approvals before paying expense' to host and collective admin settings (within policy on host side) as a dropdown, similar to [this image](https://github.blog/wp-content/uploads/2018/03/36898307-92cc9b38-1e1a-11e8-9010-9728260ac7d4.png?resize=746%2C484)
- [ ] add 'requires X more approvals' notice to expenses that require more approvals
- [ ] add 'Approvers cannot pay expense' checkbox option to both Collective and Host (again in Policy) settings.
- [ ] replace 'go to pay' button with 'payment blocked' notice describing that you cannot pay this expense as you are an approver. 

Optionally we could also 

- [ ] add 'invite approval' process for other admins, similar to 'invite expense' process
- [ ] add 'unapproved and invite' as an alternative process when payments are blocked

WDYT @Betree @alanna @opencollective/design ?

**Comment by alanna** [comment]
I think @BenJam 's description above is great for a full fledged version of this feature. But we might want to scope an MVP just focused on setting the number of approvals required at the Collective level. 

OpenMined has identified this as a priority for them, and as one of OCF's largest Collectives, that makes it priority for OCF as well.

**Comment by BenJam** [comment]
> OpenMined has identified this as a priority for them

@alanna which aspect(s) are most important for them, and how does that map to an MVP? 

There's a natural split between multiple expenses/two to sign, and I'll update my comment to reflect that. I assume OpenMined have one of those as their priority?

**Comment by alanna** [comment]
Their words:

> Multi-tier approvals — the ability for me to set a review process (me, then Andrew, as an example) could streamline things for bigger collectives.

**Comment by alanna** [comment]
Sorry I think I added this comment to the wrong issue @BenJam - their priority is about multiple approvals of an expense by the *Collective Admins* not multiple approvals for payouts by Host Admins.

**Comment by Betree** [comment]
> add 'Approvers cannot pay expense' checkbox option to both Collective and Host (again in Policy) settings.

@BenJam Which problem from the use case above is this solving? It doesn't seem like a very useful rule, and it can easily introduce unwanted side effects. For example:
- Host admin ask a user to update payout information
- The user updates the expense which goes back to `PENDING`
- Host admin approves the expense, but cannot pay it since "Approvers cannot pay expense"

**Comment by piamancini** [comment]
@BenJam @Betree @znarf to schedule a call to scope this properly

**Comment by BenJam** [comment]
plan for this week:

- [ ] spec out some of the detail and think about a delivery strategy/MVP

**Comment by kewitz** [comment]
This problem is a bit more complex than it looks and part of this complexity comes from the organizational structure of the fiscal host. No matter how many signees are required to pay an expense, an admin can always edit the collective or create another admin account to bypass this protection. So, it is not hard to see this as a governance issue for expense payment and collective management.

We could simplify this issue by increasing the hierarchy, creating a superior administration level where the _super admin_ is the only one that can add new admins and change the setting requiring multiple admins to sign for an expense.

Another way to tackle this issue is to require two specific users to sign for an expense. In this scenario, it would only be possible to exploit expenses by gaining access to the other admin account. Open Collective as a platform would be acting as the institution that sets which admins would sign payments.

The decentralized way of solving this is by implementing a system where admins must approve each other's actions. In this scenario, multiple users are required to set up the number of expense signees, invite new admins, pay expenses, etc...

**Comment by alanna** [comment]
I think it's fine to build this feature for with only good faith actors in mind. I don't see this as a problem. Unlike 2FA this feature will be used not for security but for governance. It's enough that we simply show on the expense who approved it when. If there's a rogue admin deleting other admins or faking their identity, it's really beyond the scope of this feature to address that.

**Comment by BenJam** [comment]
my bad for setting this thread off on this path but most of the discussion above has flavours ofhttps://github.com/opencollective/opencollective/issues/3081 rather than the two-to sign requirement i.e. approvers cannot be payees. @aminakazi designed up the multiple-approval (I have left a link in the other thread) but I don't think the 'two-to-sign' requirement is reflected there. 

For me, the requirement for _this_ issue is simply 'approvers cannot be payees', which I think is covered in the above:

> *  add 'Approvers cannot pay expense' checkbox option to both Collective and Host (again in Policy) settings.
> * replace 'go to pay' button with 'payment blocked' notice describing that you cannot pay this expense as you are an approver

**Comment by znarf** [comment]
Thank you @BenJam it's a good start indeed!

**Comment by Betree** [comment]
I'm ok with the proposed solution, I think that's a good and simple MVP. We should however be really careful with how we communicate, as this rule will be very easy to bypass (see https://github.com/opencollective/opencollective/issues/3328#issuecomment-987113391). It can be considered as a governance tool but in no case one that guarantees any kind of security.

Also, we haven't addressed the concerns in https://github.com/opencollective/opencollective/issues/3328#issuecomment-926476574. It's not a blocker for me, but I can see support requests coming our way quite quickly. Could we limit the "Approvers cannot pay for expense" rule to collective admins (and not host admins)?

**Comment by znarf** [comment]
What about an Expense payee not being able to Approve their own Expense? Isn't this also important?

**Comment by BenJam** [comment]
> What about an Expense payee not being able to Approve their own Expense

++ This is actually likely to be way more impactful for us... how many host admins are approving expenses for collectives vs. users approving their own expenses...

**Comment by BenJam** [comment]
just to formalise: we should add the 'payees cannot approve own expense' setting at the collective level in https://opencollective.com/octobox/admin/policies. Sorry that i didn't pick that up above :/

**Comment by jfdh** [comment]
After reading this thread, I feel like the "approver cannot pay for expense" at the host level could be a useful feature between admins. 

For now I am the only one managing the Admin panel on OCEU, so I do not really need it. On the other hand and if another person would be involved, it would definitely be a must. However I would still like to have a _'Super Admin account'_ with full access. I often use my full admin access to upload /edit - (re)approve - pay expenses for collectives.

**Comment by alanna** [comment]
In ideal cases I agree this feature will be great. But as JF said, there
are many cases where, for example, an expense that has been approved (by
someone other than the submitter and payer, if this feature is switched
on), but then there's a small issue and it needs to be edited and the host
admin is sure it's all fine to go. If they are blocked from processing it
at that point because they cannot re-approve it and pay it themselves, it
will be a headache. Not sure how we can handle this.

**Comment by BenJam** [comment]
burning this issue in favour of https://github.com/opencollective/opencollective/issues/5035 because I got the wrong end of the stick first time around.
