### ISSUE TITLE
Status of "Custom Recurring Contribution" once disabled

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3348]
What's happening if someone create a recurring "Custom Contribution" and the collective disable "Custom Contributions" a few months later? 

@Betree Can you check that we handle that elegantly? I thought about this case while answering a related support issue.

**Comment by Betree** [comment]
The only place where we check this flag on the API is in [createOrder](https://github.com/opencollective/opencollective-api/blob/50cbc556bb881e821e530d5ff0008d13504527bd/server/graphql/v1/mutations/orders.js#L199). Since we're re-using the same order when processing subscriptions, it shouldn't cause any issue. 

However while investigating that I found out that `SendMoneyToCollectiveBtn` that uses the `createOrder` endpoint too receive an error if it tries to send back the money to a collective that has custom contributions disabled. Will push an update for that today.
