### ISSUE TITLE
User left off tax form list in error

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3350]
[This user](https://opencollective.com/josegonzalez) was paid $15,000 in 2019 by Open Source Collective, but he was not on the list we gave to the accountants and thus didn't get his 1099 (we've since issued him one manually). 

We need to figure out why he was missed so we can ensure no one else is falling through the cracks.

In Forest, I can see he did submit a tax form in 2019, but the link to the actual file is missing. His 2020 one looks normal.

![Screen Shot 2020-07-20 at 12 42 17 PM](https://user-images.githubusercontent.com/5498878/87889595-812f2380-ca86-11ea-8a27-b826631b6a98.png)

The actual 2019 expense is `unclassified` as I think it was submitted before the change where we required setting either `invoice` or `receipt` - but I thought we included unclassified ones to ensure we caught ones like this. Perhaps it's a fluke and won't be an issue in the future? Still doesn't explain why the system shows his form was received but we're lacking the file.

**Comment by znarf** [comment]
If the link to the file is missing from the DB, it's likely because of a manual edit. It was properly uploaded on S3 when we checked the data earlier this year:
https://docs.google.com/spreadsheets/d/1-_CBJ95qTYcjQ9BAsQdCkoVaJc8ghkPEsUKzukmo6u8

I think we used the following documents to communicate the list to the accountants:
https://docs.google.com/spreadsheets/d/1mrn_DlEJ5iaUrPUoQwkbcF8wBbygfF26AucagXX8SYc

It seems that in this one we only looked at `INVOICE` instead of also looking at `UNCLASSIFIED` one, that might explain that this user was out of the list.

**Comment by alanna** [comment]
OK. I think this will not come up for 2020 because we will not have any more `unclassified` expenses now. But I'm worried we might have missed others from 2019 during the migration.

@znarf can you check if there are any users who have >$600 in `unclassified` expenses who were not included on the list for the accountants? If not, we can just close this. If there are, we need to inform the accountants and issue those 1099s.

**Comment by znarf** [comment]
Closing this. We'll handle that out of GitHub, already reached about that on Slack.
