### ISSUE TITLE
Pay to address disappeared from expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3364]
I submitted this expense: https://opencollective.com/ocnz/expenses/22546

When I selected my profile, it displayed my address under my name under 'pay to' (it's saved in my settings). But when I submitted the expense, the address disappeared.

<img width="797" alt="Screen Shot 2020-07-25 at 3 00 56 PM" src="https://user-images.githubusercontent.com/5498878/88447506-2df31180-ce88-11ea-9bbb-352d8e4f8434.png">

**Comment by znarf** [comment]
@Betree can you look into this?

**Comment by Betree** [comment]
The address is not there because the expense is a receipt, and we strip addresses for receipts. The address input was normally not displayed, or disappeared when you switched from `Invoice` to `Receipt`. Can you confirm this?

There's however something confusing in the UX there: if previously entered, the address is still displayed in the summary, before submitting.

**Comment by alanna** [comment]
Ah, that makes sense. I think it's more of a confusing UX thing, then. We
don't technically need payee addresses on receipt expenses, but it's there
at first and then disappears so I thought something went wrong. If we have
an address for the user, there's no harm in including it on a receipt
expense, it's just not required. So maybe we should display it if we have
it and not display it if we don't.

**Comment by Betree** [comment]
Because we don't have any input to allow you to change your address for receipts, I think that we should continue to strip it. Otherwise users could be confused about why they can't edit it.

So for me the simple fix here is to hide the payee address on the summary if the expense is a receipt.
