### ISSUE TITLE
Login screen hidden below the fold on the expense page

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#3420]
E.g. https://opencollective.com/allforclimate-uk/expenses/new
<img width="1392" alt="Screen Shot 2020-08-21 at 4 41 39 PM" src="https://user-images.githubusercontent.com/74358/90902806-51e53c80-e3cd-11ea-8206-6faac39d7439.png">
<img width="1392" alt="Screen Shot 2020-08-21 at 4 43 11 PM" src="https://user-images.githubusercontent.com/74358/90902864-6a555700-e3cd-11ea-9947-f4b543e39284.png">

**Comment by HADES-01** [comment]
@Betree I think I have found the bug (shown below). It is happening because of 
```CSS 
@media screen and (min-width: 52em) {
    .kqClfH {
         position: absolute;
     }
}
``` 
Can I work on it and send you a PR??

## BEFORE
![before](https://user-images.githubusercontent.com/52060608/94291680-8e322c80-ff79-11ea-95f6-30b98d5528c5.jpg)


## AFTER
![after](https://user-images.githubusercontent.com/52060608/94291828-bb7eda80-ff79-11ea-928f-053f3a95c15a.jpg)

**Comment by Betree** [comment]
Sorry @HADES-01, @kewitz actually prioritized a fix for this one yesterday
