### ISSUE TITLE
Strong Customer Authentication (3d Secure) not supported in Recurring Contributions

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3429]
While editing my recurring contributions, I should be able to add a new Credit Card requiring Strong Customer Authentication  (3d Secure) and it should prompt me with the Confirmation flow.

A list of test Credit Cards can be found at https://stripe.com/docs/testing#regulatory-cards

Example: `4000 0027 6000 3184`

To check how the Confirmation flow should look, try to add this sample Credit Card in your user profile (where Strong Customer Authentication is properly handled).

**Comment by sbinlondon** [comment]
Have this implemented but not entirely sure how to handle the error if the customer does not pass strong authentication.

Take a look at how it's implemented in adding a new credit card on your profile settings.

![addccprofile](https://user-images.githubusercontent.com/37520401/95747381-40633700-0c90-11eb-800f-ea86bf52971f.gif)

If we add a 3D secure card, but fail the authentication, and refresh the page, it's still listed on the account. On the backend, the payment method is created and added to the account, but a `stripeError` is returned with the response to challenge the customer with strong authentication if needed. So regardless, the payment method now exists on the account and if you refresh the page, it'll appear in the list.

I guess this isn't a problem using it in the contribution flow, for example, because when you select the payment method, it challenges you again with the strong authentication. If you fail, then you can't make the contribution.

So the problem I'm finding with the recurring contributions flow is that, if we add a 3D secure payment method, but fail the authentication, then the payment method is still on the user's account. If I refresh the page, it'll now be listed, and I can select it from the list and it isn't checked.

![3dsecurerc](https://user-images.githubusercontent.com/37520401/95748241-9a183100-0c91-11eb-8560-4f372f79b308.gif)

What is the solution here? Do I add the security check to the `updatePaymentMethod` mutation as well so that if we _do_ select the 3D secure payment method, and try to click 'Update', it challenges us again?

Or, I'm wondering if there is something we need to do more broadly across every place where we add a 3D secure card (in profile settings, in the contribution flow, here in recurring contributions) where if we try to add the card and then fail the security check, shouldn't we remove it from the account?

@Betree if you can help with this since Francois is away this week that would be great.

**Comment by Betree** [comment]
Would be great to have a flag on the payment method to know it's pending for 3dsecure confirmation to be able to re-trigger the process later on.

In the meantime, having a "Retry" button in your error message when editing recurring contributions should work for most of the cases.

**Comment by sbinlondon** [comment]
>Would be great to have a flag on the payment method to know it's pending for 3dsecure confirmation to be able to re-trigger the process later on.

For this can't we just check `paymentMethod.confirmedAt` which would be `null`? Or would you want to add something in the `paymentMethod.data` flagging this?

**Comment by Betree** [comment]
I'm not sure how `paymentMethod.confirmedAt` is used by Stripe, but if it works with that then that's a good option
