### ISSUE TITLE
Online Events

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3439]
From support.

In the confirmation email for Events, looks like a location is required. Now that Online Events are common place, this should not be the case.

Also, it seems its' extra important to precise the timezone in the Email and in the attached ICS events. We should make sure the timezone is passed and displayed everywhere.

<img width="1377" alt="Screenshot 2020-08-28 at 09 08 15" src="https://user-images.githubusercontent.com/806/91532069-0de2c200-e90e-11ea-84f5-9221c1f0f4e5.png">

**Comment by Betree** [comment]
@znarf maybe we could do the following:
- In the GeoSuggest component, add a special "online" value (or put it in another select if easier)
- When picking this value, also show a text input for "Online address" (to allow people to put a Zoom link for example)
- When saving, set collective's `locationName` to `Online` and `address` to the web URL

The email would then work out of the box. We should add some special logic to make it nicer:
- If not online:
> We are excited that (...) on September 9th 2020 at 7:00pm [TIMEZONE] at {{ event.locationName }} ({{event.address}})
- If online
> We are excited that (...) on September 9th 2020 at 7:00pm [TIMEZONE] on {{event.address}}

**Comment by Betree** [comment]
Some more feedback:

> Zoom has recently updated its security policy
> (...) « we will be requiring that all meetings have a Passcode »
> So adding just the link is not sufficient anymore. 

On top of the [previous proposal](https://github.com/opencollective/opencollective/issues/3439#issuecomment-682374043), I suggest adding a `textarea` for Instructions that will be displayed in the email. I'm tempted to store that info in `event.data.instructions`, as it's only used for events and we don't want to overload the model more than it already is. Also, it's a private info that should only be given to people participating to the event.

**Comment by Betree** [comment]
Started a work in https://github.com/opencollective/opencollective-frontend/pull/5009, I don't have the bandwidth to continue working on it right now. Feel free to take over the PR if you want to complete this feature.

**Comment by snitin315** [comment]
Can it be a bounty? I can take this up.

**Comment by Betree** [comment]
A bounty for this one is not a bad idea, it may require some flexibility if the specifications seem incomplete, but since you are fairly autonomous and have some experience with the code base I think you have what it takes to lead it.

I suggest rebasing https://github.com/opencollective/opencollective-frontend/pull/5009 to kickstart your work as a good part of the frontend work was done there. 

The part of the specs that is not really clear at the moment is about the event URL (https://github.com/opencollective/opencollective/issues/3439#issuecomment-683790691), we should store it in `event.data.instructions` as the link can contain a private password to join the event but we may want to expose it somehow in the API for attendees to see it.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
