### ISSUE TITLE
Showing wrong amount in pending contribution

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3527]
![Screen Shot 2020-09-21 at 3 08 38 PM](https://user-images.githubusercontent.com/5498878/93730702-e71e5f80-fc1d-11ea-8a42-1979677a1557.png)

These are pending financial contributions on the host dashboard. You can see the amounts on the right. But on the left under `amount` they all say NZ$100.00 which is not correct.

**Comment by sbinlondon** [comment]
I can look into this. Can I confirm that this only seems to be contributions on a tier? I did a fake donation not on a tier (the Veganizer one) and it doesn't show the details at all.

<img width="844" alt="Screenshot 2020-10-08 at 16 04 28" src="https://user-images.githubusercontent.com/37520401/95477250-0b996c00-0980-11eb-8e1f-7d9d113ecb08.png">

**Comment by sbinlondon** [comment]
Can confirm that the bug is probably here: https://github.com/opencollective/opencollective-frontend/blob/86a4dbe651cb2649561bc227754a16d2f377e31a/components/expenses/OrderDetails.js#L80

```
<FormattedNumber value={order.tier.amount / 100} currency={order.currency} {...this.currencyStyle} />
```

`order.tier.amount` was `null` for the BrusselsTogether transaction above which is why it would display zero. But I think in the case of the bug you found, it's displaying the _tier_ amount, not the order amount.

I'll open a fix for this.

**Comment by sbinlondon** [comment]
In above PR, just going to remove the order details for now since the revamp is coming soon, don't want to spend much time fixing it.
