### ISSUE TITLE
Make it easier to get to standalone tier page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3528]
Here's a standalone tier card on the Collective page:

![Screen Shot 2020-09-21 at 2 52 47 PM](https://user-images.githubusercontent.com/5498878/93730977-28fbd580-fc1f-11ea-99ad-78911b7f7266.png)

If you click `read more` you can see the campaign page:

![Screen Shot 2020-09-21 at 3 31 11 PM](https://user-images.githubusercontent.com/5498878/93731052-8001aa80-fc1f-11ea-9690-45b81107008f.png)

But it's likely a lot of people will never do that, because they only click the big action button which goes straight to the checkout process.

I think if someone has gone to all the trouble of forcing a standalone tier and putting content in it, we should direct interested users there from the main Collective page. 

So I suggest all of these are linked to the tier page:
1. Title of tier (headline of the card) should be a link
2. Main action button ('contribute' by default) 
3. Read more, if we even need to keep that as a link once the above two are in place.

**Comment by PeterDavidCarter** [comment]
Sound great!

![image](https://user-images.githubusercontent.com/23146481/94327427-e598c280-ffa2-11ea-82bf-543574667f85.png)

**Comment by alanna** [comment]
Bump! I really want this change... could it be a bounty @znarf @Betree ? My suggested change is simply to link the title and action button to the standalone page and then people can contribute from there, and remove `read more` to create more space for the description text.

**Comment by Betree** [comment]
@Memo-Es any opinion on this?

**Comment by alanna** [comment]
Could this be done any time soon please?

> Link the title and action button to the standalone page, and then people can contribute from there, and remove the 'read more' link to create more space for the description text.

**Comment by Memo-Es** [comment]
This issue is being addressed as part of the accessibility project of this sprint (Q1S2)

The design specs are described in the issue https://github.com/opencollective/opencollective/issues/4045#issuecomment-814614922.

- We are applying new hover states for the card and the tier title. 
- Both the title and the read more link lead to the standalone tier page. 
- The button label should be tied to an action, in this case 'Contribute,' and therefore, it should lead you straight to the contribution flow. 

<img width="1390" alt="Screen Shot on 2021-04-07 at 00-38-20" src="https://user-images.githubusercontent.com/49539954/113815942-97c2fb00-9739-11eb-8a9c-ef09446ced0e.png">

@alanna @Betree

**Comment by Memo-Es** [comment]
@Betree I added an icon to indicate you're opening a new tab to see the details on the tier page

![Groups](https://user-images.githubusercontent.com/49539954/117871333-df6e0280-b262-11eb-951c-f40b6e589ac0.png)
