### ISSUE TITLE
Total amount contributed number incorrect

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3551]
--> https://opencollective.com/openmined

Total is showing $221,609

<img width="701" alt="Screen Shot 2020-10-01 at 10 03 06 AM" src="https://user-images.githubusercontent.com/5498878/94739345-57bb3e00-03cd-11eb-9dec-9581a904b6c8.png">

But a lot more than that has been raised. BitMEX alone gave $300k.

<img width="481" alt="Screen Shot 2020-10-01 at 10 03 40 AM" src="https://user-images.githubusercontent.com/5498878/94739398-6d306800-03cd-11eb-9058-d73bd5b8caa3.png">

**Comment by Betree** [comment]
This number is the total amount contributed (aka spent), not the total amount received.

However this number is indeed wrong, or at least not what you expect here: `OpenMinded` contributed $7344,50 to other collectives ($5000 to CVKey Project + $2344,50 to OSC) - which is why this number is displayed BTW (we don't show it if you've never contributed to other collectives). So you could expect $7344,50 in there.

The reason why we display $221,609.05 is because we also consider paid expenses in this total amount contributed. I think we should ignore expenses when computing this total amount contributed.

**Comment by alanna** [comment]
Why is it showing the amount contributed instead of the amount raised? Ah, because it's a Fund and Funds are designed to be about paying out not fundraising?

@piamancini - why is OpenMined a Fund and not a Collective? They are primarily focused on raising money and doing work on their project, not Funding others. Or is it not a Fund and something went wrong when we integrated all their different profiles into one?

**Comment by Betree** [comment]
> Why is it showing the amount contributed instead of the amount raised?

This number in the Hero is always showing the total amount contributed, never the amount raised. If you look at another profile like https://opencollective.com/babel/ that hasn't contributed to other projects, you'll see that it just doesn't appear.
