### ISSUE TITLE
Fees as debit transactions

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3552]
## User story 
As a Collective admin, I want to accurately track my budget with credits and debits, including fees.

Currently, the ledger shows the amount contributed minus the fees as one transaction. To do proper accounting it would be two transactions, a credit of the amount contributed, plus a debit for the fees.

We have had multiple admins request this, all of whom have been finance people. This difference prevents OC data for fitting in correctly to standard accounting processes or external accounting tools.

## Best solution for this problem
Reworking how the ledger displays transactions across the board.

## MVP
A good starting point would be redesigning the data export so that instead of a transactions being one row with the fees listed in a column, fees get their own row for each transaction, as a debit. This would satisfy our power accounting users without requiring messing with how the ledger is handled in the front end.

**Comment by hellopetersmith** [comment]
This is a strong need in order to export transaction lists from Open Collective and import the data into an accounting system. Right now, there is the original expense (which is typically money going towards a person, which would classified as a Labor expense), then there is a host fee, then there is often a payment processing fee. We need to be able to easily attribute each expense to the correct expense category so that we can accurately run expense reports and manage budgets by category. As it stands, we would have to import all of the transactions into the accounting system, then manually go into every transaction and redistribute the funds tied to one transactions across three different expense accounts. This would ideally function like a bank ledger (bank statement).

**Comment by znarf** [comment]
This was done, at the exception of payment processor fees. We can track this in a separate issue:
https://github.com/opencollective/opencollective/issues/4623
