### ISSUE TITLE
Spam button on expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3588]
## User story 
As a Collective or Host admin, I want to click one button to mark expenses as spam, so that I can efficiently deal with spam expenses and support OC to identify spammers.

## Best solution for this problem
A spam button for expenses, similar to the spam button in gmail, which 1) rejects and deletes the expense and 2) flags it to the platform admins to block the spammer.

## MVP
It's currently possible to do this but very cumbersome: reject expense, copy URL, paste in spam channel on slack, delete expense (repeat for each one, and sometimes there are a bunch).

**Comment by Betree** [comment]
Part of https://github.com/opencollective/opencollective/issues/2694

**Comment by Betree** [comment]
## Frontend
- On the expense page, the left column seems like a good place to add this. The [exclamation mark icons](https://styled-icons.js.org/?s=spam) seem often used for reporting SPAM:
![image](https://user-images.githubusercontent.com/1556356/105466339-5e2f3780-5c94-11eb-9b5d-892b192e8a4c.png)

- In expenses list, I think the button should not be in your face. Hiding it like what was proposed for https://github.com/opencollective/opencollective/issues/3813 seems like a good fit.

## API
I would advocate for a generic `reportAbuse` mutation since we will want to be able to report other types of abuse in the future (#2694):

`reportAbuse`:
- `entity`: ENUM(EXPENSE)
- `entityId`: string

Posting a message to Slack could be a good start (`postMessageToOpenCollectiveSlack("The expense <link>{title}</link> has been reported as SPAM", "abuse")`).

**Comment by alanna** [comment]
Bumping this again. Just had a Collective admin pretty put off by getting a spam expense. It degrades their trust of the platform and they don't know what to do about. They didn't know they could delete the expense after rejecting it, and since they only had one other legit expense, it looked pretty bad on their page. We need a button to give them a clear action to do with a spam expense.

**Comment by Betree** [comment]
Adding two ideas:
- Flagging an expense as SPAM/SCAM should block the expense feature for the user until we unlock it (through `user.data.features.USE_EXPENSES`).
- (Not for MVP) When an account has been flagged for SCAM expenses, prevent other expenses from this user to be paid/approved by disabling the buttons and display a clear message

**Comment by alanna** [comment]
This is done
