### ISSUE TITLE
Charged amount not matching contribution amount

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3598]
I gave a $25 contribution, but was charged $27.50. The fees were already removed from the transaction so where is the extra $2.50? I can't remember if I gave fees on top. If it's that, it should really show up in the transaction record and especially on the receipt. I have to keep receipts matching the actual amounts charged for accounting and taxes.

<img width="1183" alt="Screen Shot 2020-10-14 at 9 05 58 AM" src="https://user-images.githubusercontent.com/5498878/95910585-c8664f80-0dfc-11eb-81b0-740fce6db165.png">
<img width="845" alt="Screen Shot 2020-10-14 at 9 05 38 AM" src="https://user-images.githubusercontent.com/5498878/95910593-cbf9d680-0dfc-11eb-9900-6c71418b3f82.png">
<img src="https://user-images.githubusercontent.com/5498878/95910745-04011980-0dfd-11eb-85e3-a52ac422aefb.png">

**Comment by Betree** [comment]
There are indeed $2.50 fees on top for this transaction. @kewitz could you look into why they're not displayed here (if it's expected)?

@alanna platform tips are not displayed on the receipts at the moment, do we want to display them on the same receipt than the transaction?

**Comment by alanna** [comment]
The receipt amount has to match the charged amount. As a company I made a
$27.50 purchase and that shows in my financial records, and I need a
receipt that matches that exactly for accounting purposes. I think legally
we have to include all charges on the receipt issued.

**Comment by kewitz** [comment]
Fees on top are recorded in a separate transaction and in USD.
You can get a separate receipt for this transaction on your page.
![image](https://user-images.githubusercontent.com/2119706/96322891-48550b00-0ff1-11eb-9280-5aa31e246360.png)

**Comment by alanna** [comment]
But it's going through as one charge to my credit card and one transaction in my bank account. This is causing accounting complications. If it's one transaction, it should be one receipt. If it's two receipts, it should be two transactions. If we split them fully will Stripe charge more fees though?

**Comment by Betree** [comment]
> If we split them fully will Stripe charge more fees though?

I assume so, because fees are per transaction. It's also a clearer experience for users to only get one charge for the total amount.

The problem if we include both transactions on the same receipt is that this document is marked as emitted by the host, not Open Collective. But if it's legally ok to still include the tip transaction in there, then that's probably the simplest way to do it.

**Comment by znarf** [comment]
As part of the new Pricing model, the money flow and the accounting should be clarified. Let's bring this topic in our calls this week.

**Comment by znarf** [comment]
First, because of Stripe fees, having 2 separate credit card transactions is a no go.

After that, we had a long discussion with @piamancini and here is the summary.

On the Receipt/Invoice:
- I'm personally pushing for the Host to invoice the whole amount (here NZ$27.50) and provide a receipt containing the 2 items (as lines on the Invoice).
- Pia is pushing for the Host to provide an invoice containing only the primary contribution (here NZ$25) and Open Collective Inc. to provide an invoice for the Platform Tip (here US$1.69). We would need an extra paperwork (email or PDF) explaining the breakdown of the NZ$27.50 charge to help accountants trace it.

On the Tip collection:
- I'm advocating to stop taking the Platform Tips as Stripe's "application fee" and just rely on the Host wiring the money back each month. So we have the same behavior for Credit Card, PayPal and Bank Transfer.
- Pia wants to avoid as much as possible the Platform Tip going to the Host bank account and wants to keep the collection of Platform Tips using Stripe's "application fee. She thinks it's overall cleaner and don't want align on PayPal and Bank Transfer if it's seen as inferior.

**Comment by piamancini** [comment]
The reason I am pushing for the separate invoice is because that is the most legally advisable move. The host can't provide a non profit receipt for the total because the $2.5 were never part of the donation itself. They were never intended to go to the non profit. The user chose to make a platform contribution separate from the donation. It is absolutely not ok that hosts can send a tax deductible receipt for a donation that never hit their bank account. 

The proposal of sending all the money to the host and then retrieving our planform tip I think it's also not advisable. First it makes host's lives a lot more complicated since they need to account for thousands of small transactions extra. They'll need to somehow account for the platform  fee in their revenue statement and then account for it on the way out. 

I understand we are doing this in bank accounts and PayPal but is not the preferred path. We are now doing it because we don't have another option. By far, Stripe is the preferred method people use to send platform tips 
So we are mitigating risk greatly by separating the tip at the source. 

<img width="588" alt="Screen Shot 2020-10-21 at 12 11 31 PM" src="https://user-images.githubusercontent.com/3671070/96706239-9de53b00-1396-11eb-9a01-35823d32b8b3.png">

I also understand we do this with unpaid platform fees but again - it's larger amounts and less number of transactions. I wouldn't want OSC accountants to have to account for the 5% in every single OSC transaction. 

> We would need an extra paperwork (email or PDF) explaining the breakdown of the NZ$27.50 charge to help accountants trace it.

My proposal is to send a summary in an email with two invoices attached. Accountants can use the email or the receipts to track this. The email will clearly state the amount the user can expect to see in their credit card statement. 

Example: 

<img width="550" alt="Screen Shot 2020-10-21 at 12 14 18 PM" src="https://user-images.githubusercontent.com/3671070/96706668-2a8ff900-1397-11eb-8360-3496d67f9e0e.png">

This email is then followed by a tax deductible receipt that sates Only the amount the donation is tax deductible. In this case $5 not the $6 I have.

<img width="611" alt="Screen Shot 2020-10-21 at 12 15 37 PM" src="https://user-images.githubusercontent.com/3671070/96706748-46939a80-1397-11eb-8b5f-ae7f241161b8.png">

In our case, we should send a summary + an official invoice that you can use as tax deductible receipt. 
If the summary is good enough to act as the OC Inc. invoice then great, if not, we should attach the platform tip invoice. 

If we could have PayPal tips split at the source we would definitely do what we are doing with Stripe. Stripe checkouts can offer new payment methods we can look into where we can have the same model of splitting the fee. This is the best path, the fact that we can't replicate doesn't mean we need to downgrade it to the manual process. Specially since it is the bulk of the platform tips.

**Comment by alanna** [comment]
I really understand @znarf's desire to simplify things and also to normalize the business relationship between OC and hosts where we invoice them, as this will become more common with the new host pricing model.

However I think @piamancini is right - we can't have the host providing receipts for money actually going to OC inc. A charity host, for example, legally cannot just give money to a commercial corporation for nothing in return (this is exactly how people would commit tax fraud if this were allowed), and it can't provide donation receipts for money that's not intended for charity.

So I agree that the best solution is two receipts with an email breaking down the total charged, or a combined receipt showing the different amounts as in the examples Pia posted above. I think I prefer the combined receipt with the breakdown (instead of two separate receipts), because accountants and accounting software expect one receipt per one transaction, and it goes through as a single transaction on your credit card/bank. As long as it's clear on the receipt, accountants will accept it.

**Comment by znarf** [comment]
Now that we're sending receipts per email, we should already try to attach the Platform Tip receipt to it.

Not sure what to do for the extra document explaining the total charge. Maybe it should be simply a section in the email.

**Comment by alanna** [comment]
I'm reopening this because I tried to reconcile these payments again in my accounting software, but it's still not matching up. I have a receipt for $25 but the payment is for $27.50. From the comments on this issue it seems we decided to generate two separate receipts that add up to the total, but I can't see any way to download the $2.50 one for my records.

**Comment by alanna** [comment]
Just as feedback purely from my perspective as a financial contributor in this case, I have now cancelled this contribution because the overhead is just too high to deal with the accounting confusion.

**Comment by znarf** [comment]
Yes, the issue was closed, we decided to attach the receipt for the tip in the confirmation email.

https://github.com/opencollective/opencollective-api/pull/5052

Closing the issue again because we decided together on a fix and shipped it.

@alanna please open a new one if you want to clarify your problem.
