### ISSUE TITLE
Add tooltips or hover help info or FAQ content next to refund/reject transaction buttons

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3607]
When looking at a transaction, it's not clear to the user what the difference between these two buttons is:
![Screen Shot 2020-10-15 at 2 11 14 PM](https://user-images.githubusercontent.com/5498878/96184643-42314100-0f95-11eb-9529-7fe71ba7a7f4.png)
I know we'll probably put something about it in the docs, but it would be really useful to have something in context in the app. Even though I have been privy to some of the conversations around this feature, I myself don't actually know the difference in what will happen if I click one vs the other.

**Comment by alanna** [comment]
I just encountered this help text while troubleshooting another issue...

![image](https://user-images.githubusercontent.com/5498878/96186045-58400100-0f97-11eb-9144-fae0c0777097.png)

If this is how we're solving the need for help info about these buttons, there are some problems:
* This only shows up after you click? No way am I clicking a button as scary as `reject` or `refund` without first knowing what it does. I wouldn't see this.
* The word `member` doesn't mean anything on our platform, so even after reading this I still don't know what it means. Does it mean they'll still show up in my contributors section? Is that still true if I'm refunding the only $ they ever gave?
* Will this action cancel future recurring contributions if this is a recurring one?
* Will the contributor be notified?
* It's still not clear from this text what the difference is between this and `reject`

**Comment by sbinlondon** [comment]
> The word member doesn't mean anything on our platform, so even after reading this I still don't know what it means.

Should we change that to *"They will still show as a sponsor/contributor to your Collective"*? @piamancini?

> Does it mean they'll still show up in my contributors section? Is that still true if I'm refunding the only $ they ever gave?

Interesting. I think from a technical perspective yes, we don't remove the membership if we refund their only contribution. Refunds tend to be for things like, they accidentally hit 'contribute' twice or something and we are refunding one of those. Not sure how many refunds are people removing their only contribution. @Betree?

> Will this action cancel future recurring contributions if this is a recurring one?

'Refund', no, because it's more about refunding one mistaken transaction for whatever reason, not completely cancelling or removing the contribution.

> Will the contributor be notified?

No, but usually there is a support ticket conversation ongoing where they are aware the refund is happening.

> It's still not clear from this text what the difference is between this and reject

'Refund' is for Collective admins or our team to act on support tickets where people ask for refunds (mistaken transaction, cancelled event, etc) whereas 'Reject' is more of a decision solely by the Collective or Host admins to say they don't want a contributor's money or support.

**Comment by alanna** [comment]
> "They will still show as a sponsor/contributor to your Collective"?
The term we use is "financial contributor".

> we don't remove the membership
What is a membership? You mean remove them as a financial contributor? 

Sorry to be pedantic about this, but we struggled a lot with these confusing different terms and [did some work to clarify them a while ago](https://github.com/opencollective/opencollective/issues/1969#issuecomment-490342216), and I want to make sure we stick to that and don't regress. The names of many things in the codebase are still based on the old nomenclature, which is probably confusing for newer team members. Sorry about that.

> 'Refund', no, because it's more about refunding one mistaken transaction for whatever reason, not completely cancelling or removing the contribution.

Cool, let's make this clear and explain what those buttons do in context in the app.

> Will the contributor be notified? No
I think we should notify them. People need official documentation of anything related to money. If I make a contribution from my company, I need to upload the receipt, and if it's refunded or rejected, I need to upload that notification to my accounting software.

**Comment by Betree** [comment]
> Interesting. I think from a technical perspective yes, we don't remove the membership if we refund their only contribution. Refunds tend to be for things like, they accidentally hit 'contribute' twice or something and we are refunding one of those. Not sure how many refunds are people removing their only contribution. @Betree?

Probably very few since the feature was only available to host admins since recently, but we can expect that number to grow. I think the expected behavior is indeed to remove the entry from the `Members` table, since there's no reason to keep it if they never truly contributed. The entry will be re-created if they contribute again, so it should be fine to remove it.

The only case to properly check is with recurring contributions, if I have a monthly contribution and the first one is refunded, will the `Members` entry be re-created next time I'm charged?

No need to tackle it right away, but it would be great to have a followup issue about this one.

> @sbinlondon I think **from a technical perspective** yes, we don't remove the membership
> @alanna What is a membership? You mean remove them as a financial contributor?

We usually try to enforce the terminology everywhere we can, but in the code we need to define our own concepts to work properly. Here for example, the membership @sbinlondon is referring to is the `Members` table which represent any relationship between one account and another. While we should indeed not surface this term to the user, it's still very useful for us to talk in these terms because they are the most explicit to describe a technical change.

This is not a problem of synchronization from the code with the terminology: we don't want to move our `Members` table to a `FinancialContributors` table because it also contains admins, attendees, etc. and for now we have no reason to review the data model on that part.

**Comment by sbinlondon** [comment]
@alanna Apologies, I can be a bit lax sticking to terminology when I'm discussing on issues, I will try to be better so it's more clear what I'm referring to!

> @betree No need to tackle it right away, but it would be great to have a followup issue about this one.

I wil open an issue.

> @betree While we should indeed not surface this term to the user, it's still very practical for us to talk in these terms because they are the most explicit to describe a technical change.

I'll do a quick search in our lang files to make sure `member` isn't anywhere, I have a feeling I might have done that at some point.

**Comment by sbinlondon** [comment]
So besides saying "team members" or "community members" (which I feel is ok, it isn't specifically pertaining to saying someone is a "member" of your Collective), we do say "member"/"membership" is a few places:

```
"members.members": "members",
"members.pending.details": "This member has not approved the invitation to join the collective yet",
"membership.description": "{role, select, ADMIN {Admin} MEMBER {Core Contributor} BACKER {Contributor}} since {date}",
"paymentMethod.monthlyLimitPerMember.label": "Monthly limit per member",
"tier.type.membership": "membership (recurring)",
"transaction.refund.info": "This action will reimburse your contributor for the full amount of their contribution and they will still be a member of your Collective.",
"contributeFlow.successMessage": "{fromCollectiveName, select, incognito {You're} other {{fromCollectiveName} is}} now a member of {collectiveName}'s \"{tierName}\" tier!",
"ContributionType.Membership": "Membership",
"createProfile.faq.persoVsOrg.content": "Create an organization profile if you want to make a financial contribution in the name of your company or organization. An organization profile allows you to enable other members of your organization to make financial contributions within certain limits that you can define. Organizations can also issue gift cards.",
```

**Comment by Betree** [comment]
@sbinlondon good research, would be great to update the ones that are still used in the interface. We can followup with that in a separate issue. Short feedback on that list:
- `members.members` is used in a deprecated component (no need to migrate)
- `contributeFlow.successMessage` is used in a deprecated component (no need to migrate)
- `membership.description` member is not used there, it's only in the i18n key which is ok (not displayed to users)
- `tier.type.membership` is unrelated, we should keep it
- `ContributionType.Membership` is unrelated, we should keep it
- `createProfile.faq.persoVsOrg.content` I don't think this one is problematic

**Comment by sbinlondon** [comment]
> @sbinlondon good research, would be great to update the ones that are still used in the interface. We can followup with that in a separate issue. Short feedback on that list:
> 
>     * `members.members` is used in a deprecated component (no need to migrate)
>     * `contributeFlow.successMessage` is used in a deprecated component (no need to migrate)
>     * `membership.description` member is not used there, it's only in the i18n key which is ok (not displayed to users)
>     * `tier.type.membership` is unrelated, we should keep it
>     * `ContributionType.Membership` is unrelated, we should keep it
>     * `createProfile.faq.persoVsOrg.content` I don't think this one is problematic

Ok in that case it sounds like we just need to sort:

```
"members.pending.details": "This member has not approved the invitation to join the collective yet",
"paymentMethod.monthlyLimitPerMember.label": "Monthly limit per member",
"transaction.refund.info": "This action will reimburse your contributor for the full amount of their contribution and they will still be a member of your Collective.",
```

I will make an issue.

**Comment by znarf** [comment]
Referencing the issue mentioned above: https://github.com/opencollective/opencollective/issues/3712

**Comment by aminakazi** [comment]
Do you reckon this content is clear enough? 

**Refund:** This action will reimburse the full amount back to your contributor. They can contribute again in the future.  
**Reject:** This action prevents the contributor from contributing in the future and will reimburse the full amount back to the them.

![On Hover](https://user-images.githubusercontent.com/48468919/108074846-a7a25500-708f-11eb-8437-8baae5c3a75c.png)

**Comment by piamancini** [comment]
@aminakazi content is ok by me.

**Comment by aminakazi** [comment]
Production Ready file: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=10353%3A0
