### ISSUE TITLE
Redesign the page to edit team members

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3624]
I recently sent a message asking some admins to add a contributor, and the design of that page is so bad that I had to include a warning image or I was sure they'd click the wrong thing.

<img width="618" alt="Screen Shot 2020-10-25 at 10 08 30 AM" src="https://user-images.githubusercontent.com/5498878/97093683-9da4b280-16aa-11eb-8fbc-a894f75a0f50.png">

The problem is, you click `add core contributor` and fill out the form, then the big button right there is `add core contributor` which is what you're trying to do, so of course you click that. But actually you are supposed to scroll down and click the `save` button. It's very confusing.

We should have the `save` button be really emphasised, and then elsewhere there could be a small link called `add another team member` or something like that. In fact the action button should actually be `invite` right? I think an `invite` action button for each team member you add makes more sense than one big `save` button at the end.

Related: #3618 and #1791

**Comment by alanna** [comment]
Do you also have to click save after removing a team member? Because if so, it's doubly confusing. When you click remove they disappear right away there's no reason to think you also need to click save in the interface.

**Comment by Memo-Es** [comment]
We designed a dedicated page when we did the overhaul of the settings that became the new admin panel.

| Edit/add members page | Create member modal | Edit member modal |
|-----------------------|---------------------|-------------------|
|  ![Large (Desktop)](https://user-images.githubusercontent.com/49539954/110532945-16992980-80e3-11eb-811d-1b347d329d40.png)    |   ![Modal Add Team Member (Desktop + Tablet)](https://user-images.githubusercontent.com/49539954/110532951-17ca5680-80e3-11eb-9b05-844367d6ce18.png)    |   ![Modal Edit Team Member (Desktop + Tablet)](https://user-images.githubusercontent.com/49539954/110532953-17ca5680-80e3-11eb-9913-2911cd50a334.png)    |

[See the design file in figma ](https://www.figma.com/file/eBwSvsJztTIIxoivPzz9pV/OC.com-03-Admin-Panels-%E2%9D%8F?node-id=2252%3A58314)

cc @Betree

**Comment by Betree** [comment]
The design looks good! Only one small thing is missing: members are marked as "Pending" until they accept the invitation to join the collective. IMO the simple fix would be to have a section below like "Pending invitations", and display the same cards but with a call to action to remove the invitation.

**Comment by Memo-Es** [comment]
Thank you for your input @Betree I agree, will modify the design to correspond to your idea

**Comment by kaylarep** [comment]
Is it possible to include on these pages the exact details of what permissions each role has (no e.g./'like', just listing out the exact permissions), or at least link to a page in the docs for it?

**Comment by Betree** [comment]
@kaylarep I think it's included in the modals @Memo-Es shared in https://github.com/opencollective/opencollective/issues/3624#issuecomment-794426511, below the role selection field. In today's settings, the description is also surfaced:

![Peek 2021-04-26 15-57](https://user-images.githubusercontent.com/1556356/116094916-3a6ef980-a6a8-11eb-8364-54cda442bb98.gif)

**Comment by alanna** [comment]
@shannondwray Can you add the descriptions of each role to the docs? We recently updated the wording that appears in the screenshot Ben showed above.

**Comment by shannondwray** [comment]
Done! and updated the screenshots on docs as the settings placement has changed

**Comment by Betree** [comment]
We should take the opportunity to move this feature to GQLV2.

# Specs

## API

- [ ] Create a new `server/graphql/v2/query/MemberInvitations.ts` file and add a `memberInvitations` field similar to https://github.com/opencollective/opencollective-api/blob/ae37e2e9a51563ab94fd614f1df5d7b30158939c/server/graphql/v1/queries.js#L884
- In `server/graphql/v2/mutation/MemberMutations.js`:
  - [ ] Add an `inviteMember` mutation
Args: `memberAccount` (AccountReferenceInput), `account` (AccountReferenceInput), `role` (MemberRole), `description`(String), `since` (ISODateTime).
Returns: a `MemberInvitation`
Permissions: can only add ADMIN/MEMBER/ACCOUNTANT roles. Must be an admin.
  - [ ] Add a `removeMember` mutation
Args: `memberAccount` (AccountReferenceInput), `account` (AccountReferenceInput), `role` (MemberRole).
Returns: Boolean (success)
Permissions: can only remove ADMIN/MEMBER/ACCOUNTANT roles. Must be an admin.
  - [ ] Add a `editMember` mutation
Args: `memberAccount` (AccountReferenceInput), `account` (AccountReferenceInput), `role` (MemberRole), `description`(String), `since` (ISODateTime).
Returns: `Member`
Permissions: can only edit ADMIN/MEMBER/ACCOUNTANT roles. Must be an admin.
- [ ] Deprecate the `editCoreContributors` mutation in GQLV1

## Frontend

Implement the design proposed above with the following components
- [ ] `CreateMemberModal`
- [ ] `EditMemberModal`
- [ ] `MemberForm` (used by both create and edit)

**Comment by snitin315** [comment]
Can I work on this one ?

**Comment by Betree** [comment]
@Memo-Es About the second modal from https://github.com/opencollective/opencollective/issues/3624#issuecomment-794426511, I would suggest re-wording from "Add team member" to "Invite team member", since people must accept the invitation before they're actually added as admins.

> Can I work on this one ?

@snitin315 This issue is an opportunity to replace the old `Collective.editMembers` helper with simpler, more focused methods. We must make sure that these new methods will have good test coverage, and there's some work to do to design all that properly on the API side. Because of this uncertainty on the complexity, I'm not confident enough to add a bounty at this point.

In the meantime, feel free to start looking at it if you're interested and have time - we just can't offer a bounty for it now.

**Comment by snitin315** [comment]
I think we are missing `Remove member` button and the `Pending` tag in the design from https://github.com/opencollective/opencollective/issues/3624#issuecomment-794426511

**Comment by snitin315** [comment]
For the time being, I'm displaying the pending tag as below -

<img width="972" alt="Screenshot 2021-05-11 at 7 58 07 AM" src="https://user-images.githubusercontent.com/46647141/117749053-ba5f9c80-b22e-11eb-90c1-5265cb23f0d2.png">

**Comment by Memo-Es** [comment]
Thanks for following up with this issue, @snitin315!

I realize the ideal next step would be to redesign the user cards, but that may take a little while. So, to not block this issue's progress, I suggest adding the delete button inside the edit team member modal.

<img width="912" alt="Screen Shot on 2021-05-10 at 21-48-01" src="https://user-images.githubusercontent.com/49539954/117750875-c66d3f00-b1d9-11eb-8200-d663d0dd852b.png">

I like what you did to include the pending tag; I think it works. In the meantime, we do the redesign of the cards.

cc @Betree

**Comment by kewitz** [comment]
:trophy: This issue was completed by @snitin315 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
