### ISSUE TITLE
[PROJECT] Setting to differentiate legal name and display name

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3689]
## Overview
> As an individual user, or admin of a fiscal host or self-hosted Collective, I want to specify a display name for the OC profile and separately a legal name of the entity or person, which is sometimes different. The legal name should appear on receipts and invoices, and be associated with tax forms.

## Ownership
Product: @benjam, @alanna 
Eng: @Betree, @SudharakaP 
Design: ?

## Prioritisation

**Impact:** This issue stops communities from tackling issues that put members at risk (human rights, social justice etc). This impacts on our ability to have an impact on these issues.  
**Frequency** This issue affects a small number of our users currently. 

## Proposed solution
An optional setting called `legal name` that you can set, if it's different from the display name.

The display name is used *everywhere* that the profile name is viewable publicly, including expenses, comments, etc. This is *very* important because sometimes people have important privacy reasons not to use their legal name publicly.

The legal name is used for receipts, the payee section of expenses, and sent through to the tax form system. These instances should all be places where only that user and the admins of the Host they are interacting with can see.

## Measuring success 
- Users set legal names and begin operating under psedonyms
- Communities working at risk feel comfortable using Open Collective

**Comment by alanna** [comment]
I really want to bump this up, and I think it's critical we build this soon, for the following reasons:

1. Advising people to sign up with pseudonyms is a key tool we have for balancing the transparency of our platform with very real and important privacy concerns our users may have. As we have begun to support more activist and front-line community support groups, such as initiatives supporting the trans community, we have more and more people interfacing with our platform who need a way not to publicly show their legal name. But this causes them problems when it comes to matching their profile name with their bank account payout name, the name the receipt is issued to which often needs to be their legal name for tax reporting, and when it comes time to fill out the HelloWorks tax form (which pulls through their profile name for the signature even if they fill in their legal name at the top).

2. We are welcoming more numerous and diverse hosts and self-hosted Collectives on the platform, many of which may have a display name that does not exactly match their legal name. For example, a self-hosted Collective which is a particular project or initiative with a company's bank account plugged into it, but that company itself has a different legal name. The display name has to be one thing for publicity and donations, while the entity name on the receipt is something else. There are large hosts, like Social Change Nest, whose legal name is something else, Social Change Agency, as well as legal entity types with very long and cumbersome official titles that are way too long for the title at the top of their profile. Separating legal name and display name would fix these issues.

**Comment by alanna** [comment]
If we want to enable more self-hosted Collectives, this setting will be critical (see [example here](https://opencollective.slack.com/archives/C0HSLRNVC/p1623147593114400)). Many self-hosted Collectives are using a personal or company bank account but raising money for a specific project under a different name. 

This is in addition to the important implications for accounting record keeping and privacy considerations.

**Comment by alanna** [comment]
Just bumping this up again. It's causing an issue for Gift Collective host, since the legal name of the fundholder is different. When we claim tax refunds the invoices must be made out to the taxable legal entity. We need this for so many reasons.

**Comment by BenJam** [comment]
questions:

need to detail where we show/hide this information  
need to describe how users will provide their legal name at the point of making a contribution/signing up etc.

**Comment by alanna** [comment]
Display name:
* Anywhere viewable publicly

Legal name:
* Expenses payee section (show display name for public view, legal name for host admin view)
* Receipts issued for contributions
* Tax forms
* Host data retained for contributions that trigger reporting requirements (e.g. the $5,000+ threshold @piamancini has been working on)
* Host admin CSV export (include both legal and display name in columns)

Perhaps we should show both names to the host admin in these cases, for ease of matching up the two names? E.g. I expect when contacting support people would use their display name but the host might need to match them with transactions referring to their legal name. 

We also need to visually indicate to the host that someone has a display name when looking at a place where their legal name is shown, so the host doesn't turn around and accidentally use their legal name publicly (or to address them) because they don't realise they also have a display name.

Let's design this in a way to support things coming in the future:
* programmatically requiring the legal name to match the bank account owner name and tax form name (so people can't submit an expense under their personal profile for their company, for example)
* Host exporting data they need for tax reporting purposes (which needs to use legal names)

We need to enable this setting for both individuals and organizations, as both have reasons to differentiate between names this way.

In regard to how/when we ask user to provide their legal name:

* For new profiles, I think the easiest way is to include it in the basic signup form and make it a required field. If their display name and legal name are the same, they can enter it twice (we can have a tooltip explaining where each is used in practice). 

* If we don't want to collect it on the initial signup screen because we're trying to keep that as simple as possible and many users will not do things requiring their legal name, then we'll have to do it in a more complex way. We'll need to collect or confirm their legal name when they:
  * Submit their first expense - this will ensure we have it for both expense documentation and for tax forms
  * Make a contribution that will generate a receipt (i.e. not when moving money between Collectives in the same host)
  * When an org activates as a Host is a good time to check it

For existing users, once we roll this feature out we should collect/confirm their legal name next time they submit an expense or make a contribution.

The setting should appear in the info section of settings for individuals and orgs (including hosts).

How will we handle users who misunderstand and set their display name as their individual name and their legal name as their company name? I feel like people will do this, resulting in profiles that should be orgs being individual profiles. From an accounting perspective is this actually not problematic but could it mess things up in other ways?

**Comment by Betree** [comment]
@alanna Some questions:
- Could we say that fiscal host legal names are always public? Given that you just have to make a contribution to one of its hosted collectives to see it, it seems like that's not really private info.
- In the places where we display the legal name, and to address one of your concerns above, would that be ok to display a legal name in the interface like `Legal name (display name)`?

I'm proposing some specs below for a first implementation. They're meant to be updated and split into more specific issues.

Things that are not yet in these specs as they need some input from @opencollective/design first:
- For users, requiring a legal name at signup is difficult because they're created from many places and that might complexify the form. We should however show it in the contribution for guests and logged-in users who contribute > $5K. Ping @Memo-Es
- Ask for the user's/organization legal name in the expense form

Overall, we need to define a strategy to collect this info for existing users. I've kept that part mostly out of the specs for the MVP, we'll probably have better visibility once we start working on it.

# API

- [ ] Add a `legalName` (string, default=null) field on the `Collectives` model
- [ ] On GQLV2 `Account` object, add a `legalName` field. The resolver should take care of checking the permissions:
  - [ ] Field should always be visible for admin(s) of the account
  - [ ] For fiscal hosts, the field should be visible if the user has financial contributions to one of the collectives
  - [ ] We should create a new `SEE_LEGAL_NAME` context permission and check it with `getContextPermission`
- [ ] Use `setContextPermission` for `SEE_LEGAL_NAME` in all contexts where we want to allow it
  - [ ] For expense payees, if `remoteUser` has the host admin permissions
  - [ ] For financial contributors, if `remoteUser` has the host admin permissions
- [ ] When generating the tax form on HelloWorks, use the `legalName` if available
- [ ] Add a `legalName` column on host admin CSV export
- [ ] When submitting an expense, if `legalName` is defined, make sure it matches the payout method (bank account)

# Frontend

- [ ] Add a `Legal` name field on `https://opencollective.com/account/edit` for individuals and organizations. "name" and "legal name" fields should have descriptions based on https://github.com/opencollective/opencollective/issues/3689#issue-745454887. It should be clear that one is private while the other is public (maybe add a lock icon?)
- [ ] Add a `Legal name` field (optional - if different from display name) on organizations forms
  - [ ] `https://opencollective.com/organizations/new`
  - [ ] `https://opencollective.com/my-collective/edit/host`
  - [ ] `https://opencollective.com/my-collective/accept-financial-contributions/organization`
- [ ] Expense summary: if a `legalName` is provided for the payee, show it
- [ ] In the expense form, if a legal name is defined for the payee, make sure it's set by default when adding a bank account and don't allow user to change it (there should be a tooltip to explain why it cannot be edited)
- [ ] Add a message in `Activate as host` when activating to advise admins to go and set their legal name in their profiles

# PDF service

- [ ] Update `ExpenseInvoice` to show legal names
- [ ] Update `Receipt`/`ReceiptV2` to show legal names

**Comment by alanna** [comment]
> Could we say that fiscal host legal names are always public? Given that you just have to contribute to one of its hosted collectives to see it, it seems like that's not really private info.

Yes in fact it would be great to clearly to users. Hosts need to share their legal entity name openly.

> In the places where we display the legal name, and to address one of your concerns above, would that be ok to display a legal name in the interface like Legal name (display name)

This is a good solution.

The specs look good from my side (the parts I understand).

> we need to define a strategy to collect this info for existing users

Do you think the trigger points I mentioned could also work for existing users? When they...
* Submit their next expense
* Make a contribution that will generate a receipt

For existing host admins we can just send them a direct email about it to let them know about the new setting, and announce it at the host webinar. We can manage that manually.

**Comment by Betree** [comment]
@alanna Thanks for the feedback

> Do you think the trigger points I mentioned could also work for existing users? When they...
> 
>     Submit their next expense
>     Make a contribution that will generate a receipt
> 

Yes, especially since @Memo-Es is already working on a step to collect logged-in user's info in the contribution flow when they give > $5K.

I want to have an input from design before implementing these two.

**Comment by BenJam** [comment]
Thanks, both for pressing on with this. Good job at thinking this through @Betree. We will shout loudly about this when we roll it out so I hope that we will see folks who need this using it.

**Comment by Betree** [comment]
> Host admin CSV export (include both legal and display name in columns)

@alanna I suppose the CSV you're referring to is the one received by email with the monthly host report?

**Comment by Betree** [comment]
The [MVP](https://github.com/opencollective/opencollective/issues/3689#issuecomment-905305266) for this project is mostly done. We're still iterating on the expense flow stuff, and need to add it to CSV exports, but it should be ready for the end of the sprint.

I think we should quickly - during the next sprint - follow-up with https://github.com/opencollective/opencollective/issues/4692#issuecomment-921973945 (design is still being discussed) to take full advantage of the feature and make sure we fully resolve the issues of collecting addresses for contributions > $5K.

**Comment by Betree** [comment]
Everything from https://github.com/opencollective/opencollective/issues/3689#issuecomment-905305266 is done, I'm therefore closing the project. We'll follow up with some issues mostly related to the introduction of the legal name in the contribution flow:
- https://github.com/opencollective/opencollective/issues/4719
- https://github.com/opencollective/opencollective/issues/4692
- https://github.com/opencollective/opencollective/issues/4654

**Comment by SudharakaP** [comment]
A bit overdue maybe, but I've created a project board for this at, https://github.com/opencollective/opencollective/projects/68 so that we could see all issues related to this in one place. 😉
