### ISSUE TITLE
Consensus on naming and behaviour of sections and subsections in the Collective page

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3698]
During the design and implementation of the new navigation for Collectives pages we have been encountering some discrepancies in how we name and treat the sections of the Collective page. 

We need to solve it in a language level before moving forward with the implementation of the project.

Currently we have this organization ([Example](https://opencollective.com/design)):

We see these sections in the navigation 
<img width="740" alt="Screen Shot on 2020-11-19 at 15-04-38" src="https://user-images.githubusercontent.com/49539954/99724021-9dfd5700-2a78-11eb-8de7-0fc9b504b826.png">

Whereas we have the following (also) sections in the settings page where you manage the order of sections of your page:

<img width="939" alt="Screen Shot on 2020-11-19 at 15-07-16" src="https://user-images.githubusercontent.com/49539954/99724250-f7fe1c80-2a78-11eb-8010-fc8dd3c2dc6c.png">

One of the main goals of the new design proposal is to simplify sections in the high level, so we narrowed down to just 5 main sections:

<img width="875" alt="Screen Shot on 2020-11-19 at 15-09-20" src="https://user-images.githubusercontent.com/49539954/99724458-414e6c00-2a79-11eb-940d-a0f810255887.png">

Plus, we are adding the rest of the features of the Collective page as 'subsections' 

@Betree suggested to name the main sections rather as 'Categories' and the subsections as 'features', we want to raise the discussion first to decide how are we naming these different nesting levels before moving forward with the implementation. 

Here is a table that displays all the categories and features, and which ones have stand alone pages (even if they are not included in production today).

| Profile page sections  | Standalone page  |
|---|---|
| **Contribute/Contributions**  |   |
| <ul><li>Make financial contributions (Tier cards on COLLECTIVE/ORG, TIckets on EVENT)</li></ul>  | ✅  |
| <ul><li>Contributors ('All of us')</li></ul> | 🚫  |
| <ul><li>Financial contributions made</li></ul>  | 🚫   |
| <ul><li>Recurring contributions made</li></ul>  | ✅  |
| **Events/Projects**  |   |
| <ul><li>Events</li></ul>  | 🚫 (doesn't have one yet, but should it?)  |
| <ul><li>Projects</li></ul>  | 🚫 (only on type FUND)  |
| **Budget/Transactions (name of category for type USER)**  |   |
| <ul><li>Transparency</li></ul> | ✅  |
| <ul><li>Transactions</li></ul> | ✅  |
| <ul><li>Expenses</li></ul> | ✅  |
| <ul><li>Goals</li></ul> | 🚫  |
| <ul><li>Top Financial Contributors</li></ul> | 🚫  |
| **Connect**  |   |
| <ul><li>Updates</li></ul> | ✅  |
| <ul><li>Conversations</li></ul> | ✅  |
| **About**  |   |
| <ul><li>Team (Core contributors)</li></ul> | 🚫  |
| <ul><li>Connected collectives</li></ul> | 🚫 |
| <ul><li>About</li></ul> | 🚫 |

_(* Edited by @sbinlondon to add alternatives to main 5 categories based on collective type and some missed out sections/features)_

As we see here, we have three different items:
| Example  | Suggested name  | Behavior  |  
|---|---|---|
| **Top level item**  | 'Category'  | Takes you to the Collective page and scrolls you down to that category  |  
| Sub-index w/page ✅  | 'Menu item'  | Takes you to the standalone page of the feature  | 
| Sub-index w/no page 🚫  | 'Feature'  |  N/A It just lives in the C.Page 

With this proposal, we will have the following dropdown menus for desktop, and an expanded menu for mobile (Not collapsable) 

| Desktop  | Mobile  | 
|---|---|
| <img width="1450" alt="Screen Shot on 2020-11-20 at 01-09-04" src="https://user-images.githubusercontent.com/49539954/99770332-489f6500-2acd-11eb-9926-e447fa690483.png">  | <img width="437" alt="Screen Shot on 2020-11-20 at 01-15-58" src="https://user-images.githubusercontent.com/49539954/99770998-00cd0d80-2ace-11eb-9811-ab1d9a2d4567.png">  | 

@znarf @Betree @kewitz @sbinlondon  @alanna @piamancini

**Comment by sbinlondon** [comment]
Re: @Memo-Es's suggestion:
| Example  | Suggested name  | Behavior  |  
|---|---|---|
| **Top level item**  | 'Category'  | Takes you to the Collective page and scrolls you down to that category  |  
| Sub-index w/page ✅  | 'Menu item'  | Takes you to the standalone page of the feature  | 
| Sub-index w/no page 🚫  | 'Feature'  |  N/A It just lives in the C.Page 

Largely agree on the divisions, disagree on the names and what they imply. 

The terminology issue may have been complicated by my decision to use @Betree's [features endpoint](https://github.com/opencollective/opencollective/issues/2807) work in this project but it's a decision I stand by and think will make things more simple in the end.

The **features** endpoint is to help us keep the logic about what a collective can do (i.e. receive financial contributions as a COLLECTIVE or ORG, receive expenses as a host ORG); and what data is displayed (i.e. collective type can have Conversations, Updates, and Goals but has a few Conversations threads, has Goals disabled, and no published Updates despite the feature being enabled, therefore we would only display Conversations on their page). Features is mostly an API thing.

I think a good framework would be:

* **Feature**: used to talk about what a collective is allowed to do (receive contributions or expenses, make contributions, have goals, have conversations), whether it has its allowed features enabled or disabled, and if enabled whether they have data (are "active")
* **Category**: the main clickable words that are listed on the navbar and as headings with cute icons on the collective page
<img width="875" alt="Screen Shot on 2020-11-19 at 15-09-20" src="https://user-images.githubusercontent.com/49539954/99724458-414e6c00-2a79-11eb-940d-a0f810255887.png">

* **Section**: discrete blocks within the broader **categories** on the collective page, which we may choose to show/render based on the collective type and its available features and data (this might sometimes map directly to a **feature** like Conversations or it might be a more widgety thing like Top Financial Contributors).
* **Expandable section**: if a **section** on the collective page has an equivalent standalone **page** (i.e. the "Transactions" section in the "Budget" category has "View all transactions" which links to `/collective/transactions`) (I'm not super attached to the name "expandable section", think it needs work, but I do agree with Memo's idea that we should have a separate name for the sections that are also standalone pages)

Using this, I think the main source of confusion for some people (and potential confusion with the users) **was** that the **categories** on the navbar and mobile menu would act differently depending on which page we were on: 

* on the collective page if you click a **category** like "Connect" it scrolls you down to that category heading on the page. No drop-down menu appears.
* if you are on a standalone page like `/collective/transactions` and click the category "Connect" then the dropdown menu  would appear and you can click to go to the standalone pages for "Conversations" or "Updates"

It seems we're proposing to solve this by the drop-down menus always appearing on desktop/tablet, and the entire menu being visible on mobile? Or do we want to think more about how we can clearly signal between being able to click a category to see its expandable sections vs. clicking a category to go to that category heading on the collective page?

Another outstanding question is how much control do we give users over their profile page? Can they reorder/hide entire categories on the page, but not the sections within them? Can they reorder/hide both categories and sections within categories?

**Comment by sbinlondon** [comment]
@piamancini @Betree @kewitz @znarf

**Comment by Betree** [comment]
This brings more clarity, thank you for documenting that @Memo-Es and @sbinlondon.

I agree with everything described in https://github.com/opencollective/opencollective/issues/3698#issuecomment-731140874. My main feedback would be to be careful with using just `Category`, because this word already has a meaning in the context of accounts (categories like `casino`, `seo`, etc). Out of clarity, I think we should refer to them as "Section category".

> It seems we're proposing to solve this by the drop-down menus always appearing on desktop/tablet, and the entire menu being visible on mobile?

I think that's the way to go for first iteration.

> Another outstanding question is how much control do we give users over their profile page? Can they reorder/hide entire categories on the page, but not the sections within them? Can they reorder/hide both categories and sections within categories?

That will be the most complex part, especially because we'll need to migrate the existing `sections` to a new format like:
```es6
sections = [
  ABOUT: [
    { section: ABOUT, isEnabled: true },
  ],
  BUDGET: [
    { section: TRANSACTIONS, isEnabled: true },
    { section: EXPENSES, isEnabled: true },
  ]
]
```

To me we should be able to re-order section categories (ABOUT, BUDGET, etc) and sections inside of them. But you can't get a section out of it's Section category.

Translated to UI:

![image](https://user-images.githubusercontent.com/1556356/99986396-6ca1c580-2daf-11eb-8d4d-b0369a40b318.png)

**Comment by kewitz** [comment]
@Memo-Es the expanded mobile menu is looking really good, I think it solves the issue related to linking to pages and sections we discussed in our meeting.

I agree with @sbinlondon. It is important to set coherent, non-conflicting names and be consistent across the front and back end.

My problem with listing standalone pages as a link in the dropdown is that sections belong to pages and not the other way around.
This doesn't look very important because it still represents a 1:1 relationship, but this will cause you trouble when navigating across standalone pages because all these sections will make no sense on a different page.
I can see two ways of solving this:
1. This would require a menu that mutates across pages.
    - This sucks because navigation needs to be consistent.
2. Keep the same navigation bar (and possibly the collective header) across all standalone pages to give the feeling these pages are full-screen components of the same collective page.

@Betree I think that's an elegant data-structure to address this issue.

**Comment by sbinlondon** [comment]
> > Another outstanding question is how much control do we give users over their profile page? Can they reorder/hide entire categories on the page, but not the sections within them? Can they reorder/hide both categories and sections within categories?
> 
> That will be the most complex part, especially because we'll need to migrate the existing `sections` to a new format like:
> 
> ```js
> sections = [
>   ABOUT: [
>     { section: ABOUT, isEnabled: true },
>   ],
>   BUDGET: [
>     { section: TRANSACTIONS, isEnabled: true },
>     { section: EXPENSES, isEnabled: true },
>   ]
> ]
> ```

This is fine by me. I want extra extra clarity though:

1. This `sections` array is the one in `settings.collectivePage` right?
2. Does the `isEnabled` on a section in the `settings.collectivePage.sections` array **ONLY** pertain to whether that section is visible/not visible on the collective page?
3. `settings.collectivePage.sections[section].isEnabled` is different to `settings.features[feature].enabled`? What happens if we have `settings { features { conversations: false } }` because the collective has opted out of having conversations but

```
settings {
  collectivePage: {
    sectionCategories: {[
      CONNECT: [
        { section: CONVERSATIONS, isEnabled: true },
      ]
    ]}
  }
}
```

wouldn't have an effect because we're opting out of the feature? Or would we have logic on the API side to say when we opt out of conversations via `settings.features.conversations` it also sets the bit in `settings.collectivePage.sectionCategories...` to `false`? Or maybe vice versa where if they hide conversations from their collective page in this proposed menu below, that is effectively seen as opting out of the feature?

> To me we should be able to re-order section categories (ABOUT, BUDGET, etc) and sections inside of them. But you can't get a section out of it's Section category.
> 
> Translated to UI:
> 
> ![image](https://user-images.githubusercontent.com/1556356/99986396-6ca1c580-2daf-11eb-8d4d-b0369a40b318.png)

That's pretty much what I was imagining for the edit profile page menu, thank you for visualising! 🙌 

I agree with @kewitz that navigation should be consistent wherever it's used. We don't mutate the top bar profile menu's design or functionality across pages, and I feel we should try our best to keep a similar consistency with the collective navigation.

**Comment by Memo-Es** [comment]
Agree about the navigation consistency. The proposal described above is meant to be consistent on all Collective's instances, from the Collective page and all of its possible sub-pages.

So if you click on any of the 'Section Categories' like 'Budget,' it will take you to the Collective page, down to the 'Budget' section on both desktop/mobile, and only 'Expandable sections' using @sbinlondon term will be displayed in a dropdown.

One thing also I want to surface is @alanna 's comment about the 'Goals' feature:

> Don’t combine goals and budget - some people need to put the goals progress bar right at the top and want the budget stuff elsewhere.
Basically, I think we should split up things to customize, reorder, and hide/show what they want more flexibly.

I don't think we should make 'Goals' a section of its own. These types of small decisions generated a lot of complexity in the current Collective Navigation, which was one of the main points of the design need for this update. Anyway, I wonder if that could be a widget integrated to the top part of the Collective page. @Betree, any thoughts on this?

(Also, we should also remember that we brought back this feature after a couple of negative reactions from users, so if we want to keep it, we should rethink how it plays out with the new stuff that we are planning for the near future. I decided to put it under budget because it will also be featured in the new 'Transparency' page for Collectives for sure.

**Comment by Betree** [comment]
@sbinlondon 

> This sections array is the one in settings.collectivePage right?

Yes

> Does the isEnabled on a section in the settings.collectivePage.sections array ONLY pertain to whether that section is visible/not visible on the collective page?

Currently yes, but we may want to keep https://github.com/opencollective/opencollective/issues/3396 in mind - though I think https://github.com/opencollective/opencollective/issues/3396 will be invalidated by the fact that we'll soon have CONNECT instead of UPDATES/CONVERSATIONS.

> settings.collectivePage.sections[section].isEnabled is different to settings.features[feature].enabled? 

It currently is:
- `collectivePage.sections[section].isEnabled` > Section (ie. Buget, Contributors, About, etc)
- `settings.features[feature].enabled` > Feature (ie. ReceiveExpenses, ReceiveContributions, etc)

> What happens if we have settings { features { conversations: false } } because the collective has opted out of having conversations but

It's the issue we already discussed in https://github.com/opencollective/opencollective/issues/3396. There are multiple ways to solve that, we could for example delegate the value for `isEnabled` to the settings value:

```es6
settings: {
  collectivePage: {
    sections: [
      { type: 'SECTION', section: 'GOALS' },
      { 
        type: 'SECTION_CATEGORY', 
        category: 'CONNECTED',
        sections: [
          { section: CONVERSATIONS, isEnabledSettingKey: 'features.conversations.enabled' },
        ]
      }
  ]
}
```

But if it introduces too much complexity we can solve that in a separate PR.

> Or maybe vice versa where if they hide conversations from their collective page in this proposed menu below, that is effectively seen as opting out of the feature?

That's another option

---

@Memo-Es 

> Anyway, I wonder if that could be a widget integrated to the top part of the Collective page. @Betree, any thoughts on this?

If I understand correctly, what you describe as a "widget" is a sections that wouldn't be integrated in the navigation right? If that's correct, it's indeed possible. These _Widgets_ could be sections that can live outside of a _Section category_. So:

```es6
settings: {
  collectivePage: {
    sections: [
      { type: 'SECTION', section: 'GOALS' },
      { 
        type: 'SECTION_CATEGORY', 
        category: 'CONNECTED',
        sections: [
          { section: CONVERSATIONS, isEnabled: true },
          { section: UPDADTES, isEnabled: true }
        ]
      }
  ]
}
```

**Comment by sbinlondon** [comment]
> @sbinlondon
> 
> > This sections array is the one in settings.collectivePage right?
> 
> Yes
> 
> > Does the isEnabled on a section in the settings.collectivePage.sections array ONLY pertain to whether that section is visible/not visible on the collective page?
> 
> Currently yes, but we may want to keep #3396 in mind - though I think #3396 will be invalidated by the fact that we'll soon have CONNECT instead of UPDATES/CONVERSATIONS.
> 
> > What happens if we have settings { features { conversations: false } } because the collective has opted out of having conversations but
> 
> It's the issue we already discussed in #3396. There are multiple ways to solve that, we could for example delegate the value for `isEnabled` to the settings value:
> 
> ```js
> settings: {
>   collectivePage: {
>     sections: [
>       { type: 'SECTION', section: 'GOALS' },
>       { 
>         type: 'SECTION_CATEGORY', 
>         category: 'CONNECTED',
>         sections: [
>           { section: CONVERSATIONS, isEnabledSettingKey: 'features.conversations.enabled' },
>         ]
>       }
>   ]
> }
> ```
> 
> But if it introduces too much complexity we can solve that in a separate PR.

No, I really like this idea. I think what I'm looking for is *one* source of truth, i.e. one place we can look to find all this info, and this looks like the ideal solution because 1) it makes use of the different keys we have now and means we wouldn't have as many problems trying to migrate everything to one or the other and 2) does collate everything regarding the collective page into one place.

**Comment by sbinlondon** [comment]
@Betree Since I am working on the edit collective page settings thing mentioned above as a significant portion of this project, would I be able to have you work on these: https://github.com/opencollective/opencollective/issues/3641

**Comment by Betree** [comment]
Sure, but we should probably solve the issue about how we're going to store/process the settings to render these first. The way will solve it will impact the way we develop these menus.

**Comment by sbinlondon** [comment]
Sure, I think we've all approached some conclusions but happy to summarize and try to move forward:

1. **The navigation structure**
- We have *section categories* (i.e. Budget, Contribute, About) which are the main elements on the navbar and the heading on the collective page.
<img width="875" alt="Screen Shot on 2020-11-19 at 15-09-20" src="https://user-images.githubusercontent.com/49539954/99724458-414e6c00-2a79-11eb-940d-a0f810255887.png">

- We have *sections* within these section categories (i.e. *sections* Transactions, Expenses within *section category* Budget)
- For Goals and potentially Top Contributors, we have a separate type called a *widget* which 1) does not appear in the navbar or dropdown menu and 2) can be moved anywhere on the collective page and 3) shown/hidden on its own and not having to consider what section category it is in (so Goals won't be in Budget anymore)

2. **The navbar visuals/layout/behaviour**
- We have agreed that the navigation should act the same way on all pages
- We have decided as an MVP that there is the non-collapsible mobile menu, and for desktop/tablet the drop-down menus
- If we click a section category like Budget, it opens the drop-down menus so you can select Transctions or Expenses and go to those pages
- If you are already on the collective page, clicking Budget won't scroll you down to that section (so we have the behaviour matching on all pages)

3. **The edit collective settings**
- We are going to store/represent the structure of the collective page in the database like so:

```es6
settings: {
  collectivePage: {
    sections: [
      { type: 'SECTION', section: 'GOALS' }, // a.k.a. a 'widget'
      { 
        type: 'SECTION_CATEGORY', 
        category: 'CONNECT',
        sections: [
          { section: CONVERSATIONS, isEnabledSettingKey: 'features.conversations.enabled' },
          { section: UPDATES, isEnabledSettingKey: 'features.updates.enabled' },
        ]
      }
  ]
}
```

- Visually on the edit collective profile page, it will look like this, allowing users to reorder *section categories* and *widgets* on the page, and reorder *sections* within the *section categories*. They can hide (enable/disable) *widgets* and *sections* but not *sections categories*.

![image](https://user-images.githubusercontent.com/1556356/99986396-6ca1c580-2daf-11eb-8d4d-b0369a40b318.png)

**Comment by Betree** [comment]
All good, feel free to assign me on the API issues.

I'll probably start by implementing a `convertSectionsToNewFormat` function in the frontend so that we can work with the new `settings.collectivePage.sections` without having to wait for API to be fully implemented.

**Comment by Memo-Es** [comment]
Thank you @sbinlondon for the summary! Just a small detail:

> If we click a section category like Budget, it opens the drop-down menus so you can select Transactions or Expenses and go to those pages
If you are already on the collective page, clicking Budget won't scroll you down to that section (so we have the behavior matching on all pages)

The dropdowns will appear [while hovering](https://tafka.d.pr/H3sWMj) on each navigation item (Unless there are no dropdown elements to show). If you click on the main item it will scroll you down to that section if you are on the Collective page or take you to the collective page, down to that section if you're in a sub-page

cc @Betree

**Comment by piamancini** [comment]
> If you are already on the collective page, clicking Budget won't scroll you down to that section (so we have the behaviour matching on all pages)

I'm not sure about this - Do you mean that if you are in the main collective page and you click on budget nothing happens but there will be an option to do a dropdown and I can select transactions or expenses from there? 

I would expect in the. main page to be scrolled down to the category budget in that page but maybe I'm not understanding something

**Comment by sbinlondon** [comment]
Clarifying after stand-up (thanks @Memo-Es and @piamancini!):

* Clicking a category section in the navbar always takes you to that section on the collective page
* Hovering on a category section in the navbar opens the section menu
* The mobile menu is uncollapsible for the above reasons, since you can't hover on mobile. Behaviours are the same.
