### ISSUE TITLE
New collective navigation: no more tickets section

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3725]
**Describe the bug**
With `NEW_COLLECTIVE_NAVBAR`, the "Tickets" section seems gone.

**To Reproduce**
1. Create an event
2. Go to profile page

**Comment by Betree** [comment]
Adding a test for events in `lib/__tests__/collective-sections.test.js` to prevent regressions in the future would be great

**Comment by sbinlondon** [comment]
I'll have a look at this and also add some tests 👍

**Comment by sbinlondon** [comment]
@Betree In line with the new reduced number of section categories, my plan was to put Tickets within the Contribute section - is this an ok solution?

I was going to put Tickets _instead_ of Contribute (like Transactions instead of Budget for type USER) but I think I saw that Events can also accept contributions?

**Comment by Betree** [comment]
> In line with the new reduced number of section categories, my plan was to put Tickets within the Contribute section - is this an ok solution?

Sounds like a good solution yes. The most important is to make sure we display them above the "regular" tiers.

> I was going to put Tickets instead of Contribute (like Transactions instead of Budget for type USER) but I think I saw that Events can also accept contributions?

Correct
