### ISSUE TITLE
Updates and Conversations showing even though they are disabled

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3732]
Updates and Conversations are showing on OC Nigeria's page even though they are disabled.

<img width="809" alt="Screen Shot 2020-11-26 at 10 39 32 AM" src="https://user-images.githubusercontent.com/5498878/100284398-fe8a1800-2fd3-11eb-85db-c880838e8a7b.png">

<img width="1107" alt="Screen Shot 2020-11-26 at 10 40 19 AM" src="https://user-images.githubusercontent.com/5498878/100284405-00ec7200-2fd4-11eb-8cbb-1e0239b29612.png">

**Comment by Betree** [comment]
They appear for admins only. Still a bug though, disabled sections should not be displayed for anyone.

However when I check in the DB the settings for https://opencollective.com/nigeria I see no customization of the sections:

```json
{"editor": "html", "hostCollective": {"id": 79335}}
```

@alanna could you confirm that:
1. The profile is https://opencollective.com/nigeria
2. The sections still appear as customized when you goo to the edit page

Based on the (2)'s result we may diagnostic an issue when saving, or something may have somehow stripped out the setting.

**Comment by alanna** [comment]
> The profile is https://opencollective.com/nigeria

yes

@Betree as you can see in the screenshot, they are set to `disabled`.

**Comment by Betree** [comment]
Seems like it's using the default then, since there's no `sections` in settings. The default from the edit page doesn't seem to match anymore the default we use on the collective page. @sbinlondon could you get a look, see if it's related to the latest NavBar changes?

**Comment by sbinlondon** [comment]
Sure having a look now

**Comment by sbinlondon** [comment]
> They appear for admins only. Still a bug though, disabled sections should not be displayed for anyone.

Actually if I open a private browsing window and view it logged out, Conversations is still there.

There isn't anywhere where Conversations is explicitly disabled: there's no `settings.features.conversations` or as @Betree pointed out, there isn't a `sections` in settings cause they haven't rearranged the page sections.

I suspect this is a regression because 1) we now have Converations on by default (whereas they used to be opt in?) and 2) not only was OC Nigeria created before that, I think they're old enough that they were on before Conversations were introduced, so they won't even have `settings.features.conversations: false` by default. So if they haven't explicitly turned it off then it would show up.

We need to figure out how to deal with these older collectives that won't have any explicit Conversations/Updates flags set.
