### ISSUE TITLE
CTA link in thank you email broken if you disable default tier

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3733]
From a user:

> The "Thank you for your donation" email includes a call to action with a link to https://opencollective.com/collective/donate, but this link does not work because we have disabled the custom tier. Can we change that link to only go directly to our main page instead?

I think a better solution might be to link to /contribute but the main page link is also fine.

**Comment by Betree** [comment]
The part where this appears is:
> Help us raise more money!
> Share this URL: https://opencollective.com/babel/donate 

I personally have a preference for linking the profile page, I think it's the best one to share because it has all the context (description, updates, contributors, etc.) thus people arriving there should be more tempted to contribute.

---

![image](https://user-images.githubusercontent.com/1556356/100319923-be6d6a00-2fc0-11eb-963b-184e1abfac50.png)
