### ISSUE TITLE
Repeating icons on nav bar

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3748]
Four out of six icons in the nav bar are identical. The purpose of an icon is to visually distinguish things from one another. If that's not how we're intending these icons, then it just adds visual noise in an area that's already overcrowded, and I think just having text would be preferable. I'm assuming this is a bug though, and they are not all supposed to be the same? The user who gave me this feedback said they do like the larger illustrations for each section header, but really don't like all the tiny noisy icons in the nav bar. I tend to agree.

<img width="943" alt="Screen Shot 2020-12-01 at 1 33 54 PM" src="https://user-images.githubusercontent.com/5498878/100682125-3cbf7700-33da-11eb-9e1e-0f92d1818de4.png">

**Comment by Memo-Es** [comment]
Yes, @alanna there is a different icon for each section. I assume they will be updated by @sbinlondon shortly

**Comment by Betree** [comment]
It's because we're still showing the legacy sections instead of categories. For example, `Updates` and `Conversations` are going to be merged together inside `Updates`, so in the end there will be only one icon per menu item.

There's another related issue reported by @piamancini on [Slack](https://opencollective.slack.com/archives/C01EAGU0XSS/p1606768991005500): this takes too much space.

@sbinlondon while we transition, can we hide the icons when the flag for the new navbar is off?

**Comment by sbinlondon** [comment]
Yes the repeated icons are only for legacy sections which won't be around when we make the full transition to v2.

In the meantime though, I've opened a PR to hide the icons until we've done that, and to prevent the navbar from taking too much space.
