### ISSUE TITLE
Dedicated page to show all submitted expenses

### ISSUE THREAD

**Issue by cameralibre** [opencollective/opencollective#3749]
**Describe the bug**
From my user menu, it's very easy to find information about my contributions, and see past transactions such as paid expenses.
However, I can't find a way to see my _pending_ expenses from the user menu (`TopBarProfileMenu`, I guess?):
![Screen Shot 2020-12-01 at 14 20 02](https://user-images.githubusercontent.com/15368010/100685267-edc91000-33e0-11eb-80ad-22d09e8057a1.png)

As far as I'm aware, in order to see my pending expenses I have to navigate to the collective's page, and hunt for it there:
![1](https://user-images.githubusercontent.com/15368010/100686163-9deb4880-33e2-11eb-887d-a7da36712d33.png)

Aha! ☝️ here, down the bottom: _'View all expenses!'_

**Expected behavior**
If I want to check on the status of an expense that I've submitted, I expect to be able to navigate to all of the important details about my own activity **from the user menu**, rather than needing to find that information on the collective's page.

**Comment by alanna** [comment]
Thanks @cameralibre ! 

I think we should include pending expenses on the [user profile expenses section](https://opencollective.com/cameralibre#section-transactions), at least. Right now it only seems to show paid expenses, but users often are looking for pending expenses  when they need to check the status or follow something up.

**Comment by Betree** [comment]
> I think we should include pending expenses on the user profile expenses section, at least. Right now it only seems to show paid expenses, but users often are looking for pending expenses when they need to check the status or follow something up.

We used to do that in the previous version of this section. It was a bit hacky on the engineering side (because this section show transactions and pending expenses don't have any transaction yet), but I agree that you would expect to find them there.

But having a page to show the expenses submitted by a profile would be useful too. For users to find their expenses easily, for support to investigate quickly (ie. for spam expenses) and also for https://github.com/opencollective/opencollective/issues/3686. 
A simple way to achieve that would be to add submitted (not only received) expenses to the expenses page (ie. https://opencollective.com/babel/expenses), to enable this page for users & to link it from the profile/menu.

**Comment by znarf** [comment]
Seeing submitted Expenses is generally a good idea for all kind of profiles. It will be even more important as we move more operations to an Expense based mechanism (think Monthly Host Settlement, Contribution Across Hosts).

**Comment by znarf** [comment]
I would like to see this project considered for prioritization next sprint (Q4S1).

**Comment by BenJam** [comment]
- [ ] discussion on approach w/design
- [ ] decide on approach and MVP (and document here)

**Comment by BenJam** [comment]
notes in full here (inc. recording) https://gist.github.com/BenJam/c5e167235dc35098328ff3cc2342c71f

next steps

- [ ] attempt to hack the collective budget section into user profiles 
- [ ] add the expenses page to user profiles and add expenses submitted to this page

no design needs immediately, but we'll need a review with respect to a control to filter expenses to show submitted/received/both.

**Comment by Betree** [comment]
Some additional notes that we took as part of an engineering discussion with @kewitz 

### User profile pages
- The collective Budget section can work (it adapts itself if there's missing data) but we'll need to remove the statistics on the right column. We'll need to confirm that with a POC.

### `/expenses` page for User profiles
- Remove the right panel
- Take full width
- No need for a special filter: only show submitted

### Expenses page on other profiles

Other profiles are more tricky because expenses can go in two directions.
- Maybe don't mix both types as it would be confusing
- We need the "revert view" for items:
  - Use FromCollective's avatar
  - Adapt wording

While implementing this, make sure we have a coherent solution for host users.

**Comment by BenJam** [comment]
- [ ] MVP for this week

**Comment by shannondwray** [comment]
Docs issue - https://github.com/opencollective/opencollective/issues/6143
Release issue - https://github.com/opencollective/opencollective/issues/6144

**Comment by Betree** [comment]
Feedback from today's demo:
- [ ] Update design when user submitted on behalf
- [ ] Ideally we should have the "double avatar" thing to clearly surface both the author and the payee
- [ ] Include drafts by default
- [ ] In the user menu, say "Manage expenses" instead of "Submitted Expenses" (_to match "Manage Contributions"_)

**Comment by Betree** [comment]
Feedback on @aminakazi's demo:
- There's still an ongoing conversations about the wording (submitted/received)
- We should show the filters for all accounts, with an empty view in case nothing has been submitted in the past
- We're opening a discussion around https://github.com/opencollective/opencollective/issues/6190

**Comment by Betree** [comment]
This week:
- [ ] Implement the latest design

**Comment by BenJam** [comment]
- document follow up tasks
- close this out and :tada:

**Comment by Betree** [comment]
This issue is now considered resolved. We're gonna come up with some proper documentation, but in a nutshell here are the 3 things that are changing on the platform:

#### To view your submitted expenses

1. Open your user menu by clicking on your avatar
2. Click on `Manage Expenses`

![image](https://user-images.githubusercontent.com/1556356/206029715-26205cf2-16a7-44d5-a92a-e3ce00b4808d.png)

#### To view expenses submitted by another user

1. Go to the user profile
2. In the menu, hover `Budget` then click on `Submitted Expenses`

![image](https://user-images.githubusercontent.com/1556356/206029889-017c556b-3efd-4908-904a-11f5907da6ca.png)

#### To view expenses payable to an account

1. Open the account page
2. Go to their **Expenses** page (Budget > Expenses)
3. Click on `Submitted`

![image](https://user-images.githubusercontent.com/1556356/206030099-d371c854-f306-4fa4-8606-7fe5b964d043.png)



As followups for this project, we have:
- https://github.com/opencollective/opencollective/issues/6130: we want to iterate with some proper design before releasing something there.
- https://github.com/opencollective/opencollective/issues/6216: Not really complex so we may fit it before the end of the sprint, but we want to make sure we don't degrade the performances while implementing it.

**Comment by shannondwray** [comment]
Can we make it so that this is shown by default on users profiles?

**Comment by Betree** [comment]
> Can we make it so that this is shown by default on users profiles? 

The Submitted Expenses link is already shown by default on user profiles ; unless you're referring to something else?

**Comment by Betree** [comment]
@shannondwray I see: if they've disabled their budget section in the settings, then the link won't ever appear. I'm not sure what's the best way to solve this until we have https://github.com/opencollective/opencollective/issues/6110. As a temporary improvement, I'm tempted to force the link in case the user viewing the page is a root admin but that won't solve everything.

As a temporary hack, you can add `/submitted-expenses` at the end of the URL: https://opencollective.com/chloris-d-smith/submitted-expenses.

**Comment by Betree** [comment]
Opened a feedback issue and moved this comment there: https://github.com/opencollective/opencollective/issues/6221
