### ISSUE TITLE
Deprecate global styles from Body.js

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3757]
In `components/Body.js`, we have some global styles defined that add rules for CSS classes. This is interfering with our pages design, and we already have `app.css` to define the things that we really want everywhere.

We should switch `withoutGlobalStyles` default value to `true`, and eventually add `withoutGlobalStyles={false}` on the pages that are broken (they can be documented in this issue). 

Finally, we'll remove the prop once everything will be migrated.

**Comment by SudharakaP** [comment]
@Betree : I can take this issue as it's related to the jsx migration if you don't mind. 😄

**Comment by SudharakaP** [comment]
> @Betree : I can take this issue as it's related to the [jsx migration](https://github.com/opencollective/opencollective/issues/3289) if you don't mind. smile

**Comment by Betree** [comment]
Sure! Let's push it as a separate PR though, this change could have some side effects.

**Comment by SudharakaP** [comment]
Just for the information, I've went through each page that use `withoutGlobalStyles` and checked them if they are broken. For now in the draft PR I've added `withoutGlobalStyles={false}` in every component that are broken. Below is the list. In the next couple of days I'll start migrating the components (make custom styled components and such so that we can get rid of the global styles and hence `withoutGlobalStyles` prop). 

@Betree : We can merge the draft PR first and then start the migration on separate PRs for each component. Or shall do I it in the draft PR that I opened? 

## Components that are not broken: 

`contribute.js`, `transactions.js`, `ErrorPage.js`, `createPledge.js`, `marketingPage.js`, `recurring-contributions-redirect.js`, `redeem.js`, `redeemed.js`, `signin.js`

## Components that are broken: 

- [ ]  `createUpdate.js`
- [ ] `IncognitoUseCollective.js`
- [ ] `CreateEvent.js`
- [ ] `CreateOrganization.js`
- [ ] `Hosts.js`
- [ ] `staticPage.js`
- [ ] `Page.js`
- [ ] `order.js`
- [ ] `editcollective/index.js`
- [ ] `update.js`
- [ ] `updates.js`

**Comment by Betree** [comment]
> Just for the information, I've went through each page that use withoutGlobalStyles and checked them if they are broken

The pages with `withoutGlobalStyles={true}` should not require any specific work because they are already ignoring the global styles. The pages that we do need to check are the ones that don't use `withoutGlobalStyles`.

> We can merge the draft PR first and then start the migration on separate PRs for each component.

That's a good plan!

**Comment by SudharakaP** [comment]
> > Just for the information, I've went through each page that use withoutGlobalStyles and checked them if they are broken
> 
> The pages with `withoutGlobalStyles={true}` should not require any specific work because they are already ignoring the global styles. The pages that we do need to check are the ones that don't use `withoutGlobalStyles`.
> 
> > We can merge the draft PR first and then start the migration on separate PRs for each component.
> 
> That's a good plan!

Thanks for the info. I'll work on the once that are needed to migrate in the next couple of days and open individual PRs. 👍🏽

**Comment by sbinlondon** [comment]
> ## Components that are broken:
> 
>     * [ ]  `CreateOrganization.js`

As an FYI we have someone working on `CreateOrganization` in a bounty but I'm pretty sure I'm going to ask them to remove `Body.js` from the file, so no need to worry about that.

@Betree I was under the impression `Body` was a much older component and we didn't want to use it going forward? Should I ask the contributor to remove it or is it just preference?

**Comment by SudharakaP** [comment]
@sbinlondon : Thanks for letting me know. I've updated the list above; I think you are talking about https://github.com/opencollective/opencollective/issues/3468 right?

**Comment by SudharakaP** [comment]
@Betree @sbinlondon : I've migrated all the components highlighted above (including the CreateOrganization.js as it was a very simple migration anyways) in  https://github.com/opencollective/opencollective-frontend/pull/5547. Screenshots are provided and let me know if you see any issues or needs any alterations. 😄

**Comment by Betree** [comment]
> I was under the impression Body was a much older component and we didn't want to use it going forward? Should I ask the contributor to remove it or is it just preference?

The `Page` component is more convenient to work with, it's less verbose. All the props accepted by `Body` are also supported by `Page`. So we're not going to deprecate/remove `Body`, but we should indeed try to no use it _directly_.
