### ISSUE TITLE
Collective Navigation v2: navbar v2 actions menu renders all CTAs

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3771]
Right now there are 8 CTAs and only 5 being rendered in the actions menu.

- [x] hasSubmitExpense
- [x] hasApply
- [x] hasContact
- [x] hasDashboard
- [x] hasRequestGrant
- [x] addFunds
- [x] addFundsToOrganization
- [x] hasContribute
- [x] hasManageSubscriptions

Additionally the actions menu in Figma only has 3 CTAs that have icons attached to them. We need input on the icons for the rest of the CTAs please @Memo-Es 

`hasDashboard` for the host dashboard is just using the same settings cog icon as the "admin panel" so maybe we want to change that? And `hasRequestGrant` is a dollar sign.

![Screenshot 2020-12-07 at 17 44 36](https://user-images.githubusercontent.com/37520401/101385610-ecea1f80-38b3-11eb-9609-3d6f515ccf9b.png)

![Screenshot 2020-12-07 at 17 34 48](https://user-images.githubusercontent.com/37520401/101384825-da231b00-38b2-11eb-8fd8-f4c7d7a6d60d.png)

@Betree @znarf where should the link to "Request grant" go?

**Comment by Memo-Es** [comment]
@sbinlondon "Request grant" is part of "Submit expense" since it is an expense type, just as invoice and reimbursement. Also, "Dashboard" is not an action; it's the functionality inside hosts "Admin Panel," which will exist for all users. If we need a provisional icon for the dashboard while migrating to the new admin panels, it's ok; I just wanted to point that out.
I will be updating the icons in Figma and reference it here later today.

**Comment by Memo-Es** [comment]
Missing icons for actions:

Dashboard: @styled-icons/material-outlined/Dashboard
Add funds: @styled-icons/material-rounded/AttachMoney
Contribute: @styled-icons/boxicons-regular/Planet

<img width="220" alt="Screen Shot on 2020-12-07 at 21-03-03" src="https://user-images.githubusercontent.com/49539954/101433165-de116600-38cf-11eb-94e8-f779ec8f3af4.png">

@sbinlondon

**Comment by sbinlondon** [comment]
Lovely @Memo-Es thank you!

**Comment by znarf** [comment]
> Can we get some clarification on whether Request Grant, Dashboard, and Manage Subscriptions should be in this new Actions menu?

- Dashboard needs to be in "Actions" because as far as I know we're not ready to merge "Host Settings" and "Host Dashboard". I would even argue that for Hosts "Dashboard" in the most important action and should always be available as a Button.
- I was discussed that "Request Grant" could be interesting to have in Actions, even if it's available later in "Submit Expense". This could help users who don't know that they need to go first to "Submit Expense" to "Request Grant". It was long time ago  though, maybe @piamancini has another idea now.
- "Manage Subscriptions" should definitely be in the Actions, as far as I know it's not available in the "Settings" yet. It should be "Manage Recurring Contributions".

Let's not confuse what we need to ship now and what we want to have in the future.

**Comment by sbinlondon** [comment]
> Let's not confuse what we need to ship now and what we want to have in the future.

💯 I think that's been my constant source of confusion for the last 2 months 😅

**Comment by Betree** [comment]
Maybe we could also move the `Edit cover` and `Edit main color` buttons in there?

![image](https://user-images.githubusercontent.com/1556356/101491361-f0d57a80-3963-11eb-887c-7a6a5ca129bc.png)

**Comment by piamancini** [comment]
I would have submit a grant as an action in the action menu separated from submit an expense. 

1- because it's a separate action from submitting an expense (even if now it's the same) that will need some tweaks to the flow, so it's nice to have it as it's own special thing. If we have it there, we might even remove it as an option in the expense flow and make it have it's own flow. This could help alleviate some the of the confusion we've been seeing from users. 

2 - because we might want to have it as an action started by an admin in the future, so it's good to already have it separate from the expense flow.

**Comment by sbinlondon** [comment]
Here's how it looks with all the CTAs (I just set everything to `true`, I know one collective wouldn't show them all 😉)

For me everything looks good except that Request Grant and Add Funds are the same. But potentially they wouldn't be rendered in the same menu for different collective types?

![Screenshot 2020-12-08 at 18 26 10](https://user-images.githubusercontent.com/37520401/101525236-ed9db700-3982-11eb-987e-a70986e92037.png)

**Comment by Memo-Es** [comment]
@sbinlondon 
We could use these icons for:

- Request grant (Alternative) @styled-icons/fa-solid/MoneyCheckAlt
- Manage contribution @styled-icons/remix-line/Stack

**Comment by znarf** [comment]
Just a detail, "Add Funds" (to Organization, the one used by Root Admins) should be renamed "Add Prepaid Budget". "Add Funds" will be the more common one used by Host Admins to credit their Collectives.

**Comment by sbinlondon** [comment]
> Just a detail, "Add Funds" (to Organization, the one used by Root Admins) should be renamed "Add Prepaid Budget". "Add Funds" will be the more common one used by Host Admins to credit their Collectives.

Ah ok, I will add this in a project polishing PR. Closing this issue but making a standalone card for what you mentioned on the project board.
