### ISSUE TITLE
Removed as admin but still seem to be admin

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3794]
I created [this Collective](https://opencollective.com/gameartisans), then tried to remove myself as admin. It appeared to work, asking me `are you sure you want to remove admin?` and I confirmed and saved. The Team section no longer shows me in settings. But I can still access the settings like an admin and I'm still showing on the profile page as a team member.

<img width="1251" alt="Screen Shot 2020-12-26 at 4 40 54 PM" src="https://user-images.githubusercontent.com/5498878/103145102-71381000-4799-11eb-84c6-3efc2155428d.png">

<img width="885" alt="Screen Shot 2020-12-26 at 4 43 04 PM" src="https://user-images.githubusercontent.com/5498878/103145103-75642d80-4799-11eb-944f-15faac000d02.png">

**Comment by Betree** [comment]
Looks like a cache issue, can you check if it's still happening to confirm that?

**Comment by alanna** [comment]
OK, seems to be resolved now. Is there a way to make this take effect right away? It definitely felt broken.

**Comment by Betree** [comment]
Something we probably don't do when removing members is to reload the logged in user profile, so that your access and permissions are probably updated in the frontend. We should definitely add that.

Regarding the members sections, we normally have cache invalidation for cloudflare + the `contributors` field. We should check where we failed to update.
