### ISSUE TITLE
Add the ability for Hosts to require custom information in the Contribution Flow

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3815]
For example, Casa Hacker will need Brazilian tax information from donors.
I think this can be generically implemented and stored in `order.data`.

**Comment by Betree** [comment]
Tiers can define a `customFields`, that are later rendered in the contribution flow. The data from these are then stored in `order.data.customData`. There's no interface yet for users to set their own fields, it needs to be done in the DB directly.

Maybe we could make this issue about specifying how we could surface the feature for users?

As an example, we use it for https://opencollective.com/captainfact_io/contribute/adhesion-membre-11636/checkout, because the French law requires that people agree to your "TOS" to join your non-profit as members.

The tier settings to achieve that look like that:
```json
{
  "id": 11636,
  "customFields": [
    {
      "name": "accepte_status",
      "type": "checkbox",
      "label": "Je déclare reconnaître l'objet de l'association, en avoir accepté les statuts et souhaiter devenir membre de l'association CaptainFact",
      "required": true
    },
    {
      "name": "accepte_reglement",
      "type": "checkbox",
      "label": "J'accepte le règlement intérieur",
      "required": true
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/1556356/104038760-caf6fc00-51d5-11eb-8dac-c1c133cf58bb.png)

**Comment by kewitz** [comment]
@Betree, the problem here is that this needs to be enforced at the host level since they're legally responsible for the donation.

**Comment by znarf** [comment]
Given that the core implementation is here, seems to me propagating an Host setting to all Financial Contributions should be relatively simple.

**Comment by alanna** [comment]
Could we use the same approach for #3297 so host admins can set a contribution policy?

**Comment by kewitz** [comment]
@alanna sure! Any suggestions where we could fit the custom information fields in the host settings?

**Comment by alanna** [comment]
@kewitz - For now I think we could shoehorn it into "receiving money" because that's what this policy would cover. But @Memo-Es is working on an overhaul for the whole settings area so I think just putting it somewhere for MVP and then asking him to find a better place is good enough right now.

**Comment by Betree** [comment]
> @Betree, the problem here is that this needs to be enforced at the host level since they're legally responsible for the donation.

The simplest way to implement would be to add a resolver in https://github.com/opencollective/opencollective-api/blob/87bc58a6a58944974214c39972edabe57f09a685/server/graphql/v2/object/Tier.js#L97 that would return something like:

```es6
{ ...host.settings.contributionFlow.customFields, ...tier.customFields }
```
