### ISSUE TITLE
Unable to see budget section or confirm pending bank transfer on self-hosted Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3836]
https://opencollective.com/tai-collective

They have added a bank account and activated as a self-hosted Collective. The financial contribution features are active.

However, we can't see the budget section, nor find where to confirm a pending bank transfer contribution.

**Comment by znarf** [comment]
The admins received an email with instructions on how to validate bank transfers:

<img width="782" alt="Screenshot 2021-01-14 at 09 45 39" src="https://user-images.githubusercontent.com/806/104565949-53015980-564d-11eb-90d0-27c6271d7a7e.png">

They can do this right from their Host Settings:
https://opencollective.com/tai-collective/edit/pending-orders?searchTerm=117140

<img width="1219" alt="Screenshot 2021-01-14 at 09 39 41" src="https://user-images.githubusercontent.com/806/104566029-66142980-564d-11eb-9e8a-aca02f358500.png">

We're doing this because we decided to not confuse Self Hosted Collectives with the Host Dashboard.

**Comment by znarf** [comment]
I think the budget section is currently not displayed because there is no transaction.

**Comment by Betree** [comment]
> I think the budget section is currently not displayed because there is no transaction.

Correct, in the latest version of the page "Budget" is not displayed if there's no transaction. We may review this approach once the new empty states (#3220) will be implemented.

**Comment by alanna** [comment]
OK, so this is working as intended, but we really need to work on the docs and design to make it more intuitive, because neither myself nor the user could figure it out.
