### ISSUE TITLE
Allow tracking of external funding sources

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#384]
For organizations that currently operate with more traditional funding models (ie. through grants), OpenCollective doesn't help them be transparent with their communities.

Having said that, if it _did_ cater to groups wishing to expose that information through a beautiful and coherent interface, it might make an excellent on-ramp for them to start considering how patronage-based funding might might fit into their efforts :)

**Comment by patcon** [comment]
Context: OpenCollective was surfaced multiple times in our Slack as a potentially interesting tool for the [Environmental Data & Governance Initiative (EDGI)](https://envirodatagov.org/).

cc: @shapironick @b5

**Comment by piamancini** [comment]
Hi @patcon!
> For organizations that currently operate with more traditional funding models (ie. through grants), OpenCollective doesn't help them be transparent with their communities.

hmm what makes you say this? you can still use your collective to add those funds and allow for transparent management of expenses. An example is the [Alliance of Foster Families NY](https://opencollective.com/affcny) that use the platform to allocate grants to each group. Without using the crowdfunding functionality.  

> if it did cater to groups wishing to expose that information through a beautiful and coherent interface

what would you like to see in terms of functionality?

**Comment by patcon** [comment]
Thanks for your time, Pia! You mean that we would send our grant money into a top-level collective, and distribute it from there to whatever sub-collectives we might want to set up (or disburse it directly)?

**Comment by piamancini** [comment]
@patcon exactly (and both, you can create a top-level collective see [here](https://opencollective.com/wwcode) and [here](https://opencollective.com/operationcode), or disburse directly to any collective you host). By host I mean you receive the funds for.

Think about open collective as a virtual layer over your bank account. You receive a grant on the account and then via open collective you  allocate the funds to each collective. There's no transference of money, since it all sits in the same account, but now each collective has a budget they can expense against transparently. This allows you to easily monitor each collective's balance, manage expenses and receive reports. 

If you wanted, you could then enable them to raise funds via open collective (funds that would go to your bank account but already allocated to that collective)

**Comment by patcon** [comment]
Ok, this is wonderfully helpful! I think we still have questions, but this issue has drifted enough, so I'll open others for that. Thanks Pia!

**Comment by shapironick** [comment]
One last peep, if I may! Thanks @patcon for following through on this and thank you @piamancini for your thoroughness and patience in responding. One last question that our bookkeeper asked is "does it work if it’s not actually connected to a bank account? We’re using QuickBooks as a shadow system and I can’t tell if this can be used the same way." This is because we're a fiscally sponsored project and not our own non profit, so we keep our own books while the money is in a certified 501c3's bank account. thanks!

**Comment by piamancini** [comment]
hi @shapironick I thought you had the funds yourselves and wanted to assign them to a collective. If you don't then it would be more like a shadow system as well (I like that idea). 

You 'manually add funds' which is essentially publicly stating you have $X for your project and then you submit an expense you incurred in the 'already reimbursed' option. When you hit PAID, the expense amount will be deducted from the balance of your collective, without a payment being executed. 

In this way you keep an open and transparent ledger of how you use the grant. 

How do you disburse the $ from the c3 atm?

**Comment by shapironick** [comment]
Thanks @piamancini , super helpful. we'll give this a try in tandem with the system we are already using, and then hopefully it works well and we can let go of the old system. 

currently we send them the invoices through a google form, and note it in our shadow system and reconcile once a month. they cut checks once a week. 

our current budget is $166,242.73 but it could triple within a year. it seems a bit bigger that most of your current users, no?

**Comment by piamancini** [comment]
hi @shapironick we currently manage as a supercollective the Open Source Collective, has over 500k consolidated yearly budget. The largest collective is webpack, has about 230k atm as a yearly budget. I'm happy to help you establish an easy way of manage it. The platform makes it pretty straight forward. 

You would upload your receipts and as already reimbursed and hit 'paid' when they send you the money. I also reimburse all collectives from their funds (we are the fiscal sponsor for 99% of the open source projects) once a week, it's a good rhythm.
