### ISSUE TITLE
Add host fees to host budget immediately

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3858]
## User story 
As a host admin, I want my host budget to update in realtime, with fees added to my budget as the transactions come in, instead of once a month, so I can use the funds to pay expenses right away, and keep an accurate picture of how my budget is doing.

## Best solution for this problem
Instead of waiting for a monthly date, add Host fees as soon as the funds are added to Collective balances.

This came up because we have been waiting for a big grant to come in so we can have the host fees to pay a legal bill. Finally it came in and we added the funds, but then we were confused because our budget was not updating as expected. Turns out we need to wait weeks to spend that money, which is really not great.

Related: #3846

**Comment by znarf** [comment]
The automated solution currently in place is really like the previous manual one. Host Fees collected the previous month are added as 1 transaction on the 1st of the month.

Adding host fees on a transaction basis would be more elegant in some ways but would also "pollute" the ledger. This is a topic that is discussed and open for a long time now.

It's doable. It's also an opportunity to have a definite answer on how the money should be accounted in the double-entry ledger, where is it coming from exactly?
 - In the past it was marked as coming from the Host and going to the Host Collective
 - Now, since we introduced Host Budgets, it's marked as the Host going to the Host, which is understood as a CREDIT (no DEBIT).
 - Cleaner would be to mark it as coming from the Collective to the Host.

If we mark it as coming from the Collective, this should also force us initially crediting the whole amount to the Collectives, including Host Fees.

**Comment by alanna** [comment]
What is actually happening is all the money is going to the Host and then the Host is  then crediting the amount minus host fees to the Collective. But doing it that could be even messier, because we want to show the link between the contributor and the Collective, without the Host in the middle.

Right now we already kind of fudge this by counting the total contributed in some places and the total minus fees in other places, right? Like, if someone gives $10 we show their contribution as $10 but the Collective balance only goes up by $9 if there's a 10% fee. 

So would it really be so different to actually credit the $10 to the Collective and then immediately debit $1 for the Host fee? So the initial transaction is $10 CREDIT to the Collective, then Host fees would show as a $1 DEBIT in Collective ledgers and a $1 CREDIT in the Host budget.

**Comment by alanna** [comment]
Apparently past-me thought fees as debits was a good idea #3552

**Comment by znarf** [comment]
This is done.
