### ISSUE TITLE
Stripe lacks support for application_fee in some Currencies

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3863]
**Describe the bug**
When donating to a collective that has a host using Stripe with a Brazilian account, it is impossible to set `application_fee` (collect fees at donation time) due to Stripe limitations.

We can not collect platform fees nor platform tips in these transactions, and we'll need to consider this when invoicing pending fees. The complexity here raises because there's an assumption that all Stripe transactions are already settled.

I suggest the creation of a new column in the Transactions table to track the platform settlement status and refactor everything related to charging fees and creating transactions.

As of now, we're simply waiving platform tips from collectives hosted in Brazil, we do that by setting `Collective.data.disablePlatformTips = true`.

**Comment by JoseRenan** [comment]
Hi, I have a collective based in Brazil and still getting this option with 15% as the default value:

![image](https://user-images.githubusercontent.com/11728746/109584758-ed740a00-7ae0-11eb-95e5-df364ba724b5.png)

Since all the donations made with this option active will fail, there is any way to hide this option in this case? Maybe instead of the select, show a link to the actual opencollective collective :thinking: at least while this problem is solved

**Comment by kewitz** [comment]
@JoseRenan sure! Can you send me your collective URL?

**Comment by JoseRenan** [comment]
@kewitz, the collective is https://opencollective.com/opendevufcg

**Comment by kewitz** [comment]
Blocked by https://github.com/opencollective/opencollective/issues/4124.

**Comment by kewitz** [comment]
From https://stripe.com/docs/connect/direct-charges#collecting-fees
> In line with Brazilian regulatory and compliance requirements, platforms based outside of Brazil, with Brazilian connected accounts cannot collect application fees through Stripe.

Apparently, Brazil is the only edge-case here.
