### ISSUE TITLE
Do not treat system-generated expense summary as an attachment

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3865]
It means every single expense says it has at least one attachment, which is not very helpful when reviewing expenses as an admin. I think there's an attachment to review, but there isn't. I need to scan and find the ones with actual attachments. The ones that say "1 attachment" actually have zero uploaded attachments.

<img width="1009" alt="Screen Shot 2021-01-20 at 2 22 24 PM" src="https://user-images.githubusercontent.com/5498878/105114357-a2eb8f00-5b2b-11eb-874c-83537a950571.png">

I think downloading the system-generated invoice, or expense summary or whatever we call it, should have its own location and own icon, separate from user-uploaded attachments.

**Comment by alanna** [comment]
bump

**Comment by Memo-Es** [comment]
> I think downloading the system-generated invoice, or expense summary or whatever we call it, should have its own location and own icon, separate from user-uploaded attachments.

100% agree with this issue, in the design file, the download invoice button is on the top left corner right by the expense title

<img width="306" alt="Screen Shot on 2021-05-17 at 07-51-54" src="https://user-images.githubusercontent.com/49539954/118491871-0ace7280-b6e5-11eb-81cd-aa762f2807db.png">

**Comment by Betree** [comment]
We have that in the implementation too: 
![image](https://user-images.githubusercontent.com/1556356/118492121-ff4c6d00-b71f-11eb-954c-90a38ea60f58.png)

I remember showing the generated invoice among the attached files was actually an iteration made after feedback, but I can find the context anymore so no blocker on my side to remove that.

**Comment by alanna** [comment]
Related: #4715 - if we're creating an expense actions menu, downloading the system-generated attachment would fit in there well.

**Comment by alanna** [comment]
I'm separating the core of this issue from the related #4993 to make it clearer.

**Comment by alanna** [comment]
This also applies when trying to preview expense attachments. You click to preview and the first thing you see is the system invoice, which is not useful for what that workflow is for (checking the user-uploaded file). You wait for it to load, then you have to click the arrow and load the actual uploaded attachment.

<img width="664" alt="Screen Shot 2022-08-02 at 2 10 58 PM" src="https://user-images.githubusercontent.com/5498878/182276932-dbf198d4-ebe1-43db-bc45-6836cafa35f0.png">

**Comment by kewitz** [comment]
Contrary to my first investigation, it seems that the Invoice PDF was, in fact, being used as a shortcut to access Expense information:

> I actually use the invoice attachment from the dashoard to check on things like the address and sometime to gather more information on the nature of the work done by the submitter - I find it quicker than opening the expense page.

I see two solutions for this:
1. Expose the Invoice Download button in the Host Dashboard
2. Make sure we're exposing more details in the Pay Expense modal (or maybe through the Security Checks?)

Either way, I think we should involve design in this issue.
cc @Memo-Es @alinamanko

**Comment by alanna** [comment]
I think the system generated invoice should just be treated as something completely different than uploaded attachments. The problem is combining them together and counting them as the same. Can it just have its own button? It should not increment the attachment count by 1 for sure.

**Comment by Memo-Es** [comment]
I agree with the quick fix @alanna mentions; currently, these two different links download the same file to your computer:

![Annotation on 2022-11-14 at 21-15-23](https://user-images.githubusercontent.com/49539954/201818050-c80cbf3f-6181-4ef3-aa10-46cb54d6bdc1.png)

I think we can leave the space under "Downloads" only for attachments and leave the system-generated invoice under the "More actions" dropdown, renaming it from "Download" to "Download invoice file."

I'll also be happy to work on a better solution, bringing https://github.com/opencollective/opencollective/issues/4113 back

cc @kewitz @alinamanko

**Comment by alinamanko** [comment]
Thank you for revisiting this issue. While I agree that separation of system generated invoice from attached documents makes sense I would like to see what could be the alternatives to hiding it under 'more actions'. From a host admin point of view, it adds another step to fetch the document if a review is needed. Agree that we should remove the duplication though as @Memo-Es suggests. 

What I described to @kewitz was the way currently host admin could open the invoice directly from the host dashboard without the need to go into the expense. When looking into large volumes of processing (for example for OCF I would have at least 40-50 invoices per payment run to go through) anywhere where the process can be simplified is better. 

Another thing to consider is that if we separate the invoice from the attachements, the functionality of having a preview of the doc (without the need to necessarily download it) is also something we would lose. 

I also have a question to ask. Do we now have the address field for folks submitting an invoice marked as mandatory? If so that will help with removing one check I am doing and then will help me to be more on board with the new options proposed.

**Comment by Memo-Es** [comment]
@alinamanko I agree, but it sounds like we should then work on #4113. I'd be happy to see this prioritized :)

**Comment by gustavlrsn** [comment]
Closing this as fixed in https://github.com/opencollective/opencollective-frontend/pull/8899
