### ISSUE TITLE
Add settings in the Actions menu

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3878]
<img width="1298" alt="Screenshot 2021-01-21 at 13 41 25" src="https://user-images.githubusercontent.com/806/105352618-6f256d80-5bee-11eb-97be-545d9e539343.png">

As admin of a Collective, when navigating on pages with the compressed navbar, I'm missing direct access to the settings while they could be added to the Actions menu.

This would be a temporary measure as Host Dashboard and Settings are gonna be merged in the future.

**Comment by Betree** [comment]
The long term solution for this is indeed to have an `Admin panel` button, linking to the unified dashboard. We can implement the button but link it to the settings for now, that would resolve https://github.com/opencollective/opencollective/issues/3482. 

It was actually implemented like that initially, but from the feedback that was given at the time I understood that we preferred to stay with the existing "Settings" button until the merged admin panel is ready which is why I removed it. Will bring that back.

**Comment by saideepesh000** [comment]
Hey @Betree @znarf , if this is still worth adding enhancement, can I work on this.
