### ISSUE TITLE
Start storing avatar photos in s3

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#39]
Currently, we link to a user's avatar photo on Twitter or wherever we can find it. Let's copy it to s3 and link to our copy. That way it won't go empty when the other site changes it.

**Comment by piamancini** [comment]
I think @ascari solved it here: https://github.com/OpenCollective/website/pull/173 It seems like we are raising issues in different repos and that @ascari is not a collaborator in this one because I can't mention him...

**Comment by xdamman** [comment]
I've just added him

**Comment by carlosascari** [comment]
@piamancini I believe (and I could be wrong) #173 fixed another issue you mentioned in issue #24 where the avatar that was set would not be displayed. BTW the loading indicator is an image, so its not loading forever, it just kept the loader image and the avatar was not placed over it.

In this issue the objective is to not rely on clearbit and the social media sources as well, since they can change or 404 every so often. Its a good idea.

**Comment by carlosascari** [comment]
@asood123 Please review and merge https://github.com/OpenCollective/api/pull/310

**Comment by piamancini** [comment]
@asood123 @carlosascari closing this as it seems to be solved in merge above.
