### ISSUE TITLE
Team section missing

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3905]
In OSC's settings, Team is enabled, but it's not showing on https://opencollective.com/opensource

![Screen Shot 2021-01-25 at 11 20 25 AM](https://user-images.githubusercontent.com/5498878/105645283-85d60800-5eff-11eb-9d9e-d24a6b9e4a80.png)

**Comment by alanna** [comment]
Same for https://opencollective.com/foundation and https://opencollective.com/protozoa. But not for https://opencollective.com/giftcollective so it's not affecting all hosts.

**Comment by Betree** [comment]
> @Betree could this be same issue we had (but on reverse) that budget was always visible even if we disabled it?

@piamancini Not really, for the budget section we just forgot to implement the condition that checked the `restrictedTo` field of the section (that defines that only admins can view it).

For this issue about the team section, the problem came from two things:
- The section was not added to these host when we implemented it (migration issue)
- Default sections were marked as enabled in the settings, even though they were not enabled on the page yet

https://github.com/opencollective/opencollective-frontend/pull/5767 took care of the second item, and I'll deal with the first one manually once it's deployed.
