### ISSUE TITLE
Add Collective names to consolidated receipt

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3908]
Here's what a consolidated receipt looks like when you have an organization with a large number of contributions (this is only one of three pages that all look this way):

![github-sponsors_opensource_2020-11-01_2020-12-30](https://user-images.githubusercontent.com/5498878/105646068-976cdf00-5f02-11eb-83ee-544094ad9107.jpg)

Each "Financial Contribution" is linked to the Collective, but either the description column should use the Collective name instead of the transaction description, or there should be another column for the Collective name.

**Comment by Betree** [comment]
Isn't that something specific to OSC / Github sponsors? Transactions names normally include the collective name. With a "regular profile", this is what I get:

![image](https://user-images.githubusercontent.com/1556356/105677934-cd9f6400-5eec-11eb-95de-55d057d6c797.png)

**Comment by znarf** [comment]
It's an edge case because the description usually contains the collective name or something more descriptive. Here, unless I'm mistaken, an admin decided to enter manually these entries as "Financial Contribution".

I don't think it's worth prioritizing this now, especially with the risk of breaking the layout.

**Comment by alanna** [comment]
If it's an edge case, we shouldn't prioritise it. But I'll leave it open.
