### ISSUE TITLE
New Pricing Page Design - Implementation

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3912]
### We have redesigned the pricing page to align with our new sustainability model.

- Featuring two main sections: "For Collectives" and "For Fiscal Hosts," as well as a FAQ module (@alanna, @piamancini, what content do we want there?)

---

![Desktop](https://user-images.githubusercontent.com/49539954/105796675-f8250780-5f54-11eb-8ae2-514118fa5366.png)

- For any copy change, comment here or add as a comment in Figma :)

See the [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=9752%3A0) 🎨 in figma

@znarf

**Comment by alanna** [comment]
I love how the colors and illustrations make it look much friendlier.

We've been through this before, but I still think we should consider whether we really want to put everything on one page, or whether it makes more sense to get users to pick the path they are interested in and only see the info relevant to them, because otherwise it's *so* much information and pretty confusing. You can imagine a person who doesn't understand our platform or the terminology getting really lost on this page. I personally liked the tabs on the old page, but I 

One big issue I see is that it's missing self-hosted Collectives. 

We have never really nailed a good way to communicate about them. We don't want to attach the complicated term "fiscal host" because we want the message to be as simple as "just connect your bank account". But actually where you have 3 categories of fiscal host (start, grow, scale) there's actually another one, "self", which is limited to a single Collective and can't charge host fees. Or you could think of the "Collectives" section as being divided into "Hosted Collectives" and "Self-Hosted Collectives" (but probably not those words), with the difference being to hold your own funds or apply to a Host to hold them for you.

Another issue: it says platform tips applies everywhere, but actually they are not turned on for OSC, which is the largest Host. So this might be confusing. I raised #3811 because I think we should bring OSC into line with the new model, to avoid exactly this kind of complexity when explaining pricing, but it's not resolved yet.

Besides that, I have a lot of tiny text changes to make... but I think it's actually easier if we just implement it and then I make a pull request with the text changes after (or while it's on staging), because it's too hard to work with Figma and a pain to pull all the text out into a document. I can work within the design and just make small text changes once it's implemented.

**Comment by alanna** [comment]
Thinking about this a bit more: we should radically simplify it. We can put all the detail behind links to more detailed pages. That way we can avoid hitting people with a wall of too much detail that might not apply to them, while allowing them to dig deeper to find out what they need to know.

Here's a version....

# Pricing

### FREE For Collectives
 * Unlimited access to all features
 * Platform Tips enabled
 * No fees if you hold money in your own bank account
 * Fiscal Host fees may apply
 * Payment processor fees may apply

### For Fiscal Hosts
* Host unlimited Collectives and get access to all features
* FREE if you don't charge Host fees
* Platform Tips enabled
* 15% revenue share if you charge Host fees
* If you manage >$150,000, we'll get in touch about an enterprise agreement

... and basically put everything else behind links to more detailed pages, or expandable details, or something, so when you look at the page you can quickly take it all in and figure out what applies to you.

Obviously there are a lot of terms used people might not understand, but we can have a detailed FAQ explaining Platform Tips, Fiscal Hosts, Host Fees, etc etc.

Note, this does not solve the issue of OSC not fitting in the new model, as mentioned above.

**Comment by piamancini** [comment]
Thanks @alanna - I think we can make some improvements but I don't want to delay having a functioning pricing page anymore. Let's see what can we fix: 

I personally like the fact that all the information is there and you are not forced to click through separate things to see more stuff. But maybe we can do an initial page that has to options for Collectives and Fiscal Hosts and the right box shows up when you click on one of the options. That would solve the problem of seeing twice for example the platform tips box. @Memo-Es can we do an option like this please? 

We could also remove the long paragraph after the title For Collectives. We should assume people read the homepage before landing there. That will clear the space a lot. I would leave the one under Fiscal Host because I think tit's worth clarifying the term. 

To the self hosted collective comment: that is exactly wha the first box is about. A self hosted collective is just a collective and we say it at the beginning, it is free for collectives. You've (and we all have) inherited this idea of hosts, self hosted, etc. but a new collective is not thinking about that. It's just reading it's a collective. I think what triggered this was the fact that we added a comment about host fees there, because we need to communicate that but the phrasing needs to be improved. @Memo-Es I'll make a couple of suggestions in figma to remove wording. 

On OSC I don't think we it's a problem right now. We want to experiment with platform tips but there are many hosts still on a plan that haven't activated platform tips either. It's an arrangement between host and platform. I think that adding the complexity here of making a message for OSC is not the right call.

**Comment by Memo-Es** [comment]
### Design update
---
![Desktop](https://user-images.githubusercontent.com/49539954/106095736-e92b8a00-60f9-11eb-8477-32b5f571999b.png)

[GIF](https://tafka.d.pr/2PSjem) showing the page interactions

@alanna @piamancini

**Comment by piamancini** [comment]
@Memo-Es is the Valid for All Plans behind a button or do you see it for everyone? If the latter - I think it lacks some coherence. Plans is related to hosts so I wouldn't expect collectives to read it. 

Maybe we display  Valid for All Plans + The Host Box under a Know More that brings it up and the info under Valid for All plans (with another title) in a know more under the Collective

**Comment by Memo-Es** [comment]
### Design update
---

![Desktop](https://user-images.githubusercontent.com/49539954/106216427-b4badb00-6198-11eb-96d9-9c76917dba27.png)

[GIF](https://tafka.d.pr/7DoYPM) showing the page interactions

@alanna @piamancini

**Comment by piamancini** [comment]
great! thank you @Memo-Es We can go ahead and do mobile versions

**Comment by Memo-Es** [comment]
### Design update - Mobile versions

| Desktop | Tablet Landscape | Tablet Portrait | Mobile |
|---------|------------------|-----------------|--------|
|  ![Desktop](https://user-images.githubusercontent.com/49539954/106371438-f29b3900-6329-11eb-9d5a-9d644f39a687.png)       |       ![Tablet landscape](https://user-images.githubusercontent.com/49539954/106371445-f62ec000-6329-11eb-9dd0-9f6f37766910.png)          |    ![Tablet portrait](https://user-images.githubusercontent.com/49539954/106371444-f5962980-6329-11eb-8784-f36d8d323ee2.png)     |   ![Mobile](https://user-images.githubusercontent.com/49539954/106371442-f4fd9300-6329-11eb-88d7-0c6a8512018b.png)     |
|         |                  |   ![Tablet portrait - Nav bar scrolled](https://user-images.githubusercontent.com/49539954/106371443-f4fd9300-6329-11eb-899c-034e1d1c3a3d.png)    |  ![Mobile - Nav bar scrolled](https://user-images.githubusercontent.com/49539954/106371441-f464fc80-6329-11eb-839d-c25c7e97d519.png)   |

See the [production-ready file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=9752%3A0) in figma 🎨


@znarf  @piamancini @alanna

**Comment by Memo-Es** [comment]
Closing this as it's live in production https://opencollective.com/pricing
