### ISSUE TITLE
Initiative name cut off in contribution flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3946]
<img width="742" alt="Screen Shot 2021-02-07 at 4 40 04 PM" src="https://user-images.githubusercontent.com/5498878/107135892-6dd0a080-6963-11eb-9f7e-7eb63049b8cb.png">

There are a couple things that could be improved here... Wherever possible we should show the full title.
1. If "contribute to" was smaller and on its own line, you could see the full event title
2. There's no reason "Wellington" should be cut off when it's on its own line with lots of space left

**Comment by Betree** [comment]
It's actually more tricky than it seems. The string "XXXXXX" will take more space on the screen than "......", even though they have the same number of characters, so it's difficult to set a max length that looks good everywhere. Yet we do have to truncate this string to accommodate with some initiatives having really long names.

Simplest fix would be to increase a bit the value that we use as max length, though that might not look good for other initiatives.

Two alternatives:
- Use CSS line clamping (cross-browser support is not ideal I think)
- Use the `AutosizeText` component to make the text smaller when initiative's name is really long

**Comment by alanna** [comment]
I don't think it's because of the difference between ..... and XXXXX because the middle line "entanglement evening" is like 20+ full size characters, and the word "wellington" is only 10 but it's truncated.

**Comment by Betree** [comment]
@alanna The truncation [is done](https://github.com/opencollective/opencollective-frontend/blob/51fefe7dd0507e192a64b00149dfef07aa11e28e/components/contribution-flow/ContributionFlowHeader.js#L51) on the **full** profile name, not the individual words:

```jsx
<FormattedMessage
  defaultMessage="Contribute to {collective}"
  values={{ collective: truncate(collective.name, { length: 30 }) }}
/>
```

What I meant with the size difference example between ..... and XXXXX is that it's difficult to find a value that works well for every case when truncating the strings (because two strings with the same length can have different sizes).

Thus the alternatives proposed in https://github.com/opencollective/opencollective/issues/3946#issuecomment-774722453, rather then just increasing the size (which would break the design in other cases) we should think about a long-term solution.

**Comment by Betree** [comment]
Temporarily increased the max length from `30` to `60` in https://github.com/opencollective/opencollective-frontend/pull/5913

**Comment by alanna** [comment]
+1

**Comment by Betree** [comment]
Closing as per https://github.com/opencollective/opencollective/issues/3946#issuecomment-838020080. Feel free to re-open if you think we still have work to do on this one.
