### ISSUE TITLE
Link fees & tips transactions details to platform settlement expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3952]
As a host admin, if I look at the transactions on the host budget, I see this monthly platform settlement transaction as a credit:

![Screen Shot 2021-02-09 at 9 32 10 AM](https://user-images.githubusercontent.com/5498878/107278265-6243bd80-6aba-11eb-9593-2b32670561b6.png)

If I click on it, nothing happens and there's no way to find out more about what it is or how that number was derived.

Meanwhile, over on the expenses page, there's this expense which is related but not the same amount. You can click on it and it has more details about numbers affecting the platform settlement amount:

![Screen Shot 2021-02-09 at 9 39 06 AM](https://user-images.githubusercontent.com/5498878/107278438-b2228480-6aba-11eb-9962-2764ac54e9a1.png)

So right now we don't provide a way for the user to get more details about the platform settlement transaction.

**Comment by znarf** [comment]
The first one doesn't have an Expense attached, explaining why there is no link. 

The second one is a different transaction.

**Comment by alanna** [comment]
OK, then we need to do something where someone can click on the transaction to find out what it is. Where can I see the expense attached to the transaction? I can't click on it. If it's not related to that expense, then where is the correct expense debiting these funds? I thought the credit and expense went in at the same time so the host budget didn't end up with funds they weren't allowed to spend because they are owed to OC?

**Comment by znarf** [comment]
>  Where can I see the expense attached to the transaction?

>  If it's not related to that expense, then where is the correct expense debiting these funds?

There is none. Similar to Added Funds for example.

> I thought the credit and expense went in at the same time so the host budget didn't end up with funds they weren't allowed to spend because they are owed to OC?

It seems it's another problem as the one described in the issue.

**Comment by alanna** [comment]
> It seems it's another problem as the one described in the issue.

No it's related because the problem underlying this issue is I can't find an expense that breaks down that platform fees and tips transaction. if it's not the expense I posted above, then how do I follow the path of that money in and out? I can't see another platform expense.

**Comment by znarf** [comment]
Can you double check and read the portion I commented and my comment? I didn't write it was not related, I said it was a different thing. You should agree, you even created an issue about it https://github.com/opencollective/opencollective/issues/3955 

Let's stay on track and focus on your problem about transaction details missing.

**Comment by znarf** [comment]
The title of the issue being "Link fees & tips transactions details to platform settlement expense", we're not gonna do this for the reasons explained above.

If it's about creating the "Platform Fees and Tips collected in January" through the Expense system and making sure there is an Expense attached to it, we should track this in a new cleaner issue.

While I understand the goal, I personally think this is not desirable because this transaction is actually more similar to "Added Funds" than an "Expense". It would be problematic as an Expense in our system: Where is the money coming from? Who's the Payer.

Ultimately, we would like to add these "Platform Fees and Tips" on a transaction per transaction basis, similar to what is asked in https://github.com/opencollective/opencollective/issues/3858

**Comment by alanna** [comment]
OK, I think the main issue is I don't understand why the platform settlement is not the same amount as the platform fees and tips, but we can discuss that separately. I'll close this issue because it doesn't work as I initially assumed.
