### ISSUE TITLE
Host admin can manually add funds to tier

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4009]
## User story 
As a host admin, I want to be able to select a particular tier when I am manually adding funds to a Collective, so that the contribution can show up correctly at the intended tier. Currently you can only add funds to the Collective's general budget.

## Best solution for this problem
Add a dropdown menu of the Collective's tiers in the 'add funds` modal.

![Screen Shot 2021-02-24 at 10 50 47 AM](https://user-images.githubusercontent.com/5498878/108913139-72e55d80-768e-11eb-8f25-5f0f2a149e2f.png)

**Comment by Betree** [comment]
Fairly simple to implement, the main difficulty will be to make sure we fetch the tiers everywhere (we probably want to do that in `AddFundsModal`).

Regarding the design, I think it's important to have (Optional) in the label since all the other fields are mandatory. That, or prefill the tier selection with something like "General budget" or "No tier".

**Comment by alanna** [comment]
Bump. This is something that will always come up, and currently requires involving OC devs to manually edit transactions to associate them with the right their. We said we want to avoid needing to directly edit the database where possible.

**Comment by Betree** [comment]
Looks like there's a common need for a `TierPicker` component between https://github.com/opencollective/opencollective/issues/5000 and https://github.com/opencollective/opencollective/issues/4009. Let's see if we can either extract that from somewhere (edit recurring contributions?) or at least make sure we don't double-implement in parallel
