### ISSUE TITLE
Manually added payment processor fees not charged

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4010]
**Describe the bug**
It seems that amounts put in the `payment processor fees` box when making a manual expense payout are not being applied.

A user reported this and I just tested it on staging.

I put $25 in the box and marked it as paid.

<img width="360" alt="Screen Shot 2021-02-24 at 2 32 55 PM" src="https://user-images.githubusercontent.com/5498878/108931993-7b995c00-76ad-11eb-84e1-7727eee3f4ff.png">

But on the expense and the transaction, it still shows $5000 not $5025.

<img width="677" alt="Screen Shot 2021-02-24 at 2 34 14 PM" src="https://user-images.githubusercontent.com/5498878/108932107-b00d1800-76ad-11eb-95db-5b442510d612.png">

**Expected behavior**
The system should add the processor fee amount to the total debited from the Collective balance for that expense. It should also show up transparently somewhere so you can see the fees that were applied.

**Comment by alanna** [comment]
@znarf @Betree can you take a look at this?

**Comment by Betree** [comment]
Looking at it

**Comment by Betree** [comment]
So the problem is not with the modal, things are properly recorded in our ledger. It's the value that we display in the transactions list that is incorrect. I'll make an update for that.

Showing the fees for paid expenses has been proposed in https://github.com/opencollective/opencollective/issues/3224, but it wouldn't hurt to also show that in the list - with the same "View details" pattern.
