### ISSUE TITLE
Use `next/image` component for the homepage

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4012]
**What**
Using `next/image`, we could be able to improve the loading time for the homepage where the images are pretty heavy.

**How**
Replace `<img` by `<Image` from `next/image`. Props should be adjusted to ensure we maintain good image quality.
See https://nextjs.org/docs/api-reference/next/image

**Comment by SudharakaP** [comment]
@Betree : I've created a pull request where all `<img>` tags are replaced by `next/image`. I later realized that this issue only concerns with the homepage images. 🤔 Is there a reason to only focus on the homepage? If so let me know and I'll adjust the PR. 😄

**Comment by Betree** [comment]
> @Betree : I've created a pull request where all `<img>` tags are replaced by `next/image`. I later realized that this issue only concerns with the homepage images. thinking Is there a reason to only focus on the homepage? If so let me know and I'll adjust the PR. smile

The idea was to test on the homepage first to see if we face any issues with that in production. It's also the place where it's most needed since we have many heavy images in there that would benefit from progressive loading.

https://github.com/opencollective/opencollective-frontend/pull/6009 is nice and we should keep that open for later, but I still think we should start with a smaller experiment just for the homepage.

**Comment by SudharakaP** [comment]
> > @Betree : I've created a pull request where all `<img>` tags are replaced by `next/image`. I later realized that this issue only concerns with the homepage images. thinking Is there a reason to only focus on the homepage? If so let me know and I'll adjust the PR. smile
> 
> The idea was to test on the homepage first to see if we face any issues with that in production. It's also the place where it's most needed since we have many heavy images in there that would benefit from progressive loading.
> 
> [opencollective/opencollective-frontend#6009](https://github.com/opencollective/opencollective-frontend/pull/6009) is nice and we should keep that open for later, but I still think we should start with a smaller experiment just for the homepage.

@Betree : Sure. I've done a separate PR (https://github.com/opencollective/opencollective-frontend/pull/6140) to migrate the `Topbar` and `Footer` to `next/image`. I think this makes minimal changes that will be reflected in the home page. Let me know if there's anything else to be changed/added. 😄

**Comment by SudharakaP** [comment]
@Betree : Ah, thanks. I was looking at your comment on https://github.com/opencollective/opencollective-frontend/pull/6140 and making some changes and it occurred to me that this might not be a wise change to make at this point. The problem with `next/image` is that we have to specify both height and width always. There's even an open issue at; https://github.com/vercel/next.js/issues/18497. Notice that even in the [other PR which I opened](https://github.com/opencollective/opencollective-frontend/pull/6009), I am doing this. I feel that this might not be the best moving forward as everyone will have to calculate the aspect ration of the images and make sure to set the height and width so that it looks nice. What do you think? 🤔 🤔

**Comment by Betree** [comment]
Setting `height`/`width` is actually a good practice to make sure that we reserve the proper amount of space. Without that, you end up with text jumping when the image loads (because it's 0x0 before loading). So it doesn't sound like a blocker to me, we can easily override these values with CSS if needed.

**Comment by SudharakaP** [comment]
> Setting `height`/`width` is actually a good practice to make sure that we reserve the proper amount of space. Without that, you end up with text jumping when the image loads (because it's 0x0 before loading). So it doesn't sound like a blocker to me, we can easily override these values with CSS if needed.

@Betree : Ah, sure that makes sense. Now I've converted all images to `next/image` in the homepage at https://github.com/opencollective/opencollective-frontend/pull/6140. Had to create a new temporary component that mimics `HomeIllustraction.js` in order to make sure we only convert the images in the homepage rather than doing too many changes everywhere. Anyways, let me know how it goes and if everything good I'll convert the rest as well. 😄
