### ISSUE TITLE
Expired Cards not handled as expired

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4058]
It should not be possible to pick an expired credit card when contributing.

<img width="729" alt="Screenshot 2021-03-04 at 13 57 57" src="https://user-images.githubusercontent.com/806/109967433-b294f080-7cf1-11eb-85f2-546b3889bcb4.png">

In the Contribution Flow, you get an error at next step when proceeding with the payment.

<img width="312" alt="Screenshot 2021-03-04 at 14 00 23" src="https://user-images.githubusercontent.com/806/109967667-fc7dd680-7cf1-11eb-8b42-42de236de18d.png">

In the Manage Recurring Contributions, there is no feedback, you can update the contribution with an expired credit card.

**Comment by Betree** [comment]
When expired, payment methods are properly disabled in the contribution flow and hidden in the "Edit payment method" popup.

![image](https://user-images.githubusercontent.com/1556356/117434141-96e5da80-af2c-11eb-834e-48d82fd811ad.png)

I found that the root cause for this issue comes from the API: we usually don't set any `expiryDate` on credit cards, the following query returns only 3 entries from 2017:

```
SELECT * FROM "PaymentMethods" pm 
WHERE "type" = 'creditcard'
AND "expiryDate" IS NOT NULL
ORDER BY "createdAt" DESC
```

The expiry date that we display in the frontend is based on `data.expYear` + `data.expMonth`.

I think that we should fix things on the API by:
- [ ] Adding a migration that fills `expiryDate` for all `creditcard` payment methods, based on `expYear`/`expMonth`
- [ ] Automatically settings `expiryDate` when creating the payment method
