### ISSUE TITLE
Track Settlement status on Transaction level

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#4077]
**Problem**
When it comes to calculating our revenue and settling pending fees, we have too many assumptions.
We can collect fees/contributions based on host, plan, collective, payment method, and order.
Most of the logic behind this live in our code, these are conditionals that will affect one thing or another when we process an order.
This code is mostly OK but since we don't persist the state of these logics in the transaction, we keep replicating these logics across the code: we need to translate how a transaction should be settled across order processing, collective metrics, host reports, platform reports, and Metabase reports.

**Proposed Solution**
Refactor Transaction model to keep track of settlement information:
- Add settlementStatus enum column: IGNORED or PENDING -> INVOICED -> SETTLED.
- Add settlementAmountInHostCurrency int column to calculate and track the amount of the settlement at processing time, can be null if IGNORED or if you wish the amount to be calculated on the settlement.
- Add settlementPolicy string column: PLATFORM_FEE, PLATFORM_TIP, HOST_REVENUE_SHARE

We'll also update the payment providers to consider this when creating Transactions.

**Comment by kewitz** [comment]
cc @Betree @znarf

**Comment by znarf** [comment]
- How do we detect when a transaction move from `INVOICED` to `SETTLED`?
- What's the value of `settlementAmountInHostCurrency`, is it like a kind of `platformFeeInHostCurrency`? Should we try find a better name?
- Can `settlementPolicy` be null? When would we have `PLATFORM_TIP` as a `settlementPolicy`

**Comment by kewitz** [comment]
> * How do we detect when a transaction move from `INVOICED` to `SETTLED`?

The settlement expense already stores the ID of all transactions involved in the settlement.
We'll add a conditional for when the expense is paid.

> * What's the value of `settlementAmountInHostCurrency`, is it like a kind of `platformFeeInHostCurrency`? Should we try find a better name?

Yes, in the case where we charge a platform fee, the settlement amount should have the same value.
I'm OK with any names, we should just make sure that everything is consistent, if we're persisting a settlement status then we also need to have a settlement amount.

> * Can `settlementPolicy` be null? When would we have `PLATFORM_TIP` as a `settlementPolicy`

We would assign PLATFORM_TIP to the original transaction. The tip transaction could be marked as 'IGNORED'.

**Comment by znarf** [comment]
> The settlement expense already stores the ID of all transactions involved in the settlement.

It's in a JSON blob right? Could this be more cleanly stored in the model?

> I'm OK with any names, we should just make sure that everything is consistent, if we're persisting a settlement status then we also need to have a settlement amount.

"settlement" doesn't mean much. settlement of what? we should find something more descriptive. I'll think about it, but great if you could propose something else.

> We would assign PLATFORM_TIP to the original transaction. 
>  The tip transaction could be marked as 'IGNORED'.

My original question was "Can `settlementPolicy` be null?" I don't get the use case for `PLATFORM_TIP`.

I actually think this is the tip transaction that should be taken into account in the settlement, not the other.

**Comment by Betree** [comment]
Looks good to me.

I guess the alternative if we don't want to blotter the `Transactions` table is to use a separate table like `TransactionSettlements` with `TransactionID | SettlementExpenseId | status | policy | amount`. The main benefit that I see in doing something like that is the immutability of the ledger: we're not supposed to update rows in the `Transactions` table (though we stopped respecting this rule a while ago).

I'm good with adding these columns to the `Transactions` table if it makes things simpler.

**Comment by kewitz** [comment]
@znarf exactly, that info is living in the data of the expense. I like the idea suggested by @Betree of creating a separate table to track this.

I agree settlement is a bit too generic, perhaps we should be more explicit and go for a table called `RevenueSettlements`?

The tricky part about `settlementPolicy` is that we're also not consistent with how we handle these transactions.
Platform tips create a separate pair of transactions and this is a unique behavior.
I like the idea of attaching the settlement policy to the original transaction because it will help us track and charge pending transactions and ignore the ones we already collected. I'm not against of ignoring the original transaction and settling the tip transaction tho, I would just like to have a consistent behavior because the existing problem is exactly this kind of conditionals everywhere.

@Betree I like the idea of creating a new table to track this, I don't think it will make things much more complex but I don't have full clarity on this and will only know for sure when I start implementing it.

**Comment by Betree** [comment]
Below are some specs proposals based on what has been discussed for this. My personal preference goes to the 1st one, using a separate `TransactionSettlements` (exact name TBD) indexed on `TransactionGroup` +`kind`. By avoiding data duplication, we make querying/updating easier and we avoid potential inconsistency issues. It also preserves the `Transactions` table immutability.

## 1. `TransactionSettlements` table indexed on `TransactionGroup` +`kind`

<details>

Alternative names: `TransactionDebts`, `Debts`, `DebtSettlements`

It implies a limitation, but that actually sounds like something we would want to enforce: there can be only one pair of transactions per `TransactionGroup`/`kind`. For example, we won't be able to have two `PLATFORM_TIP` for the same `TransactionGroup`. If this causes troubles later with for example, implementing something like a tip that can be dispatched between multiple collectives, a solution could be to also index on the `CollectiveId`. But for now, just using `TransactionGroup` + `kind` should work to enforce the uniqueness.

### Preview
- `Transactions`

id | type | kind | amount | TransactionGroup
-------- |-----------|-------------| --------|-------------
1 | DEBIT | CONTRIBUTION | -1000 | abcdefg-hijklmn
2 | CREDIT | CONTRIBUTION | 1000 | abcdefg-hijklmn
3 | DEBIT | PLATFORM_TIP | -100 | abcdefg-hijklmn
4 | CREDIT | PLATFORM_TIP | 100 | abcdefg-hijklmn

- `TransactionSettlements`

TransactionGroup | kind | status
-------- |-----------|-------------
abcdefg-hijklmn | PLATFORM_TIP | OWED

- SQL query
```sql
SELECT t.*, s."status" AS "settlementStatus"
FROM "Transactions" t
INNER JOIN "TransactionSettlements" s
  ON t."TransactionGroup" = s."TransactionGroup"
  AND t.kind = s.kind
```

### Pros
- The main argument for this is that there is no duplication of the information: there's only one settlement row per transactions pair (ie. one row for a platform tip, or for a host fee share). This translates into:
  - A smaller table
  - Smaller index
  - Easier to insert/update
  - No risk of inconsistencies between the transactions
- Keeps the `Transactions` table immutable
- Does not overload the `Transactions` table
- 1 to 1 relationship: no duplicate rows when joining a settlement to a single transaction

### Cons
- Needs a `JOIN` to get the data

</details>

## 2. `TransactionSettlements` table indexed on `transaction.id` (+ `type`)

<details>

This one also induces using a separate table, but it would link on transaction ID rather than transaction group. This proposal should also include the `type` (CREDIT/DEBIT) to prevent duplicate joins.

### Preview
- `Transactions`
*Same than previous proposal*

- `TransactionSettlements`

TransactonId | type | status
-------- |-----------|-------------
3 | CREDIT | OWED
4 | DEBIT | OWED

- SQL query
```sql
SELECT t.*, s."status" AS "settlementStatus"
FROM "Transactions" t
INNER JOIN "TransactionSettlements" s
  ON t."id" = s."TransactonId"
  AND t.type = s.type
```

### Cons
- Needs a `JOIN` to get data
- Data duplication

</details>

## 3. `settlementStatus` column on `Transactions` table

<details>

### Preview
- `Transactions`

id | type | kind | amount | settlementStatus
-------- |-----------|-------------| --------|-------------
1 | DEBIT | CONTRIBUTION | -1000 | NULL
2 | CREDIT | CONTRIBUTION | 1000 | NULL
3 | DEBIT | PLATFORM_TIP | -100 | OWED
4 | CREDIT | PLATFORM_TIP | 100 | OWED

### Pros
- No need to join
- Easy to query

### Cons
- Data duplication
- Many `NULL` entries
- Breaking `Transactions` immutability

</details>

**Comment by znarf** [comment]
I like 1), we also need to think that we need to establish a relationship between the `TransactionSettlements` and the settlement `Expense` when we move from `OWED` to `INVOICED`. Adding an `ExpenseId` column should do the job.

**Comment by znarf** [comment]
Closing as it was mostly  implemented in https://github.com/opencollective/opencollective-api/pull/5908.
