### ISSUE TITLE
Integrate bitcoin payments

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4084]
I'm starting this issue to hopefully scope what would be required to integrate bitcoin payments into the checkout flow. We haven't decided to prioritise this, but it would be helpful to understand if it's an easy thing or a hard thing.

OpenNode has [an API and documentation for developers](https://developers.opennode.com/). I reached out to them to try to understand how integration could work, and here's what they said.

----

1. User selects project that wants to contribute to
2. Select Bitcoin as an option, decide the amount to donate
3. Create a charge via OpenNode’s API where the order_id field is associated to that specific entity on OpenCollective (or map the charge id to a entity) and redirect user to OpenNode self-hosted checkout page (https://checkout.opennode.com/charge-id-here
4. User pays
5. Open Collective gets notification via webhook that the charge was paid and OpenCollective is able to map that specific payment to that entity. Credit the entity.

![Screen Shot 2021-03-11 at 5 56 03 PM](https://user-images.githubusercontent.com/5498878/111093831-b270dc80-859e-11eb-80bb-6ea3fb63c0d3.png)

**Comment by alanna** [comment]
@kewitz I'm in touch with the co-founder CTO and I think he's Brazilian - maybe you two could have a chat about it?

If it's hard, I'm not convinced we should do it, but if it's pretty easy it could be worth it. We've processed >$50k in BTC contributions already, even though most people don't even know it's an option because we don't have a good way to surface it.

**Comment by kewitz** [comment]
@alanna I don't think it is complex to implement this, especially because donations are instantly converted to USD.
This has just been falling out of priority but it still in my personal backlog, I think 50K is enough to justify raising its priority.
Also, accepting crypto would also create a buzz around Open Collective and OSC.

**Comment by alanna** [comment]
@kewitz I think it's a strong enough argument to at least scope this out. I'll connect you with the OpenNode contact in case you want to have a call with him. He seems eager to help out.

**Comment by alanna** [comment]
After talking with @piamancini - we can't prioritise this now and we want to take the time to properly look into options before going ahead.

**Comment by urza** [comment]
Hi. I strongly suggest you implement bitcoin payments via Lightning Network instead of onchain payments. With Lightning Network you avoid onchain fees and settlement is instant, neither side has to wait for onchain confirmation(s). For small donations like $5, onchain payments are uneconomical and bloat the blockchain unnecessarily. As Ligthning Network adoption grows, it is becoming standard for bitcoin payments.

One solution how to integrate this is use BTCPayServer - opensource payment processor for both onchain and lightning bitcoin payments 

https://github.com/btcpayserver/btcpayserver

**Comment by BenJam** [comment]
closing as we have an approach and an issue to pick up on in #5075
