### ISSUE TITLE
Wise balance on host dashboard doesn't update as you pay expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4087]
The purpose of showing the Wise balance (and PayPal balance) on the host dashboard is to know if you have enough funds to process expenses to be paid via those methods. However, I just checked the Wise balance and it said $108.55, then I paid these two expenses (auto via Wise), and the balance still says $108.55. Shouldn't it go down as you pay the expenses?

<img width="1008" alt="Screen Shot 2021-03-16 at 10 11 54 AM" src="https://user-images.githubusercontent.com/5498878/111222218-66767400-8640-11eb-9d04-a13f74970c87.png">

**Comment by kewitz** [comment]
This is already true and I was able to successfully test this on staging.
The problem is, in real-world applications Wise can take a little bit longer to validate the transaction and subtract the amount from the balance.
I refactored the balance resolver to consider the amount reserved in your Wise account, this should take care of the issue in production.
