### ISSUE TITLE
Exclude E2E Tests from Running for i18n/crowdin branch

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4117]
**Describe the bug**

I am wondering if it would be okay to exclude running E2E tests from the `i18n/crowdin` branch. Because whenever the robot pushes it's commits I see that all the other CI tests starts queuing up and we have to wait until the robot CI stuff finishes. 🤔 

**Screenshots**

![image](https://user-images.githubusercontent.com/12435965/112355675-1f653000-8c8b-11eb-8012-15879aacf6b7.png)

cc: @Betree

**Comment by Betree** [comment]
Definitely. There's a small test for internationalization in cypress (`test/cypress/integration/00-i18n.test.js`), but since we're not supposed to make important changes in that branch it's not crucial to run it. And the fact that Crowdin pushes one commit per language makes this too floody now that we are supporting 10+.
