### ISSUE TITLE
[PROJECT] Ledger Refactoring

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4124]
## Owners

@Betree @znarf 

## Overview

There is currently a few questions that are not easily answered with the structure of the ledger.

What is Open Collective revenue?
 - How much in Host Revenue Share to date?
 - How much in Host Revenue Share pending payment from the host?
 - How much in Platform Tips and Fees pending payment from the host?

What are the Fiscal Host owing to Open Collective this month?
- Pending Platform Fees
- Pending Platform Tips
- Host Revenue Share

What is the Fiscal Host budget?
- Host Fees added to the budget in real time
- Host Revenue share deducted in real time
- Total money on account / due

There are also mechanisms that are unpractical:
- Adding Host Fees to the Host Budget on a monthly basis. Issue: https://github.com/opencollective/opencollective/issues/3858
- Removing already paid Host Revenue share on a monthly basis
- Adding Pending Platform Fees and Platform Tips to the Host Budget on a monthly basis

This is also an opportunity to move these items to real time.

## Prioritization

- Does this serve our mission?

This will help us provide clearer accounting for the Platform and the Hosts. Accounting is a core to our mission.

- Does this increase quality? 

Yes

- Does this add technical debt?

No, it's clearing technical debt.

- Is it feasible to build and maintain with our current team and runway?

Yes

- What insight or research is this project based on?

It's based on what we learned with Fiscal Hosts and implementation of the new pricing model.

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 

We think we have a good understanding of the problem now.

- What is the estimated time-frame for delivering this project? 

6 weeks to 3 months.

## Details

Platform Fees is generally a non-issue, because we're deprecating them and don't expect to have any on July 1st the latest.

1) Adding Pending Platform Tips to the ledger

type       |    amount  | netAmount | to          | from      | host        | kind                       | settlementStatus 
-------- |-----------|-------------| --------|---------|----------|-------------------|----------
CREDIT  |    +100     |     +100        |   eslint  |  kewitz   |  osc        |  CONTRIBUTION   |
DEBIT     |     -100      |     -100         | kewitz  |  eslint    |                 | CONTRIBUTION    |
CREDIT   |   +20   |    +20       |      opencollective    |  kewitz        |      opencollective    |     PLATFORM_TIP
DEBIT    |   -20     |     -20      |       kewitz         |     opencollective                  |         |  PLATFORM_TIP
CREDIT |    +20     |   +20     |       osc            |    opencollective     | opencollective    |   PLATFORM_TIP | OWED
DEBIT   |    -20      |   -20       |    opencollective   |  osc             |    osc          |        PLATFORM_TIP |  OWED

2) Adding Host Fees + Host Fee Share + Pending Host Fee Share to the ledger

type       |    amount  | netAmount | to          | from      | host        | kind                       | settlementStatus 
-------- |-----------|-------------| --------|---------|----------|-------------------|----------
CREDIT  |    +100     |     +100        |   eslint  |  kewitz   |  osc        |  CONTRIBUTION   |
DEBIT     |     -100      |     -100         | kewitz  |  eslint    |                 | CONTRIBUTION    |
CREDIT  |   +10  |     +10     |       osc       |         eslint      |        osc        |          HOST_FEE
DEBIT   |  -10    |   +10     |       eslint    |         osc          |       osc        |          HOST_FEE
CREDIT |    +1.5   |    +1.5      |      opencollective  |   osc        |         opencollective   |    HOST_FEE_SHARE
DEBIT    |  -1.5   |    -1.5     |       osc     |           opencollective   |   osc         |         HOST_FEE_SHARE
CREDIT  |   +1.5    |  +1.5     |       osc        |        opencollective   |   opencollective    |  HOST_FEE_SHARE |  OWED 
DEBIT  |    -1.5    |   -1.5        |    opencollective    | osc         |        osc         |         HOST_FEE_SHARE |  OWED

3) Everything together (maximum complexity)

type       |    amount  | netAmount | to          | from      | host        | kind                       | settlementStatus 
-------- |-----------|-------------| --------|---------|----------|-------------------|----------
CREDIT  |    +100     |     +100        |   eslint  |  kewitz   |  osc        |  CONTRIBUTION   |
DEBIT     |     -100      |     -100         | kewitz  |  eslint    |                 | CONTRIBUTION    |
CREDIT   |   +20   |    +20       |      opencollective    |  kewitz        |      opencollective    |     PLATFORM_TIP
DEBIT    |   -20     |     -20      |       kewitz         |     opencollective                  |         |  PLATFORM_TIP
CREDIT |    +20     |   +20     |       osc            |    opencollective     | opencollective    |   PLATFORM_TIP | OWED
DEBIT   |    -20      |   -20       |    opencollective   |  osc             |    osc          |        PLATFORM_TIP |  OWED
CREDIT  |   +10  |      +10     |       osc       |         eslint      |        osc        |          HOST_FEE
DEBIT   |  -10    |    +10     |       eslint    |         osc          |       osc        |          HOST_FEE
CREDIT |    +1.5    |    +1.5      |      opencollective  |   osc        |         opencollective   |    HOST_FEE_SHARE
DEBIT    |  -1.5     |    -1.5     |       osc     |           opencollective   |   osc         |         HOST_FEE_SHARE
CREDIT  |   +1.5    |  +1.5     |       osc        |        opencollective   |   opencollective    |  HOST_FEE_SHARE |  OWED 
DEBIT  |    -1.5     |   -1.5        |    opencollective    | osc         |        osc         |         HOST_FEE_SHARE |  OWED

4) Once the Settlement invoice is paid, we should make sure it's properly tagged:

type       |    amount  | netAmount | to          | from      | host        | kind                       | settlementStatus 
-------- |-----------|-------------| --------|---------|----------|-------------------|----------
CREDIT  |   +20.5     |     +20.5     |        opencollective    |  osc           |       opencollective    |    EXPENSE  
DEBIT  |    -20.5      |   -20.5         |    osc          |       opencollective    |   osc               |    EXPENSE

To keep track of the settlement process, `settlementStatus` for `OWED` transactions should be marked as `INVOICED` then `SETTLED`.

4) For the Refunds, we will have to create all reversed transactions, even `OWED' one. We will be counting them in the next settlement invoice.

## Frontend

- `OWED` transactions should be ignored by default

Host Fees:
- will be moved to separate transactions and not appear anymore in the Transaction entries.
- to not bloat the UI, they should be ignored in the default view and accessible with a "ALL transactions" filter

_In Progress_

**Comment by Betree** [comment]
This proposal seems pretty mature. I like the fact that we're recording this as a separate transaction, making sure that we can compute the balances with a simple `SUM` is a very nice goal that should simplify many things. It should also not be too difficult to implement this as a non-breaking change for the frontend, for example the `transaction.hostFee` resolver could be something as simple as `transaction.getHostFeeTransaction().amount`.

My only interrogation is about the `settlementStatus` column. Similar to https://github.com/opencollective/opencollective/issues/4077#issuecomment-796799775, I have the feeling that we should implement this in a separate table:
- To keep `Transactions` immutable
- To avoid overloading the `Transactions` table (esp. if we think we may add more info about the settlement for transactions in the future)

But it's a small design preference. Using a column in the `Transactions` table is not a blocker for me.

**Comment by piamancini** [comment]
Review Call update: 
Implemented txn kind as a new column in the table 
Implemented the txn settlement, a separate table meant to track status of DEBT TXN 
Still some work to do: system is working but we are not using it to generate host invoice for example yet. This has rolled over to this sprint (S2Q2) 

++ Well scoped - as much as possible, since always things come up along the way. Overall description is good, we didn't deviate much. 

-- We should have communicated more clearly that we knew that it would take more than one sprint. 

New Goal: finish project by end of June - we might need to involve other devs so we can finish on time.

**Comment by Betree** [comment]
We just had a call with @znarf where I expressed some concerns about the approach we're currently taking here. While it achieves the goals that we have to have a clearer definition for the balances, it feels to me that it's not describing the reality properly as we're recording money transfers that never happened.

Taking the platform tip as an exemple:
![image](https://user-images.githubusercontent.com/1556356/118778106-0f805b80-b88a-11eb-993e-07058bdbbfe4.png)

Unless we're using Stripe (where we can directly take the tip out of the contribution), this is not what really happened. At this point, the contributor (`kewitz`) only gave money to the collective (`eslint`) so the host (`osc`) is the one actually holding the tip. In this proposal, we're solving the underlying balance issue by creating an `OWED` transaction from the host to Open Collective to describe this, which lowers the balance of Open Collective to make sure a `SUM` returns the real amount. The settlement transaction will then resolve this.

# Alternative proposal

My goal with this proposal is to offer an alternative approach that better describes reality while keeping things simple.

1. Recording platform tips

type       |    amount  | netAmount | to          | from      | host        | kind                       | settlementStatus 
-------- |-----------|-------------| --------|---------|----------|-------------------|----------
CREDIT  |    +100     |     +100        |   eslint  |  kewitz   |  osc        |  CONTRIBUTION   |
DEBIT     |     -100      |     -100         | kewitz  |  eslint    |                 | CONTRIBUTION    |
CREDIT   |   +20   |    +20       |      osc    |  kewitz        |    opencollective  |     PLATFORM_TIP  | OWED
DEBIT    |   -20     |     -20      |       kewitz         |     osc                  |         |  PLATFORM_TIP  | OWED

2. Host settlement transaction (sums all platform tips received by the host)

type       |    amount  | netAmount | to          | from      | host        | kind                       | settlementStatus 
-------- |-----------|-------------| --------|---------|----------|-------------------|----------
CREDIT  |    +20     |     +20        |   opencollective  |  osc   |       |  PLATFORM_TIP   |
DEBIT     |     -20      |     -20         | osc  |  opencollective    |                 | PLATFORM_TIP    |

# Diff between the two versions

<table>
<thead>
<tr>
<th width="25%"></th>
<th>Initial proposal</th>
<th>New proposal</th>
</tr>
</thead>
<tbody>
<tr>
<td>Record a debt tip</td>
<td>

1. Record contribution
2. Record tip from contributor to Open Collective
3. Record debt from Host to Open Collective
</td>
<td>

1. Record contribution
2. Record tip from contributor to **Host**
</td>
</tr>
<tr>
<td>Settle owed tips</td>
<td>

1. Create a transaction between the Host and Open Collective summing all the platform tips
2. Mark OWED transactions as settled
</td>
<td>

1. Create a transaction between the Host and Open Collective summing all the platform tips
2. Mark OWED transactions as settled
</td>
</tr>
<tr>
<td>Record a direct tip (Stripe)</td>

<td>Not mentioned in the specs, but I guess the simpest would be to record only the transaction from the contributor to the host, without any debt transaction nor settlement.</td>
<td>Directly record a transaction from the contributor to Open Collective, without any debt or settlement</td>
</tr>
<tr>
<td>Compute projected balance for Host</td>
<td>

```sql
SUM(netAmount)
WHERE HostCollectiveId = $hostId
```
</td>
<td>

```sql
SUM(netAmount)
WHERE HostCollectiveId = $hostId
AND "isDebt" IS NOT TRUE
```

</td>
</tr>
<tr>
<tr>
<td>Compute real balance for Host (money in bank account)</td>
<td>

```sql
SUM(netAmount)
WHERE HostCollectiveId = $hostId
AND collectiveId IN $hostedCollectives
```

</td>
<td>

```sql
SUM(netAmount)
WHERE HostCollectiveId = $hostId
```

</td>
</tr>
<tr>
<td>Compute real balance for Open Collective</td>
<td>

```sql
SUM(netAmount)
WHERE CollectiveId = 8686
```

</td>
<td>

```sql
SUM(netAmount)
WHERE CollectiveId = 8686
```
</td>
</tr>
<td>Compute projected balance for Open Collective</td>
<td>

```sql
SUM(netAmount)
WHERE CollectiveId = 8686
AND settlementStatus != 'OWED'
```
</td>
<td>

```sql
SUM(netAmount)
WHERE CollectiveId = 8686
OR (
  settlementStatus = 'OWED'
  AND HostCollectiveId = 8686
)
```
</td>
</tr>
<tr>
<td>Get all debts for settlement invoice</td>
<td>

```sql
FROM Transactions
WHERE isDebt = TRUE
AND settlementStatus = 'OWED'
```
</td>
<td>

```sql
FROM Transactions
WHERE isDebt = TRUE
AND settlementStatus = 'OWED'
```
</td>
</tr>
<tr>
<td>Refund a settled contribution with platform tip</td>
<td>

- Create a transaction to revert the contribution
- Create a transaction to revert the tip from Contributor to OC
- Create an `OWED` transaction from Open Collective to Host
- In the next settlement, deduce this amount from the total amount
- (Bonus) If the expense amount is negative, invert payee/payer
</td>
<td>

- Create a transaction to revert the contribution
- Create an `OWED` transaction from Open Collective to Host
- In the next settlement, deduce this amount from the total amount
- (Bonus) If the expense amount is negative, invert payee/payer
</td>
</tr>
<tr>
<td>How to display the tip in Open Collective's budget</td>
<td>Filter out debts</td>
<td>By default, owed platform tips won't be included on `/transactions`. We can eventually add a `includePendingTransactions` on GraphQL API if surfacing them is important. This flag would add all transactions where `isDebt=TRUE` and `HostCollectiveId` = 8686</td>
</tr>
</tbody>
</table>

## Personal conclusion

In my opinion, the alternative proposal better reflects reality. I also think it's a simpler model because there are fewer transactions involved, we just describe how the money moves. 

The main philosophical difference between the two is that the first approach considers the projected balance as being the default state whereas the alternative proposal considers the real balance (how much you have in your bank account) as the default state.

**Comment by Betree** [comment]
We're mostly there :rocket: Release is planned for 1st of July.

# Still to do

Tackle last items from #4332 / #4333:
- [ ] Hide host fee share (and their debts) in all CSVs @Betree 
- [ ] Put host fee in columns for collective report CSV @Betree 
- [ ] Put host fee in columns for host report CSV @Betree 
- [ ] Hide host fee (+ shares) in email transactions list @Betree 
- [ ] Add host fee share debt below "Platform tips" (Other credits) in host report email @znarf

# Release plan

- [x] Disable host settlement CRONs
- [x] Disable host report
- [x] Disable recurring contributions job
- [ ] Update CSVs/emails/reports (see `Still to do` above)
- [ ] Merge tests (will switch feature flag default)
- [ ] Delay deploy of API to 30th 00h00 UTC, to avoid platform tips in different currencies (sync with Leo or Suds)
- [ ] Recurring contributions
  - [ ] Run recurring contributions job manually on ~100 contributions and check results
  - [ ] Check PayPal subscriptions results
  - [ ] If everything looks good, re-enable the recurring contributions CRON job
- [ ] Compare settlement scripts results (DRY mode)
  - If not match => iterate
  - If match => run manually 
- [ ] Run host report manually
  - If not match => iterate
  - If match => run manually 

# Things to iterate on after the release
- [ ] Review accountants reports in metabase
- [ ] Review revenue metrics in metabase
- [ ] Revamp CSV reports
  - [ ] Merge the code to generate CSV between frontend (transactions list) and API (emails)
  - [ ] Show transactions groups
  - [ ] Update descriptions - eg. "Host Fee share for transactions group #xxxxx-yyyy-zzzz-aaaa".

**Comment by Betree** [comment]
All done. The remaining issues have been extracted to https://github.com/opencollective/opencollective/issues/4426 + https://github.com/opencollective/opencollective/issues/4427
