### ISSUE TITLE
Broken collective-tweet

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4150]
As reported on Twitter: https://twitter.com/luceos/status/1377541409071321091?s=21

Source: https://github.com/opencollective/opencollective-api/blob/10e0cbb0d14fc3f8d6097d5674d2ec180bc2eec2/cron/monthly/collective-tweet.js#L133-L144

Broken in: https://github.com/opencollective/opencollective-api/commit/463ca4c99161c18788eeb0d26d0135e8f484098d

**Comment by Betree** [comment]
I started investigating this one already, it appears that it was not caused by https://github.com/opencollective/opencollective-api/commit/463ca4c99161c18788eeb0d26d0135e8f484098d. The string renders something like `({twitterHandles}, +{count})` but if none of the new contributors have a Twitter handle we just display `(, +5)`. I will work on a fix today.

**Comment by Betree** [comment]
Will also take the opportunity to update `backers` to `financial contributors`
