### ISSUE TITLE
Move from "githubHandle" to "repositoryUrl"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4165]
*Based on the feedback received in https://opencollective.freshdesk.com/a/tickets/14260*

# User story

> It would be nice if the text field for entering the repository is not limited to GitHub. There are also GitLab, Codeberg or any self-hosted repositories.

# MVP

For this issue, we don't want to replace the inputs in the OSC Github flow (https://opencollective.com/opensource/apply) as we use the number of starts a project has as a mean to verify its popularity, and yet need to define similar criteria for Gitlab or other kinds of projects. Right now, they can apply manually and applications are carefully reviewed by humans.

What we want for this issue, is to allow users to use any kind of repository for their profile, the one that's linked in the collective page:
![image](https://user-images.githubusercontent.com/1556356/113825303-198a4700-9781-11eb-8817-e9a09761ad95.png)

We could achieve that by:
- [ ] Introduce a new `repositoryUrl` field on GraphQL API
- [ ] Deprecate `githubHandle` on the GraphQL API
- [ ] Migrate `githubHandle` to `repositoryUrl` in the model, adapt all existing entries
- [ ] Add legacy compatibility for `githubHandle` on the GraphQL API if `repositoryUrl` is a Github link
- [ ] Adapt the frontend. We can have a special icon for Gitlab, and if the provider is unknown we can just fallback on something generic.

**Comment by nfk** [comment]
Really useful feature for collective like mine with gitlab instance.

**Comment by numeropi** [comment]
Yes same here, my organization uses gitlab and we can't add it because it only OpenCollective accepts Github.

**Comment by BenJam** [comment]
@opencollective/design I think the only consideration here is that we might need a set of icons for engineering for GitLab, Codeberg, Radicle and a generic icon.

**Comment by BenJam** [comment]
- [ ] add `</> code repository` for generic repo links

**Comment by Memo-Es** [comment]
## Design input

We decided to have 2 different options:

Since the most common one is GitHub, for all GitHub repositories we are using this option
<img width="450" alt="Screen Shot on 2022-05-24 at 20-22-40" src="https://user-images.githubusercontent.com/49539954/170159023-32c21fe6-e313-4889-817a-7e72a9473234.png">

Fot all other alternatives we are using this option
<img width="453" alt="Screen Shot on 2022-05-24 at 20-22-19" src="https://user-images.githubusercontent.com/49539954/170159125-9f5b9557-5c3e-4d86-8234-93d68dc0b16b.png">

Both options have label now "Code repository" because we decided to treat this link differently from the rest of social media links that use only icons

[🎨 Figma file reference](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16687%3A237353)
