### ISSUE TITLE
Documentation for Funds

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4172]
We launched funds https://blog.opencollective.com/funds-for-open-source/ 🎉  but we didn't document it 😅 let's fix that.

FYI this is a template that I think we should fill in as the product, design and engineering team so we provide the necessary context for updating the docs from the start:

### What's changing?

We've introduced Funds: a new way of supporting your community https://blog.opencollective.com/funds-for-open-source/ Funds is a new way of thinking about open collective's offer, it includes:

- a streamlined, single payer process or supporters
- support for communities operating on open collective or elsewhere
- a lightweight 'request a grant' process for projects to apply to funds for support

### Why are we changing it?

Organsations often want to support many projects, but their procesurement processes mean the cost of doing so outweighs the benefits of providing that support. We're reducing the cost on their side by offering a managed process with a single supplier. 

### Who does this change impact?

Our messaging is focussed on the open source community, but there's no reason why we can't establish funds for other causes. The change impacts

- supporters, who may want to esablish a fund rather than support individual projects
- hosts, who may want to offer funds as part of their service
- collectives who may want to request a grant from a fund 

### How do users use it?
Right now the process is very much 'contact us'. From there we'll guide supporters, hosts or play matchmaker as necessary.  

### Is this change optional or mandatory?
This change is an option avaiaible to hosts and supporters who choose to collaborate on a fund. 

### Is this change being released incrementally as a beta? What's the schedule?
We're initially launching with a focus on open source, but there's no reason we shouldn't be able to offer something cimilar in different _verticals_ directly (through Open Collective Foundation for example) or thorugh another host.

From here I imagine we'll want to (again feel free to use this as a template)

### Documentaiton strategy
Add Funds as a new feature avaiaible to hosts, clarify the difference between Funds and funds managed by hosts for collectives. Consider adding 'request a grant from a fund' to collective guidance (we may wish to add this later).

### Changes to be made
Proposing a few mods that we might want to make here, feel free to ignore

- [ ] add 'Funds' to terminology https://docs.opencollective.com/help/about/terminology
- [ ] add 'Funds' to features https://docs.opencollective.com/help/product/product
- [ ] consider adding a comparison for Funds to https://docs.opencollective.com/help/product/product 
- [ ] consider adding 'request a grant' to docs for collectives
- [ ] add 'Funds' page to hosts docus
- [ ] review Open Source Collective and clarify Funds feature relative to managing 'funds' https://docs.opencollective.com/help/fiscal-hosts/open-source-collective

**Comment by kaylarep** [comment]
Current info about Funds that can be used to help:

- [Two kinds of initiatives (from OCF docs)](https://docs.opencollective.foundation/about/what-we-offer#two-kinds-of-initiatives)
- [Internal Info](https://docs.google.com/document/d/1xl3YB9YpDZAIjZUg3nzTvyO0Tg0aY1Tq9SFnT_-Zhyo/edit#heading=h.3i0gbqerqtwm)

**Comment by kaylarep** [comment]
Can we add Funds to the [terminology](https://docs.opencollective.com/help/about/terminology) page? (brief description + would link to the separate Funds page)

**Comment by kaylarep** [comment]
[Notes ](https://hackmd.io/@EYsBLmJDSOer2O0zv1Ntqw/HJOnjkDDu) from our last 'clarification' meeting:

**Comment by alanna** [comment]
I am not convinced that Funds should be a public facing self-serve feature at all, at least for now. It's been working well for us to have a high-touch relationship and directly support all Funds. That doesn't mean it shouldn't be documented, just that perhaps a basic description of a Fund is enough, and we can get into details with Fund creators in our conversations with them. I don't think we should necessarily open access to Funds to anyone to create and use.

This also speaks to how we need to continue clarifying what belongs in the platform docs vs specific host docs. Funds will mean something different to OSC and OCF. That difference should be fine to handle because that info will be in different docs. SCA or other hosts may start using Funds, and that will be different again. So I'd strongly suggest we only put the most generic info, that which is true for all hosts, int eh platform docs. We can link out to the host docs of hosts using Funds from there.

I see this as yet another permutation of the deeper design discussion that needs to happen around "Collectives within Collectives" —Events, Projects, Tiers with Goals, are all kind of overlapping. @piamancini has rightly sensed that we probably need a more elegant way of handling this without continuing to complicate and bloat the featureset. So before we dive deep into 'what is a fund' we should have that workshop.

**Comment by timfong888** [comment]
If helpful, these were questions I needed to explicitly clarify (and pia answered) after reading the docs a few times.  Could give insight into a newbie mind:

https://opencollective.slack.com/archives/C016456GD1N/p1620947264007000

Answers here:

https://opencollective.slack.com/archives/C016456GD1N/p1620977297005700

**Comment by BenJam** [comment]
While I agree that we (Open Source Collective, Open Collective Foundation) benefit from having a high-touch process for onboarding hosts right now I do think that the docuemntation at the very least should enable hosts to decide how the mechanics work in practice so that they can offer funds through their org. i.e.

> In general we should consider documentation on Open Collective as neautral to the environment that it is being used

**Comment by shannondwray** [comment]
Just clarifying that this is only available to OCF, OSC and OCE currently?

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#_lurYe
