### ISSUE TITLE
Invite organization to submit an expense 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#4224]
**Describe the bug**
Was updating the documentation regarding inviting a user to submit an expense, I noticed in the old documentation you could invite a personal account or an organization account to submit the expense. The option to invite an organization to submit an expense doesn't exist anymore. Just wanting to check that this wasn't something that was missed when the feature was updated. 

**To Reproduce**
1. Go to 'submit an expense 
2. Click on who is being paid and then invite someone to submit an expense. 
3. there is no organisation option. 
4. In the documentation: https://app.gitbook.com/@opencollective/s/help/expenses-and-getting-paid/submitting-expenses
the third image from the bottom shows the old experience.

**Comment by znarf** [comment]
@kewitz what happened to Submit on Behalf as an Organization, as seen in the documentation?

![deepin-screen-recorder_Select area_20201116200758](https://user-images.githubusercontent.com/806/117277547-46a14680-ae60-11eb-89a9-c814d32dd9ae.gif)

**Comment by kewitz** [comment]
The designed implementation considered that we were always going to invite a specific person and that person would decide if they wanted to create a personal profile or a profile for their company.

This is still an option, but it is an option for the invited user and not for the inviter.

**Comment by alanna** [comment]
> it is an option for the invited user and not for the inviter

The purpose of this feature is to allow the inviter to do all the work so the invitee just needs to confirm. If we don't achieve that, we might as well just have the invitee submit their own expense. 

It would be interesting to look at data about how people are using invited expenses:
* How much detail are inviters putting in (of what we allow them to input) and how much at they leaving for invitees?
* How many invitations are completed vs ignored/failed?
* How many invitations result in individuals or orgs submitting the expense?
* How many of the individual ones actually should be orgs (profile name does not match payout account owner)?

It's possible I'm wrong about the key use case for this feature (getting vendors to submit an expense instead of having to do a reimbursement because they won't use the platform), but we should try to look at some evidence to see.

**Comment by alanna** [comment]
Here's a comment thread explaining why this is important to users and communities: https://opencollective.com/bronzeville-kenwood-ma/expenses/49183#new-comment-on-expense

**Comment by alanna** [comment]
Bumping this one again. Inviting an org to create an expense is commonly a situation where the invitee has very little motivation to understand how the platform works, often is not very technical, and has low motivation to deal with complexity. We need to make it as easy as possible. I am sitting here about to send and email to an org I want to pay just knowing they are not going to have a good experience with this flow because I can't set up the org details for them in the invited expense.

**Comment by alanna** [comment]
@BenJam I think this is one to prioritise if you're going to focus on helping Collectives spend money.

**Comment by alanna** [comment]
Also, the invite expense interface asks for the payee. If the payee is an organization, the inviter will put the org name in here instead of the individual submitter's name. This is how we end up with orgs set up as individual profiles, which causes all manner of problems. and confusion.

<img width="694" alt="Screen Shot 2021-12-12 at 11 30 04 AM" src="https://user-images.githubusercontent.com/5498878/145693581-67c670b2-f985-4cea-803b-2320593dfd45.png">

The fact that it would take a paragraph to properly explain to the inviter that they should put a person's name instead of the org name in this box (which they would not read anyway), indicates the UX design here isn't working.

**Comment by kewitz** [comment]
Demo:
https://www.loom.com/share/19a2448bd8d744e297799b38ec1e5de1

**Comment by alanna** [comment]
Looking good @kewitz !

1. Keep in mind the user here is *not* someone from the org, but is inviting that org, so it shouldn't say "What does YOUR organization do". Maybe "Organization description"?
2. "Who will receive the money for this expense" doesn't make sense, because implicitly the invited organization is the one receiving it. How about "Contact name"? 
3. It's hard to communicate in this context that we need a human individual with a name and email who will then be the admin of this org profile. In practice I expect some people will just put the org name again, especially if it's a team/org email address not an individual's that they are putting in the next box. I guess that's fine?

**Comment by kewitz** [comment]
@alanna I will fix the labels of the fields.

3. We don't actually support an Organization profile without a User profile to act as admin. I think the submit on behalf kinda breaks this existing rule and we could think about refactoring this to allow people to log in straight with an Organization profile, but I don't think we'll be able to solve it in this issue.

**Comment by alanna** [comment]
Yeah I know. I think it's enough to change that field to "contact name" to make it clearer.
