### ISSUE TITLE
[DOCS] Adding Documentation about Virtual Cards

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4247]
As discussed https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP?node-id=10732:6433#78230645 we need to add documentation for Virtual Cards. Currently we don't seem to have any documentation about this. 😄 

Ideally we should have a link to the documentation section from the Host Virtual Cards page in host settings (as per the above Figma design). I am removing this link for now until we add the documentation for this.

**Comment by znarf** [comment]
cc @BenJam @shannondwray

**Comment by BenJam** [comment]
Looks like there's already virtual cards documented in the API. I'll pick this up initially.

**Comment by BenJam** [comment]
okay so darafts in for hosts https://app.gitbook.com/@opencollective/s/help/~/drafts/-M_VBGU-xIsA6G0R9N_G/virtual-cards and users https://app.gitbook.com/@opencollective/s/help/~/drafts/-M_QgG70qBzkQgD_FabN/expenses-and-getting-paid/virtual-cards 

Couple of things missing: 

- I was unable to verify the 'request a card' procudureso that needs to be done, and needs a screenshot. 
- I wasn't sure, but guessed that a paused card would also be rejected for ongoing (pre-authed) recurring payments with a provider

and a couple of points:

- it doesn't seem like there's any way to see whether you host offers virtual cards, so we will need them to be overt about this if they choose to offer them. 
- It is a bit weird that the action is 'assign card' instead of create virtual card, as there are no virtual cards _to_ assign until they are created. 
- I think we can do a better job of hand holding through the process to ensure that the user has created a card on privacy and has those details ready to input into the assign flow. Given the point above perhaps we should build a create flow that just points folks at priovacy.com?
- it **massively** threw me that, from the host virtual card settings  page it appeared that I could only assign a card to myself (the host) because this was pre-filled in the dropdown until I typed something

/cc @aminakazi @kewitz

**Comment by aminakazi** [comment]
> * It is a bit weird that the action is 'assign card' instead of create virtual card, as there are no virtual cards _to_ assign until they are created.

We call it 'assign a card' and not 'create card' because the card is created on privacy.com and not OC. Calling it create a card would be misleading. 

> * I think we can do a better job of hand holding through the process to ensure that the user has created a card on privacy and has those details ready to input into the assign flow. Given the point above perhaps we should build a create flow that just points folks at priovacy.com?

We do have[ text that mentions](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC-Design-Production-Ready-%E2%9C%85?node-id=10720%3A177205) they need to create the card on Privacy.com but if that isn't clear enough, maybe we can have a note on the 'settings' page/section of the virtual card
<img width="304" alt="Screenshot 2021-05-13 at 5 33 11 PM" src="https://user-images.githubusercontent.com/48468919/118123053-4e895980-b411-11eb-9c98-2ef5cf7b3d47.png">



> * it **massively** threw me that, from the host virtual card settings  page it appeared that I could only assign a card to myself (the host) because this was pre-filled in the dropdown until I typed something

We could have an [empty state for the drop down](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC-Design-Production-Ready-%E2%9C%85?node-id=12486%3A0) 
<img width="335" alt="Screenshot 2021-05-13 at 5 35 40 PM" src="https://user-images.githubusercontent.com/48468919/118123284-a7f18880-b411-11eb-8abb-2699a73ce2c5.png">
> 
> /cc @aminakazi @kewitz

**Comment by BenJam** [comment]
heh I think I accidentally turned this issue into a design review, but thank you for letting me do that @aminakazi :D 

>We call it 'assign a card' and not 'create card' because the card is created on privacy.com

That's a fair point....

> We do have text that mentions they need to create the card on Privacy.com

.. I guess from my comment before I was thinking to user might click 'create card' and be signposted, super obviously to Privacy, with a note to say when they should jump back into Open Collective to continue. Let's leave it as is and try to pick up if others are confused, it may very well just be me being a bit overly cautious. 

> We could have an empty state for the drop down

I would go for that if it was me, just becuase it seemed, from the outset that I didn't have the option to type. I'm not sure about the design standard for this but I'd always prompt the user toward an acion rather than guess their next action, and that feels a little like what we're doing here.

**Comment by BenJam** [comment]
Given the docs are ready @SudharakaP might you be able to link them up?

**Comment by SudharakaP** [comment]
@BenJam : Not sure what you mean by linking them up? Could you please elaborate on this a bit. 😄

**Comment by BenJam** [comment]
> Ideally we should have a link to the documentation section from the Host Virtual Cards page in host settings

Boop!

**Comment by SudharakaP** [comment]
> > Ideally we should have a link to the documentation section from the Host Virtual Cards page in host settings
> 
> Boop!

@BenJam : Ops, I forgot my own issue. 😄 Btw, just to confirm so what should the link point to is it https://docs.opencollective.com/help/fiscal-hosts/virtual-cards?

**Comment by shannondwray** [comment]
1. @BenJam get grammarly.com 😂
2. Was wanting to add some more screenshots to the collectives doc page but unsure how to get the virtual card feature added to my staging account. 
3. It may also be good to add information about how to get virtual cards turned on for hosts and collectives, as it has been a little confusing for me jumping in trying to find these sections in settings to have a look and them not being there. 
4. Please let me know if i'm just missing something :)

**Comment by BenJam** [comment]
> get grammarly.com

lol 👍

**Comment by SudharakaP** [comment]
>     1. @BenJam get grammarly.com joy
> 
>     2. Was wanting to add some more screenshots to the collectives doc page but unsure how to get the virtual card feature added to my staging account.
> 
>     3. Would I be able to get the feature turned on in my staging account: https://staging.opencollective.com/testcollective1

@kewitz : Just want to point your attention to @shannondwray 's comment on how to setup the virtual cards in her staging account, https://github.com/opencollective/opencollective/issues/4247#issuecomment-848467365. Not sure of the exact steps here so thought of asking you. Thanks. 🐨

**Comment by kewitz** [comment]
@shannondwray I created a few cards in the Sandbox environment so you can use them on staging:
The numbers are `4111111279155371`, `4111111243764787`, `4111111667415775`, `4111111413326847`, and `4111111148230231`.
You can just go ahead and add them to the platform using any expiration date and CVC.
