### ISSUE TITLE
Add funds returns 'created at' error

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#43]
host of WWCodeDC is trying to manually add funds to the collective and they are getting an error that says 'CreatedAt must be less than or equal to "Tue Apr 12 2016 17:00 GMT-7 PDT" idem for a different date. 
<img width="1130" alt="screen shot 2016-04-20 at 9 55 48 am" src="https://cloud.githubusercontent.com/assets/3671070/14694258/7ab65f92-071b-11e6-8ac5-8583d050e7d7.png">
<img width="430" alt="screen shot 2016-04-20 at 5 16 31 pm" src="https://cloud.githubusercontent.com/assets/3671070/14694280/ae5cf392-071b-11e6-9046-da28194dd275.png">

**Comment by asood123** [comment]
From what I can tell, the validator check is failing. https://github.com/OpenCollective/app/blob/master/frontend/src/validators/transaction.js#L22. (Notice `CreatedAt` is with a capital `C`. We use it everywhere with a small `C`, except in the validator.

1. I couldn't repro this in production or staging or localhost
2. First guess was the user's clock on computer was screwed up (hard to imagine in this day and age but who knows). I couldn't reproduce it on my machine either after messing with the clock.
3. Other theories: Maybe they are using IE?

**Comment by asood123** [comment]
IE8 doesn't support `Date.now()`, which is what we are using. 

@piamancini can you pls find out what browser she's using?

**Comment by sedubois** [comment]
Don't get where that 9-day difference comes from. The validation only accepts dates up to "tomorrow". The error message shows what the code thought was tomorrow's date = April 12th and so "today" was 11th -- vs. the reality being April 20th. One idea to debug is asking the WWCodeDC host to:
1. go to that "add funds" page
2. open the Javascript console (in Google Chrome on Mac OS X it's Alt-Cmd-j)
3. Note what time it really is
4. type the following commands one by one in order to see what they print (<enter> between each):
```
var createdAt = Date.now(); createdAt
var today = new Date(); today
var tomorrow = new Date(today); tomorrow.setDate(today.getDate()+1); tomorrow
var tomorrowIso = tomorrow.toISOString(); tomorrowIso
var tomorrowSlice = tomorrowIso.slice(0,10); tomorrowSlice
```
5. add the fund by clicking Submit
6. observe the error message in the banner
7. send screenshot(s) showing (if possible in same screenshot) the banner error and the console messages

(And I will evaluate myself the result of `Joi.validate(createdAt, Joi.date().max(tomorrowSlice).required().raw())`)

**Comment by piamancini** [comment]
She tried it again and it went through, it might gave been a setting on her side. I'm going to close this. We'll re open it if it happens again.
