### ISSUE TITLE
[DOCS]新しい

### ISSUE THREAD

**Issue by maanm0821** [opencollective/opencollective#4370]

**Comment by SudharakaP** [comment]
This ticket is closed due to **guidelines not followed**. 

All tickets should follow the guidelines as mentioned in: 

- The [Code of Conduct](https://github.com/opencollective/opencollective/blob/main/CODE_OF_CONDUCT.md).

- Submission guidelines as mentioned in our [README file](https://github.com/opencollective/opencollective/blob/main/README.md#issues).
