### ISSUE TITLE
opencollective

### ISSUE THREAD

**Issue by duongxuantuan** [opencollective/opencollective#4379]
URL: 
Logged in as (username or profile URL):
Error message if any:
Expected result: 
Browser:

**Comment by Betree** [comment]
This ticket is closed due to **guidelines not followed**. 

All tickets should follow the guidelines as mentioned in: 

- The [Code of Conduct](https://github.com/opencollective/opencollective/blob/main/CODE_OF_CONDUCT.md).

- Submission guidelines as mentioned in our [README file](https://github.com/opencollective/opencollective/blob/main/README.md#issues).
