### ISSUE TITLE
Unable to query projects through the API

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4383]
*This query was sent directly to me from someone tinkering with the API, so I'm passing it on.*

I’ve been struggling a bit with the GraphQL required to get a list of projects that come under a given collective.

- I want to get the list of projects that come under a given collective (identified by ID or slug).
I have tried the following, but it tells me "Please provide a slug or an id” for the initial part of the query.

```gql
query Account {
  account (throwIfMissing:true ) {
    id
    name
    slug
    website
    description
    longDescription
    expensePolicy
    tags
    type
    isIncognito
    memberOf (
      account: {
        slug: "ehf-community"
      }
    ) {
      totalCount
      nodes {
        id
      }
    }
  }
}
```

My failing approach is to try to get “all projects” (aka account) that are a member of “ehf-community”.

I’m a relative newbie at GraphQL so I might be missing something important, but I also can’t seem to get a list of projects just by querying directly for "ehf-community” and requesting a list of projects that it holds. PROJECT is not a type of “member” that an account holds. Could this be an oversight in the API, or is there a different way to approach this?

**Comment by alanna** [comment]
@znarf can you help?

**Comment by Betree** [comment]
The `slug` must be passed on the root `account` query:

```gql
query Account {
  account (throwIfMissing:true, slug: "ehf-community") {
    id
    name
    slug
    website
    description
    longDescription
    expensePolicy
    tags
  }
}
```

But `projects` are not yet exposed on our public API; we need to make a change to make that possible.

**Comment by znarf** [comment]
True, there is currently no way to access Events and Projects from their parent object.

**Comment by buzzykiwi** [comment]
Hi guys
I was the one who originally contacted Alanna with the question. A little background: we use Grants Management software called Fluxx, one of the major software systems available for grant making. I am doing a proof of concept of an integration between Fluxx and OpenCollective, so that grant applicants can indicate that they are using OC as Fiscal Sponsor and ideally provide a Project name/slug. Once these are in the system, the funder will be able to track progress of expenditure of the grant via the project. My plan is to make our integration available to funders using Fluxx around the world.

The reason for the query above is that I want the funder to be able to view and select from the list of projects under a Collective, when setting up the grant.

Thanks @Betree and @znarf for confirmation of how to do the query, and confirmation that the reason I could not find projects is that they are not there to be found.

Could I ask you whether you have any plans to expose Events and Projects so they can be seen from the parent object? Is this just a "to do" item, or is there a more fundamental reason why you don't want to expose them in this way?

Thanks
Stephen

**Comment by Betree** [comment]
Unfortunately, we're under limited capacity with the summer holidays and other priorities really need to be addressed during this period. Because it's a simple project, I hope we'll have the ability to prioritize it soon!

**Comment by buzzykiwi** [comment]
Thanks @Betree - I look forward to hearing more info once it's underway.
Cheers
Stephen
