### ISSUE TITLE
Event attendees not receiving email notification of update

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4416]
The organizers of [this event](https://opencollective.com/do-good-jobs-x-the-connectorship-project-7ff21cc4/updates/tuesday-6th-event-reminder-do-good-jobs-x-the-connectorship-project) need to email all attendees, but many of them registered as guests and now the system doesn't have their email. It's pretty common for events to need to be able to contact all attendees. We need to give organizers control over whether they accept registrations from guest users.

**Comment by alanna** [comment]
Hmmm I was wrong, even if they registered as guests it should have collected their email. So why are these attendees not receiving the email notification of the update?

**Comment by Betree** [comment]
It's strange, all these people got registered as `BACKER` rather than `ATTENDEE`.

However, looking at Mailgun's logs, it looks that the number of emails and the addresses they were sent to match what we expect. To better investigate, I would need an example of an email that did not get the notification where it should have.
