### ISSUE TITLE
Issues back 

### ISSUE THREAD

**Issue by clara98Rega** [opencollective/opencollective#4418]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Betree** [comment]
This ticket is closed due to **guidelines not followed**. 

All tickets should follow the guidelines as mentioned in: 

- The [Code of Conduct](https://github.com/opencollective/opencollective/blob/main/CODE_OF_CONDUCT.md).

- Submission guidelines as mentioned in our [README file](https://github.com/opencollective/opencollective/blob/main/README.md#issues).
