### ISSUE TITLE
Pledges - Open for All Websites

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4422]
I had this little problem when recently I wanted to create a pledge (https://opencollective.com/pledges/new?), but our pledges page blocks the creation of a pledge if there's no GitHub URL. Also I think it needs to be a org or repo with 100 stars. I was wondering whats the reason for this limitation? The project I wanted to create a pledge doesn't have GitHub. Ideally, can't we just simply ask for the URL instead of the GitHub url and not check for GitHub stars? 🤔 🤔 😄

**Comment by Betree** [comment]
I think there were two main goals with this limitation:
1. Apply OSC's conditions: The pledges flow is currently dedicated to collectives who should be hosted by OSC, and having a repo with 100 stars is a prerequisite to be automatically approved by them. There are other solutions when applying manually, but the idea is that a project needs to gain some popularity before it can be hosted.
In the past, claiming a pledged collective was an automatic process, so this condition was mandatory. Since it's manual today, we don't need it as much anymore, but it still is a nice pre-filter.
2. Avoid SPAM: if we let anyone add a pledged collective with just an URL (or without verifying the popularity of the repo), we'll get SPAM. Both for projects that have nothing to do with the platform, but also Casinos, Keto, CBD, etc... for this reason, and because pledges are not that important of a feature (you can always contact project admins directly to achieve the same result), I would prefer to not touch this limitation.

**Comment by SudharakaP** [comment]
@Betree : Thanks much for the explanations. Makes sense. 🤔 😄
