### ISSUE TITLE
Budget not adding up

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4431]
https://opencollective.com/study-into-action/projects/artcoop

It shows $6000 coming in, $174.30 payment processor fee, $300 disbursed,$5,525.70 balance and $5,825.70 total raised.

* Total raised should be $6000
* There have been zero expenses and no other transactions. Where is the $300 disbursed coming from?
* What happened to host fees?

![Screen Shot 2021-07-07 at 8 58 44 AM](https://user-images.githubusercontent.com/5498878/124666234-da939b00-df01-11eb-83c4-bef1ad9265a0.png)

![Screen Shot 2021-07-07 at 8 56 15 AM](https://user-images.githubusercontent.com/5498878/124666244-dd8e8b80-df01-11eb-829f-2d486111748f.png)

**Comment by Betree** [comment]
This is related to the recent ledger refactor.
- Payment processor (stripe) fee was $174.30, this number is correct
- Host fee is $300 (5% x $6000). This should be displayed in the transaction details, I need to investigate why it's not in this case
- The `Total disbursed: $300` metric is wrong: we should not count fees as disbursed money
- The balance is right: $3000 - $174.30 - $300 = $5525.70

**Comment by Betree** [comment]
I've fixed the total disbursed metrics.

The host fee is still not displayed in the transaction details, and that's because it is now a separate transaction. The proper way to look at it is by using the `kind` filter on the transactions page, I just recorded a demo to explain how to do that: https://www.loom.com/share/d3c3f6c28d354c948b52ca9b6d75d475. I started https://github.com/opencollective/opencollective/issues/4438 to discuss transaction details further.
