### ISSUE TITLE
Add description next to 'Virtual Card Policy' for hosts

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#4443]
Add next to the title 'Virtual Card Policy' within Virtual Card Settings where the written policy's text will appear.  

This will help hosts understand when/where users will see their policy. Rght now it is unclear where the policy is displayed. 

Also hosts will understand that they can add some sort of acceptance criteria/questions for card requesters here.

Sample text:
"This policy text will appear in a pop up when someone 'Requests a Virtual Card' from the Host's Action Button. You can also application questions here. The requester will have the option to add a note/reply."

## Best solution for this problem
The text could either appear smaller/in parenthesis or could be a little blurb that appears when you hover over an (i)

![image](https://user-images.githubusercontent.com/64920686/125138684-f21a8180-e0c3-11eb-9b7c-049132cc7241.png)

**Comment by SudharakaP** [comment]
My thinking here is to add a small info icon with a tool-tip so that when the user hovers over it they will see the sample text. Something like the following; 

![Screenshot from 2021-07-10 20-08-40](https://user-images.githubusercontent.com/12435965/125181610-5b30f080-e1bb-11eb-97fc-184e3b68f9d6.png)

As for the sample text, I am not exactly sure about the first line, shouldn't it be, "This policy text will appear in a pop up when someone 'Requests a Virtual Card' from the **action drop-down in the collective page**."

cc: @kewitz

**Comment by kaylarep** [comment]
This looks like a great idea @SudharakaP ! 

Maybe the text can read: "This policy text will appear in a pop up when someone 'Requests a Virtual Card' from the Action menu on the collective's page."

(just trying to not have the words 'up' and 'down' in the same sentence so its not too confusing hopefully.

Is it displayed anywhere else as well?

**Comment by SudharakaP** [comment]
> This looks like a great idea @SudharakaP !
> 
> Maybe the text can read: "This policy text will appear in a pop up when someone 'Requests a Virtual Card' from the Action menu on the collective's page."

Thanks. Yes, that makes sense. 😄 

> Is it displayed anywhere else as well?

The policy is also displayed at the top of the collective settings (virtual cards section) but that is only seen by collective admins, so my thinking is that the above sentence is accurate. 😄 

@kewitz : I've made a quick PR for this, but in case if you disagree with this or think we need to have an alternative design feel free to let me know; we can reiterate. 😄
