### ISSUE TITLE
Inconsistent PayExpenseButton behavior

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#4453]
**Describe the bug**
For the same expense, we can have two different pay expense buttons being presented in the expense page and in the dashboard.
We should make sure we have enough data to present the same button on both pages.

Example:
The payment modal in the Expense page displays the old PayPal screen, even though the host is using PayPal Payouts.
The button should be offering to Schedule the Expense for payment:
![image](https://user-images.githubusercontent.com/2119706/125653881-f19be132-5e3b-4cc7-af91-0381fcc79aaa.png)

The same thing happens for Wise payments, in the Expense page, it will only allow the expense to paid manually because it can't detect the host is connected to Wise.

**Comment by SudharakaP** [comment]
@kewitz : There's a thing I missed here. Note that in my PR I only show the budget section; I just realized that this buttons also appear on the expenses screen. We need to fix that as well. I'll do a PR soon. 🙂

**Comment by SudharakaP** [comment]
@kewitz : I also noticed that we need to add a condition to guard against collectives that doesn't have a host; otherwise a graphql error is being thrown which I've also corrected in the above PR. 

https://github.com/opencollective/opencollective-frontend/pull/6631/files#diff-01e697628ff3f9c10f4cec946fc2e1cee905f7086d22fd0199462b5247b82e04R131-R132
