### ISSUE TITLE
Create New Payment Method Type for Crypto Contributions

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4456]
We need to create a new payment method type for crypto contributions. I am proposing the following changes to the tier page; 

- [x] Add `Crypto` payment method type (just like enable flexible contributions)
- [x] When the crypto type is created it should show the tier card title as `Crypto Contribution`; something along the lines of the design below.
- [x] Hide the crypto creation option under a feature flag for now. 

Currently we have the flexible contributions section as follows;

![image](https://user-images.githubusercontent.com/12435965/127196426-03c15891-97bf-45f3-9aa4-a2fe5f9ca9c9.png)

Similarly, we need to add the Crypto Contributions section below that. 

Something similar to the following card will be shown when the crypto contributions are enabled; 

![image](https://user-images.githubusercontent.com/12435965/125860951-6bb8d564-855d-40cc-8f69-5872862c23f1.png)

@opencollective/design @kewitz : Feel free to weigh in on this please; especially the part about the design. 😄

**Comment by aminakazi** [comment]
@SudharakaP Crytpo isn't a tier. Crypto is a method of payment, but it'll still live under the 'contribute' section. Hence we can't add crypto in the dropdown here. 

We have [a new design](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/OC-Design-Lab?node-id=11080%3A136051) which allows the admin to toggle crypto payment. It is yet to be moved to production. 

The crypto mode of payment can't be edited in terms of the name, description etc. because it will be a uniform mode of payment for everyone.

**Comment by SudharakaP** [comment]
@aminakazi : Thanks for the information. But I am not sure if this part falls under the scope of this project. The designs seems to revamp the contribution tier page. My suggestion is to handle the changes to the contribution tier page in a dedicated project and for now we add crypto as a tier which seems simpler. However I am open to change if others think if the changing of the contribution tier page should also be handled here. 🤔 

cc: @kewitz @BenJam

**Comment by znarf** [comment]
Crypto should not be a Tier Type. It can be something similar to "Enable flexible contributions"

**Comment by Betree** [comment]
I agree. Crypto is a payment method type, not a tier type.

Tier types are used for many things, like deciding whether we need to apply taxes (product, services) or create special types of memberships (ticket, membership). It seems dangerous to override it only because the payment method is different.

**Comment by SudharakaP** [comment]
@znarf @Betree : Thanks for the information. I've altered the issue to make the Crypto Contribution as an `Amount Type` instead. Hope that makes sense now. Let me know if there's anything you need to add/change here. 👍🏽

**Comment by Betree** [comment]
Using `Amount type` seems like a hack as well. The values for this field (flexible, fixed) have nothing to do with the payment method. We may want to allow flexible and/or flexible contributions with crypto in the future. I think the proposal from https://github.com/opencollective/opencollective/issues/4456#issuecomment-885556993 is a good approach.

**Comment by Memo-Es** [comment]
Just updated the issue regarding the tier card design update on the card and settings https://github.com/opencollective/opencollective/issues/4346

cc @SudharakaP

**Comment by SudharakaP** [comment]
> Just updated the issue regarding the tier card design update on the card and settings #4346
> 
> cc @SudharakaP

Thanks Memo. 😄
