### ISSUE TITLE
Updates to Updates not showing unless you hard refresh

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4482]
1. Publish a new Update or delete an old draft
2. Go back the to Collective page and scroll to the Updates section to see the results of your handiwork
3. The new Update does not show up
4. Do a hard refresh
5. See the new Update

It seems like a very natural path to post a new Update and then go back to your page to have a look. Can we refresh the page automatically or something?

**Comment by SudharakaP** [comment]
This one is something that I've seen several times but somehow forgot to create an issue as and when I saw it. Thanks @alanna. 👍🏽 

I think this is due out the Apollo cache policy we have (defaulting to `cache-first`) for updates. My thinking is that we should probably `cache-and-network` for updates since I suppose this can be quite a common flow and keeping the cache up-to date makes sense. 🤔

@Betree : I've made a PR for this, let me know if you disagree. 😄
