### ISSUE TITLE
Fix Zipcode Bug in Stripe

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#45]
From user Hunter Trujillo

Hey, I just tried donating, and after Stripe payment went through, I got an error in the title bar that said this:
Unexpected token < in JSON at position 0
And then in my console, I'm guessing you're using Redux, the action that failed was this:
DONATE_GROUP_FAILURE
There was a 503 from a request at this endpoint:
https://opencollective.com/api/groups/43/payments/
The page I was on was here:
https://opencollective.com/apex#support

User had changed ZipCode recently. No place in stripe path to change zipcode 

Possible fixes: 
* enable the zip code field on the stripe form
* disable declining cards that fail zip code verification on your stripe settings.

**Comment by xdamman** [comment]
I'm not a fan of adding the zip code in the form because it will scare Europeans who aren't used to that.

I wonder what triggers this error. You had to basically already have your card registered in stripe and then change your zip code with the bank?

I've momentarily disabled the zip code verification at stripe level. Can you try again?

**Comment by cryptoquick** [comment]
Yeah, that's exactly what happened, and I couldn't find a way to change that in Stripe, because they don't have a B2C login, afaik. It's just for their B2B service.

I tried it again and it worked now. That's a beautiful profile picker btw, is that custom? I generally leave that setting off on my Stripe settings, but the CVC verification on, it's pretty safe, imo, and people, especially devs, tend to move. 😸

**Comment by xdamman** [comment]
Glad it worked and thanks for your support to [Apex](https://github.com/apex/apex#backers)!

I've put the zip code verification back on. We'll see if we get more errors. What we definitely need to do is improve the error message. It shouldn't fail like that.
Thanks again for bringing this up to our attention! 👍

**Comment by piamancini** [comment]
closing this issue until we receive more errors.
