### ISSUE TITLE
Improve tip presets for free tiers

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4508]
When contributing to free tiers, you are presented with tip options in the contribution flow that don't look great:

![image](https://user-images.githubusercontent.com/1556356/127619232-cf4103bb-16c1-4a63-b6f9-c308bc8d8ea1.png)

# Proposed solution

I see two things to improve there:
1. If `tier.amount` is `0` and the amount is fixed, do not offer to add a tip.
2. If it's a free tier but with a flexible amount (ie. you can freely donate to the collective), we should hide the tip whenever you select `0` and show it you select a positive amount

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](https://docs.opencollective.com/help/contributing/development/bounties).

**Comment by znarf** [comment]
🏆 This issue was completed by @snitin315 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
