### ISSUE TITLE
Handle local tax on invoice expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4532]
## User story 
As an expense submitter who must charge and clearly mark GST/VAT/sales tax on invoices, I need a way to indicate the tax portion of what I am charging via an expense on Open Collective.

As a host admin, I must keep accounting records of the tax portion paid out to vendors/contractors, and need that separated out in the data I get from Open Collective.

## Best solution for this problem

For hosts who have the local tax setting switched on, an additional checkbox appears on incoming invoice expenses to that host, asking if this invoice includes GST/VAT, and if so, applies the local tax rate to the invoice, breaking it out into a separate line, and shows a box for the tax ID number. The system should already know the local tax name and rate, as it does for charging it on sales. Details like the taxID number should be saved, as payout info is.

![Screen Shot 2021-08-06 at 8 22 10 PM (1)](https://user-images.githubusercontent.com/5498878/128483831-0be068ed-2029-4129-9240-d3a6d27ec2c5.jpg)

## Metrics 
Host have an easier time dealing with tax reporting.
More hosts use OC because it achieves more basic standard tax functionality.
Expense submitters are clear about tax on their invoices, and need to upload attachment invoices less.

**Comment by alanna** [comment]
@Betree when you get back from holiday could you scope this? I'm considering the idea of sponsoring a bounty for it funded by fiscal hosts who need this feature.

**Comment by Betree** [comment]
This issue is similar to - but more comprehensive than, since it includes GST - https://github.com/opencollective/opencollective/issues/1552. Specs adapted from this issue:

# API
- [ ] On expense mutations, accept a `taxes` input for each `ExpenseItem`. Store that in a new `taxes` (JSON) field.
- [ ] Include total VAT for all expenses in the monthly report for hosts
- [ ] Record this information in `Transactions` (`taxAmount`) when paying the expense

# Frontend
- [ ] Add tax amount input field when creating/editing an expense (see design suggestion above) and hosts has a local tax

**Comment by snitin315** [comment]
@Betree how do we enable local tax for hosts? do we already have a dedicated field in fiscal host settings for this?

**Comment by Betree** [comment]
@snitin315 You have to set the currency of the host to EUR or NZD. On the settings page, you then have the ability to set up VAT (for EUR) or GST (for NZD).

**Comment by RomyKraemer** [comment]
This would be great to have, especially for hosts w communities from multiple countries. They'd need to be able to add their own local tax rate which should then be saved, together with their tax ID and other account info and added as an option to all invoices.

**Comment by Betree** [comment]
Just discovered that we have a `vat` column set on the `Expenses` table with that info set. We should ideally move this column when we tackle this.

**Comment by jfdh** [comment]
**Elaborating on Alanna's user story:**

As a host Admin, I wanna make sure that people only uses the invoice option to submit services with a legit tax status. In the EU, you need a company/tax number to get paid for a services you gave to a collective.

As a host Admin, I need my accountant to be able to get these tax numbers in the csv export. The accountant also needs separated zip files (one with expenses, the other one with all the invoices (for services)).

**Best solution for this problem**

Add a mandatory VAT/GST custom field (that some host can have, other not depending on the needs) after the user chose the invoice option.

P1 high frequency, high impact

**Comment by Betree** [comment]
Raw feedback below from the pre-kickoff call with @alanna and @jfdh; it was about scoping the different needs and seeing how they intersect between VAT and GST. It was mentioned in this call that we'll really need some help from @opencollective/design since this is a relatively complex feature that's touching the expense form.

**Common needs**
- Ability to specify whether an expense item (or an expense, if too complex to implement per item) **has a tax attached**
- Ability for expense submitters to input an optional **tax ID number**
- We'll start by implementing this feature **for invoices only**
- The collected tax ID numbers should ideally be included in **CSVs**
- Display tax amounts on **generated PDFs** 
- Today GST/VAT is not included in the balance, we should review that policy while implementing to make sure it's the best option
- Whatever we decide, it'd be great to have the metrics about collected/spent tax on the **host reports dashboard**. Accountants should have access to these metrics.
- Should be clear if the inputs for the amounts of the items are including or excluding the tax amounts

**VAT-specific needs**
- People need to be able to set a custom tax rate (because VAT differs based on your country and the type of product/service you're selling)
- On generated PDF invoices, if the host has VAT, invoices without it will usually need to include a special sentence: `VAT not applicable, article 293 B of the CGI`
- In the future, we may want to make the VAT ID number field required for invoices

**Comment by jfdh** [comment]
### Here is how [Smart](https://smartbe.be/en/) tackles this

Smart is a worker's cooperatives which use temporary contracts to allow workers to invoice for services

**Step 1**

![Smart 1bis](https://user-images.githubusercontent.com/30813303/157207248-d41335b6-b309-4dcc-9056-0a9cf450c9ab.png)

**Step 2**

![Smart 2](https://user-images.githubusercontent.com/30813303/157207276-cbbed9ad-8436-49a2-b31c-c987f13f4261.png)

**Step 3**

![Smart 3](https://user-images.githubusercontent.com/30813303/157207342-06846c9d-f34d-42b9-9258-8210cf40add2.png)

**Comment by piamancini** [comment]
- [ ] incorporate feedback and handover design

**Comment by flaki** [comment]
Here is something that we discovered recently that is a related issue that may affect this feature as well.

RustFest is handled by Bay Area Tech Club, an Estonian host using EUR as the main currency. We operate globally and for one of our events had live translation, invoiced from Mexico in US dollars. The invoice has been submitted [as an expense](https://opencollective.com/rustfest/projects/rustfest-global-2021/expenses/65995), but the expense states EUR because that is a requirement, so the expense submitter had to put an EUR amount using whatever conversion rate they had available to them.

Upon payment we, the host, used manual payment and the best available method to pay the expense in the target currency ($500 USD) and accounted for the difference between the originally stated expense EUR amount and the deducted EUR amount in the "payment fees" section. This worked because we paid ~8 EUR more above the originally stated 471 EUR of the expense amount, but if we would have paid less there would be no way to account for the difference (not sure if "payment fee" will take a negative amount?).

This means that we end up with a lot of extra conversions (which is also a pain for the expense submitter) for no good reason, as the final budget amount will end up determined by "how much we have paid from the bank account" anyway.

My ask would be that hosts should be able to define currencies they accept expenses in, and people should be able to select a currency more appropriate for their expense submission during the submission process. Open Collective could grab the daily presiding exchange rates from whichever provider it wants from to provide an *informational* amount in the UI for how that expense will affect the budget of the collective, and upon payment, instead of "payment fees" the host should input the total paid amount (the effect of the payment on the collective budget) instead.

The reason I'm noting this issue in this thread is because once you add regional taxes this will make it even more problematic (I'd imagine having to force an NZ invoice into euros because the collective is an EU-based one, and having to separately translate the invoice amount and taxes to EUR, manually, upon expense submission) -- whereas in reality the expense should reflect the original receipts as closely as possible, and AFAICT the final EUR amount is important mostly for *"how much should be deducted from the collective's budget for this payment"* reasons anyway?

> PS: if this has been discussed before, feel free to move this comment to another thread (cursory look didn't reveal any) but I can also re-file this as a separate issue if you'd like.

**Comment by Betree** [comment]
@flaki I believe another feature we're currently testing internally that's meant to be released publicly in the next few weeks, #5146, can help with this use case.

**Comment by piamancini** [comment]
- [ ] finalize the form

**Comment by piamancini** [comment]
- [ ] ship form as it is
- [ ] incorporate feedback into design and check again with team 
- [ ] options for GST / VAT

**Comment by jfdh** [comment]
Here is a great example of automated invoice generated by Accountable @Betree 

[a23d6920-ae90-11ec-a868-cf0d3bf3cd43 (1).pdf](https://github.com/opencollective/opencollective/files/8452206/a23d6920-ae90-11ec-a868-cf0d3bf3cd43.1.pdf)

**Comment by aminakazi** [comment]
Final production-ready files can be [found here.](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/?node-id=16310%3A239733)

A loom update can be [found here.](https://www.loom.com/share/9abaca9eeff342a4b373a720955ea59d)
