### ISSUE TITLE
Expenses getting through with no address saved

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4566]
Doing some compliance checks for OCF, I came across these profiles that have been paid a significant amount via invoices expenses in the last 12 months, but when I call the `address` field for their user collective in metabase, I get nothing or an incomplete address (e.g. in the US but missing the state).

https://opencollective.com/flea-street-cafe
https://opencollective.com/james-oliver
https://opencollective.com/viviane-allegretti-thoughtworks
https://opencollective.com/julia-viana
https://opencollective.com/kayla-ep
https://opencollective.com/andrew-kim1
https://opencollective.com/kimberly-calichio

How is the system allowing them to submit invoice expenses without an address or with an incomplete one?

**Comment by Betree** [comment]
Addresses for payees should be looked for in `expense.payeeLocation`. The value of `expense.payeeLocation` is automatically copied to `collective.address` if it's null, but there's no guarantee that users will not remove their addresses from the profiles after that, while `expense.payeeLocation` is immutable.

For `flea-street-cafe` (and probably some others), it's because all their expenses were submitted in 2020, before we introduced validation. The address is set to "See invoice", so it's not empty, but not correct either.

**Comment by alanna** [comment]
The problem is, the `address` field is what's printed on invoices and receipts. So [this one for example](https://opencollective.com/parentpreneur-foundation/expenses/48095) is not a valid invoice due to the incomplete address.

This is relevant for #3340 - at some point `expense.payeeLocation` and `collective.address` will be forced to match. But for now, how do we deal with these examples that are resulting in invalid receipts and invoices?
