### ISSUE TITLE
collective administration, emailing backers, expense approval/rejection protected via 2FA

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#459]
Howdy. It's pretty self-explanatory. Collectives are a centre of finance and right now they are only protected by 1FA. Let's get the security hardened and mitigate any infosec drama before it occurs.

**Comment by sbinlondon** [comment]
As an update, we are currently working on adding 2FA to payouts for hosts.

**Comment by sbinlondon** [comment]
@znarf @Betree @kewitz We're adding 2FA for payouts for hosts. What do we think about the other points included here - email, expense approval/rejection, other administration? I think expense approval/rejection is potentially covered by payout 2FA since you can't really approve and then payout without having the 2FA sorted. But maybe we want as many layers of protection regarding payments as possible. On the other hand, we don't want to introduce too much friction for too many things that hosts are doing daily. Thoughts?

**Comment by Betree** [comment]
Protecting the Sign In will be a good first step towards protecting all the features. After that we'll need to define what it critical and what is not. Editing the settings, emailing contributors (updates) and managing expenses does seems critical to me.

> I think expense approval/rejection is potentially covered by payout 2FA since you can't really approve and then payout without having the 2FA sorted

Not really, Approve/Reject is done by the collective admins while paying is the responsibility of the host admin. So you could hack the account of a collective admin to approve your own expense, most host admins will pay it as long as it looks legit.

> On the other hand, we don't want to introduce too much friction for too many things that hosts are doing daily. Thoughts?

Yes, that's why we really need to have a cookie to persist the authorization for _x minutes/hours_. If you've just verified your 2Fa 5 minutes ago to sign in, we should not ask for it again when approving/paying an expense.

If not created already, it would be great to have an issue about that - at least to estimate the cost of implementation.

**Comment by sbinlondon** [comment]
> Editing the settings, emailing contributors (updates) and managing expenses does seems critical to me.

Agreed 👍 

> > I think expense approval/rejection is potentially covered by payout 2FA since you can't really approve and then payout without having the 2FA sorted
> 
> Not really, Approve/Reject is done by the collective admins while paying is the responsibility of the host admin. So you could hack the account of a collective admin to approve your own expense, most host admins will pay it as long as it looks legit.

I can create an issue for this

> > On the other hand, we don't want to introduce too much friction for too many things that hosts are doing daily. Thoughts?
> 
> Yes, that's why we really need to have a cookie to persist the authorization for _x minutes/hours_. If you've just verified your 2Fa 5 minutes ago to sign in, we should not ask for it again when approving/paying an expense.
> 
> If not created already, it would be great to have an issue about that - at least to estimate the cost of implementation.

And also for this

So I'll close this issue since it's a bit broad, and link to the new ones, sound good?

**Comment by Betree** [comment]
> So I'll close this issue since it's a bit broad, and link to the new ones, sound good?

Sounds good

**Comment by alanna** [comment]
We have implemented 2FA
