### ISSUE TITLE
Admin dashboard reports: Total money managed section

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4606]
Part of https://github.com/opencollective/opencollective/issues/4300
Design file: [Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13711%3A157088)

---

## Collapsed view

- [x] For the first part of this issue, `HostMetrics` should provide all the data we need
- [x] The chart must use the primary color of the collective. For now, we've decided to build it with fixed percentage widths and without any JS library, just some good old CSS.

![image](https://user-images.githubusercontent.com/1556356/131500875-ce3784a5-1c17-42d9-81c5-71dcfc075335.png)

## Historical view

- [x] When clicked, "See historical" should expand and fetch the data it needs dynamically
- [x] On `HostMetrics` add a new `totalMoneyManagedProgress` field:
  - [x] Args: `year` (required)
  - [x] Response: `[{ date, amount  }]`
- [x] Use a [chart library](https://github.com/opencollective/opencollective/issues/4599) to display the progress across time
- [x] The select filter should include all the years of activity for this collective. We can achieve that with something simple like `getYearsFrom(getYear(collective.createdAt))`.

![image](https://user-images.githubusercontent.com/1556356/131501954-35c67b16-4d8d-4624-a2e0-f9c161c42b0c.png)

**Comment by SudharakaP** [comment]
@Betree : I'll take this one if no objections, or unless you already have plans to do it yourself. 😉  😄

**Comment by Betree** [comment]
@SudharakaP Feel free to implement the `Collapsed view` part. For the historical view, I want to explore a bit the API queries to try and see how we can re-use as much as possible what we have while making sure performances are there.

**Comment by SudharakaP** [comment]
@Betree : So I've done the initial implementation of the reports section. Hope it looks good. 😄 

Few things to note; 

1) I was exactly sure if I did the calculations correctly here; 

https://github.com/opencollective/opencollective-frontend/blob/bc49043dac6e1292a591eb93b959e15c5e7eb3f2/components/host-dashboard/reports-section/TotalMoneyManagedSection.js#L121-L126

Let me know if you see any issues. 

2) Small deviation from the design; I used the words `Collectives` and `Host Organization` instead of `My Collectives` and `My Host Organization` in the labels. It made it a bit easier to make it work well with the smallest size mobile screens without splitting it to two lines. Hope that's okay? 🙂

**Comment by SudharakaP** [comment]
@Betree : If you haven't already started, I'll be working on the historical view of this? Hope there's no objections. 😉

**Comment by SudharakaP** [comment]
> @Betree : If you haven't already started, I'll be working on the historical view of this? Hope there's no objections. wink

Just for the record; it was discussed that this will be looked at first by `Ben (@Betree)` as it involves some tricky revenue metric calculations.

**Comment by BenJam** [comment]
plan 

- [ ] close out this issue
