### ISSUE TITLE
Update Cryptographic Hash Algorithm from `SHA1` to `SHA3`

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4636]
This was initially pointed out at, https://opencollective.slack.com/archives/C0RMV6F8C/p1630767161048100. At several places in the API we use the [`SHA1` hash](https://en.wikipedia.org/wiki/SHA-1). It would be nice to update this to [`SHA3`](https://en.wikipedia.org/wiki/SHA-3) to conform with the latest standard. 😃

**Comment by SudharakaP** [comment]
If no objections I can look into this one. 😉

**Comment by znarf** [comment]
Using an hashing algorithm is not insecure if it's not used for security features or cryptography.

Creating a cache key with whatever version of an hashing algorithm is fine. We could be using md5 and it would be the same.

**Comment by m5kr1pka** [comment]
> Using an hashing algorithm is not insecure if it's not used for security features or cryptography.
> 
> Creating a cache key with whatever version of an hashing algorithm is fine. We could be using md5 and it would be the same.
> 
> It's a classic mistake.

Are you sure about MD5. The MD5 message-digest algorithm is a cryptographically broken but still widely used hash function producing a 128-bit hash value.

Somewhere I've read that bcrypt is good, but this is not my area of expertise.

**Comment by SudharakaP** [comment]
> Using an hashing algorithm is not insecure if it's not used for security features or cryptography.
> 
> Creating a cache key with whatever version of an hashing algorithm is fine. We could be using md5 and it would be the same.
> 
> It's a classic mistake.

Makes sense; thanks for the explanation. It's seems to be used only for caching and one other instance we use it for creating the `sender_batch_id` for paypal; https://github.com/opencollective/opencollective-api/blob/0438cc597790f802c75a9f2702b10084d5aad0ee/server/paymentProviders/paypal/payouts.ts#L53. Hence I am closing this issue.

**Comment by m5kr1pka** [comment]
In transferwise case you use bank account details as a cache key. Cache keys tend to leak to front.

```const hashObject = obj => crypto.createHash('sha1').update(JSON.stringify(obj)).digest('hex').slice(0, 7);```

https://github.com/opencollective/opencollective-api/blob/0438cc597790f802c75a9f2702b10084d5aad0ee/server/paymentProviders/transferwise/index.ts#L180

> > Using an hashing algorithm is not insecure if it's not used for security features or cryptography.
> > Creating a cache key with whatever version of an hashing algorithm is fine. We could be using md5 and it would be the same.

**Comment by Betree** [comment]
I too don't see any security issue with this either:
- For PayPal, the hash is there to prove the uniqueness of the batch. There are no user data injected (we're only using IDs) so creating a collision is extremely unlikely, if not impossible. And in case there would be a collision, it would just make the payment for this batch fail.
- For Transferwise, we're caching the required cache keys for the form validation on our side. The only impact of a collision would be to have you rejected later in the process of submitting an expense because Transferwise verifies all the info at payment time anyway.

Just a note for the future: it's better to report security issues (even if they're just suspicions) privately. See https://github.com/opencollective/opencollective/blob/master/SECURITY.md
