### ISSUE TITLE
Add newsletter opt-in to guest contribution flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4671]
If someone contributes as a guest it may be the only contact we have with them. We should give them the option to subscribe to the newsletter if they want, so we can potentially entice them to get more involved. I think there should be a tickbox on this screen.

![Screen Shot 2021-09-13 at 10 12 37 AM](https://user-images.githubusercontent.com/5498878/133004457-2e0994ce-e053-47bf-a51f-d5aeed591352.png)

Just like there is on the account creation screen:
![Screen Shot 2021-09-13 at 10 14 26 AM](https://user-images.githubusercontent.com/5498878/133004477-dcaf1146-bb50-470d-89ee-5814b37b1323.png)

**Comment by Betree** [comment]
The solution picked by design and that we've implemented was to show it on the success screen:
![image](https://user-images.githubusercontent.com/1556356/133586874-818e27f3-fe4b-4b5c-99a9-d068bed397bf.png)

I personally like this solution because:
- People may not have the context about what Open Collective is when contributing
- Anything we can do to simplify the contribution process will increase the completion rate
- I find the call to action on the success page very clear, and I like this pattern of having some "Want to go further?" actions **after** the contribution.

Ping @opencollective/design

**Comment by alanna** [comment]
Ah ok that solution makes sense, I didn't know.
