### ISSUE TITLE
Whitelist for redirects

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4695]
If we link from the platform to the OCF docs, the user sees this warning:
<img width="476" alt="Screen Shot 2021-09-17 at 2 09 03 PM" src="https://user-images.githubusercontent.com/5498878/133712912-c455ff8c-6e69-499c-b7f3-5c2076bcc17a.png">

It would be great if we could have a whitelist for domains that skip this redirect, such as opencollective.foundation and oscollective.org and their subdomains.

**Comment by znarf** [comment]
@Betree I thought we already had this notion of trusted domains. Am I wrong or what is different here?

**Comment by Betree** [comment]
> @Betree I thought we already had this notion of trusted domains. Am I wrong or what is different here?

We indeed have this notion already.

- In https://github.com/opencollective/opencollective-api/pull/6603, I'm adding the two domains to the trusted list to make sure they will be linked directly in the future when sanitizing (rather than being sanitized as `/redirect?url=...`).
- In https://github.com/opencollective/opencollective-frontend/pull/6886, I'm tweaking the behavior of the `external-redirect` page to make sure we don't show any warning for already sanitized links pointing to domains that are now trusted (e.g. `https://opencollective.com/redirect?url=https://opencollective.foundation`)
