### ISSUE TITLE
Do not call it "host fee share"

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4702]
We should simplify our terminology and just call it "platform fee". This has caused confusion in multiple situations. I just found an accounting mess because they (understandably) assumed 'host fee share' meant a fee *paid to the host*. Our pricing model is already complex, with three different kinds of fees (host, platform, payment processor), plus platform tips. We should simplify the language wherever we can.

**Comment by znarf** [comment]
This was effectively brought multiple times by you and this was discussed within the team.

Consensus is that "Host Fee Share" might not be a great name but naming it "Platform Fee" would have been even more confusing because "Platform Fee" was something different in the past.

It would be bit difficult to justify having "Platform Fees" again when we said that we were dropping it in the past. At least we should be really careful with it.

> Zero Platform Fees for Charitable Collectives
https://blog.opencollective.com/open-collective-platform-is-moving-on-to-0-fees-for-charitable-collectives/

> Zero platform fees!
https://blog.opencollective.com/what-a-year/

> we expanded our 0% platform fees offer
https://blog.opencollective.com/open-collective-investors-update-august-2020/

**Comment by alanna** [comment]
I don't think it's the right call to be held by the past like this. things
change. We have to move on. Will we have to consider what we called things
years ago forever?

We were always clear that it was no platform fees *for collectives*. The
platform fee is now something charged to the host. But that doesn't change
the essence of what it means.

If not platform fee, then what do we call it that's simple and clear? Host
fee share is not working. Shared revenue is way too broad and misleading.

**Comment by abitrolly** [comment]
I'm trying to understand various fees. Can we draw a diagram?

Which one is closer to reality.
```
[giver] --    1    --> [collective] --    2    --> [host] --    3    --> [platform]
```
^ Giver pays transfer fee 1 (is there any?) and the full sum goes to collective, then collective pays service fee 2 to host, and then host pays 3 to the platform? 

```
[giver] --|--    2    --> [host] --    3    --> [platform]
          |-------------> [collective]
```
^ Giver pays no transfer fees, directly donates to collective, but pays service fee 2 to host, host pays 3 to platform.

**Comment by alanna** [comment]
Closing in favor of #4929
