### ISSUE TITLE
Users not finding contact under actions menu

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4760]
## Who is your user?
Someone trying to reach a Collective, like a financial contributor or expense submitter

## What are they trying to achieve?
Find the contact button

## How are they currently doing this?
Contacting main OC support, because that's the visible contact option, who then has to direct them to the Collective, delaying an answer and using up support resources

**Comment by SudharakaP** [comment]
@alanna : I am not exactly understanding the problem here. We currently have a contact button under actions menu.

![image](https://user-images.githubusercontent.com/12435965/135723672-eb53c5ae-e2d8-49d6-8c68-4a8e89d91c20.png)

Do you mean that users have trouble finding it? One thing I can suggest is adding the contact link (with a nice icon) near the social icons on the collective page. 

![image](https://user-images.githubusercontent.com/12435965/135723711-37fb8d22-79ab-4e12-a6fe-f5da225335a9.png)

Here after the website link we could add a mail button linking to the contact form which makes it obvious that it's a contact form. 

@Betree : Let me know if you agree with this one; I can implement. 😄

**Comment by BenJam** [comment]
Status: 💚

@aminakazi's done the design, just need to be implemented. Should be able to put this in the current sprint.

**Comment by aminakazi** [comment]
You can find the [final designs here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15064%3A202816).

We've added an email icon in the header and a standalone button in the about section to help the user find the contact options better. The contact form has also been redesigned as a pop-up instead of the way it is working right now.

**Comment by SudharakaP** [comment]
If there's no objections, I can take this one after we are done with the host reports and the [refunds balance issue](https://github.com/opencollective/opencollective/issues/4369). 😄

**Comment by ninavizz** [comment]
I commented in the Figma, but will also comment here: "Actions" is not an intuitive call to action to any user. "Contact" is also such a basic call to action, it should be elevated from the menu imho. The planet icon is cute, and after thinking about it for a while I get it—but icons are supposed to be immediately intuitive, and not require users to think. I still don't know what that specifically means, or if it is a CTA for existing or future contributors to a project.

All that said, the watercolor backgrounds in Figma are off the hook beautiful, and I love!

<img width="456" alt="Screen Shot 2021-11-25 at 1 22 40 PM" src="https://user-images.githubusercontent.com/8262612/143500991-c85cddef-4448-498b-b560-7fd63bf0401d.png">


From Figma:
> The word "Actions" is not an intuitive or cognitively-resonant CTA to draw users in. Additionally, you are speaking to different user types in this menu—which is an anti-pattern. And, "Submit Expense" is redundant with the button to the left of "Actions." 
> 
> I would recommend two different menus—one "For Contributors" and another "For Admins," and have the latter only visible to administrators. 
> It is just not clear who can add funds, manage a collective, or what "Contribute" means. "Contact" is the only obvious CTA there, and needs to be elevated from the menu.

**Comment by aminakazi** [comment]
Production Ready file is [linked here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15064%3A202816)

**Comment by BenJam** [comment]
Plan for this week:

- [ ] check against initial problem/get feedback from with @alanna and @alinamanko

**Comment by ninavizz** [comment]
Why is this being closed if nothing was solved, and no user testing appears to have been done to learn about the problem or efficacy of a solution?

The problem is unlikely to be not users not noticing it within the Actions menu, but users not thinking to check a menu labeled "Actions," as that is a highly un-discoverable location for a "Contact" item. Attempting to solve the problem with just an icon (especially one that is so light and thin) is also not adding a very discoverable visual feature to a page. Icons alone are an accessibility anti-pattern, and anybody with vision issues will also struggle with the faint outlines and lack of contrast with the icons you're using. 

The page is covered with tons of Open Collective specific nomenclature and concepts, but little that is relatable to people not embedded in Open Collective mental models. That's a really crappy experience, and alienates more than it engages.

Also, it's unclear what the proposed solution is, after being linked to a Figma file with many screens. 

Guys, people depend upon this product to get paid and to fundraise. It's not cool to _burden_ users with your own ideals of utopian concepts that negligibly translate, in a utility people depend upon for practical needs. You can imbibe values into your products, without burdening people with them as hindrances to basic usability via relatable mental models. For a global product, no less.

**Comment by alanna** [comment]
It's being closed because a new design surfacing the contact action in
multiple other more visible places on the page has been implemented. It may
take a little more time to get into production, but we close issues when
the related pull request is completed.

**Comment by SudharakaP** [comment]
> It's being closed because a new design surfacing the contact action in multiple other more visible places on the page has been implemented. It may take a little more time to get into production, but we close issues when the related pull request is completed.

Just to note this is in production now. 😄 👍🏽

**Comment by ninavizz** [comment]
@SudharakaP Right—but how do you know the problem has been solved for, if there was no user testing—or if there was user testing, why were findings not posted with the issue? I just looked in production, and did see a great and clearly visible "Contact" button, but it also looks nothing like the much less visible solutions offered in the Figma wireframes, above. 

All of this is to say, that you guys do a pretty horrible job with surfacing _good_ UX practices. Which is a huge bummer, considering your visibility in open source—and how awful UX practices are understood (and practiced), in open source. 

Please do user testing. Please communicate findings from user testing. You guys have the resources. Many projects do not. Arguably, most do not. We need better lead-by-example setters in our space. Thanks.

**Comment by Memo-Es** [comment]
@ninavizz Thank you for your concern. You are correct that we should do more user testing. And right now, it's being appropriately addressed. 
I don't get your contributions to our issues, though. If you want to get closer and collaborate with any team, you should approach with a little more finesse and not with incendiary comments no one will react to. It's easy for all of us to just go to PayPal, or Wise, or whatever and start a flamewar about what we think is not right or what we believe best practices are. 
The truth is, thousands of real people use the platform, and we keep an open eye and ear to hear what actual users are requesting. The bottom line here is that especially in open-source, I recommend you start adopting nicer ways to collaborate with people you don't know :)
BTW my invitation for you to get properly in touch and set some collaboration is still open, let me know if that interests you

**Comment by ninavizz** [comment]
@Memo-Es Why would I want to get in touch with you to offer my work for free—or, why would you assume I'm here desiring collaboration? I'm not. I'm stuck using your product because a team I work with uses it to solicit contributions, and then uses those contributions to pay contractors overseas. It meets the need of working across borders in paying international contributors, very well. I never wanted to get in touch with you properly "collaborate." I volunteered the option for you to get in touch with me, if you have questions—and I did what good open source contributors do, which is file issues if things are broken. I stopped short of volunteering to fix those, however, because I don't have that bandwidth. 

If you detect hostility in my comments, it's because you're assuming an awful lot—your entire team is, and has been. 

Following what "actual users are requesting" and then never testing those things, is not how you make usable products. That is not up for debate. In open source, user-centric product development is not well understood, and that is only because very few projects are acclimated to working with UX. 

User testing, in combination with listening to _all_ of your users (not just the project leads), is how you create a usable product. Things like privacy/visibility things, need user testing to get done right. Yes, I am pissed that you've created a payments platform that is approached as some utopian community sharing somethingerother—and not as a platform where users have their PII, post invoices, etc. That mandates a lot more respect for clearer communication about privacy, than has been invested in the product. OC takes the utopian/post-capitalism brand-spirit part of your product very seriously, and user privacy is treated like a joke. Businesses are not "collectives," they're businesses. Workers pay our bills from money we earn. I'm an anarchist, and all for collaborative stuff—but that's not what your platform facilitates, as a practical matter. 

Anyhow, I'm not here to "collaborate." You can begin, by not assuming that. :)
