### ISSUE TITLE
Automatically update guest slugs when they confirm their accounts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4876]
This profile: https://opencollective.com/guest-5d9e6786

Is admin of this Host: https://opencollective.com/solidarity-with-student-workers-of-columbia

Guest accounts should not be able to be admins.

**Comment by Betree** [comment]
@znarf is right. Technically, this user is not a guest. It just happened that they kept the slug as-is when they verified the account.

The main reason why we stopped updating the `slug` automatically in https://github.com/opencollective/opencollective-api/pull/6468 is that the thank you emails would link to `/guest-xxxxx/recurring-contributions` so the URL sent by email ended up as 404 errors.

Now, in the spirit of #4931 and since there's already a redirect on https://opencollective.com/recurring-contributions, I think we should revisit this with the following steps:
1. [ ] Update all thank you emails to link to https://opencollective.com/recurring-contributions
2. [ ] Tackle #4931 
3. [ ] On https://opencollective.com/:slug/recurring-contributions, if the profile is not found, redirect to https://opencollective.com/recurring-contributions
4. [ ] Rollback https://github.com/opencollective/opencollective-api/pull/6468 to automatically update the slug of guests when they confirm their accounts
