### ISSUE TITLE
invoice PDF link in Thank you Email is a 404

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#488]
Made a donation to the new open source collective to test stripe. 
received the thank you email, clicked on the link to download the expense. Link is a [404](https://opencollective.com/newopensourcecollective/transactions/e8f6ebf8-9cfb-415f-8056-78401e49386b/invoice.pdf)

**Comment by xdamman** [comment]
That's only happening for that new collective. And it's because there is no User that is attached to the host collective id 8944 referenced in that Transaction (via `User.CollectiveId`). It looks like there is something inconsistent in the database. The User I could find is UserId 8146 but it is linked to the CollectiveId 8945.

As a side note, let's consider how widespread an issue is before assigning it the tag high priority.

**Comment by piamancini** [comment]
Given that invoices were already showing wrong amount it made sense to bundle them together.

**Comment by xdamman** [comment]
Best way to test if an issue is widespread is to try with another collective if possible on another host (especially in the case of an issue for a new host).

Anyway, can we close this issue? Solution is to fix the database records per my comment above, nothing in the code for me to do here.
