### ISSUE TITLE
Tag list underlapping box element on expense list

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4887]
![Screen Shot 2021-11-01 at 2 14 54 PM](https://user-images.githubusercontent.com/5498878/139608741-abeeaf73-390c-438c-b540-f7420310763b.png)

You can't scroll down to select a tag because it's hidden under the container box.

To reproduce, click "add tags" on an expense at the end of an expenses list, on a Collective with a long list of tags (e.g. OCF's host budget).

**Comment by Betree** [comment]
We'll probably need to use a react portal to solve this issue

**Comment by tewarig** [comment]
is this issue still needed to fix? can I work on this @znarf @Betree

**Comment by woolnerd** [comment]
@Betree @znarf Hello, if this issue is still available, I would like to tackle it. I've been looking at a solution locally using createPortal (as suggested) which seems promising. Thanks!

**Comment by Betree** [comment]
Hi @woolnerd, this seems like the right approach. An alternative would be to rewrite this by building upon a [shadcn component](https://ui.shadcn.com/docs/components/command), as we're now using Tailwind CSS, but that's more work and a greater risk of side effects.

Either way, we'd be happy to review your PR when you'll have something to share :slightly_smiling_face:

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/9604 (not deployed yet)

**Comment by woolnerd** [comment]
@Betree Thank you for your help
and feedback on this issue! It was my first OS contribution and I look for forward to many future ones! Before moving on, I just wanted to check if this issue qualified for a bounty? Thanks again!

**Comment by Betree** [comment]
@woolnerd Thank you!

We've added you to https://github.com/orgs/opencollective/teams/contributors/members. You can now push directly to most Open Collective repos (only the `main` branches are protected).

The `bounty candidate` tag indicates that we're considering the issue for bounties, but a review is still required. If you're interested in working on an issue with this tag, feel free to comment on it, and we'll clarify whether we're ready to put one on it. Otherwise, you must look for the `bounty` tag (see https://docs.opencollective.com/help/contributing/development/bounties).

While reviewing the label description for `bounty tag`, I realized it was a bit ambiguous, I edited it and we'll exceptionally add a bounty for this issue (see the comments below).

**Comment by Betree** [comment]
:trophy: This issue has been completed by @woolnerd  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
