### ISSUE TITLE
Contribution flow: new tip picker

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4897]
Part of #4299
Design: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13575%3A211640

We should create a dedicated `ContributionTipPicker` component (feel free to find a better name) and add a corresponding example in our styleguide.

![image](https://user-images.githubusercontent.com/1556356/139851887-8ba4115e-d6f5-4b0b-91e1-284970f10f06.png)

**Comment by Betree** [comment]
Ping @opencollective/core, as I'm not sure whether everyone had the time to look at this.

I'm personally not a fan of having one input above and another one below, I feel like it creates unnecessary complexity.

Also, @Memo-Es, is there a modal or something when you check `I don't want to contribute to Open Collective`? We should carefully check the impact of such change on our metrics.

**Comment by Memo-Es** [comment]
@Betree Agreed with the vertical placement, I went ahead and fixed it:
<img width="1065" alt="Screen Shot on 2021-11-02 at 15-21-34" src="https://user-images.githubusercontent.com/49539954/139953826-41da7ac8-04d5-449c-aff3-e671a825a52f.png">

About the `I don't want to contribute to Open Collective` checkbox, we could even remove it, and let the user type 0 with the fields, adding also a small confirmation modal if we want to add an extra blocker

**Comment by Betree** [comment]
@Memo-Es I like this new version! I also agree with the modal when the person sets `0`. Such a modal is a great opportunity to explain what we do and why tips are important to us.

@opencollective/core any opinions on this? These are small changes, but they can have a significant impact.

**Comment by kewitz** [comment]
@Betree I agree that having one input above and another one below is a bit confusing, not sure if having both below is actually better since in both cases it seems that you're setting limits of an interval with different units.

I don't see an easy way to solve this so I would just pick one and ping users for feedback.

Related to `I don't want to contribute to Open Collective` checkbox, I think a message box appearing after checking the box could be less intrusive. Adding an illustration to this message box could attract enough attention from the user.

**Comment by SudharakaP** [comment]
Some small feedback here; I would vote for a slider which can be dragged to any given place (such as the ones in [this page](https://www.w3schools.com/howto/howto_js_rangeslider.asp)) instead of the slider with predefined placeholders. The reason being there is inaccuracy in the slider selection with the percentage value. So for example if the user wants to give a 30% tip for a value of 10 dollars they contributed, then if the slider is divided into 7 parts as shown in the above design the slider ideally should be between the second dot and the third dot I think since `2/7 < 30% < 3/7`. This creates a certain usability problem with the slider and I feel users might not really use it if the breakdown of values doesn't make much sense (like the one seventh example). 

Rather if the slider was continuous and could be dragged to any given position (the values are incremented by 1%) then the user has much more flexibility when using the slider. So they can choose 35% for example easily. Just my two cents. 🙂

**Comment by kaylarep** [comment]
Just to check, can people manually type in their own number?

I know people can get very frustrated when tips are pre-set for them.
