### ISSUE TITLE
Consolidated Recurring Contributions management

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4931]
As a user, I would like to manage all my recurring contributions from a single page:
- [x] User contributions
- [x] Incognito contributions
- [ ] Organization and Collective contributions

Today, it can be difficult to find where to manage recurring contributions from and that would be a really welcome change for users to have this consolidated view available.

**Comment by Betree** [comment]
I strongly agree with this one. Since https://github.com/opencollective/opencollective-frontend/pull/6174, incognito contributions are already grouped on the main "Recurring contributions" page. It would be great to have a canonical https://opencollective.com/recurring-contributions that includes all the profiles you're managing.

**Comment by Betree** [comment]
This would be really useful to solve https://github.com/opencollective/opencollective/issues/4876

**Comment by Betree** [comment]
Small [POC](https://github.com/opencollective/opencollective-frontend/pull/7432) about how this could look like. With https://github.com/opencollective/opencollective-frontend/pull/7416 now implemented and deployed, building this consolidated page would be really simple.

https://user-images.githubusercontent.com/1556356/152354888-d4e2bdab-26b6-4ca5-a92b-233acd0994ba.mp4
