### ISSUE TITLE
Select: hide "Nothing found" if no search term

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4934]
Expected behavior:
- hide the tooltip
- or show a better message

![image](https://user-images.githubusercontent.com/1556356/141085253-8c35f1c6-92d0-4633-993e-922b348a0a42.png)

**Comment by SudharakaP** [comment]
Just as a note, the the only place I could find where the StyledSelect is used in this way is the `CollectivePicker` where we don't have any default options and only shows the options when the user type at least one character. So I think this only applies for the `CollectivePicker`. My solution to this is based on this assumption. Let me know otherwise. 🤔 🙂
