### ISSUE TITLE
[Feedback] Crypto contributions

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4935]
Feedback issue for crypto contributions:

Release https://opencollective.com/opencollective/updates/support-open-source-software-using-crypto
Documentation https://docs.opencollective.com/help/financial-contributors/crptocurrencies

**Comment by BenJam** [comment]
from @piamancini 

> I was just demoing the flow, but never hit the finish button. However this [thank you] email was still sent. 

looking into this, the email is sent at the point a QR is generated because we also want the QR to be sent to the contributor. The QR screen does not say that this email will be sent nor does it take you to the thank you screen. 

| QR Code Screen | Thank You Screen |
| --- | --- |
| ![Screenshot 2021-11-10 at 12 41 43](https://user-images.githubusercontent.com/158833/141115558-60bdb7c2-0c61-4247-b607-35c9b1f05ad3.png) |  ![Screenshot 2021-11-10 at 12 42 02](https://user-images.githubusercontent.com/158833/141115584-1da4e89c-44db-43f4-946b-392b3cc22a2c.png) |

**Comment by SudharakaP** [comment]
> from @piamancini
> 
> > I was just demoing the flow, but never hit the finish button. However this [thank you] email was still sent.
> 
> looking into this, the email is sent at the point a QR is generated because we also want the QR to be sent to the contributor. The QR screen does not say that this email will be sent nor does it take you to the thank you screen.

One simple solution I could suggest here is to add the `Your contribution is pending` message to the QR code screen as well. This way users know that even at the QR code screen we assume the user has made the contribution. In fact there's no functional difference between the QR code screen and the success screen; when the user hits the QR code screen the order is created and the contribution is assumed to have been done. 

As an alternative we could also not have a dedicated success page for the Crypto flow and view the success message within the QR code screen. This would need some design I think but will be better since actually the contribution is assumed a success when the user hits the QR code page. 🤔 

cc: @opencollective/design @BenJam @znarf

**Comment by Memo-Es** [comment]
I'm proposing a quick solution while we push the contribution flow update:


<img width="1076" alt="Screen Shot on 2021-11-16 at 18-33-17" src="https://user-images.githubusercontent.com/49539954/142088050-d0350fd5-a882-4320-ae6d-b98b42828b4b.png">

I'm getting rid of the success screen and including a couple of details in this one.

Let me know what you think @SudharakaP @BenJam

**Comment by SudharakaP** [comment]
Thanks @Memo-Es. Let me open a new issue for this so that we can iterate. Could you please share the Figma file with me? 😃

**Comment by Memo-Es** [comment]
@SudharakaP https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15015%3A205718

**Comment by SudharakaP** [comment]
> @SudharakaP https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15015%3A205718

Thanks. 🤗

**Comment by BenJam** [comment]
> Let me know what you think @BenJam

my apologies that I didn't respond to this in time but, having looked at the implementation in https://github.com/opencollective/opencollective/issues/4965 I wonder whether there's an alternate that:

- doesn't miss the opportunity for folks to include a message with their contribution, or share their contribution with their social network
- provides an additional prompt to ensure that the transfer is completed

something like:

![Payment Info](https://user-images.githubusercontent.com/158833/143424228-cbf67b76-b498-40a1-b78e-7ee19559cff1.png)

which conceptually gates the thank you but still provides a route to it. I defer to @Memo-Es on whether our design standards say we should not speak directly to the user like this.

**Comment by Memo-Es** [comment]
I like your suggestions @BenJam, @SudharakaP I modified the file accordingly
https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13104%3A204710

**Comment by Memo-Es** [comment]
@BenJam just making sure we have your eyes on the last solution before @SudharakaP wrapt it up

**Comment by SudharakaP** [comment]
> @BenJam just making sure we have your eyes on the last solution before @SudharakaP wrapt it up

Just fyi, I've made changes as per the new design and the new screen-cast is at, https://github.com/opencollective/opencollective-frontend/pull/7158#issue-1059791871

**Comment by shannondwray** [comment]
Thoughts on enabling this feature Open Collective wide?

**Comment by rudyfraser** [comment]
Hello,

Reaching out per my brief convo with Shannon [in the Slack.](https://opencollective.slack.com/archives/CJ2ERRZQ8/p1672960734642949). I came across a proposal recently for a fiscal host on Open Collective who was interested in using OC to act as a fiscal host for crypto currencies ([link](https://docs.google.com/document/d/1_omNeKxa8xiJbj3hDvb42izN5mAIouueiTTLUYvWiw8/edit)).

It's my understanding that OC's existing crypto contribution flow is supported by The Giving Block and converts crypto contributions to fiat, per [this documentation](https://docs.opencollective.com/help/financial-contributors/crypto).

For my purposes and to meet the general requirements of a "Celo Fiscal Host", I would not want the crypto to be converted to USD. How I imagined using OC with crypto would be:
- Having a completely self-managed way of contributing crypto to a wallet (since the very nature of wallets supports their own payment rails)
- Having a way to update the available funds in a crypto-native fiscal host (which seems to be supported by the [addFunds](https://graphql-docs-v2.opencollective.com/mutations/addFunds) mutation)
- Be able to view a balance and transactions in the [supported cryptocurrency](https://graphql-docs-v2.opencollective.com/types/Currency) (i.e. instead of USD, it would display cUSD)
- Being able to submit requests (reimbursement, invoices, etc.) and select the cryptocurrency as an option for payout. The only available option for payout in crypto would be "Other" and we would ask for wallet details, etc.

Papertree has [hacked together an MVP of this on our own](http://dao.papertree.earth/) but it would be great to have all of this supported by Open Collective, using similar APIs and UIs, etc.

**Comment by mariaa144** [comment]
Allowing for Bitcoin Lightning would be great! As fees get higher on bitcoin, the Lightning network allows for smaller and more frequent donations. Also there is no waiting for confirmations.

**Comment by mariaa144** [comment]
Donating with bitcoin is important to me because I often have trouble with my cards going through such as using privacy.com to pay a collective which is paid in Euros.

**Comment by shannondwray** [comment]
Should we close this since it's been removed? @BenJam
