### ISSUE TITLE
Done

### ISSUE THREAD

**Issue by zahirpatel110** [opencollective/opencollective#4948]
Done 

_Originally posted by @zahirpatel110 in https://github.com/Raphael-MOUQUIN/opensource.guide/pull/2#issuecomment-968175277_

**Comment by zahirpatel110** [comment]
> Done 
> 
> _Originally posted by @zahirpatel110 in https://github.com/Raphael-MOUQUIN/opensource.guide/pull/2#issuecomment-968175277_

**Comment by zahirpatel110** [comment]
> Done 
> 
> _Originally posted by @zahirpatel110 in https://github.com/Raphael-MOUQUIN/opensource.guide/pull/2#issuecomment-968175277_

Readme.MD

**Comment by SudharakaP** [comment]
This ticket is closed due to **guidelines not followed**. 

All tickets should follow the guidelines as mentioned in: 

- The [Code of Conduct](https://github.com/opencollective/opencollective/blob/main/CODE_OF_CONDUCT.md).

- Submission guidelines as mentioned in our [README file](https://github.com/opencollective/opencollective/blob/main/README.md#issues).
