### ISSUE TITLE
Fixing Host and its ensuing issues

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#497]
We have three types of collectives:
1. User
2. Org
3. Collective

For each, all member relationships should be in the `Member` table. Currently, neither `USER` nor `ORG` members are listed in that table. For `USER` we are shortcutting in `Users` and `Collectives` table. Same shortcut doesn't work for `Org` like Airbnb. It's currently linked to a User account when it should be completely independent of that User and only a relationship to that User should be listed in `Members` table. *TODO: add all relationships to Members table*

For each type of collective, we define a `ADMIN` that can operate the money behind the collective.

1. In a `USER` collective, the user who created it is the only one who is an `ADMIN`. And this relationship is based on PaymentMethod.

2. In a `ORG` collective, lots of users can be admins. They become an `ADMIN` by either adding a PaymentMethod or someone's who is an `ADMIN` adds them and gives them access to that PaymentMethod.

3. In a `COLLECTIVE` collective, `ADMIN` can approve and pay expenses. Same as above. But, there is one special relationship here called `HOST`. This is also dependent on PaymentMethods. For purpose of this let us define a new type of PaymentMethod that we can issue called `HostPM`.

Ex: 
- When a user signs up their collective, they are listed as `ADMIN`. In order to add funds, we upgrade them to `HOST` - meaning add a `HostPM` to their name and they can now add funds using that PM. If they want to receive a donation, they need to add another paymentMethod - a stripeAccount. If they want to pay expenses, they need to add another PM - paypal.

- WWCode example.
Host: admin@wwcode.com (User) and a corresponding Collective
HQ collective: wwcode
Austin collective: wwcode-austin

Host gives $300 to austin. 
- Order: $300 from HostCollective to AustinCollective using HostPM
- Txn: double entry based on the Order

So, a Host is just a User with a special PaymentMethod. 

If this makes sense, then we need to make following changes:
- add all members for any type of collective to the `Members` table and remove the shortcuts in User and Collective tables for consistency (you could leave them, personally I think they are going to get out of sync and cause trouble for us later)
- Create a new type of PaymentMethod for Hosts
- Find all Hosts and create that PM for each of them
- Fix order and transaction table to make sure it's consistent.

**Comment by xdamman** [comment]
Thanks for this first shot at addressing this issue. This is a quick first reaction to address some misunderstanding and add other perspectives. 

The first paragraph is incorrect. Currently the Members table already defines all relationships between users, orgs and collectives. It’s just that we are abstracting the concept of user and org under the term MemberCollectiveId (because every user has a collective attached to them 1:1 and every org is a collective). This also enables us to have a collective as a backer of another collective in the near future. 

When we create an org we already automatically add the creator’s user collective as the first admin of that collective type organization (remember all relationships in Members are between collectives).

Doing the same for collectives of type user doesn’t make much sense because you would basically have always the same circular relationship (MemberCollectiveId=1, CollectiveId=1, role=“admin”). Not sure we want that even though I see your point about consistency. Seems overkill to me.

I think a host should be an organization -not a user- with a special payment method to add funds and a stripe account (in ConnectedAccounts). First because in most cases a host will effectively be an organization and not an individual (wwcode, BrusselsTogether, ...), second unlike a user that only has one admin, we want to be able to have multiple admins who could manage the host (pay expenses, add funds). Lastly, we don’t want people to create a login with a generic email (KYC). It’s worth noting that when you create a business account on Paypal on behalf of a legal entity, they will still ask you details about the individuals behind that entity for their KYC. 

We are already creating a dummy payment method for every new collective. Its goal is to allow collective to collective donations using the collective’s balance.

So likewise, we could create a dummy payment method for an organization collective. That makes sense to me.

Let me think this through once more and I’ll come back with another proposal/iteration.

**Comment by xdamman** [comment]
*Been thinking more about all this...*

First, a few things to consider:
- Only USER and ORGANIZATION collectives can have a negative balance because they are the ones bringing money into the system from the outside.
- Similarly, a regular collective (of type COLLECTIVE) can never have a negative balance.
- A Host is the owner of the bank account that holds the money on behalf of one or multiple collectives.
- Like in the real world, the owner of a bank account can be an indivial person or an organization.
- Like in the real world, an organization can have multiple administrators.
- A Host should also operate in full transparency (at least for their activity of Hosting other collectives, they can still have a "separate business" outside of their budget on open collective)
- We should be able to see how much each collective contributed to the budget of the Host
- Ideally, a Host should share their accounting expenses and other common expenses
- Because of all of that, it makes sense for the Host to be a collective and not create a separate collective (otherwise such separate collective wouldn't receive the commission from the hosted collectives)
- The budget of the Host should be based on the direct donations to the Host (eg. I want to support WWCode in general), plus all the Host fees (and we should extrapolate the fees from the monthly donations for the year)
- A separate view should show the aggregate budget of all the hosted collectives (arguably, this could be the primary yearly budget we show above the fold and the Host specific budget is the one at the bottom of the page alongside their ledger -- but I like the idea of having to clearly distinct budgets, one for the Host, one aggregate across all hosted collectives)
- People shouldn't have to logout/login between multiple accounts. They should have one account with multiple roles
- We should avoid requiring people to create an account with a generic email address.

With all of this, I think having the Host as a collective makes the most sense.
That leaves us with the problem of add funds.

Right now, when we add funds from the Host to a collective, we create 3 transactions which breaks the principle of a double entry accounting:
- We add e.g. $100 to the Host collective with no source (no `FromCollectiveId`)
- We remove $100 (DEBIT) from the HostCollective
- We add $100 (CREDIT) to the right CollectiveId

Normally, we should never add fund without a source. For example, for the Open Source Collective Host, when adding funds to Preact for their t-shirt sales, we should create a collective for Threadless as an organization and use them as the source:
- We remove $100 (DEBIT) from Threadless Collective (type ORGANIZATION)
- We add $100 (CREDIT) to the Preact Collective

In the ideal scenario, Threadless would directly give the money to Preact. And in that case, that's exactly what we would see in the Transactions table.
The only difference being that they would use a Stripe Credit Card as the `PaymentMethod`.

Which got me thinking (also taking into consideration your previous input above): We should actually create a payment method to represent the bank account of the Host.

A payment method can have a balance exactly like a PayPal PayKey.
And whenever we add funds, we use that `PaymentMethod`.

We could do that for AirBnB too.
We create a `PaymentMethod` linked to the Open Source Collective with a balance of $6k. And everytime we use it, we reduce its balance.
That also solves the problem of when we should take our commission. We only take it when that `PaymentMethod` is used.
This principle could also be used for Bloomberg Beta. They would prepay x `PaymentMethod` with a balance of $100.

Now, what happens when WWCode wants to allocate $1k to WWCode Austin and what if they don't want to create a collective for the source of the money?
Multiple options:
1- **If the Host has enough funds**: they can consider it as a donation coming from the Host, in which case it will show up as:
- DEBIT $1k from the WWCode Host Collective
- CREDIT $1k to WWCode Austin

2- **If the Host collective doesn't have enough balance**: they have to create another collective for their organization -- independent of the Host collective. There is no workaround and I don't think it's an issue. Technically, one alternative would be to create an "Anonymous Donor collective", but I'm not a fan for KYC reasons.

## Pure Host
Either the organization acting as a Host is a Host pure, meaning it has no other puporse than Hosting (e.g. OC Europe, BrusselsTogether, etc.) or either the Host can have other activites (e.g. wwcode and probably most other Hosts).
In the former, it's obvious that the Host shouldn't be able to get into a negative amount. All the money coming in should be accounted for in the budget of the Host collective.
In the latter, I think it's not a bad idea to have a distinction between WWCode the organization and WWCode the Host. It will make it clearer for WWCode how much it costs them to run the hosting activity.
That means that if they want to add funds without specifying an external source (and creating a collective for it like we did with BrusselsTogether where we created ORGANIZATION collectives for the [Lunt Foundation](https://opencollective.com/luntfoundation) and for [Beyond Carnivism](https://opencollective.com/beyondcarnism) to account for their wire transfers to the Host), then they will have to create a collective for WWCode organization and use them as the source for the add funds.

# Migration

- Create a WWCode organization (/wwcodeorg?)
- For each 3rd transaction in the Transaction table that represents add funds (all rows that don't have a `FromCollectiveId`):
  a. Create a `PaymentMethod` with a balance equivalent to the amount and attached to the new WWCode org
  b. Update the 2 other transactions to reference that `PaymentMethod`
  c. Update the `PaymentMethod`'s balance (set it to zero -- we could directly set it to zero at step (a); we could also argue that we don't even really need to create a `PaymentMethod` in this case at all)
  d. Remove the 3rd transaction row
  e. Add a double entry to the WWCode org:
    - DEBIT CollectiveId wwcodeorg
    - CREDIT CollectiveId to the destination of the add fund (e.g. wwcodeaustin)


*What do you think?*

**Comment by asood123** [comment]
The key definitely lies in setting up a paymentMethod to serve as bringing money inside. Feels like we are on the right track.

I think it's fine to have a Host as an org. Let me think about it more. 

> 2- If the Host collective doesn't have enough balance: they have to create another collective for their organization -- independent of the Host collective. There is no workaround and I don't think it's an issue. Technically, one alternative would be to create an "Anonymous Donor collective", but I'm not a fan for KYC reasons.

Isn't that the main issue? I don't follow how we can keep asking them to create additional collectives on add funds? What happens when they want to undo these changes? Will they have to log into those accounts independently? They are going to end up with dozens of collectives. Too confusing to explain. Maybe a way to solve this is add more money to the same bank account paymentMethod. 

I think in all cases, Host is different than the main collective. In order to tell Host fees vs the money the Host has for other collectives means that we should create two accounts for them - one account is what we credit with the Host fee (and maybe that's same as their profile page). Second account is what they are holding for other collectives. That would be a true double entry ledger.

Also, your comment above about orgs having members in the Members table doesn't line up with the data in the table. Look up Airbnb Org. It has a User account linked to it in the User Table. Then, has no entry in the Members table. Same for Digital Ocean - it's an org linked via Users table and has no members in the Members table. That setup is very confusing to me.

Let's chat live when you wake up

**Comment by xdamman** [comment]
Dealing with https://opencollective.com/laconexion I realized that a Host should actually always be a User or an Organization collective. Because a Host is the legal entity that receives the money on behalf of a (virtual) collective.

I think we can keep our previous conclusion, the only change is the WWCode HQ should be an Organization Collective and we should allow an Organization page to act as a collective if it's a host (or create a new collective type HOST?). 
If WWCode HQ wants to add funds to WWCode Austin, either:
- (ideally) they specify the source (and create an organization collective on their behalf in the process); or
- they create a general purpose Organization Collective (WWCode Fund) to be the source; or
- they simply get their HQ into a potential negative value. I don't think there is any way around it. And I think it's ok.

**Comment by asood123** [comment]
That's what I was thinking too - host always needs to be a user or org. Let's start with that and see if a new type `HOST` is needed.
