### ISSUE TITLE
Display embedded video in changelog update

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4983]
I announced the new embed video feature in a changelog update using an embedded video, but it's not displaying the video in the modal.

![Screen Shot 2021-11-24 at 10 36 11 AM](https://user-images.githubusercontent.com/5498878/143133050-ff5da4a2-ad41-46db-88af-1f3855863c23.png)

**Comment by SudharakaP** [comment]
@alanna : Can you please let me know the link to this video? 🤔

**Comment by SudharakaP** [comment]
Ops disregard my earlier comment, I misunderstood, I thought the video was not embedded. It seems the video does not show in the modal but was correctly attached. I'll look into this. 🤔

**Comment by SudharakaP** [comment]
@alanna : I tested this and I couldn't recreate this yet. I see the update like this, 

![image](https://user-images.githubusercontent.com/12435965/143137449-7c31c80c-26f4-44c8-ad80-ac55515d1a25.png)

As you can see it's the first part of the text you've entered and the video is not shown there since the modal is too small to show the entire content. 🤔

Can you confirm you still see what you have attached in the screenshot or you only saw that in the first try? 🤔

**Comment by alanna** [comment]
I added the text link afterward so it would be less confusing for users. At first it was like the first screenshot I posted, where it said "like this:" and then nothing showed about the video. The video is working fine in the update, just not in the modal.

**Comment by SudharakaP** [comment]
> I added the text link afterward so it would be less confusing for users. At first it was like the first screenshot I posted, where it said "like this:" and then nothing showed about the video. The video is working fine in the update, just not in the modal.

Ah, thanks for the clarification. Now it's clear to me what the problem is. For one video embedding in this modal is tricky as then we'll have to make the modal bigger. 🤔 

@Betree @opencollective/design : Currently we are only showing the summary of the update and in their we strip out the videos. We could potentially try to show the whole html in conjunction with our [blur effect](https://github.com/opencollective/opencollective/issues/4903#issue-1043073665). But I am a bit doubtful if that's a good solution as it's doesn't serve any purpose and unless people can view the video in the modal itself it's no use. 🤔 

Alternatively a simpler solution might be to replace the video in the modal with a link (such as `Click here to view the video`) which redirects the user to the video. WDYT? 🤔

**Comment by alanna** [comment]
If it's impossible to show the video in the modal in a playable format,
then the next best MVP might be just replacing it with the text link, as I
did manually. Just having nothing there isn't an option because it's
confusing.

**Comment by Betree** [comment]
> For one video embedding in this modal is tricky as then we'll have to make the modal bigger.

Not a blocker for me personally if it becomes a bit taller because of a video.

> We could potentially try to show the whole html in conjunction with our blur effect.

I think that's a good and simple solution. Except the "Show all" link should redirect to the update's page, not expand the content.

> But I am a bit doubtful if that's a good solution as it's doesn't serve any purpose and unless people can view the video in the modal itself it's no use.

If we set a limit tall enough, people will be able to see the video.

**Comment by SudharakaP** [comment]
I've done a [sample solution here](https://github.com/opencollective/opencollective-frontend/pull/7185#issue-1063231467) with the blur effect. Now note that the `Read more` link has been removed because we have the expand/collapse link to show the full changelog text if needed in the modal itself. I don't know if this is the optimal solution since we will have a scroll bar on the modal in this method. But let me know what you think. 🤔
