### ISSUE TITLE
Expense line item description cut off

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4986]
This doesn't look right.

![Screen Shot 2021-11-24 at 3 15 27 PM](https://user-images.githubusercontent.com/5498878/143159363-ee22bf3f-856e-4716-94b3-0b457539ccde.png)

https://opencollective.com/parentpreneur-foundation/expenses/43306

**Comment by SudharakaP** [comment]
@alanna : We recently implemented this behavior of blurring the content if it spans several lines. So here the content spans for three lines and therefore it's blurred at the second line and the third line is hidden. Do you mean that the line shouldn't be truncated because it's a link? I am not sure if it's a good idea to prevent truncations based on content. But I am open to suggestions. 🤔 

cc: @Betree

**Comment by alanna** [comment]
This isn't showing three lines though? The description is being cut off after less than one line. Like the first line is half faded out.

I disagree with this design decision, if this is working as intended. An expense is an official financial document. All the details are important. I don't see much benefit to cutting content off like this.

When you click 'read full description' it shows that the content takes up close to the same amount of space when hidden as the 'read full description' link itself takes up, so what's the point? If we are going to truncate content let's only do it when it makes a big difference to space savings.

![readmore](https://user-images.githubusercontent.com/5498878/143165811-f8a608c5-520a-40c5-af28-0b31307023ba.gif)

**Comment by SudharakaP** [comment]
> This isn't showing three lines though? The description is being cut off after less than one line. Like the first line is half faded out.
> 
> I disagree with this design decision, if this is working as intended. An expense is an official financial document. All the details are important. I don't see much benefit to cutting content off like this.
> 
> When you click 'read full description' it shows that the content takes up close to the same amount of space when hidden as the 'read full description' link itself takes up, so what's the point? If we are going to truncate content let's only do it when it makes a big difference to space savings.
> 
> ![readmore](https://user-images.githubusercontent.com/5498878/143165811-f8a608c5-520a-40c5-af28-0b31307023ba.gif)

I counted from the `Black DadPrepreneurs...` line which is why I said 3 lines. 😉 

Yes, your point makes sense. What do you think an appropriate amount to cut off? I think the adjustment here is simple but we need to decide exactly how many lines should show without blurring/cutting off. 🤔

**Comment by SudharakaP** [comment]
My thinking is that to increase the cutoff to four lines. So meaning, if it's 3 lines,

![image](https://user-images.githubusercontent.com/12435965/143172745-dbe8658a-2294-4a49-9e35-dd18324d80e0.png)

and if it's 4 lines,

![image](https://user-images.githubusercontent.com/12435965/143172692-8d752f08-6f79-43ef-9bea-0fb60d99c72e.png)

**Comment by Betree** [comment]
> An expense is an official financial document. All the details are important.
I don't agree with that. The PDF receipt that you download is an official financial document, but the page itself is not. Otherwise, we shouldn't have used tooltips cause they can't be printed.

> I don't see much benefit to cutting content off like this.
The main benefit was for grants because they can have rich text with a lot of content and showing everything by default makes things more complex when you want to scroll down to the actions or to the comments thread.

We can indeed play around with the default size limit, even set it to 20 lines if we want to be on the safe side, and truncate only when it's really necessary. As @SudharakaP said, it's up to personal preferences at this point. Engineering will let @opencollective/design take ownership on this one.

**Comment by alanna** [comment]
OK I think the solution of increasing it to a few more lines is good. If
there's a really long text there it makes sense. But this is catching more
usual line items that are only two lines of text, so it's too short. We
should make it not cut off most cases which are below 2-3 lines of text. So
I like Sud's proposal above, except maybe increase to 5 lines.

**Comment by znarf** [comment]
Let's move to 5 lines and close the issue.
