### ISSUE TITLE
rss/atom feed for changelog

### ISSUE THREAD

**Issue by mkurz** [opencollective/opencollective#5003]
It would be nice if you could add a rss/atom feed to https://changelog.opencollective.com/

(I could not open this issue at https://github.com/opencollective/opencollective-changelog)

Thanks!

**Comment by Betree** [comment]
Hi @mkurz, https://changelog.opencollective.com is really just a summary of the activity that happens on this repo. We don't invest much in it nowadays because feature updates are published on https://opencollective.com/opencollective/updates (which should have some RSS too! https://github.com/opencollective/opencollective/issues/3504).

There are probably some tools that can generate an RSS feed from Github's activities out there; we'd also be open to merging if someone wants to contribute to this. But it's unlikely that we'll tackle it ourselves in the near future.

**Comment by Betree** [comment]
The abovementioned changelog has been removed
