### ISSUE TITLE
Captcha Issues (False Negatives)

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5063]
Since we implemented HCaptcha, there were a few reports related to legit users not being able to complete their orders.
Although some of these cases are expected, I'm creating this issue to track these reports.

- It is known that some browser plugins can cause Captcha malfunction. We need to double down on Sentry to track weird errors that may be caused by third-party plugins.
- There's nothing that suggests you can move to the payment step without successfully passing the frontend side of the Captcha. I reviewed the code and tried to reproduce it debugging the order state in the frontend. If the challenge fails, the captcha value will be set to null and the next step button will be disabled.
- If the backend part of the captcha validation fails, no order will be created. The user probably reported this after successfully trying the second time.
- If you fail captcha in the frontend, you can always retry. You'll only advance in the order flow if you pass captcha validation.
- I notice that sometimes the captcha check will fail in the backend. I notice that fraudsters are trying to re-use captcha keys and causing errors.
- If you fail the captcha validation in the backend, you can simply return to the previous step and retry the captcha. We may want to rethink this UX.

**Comment by znarf** [comment]
It would be handy to re-display the captcha at the final step when we receive a failure, giving an intuitive way for users to validate their contribution, even if there was a problem with it.

**Comment by larsent** [comment]
Hi all, I wasn't previously familiar with this project. It's cool! 

I encountered this as a user this morning. The donate flow is a 3 step flow: Details, Profile, Payment Info. The captcha is on the "Profile" step. I
* Completed steps 1 and 2, including the captcha
* On the Payment Info step, I entered the wrong CVC and submitted the form. I see that this generated a Stripe token, which got submitted to the server. _I think it's important to point out that in some cases, entering invalid payment details won't reproduce this issue, because stripe.js catches a lot of invalid criteria before the form submission reaches your server._
* The card decline error was displayed properly
* I fixed my CVC and submitted again. This time, I got "Captcha verification failed"

<img width="704" alt="Screen Shot 2021-12-22 at 9 27 27 AM" src="https://user-images.githubusercontent.com/339129/147115917-b2f6b6ed-4897-4031-a92c-2ac5695b03cc.png">

I notice that the same Captcha token is submitted across requests (which makes sense since I only completed the captcha once, in the previous step). 

I wonder if what's happening is the captcha tokens are one-time use. The request in which the card gets declined validates the captcha, which invalidates it for the next request. 

I think @kewitz has it right 
> If you fail the captcha validation in the backend, you can simply return to the previous step and retry the captcha. We may want to rethink this UX. 

but it's pretty hard for a user to figure out they should browse to a previous step to re-complete the captcha. Perhaps the captcha makes more sense on the Payment Info step?

**Comment by kewitz** [comment]
@larsent that's valuable information. You're correct, the token is single-use and this is probably what is causing false negatives to happen.

**Comment by Betree** [comment]
Is there a way to re-generate (or re-use) a token without asking the user to complete the captcha again? Forcing users to go through the captcha flow one more time (even if it's on the payment step) would be a tedious and arguably unnecessary process since we've already confirmed that they're not a robot.

Sure, we can ask the captcha again after 5 failed attempts (to prevent bruteforce) but ideally, it should not impact the use case shared in https://github.com/opencollective/opencollective/issues/5063#issuecomment-999666238 where a simple typo in the CVC resulted in an error.

**Comment by kewitz** [comment]
@Betree that might be doable but we'll need to move the Captcha component to the payment information step.

**Comment by marysia-tanska** [comment]
Hi, I've just encountered the same/similar issue again.

<img width="488" height="321" alt="Image" src="https://github.com/user-attachments/assets/76f0d09f-5c3d-4793-b043-bde6e1df11b5" />

Tangent bug: the same OC organisation is also selling tickets through their website with what looks like an OC integration. In there there's another error: it says I can't buy a ticket with my email address as there's an account connected to it and I need to log in, but there's no field or button for login details.

<img width="851" height="299" alt="Image" src="https://github.com/user-attachments/assets/10727381-cfa4-4fe3-af84-89cd33b2a2ec" />


I'm on Windows + Chrome, also tried on Android + Ecosia
