### ISSUE TITLE
View all expenses on mobile jumps to footer

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5124]
**Describe the bug**
I clicked 'view all expenses' on the regional retreats events page and when the /expenses page loads of goes to the bottom of the page instead of the top as expected.

**Smartphone (please complete the following information):**
Pixel 4a5g
Android 12
Firefox

  P3 high frequency, low impact

**Comment by SudharakaP** [comment]
This is due to the `scrollBehavior` which we use for smooth scrolling. And seems that Firefox based browsers do not behave good with this property; https://github.com/vercel/next.js/issues/12105#issuecomment-907208495. I've added a piece of code that disables smooth scrolling for Firefox. Let me know how it looks. This is tricky to test on a desktop (since almost all mobile simulators on Chrome or Firefox dev tools simulate Chrome or Safari browsers it seems) and I think we need to push this to staging and test it on an actual device with Firefox. Let me know if you have any objections to this. 🤔 

cc: @Betree
