### ISSUE TITLE
[Strategic Focus] API, Open Collective as a platform

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5140]
Today, Open Collective is mostly a "website" and we would like to evolve in the direction of becoming more a "platform", an infrastructure. For this, one key aspect is the API and developers tools.

Since its original [preview release](https://blog.opencollective.com/open-collective-graphql-api-preview/), more than 3 years ago, we made our public GraphQL API v2 our first choice for new developments but we haven't iterated on its documentation for third party developers.

As a strategic focus, we would like to:

- ensure that the GraphQL API v2 is "complete"
- let developers do everything that is currently possible on our website with it.
- re-launch the API with a developer website, updated documentation, featured use cases and various developer tools.
- work with some key partners on integrations with our API (e.g. GitHub)
- start using it for small CLI internal tools (e.g. CSV to Added Funds for GitHub Sponsors, Benevity)

Prioritized Project for Q1 2022 Sprint 1:
- https://github.com/opencollective/opencollective/issues/5150

The main deliverables from Q1 2022 Sprint 1:
- Assessed the "completeness" of the GraphQL API v2: https://docs.google.com/spreadsheets/d/1KWkfdmwEKZqkV2jMHUF2p3LMJ5m2jtDJbyzBwok-8sc
- Added a few missing parts to the API: root queries for all kind of accounts, `createEvent` mutation
- Paid some debt and removed unused GraphQL API v1
- CLI tool to Add Funds for Github Sponsors: https://github.com/opencollective/opencollective-tools
- Creating a repository for API examples https://github.com/opencollective/api-examples
- Extending `createCollective` mutation to accommodate [GitHub use case](https://github.com/opencollective/api-examples/blob/main/account/create-apply-invite.md)

**Comment by alanna** [comment]
I absolutely support improving the API and making more integrations and outside development possible, so this is great. Right now we have several immediate use cases/needs, including GitHub, Benevity, and Cobudget.

I just want to be sure we keep in mind that success in this area is not only about tech. It's a lot about relationship building, partnerships, funding, community-building etc. Even if we have an amazing API, people won't just magically come along and build stuff. I think most of the coordination will still need to be driven from core team capacity, at least for while. 

As long as we're realistic about this, that's fine. But I don't want us to only focus on the tech side and end up with great tools that are under-used. So let's make sure the tech side is driven by real use cases and we have a strategy around that too.

Meanwhile, I can also imagine us, the core team, investing in building integrations ourselves, to achieve functionality we don't want to build ourselves. For example, we have discussed integrating with a third party events tool instead of needing to develop our own events feature to that level. The API will help make this more feasible.

**Comment by aerugo** [comment]
This is an excellent idea. We would love to integrate Cobudget with OpenCollective.

These are my initial thoughts on how to make a useful integration. I am posting it here so that you can treat it as a detailed user story for the API.

Take this proposal with a grain of salt, because once we sit down for a shared co-design session between people at OpenCollective and Cobudget, we will probably revise this quite a bit. This is just a starting point, and the purpose is only to start exploring what sorts of actions would need to be available through the OpenCollective API.

I will assume some familiarity with the idea behind Cobudget, but here are some concepts I will use:

- Bucket: A proposal to fund something specific. A bucket can have a description, pictures, and a line-by-line budget. A bucket can be owned by one or more people. A bucket is funded by users allocating funds to it through their balance. A bucket is a little like a Kickstarter-project - it is only considered funded once it reaches its minimum goal.
- Round: Buckets are created and funded in "rounds". A round can time limited or indefinite in time.
- Allocation: An admin of a round can allocate funds to a user.
- Contribution: A user can contribute funds to a bucket.

Cobudget is agnostic about what you choose to fund through a bucket. Personally I have seen everything from a 50 EUR investment in stationary to a 20,000 EUR budget for a large outdoor sculpture in a public park.

Rounds are also highly varied in scope and time. Some rounds are indefinite with a steady trickle of funded buckets. Other rounds have very clear time periods with hundreds of buckets created and funded over just a few weeks.

Based on these experiences, I imagine that an integration could look something like this:

---------------

1. A collective admin creates a project on OpenCollective
2. A round on Cobudget can be linked to that project, and through an API key gets the permissions it needs for that project. Ideally, this is just a "Connect to OpenCollective" button where a user who is admin of both the Cobudget instance and OpenCollective project gets redirected to OpenCollective, chooses their project, and gets directed back to Cobudget. We probably also need to do some sanity checks here - like looking out for mismatching currencies.
3. Once a bucket has been funded on Cobudget, an owner of the bucket can accept the funding. Once they take this action, the funds contributed to that bucket are added to the OpenCollective project from the Collective with a description containing the bucket ID, like:
	* Credit from MyCollective to MyProject • February 6, 2022
		* Funded bucket MyBucketID
4. Buckets that have accepted funding in a round that is linked to an OpenCollective project have a "Submit expense" button on Cobudget, visible to bucket owners and admins. This button brings up a modal on Cobudget that allows the same actions that are available on OpenCollective, with the exception that tags cannot be added manually. Instead, the tag is assigned by Cobudget to match the bucket ID. This would require a change to OpenCollective, namely to allow configuring projects so that only admins can create and assign tags to expenses.
5. When a user creates an expense, they are asked to log in to OpenCollective with a redirect back to Cobduget, or to create an account for OpenCollective through Cobudget. If they choose the latter, an account is created for them with the same email they use for Cobduget. Payment methods are available through Cobudget and new ones can also be added.
5. Submitted expenses that are tagged with the bucket id on OpenCollective are shown on Cobudget, including their status, and with a link to the record on OpenCollective. 
6. A sum of all submitted expenses for the bucket are shown on Cobudget.

Actual payout and approval of expenses would not happen on Cobudget, but on OpenCollective. We would assume that the handfull of admins of a round would need to learn how to use OpenCollective, while the regular users could handle their bucket "cradle to grave" on Cobudget.

**Comment by shaunagm** [comment]
The big technical blocker to Metagov integrating with OpenCollective right now is the lack of support for oauth & programmatic setting of webhooks. With our pilot users, we have to walk them through the process of copying and pasting their API key into a form on our website, and adding a webhook on OC back to our site. This usually means doing a Zoom call with them. Would love to get to the point where they can just click a series of buttons.

There are other things that would make it easier for us to integrate into OC but that's the big one.

**Comment by aerugo** [comment]
@znarf - to get some idea, how much of the integration I described could be done with the current API, and what is still missing?

**Comment by alanna** [comment]
Similar ask from @aerugo 

> I had a quick look at a spreadsheet I found that listed the features of the v2 API, and from what I understood, the main blocker might be if it's possible programatically create an API key for a user by authing them on OpenCollective and then redirecting back to the third party. That would probably be required to allow users to add expenses from Cobudget, but perhaps there is a workaround that I am not aware of.

**Comment by aerugo** [comment]
Could the copy-paste be circumvented by something semi-automatic?

One integration that might be good enough would be to simply create new users that are completely controlled by Cobudget. These would never be logged in to on OpenCollective, but used hold the expenses and payment methods that are created on the Cobudget side. Would it be possible to programatically:

- Create a new user
- Add it to a collective and project
- Generate an API key for that user and pass it back to Cobudget

This would really be just as good for the end user, except in the rare case that the end user already has an OpenCollective account with payment methods.

**Comment by znarf** [comment]
@aerugo @shaunagm The first beta version of our OAuth implemention is live. There is no full documentation yet but I've started a minimal one here: https://github.com/opencollective/opencollective/issues/5586 Happy to get your feedback, maybe on [our slack](https://slack.opencollective.com/), #api channel.

**Comment by aerugo** [comment]
I think @shaunagm is more close to implementing, but we might start looking into it soon too. 
Great that this is up now, excited to start working with OpenCollective as a platform!
