### ISSUE TITLE
[Strategic Focus] Community Governance

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5143]
Our Collectives are growing and their needs too. More and more, we're asked to provide tools to ensure a better governance of Collectives. We would like to reinforce that all admins are involved in the management of the Collective, and prevent a rogue admin to hurt the Collective. 

This can takes many form:
- enforcing best practices, like Collectives having more than 1 admin
- review permission system, introduce new roles, 
- multiple approval on key actions: adding new admins, approving expenses
- community participation regarding allocation of funds
- community votes

Prioritized Project for Q1 2022 Sprint 1:
- https://github.com/opencollective/opencollective/issues/5036

Other Issues/Projects:
- https://github.com/opencollective/opencollective/issues/5037
- https://github.com/opencollective/opencollective/issues/3081

GitHub label: https://github.com/opencollective/opencollective/labels/governance

**Comment by alanna** [comment]
I think some governance features make sense to build into the core of OC. But many make more sense to do via integrations. So let's keep that in mind when we're deciding what to build ourselves. 

Several really exciting collaborations are emerging now, like Metagov and Cobudget, and in these cases I think we best serve our governance tooling aspirations by focusing on #5140 API and time spent building relationships with collaborators.

I have worked on *a lot* of governance tooling and processes, and what I've learned is that one size does not fit all. We need to give people diverse tools and help them build the skills to pick the right ones for their community. This kind of capacity building is about soft skills and relationships as much as the tools themselves.

So what I'm saying is, I really support this strategic focus, and let's keep talking about how to go about it mindfully.

**Comment by shaunagm** [comment]
I'm the lead developer/architect for [Metagov](https://metagov.org/)'s [Gateway](https://github.com/metagov/gateway), which is meant to facilitate customized governance across multiple platforms. We've done some custom work over the last six months with a half dozen collectives, helping them set up expense approval processes that involve doing a consensus vote on Loomio, or a majority vote on Slack, or a custom approval process on Slack. You can see more detail and screenshots in [this blog post](https://blog.opencollective.com/metagov-gateway/).

We're very eager to talk through what a more in-depth integration might look like. We're imagining a link on a collective's dashboard that says something like "add custom governance". Users would then be able to choose among a variety of options, such as "vote on OpenCollective", "use consensus on Loomio", "consensus/vote/approve in Slack/Discourse/Github", etc which could be configured in various ways (for instance, saying a vote will take X number of days, or what might happen in case of a block in a consensus process). We'd start with a single option but could keep adding as many as people find useful. I agree with Alanna that customization is often desirable, so I suspect that we'd end up adding a lot of options, which we'd be thrilled to do. We're an open source project and could also mentor folks who want to learn how to add new options themselves, if there's interest.

I will note that so far no one we've worked with has chosen to make their decisions _on OpenCollective_. This is because of a lack of obvious and accessible discussion spaces. For instance, one could conduct a vote on whether to approve an OpenCollective expense through comments on that expense, but (a) not everyone who needs to participate may have access to the expense comment thread due to the inbuilt permissioning system and, (b) some governance decisions do not have associated comments threads the way "approve expense" does. Metagov often uses comments and messages as the medium for decision-making in the absence of explicit decision-making tools on the platform (we don't need to use comments for this on Loomio, for instance, because Loomio is already explicitly doing decision-making).

Any route we go down here would likely require at least some changes from OpenCollective. We'd love to talk with anyone in the community who is interested in these topics, and to be involved in any ongoing discussion about how OC is going to facilitate governance going forward.

**Comment by alanna** [comment]
Thanks for the context @shaunagm ! I'm really excited about what Metagov is bringing to the OC ecosystem.

In regard to your question about how decision making processes could happen natively on OC, I'd love to hear your thoughts and what you've learned from groups you're working with about how they'd want it to work. We have some spaces, like Conversations and comment threads on Updates, which could be repurposed for such communications, but they weren't designed with decision-making foremost in mind. 

I suspect you are right that many groups might not want to use another tool, and ideally we'd provide them options. I'm interested in how our native options can be functional but lightweight, so we can continue to focus on integrations for access to specialist complex functionality. Doing a good job at drawing where that line is will be key for a good strategy around governance tooling for OC.

**Comment by shaunagm** [comment]
For most of the groups we're working with, only a small portion of members interact with OpenCollective—some subset of the leadership, usually. So Metagov serves a dual purpose of enabling democratic decision-making but also just bringing transparency and visibility about finances to their main community platform, most often Slack. (For other groups we've talked to, there's no single platform used by the group, so we're working on enabling integrations through email and text as well.)

No one has asked us to let them make decisions via OpenCollective itself, which is why I forgot that Conversations were even a thing. You can see [here](https://opencollective.com/metagov/conversations/closed-this-is-a-vote-96e8n56o) a very bare-bones vote via conversation thread back in May 2021. Something like that could be linked to any action on OC. The barrier is less functionality and more the user experience—we'd want to make it easier and more intuitive to find the decision-making buried in Conversations. But I don't know how high a priority that particular goal should be, because I don't know how many collectives actually would want to make decisions on OC vs elsewhere.

**Comment by BenJam** [comment]
reopening as we continue the conversation about our governance features.
