### ISSUE TITLE
Expense failing due to Wise balance gets into incorrect error state

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5252]
If you pay an expense and it fails due to insufficient Wise balance, you see this:

![Screen Shot 2022-02-23 at 1 35 22 PM](https://user-images.githubusercontent.com/5498878/155243813-42d7e92d-f976-42e4-99d9-d9a0e4e2e969.png)

The expense's status then gets set to `error`. 

If you later refill the Wise balance and try to pay the expense again, you get this:

![Screen Shot 2022-02-23 at 1 37 29 PM](https://user-images.githubusercontent.com/5498878/155243912-3eeab60c-01cd-44d6-a2cd-95af88357839.png)

The only way out of this state is to edit the expense and re-approve it.

This should not happen. Once you refill the Wise balance, you should be able to pay it. And if you try to pay it again before refilling the balance, it should fail because of the balance issue, not due to being in `error` state.

**Comment by Betree** [comment]
Ping @kewitz

**Comment by kewitz** [comment]
Ideally, we throw the error in the payment action and not while processing the expense.
This is quite an edge-case, this means you probably had enough balance to pay for the expense value but not to cover the fees.

Either way, I agree with @alanna, an error can occur due to an external state and as a user, you should be able to just pay it again after it happens.

**Comment by alanna** [comment]
In this case the Wise balance was way lower than the expense amount, not just fees (I think the Wise balance was $50 and the expense was $300 or something like that).
