### ISSUE TITLE
[Roadmap] Ideas for Q2 Sprint 1 Prioritisation

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5330]
This is the issue to gather ideas for prioritization of the following sprint.

## Context
You can find here a detailed [FIGMA FILE](https://www.figma.com/file/uCwmTBwNC6Y9sronWds1TN/Sprint-processes?node-id=1101%3A68) that explains the Sprint Process. Here you can find the [Spring Planning Project Board](https://github.com/orgs/opencollective/projects/5/views/19). You can filter per milestone if you want to see other sprints. The view should normally default to the current sprint.

## Who should use this issue?
This issue should be used by the Sprint Facilitator of the following Sprint (not the current one) to start gathering some ideas for future prioritization.

This issue should be used by anyone who wants to submit an idea for immediate consideration.

## How to use this issue?
This is to gather ideas for things to be immediately built. This is not a backlog issue to dump every bug, request, etc.

Please refer to the current Strategic Focus Issues to get a sense of the current Roadmap Priorities. You can find them at the top of the Planning Board.

For FY22Q1S1/2 (year 22, 1st quarter, 1st sprint) and FY22Q1S2 these are:

- #5140
- #5141
- #5143
- #5148

In order to facilitate the ongoing process, we'll keep these focus areas for this next sprint and will refine them and reviewed them during the next retreat week. 

Please refer to the [Sprint Calendar](https://calendar.google.com/calendar/u/0?cid=b3BlbmNvbGxlY3RpdmUuY29tX2ZxbTN0azYwNTRucGp2YTY1czBoajRpdXFrQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) to see where we are and when the next retreat week is.

## Format 

The format for contributing ideas is reasonably open but I encourage you to think about _problems_, (not solutions) and the impact of those problems.  Consider the following questions:

- Who is your user?
- What are they trying to achieve?

It's useful to use the following format when trying to reflect this:

> When ____ , I want to ___ , so I can ___

## Prioritisation 

We rely on each of you to self-select problems that have both a high degree of impact and a high degree of alignment with the strategic focus areas above. 

For the purpose of determining high impact the triage process we use provides the following guidance:

Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

High frequency - >10% of users affected (measured as a proportion of total potential users for this case).

**Comment by kaylarep** [comment]
https://github.com/opencollective/opencollective/issues/4165

**Comment by kaylarep** [comment]
https://github.com/opencollective/opencollective/issues/4210

**Comment by alanna** [comment]
@kaylarep can you edit your two comments above and add a sentence about why you think they should be prioritised? Doesn't have to be a full thesis or anything, just a note.

**Comment by alanna** [comment]
## #5195 Collective activity log

I'm suggesting this because I think it meets multiple needs at once. The people working on API integrations (Cobudget, Metagov) have expressed that this would be a very helpful data feed, and we also need this for compliance reasons for OCF (e.g. reviewing if a Collective changes their mission, etc). I also think it's an important view for transparency overall.

**Comment by kaylarep** [comment]
## https://github.com/opencollective/opencollective/issues/3422 Incognito payouts

Most recent user feedback:
>I think this will be key in getting OC implemented for some more traditional orgs.

>My preference would even be to trust orgs to decide if it might be right for them to only display an aggregate of how much has been paid out in a given month, and not even show the individual payout transactions publicly. That would give orgs the choice to use OC without having to be more transparent than is customary for NGOs. Complete transparency of compensation to people is a pretty high bar to set as a requirement.

**Comment by alanna** [comment]
## #4953 Paypal fees issue causing negative balances

Negative balances look really bad and can throw off the host's accounting calculations. It's important we get financial accuracy fundamentals right.

**Comment by emberwry** [comment]
reopening #4760 Users not finding contact under actions menu

people still not finding the collective contact button and emailing support instead- prioritizing a button that says "CONTACT"  at the top of the page, not under "actions" or behind an envelope icon

**Comment by emberwry** [comment]
### #5251 Provide a way to identify expenses that are pending additional info

the "ready to pay" queues in OSC and OCF are a mess, with lots of old expenses and buried new ones that make it easy to miss the ones that are actually ready to be paid.

**Comment by kaylarep** [comment]
## https://github.com/opencollective/opencollective/issues/1738 Allow usual username/mail + password login
Another recent user request for this.  Or at least having the option to use a username/password - especially as password managers are getting more popular

**Comment by emberwry** [comment]
### #5255 in expenses paid out with paypal, create option for the payee to pay the fees

right now the process when an expense with a paypal payout has insufficient balance to cover the payment processing fees, we have to manually edit the expense and go to paypal to pay that amount and then mark it done manually. would love to have the little tick box to just have the payee pay the processing fees as we do with wise payouts.

**Comment by RichardLitt** [comment]
### #3357 Add a page to manage email subscriptions

Right now, users are getting too many emails. I've heard this from multiple users. There's no way to easily unsubscribe and resubscribe to emails, and we do not want to overwhelm users and influence their perception of the platform.

**Comment by kaylarep** [comment]
## https://github.com/opencollective/opencollective/issues/5360 Require address when creating new org as invoice expense payee

just adding this here,[ as its](https://opencollective.slack.com/archives/G46PNRCGP/p1648501302126489):
>  a big problem and blocking hosts from processing payouts.  don’t know if it should be P1 because it’s not high frequency but it’s pretty bad

**Comment by kaylarep** [comment]
## https://github.com/opencollective/opencollective/issues/5318 Sharing up-to-date press/media about e2c 

We need a place/easier way to keep the e2c publications organized and up-to-date.

right now, the most live info is in slack, but important articles/discussions/posts will get buried there.

**Comment by kaylarep** [comment]
## https://github.com/opencollective/opencollective/issues/5382 In-OC app notification management 

[User feedback](https://opencollective.slack.com/archives/CJ2ERRZQ8/p1648613511982539): Is it possible to receive / manage notifications from Open Collective within the platform only, and turn off email notifications? I'm in admin role on several organisations and collectives and the amount of OC emails I'm receiving is overwhelming

**Comment by alanna** [comment]
## #5368 Receipts for non-tax-deductible payments

This is causing a compliance problem for OCF and Gift Collective. I'm not sure how to judge priority, as this only affects a small number of transactions, but it causes a pretty big problem when it does affect them (producing invalid tax deductible receipts, which is a big no no for a charity).

**Comment by alanna** [comment]
## #5325 Expense invited to Collective should default to Collective as payee

This is a small change that has an outsize support impact when it goes wrong and degrades people's first experience with the platform. I hope it can be prioritized. It's important for the upcoming Season of Docs round of payments.

**Comment by alanna** [comment]
@piamancini in terms of your discussions with Cobudget and Metagov regarding API integrations, do we need to add anything here? Or was all that addressed in the previous sprint prioritisation?

**Comment by alanna** [comment]
> #3422 Incognito payouts

I recently had a call with NumFOCUS (who is adopting OC as a tool for their fiscal host which has nearly 50 project ready to go live) and they identified this as a priority.

**Comment by emberwry** [comment]
#3593 Host can require minimum number of admins

OCF and OSC both have policies to require more than 1 admin, but because the application doesn't require 2 admins to apply many people get through and then we have to follow up, more back and forth, making accepting applications a more onerous task.

**Comment by alinamanko** [comment]
### Timings notifications on expenses #[4518](https://github.com/opencollective/opencollective/issues/4518)

This would be a very simple fix in my opinion of just adding a Newer/Oldest filtering option to the host admin dashboard on the expenses tab.

**Comment by alinamanko** [comment]
### Enabling update of bank account [#4221](https://github.com/opencollective/opencollective/issues/4221)

This is an issue we receive lots of questions about and if it is possible to get it enabled that would be amazing

**Comment by alinamanko** [comment]
### Host Reports and added funds #[5372](https://github.com/opencollective/opencollective/issues/5372)

This seems like a high priority to me to enable to have a complete view of incoming funds

**Comment by SudharakaP** [comment]
### Search Experience Redesign (https://github.com/opencollective/opencollective/issues/4295) - Further Improvements

There are things that we could further improve on the search experience project; 

- Filtering for inactive/orphaned collectives.
- Scope and implement further filtering on the search page; currency filter, filtering by address/region, sort alphabetically.

**Comment by alanna** [comment]
## Implement new help/support page design

I can't find an issue for this - maybe @Memo-Es and @aminakazi can help?

A while back the designers demo'd some great designs for a revamped help page that would guide people to look at the documentation before contacting support, and collect more info from people to communicate to support what they are talking about. This would also cut down on the number of people contacting OC thinking they are contacting the Collective.

**Comment by alinamanko** [comment]
> ## Implement new help/support page design
> I can't find an issue for this - maybe @Memo-Es and @aminakazi can help?
> 
> A while back the designers demo'd some great designs for a revamped help page that would guide people to look at the documentation before contacting support, and collect more info from people to communicate to support what they are talking about. This would also cut down on the number of people contacting OC thinking they are contacting the Collective.

@alanna the [new support page is live](https://opencollective.com/help) and it may just be a matter of getting to it from the main page easier?

**Comment by alanna** [comment]
So people go all the way through the new support page and *still* end up emailing OC instead of the Collective? That's incredible to me.

**Comment by alanna** [comment]
If the new support page is live, why was there no 🔥  for it?

**Comment by natehn** [comment]
### https://github.com/opencollective/opencollective/issues/4927 Bank transfer (ACH/wire) contributions within the platform

I would love it if we scoped bank transfer donations through Wise or Stripe. At least exploring possibilities and fleshing out the issue for a future sprint would be great. It would also enable https://github.com/opencollective/opencollective/issues/2734.

**Comment by Memo-Es** [comment]
> So people go all the way through the new support page and _still_ end up emailing OC instead of the Collective? That's incredible to me.

What do you mean by the Collective? @alanna 

The relation I see with what you mention is the issue of people not finding the Contact button from the Collective page, we can showcase the new help & support page with its new functionality as well (Search bar) and rethink a bit https://github.com/opencollective/opencollective/issues/4760

**Comment by alanna** [comment]
I mean that support still gets lots of emails from people thinking they're contacting the Collective (like a specific open source project for example) but are actually contacting OC. We don't know why so many people get confused, but I had hoped that the new support contact workflow would weed them out.

**Comment by Memo-Es** [comment]
## https://github.com/opencollective/opencollective/issues/4356 Main nav bar updates
- Incorporating the new search capabilities
- Displaying all our marketing pages. Easier to navigate and find stuff
- New pattern for notifications (Both platform and user's)

**Comment by alanna** [comment]
My take on priorities, with different hats on:

### Overall
While it's not going to be an easy one, I think we need to do #5368 *Receipts for non-tax-deductible payments* because it's causing a bad compliance issue for our charity hosts.

### Ops/support team
The top pick is #5255 to enable the solution to the 'unable to pay 100% of balance due to fees' problem, which we already built for Wise expenses, for paypal expenses.

### OCF
Top pick is #3593 *Host can require minimum number of admins* - this will save a lot of time, improve compliance best practice, and benefit OSC onboarding as well.

### Broken stuff
I hope we can fix these bugs:
* #5325 Expense invited to Collective should keep Collective as default payee
* #5372 Host reports missing added funds
* #5360 Require address when creating new org as invoice expense payee

**Comment by shannondwray** [comment]
Analytics - Would be great to be able to get data about blog views (Plausible) - https://ghost.org/integrations/plausible/ 

Would also very much aid the UX conversation if we have more information about how users use the platform, what they click on, the flows between pages etc

**Comment by Memo-Es** [comment]
## Short term onboarding flow improvements
 - #5399 
 - https://github.com/opencollective/opencollective/issues/5400

**Comment by Betree** [comment]
## #3438 Redesign the page to edit tiers

This is a big project, but I would like to experiment with a different approach to reduce the load on the engineering team to the minimum by only taking care of creating the base skeleton of the page and having all the different parts in it (create a tier, edit a tier, remove a tier) tackled by external contributors through bounties.

I actually started [a draft](https://github.com/opencollective/opencollective-frontend/pull/7403) to do exactly that 3 months ago but I haven't found the time to iterate because it's difficult to prioritize things that are not on the roadmap.

Expected load on the engineering team:
- To create the skeleton: Medium (we probably want to do the listing part ourselves as the drag'n'drop feature deserves some refactoring)
- To create the specs: Simple
- To review the contributor's PRs: Medium. We can control the load by creating the issues progressively

**Comment by Betree** [comment]
# Tackle 1 non-critical security issue

While critical things are fixed with top priority, we have some security reports for non-critical issues that we never iterate on because they're not on the roadmap. Working on these is often not as satisfying for the team as enhancements or new features, because doing so is not going to improve the experience for anyone.
Yet they're important. For example, one issue we currently have impacts our email domain reputation, which can trigger things like https://github.com/opencollective/opencollective/issues/3106.

**My proposal is to tackle at least one of these issues each sprint, the one that we find the most impactful.**

Choosing the exact issue to work on can unfortunately not be done publicly as we can't release details about security issues before they're fixed.

**Comment by natehn** [comment]
Throwing this in here as well, even though it lives kind of outside the prioritization process:

### Ethical framework, continued: accountability and enforcement #5404

**Comment by alanna** [comment]
I had a call with the admins of multiple larger hosts and we went through this list together. They flagged #5195 #5251 #3593 and #4927 as priorities.

**Comment by kaylarep** [comment]
## https://github.com/opencollective/opencollective/issues/5410 Virtual Card Edits

This one is a doozy. If we can't get it this sprint, it's still a top priority at some point!  -- Also, could potentially be broken down into smaller issues.

**Comment by Memo-Es** [comment]
## #4689 Implement new homepage
 - Implement new homepage
 - Migrate the current homepage to /collectives
 - Set global style for marketing pages
 ---
 - Implement front end metrics (We need to create a new issue along with @opencollective/developers

**Comment by Betree** [comment]
## https://github.com/opencollective/opencollective/issues/1660 oAuth support 

@znarf Wanted to have this one in the upcoming sprint. The deliverable would be to have an MVP that allows some beta-testers to use an oAuth app with the basic stuff. We'll also need some design for the sign-in modal and pages to manage your apps.

**Comment by jfdh** [comment]
### #5418 Add a special tax deductibility tier for EU collectives

As we are making progress wit @piamancini  to offer tax deductibility for any donors in Europe, we will need to redirect these tax deductible donations to the bank account of the Foundation we are working with. More context in the issue.

**Comment by Betree** [comment]
## Improve validations in the expense form

Complexity: 1-3 days (medium)

We had many issues in the past with the expense flow being unexpectedly blocked and it's still happening to us in different situations. This started after the introduction of grants, where we started disabling the Cancel/Prev/Next buttons if there was an error in the form (even if for some reason the error was made on another step).

The following issues result from this root cause:
- https://github.com/opencollective/opencollective/issues/5020
- https://github.com/opencollective/opencollective/issues/5222
- https://github.com/opencollective/opencollective/issues/5429

It's a really annoying bug because you're basically trapped when it happens to you, everything is disabled and there's no message to explain what's wrong. I had started https://github.com/opencollective/opencollective-frontend/pull/7533 to solve this and would like to take some time to finish it.

**Comment by mkurz** [comment]
Can you please prioritize #2734? [We](https://opencollective.com/playframework) do have a company that wants to back us on a monthly basis with a substantial amount, however their finance department doesn't allow payments with credit cards, so that is blocking us at this point. We would have them as sponsor since like 2 month now probably already if recurring bank contributions would work.
Thanks!

**Comment by kewitz** [comment]
## https://github.com/opencollective/opencollective/issues/5431 Feature: Manage pending Expenses and Charges

As a high priority post-MVP feature for Recurring Expenses that can also help with missing virtual card receipts.

**Comment by kewitz** [comment]
## https://github.com/opencollective/opencollective/issues/5183 Provide Payout Method and Account context when Approving/Paying Expenses

**Comment by alanna** [comment]
## #2808 Host admin can export contributor data CSV

We already enable this data export for Collectives, but Hosts needs access to the same data as well. This has been requested by multiple large hosts. The only reason it hasn't been a critical need for first party hosts is because we do custom data queries with metabase, but all Hosts need this data.

**Comment by BenJam** [comment]
## #4691 Implement cleaned-up trasnactions interface 
Looking back through previous sprints I think there are a couple of hangers left in https://github.com/opencollective/opencollective/issues/4691#issuecomment-1098943311 we need a new issue to cover this.

**Comment by BenJam** [comment]
## 2682 Customisable email templates
P2 carry over from last sprint. As requested by a user: https://opencollective.slack.com/archives/C6JTTA4SK/p1644007590497949

**Comment by BenJam** [comment]
## #3504 RSS feed for updates

P2 carry over from last sprint. Strategic Focus on community growth
