### ISSUE TITLE
Notification emails should consistently come from no-reply@oc.com

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#5351]
**Describe the bug**
Any emails titled in this fashion, `Expense paid for <collective name>: -$00.00 for <title of expense>`, come from the account `info@opencollective.com` instead of `no-reply@opencollective.com`.

**Expected behavior**
They should come from `no-reply@opencollective.com`. 

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by RichardLitt** [comment]
Same for "New message from ..." emails.

**Comment by RichardLitt** [comment]
Same for "Expense paid for ..." emails.

**Comment by RichardLitt** [comment]
Another one: "X wants a Virtual Card". Note, @SudharakaP.

**Comment by RichardLitt** [comment]
Another one: "New expense on Open Source Collective: $5,000.00 for Research".

**Comment by SudharakaP** [comment]
> Another one: "X wants a Virtual Card". Note, @SudharakaP.

> Another one: "New expense on Open Source Collective: $5,000.00 for Research".

Thanks @RichardLitt 👍🏽

**Comment by alanna** [comment]
Have you discussed this with the user support team? These are currently not sent from `no-reply` because people can reply to them and support responds. This a very common way we get questions from users. cc @alinamanko @emberwry

**Comment by emberwry** [comment]
or make them all from noreply but say very clearly 'if you have any questions or concerns about this please contact support@opencollective.com' but no, then we'll lose the context that's so convenient when they respond directly. @RichardLitt what's the reason for making these noreply?

**Comment by RichardLitt** [comment]
Some of the newsletters are no-reply, and some are not. What struck me was the inconsistency between what was and what wasn't. Thinking about it closer, I don't mind either way, but I had assumed (incorrectly) that they should come from no-reply as that's where others are coming from.

**Comment by kaylarep** [comment]
I think it depends on the context. 

e.g. from the discussion [here](https://opencollective.slack.com/archives/C020ZQSLM5M/p1648543715144069), for example, in the https://github.com/opencollective/opencollective/issues/4694  

> i'd personally prefer it go to a no-reply. especially since it says 'contact your fiscal host' in the message.  im just concerned that we will have a lot of lost and angry admins reaching out to our support team when we will have no idea/context for the issue. and then redirecting an already confused admin will take longer, look clumsy. (redispatching sometimes is quite tedious).

**Comment by RichardLitt** [comment]
Perhaps a designer could help us figure this out better? @aminakazi @Memo-Es

**Comment by SudharakaP** [comment]
Related to this issue the following changes were proposed; 

- `Expense paid for` messages come from `no-reply@opencollective.com`
- `New message from` messages come from `no-reply@opencollective.com`
- `wants a Virtual Card` messages come from `no-reply@opencollective.com`
- `New expense on` messages come from `no-reply@opencollective.com`

@RichardLitt @opencollective/design @alinamanko @emberwry : My thinking is not to do these changes and keep things as they are for now unless we have a strong case to suggest we are getting too many emails or that there's some other problem that warrants these `no-reply` changes. I feel that as @emberwry [has pointed out](https://github.com/opencollective/opencollective/issues/5351#issuecomment-1081219576) these changes can lose context of the email conversations, or simple make the users life difficult when they could have just simply responded to the email. Thus I am closing this issue if no objections. Please feel free to re-open if you think otherwise. 🙂

**Comment by RichardLitt** [comment]
Sounds good. Thank you, @SudharakaP, for your work here!
