### ISSUE TITLE
Host Reports and added funds

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#5372]
At the moment it seems that the host reports don't have the option to see the added funds along with the contributions and expenses and as such, we lose quite a big chunk of visibility on incoming funds. I wonder if the Contributions section in the graph below could include the added funds as well:

![capture](https://user-images.githubusercontent.com/57156267/160323080-c9435088-436f-4ed4-a8ec-29bbd2f7d1ec.png)

Here is a Loom on this issue to give you a bit more information about the problem - https://www.loom.com/share/ebefb1bee6d7475a86bda18f5eac9650

**Comment by alanna** [comment]
Are host fees from added funds transactions included in the host fee numbers, and subsequently in the platform share numbers? If not that is massively skewing the picture.

**Comment by Betree** [comment]
> Are host fees from added funds transactions included in the host fee numbers, and subsequently in the platform share numbers? If not that is massively skewing the picture.

Yes, [they're included](https://github.com/opencollective/opencollective-api/blob/4ca438e890e0454c38d107631ecbc6025b2bbfae/server/lib/host-metrics.js#L216), the code that computes the host fee / platform share numbers doesn't care about where the fees are coming from.

We failed to foresee an important use case while creating this view, but thankfully it shouldn't be too difficult to add. Small specs proposal below.

# Specs
Most timeseries for hosts live in `host.hostMetricsTimeSeries`. For some reason, expenses/contributions timeseries have been added to some special objects (`host.expensesStats.expenseAmountOverTime`). I would propose to:
- [ ] Deprecate `host.expensesStats.expenseAmountOverTime`
- [ ] Deprecarte `host.contributionStats.contributionAmountOverTime`
- [ ] Add a new `host.hostMetricsTimeSeries.totalReceived`: quite similar to `contributionAmountOverTime`, except it would include the kind: `[ { date: '2020-01-01', amount: 1000, kind: 'CONTRIBUTION' }, { date: '2020-01-01', amount: 1000, kind: 'ADDED_FUNDS' }, ... ]`
- [ ] Add a new `host.hostMetricsTimeSeries.totalSpent`. I don't think we need to cover other types of debits, for now, so we can simply copy-paste
- [ ] Update frontend to use these new fields. No breaking change since we're not changing the existing ones

**Comment by Betree** [comment]
@alanna I'm adding added funds in there. Some feedback on this view could help:

![image](https://user-images.githubusercontent.com/1556356/164435660-17fa1be6-0c6a-42fe-9472-395936dcaa71.png)

- Should added funds be a separate metric as done here, or should we bundle added funds + contributions?
- Should we change the section title?

**Comment by alanna** [comment]
* At this stage, I think combine it into one metric. The top-level stats of all contributions to a Collective is useful, and breaking it down into payment methods isn't the most important thing. In the future it could be cool to have more fine-grained views to explore those nuances, but let's scope that out separately.
* No need to change the title - we think of all money coming into a Collective as 'contributions' regardless of how the funds were received.

How are we handling internal transfers between a Collective and its Projects and Events? I hope all funds for a Collective, including Projects and Events, can be combined into one, and the numbers are not skewed by moving money between them (e.g. If $100 comes in via an Event it's included in Collective contributions, but when that $100 is later moved from the Event to the main budget, it's not counted again).

**Comment by Betree** [comment]
> * At this stage, I think combine it into one metric. The top-level stats of all contributions to a Collective is useful, and breaking it down into payment methods isn't the most important thing. In the future it could be cool to have more fine-grained views to explore those nuances, but let's scope that out separately.

I've added some additional code to merge the two metrics. Both values are now displayed in the tooltip:

![image](https://user-images.githubusercontent.com/1556356/164651788-e782ce2a-10af-4ad5-9ec1-5a94f3c6d648.png)

> How are we handling internal transfers between a Collective and its Projects and Events? I hope all funds for a Collective, including Projects and Events, can be combined into one, and the numbers are not skewed by moving money between them (e.g. If $100 comes in via an Event it's included in Collective contributions, but when that $100 is later moved from the Event to the main budget, it's not counted again).

Unfortunately, a credit from the event to the collective will be counted as a contribution. We should tackle this in https://github.com/opencollective/opencollective/issues/4726
