### ISSUE TITLE
webpack backer not showing up

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#539]
https://opencollective.com/sarah_edo (id1589) has a correct subscription to webpack, documented in Order table (id 1552) but it has no row on the members table and so it's not showing up.
manually created a row for her as a backer

**Comment by piamancini** [comment]
correction, there was a line. I updated it to see if it changed something. User still not showing up

**Comment by xdamman** [comment]
Looking into it.

Btw, I saw that you also changed the `createdAt`, please never change that value (`updatedAt` is fine to update). I've restored it from a backup. All good, no worries.

**Comment by xdamman** [comment]
The issue was that we were only fetching the latest x backers at a time and then sorting them by total amount donated.

Now I'm sorting them at the API level (which wasn't trivial and is quite resource intensive because it has to compute every time the total amount donated for each -- we should optimize this at some point)
