### ISSUE TITLE
'Pending' Application appears as 'Already Hosted'

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5392]
As a host admin: an applying group (I'm assuming this is what happened) tried to resubmit their page. Their group is still pending acceptance (has not been accepted yet), and when they attempted, they received this message. --> So that hilighted portion is incorrect; they're not hosted, just pending.
![image](https://user-images.githubusercontent.com/64920686/161818600-5c9ee939-3bd0-46ba-8113-35d5d01b32b6.png)

**Comment by Betree** [comment]
Probably comes from [this line](https://github.com/opencollective/opencollective-frontend/blob/dcf018ff3fba6120aae626f23e76a661a1ab57d2/pages/ocf-host-application.js#L107). We should not run this condition if the mutation has succeeded, because the GQL cache will be updated with the host (in `collective?.host?.id`).

**Comment by RCheesley** [comment]
Here is the popup - I had the same experience :)

![screenshot-opencollective com-2023 03 03-10_25_18](https://user-images.githubusercontent.com/2930593/222696551-6c806cda-957f-4ea3-bea3-5daf5242e1df.png)
