### ISSUE TITLE
`no-console` ESLint Rule Should Be `Error` 

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5398]
From time to time we might add `console` statements (`console.log`, `console.error` etc) while writing code for testing. While these are useful, we shouldn't check these in, but it sometimes misses the eye as ESLint in our [current configuration](https://github.com/opencollective/opencollective-frontend/blob/99d887ec9983fc88b0dbaf94a11cf4e6d0c14cf8/.eslintrc.json#L6) only gives warnings for `console` statements.

I believe we need to turn on ESLint errors for `console` statements and make sure we add ESLint exceptions to places where there's a legitimate use for `console`. There's six places in code where we use `console` statements and thus it should be fairly easy to add exceptions for these. 

This will make sure that we don't accidentally check-in `console` stuff.

**Comment by Betree** [comment]
In the future, we may want to add a proper `logger` in the frontend, so that we can still log things when we feel the need but can disable them by default in production

Something else we never think about but that can be helpful: the `Sentry.captureException` directly creates a report on Sentry. We should ideally use it whenever we have something like that:

```es6
try {
  doStuffThatNeverSupposedToFail();
} catch (e) {
  Sentry.captureException(e, null, { tags: ['manual-capture'] }); // Adding a special tag to easily spot these issues in the dashboard
}
```
