### ISSUE TITLE
Content Text Injection

### ISSUE THREAD

**Issue by AkshayraviC09YC47** [opencollective/opencollective#5417]
**Describe the bug**
Hello team, recently i found that https://opencollective.com has an content/text injection vulnerability
Text injection allow attacker to inject custom content and text into the website via crafted urls/endpoints 
this allow to do phishing,scamming etc

**To Reproduce**
1. Just visit 'https://opencollective.com/signin/sent?email=(This%20website%20has%20been%20moved%20to%20http://evil.com)'
2. The content has been injected on `sent?email=` endpoint

**Screenshots**
<img width="887" alt="Screenshot 2022-04-11 at 10 25 26 AM" src="https://user-images.githubusercontent.com/58636452/162667560-d7c42997-9e84-42d3-b921-c9bc95e6246b.png">

**Severity**
  P4 low frequency, low impact

**Comment by Betree** [comment]
We don't consider this one to be a security issue since the content is sanitized.

Security reports must however follow some rules (see our [security policy](https://github.com/opencollective/opencollective/blob/master/SECURITY.md)). Creating a public issue is the opposite of responsible disclosure and public reports submitted like that are of course not eligible for our bounty program. Closing + deleting.
