### ISSUE TITLE
Country search not showing Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5447]
I was looking for Scuttlebutt related Collectives in NZ. It turned up the *host* of the two such projects I'm aware of, but not the Collectives themselves (which have the keyword *Scuttlebutt* in their title even).

<img width="1220" alt="Screen Shot 2022-04-18 at 9 24 51 AM" src="https://user-images.githubusercontent.com/5498878/163732764-48b73004-73b5-4f65-af32-01f822ee25ae.png">

<img width="494" alt="Screen Shot 2022-04-18 at 9 30 11 AM" src="https://user-images.githubusercontent.com/5498878/163732803-04f2edcf-e730-4d8f-805a-538b8f80f8e5.png">

Country search should pick up on the fact that these Collectives are under an NZ host and their currency is NZD and show them when someone is searching for NZ.

**Comment by SudharakaP** [comment]
Currently we only filter by country; and we don't check for currencies of collectives for this search. My thinking is maybe we should have a separate search filter for currency rather than mixing currencies and countries in the same country filter? This is proposed in one of the designs; 

https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16237%3A237513

@Memo-Es

**Comment by alanna** [comment]
The thing is, users don't care about our data structure. They just want to know which things are in NZ or whatever they are filtering for. We store this information across many different forms and locations, but that's our issue to solve, not to expect the user to know whether to search by country or currency or address.

**Comment by Betree** [comment]
> Currently we only filter by country; and we don't check for currencies of collectives for this search. My thinking is maybe we should have a separate search filter for currency rather than mixing currencies and countries in the same country filter? This is proposed in one of the designs; 
> 
> https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16237%3A237513
> 
> @Memo-Es 

@SudharakaP we don't need to involve the currency here. The country of an account should fallback to the parent's country, then the host's country.

**Comment by SudharakaP** [comment]
@Betree : I've opened a PR for this to modify the search query so that we return collectives whose parent belong to the country that is filtered for. But one thing I am a bit unsure about is that whether we need to also display the country flag on the collective card for these projects. For example in the below screenshot we see that `Test Project` is shown because it's parent is `Agora Collective` and that  is Canadian. However currently on the front-end we don't show country flags for projects or events, only organizations. I am wondering if we should show this? I am doubtful because it also give a kinda misleading idea that an event belongs to a country or a project belongs to a country, which might be a bit confusing I felt compared to an organization or a collective showing the country flag. 🤔  

![image](https://user-images.githubusercontent.com/12435965/165184447-8f0f093c-7ed3-4190-b063-3757b0709c55.png)

cc: @Memo-Es

**Comment by Betree** [comment]
> @Betree : I've opened a PR for this to modify the search query so that we return collectives whose parent belong to the country that is filtered for. But one thing I am a bit unsure about is that whether we need to also display the country flag on the collective card for these projects. For example in the below screenshot we see that `Test Project` is shown because it's parent is `Agora Collective` and that is Canadian. However currently on the front-end we don't show country flags for projects or events, only organizations. I am wondering if we should show this? I am doubtful because it also give a kinda misleading idea that an event belongs to a country or a project belongs to a country, which might be a bit confusing I felt compared to an organization or a collective showing the country flag. thinking
> 
> ![image](https://user-images.githubusercontent.com/12435965/165184447-8f0f093c-7ed3-4190-b063-3757b0709c55.png)
> 
> cc: @Memo-Es

I do think that we want to do this. As per my comment above:
> The country of an account should fallback to the parent's country, then the host's country.

If you haven't defined your event location, then it should default to your collective location (because if not specified it seems safe to assume that you operate from the same country). Whether we want to also display the host country as a fallback by default is a different question, no strong opinion on my side.

**Comment by SudharakaP** [comment]
> I do think that we want to do this. As per my comment above:
> 
> > The country of an account should fallback to the parent's country, then the host's country.
> 
> If you haven't defined your event location, then it should default to your collective location (because if not specified it seems safe to assume that you operate from the same country). Whether we want to also display the host country as a fallback by default is a different question, no strong opinion on my side.

@Betree : Thanks. I've opened a PR to add these flags to child collectives at; https://github.com/opencollective/opencollective-frontend/pull/7740
