### ISSUE TITLE
user profile not displaying

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#551]
opencollective.com/mojoaxel shows a 500. Looks like a frontend issue.

**Comment by xdamman** [comment]
Can’t really look at it now but here is an easy way to debut this type of error:
Copy the db to staging, monitor the frontend logs on staging when opening that page.

**Comment by xdamman** [comment]
This could be an issue with the longDescription that contains anchor tags or unsupported html, or a erroneous state in the database.

**Comment by asood123** [comment]
Already repro'd it in frontend. It's an apollo error that I could chase... Or much easier for you to fix and I can stay focused on host migration :)

**Comment by xdamman** [comment]
What’s the Apollo error?

**Comment by xdamman** [comment]
I’ll look into it first thing tomorrow.

**Comment by xdamman** [comment]
Error is 
```
apollo error:  { TypeError: Cannot read property 'name' of null
app[web.1]:     at Membership.render (/app/build/.next/dist/components/Membership.js:61:29)
```
Which links to 
```javascript
const name = ((collective.name && collective.name.match(/^null/)) ? null : collective.name) || collective.slug;
```
https://github.com/opencollective/frontend/blob/ec7725726fad64ca02e1ac8e012ca3b362b0a81a/src/components/Membership.js#L20

So it means that one of the collective linked in the `Members` couldn't be fetched.
It might be related to #555 because I can see that this user is an `ADMIN` of multiple duplicates of open source collectives with GitHub repo. I also see those collectives are not active.

Regardless, the frontend shouldn't break that bad in such situation. Pushing a quick fix for that.

**Comment by xdamman** [comment]
![](https://cl.ly/2L1y2o2c3C2j/Screen%20Shot%202017-10-25%20at%2012.06.27%20PM.png)

**Comment by xdamman** [comment]
You can see that when opening the console on https://opencollective.com/mojoaxel

**Comment by xdamman** [comment]
At least now the profile page shows up. So removing the high priority label.

**Comment by piamancini** [comment]
@asood123 this is for vis. they've hit  github onboarding issues many times. I'll assign a priority label and assign it to you as well.

**Comment by piamancini** [comment]
this is part of #555
