### ISSUE TITLE
"Resend invite" button positioning issues

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5585]
Seems to happen when one of the cards includes a description but not the others:

![image](https://user-images.githubusercontent.com/1556356/170254144-df99712b-9661-4e8e-9b62-9c6e5843cabd.png)

Steps to reproduce:
1. Create a collective
2. Click on Settings > Team
3. Invite some members

**Comment by Soheilafsha** [comment]
اعضای هیئت مدیره برای پروژه هایی که به ایده های من مربوط میشود تعیین کنید و قرار اولین جلسه تبادل نظر را مشخص و اعلام کنید

**Comment by Soheilafsha** [comment]
اعضای هیئت مدیره از هر نقطه جهان قابل قبول میباشد .
برای ارتباط عمیق تر و شکل گیری زنجیروار دنیای وسیع تر در میز کار راه دور جوامع رو بهم بیشتر متصل کنیم .
اگر اماده شروع هستین عملیات و تپارکات لازم رو فراهم کنید و نظرات خود را با اعضای خلاق هیئت مدیره به تبادل نظر و برسی به اشتراک بگذارید

**Comment by palerdot** [comment]
@Betree I have a PR that fixes this issue. PR - https://github.com/opencollective/opencollective-frontend/pull/7845

The solution suggested in the PR is to add a `min-height` to the description paragraph so that it takes of alignment issues when there are member cards with empty description. I have provided more details in the linked PR. In case any changes are required, please let me know.
