### ISSUE TITLE
Add tests for member invitation mutations

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5605]
Given that these mutations represent quite important features, we want them to be covered.

Here's the skeleton that we want to implement in `test/server/graphql/v2/mutation/MemberInvitationMutations.test.ts`:

```es6
describe('MemberInvitationMutations', () => {
  describe('inviteMember', () => {
    it('should create a new member invitation and its related activity', () => {});
    it('must be authenticated as an admin of the collective', () => {});
    it('can only add with role accountant, admin or member', () => {});
    it('can only add with a user account', () => {});
  });

  describe('editMemberInvitation', () => {
    it('should edit the role, description and since and document the changes in an activity', () => {});
    it('must be authenticated as an admin of the collective', () => {});
    it('can only update role to accountant, admin or member', () => {});
  });

  describe('replyToMemberInvitation', () => {
    it('can accept the invitation and document the changes in an activity', () => {});
    it('can decline the invitation and document the changes in an activity', () => {});
    it('must be authenticated as the invited user', () => {});
  });
});

``` 

*Tip: run with `npm run test -- --watch test/server/graphql/v2/mutation/MemberInvitationMutations.test.ts`*

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by snitin315** [comment]
@Betree  The following cases (Editining an invitation and declining an invitation) actually don't document changes in an activity.


`it('should edit the role, description and since and document the changes in an activity', () => {});`
` it('can decline the invitation and document the changes in an activity', () => {});`

https://github.com/opencollective/opencollective-api/blob/8916c35847d63b40a167dce4a8d2944d8b4c25aa/server/models/MemberInvitation.js#L162-L165
https://github.com/opencollective/opencollective-api/blob/8916c35847d63b40a167dce4a8d2944d8b4c25aa/server/models/MemberInvitation.js#L228-L231
