### ISSUE TITLE
Associate guest contributions to registered profile

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5634]
Recently I've been dealing with a case where someone set up an org profile for their foundation, but then made a series of contributions without logging in, creating a new guest profile every time. This is quite easy to do, since it's easy to simply make a guest contribution. They put in the name of the org so they weren't intending it to be separated or anonymous. This results in numerous duplicate profiles and the contributions not showing on the actual org's page.

If someone enters the name and email of a registered profile as a guest, can we safely associate it with their registered profile even if they are not logged in? At first glance it seems like a security issue because people could donate in the name of profiles they do not actually control if they know the associated email. 

However, what would the motivation be for someone to give money in the name of an unassociated org? What benefit or scam could they possibly get? The notification for the guest contribution goes to the email associated with the org profile anyway, so they will be made aware.

If there's not a security risk, I think we should consider automatically associating such contributions to the registered profile, and send an email saying "$x was contributed to Y Collective in the name [organization]. This was processed as a guest contribution. If this was not an authorized contribution, let us know" or something like that.

**Comment by Betree** [comment]
> If someone enters the name and email of a registered profile as a guest, can we safely associate it with their registered profile even if they are not logged in?

This is what we currently do. It's currently considered an acceptable security issue (https://github.com/opencollective/opencollective/issues/4265) that we're hoping to solve with https://github.com/opencollective/opencollective/issues/3842.
Since emails are associated with a user profile, this however only applies to individuals - not orgs.

> However, what would the motivation be for someone to give money in the name of an unassociated org? What benefit or scam could they possibly get? The notification for the guest contribution goes to the email associated with the org profile anyway, so they will be made aware.

For individuals, the main risk (that we currently assume) is users thinking that they've been hacked (see https://github.com/opencollective/opencollective/issues/4265).

For organizations, the risk would be:
1. Contribute to a controversial project as Facebook, Google, or any public company
2. Tweet about it - *Look, Facebook is supporting xxx!*
3. Eat popcorn

Automatically assigning to an org based on the name is tricky. I still think that the long-term solution is to force users to sign in when the email exists (from there, we're able to surface the orgs they're administrating). That will become acceptable once we have https://github.com/opencollective/opencollective/issues/3842 (esp. for the embedded contribution flow).

**Comment by Betree** [comment]
Should we close in favor of https://github.com/opencollective/opencollective/issues/4265? It sounds like the same issue
