### ISSUE TITLE
Do not show archived items on user menu

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5770]
A user created a bunch of Collectives, then decided to make them all Projects under one Collective instead and archived the Collectives. Now their user menu looks like this:

<img width="421" alt="Menu Screenshot" src="https://user-images.githubusercontent.com/5498878/180088922-e1f2ef53-e528-403e-946a-495080b77a10.PNG">

Could we not display archived items here?

**Comment by Betree** [comment]
Archived accounts still have a public page, it's helpful to link them from somewhere. We should think about a proper place to do that, otherwise we'll get support tickets with the inverse problem: "I can't find my archived collective".

My suggestion would be to keep all these in the user menu, but to collapse them under an "Archived" section that can be extended on click.

cc @opencollective/design

**Comment by alanna** [comment]
I agree with @Betree 's proposed solution

**Comment by Betree** [comment]
Got a [request](https://opencollective.freshdesk.com/a/tickets/138223) for this on support

**Comment by alanna** [comment]
I think we should implement the suggestion above as an MVP and not wait for design. @SudharakaP ?
