### ISSUE TITLE
Custom label or description for virtual cards

### ISSUE THREAD

**Issue by themightychris** [opencollective/opencollective#5788]
When multiple virtual cards exist in an account, it is currently necessary for admins to manually document out of band what the use/purpose for each card is. It would be very helpful for admins to be able to assign a custom label or description to each card

**Comment by znarf** [comment]
## User story 

As a Collective admin, I would like edit the name of my cards to have a clearer view of their respective purpose.

## Best solution for this problem

A "Edit Card details" action in the Virtual Card administration interface similar to the one available for Host admins.

Only "Card Name" would be available for Collective instead of all the settings available to Host admins.

<img width="375" alt="Screenshot 2022-09-23 at 11 55 25" src="https://user-images.githubusercontent.com/806/191939188-4a0327c7-8cb6-4dd8-94a0-7ab13d0a0651.png">

Also:
- In the Create Card form, "Card name" should have a default value so Host admins don't have to figure one by themselves.

## MVP

Because Host admins can already change "Card Name", Collective admins can ask them to proceed with the change, which is inefficient.

## Metrics 

- How many cards edited by Collective admins and a non-default "Card name" after the feature is shipped?

## Documentation 

We should update the Virtual Cards documentation from the Collective admins perspective, ensure "Edit Card Details" and "Card name" are covered.
