### ISSUE TITLE
Host admin can set expense to incomplete from any state

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5824]
Currently only Approved/Error expenses can be marked as `incomplete`. This seems arbitrary and there are many cases when an expense in `pending` or another state might need to be marked `incomplete`. The only restriction that makes sense to me is disallowing it from `paid` state.

**Comment by Betree** [comment]
On top of "Paid", it also doesn't make sense to allow `Mark it as incomplete` for:
- Draft: drafts are, by nature, incomplete
- Unverified: same as draft
- Processing: processing expenses cannot be changed because the payment is ongoing
- Scheduled for payment: not sure about this one, but the same limitation as Processing might apply

cc @kewitz

**Comment by kewitz** [comment]
Considering that setting as incomplete is a tool restricted to host admins, the idea here is to make sure that until the collective admin approves the expense, the expense is totally outside the host admin's plate. The exception here is the case the expense is submitted to the host collective because the host and collective admin is the same person. But I don't think this counts for the majority of expenses.

Is this assumption wrong?

**Comment by alanna** [comment]
The example that led me to raise this issue was an expense that had a compliance issue that I knew about, but other Host admins did not, and they might accidentally approve and pay it. In this case, the admin of the Collective was also a Host admin. Basically I as a Host admin wanted to ensure it wouldn't get paid by another admin, and dropping a note in Slack or whatever is very likely to be lost. It was a compliance issue most other admins don't consider in this case.

**Comment by alanna** [comment]
Basically I think unless there's a strong reason not to, we should make tools as flexible as possible because we don't know all use cases.
