### ISSUE TITLE
Create OSC Onboard Page

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5972]
Relocate existing OpenSource related Components
We want to have the flow forking when you click in the "For open source projects" (goes to /opensource/apply/intro)
- [x] Create osc-host-application folder
- [x] Move existing OpenSource related components from create-collective into the new folder
- [x] Restyle CreateOpenSourceCollective and Repository list
- [x] Create new page/route for "/opensource/apply/intro"
- [x] Redirect create-collective button to new route

**Comment by gustavlrsn** [comment]
@poohlaga here's a [link to Figma with the copy](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?node-id=16482%3A214918) that needs to be updated once we update the criteria, related to #5974

**Comment by kaylarep** [comment]
I would just ask that, since this process is essentially copy-pasting from the OCF one, if you notice things that are redundant/weird about the module flow and you make edits, please make these edits to the OCF one too.  

(I think the OCF was crafted a bit hastily and might benefit form some review/refinement).
