### ISSUE TITLE
Banning Accounts should Free the Slug

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5987]
I had this idea with regard to this following Freshdesk ticket; https://opencollective.freshdesk.com/a/tickets/119533. 

Currently when root actions are used to ban a collective we do not reset the slug of the collective, resulting in manual action needing to me taken to free the slug. I suggest,

- For both `Ban accounts` and `Search & destroy` we reset the slug. 
- I also think that `Search & destroy` is a bit of a misnomer as under the hood we actually banning the account. Maybe we should rename this to `Search & ban`? 
- Should we only use these root actions to ban accounts? Because both of these sets the `isBanned` flag to true. I believe when we complete https://github.com/opencollective/opencollective/issues/5374 there will be a distinction between banning and deleting. 

cc: @Betree

**Comment by Betree** [comment]
Good call, we should indeed change the slug. That can be done from https://github.com/opencollective/opencollective-api/blob/main/sql/ban-collectives.sql#L16

The name "Search & destroy" comes from the manual job of banning spammers that was documented like that, we didn't think much about it since it's an internal tool that's mostly used by myself and @znarf. No blocker for me to change it if it makes things clearer. And yes, both tools currently in "Moderation" are meant to ban, not delete.
