### ISSUE TITLE
Webhook Questions and Clarifications

### ISSUE THREAD

**Issue by Cadair** [opencollective/opencollective#6018]
Hello,

I have started using open collective for SunPy (as part of NumFOCUS) and am loving it so far, but I wanted to pull in collective notifications into our [matrix](matrix.org) chat.

I have managed to get [quite far](https://github.com/matrix-org/matrix-hookshot/pull/514) by just collecting some example payloads over time, but I have a few questions and comments:

1) Why does the `"expense.comment.created"` payload have no data? What's the expected way to be able to provide links to the comment etc with that event?
2) Why do the `"collective.expense.approved"` events not have a `data.collective` object with details about the receiving collective but `"collective.transaction.created"` payloads do?
3) Is there any way to link to a transaction for more information?
4) It would be super useful if a URL field could be added to most of the payloads to get a link back to the event in the web UI.
5) #4244 would be really lovely!
6) How do I get webhook events for things that happen in my sub-projects?

Thanks so much for an awesome platform!

**Comment by Betree** [comment]
Hi @Cadair!

> 1. Why does the `"expense.comment.created"` payload have no data? What's the expected way to be able to provide links to the comment etc with that event?

Expense comments are private, and we decided a while ago that webhook events wouldn't include any private data in order to facilitate the security aspects of this feature. With our team growing, that's something we may rediscuss but it's how it works now.

Our advice is usually to listen to webhooks to get notified about new activities, then use our [public GraphQL API](https://docs.opencollective.com/help/contributing/development/api#graphql-api) to retrieve the data.

> 2. Why do the `"collective.expense.approved"` events not have a `data.collective` object with details about the receiving collective but `"collective.transaction.created"` payloads do?

We could add that bit of information if it unblocks you, but keeping #3422 in mind it's probably better to use the GraphQL API here too.

> 3. Is there any way to link to a transaction for more information?

If you mean in the UI, an option is to search for `#{transactionID}` on the transactions page: https://opencollective.com/babel/transactions?searchTerm=%231238714.

> 4. It would be super useful if a URL field could be added to most of the payloads to get a link back to the event in the web UI.

Good call, I'm opening an issue for this one in https://github.com/opencollective/opencollective/issues/6020.

> 5. [Provide Example Payloads for all webhook events #4244](https://github.com/opencollective/opencollective/issues/4244) would be really lovely!

We haven't documented all activity types yet, but this one is live already:


![Peek 2022-07-18 12-53](https://user-images.githubusercontent.com/1556356/179496912-9efaed15-b299-4c96-9801-27dc54b59fe1.gif)


>  6. How do I get webhook events for things that happen in my sub-projects?

Currently, you need to add the webhook on each account individually.
In the future, we want to give you the option of choosing whether the webhook needs to run on them too: https://github.com/opencollective/opencollective/issues/4738. 

> Thanks so much for an awesome platform!

Thanks for providing this constructive feedback!

---

@shannondwray before closing this issue, I'd like us to update https://docs.opencollective.com/help/collectives/collective-settings/integrations#webhooks-generic-slack-discord to explain that payloads don't contain any private info and redirect people to https://docs.opencollective.com/help/contributing/development/api#graphql-api if they need more. Let me know if you need more details!

**Comment by Cadair** [comment]
Hi @Betree thanks for answering my questions so quickly!

> Expense comments are private, and we decided a while ago that webhook events wouldn't include any private data in order to facilitate the security aspects of this feature. With our team growing, that's something we may rediscuss but it's how it works now.

This makes perfect sense, for my use case just having a link to the comment would be great as then I could have a message which says "New comment posted: <link>".

> Our advice is usually to listen to webhooks to get notified about new activities, then use our [public GraphQL API](https://docs.opencollective.com/help/contributing/development/api#graphql-api) to retrieve the data.

I don't think the way I am handling the webhook parsing allows me to make further calls out to anything (it's in a very restricted sandbox).
 
> > 2. Why do the `"collective.expense.approved"` events not have a `data.collective` object with details about the receiving collective but `"collective.transaction.created"` payloads do?
> 
> We could add that bit of information if it unblocks you, but keeping #3422 in mind it's probably better to use the GraphQL API here too.

I am not sure I follow, I am talking about the receiving collective, i.e. to whom the money is being paid from (i.e. SunPy) rather than who it's being paid to. The information about the user who submitted the expense is already included.

> 
> > 3. Is there any way to link to a transaction for more information?
> 
> If you mean in the UI, an option is to search for `#{transactionID}` on the transactions page: https://opencollective.com/babel/transactions?searchTerm=%231238714.

Perfect thanks.

> 
> > 5. [Provide Example Payloads for all webhook events #4244](https://github.com/opencollective/opencollective/issues/4244) would be really lovely!
> 
> We haven't documented all activity types yet, but this one is live already:

Oh excellent, I missed that. Might be worth including that or mentioning it here: https://docs.opencollective.com/help/collectives/collective-settings/integrations ?

> 
> > 6. How do I get webhook events for things that happen in my sub-projects?
> 
> Currently, you need to add the webhook on each account individually. In the future, we want to give you the option of choosing whether the webhook needs to run on them too: #4738.

Maybe I don't have the permissions to do this then, but I can't see any option to enable wehooks on [this](https://opencollective.com/sunpy/projects/sunpy-nasa-80nssc22k1058-ostfl) subproject for example?

**Comment by Betree** [comment]
> This makes perfect sense, for my use case just having a link to the comment would be great as then I could have a message which says `New comment posted: <link>`.

I've created an issue to document the need for this: https://github.com/opencollective/opencollective/issues/6178.

> > > 2. Why do the `"collective.expense.approved"` events not have a `data.collective` object with details about the receiving collective but `"collective.transaction.created"` payloads do?
> > 
> > 
> > We could add that bit of information if it unblocks you, but keeping #3422 in mind it's probably better to use the GraphQL API here too.
> 
> I am not sure I follow, I am talking about the receiving collective, i.e. to whom the money is being paid from (i.e. SunPy) rather than who it's being paid to. The information about the user who submitted the expense is already included.

Sorry, I misread that part! I'm pushing an update in https://github.com/opencollective/opencollective-api/pull/8195 to add the collective info.

> Oh excellent, I missed that. Might be worth including that or mentioning it here: https://docs.opencollective.com/help/collectives/collective-settings/integrations ?

Indeed! I've updated the docs page.

> Maybe I don't have the permissions to do this then, but I can't see any option to enable wehooks on [this](https://opencollective.com/sunpy/projects/sunpy-nasa-80nssc22k1058-ostfl) subproject for example?

Looks like there's a bug on the menu, I'm working on it at https://github.com/opencollective/opencollective-frontend/pull/8396. If you need to access the feature today, you can do so by accessing the direct URL: https://opencollective.com/sunpy/projects/sunpy-nasa-80nssc22k1058-ostfl/admin/webhooks.


Closing the issue as this should address all the questions, but feel free to re-open if you have more.

**Comment by Cadair** [comment]
Thanks so much!
