### ISSUE TITLE
Unable to register incognito for an event

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6245]
**Describe the bug**
There are people who want to go to https://opencollective.com/decentsocial/events/decentsocial-conference-8c7e0a05 that have privacy concerns, but it seems it's not possible to select 'incognito' when registering

**Expected behavior**
Incognito should be an option when selecting the contribute as profile.

  P1 high frequency, high impact

**Comment by mixmix** [comment]
Know it's new year.
Would love this to be solved in the next 2 weeks as we promote our event.

Lmk if there's any way I can help

**Comment by Betree** [comment]
This is not a bug but a design choice we [made](https://github.com/opencollective/opencollective-frontend/pull/2435) after https://github.com/opencollective/opencollective/issues/2371. The issue was that, as an event organizer, you need access to some information for the attendee (at least the email).

We've iterated on the incognito feature since and admins now get incognito users' emails when they export the CSV. So, I see no blocker for this issue. I'll open a small PR to try out the change and ensure everything works as intended.

**Comment by mixmix** [comment]
Awesome, thank you.

I guess an "email recipients" or "here are the recipient emails to copy" feature could be good. Different feature though

**Comment by Betree** [comment]
Hi @mixmix, contributors can now use "incognito" for events. Let me know if you face any issues!

**Comment by BenJam** [comment]
seems to me that, mostly, the need would be to register for the event and not appear in the attendee list... without having the request @alanna received I'm not sure. 

Given the current guidance is specifically that if you do not want to share your details with the event administrators I think the expectation we created for users there is okay... but we probably need to go back to the original proposal in #4537 and have a specific opt-in for sharing details (and perhaps, update preferences) with the admons.

**Comment by Betree** [comment]
@BenJam I made a proposal that is similar to your last comment in https://github.com/opencollective/opencollective/issues/7308, which is therefore a requirement to resolve this issue.
