### ISSUE TITLE
Event attendees broken?

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#6247]
## What I saw

1. https://opencollective.com/decentsocial/events/decentsocial-conference-8c7e0a05

![image](https://user-images.githubusercontent.com/2665886/208791347-edc67be6-1847-408a-8a75-6352736d6152.png)

2. https://opencollective.com/decentsocial/events/decentsocial-conference-8c7e0a05/contribute/decentsocial-2023-49790

![image](https://user-images.githubusercontent.com/2665886/208791378-d9888262-75ce-4776-ad67-77703b0c6e00.png)

## What I expected

if 4 people are going... I expect the same 4 people to have be listed as attendees everywhere. 

## Debugging

I wondered if it was because we have a free tier... but no that's not it because Dmitri paid money... maybe he contributed money without registering (we had that as an option, but disabled it to reduce confusion), but he thinks he registered.

Since disabling the contributions to the event (so there is only the register pathway), it seems like "Nataniel" has also fallen into this mystery hole...

I though maybe it was your caches, but no this problem is persisting over an hour....

**Comment by Betree** [comment]
- https://opencollective.com/ianconsolata: that's indeed because of a bug where people registering for free tickets are not attributed to the right ticket. Pushing a fix in https://github.com/opencollective/opencollective-api/pull/8355.
- https://opencollective.com/dmitri-zagidulin: he's indeed in the situation you described (`maybe he contributed money without registering (we had that as an option, but disabled it to reduce confusion), but he thinks he registered`)
