### ISSUE TITLE
Broken dev environment for Horizon project

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6261]
Looks like `_data` is excluded from `.gitignore`.

![image](https://user-images.githubusercontent.com/1556356/210242847-2227191a-5be0-40ce-af21-b2fe164b3391.png)

**Comment by Betree** [comment]
Fixed with `npm run fetch-data` after modifying some env variables.

We should either:
- Commit some initial `_data`
- Or document the command (and how to setup your in `README.md`)

**Comment by gustavlrsn** [comment]
Updated the README with instructions and some general notes here:
https://github.com/opencollective/horizons/pull/25

`_data` is currently git ignored since it's quite big with the production data (42 MB), but as you say adding some smaller initial dataset could be nice to much easier have the dev environment set up

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/horizons/pull/25
