### ISSUE TITLE
Improve tag validation

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#6326]
There are tags looking like this, as a single tag:
`"instagram #contemporaryart #portrait #creative #artgallery #hiphop #photooftheday #sketchbook #fashion #follow #beautiful #rap"`

And also URLs, and other things.

Perhaps there is a need to define stricter validation

- max length?
- only certain characters?

**Comment by Betree** [comment]
We already have some basic tags formatting/validation in [`sanitizeTags`](https://github.com/opencollective/opencollective-api/blob/1a328112d30ba79086c886f15e6a0d518e5dadf2/server/lib/tags.ts#L29).  However, it looks like the `Collective` model is not taking advantage of it but instead relies on its own `cleanTag`.

This helper currently:
- Trims + lowercase
- Remove empty
- Uniq
- Enforce max length

The example you shared looks like a misuse of the tags input, which could be resolved by having a better UX. In doubt, we could also split on `#`: 

```es6
const tags = flatten(baseTags.map(tag => tag.split('#')));
```

I'm not sure about limiting to certain characters, but why not if we find obvious cases to prevent?

**Comment by gustavlrsn** [comment]
Ah, thats good, seems like we're mostly covered! Maybe an improvement could be to have them both use the same validator, the `Collective` version does not seem to look at max length.

For limiting to certain characters, what I had in mind was to limit to something like alphanumericals (a-z, 0-9), hyphens, underscores, dots and spaces to prevent tags like `https://google.com`.

**Comment by Betree** [comment]
@gustavlrsn We should also allow accents and many other special characters for proper internationalization. Taking French as an example, these tags would be valid: `#français`, `#algèbre`, `#hôte`, `#noël`. And there are [many more](https://github.com/opencollective/opencollective/issues/5916) if we want to cover different locales.

All things considered, if we do want to implement this kind of validation, I would go with a "block list" rather than a "allow list".

**Comment by gustavlrsn** [comment]
Closing this as https://github.com/opencollective/opencollective-api/pull/8462 was merged.
