### ISSUE TITLE
Retrieve user info to login

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#634]
Message from Austin:

> Hey Open Collective Team,
> 
> Recently merged a PR to Activate Open Collective (https://github.com/wonderkiln/CameraKit-Android), but I am a bit lost as to how to ‘manage’ the Open Collective page and account as none of the emails I would normally login with seem to be associated with the account, nor do I see a Github login.
> 
> Any help would be appreciated, as currently I have no idea how to edit the Open Collective page.

I asked the user for the collective's URL, still waiting for his response. We might be able to look it up as CameraKit-Android

**Comment by nicobarretoOC** [comment]
Here is the Collective's URL: https://opencollective.com/CameraKit-Android

**Comment by piamancini** [comment]
done and answered

**Comment by itsjavi** [comment]
@piamancini I have the same issue, seems that when I connected with Github to apply for a project, Open Collective created another separated account that I don't have access to, probably because the Github public email was used, which is a `@users.noreply.github.com` :( . I also asked in Slack in support it but no response yet.

**Comment by piamancini** [comment]
hi @itsjavi yes I fixed it for you, you had that problem. you can now use your gmail. let me know how it goes.
