### ISSUE TITLE
CSS issue pop up actions menu (regression)

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#6429]
https://opencollective.com/xr-belgium/contribute/brussels-red-rebel-brigade-52129

<img width="1106" alt="Screenshot 2023-02-17 at 11 04 46 AM" src="https://user-images.githubusercontent.com/74358/219614695-9c7b8a48-9db8-4504-9654-4ef792be1f45.png">

Looks like a regression of #4403 

It works on Chrome though: 
![Screenshot 2023-02-17 at 11 10 47 AM](https://user-images.githubusercontent.com/74358/219615609-c368e08c-43d3-4bec-b735-e8645bc988b9.png)

**Comment by xdamman** [comment]
(I feel for you, those browser specific CSS issues are a pain, reminds me of the good old days where we had to support Internet Explorer 4, that was something!) 🙃

**Comment by Betree** [comment]
> (I feel for you, those browser specific CSS issues are a pain, reminds me of the good old days where we had to support Internet Explorer 4, that was something!)

90% of the browser-specific issues we've seen these last few years on OC were for Safari. Safari definitely is the new IE!

Regarding the issue itself, the tier page somehow has its own stickiness implementation, maybe because it was implemented before the latest navbar. It doesn't make much sense to have a different behavior there; I'm gonna try and deprecate this in https://github.com/opencollective/opencollective-frontend/pull/8649.

Thanks for the report!
