### ISSUE TITLE
Add Support for `COLLECTIVE_MEMBER_CREATED` for Slack/Discord notifications

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6482]
Related to https://opencollective.freshdesk.com/a/tickets/170615

Investigating out webhook notifications it seems that we don't send any notification for the `COLLECTIVE_MEMBER_CREATED` activity anymore.

**Comment by Betree** [comment]
To make it clear, the issue only affects Discord & Slack right?

**Comment by SudharakaP** [comment]
> To make it clear, the issue only affects Discord & Slack right?

Correct. Sorry missed mentioning that in the original post.

**Comment by josesimoes** [comment]
Hi, 

Since my comment on the PR opencollective/opencollective-api#8608 hasn't had any reply I'm re-posting it here.

Thank you for the quick fix. However I have a concern: this hook used to generate a more meaningful message which included the contribution amount. This is something that's pertinent to the announcement of a new contributor joining the open collective.
If there is no interface to customize the message, I suggest this is added to the default message.

For reference this is how it used to look like:

![image](https://user-images.githubusercontent.com/1881520/221951054-f154cc93-6ae4-4bfa-b73b-5a90b1766880.png)

Which later evolved to:

![image](https://user-images.githubusercontent.com/1881520/221951170-bc0d88f6-8914-412d-91ac-a0c21186076e.png)


>>>>>>>>


Just today we've received a new contribution on the collective and this is how it looks on Discord:
![image](https://user-images.githubusercontent.com/1881520/225565800-7a552c50-edfe-4709-b91b-b69ca0fdb516.png)


Any chance you can improve this please?

**Comment by SudharakaP** [comment]
> Hi,
> 
> Since my comment on the PR [opencollective/opencollective-api#8608](https://github.com/opencollective/opencollective-api/pull/8608) hasn't had any reply I'm re-posting it here.
> 
> Thank you for the quick fix. However I have a concern: this hook used to generate a more meaningful message which included the contribution amount. This is something that's pertinent to the announcement of a new contributor joining the open collective. If there is no interface to customize the message, I suggest this is added to the default message.
> 
> For reference this is how it used to look like:
> 
> ![image](https://user-images.githubusercontent.com/1881520/221951054-f154cc93-6ae4-4bfa-b73b-5a90b1766880.png)
> 
> Which later evolved to:
> 
> ![image](https://user-images.githubusercontent.com/1881520/221951170-bc0d88f6-8914-412d-91ac-a0c21186076e.png)
> 
> > > > > > > > >
> 
> Just today we've received a new contribution on the collective and this is how it looks on Discord: ![image](https://user-images.githubusercontent.com/1881520/225565800-7a552c50-edfe-4709-b91b-b69ca0fdb516.png)
> 
> Any chance you can improve this please?

Thanks for pointing this out and sorry I missed your previous message on the PR. I've opened a new issue https://github.com/opencollective/opencollective/issues/6570 to keep track of this.

**Comment by josesimoes** [comment]
@SudharakaP no problem! It happens.
