### ISSUE TITLE
Wrong expense description in approval email (but correct expense title)

### ISSUE THREAD

**Issue by mkurz** [opencollective/opencollective#6493]
Like every 1st of the month I received my "_Your recurring expense ... was drafted_" email.
So I clicked on the blue "_Review and Submit_" link in the email and changed the "expense title" and the "description" so it contained March instead of February (makes sense no? :wink:). After saving and approving the expense myself, I received an confirmation email with the title "_Your expense to ... has been approved_". However in the email the old description is still used (the one which originally was used in the recurring draft):
<kbd><img width="400" src="https://user-images.githubusercontent.com/644927/222098249-46f2e66e-66a9-4e48-a2cd-6e3abf14100c.png" /></kbd>

It should be written "...March..." instead however.
The expense however shows the correct description: https://opencollective.com/playframework/expenses/125641

It should also be mentioned that the email however contains the correct expense title in its first line:
<kbd><img width="600" src="https://user-images.githubusercontent.com/644927/222098745-4879c9b1-b847-4544-8a90-334a6879d96d.png" /></kbd>

**Comment by Betree** [comment]
@mkurz Thanks for documenting the issue, the root cause it easy to track: In https://github.com/opencollective/opencollective-api/blob/9087b3e676dfb817f97371cf5f60878f24609f50/server/models/Expense.ts#L114, we're loading expense items from `data.items` first. For recurring expenses, this contains the data of the last created expense.

We could fix this by having `expense.getItems()` first, but `data.items` should arguably be removed (as well as all "draft" fields) as soon as the recurring expense gets completed. @kewitz would that make sense?
