### ISSUE TITLE
Cancelled Orders with `isActive` subscription

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6509]
```
SELECT *
FROM "Orders" o
INNER JOIN "Subscriptions" s ON o."SubscriptionId" = s.id
WHERE s."isActive" IS TRUE
AND o."status" = 'CANCELLED'
```

Looks related to PayPal in most cases.

**Comment by Betree** [comment]
No cases yet but it looks like this can happen with disputes:
- https://github.com/opencollective/opencollective-api/blob/f73119dc179e383dc2729203e7e46c2bb045bd7b/server/paymentProviders/stripe/webhook.ts#L409
- https://github.com/opencollective/opencollective-api/blob/f73119dc179e383dc2729203e7e46c2bb045bd7b/server/paymentProviders/stripe/webhook.ts#L581

**Comment by Betree** [comment]
Actually, this is the expected behavior: we're now handling PayPal cancelations asynchronously in many cases. To achieve that, we mark the order as cancelled then the [`cron/hourly/70-cancel-subscriptions-for-cancelled-orders.ts`](https://github.com/opencollective/opencollective-api/blob/420481ed914cd2133cd1820f1e318281cb4100ff/cron/hourly/70-cancel-subscriptions-for-cancelled-orders.ts#L55) job picks them up for actual cancellation.

However, it looks like the job has been failing lately, probably because of an issue with OCNZ that I wanted to investigate this week but wasn't able to due to their PayPal account being protected behind a 2FA sms.

![image](https://user-images.githubusercontent.com/1556356/222767869-d512bd3b-607f-4548-b5d3-21c286c490fd.png)

I'll check that and will improve the script to make sure it continues if one cancellation fails.
