### ISSUE TITLE
Show Projects in Manage Contributions page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6538]
Related to https://opencollective.freshdesk.com/a/tickets/172955

Currently we are not displaying projects within the managed contributions section (only Organizations and Collectives are displayed). Therefore if the a project is used as a payee of a recurring contribution there's no way to cancel that contribution.

**Comment by Betree** [comment]
> Currently we are not displaying projects within the managed contributions section (only Organizations and Collectives are displayed). Therefore if the a project is used as a payee of a recurring contribution there's no way to cancel that contribution.

To phrase it differently since I had some difficulty to understand initially: when a project is used as the ~~payee~~ contributing profile for a recurring contributions, it does not appear in the left column on https://opencollective.com/manage-contributions.

Note that it works when accessing the URL directly, we only need to link it in the menu: https://staging.opencollective.com/:projectSlug/manage-contributions
