### ISSUE TITLE
System should not suggest unusable slug

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6620]
If you use an org name that's too long when creating an org, the system will automatically suggest a slug that it won't accept. It should truncate system-generate slugs to the allowed character limit.

<img width="495" alt="Screen Shot 2023-03-31 at 11 38 08 AM" src="https://user-images.githubusercontent.com/5498878/228979127-1af6877e-70b2-4d66-949a-274aca351a22.png">

**Comment by Betree** [comment]
This needs to be added in: https://github.com/opencollective/opencollective-frontend/blob/8d3db5b0d3964fd4662d59c8262c244e8c26e896/lib/collective.lib.js#L92. I suggest using `lodash`'s `truncate`, but if you feel fancy you can try and implement something to figure a better behavior and try to truncate on dashes:
- `aaaaa-bbbbb-ccccc-ddddd-eeeee-fffff` -> `aaaaa-bbbbb-ccccc-ddddd-eeeee`
- `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` -> `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`

Then we'll need to update https://github.com/opencollective/opencollective-frontend/blob/8d3db5b0d3964fd4662d59c8262c244e8c26e896/components/CreateOrganizationForm.js#L149 to use this common  `suggestSlug` helper rather than then one manually defined there.

**Comment by RaunaqChawhan** [comment]
Hi @Betree , I'd like to work on this.

**Comment by RaunaqChawhan** [comment]
Hi @Betree / @alanna , could you please assign this to me?

**Comment by RaunaqChawhan** [comment]
Hi @Betree , I've raised the following pull request for this issue: https://github.com/opencollective/opencollective-frontend/pull/8801
