### ISSUE TITLE
Expense Flow: Incomplete side-effects

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#6698]
Update the side-effects of Incomplete expense updates:

- [x] When Expense or its items value or description change: automatically move it to Pending and email Collective admin.
- [x] When only Payout information is updated, move it to Approved for fiscal host admin to pay.
- [x] When the author comments on the expense, move it to Approved for the fiscal host admin to reply.

**Comment by Memo-Es** [comment]
I don't think it's ok to approve an expense after only a comment by the submitter. It can be a question or request for further clarification ([Exhibit A](https://opencollective.com/design/expenses/106939#new-comment-on-expense)).
I am pushing here again to create the "assign" action because then it's clearer that when an expense submitter answers using the comments, it gets back on the tray of the fiscal host admin chores. @kewitz @iamronen

**Comment by kewitz** [comment]
@Memo-Es the problem with assign is that it not only gets the ball back to the fiscal host but also starts to get into work balancing host admins. I would really like to keep the work balance out of our scope for now because this generates a whole new set of problems.

The suggestion for setting it back to approved is to convey the idea that the expense should be checked by any available host admin if it is for paying for the expense or just replying to any further questions from the payee.
