### ISSUE TITLE
Organizations lost address?

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6754]
I went to submit an expense to OCF from Protozoa and noticed the Protozoa organization's address was somehow deleted, despite being saved in the system for a long time and used many times before. Then I checked some other org profiles I use and it seems all their addresses may have been deleted. These are orgs where I'm sure there was an address saved previously. Additionally when I went to Protozoa's settings to re-add the address there seems to be nowhere to input it on the info tab in settings. Where are orgs supposed to save addresses and where did their previously saved addresses go?

**Comment by Betree** [comment]
@gustavlrsn can we check if it's related to https://github.com/opencollective/opencollective-api/pull/8626? The profile is https://opencollective.com/protozoa

**Comment by gustavlrsn** [comment]
@Betree Yep, what seems to have happened is that the migration script picked up `null` from `collective.data.address` and putting that into the new `location.structured` field as the string `null` (and skipping to migrate `collective.address`). About 1137 Collectives are affected (out of which 78 have since updated their address).

I'll create another migration to migrate these since we still have the original fields.

@alanna the address field was changed to an autocompleting location input in https://github.com/opencollective/opencollective-frontend/pull/8719 - which will save a structured address that will be used in the expense flow. I think it's worth considering how well that autocompleting input works for the use case when you only want a complete mailing address.

**Comment by gustavlrsn** [comment]
Closing this as fixed in https://github.com/opencollective/opencollective-api/pull/8968
