### ISSUE TITLE
Onboarding flow for new hosts

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#679]
1. Create a collective for your association/meetup/opensource/etc.
2. Start uploading expenses or create events
3. To activate paid tiers/tickets, you need a host
3.1. Connect a stripe account: as an individual or as an organization
3.2. Apply to an existing host (we should explain the cost/benefit of it) (v1: email to us)

**Comment by xdamman** [comment]
@cuiki would be good if you could come up with some mocks for this. Remember, we discussed this flow together on the whiteboard in Guadalajara.

**Comment by piamancini** [comment]
We have this doc that shows what happens today manually and what would be ideal to see https://docs.google.com/document/d/1cmuZBfSeIFr2O-zcRC1BNpKJ1sw3YjEqO44JT5jjz_8/edit#

**Comment by cuiki** [comment]
Hey, ok cool. 

@xdamman this is the image I have of what we went through in the board. Do you have any pics different from this?

![img_0106](https://user-images.githubusercontent.com/981188/33588224-70878e48-d937-11e7-9bb1-fe5542bb87f6.JPG)

**Comment by cuiki** [comment]
Hi everyone.

In order to fully understand how this flow plugs into the OC site, I made this general flow. It is not finished (the flows for the collective page is pending), but the flow that describes the creation of new collectives and applying to get hosted or self-host is there. I based the flow on the document @piamancini shared, what we went through here in GDL, and the questions Nico and I addressed.

I am also moving the design process to InVision. It is easier and better than Zeplin's feedback process.

Please review and let me know if it makes sense. Leave comments for what needs to change, removed, or added:
› https://invis.io/UQF0FK26S#/269849583_01-General-Flow-2x

**Comment by cuiki** [comment]
Hi @xdamman , @asood123 , @piamancini and @nicobarretoOC. Here is the latest update to the general flow. This update shows some questions that I addressed with Nico and Aseem. Please check this carefully! I need your approval of this flow to move on to designs.

Flow: https://invis.io/UQF0FK26S#/269849583_01-General-Flow-2x
— Leave comments in there if you need to.

**Comment by nicobarretoOC** [comment]
**Meeting with Cuiki notes:**

- Will people still be able to donate directly to a host so they can then distribute to a collective?
    - (This can be solved in short term by creating a collective that represents the host.)
- If in theory you can already apply to be hosted in the host page, why don’t we just create a host directory and link it to the process so people can discover hosts?
- On Fiscal Host profile page, the button “Apply to create a collective” should be changed to a “apply to be fiscally hosted” and you have 2 options:
    - Create a new collective
    - Use existing collective
        - Are you an orphan collective?
        - You want to switch fiscal Host?
            - We are self hosted
            - We had a final host
- Shall we create a flow for organizations that want to host/become a fiscal sponsor?

**Comment by xdamman** [comment]
Looks great!

**Comment by cuiki** [comment]
@xdamman, @piamancini, @asood123 

Any notes to this? Should I continue on wireframes/mocks?

**Comment by piamancini** [comment]
this looks deprecated now because of self-serve flow. Please confirm and close.
