### ISSUE TITLE
Wrong GST amount charged on transactions

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6868]
These two contributions were made with GST, but the amount of GST recorded is not the correct 15%, it appears to be half.

https://opencollective.com/halaw-auckland-1st-of-june-cb686160/contributions/657023

https://opencollective.com/halaw-wellington-24th-of-may-f2a217c5/contributions/657011

**Comment by alanna** [comment]
We have manually corrected these for our upcoming GST return, but it would be great if they could be corrected in the database for the future. From what I can see the correct amount in total, including GST, was charged to the buyer, it just was incorrectly recorded in `tax amount`.

**Comment by Betree** [comment]
Looked for other cases but found none; these transactions were part of the bug where the quantity was not considered when calculating taxes (ordering two tickets only charges for the GST of the first one). 
The root cause was already fixed; I've manually fixed the 2 transactions.

<details><summary>Details</summary>
<p>

```sql
select
  ROUND(amount::float / 1.0 + ((data -> 'tax' ->> 'percentage')::float / 100.0)) as expected_gross,
  amount + "taxAmount" AS actual_gross,
  ROUND((amount::float / (amount + "taxAmount"))::numeric, 2) AS actual_tax_rate,
  data -> 'tax' ->> 'percentage',
  *
from "Transactions" t
where "taxAmount" IS NOT NULL
AND "taxAmount" < 0
AND type = 'CREDIT'
AND currency = 'NZD'
AND ROUND((amount::float / (amount + "taxAmount"))::numeric, 2) != 1.0 + ((data -> 'tax' ->> 'percentage')::float / 100.0)
AND "deletedAt" IS NULL
```

</p>
</details>
