### ISSUE TITLE
Paying expenses puts collective in negative balance

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#688]
Two expenses (eid: 2276 and 2288) paid out on 24th put /playworkskerryproject (cid: 936) in negative balance. That shouldn't be allowed.

They are real paypal transactions, so actual money got paid out - more than we think the host had for that collective.

**Comment by asood123** [comment]
Missing transactions for paid expenses (where Payoutmethod is not paypal) that I added via script are from tId: 47047 to 47064. None of them are for this collective.

**Comment by xdamman** [comment]
I've set expense id 2276 back to approved and tried to pay it again as "other" locally and I got the right error message
![](https://cl.ly/223t0F2u1q46/Screen%20Shot%202017-11-28%20at%205.42.59%20PM.png)

Same when trying to pay with PayPal as the payout method:
![](https://cl.ly/1s3Y1z403x2V/Screen%20Shot%202017-11-28%20at%205.46.45%20PM.png)

Can we ask the host what was their process?

**Comment by asood123** [comment]
Does the UI allow clicking "Pay" on multiple expenses at the same time?

**Comment by xdamman** [comment]
Mmmm... that's probably the issue. If two requests come at the same time, and because it takes time to process them, the balance doesn't have time to update.

A short term solution would be to avoid allowing that on the frontend but really this should be solved at the API level. We need some form of a lock on a collective ledger, or create a pending transaction.

Maybe better:
- Directly create the DEBIT transaction (remove $100 from collective to pay expense)
- Process the payout, if another payout requests comes in, the balance check will already take into account previous transaction currently processing in parallel
- On success: proceed as normal, i.e. add CREDIT transaction to the user account
- On error: add CREDIT transaction to the collective account to cancel the DEBIT

Might just look a bit ugly if there are a lot of errors.
Any thoughts?

**Comment by asood123** [comment]
Thinking more about it, I don't think we need anything fancy here for now. Paying expenses is a Host's responsibility - same person who has access to the bank account (pretty much in all cases anyway). Not much incentive for that role to take advantage, since it's their money to begin with. 

I think a frontend fix for now would be fine. Though looking at the frontend code, that doesn't seem trivial either...

**Comment by asood123** [comment]
Something like this might work: https://github.com/opencollective/frontend/pull/128

**Comment by asood123** [comment]
@xdamman are you working on this? otherwise, let's merge the temporary fix.

**Comment by asood123** [comment]
Fix merged, going out shortly.
