### ISSUE TITLE
Links to Updates not pulling through data to Social Media

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6938]
When I post this link https://opencollective.com/tauiwi-tautoko/updates/new-training-for-tauiwi-pakeha-oct-nov

on Twitter or other social media, this is how it looks:

<img width="588" alt="Screen Shot 2023-08-15 at 12 35 39 PM" src="https://github.com/opencollective/opencollective/assets/5498878/dbb75770-6748-4ad5-a4e2-453acfa642a1">

It should be pulling through at least the Update title and ideally the first few lines of the text. Otherwise it's not very inviting to click through and hard to share online.

**Comment by kewitz** [comment]
This problem is fixed on the Update pages. Keep in mind that Twitter caches this meta-data on their side, which means reposting "https://opencollective.com/tauiwi-tautoko/updates/new-training-for-tauiwi-pakeha-oct-nov" may not work. But things are definitely working for pages that were never linked:
![image](https://github.com/opencollective/opencollective/assets/2119706/4dcc9c3a-1a82-4a1d-964f-2a61779de8ec)

On another note, the same problem is affecting several other pages, which are going to be refactored to address this issue. Thanks for reporting, Alanna!
