### ISSUE TITLE
Chart of Accounts for Fiscal Hosts

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#7026]
## User story 
> A chart-of-accounts is a set of accounting categories that fiscal hosts use in accounting practices to sort and aggregate transactions. For years the platform has tried to address this using expense tags but this has proved itself to be an unsuitable solution

## Best solution for this problem
Enable fiscal hosts to specify a chart-of-accounts they use on the platform. The chart-of-accounts will be a fiscal host dashboard tool. 

Enable fiscal hosts to optionally indicate for each accounting category in the chart of accounts:

1. A technical name. 
2. A user friendly name (which by default is the same as the technical name).
3. An accounting code (which associates the on-platform accounting categories with off-platform accounting categories). 
4. Whether or not it applies to expenses.
5. Whether or not it applies to contributions.
6. Whether or not it can be used by other users (namely: expense submitters and collective admins) to assign expenses to it in the expense submission flow. 
7. Provide specific instructions to users about submitting expenses to it.    

[Coda reference](https://coda.io/d/_dnHLKv7oLV0#Projects_tusx8/r128&view=modal)

**Comment by poohlaga** [comment]
Not sure which is the source of truth (github or coda) so I made a comment in coda about flat structure vs. hierarchy for chart of accounts

**Comment by poohlaga** [comment]
Also made a note there about the MVP having only one category per transaction and to ensure this is taken into account for any offline workaround or reporting needs. I think this is more critical for OCF

**Comment by Betree** [comment]
The specs posted in https://github.com/opencollective/opencollective/issues/7028#issuecomment-1754732487 also cover this issue.

**Comment by Memo-Es** [comment]
### Design update

After a couple of design rounds:
 - [Round 1](https://www.loom.com/share/1f412c31f45b4ee6b19ba25bf50f9f2d?sid=f48b61b5-6c21-4f1a-b870-1f7675e52549)
 - [Round 2](https://www.loom.com/share/11750808cf1049a09807d14955dc057f?sid=7c3ce05f-2281-4b5b-95f5-e68ba730d029)

This is the version we ended up with:

| Chart of Accounts Settings Page | Create Account Category | Overview Account Category |
|---------------------------------|-------------------------|---------------------------|
|           ![Image](https://github.com/opencollective/opencollective/assets/49539954/8037de1e-e096-4205-832e-1e3f3f6680e9)                      |            ![Image](https://github.com/opencollective/opencollective/assets/49539954/908935b9-3314-4efa-b37f-53443fe49b06)             |          ![Image](https://github.com/opencollective/opencollective/assets/49539954/35ae9bf4-3563-46cf-bb7a-d44f0e5b0250)           |

**Accounting categories details**
 - Chip-based design. It is easy to tell one item apart from another. Easy to place in a different instance of the dashboard.
 - We display the code number first, then the main "category chip". On the far right side, the "flag indicator" plus the "actions" button
 - The "flag indicator" shows whether a category has enabled submission through expenses or not, with the label "Expense submission" and a cross icon for the negative, and a checkmark icon for the positive
 - The "category chip" is colored in a different hue from the feedback ones (main blue, red, green) for it to stand out from the expense management side of the dashboard for host admins, collective admins, and submitters alike
 - The "category chip" displays the "friendly name" only when it is different; otherwise, it remains hidden.



![Image](https://github.com/opencollective/opencollective/assets/49539954/9080d2a2-2932-4377-905c-f9a7d7efbadf)

**Comment by Betree** [comment]
We've achieved all the required parts for this project. Follow-up issues:
- https://github.com/opencollective/opencollective/issues/7100
- https://github.com/opencollective/opencollective/issues/7053
- https://github.com/opencollective/opencollective/issues/7087
