### ISSUE TITLE
Implementing an Expense Categorization process

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#7028]
## User story 
> The different legal environments in which fiscal hosts operate present fiscal hosts with different accounting and reporting requirements. Expenses (how money is spent and what it is spent on) play a central role in validating that a fiscal host is aligned with its mission and is meeting its legal requirements. At the end of every year (and during audit events) fiscal hosts need to be able to clearly and reliably demonstrate that the expenses they’ve paid are legitimate and aligned with their mission. 

### Scope 1:
Implement a process of categorizing expenses that distributes this effort across the users involved in expenses: expense submitters, collective admins and fiscal host admins. The relevant accounting categories will be extracted from #7026 .
1. Expense submitters - Expense Submission
    1. Expense submitters will be required, in the expense submission flow, to select one accounting category to which the expense is related. This means that in cases where, for example, an expense submitter is asking to be reimbursed for a receipt whose line-items span numerous accounting categories, the expense submitter will need to submit separate expenses. When submitting an expense, an expense submitter can also select “I don’t know” as the expense category. 
    2. When adding line-items to an expense the expense submitter needs to be made aware of the selected accounting category so that they can make sure that the line-items being added are aligned with the selected expense accounting category. 
2. Collective admins  - Expense Approval: collective admins will be required to review the expense category. The user experience should make this requirements explicit, for example:
    1. The expense category selected by the expense submitter is shown to the collective admin.
    2. The collective admin, as part of the approval process, HAS to re-select an accounting category, even if it is the same accounting category selected by the expense submitter. 
    3. The collective admin CANNOT click on the approve affordance of an expense without explicitly selecting an accounting category.
    4. The collective admin can also choose “I don’t know” as an expense category.
    5. The expense accounting category is updated to the accounting-category selected by the collective admin.
3. Fiscal host admins - Expense Payment: fiscal host admins are (legally) required to review the expense category:
    1. The selected (by the expense submitter or collective admin) expense category should be shown to the fiscal host admins.
    2. They should be able to change it.  
    3. The fiscal host admin is required to choose a valid accounting category. They cannot choose “I don’t know” as an expense category.
    4. If a fiscal host admin selects an accounting category different than the one selected by the expense submitter or collective admins, an email is sent to both the the collective admin and expense submitter indicating this. The email should be worded as guidance/training so that future expense are correctly submitted.

### Scope 2
Add the expense accounting-category to the CSV exports.  

### Scope 3 

Import the off-platform expense categorization results that the OCF team has been performing manually for 2023.

[Coda reference](https://coda.io/d/_dnHLKv7oLV0#Projects_tusx8/r129&view=modal)

**Comment by Betree** [comment]
# Technical specs

These specs are covering both this issue and https://github.com/opencollective/opencollective/issues/7026.

**Tension about naming**

There is tension on whether we should name this new concept “Chart of Accounts” or “Transaction Categories” in our codebase. While the first is more accurate from an accounting perspective, it wouldn’t match our other models. It could create some confusion around the potential link with “Accounts” (aka. Collectives/Organizations/...etc). 

On the other hand, “Transaction category” could create some confusion around how it relates to “Transaction kind”.

## API

* Create a ChartOfAccounts table
  * `code` (string, required)
  * `name` (string, required)
  * `friendlyName` (string, optional) - an alternative name to expose to non-accountants (i.e. expense submitters and collective admins)
  * `type` ([EXPENSE, ASSET, LIABILITY,REVENUE,OTHER], required) the account type. This is used in accounting and will help to decide where this the account needs to be surfaced. This will be set to EXPENSE for all entries in the first release.
  * `HostCollectiveId` (foreign key, required)
  * Unique index on (code, `HostCollectiveId`)
* On the Expenses table, add a `ChartOfAccountId` column (foreign key, optional)
* In GraphQL, expose the chart of accounts publicly (since expense submitters will need to access it) under host.chartOfAccounts.
* Add mutations to manage the chart of accounts; depending on the design:
  * Either a `editChartOfAccounts(host, chartOfAccounts)` mutation
  * `addToChartOfAccounts` / `removeFromChartOfAccounts` / `editChartOfAccount` 
* Add a new policy for “Expense submitters and collective admins participate in expense categorization”
* In createExpense/editExpense mutations, add support for a `ChartOfAccountReferenceInput` argument that will be stored in `ChartOfAccountId`. Check policies to make sure remote user is allowed to change the category.
* When a fiscal host admin edits an expense to select a different chart of accounts, email the expense submitter to inform them about the change (for education purposes).

## Frontend

_Frontend Specs to be edited/completed based on the actual design_

* In the Host Workspace > Policies, expose a toggle for  “Expense submitters and collective admins participate in expense categorization”.
* In the Host Workspace, add a new “Accounting” entry in the menu. The only category for now will be “Chart of accounts”, to let host admins edit their chart of accounts.
* Add support for selecting the chart of accounts in the expense flow.
* Find a way to let host admins re-categorize an expense after it has been paid

**Comment by Betree** [comment]
@iamronen I like this suggestion, `AccountingCategories` clarifies everything.

**Comment by Memo-Es** [comment]
### Week 3 update
 - [ ] Add categorization to the expense submission flow (Design)
 - [ ] Add "Accounting" section to Fiscal Host Dashboard

**Comment by Betree** [comment]
For this week:
- [ ] Merge & deploy https://github.com/opencollective/opencollective-api/pull/9390
- [ ] Cleanup, merge & deploy https://github.com/opencollective/opencollective-frontend/pull/9467 behind a feature flag

**Comment by Memo-Es** [comment]
### Week 4 update
 - [x] [Add "Accounting" section to Fiscal Host Dashboard](https://github.com/opencollective/opencollective/issues/7059#issuecomment-1767694682)
 - [x] [Process for Fiscal Host to categorize expenses from the payouts tool (Expense pipeline)](https://www.loom.com/share/e1db97c7b8f949d09566c143730dd546?sid=4a9c70de-aa14-4ea0-9595-b56a7d50bb4d)
 - [ ] Add categorization to the expense submission flow (Design)
 - [ ] Approval process for Collective admins

**Comment by Betree** [comment]
This week:
- [ ] Merge & deploy https://github.com/opencollective/opencollective-api/pull/9411

**Comment by Betree** [comment]
This week:
- [ ] https://github.com/opencollective/opencollective/issues/7052 (frontend)
- [ ] Surface the accounting categories in the expenses lists

**Comment by Memo-Es** [comment]
### Design results

[ - Fiscal Host Admins](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21943-10077&mode=dev)
[ - Collective Admins
](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21943-10078&mode=dev)  [ - Expense Submitter](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21943-10079&mode=dev)

@Betree

**Comment by Betree** [comment]
Added some specifications for the latest design proposal to show an edition history for the field:
- https://github.com/opencollective/opencollective/issues/7090
- https://github.com/opencollective/opencollective/issues/7091

**Comment by Betree** [comment]
This week:
- [ ] Finish https://github.com/opencollective/opencollective/issues/7089 by showing accounting categories in non-admin expenses list.
- [ ] https://github.com/opencollective/opencollective/issues/7091
