### ISSUE TITLE
Unexpceted error after saving editet tiers

### ISSUE THREAD

**Issue by shtefcs** [opencollective/opencollective#708]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: https://opencollective.com/wireflow/edit#tiers
Logged in as: (https://opencollective.com/kinder)
Error message if any: Not found
Expected result: to save changes (acutally it does saved)
Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)

Bonus point if you can add a screenshot :-)

https://www.screencast.com/t/hnACfwG4Y

Just encountered this error/bug while tried to add/edit tiers 

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
thanks @shtefcs. We'll prioritize this tomorrow.

**Comment by shtefcs** [comment]
Take your time, since at the end it saved my changes.

**Comment by xdamman** [comment]
So the problem is that after we perform the mutation to add the new tier, Apollo is refreshing the `data` prop of the parent componentpages/editCollective.js`  without including `data.Collective` https://github.com/opencollective/frontend/blob/master/src/pages/editCollective.js#L34

Not sure how to handle this. Need to continue investigate.

**Comment by xdamman** [comment]
It's weird because it wasn't happening before. Not sure if it's a recent update of Apollo that changes that behavior.

**Comment by asood123** [comment]
Fixed.
