### ISSUE TITLE
Be able to see which email you used to create an account

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#709]
Message in Discourse:

There’s no way to see in your profile which email you’ve already registered with. That’s a bit bothersome when you’re requesting an invite but don’t know if you’ve got an account already or not.

**Comment by piamancini** [comment]
nico, are you following up with these users? replying to them on the forum?

**Comment by nicobarretoOC** [comment]
Yep!

**Comment by piamancini** [comment]
I agree. The email only access is quite a pain. Specially since github surfaces nonreply emails for maintainers all the time. 
I prefer it to passwords, but it should be improved and also be an opt-out.

**Comment by cuiki** [comment]
I believe this means that there is no place to view or even edit the email address a user signed up with. I think this needs a two-step solution to fix first the immediate issue of visibility, and then the issue of being able to update the email of a user's OC **personal account.**

First, there is one place we can provide this info quick and easy way. Just so users can see the email address they signed up with. Thats the user pop-out menu: In the past I did a version for it that included the email but it was never built. Then @HipsterBrown did a newer version where I had not included it there because it was just an improvement to solve the confusion of creating new orgs vs collectives from there.

I've added it now to the newer version in FIGMA and we can either do that in a quick fix or try to slightly update the design of this pop-out menu to better include this info, basically building the first version of this menu.

You can see them here: https://www.figma.com/file/JZxZiavpekMXjSL5dFB66BS6/design-system-%E2%80%94-02-molecules?node-id=0%3A1716

Regarding the editing part, I think we should allow this in the users' settings, but perhaps this touches other parts on the engineering side that need to be discussed, regardless, we must provide the users a way to update this.
