### ISSUE TITLE
Improve inline documentations for OAuth and Personal Tokens

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7125]
For both OAuth and personal tokens, we're displaying some docs on the "For developers" page:

![image](https://github.com/opencollective/opencollective/assets/1556356/68650dca-8d6f-414b-b6af-83e8c8a6350d)

But as soon as you actually create one, you're redirected to the single App/Token's page, and there's no more docs in there:

![image](https://github.com/opencollective/opencollective/assets/1556356/56044064-9eae-44cf-838a-b08ad72f9c8b)

The issue is: it's actually at **this** stage that you need the documentation the most, since the next thing for you to do is to copy-paste the token to the tool/software that you're using, so you need the header's name.

**Comment by Guilherme-NL** [comment]
@Betree, the idea behind this issue is to place the same information from "forDevelopers" on the page to which we are redirected when creating an OAuth Token/App? For example, on the Token page, I will incorporate a header with the following information:

"Personal tokens are used to authenticate with the API. They are not tied to a specific application. Pass it as Personal-Token HTTP header or personalToken query parameter in the URL. check [our documentation](https://docs.opencollective.com/help/developers/personal-tokens)."
