### ISSUE TITLE
Donation Receipt Appears in Host Currency Instead of Collective Currency

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7127]
**Describe the bug**

It seems that for certain collectives in the platform such as this one, https://opencollective.com/bitcoin-design-foundation where the collective currency is EUR and the host currency is USD, all the donation receipts seems to appear in USD while the numeric amount is in EUR. For example here's a sample receipt;

![image](https://github.com/opencollective/opencollective/assets/12435965/e2c4ef31-2599-457d-9a3b-1ae2c43bfb3f)

This is for the contribution; https://opencollective.com/bitcoin-design-foundation/contributions/711594 which is in EUR. 

**To Reproduce**
1. Go to any contribution for a collective which is in a different currency than host
2. Download the receipt to see the discrepancy 

**Expected behavior**

The receipt should display the correct currency of the collective

**Comment by SudharakaP** [comment]
Reported at, https://opencollective.freshdesk.com/a/tickets/294190 and at slack; https://opencollective.slack.com/archives/C0429NTTABF/p1700732375681179

**Comment by Betree** [comment]
I'm going to fix the root cause for this issue in https://github.com/opencollective/opencollective-pdf/pull/973. The PR also ships a fix to make sure we always retrieve the host from the transaction rather than `account.host`, as the host may have changed since the transaction was made.

The idea of displaying receipts in the collective's currency requires some more thinking: we've always displayed this document in the host currency (with the original amount/exchange rate displayed in the table). I'm afraid we could break some host's expectations if we switch this; i.e. are all hosts allowed to generate invoices in a different currency?
