### ISSUE TITLE
Add Interweave library to render all rich texts on the platform

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7133]
See https://github.com/milesj/interweave (4.8kB, 1K stars)

> Interweave is a robust React library that can...
> - Safely render HTML without using dangerouslySetInnerHTML.
> - Safely strip HTML tags.
> - Automatic XSS and injection protection.
> - Clean HTML attributes using filters.
> - Interpolate components using matchers.
> - Autolink URLs, IPs, emails, and hashtags.
> - Render Emoji and emoticon characters.
> - And much more!

Why use it:
1. To automatically turn URLs for "regular text" into anchors (see https://github.com/opencollective/opencollective/issues/7126)
2. As a double safety on our rich text content (collective long description, update body, ...etc). While we do sanitize this content in the API, there's nothing checking the validity of the rich texts in the frontend at the moment. An attacker exploiting a model validation bypass or SQL injection could inject XSS exploits directly, and the frontend would run them blindly.

Downsides:
- It's likely slower than rendering directly
- If not configured properly, we may end up with discrepancies between the rich text editor and the rendered text

**Comment by gustavlrsn** [comment]
Looks like a nice library, makes sense with some double safety here and avoid the ominous `dangerouslySetInnerHTML`.

The aspects around auto-linking seems nice, and I see that it also can be set up to handle @mentions and #hashtags 👍

However, as you allude to around discrepancies between editor and rendered text, it's good to remember that for things like auto-linking and @mentions, we should ideally also have it implemented in the editor itself, so that it is obvious that a link is created automatically from a URL, without manually creating one etc, or that it's possible to create @mentions (if we choose to add that, I guess we need some notification support for those first)

And even if we implement those in the editor, it could still be nice to have another way to parse those elements when rendering, for example, the stored @mention in the text might include some reference to an account id (that we don't want to render, but we might use to swap out the slug if it has been changed or link to the right account when rendering)

**Comment by Betree** [comment]
> we should ideally also have it implemented in the editor itself, so that it is obvious that a link is created automatically from a URL, without manually creating one etc, or that it's possible to create @mentions

For rich text contents, absolutely (it's the case already).

For expense items, I wouldn't want to make it more complex than a simple text input for now. Auto-linking could nice to have in case someone drops a link in there, but we don't want to encourage any kind of formatting for this field. For example, we don't want people to add a link with a different text (like [this](https://google.fr)) because their final purpose is to be rendered inside (printable) PDFs.

> But even if we implement those in the editor, it could still be nice to have a way to parse those elements when rendering, for example, the stored @mention in the text might include some reference to an account id (that we don't want to render, but we might use to swap out the slug if it has been changed or link to the right account when rendering)

Indeed, the logic for building such mentions should rely on the rich text editor/API logic, like what we do today for (aliased) links and videos.

**Comment by gustavlrsn** [comment]
> For expense items, I wouldn't want to make it more complex than a simple text input for now.
Makes sense, didn't consider the simpler fields!
