### ISSUE TITLE
Host Dashboard section for Tax Forms (US)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7136]
Part of https://github.com/opencollective/opencollective/issues/7346

**Needs**
- Independent US hosts ([that are not connected to Dropbox forms](https://github.com/opencollective/opencollective/issues/6948)) also need a way to check who they need to send tax forms to.
- All fiscal hosts need a way to easily check a list of all the required tax forms for a given year, along with which ones are still pending. They need a way to [view the documents](https://github.com/opencollective/opencollective/issues/6863), [resend them](https://github.com/opencollective/opencollective/issues/6126), [mark them as "Not required"](https://github.com/opencollective/opencollective/issues/6225), [invalidate them](https://github.com/opencollective/opencollective/issues/7134) or [manually upload them](https://github.com/opencollective/opencollective/issues/4805).

**Solution**
1. Add a new dashboard section for US hosts called `Legal Documents` (if we want to be generic) or `Tax Forms` (if we want to keep it specific).
2. Show some filters: search by text, year (default=current)
3. Show a table that queries the list of all expenses that require a tax form (we do have such queries in Metabase) and returns a summary grouped by the payee, along with the submitted document link (if the host is connected to Dropbox Forms). We have a query like that in Metabase.
4. For each entry, add an action dropdown that will let us implement the aforementioned actions.
5. Add a button to export the results as CSV (accounting firms usually require a document like that)
6. Bonus: add a button to export a `.zip` with all the tax forms

![image](https://github.com/opencollective/opencollective/assets/1556356/47e85221-267b-4be1-93a2-7b9c9d1e8875)

**Comment by iamronen** [comment]
Some comments
1. I suggest discerning between two kinds of entities (at least from the user experience perspective). 
   - required tax forms
   - tax forms 
3. Perhaps the pipeline pattern can be used here for: Required, On Record, Expired/Invalid.
4. Is there going to be a drawer where a single tax form can be viewed and downloaded?
5. If there is going to be a drawer, it may be useful to show in it through which collectives a payee is getting paid. 
6. It can be useful to add to the context menu a link to "Expenses" for a given payee -> redirect to a filtered list of expenses (both paid and waiting to be paid).
7. It can be useful to add an indicator if a payee has expenses waiting to be paid that are blocked because of the missing tax form.
8. Clarify what country is being shown here? Country of residence of the Payee?
9. My understanding is that the downloads (both the CSV and the forms) is needed per fiscal year. If that is the case lets make sure that it is clear in the UX,
