### ISSUE TITLE
Tier validation: prevent setting a preset lower than the minimum amount

### ISSUE THREAD

**Issue by Abekonge** [opencollective/opencollective#7176]
When selecting free in a flexible tier.  The primary buttton `Your info` does not do anything.

**To Reproduce**
1. Go to https://opencollective.com/kollektiv-email/contribute/medlem-af-kollektiv-email-67109/checkout
2. Click on `Your info`
3. Nothing happens.

**Expected behavior**
Proceed with the flow.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 121.0 64bit

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Hi @Abekonge, it looks like you have the minimum amount for this tier set to `1`. We should add some validations to prevent this, but in the meantime you should be able to make it work by removing the minimum amount.

![image](https://github.com/opencollective/opencollective/assets/1556356/77fab9b9-79e6-428e-8071-b7f73798a30f)

**Comment by Abekonge** [comment]
> Hi @Abekonge, it looks like you have the minimum amount for this tier set to `1`. We should add some validations to prevent this, but in the meantime you should be able to make it work by removing the minimum amount.

Ah doh 🤦‍♀️, of course - good catch!  

I changed the title to lower instead of higher ...

**Comment by rdela** [comment]
@Betree the missing validation and silent error you mentioned above is an issue in the @lumeland collective “I use Lume often” tier as well. I emailed @oscarotero already so it may be fixed by the time you read this, but here are screenshots of the problem in action to illustrate how confusing it is…

[Lume’s](https://opencollective.com/lume) “[I use Lume often](https://opencollective.com/lume/contribute/i-use-lume-often-35668/checkout)” recurring contribution is set to a minimum contribution amount of $10, but the preset amounts are only $5 and Other.

Worse, the form does not tell you why it does not submit unless you select Other. If you leave $5 selected and click the Your info →  button, nothing happens. No error, nothing…as @Abekonge pointed out.

![Image](https://github.com/user-attachments/assets/620bbd9a-f23f-4bf5-9c50-f3026e926ccc)

Here I have selected Other: 

![Image](https://github.com/user-attachments/assets/c1943f41-aef5-4b8b-8ad7-c6ad81201bdd)

And here I have tried to submit the form with $5, and finally we see the error: “Please select a value that is no less than 10.” 

![Image](https://github.com/user-attachments/assets/45c906ca-3ebd-410d-9a24-4b114ed58028)

Yes, it should not be possible to have a preset contribution amount lower than the minimum, but also the form should show the error in all amounts, no matter which contribution tab is selected.

**Comment by Betree** [comment]
@rdela Thanks for the additional feedback, we're adding a bounty on this one.

:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $300 when the Pull Request is reviewed, accepted and merged.

**Expected delivery**
- The tier form (`/dashboard/collective/tiers` > "Edit Tier") should have frontend validations that don't let you submit it if one of the presets is lower than the minimum amount. A clear error message following standard patterns (either a toast or an inline error on the field) should be added.
- In the contribution flow (`components/contribution-flow/StepDetails.js`), if the amount selected is lower than the minimum, show an error above the amount picker (regardless of how the amount was set). Do not show an error if the custom amount input is empty.
![Image](https://github.com/user-attachments/assets/506c97a1-95b0-4264-989b-11c3fe03becc)


:arrow_right: [More info on the bounty program](https://docs.opencollective.com/help/developers/bounties)

**Comment by Myestery** [comment]
Hi @Betree 
If this is open, I'll like to work on it

**Comment by Betree** [comment]
@Myestery The issue will be assigned to you for the coming 3 weeks (can be extended upon request)

**Comment by Myestery** [comment]
> [@Myestery](https://github.com/Myestery) The issue will be assigned to you for the coming 3 weeks (can be extended upon request)

I submitted a PR [here](https://github.com/opencollective/opencollective-frontend/pull/10789) to fix it

**Comment by Betree** [comment]
:trophy: This issue has been completed by @Myestery  

To claim the bounty, please submit an invoice to https://opencollective.com/ofitech/expenses/new (please mention the issue number) and comment here with the expense URL once you've posted it.

We also added you to https://github.com/orgs/opencollective/teams/contributors/members. **Congrats!** :tada: You can now push directly to most Open Collective repos (only the `main` branches are protected).

_Note: we still need to merge & deploy the fix._

**Comment by Myestery** [comment]
I created the invoice here https://opencollective.com/ofitech/expenses/228118
