### ISSUE TITLE
PDF Service: Add support for OAuth tokens and Personal Tokens 

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7259]
Users integrating with our public API [want](https://opencollective.slack.com/archives/C4TC3AYDT/p1706616553173629?thread_ts=1700050277.925849&cid=C4TC3AYDT) the ability to download PDFs.

We could enable this in a few steps:
- [ ] On the PDF service, accept OAuth Tokens and Personal Tokens, make sure they get passed to the API
- [ ] (Bonus) On the API's `Transaction` & `Expense` objects, expose the PDF URL

**Comment by samuk** [comment]
Thanks @Betree my use case is;

Send the PDF and payment notification into Quickbooks via email to save these transactions having to be manually copied into the accounting software. 

It will save us several hours a week I think. 

Is there a way of prioritising this feature if we pay for it?

**Comment by Betree** [comment]
@samuk It might actually align with some priorities we're currently exploring.

@aerugo @kewitz, as part of https://github.com/opencollective/opencollective/issues/7182, did you identify the ability to download PDFs (contribution receipts, expense invoices, etc) as a requirement for reconciliation?

**Comment by kewitz** [comment]
@Betree we were using the GraphQL query directly. Ideally, we would refactor that pipeline to work on top of CSV exports because it is a public and standard file. We're still not sure how this reconciliation tool will be presented to the user.

One thing that we should take into consideration is the size of these exports and the time it takes to generate one CSV. We'll eventually need to consider asynchronous requests/responses for these reports, turning this into one mutation and one resolver instead of a single API call.

**Comment by samuk** [comment]
Thanks. My user need is certainly to be able to access the original .PDF files.

**Comment by samuk** [comment]
Any news on this one please?

**Comment by kewitz** [comment]
@Betree we haven't reached that point yet, there's no clear picture of what artifacts are necessary and how/where the reconciliation will happen.

@aerugo may have more information.

**Comment by Betree** [comment]
@kewitz Ok :+1: 

@samuk I'll personally take care of this issue. We want to allow it, and the change seems simple enough. We'll try to ship it in the coming two weeks.

**Comment by samuk** [comment]
Nice, thanks

**Comment by Betree** [comment]
Not released yet

**Comment by Betree** [comment]
@samuk We've released the feature; the PDF service now supports passing either a `Personal-Token` (for personal tokens) or an `Authorization` header (for OAuth). The endpoints are:
 - GET `https://pdf.opencollective.com/receipts/transactions/:transactionUUID/receipt.pdf`
 - GET `https://pdf.opencollective.com/expense/:expenseUUID/invoice.pdf`
 - GET `https://pdf.opencollective.com/receipts/collectives/:fromCollective/:host/:fromDate/:toDate/receipt.pdf`

We've documented them in https://docs.opencollective.com/help/contributing/development/api#pdf-service.

Let us know if you have any feedback!

**Comment by samuk** [comment]
Nice, thanks I'll give it a go

**Comment by YTSengul** [comment]
I am reaching out regarding an issue I encountered while retrieving data. Upon making a request, I received the following response:

`{
    "name": "BadRequest",
    "message": "Invalid expense id: *****",
    "status": 400
}`

Could you kindly provide me with further clarification on this matter? I have been utilizing my personal access token for authentication, and I can confirm its validity. Notably, when intentionally providing an incorrect token, the error response differs. Therefore, I am confident that the issue lies elsewhere.

Could you assist me in identifying the cause of this error and guide me on resolving it? Any additional information or troubleshooting steps you can provide would be greatly appreciated.

**Comment by Betree** [comment]
@YTSengul You're likely using a legacy expense ID (numerical, i.e. `4242`) instead of a GraphQL V2 `id` (uuid).

You can exchange them through GraphQL like this:

```gql
{
  expense(expense: { legacyId: 4242 }) {
    id
  }
}
```
