### ISSUE TITLE
About Section Video Embed Error

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7526]
**Describe the bug**

Starting recently the video embed seems to have stopped working and YouTube embeds are no longer possible to be added to the About section. 

**To Reproduce**
1. Go to any collective you administer
2. Go to the about section and try to add a YouTube video
3. Note that the video is not added properly and once you click on save the section cannot be edited anymore. 

**Expected behavior**

When adding the video the preview should be shown in the edit text area and once saved it should enable playing the video. 

**Screenshots**

[add-video-error.webm](https://github.com/user-attachments/assets/e0a1e23b-f113-46d6-8f1b-81a6d7f9da97)

**Comment by SudharakaP** [comment]
This issue was reported at, https://opencollective.freshdesk.com/a/tickets/363898

**Comment by Betree** [comment]
I'm looking at this as a priority

**Comment by Betree** [comment]
This was introduced in https://github.com/opencollective/opencollective-frontend/pull/10595, Trix v2.1.3 is not impacted by this issue. On top of fixing the root cause, the test in https://github.com/opencollective/opencollective-frontend/blob/1baa41c656a34dd90ad60639f51e0ec148e9cb78/test/cypress/integration/04-collective.test.js#L164 should be extended to include a YouTube video, to prevent future regressions.

**Comment by Betree** [comment]
We're not the only ones impacted by [this issue](https://github.com/basecamp/trix/issues/1178). Since it was published as a patch (not respecting SemVer) and included a security fix, we merged it without thinking twice.

Unfortunately, the new release did not include a workaround we could easily use so we had to [fork](https://github.com/opencollective/trix) the project. https://github.com/opencollective/opencollective-frontend/pull/10631 adapts the frontend to this custom fork and adds a few minor enhancements. It also adds an integration test to prevent similar regressions in the future.
