### ISSUE TITLE
Old tier should be inactive but not 404

### ISSUE THREAD

**Issue by wenzeslaus** [opencollective/opencollective#7571]
**Describe the bug**

A link to a tier which is not active anymore goes to "Oops! Page not found" page. There is no link to the project.

This is a big issue for us for two reasons:

1. A tier has a list of contributors to that tier, that's important for acknowledgement - that's how we acknowledge our sponsors for an event.
2. Old links are around in event announcements and reports, so when someone clicks that link with intention to send money, we want to make it easy to send the money using an active tier.

Inactive tiers links should show the tier with its details to acknowledge past contributors and link to the active tiers.

Even outside of the use case of tiers for events, I can see that we may change tiers in the future and we will have the problem of old tier-specific links and need for acknowledgement of a particular group.

If I recall correctly, old tiers were working couple months ago. I would really like the old tiers back to acknowledge the right event contributors.

**To Reproduce**

* Find a link to an old tier. Here is ours: https://opencollective.com/osgeo/projects/grass/contribute/community-meeting-2024-71849
* Result is "Oops! Page not found".

**Expected behavior**
Page with the tier details just like for active tiers and a link to all active tiers (_See active tiers_) instead of the Become/Join/Contribute button.

**Additional context**
I think this worked in the past.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Hi @wenzeslaus,

We haven't changed the way tiers work in this regard:
1. When an account gets archived or an event ends, the tier is marked as inactive. You cannot contribute to it anymore, but its visibility stays the same and the direct URL continues to work. Tiers are **not** deleted automatically.
2. Tiers can be manually deleted from the dashboard, using the "Delete" action. Deleted tiers lose their public pages.

![image](https://github.com/user-attachments/assets/e9814020-8181-4de3-bd05-9509e53df1fd)

In your case, one of the admins for the project deleted the tier on `2024-06-24`, so what you're describing is the expected behavior. We can restore the tier if it unblocks you.

You'll probably be interested in https://github.com/opencollective/opencollective/issues/3529, where a mechanism for archiving tiers has been requested.

**Comment by wenzeslaus** [comment]
> ...When an account gets archived or an event ends, the tier is marked as inactive.

Seems we need to learn about these events you mention!

> In your case, one of the admins for the project deleted the tier on `2024-06-24`, so what you're describing is the expected behavior.

We misunderstood the consequences here. Yes, archiving was what was likely the intention.  

> We can restore the tier if it unblocks you.

That would be awesome. Here are the two lost tiers:

* https://opencollective.com/osgeo/projects/grass/contribute/grass-community-meeting-prague-2023-55074
* https://opencollective.com/osgeo/projects/grass/contribute/community-meeting-2024-71849

If they can be made inactive (as in inactive event above), that would be even better.

> You'll probably be interested in #3529, where a mechanism for archiving tiers has been requested.

Thank you. I'll follow up there on that.

**Comment by Betree** [comment]
Done: 
![image](https://github.com/user-attachments/assets/7a0a3c28-feba-49c8-83fc-29d71933bb90) ![image](https://github.com/user-attachments/assets/8a239ede-2776-441a-8969-ad1277a5e1ca)
