### ISSUE TITLE
Expense is getting paid out multiple times

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#762]
Check expense id: 1737. It has 4 transactions in table.

**Comment by xdamman** [comment]
This is weird because:
1- It shouldn't let you pay an expense that is PAID
https://github.com/opencollective/opencollective-api/blob/master/server/graphql/mutations/expenses.js#L155
2- It shouldn't let you edit an expense (and reset its status) that is PAID
https://github.com/opencollective/opencollective-api/blob/master/server/graphql/mutations/expenses.js#L27

I'll keep investigating.

**Comment by xdamman** [comment]
Looks like it went from PAID back to APPROVED
![](https://cl.ly/2z0k1S181Z3z/Screen%20Shot%202017-12-18%20at%2012.10.28%20PM.png) by User 772 which is our host user.

@piamancini could it be that you approved an expense by email?
