### ISSUE TITLE
Editable OC

### ISSUE THREAD

**Issue by erickrico** [OpenCollective/OpenCollective#84]
Give the core contributors the capability to edit their OC  

### Editable sections
- Logo
- Collective name???
- Collective Core Mission
- Who we are
- URL to collective page/repo
- add or remove contributors + core contributors
- Why support us txt + (video/image)
- maybe edit backers 

Those are all the editable sections i came up with, feel free to add or comment (:

**Comment by piamancini** [comment]
adding: 'member since date'

**Comment by erickrico** [comment]
hey, quick update of the approach im taking, for text im going as close as possible to a wysiwyg editor, i still have to see the best solution to upload images/video although i don't think it will be hard, in the main time the most complex part i see is the "contributors" section but i feel confident i can deliver a good solution for it

### editable version default
![editable version-default](https://cloud.githubusercontent.com/assets/18429104/15341770/62381514-1c56-11e6-9077-918fc0863ffc.jpg)


### editable version hover on item
![editable version-on hover](https://cloud.githubusercontent.com/assets/18429104/15341780/70ff9dba-1c56-11e6-8523-930bb3ab0248.jpg)


### editable version all hover spots 
![editable version wysiwyg](https://cloud.githubusercontent.com/assets/18429104/15341795/834767aa-1c56-11e6-9164-dd28019081e3.jpg)

**Comment by erickrico** [comment]
ok, long post incoming O: , 

### editable version (full page)
![editable version](https://cloud.githubusercontent.com/assets/18429104/15590690/81e67c52-235e-11e6-9b43-cc211f80c632.jpg)

### update logo
![screenshot 2016-05-26 10 57 09](https://cloud.githubusercontent.com/assets/18429104/15590721/b5684c9a-235e-11e6-8d9f-b56121913c2c.png)
![screenshot 2016-05-26 10 57 19](https://cloud.githubusercontent.com/assets/18429104/15590723/b78274e2-235e-11e6-99a6-d8287ae7a19e.png)


### update mission
![screenshot 2016-05-26 11 00 16](https://cloud.githubusercontent.com/assets/18429104/15590739/c990008c-235e-11e6-9ea6-48c420dd91eb.png)
![screenshot 2016-05-26 11 07 11](https://cloud.githubusercontent.com/assets/18429104/15590740/c9911e54-235e-11e6-9450-4d616a07a5e1.png)


### update link
![screenshot 2016-05-26 11 11 22](https://cloud.githubusercontent.com/assets/18429104/15590773/f5f64492-235e-11e6-8bbf-d5d5b5087b50.png)
![screenshot 2016-05-26 12 41 36](https://cloud.githubusercontent.com/assets/18429104/15590772/f5f55df2-235e-11e6-83aa-b4876d3e223c.png)

### update long description
![screenshot 2016-05-26 12 46 27](https://cloud.githubusercontent.com/assets/18429104/15590793/0dabeace-235f-11e6-9cdb-d4489c62690e.png)
![screenshot 2016-05-26 12 32 24](https://cloud.githubusercontent.com/assets/18429104/15590797/132b823e-235f-11e6-83e6-bed3bee3a760.png)


### edit contributors / add contributors
![screenshot 2016-05-26 12 48 00](https://cloud.githubusercontent.com/assets/18429104/15590827/3f375ccc-235f-11e6-9e4d-e362c5b0f98c.png)
![screenshot 2016-05-26 12 49 35](https://cloud.githubusercontent.com/assets/18429104/15590828/3f3864aa-235f-11e6-9c65-769a17e83b9b.png)
![screenshot 2016-05-26 12 50 13](https://cloud.githubusercontent.com/assets/18429104/15590829/3f3e4bae-235f-11e6-8352-83b4800c372c.png)


### edit backers
![screenshot 2016-05-26 13 06 44](https://cloud.githubusercontent.com/assets/18429104/15590860/76a8293e-235f-11e6-92af-49f72b57f091.png)
![screenshot 2016-05-26 13 06 57](https://cloud.githubusercontent.com/assets/18429104/15590859/76a659e2-235f-11e6-81ab-44f1a75f7f61.png)

**Comment by piamancini** [comment]
looks great! i love doing everything from the public page. 
My two cents: 
I wouldn't allow for backer since, because we have a record of that, their first donation. I would only have editable 'the contributor since'

**Comment by carlosascari** [comment]
@xdamman @asood123 
I plan to pause working on the Editable Collective and focus on refactoring the PublicGroup container and related components.

PublicGroup is a bit bloated and should to be re-factored, however the reason I want to re-factor it now is to **reliably** re-use all components, in the Editable Collective feature.

I also plan to turn some non-components like the mission statement inside the` PublicGroupHero` component, into a component so I can place it freely when editing, in order to separate it from the `PublicGroupHero` component that will also be rendered so the User can feel familiar while editing their Collective.

This is to meet the design from Erick while at the same time reuse existing `PublicGroup` components so the Edit Preview resembles that of the User's collective. [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG)

>The idea is be able update `PublicGroup` and its related components, without having to also update the Editable Version of `PublicGroup`.

I will explain visually:

![Component Layout](https://my.mixtape.moe/xfycef.png)
*NOTE: On the right is a component that was selected to be edited*

`EditCollective` is the container, inside we reuse several `PublicGroup` `src/components/public_group` child components, upon clicking a editable component such as the logo or the mission statement, there is an overlay and on top is the same component that was clicked on, but as a editable version.

This looks similar to the overlay and input box when entering a new post on facebook:

![Similar Look](https://my.mixtape.moe/jccefz.png)

If you have any suggestions or doubts, let me know

**Comment by asood123** [comment]
`PublicGroup` is a mess. Refactoring is desperately needed. 👍  I hope you can do it in small chunks, instead of all at once. Easier to review, launch, test and revert if needed. And if people are working on stuff simultaneously in the same areas, less likely to create messy merges.

Another way to look at it, what's the minimum amount of refactoring you could do to get a single component editable launched? Once a single component is editable, others can copy that flow and split the effort of making everything editable. Maybe no refactoring is needed for a single component to be edited (like the description)?

In your example above, shouldn't `mission` be editable inline (WYSIWIG), instead of popping up an overlay?

**Comment by carlosascari** [comment]
I will be refactoring small chunks at a time, it will be very specific to only what is needed.

You are right, WYSIWIG was not the right term for it. It is not WYSIWIG, what I meant was that by reusing `PublicGroup` components, the user can edit and see how their Collective will look publicly, before saving any changes.

Not all components will become editable versions, only some like the `ContributorList`, as shown above, must have a edit mode. Other components like the logo found in `PublicGroupHero` will be edited with the `ImagePicker` component, however I'd still like it to be its own component (The logo element itself), so I can place it on top when a user hovers over it as shown above, since I cannot do that feasibly, from the `EditCollective` container while it is inside another component, `PublicGroupHero`, in this case.

There will be general purpose editors for:

- Images: `ImagePicker`
- Text: `CustomTextArea`
- Markdown: A markdown editor, will use `CustomTextArea` for now
- Backer/Contributor: The model shown above

They will all have a similar container design, that will lay on top of the overlay.

**Comment by asood123** [comment]
Add tasks/bugs that pop to this note.

- [ ] Bug: Top right never changes to "Save changes" button, so you can mistakenly exit without saving.
- [ ] Feature: Instead of a popup, how much work is it to allow inline editing of text components?
- [ ] Backend auth: enable updating collective for `MEMBERS` and `HOST` only. [@asood123]
- [ ] Frontend auth: get data from backend on whether the current user is allowed to edit and only show edit link in that case [@asood123]

- [ ] Frontend: add `Edit` link from the dropdown with the name of the collective. `Edit Yeoman Collective`. Let's do this last.

**Comment by piamancini** [comment]
re-open specific bugs/issues of this feature as required
