### ISSUE TITLE
large images (above limit) for avatars/background silently fail

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#906]
add an error message

**Comment by piamancini** [comment]
@xdamman I thought you fixed this? can we close?

**Comment by xdamman** [comment]
No I didn’t think this yet.

**Comment by piamancini** [comment]
This wasn't fix. Is no longer reported, but that doesn't mean users are not experiencing it and not reporting. Should be an easy fix for @Betree 
cc @znarf

**Comment by Betree** [comment]
This will be fixed by https://github.com/opencollective/opencollective-api/pull/1514 + https://github.com/opencollective/opencollective-frontend/pull/1032

Following changes have been made:
* Correctly display the error message. 
* Reset the `error` state field after a successful upload to make the error disappear 
* Increase request timeout to 2 minutes instead of 25 seconds for images upload

**Error message preview**

![Proof of work](https://user-images.githubusercontent.com/1556356/48343428-a5601d80-e672-11e8-8e81-8b3ca5a2ff20.png)
