### ISSUE TITLE
sponsor logos are repeated 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#946]
https://opencollective.com/babel#contributors 
safari and chrome 
same happens with the row below 
<img width="882" alt="screen shot 2018-03-05 at 6 42 33 pm" src="https://user-images.githubusercontent.com/3671070/37039784-4e004e00-2126-11e8-84c3-1b824ad5630c.png">

**Comment by piamancini** [comment]
Issue is that when sponsor does a new donation because cc expired we are creating a new row in member's table. logos are then duplicated. I am marking one as deletedAt but underlying issue still needs to be addressed.

**Comment by asood123** [comment]
This turns out to be hard to fix. Easiest approximation of the fix is to dedup on member table rows (in `allMembers` graphql query). I'm running into issues with Sequelize using distinct or groupings - looks like an [open bug on Sequelize] (https://github.com/sequelize/sequelize/issues/4310), will have to rewrite that entire section as a raw sql query. It's complex and needs more attention than a friday afternoon. 

Let's keep this open. I'll manually fix the issue in db for now.

**Comment by piamancini** [comment]
ok. yep, we can mark the rows as deleted at for the moment
