### ISSUE TITLE
move collective to europe

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#981]
Hello everyone,

Would you please move the collective https://opencollective.com/tenancy to Europe.

As per request on twitter: https://twitter.com/opencollect/status/978266762700640256

Thank you so much 🤗

**Comment by asood123** [comment]
Steps needed to accomplish this:

1. Calculate current net balance in Collective and Host Fees
- Balance: $176.19, HostFees: $25.25 (as of 3/30/18)
- Note that since host fees are small, we won't be moving them in this case - much easier from ledger perspective. 

2. Enter a manual transaction/Expense to remove the balance from collective (zero out the USD balance of collective

- [ ] File an expense to collective for $176.19.

3. Enter a manual transaction/donation in converted USD to Euros to restart collective in Euros

- [ ] Transfer money to european host: Euro 137.70
- [ ] Record amount in Euro from last step as a one-time donation (maybe use Add funds?)

4. Change host in Collective table
- [ ] Update collective currency
- [ ] Change host
- [ ] Update currency in tiers

**Comment by asood123** [comment]
One open issue remaining is that the old contributors are showing as giving in Euros (in their cards). It's not trivial to fix (our system assumes a single currency across a collective). I'd suggest that we cancel those subscriptions and reenter them in Euros (those original subscriptions in USD will likely be charged higher rates from payment providers if they are converted anyway).

**Comment by asood123** [comment]
(Hit closed by mistake)

**Comment by luceos** [comment]
Canceling would require me to get in touch with my backers personally to ask them to renew their pledges, I don't have their mail addresses I think.

**Comment by piamancini** [comment]
@luceos you can export all your members https://opencollective.com/:slug/edit#export

**Comment by luceos** [comment]
I just sent them an email, feel free to cancel them. If you're able to reenter them (?) please do @asood123 otherwise let me know when cancelled from your end so I can follow up.

**Comment by luceos** [comment]
@piamancini @asood123 sorry for tagging but this seems to get lost and this is not something I'd like to have delayed for too long as it might confuse backers..

🤗

**Comment by piamancini** [comment]
@luceos following up on our email thread today, the 3 subscriptions (made in USD to your collective) are still active. Do you want us to cancel them so they can re-do them for the correct tier?

**Comment by piamancini** [comment]
Otherwise, can I close this issue?

**Comment by luceos** [comment]
I've sent them one last email stating the situation and linking this issue. Go ahead.

**Comment by piamancini** [comment]
closing this as there are no outstanding tasks.
